rhs_weap_2a28 = {
    "muzzles": ["HE","AP"],
    # Class: CfgWeapons\rhs_weap_2a28\AP [Indent level: 1],
    "AP": {
        "aiDispersioncoefX": 7,
        "aiDispersioncoefY": 12,
        "canLock": 0,
        "ballisticsComputer": 0,
        "scope": 1,
        "cursor": "EmptyCursor",
        "displayName": "2A28",
        "reloadSound": ["A3|sounds_f|vehicles|armor|noises|reload_tank_cannon_3",3.16228,1,10],
        "magazines": ["rhs_mag_pg15v_24","rhs_mag_pg15v_20","rhs_mag_pg15v_12","rhs_mag_og15v_16","rhs_mag_og15v_20","rhs_mag_og15v_8"],
        "minRange": 1,
        "minRangeProbab": 0.1,
        "midRange": 765,
        "midRangeProbab": 1,
        "maxRange": 1300,
        "maxRangeProbab": 0.1,
        "reloadTime": 7,
        "magazineReloadTime": 5.5,
        "aiRateOfFire": 6,
        "aiRateOfFireDistance": 1000,
        "maxLeadSpeed": 100,
        # Class: CfgWeapons\rhs_weap_2a28_base\gunParticles [Indent level: 1],
        "gunParticles": {
            # Class: CfgWeapons\rhs_weap_2a28_base\gunParticles\Effect [Indent level: 2]
            "Effect": {
                "positionname": "Usti hlavne",
                "directionname": "Konec hlavne",
                "effectname": "CannonFired"
            }
        },
        # Class: CfgWeapons\rhs_weap_2a28_base\player [Indent level: 1],
        "player": {
            "dispersion": "0.00025*15",
            "sounds": ["StandardSound"],
            # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
                "soundBegin": ["begin1",1],
                "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
            },
            "soundContinuous": 0,
            "reloadTime": 6,
            "magazineReloadTime": 6,
            "autoReload": 1,
            "autoFire": 0,
            "aiRateOfFire": 1,
            "aiRateOfFireDistance": 10,
            "minRange": 0,
            "minRangeProbab": 0.01,
            "midRange": 1,
            "midRangeProbab": 0.01,
            "maxRange": 2,
            "maxRangeProbab": 0.01,
            "multiplier": 1,
            "burst": 1,
            "burstRangeMax": -1,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "useAction": 0,
            "useActionTitle": "",
            "showToPlayer": 1,
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "displayName": "Semi",
            "textureType": "semi",
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1,
            "aiRateOfFireDispersion": 1
        },
        # Class: CfgWeapons\rhs_weap_2a28_base\close [Indent level: 1],
        "close": {
            "dispersion": "0.00025*15",
            "showToPlayer": 0,
            "burst": 1,
            "burstRangeMax": 1,
            "aiRateOfFire": 6,
            "aiRateOfFireDispersion": 0.5,
            "aiRateOfFireDistance": 500,
            "minRange": 5,
            "minRangeProbab": 0.1,
            "midRange": 500,
            "midRangeProbab": 0.8,
            "maxRange": 1000,
            "maxRangeProbab": 0.85,
            "sounds": ["StandardSound"],
            # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
                "soundBegin": ["begin1",1],
                "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
            },
            "soundContinuous": 0,
            "reloadTime": 6,
            "magazineReloadTime": 6,
            "autoReload": 1,
            "autoFire": 0,
            "multiplier": 1,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "displayName": "Semi",
            "textureType": "semi",
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1
        },
        # Class: CfgWeapons\rhs_weap_2a28_base\short [Indent level: 1],
        "short": {
            "dispersion": "0.00025*15",
            "showToPlayer": 0,
            "burst": 1,
            "burstRangeMax": 1,
            "aiRateOfFire": 6,
            "aiRateOfFireDispersion": 1,
            "aiRateOfFireDistance": 1000,
            "minRange": 500,
            "minRangeProbab": 0.3,
            "midRange": 1000,
            "midRangeProbab": 0.85,
            "maxRange": 1500,
            "maxRangeProbab": 0.85,
            "sounds": ["StandardSound"],
            # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
                "soundBegin": ["begin1",1],
                "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
            },
            "soundContinuous": 0,
            "reloadTime": 6,
            "magazineReloadTime": 6,
            "autoReload": 1,
            "autoFire": 0,
            "multiplier": 1,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "displayName": "Semi",
            "textureType": "semi",
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1
        },
        # Class: CfgWeapons\rhs_weap_2a28_base\medium [Indent level: 1],
        "medium": {
            "dispersion": "0.00025*15",
            "showToPlayer": 0,
            "burst": 1,
            "burstRangeMax": 1,
            "aiRateOfFire": 8,
            "aiRateOfFireDispersion": 4,
            "aiRateOfFireDistance": 1250,
            "minRange": 1000,
            "minRangeProbab": 0.6,
            "midRange": 1500,
            "midRangeProbab": 0.85,
            "maxRange": 2000,
            "maxRangeProbab": 0.8,
            "sounds": ["StandardSound"],
            # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
                "soundBegin": ["begin1",1],
                "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
            },
            "soundContinuous": 0,
            "reloadTime": 6,
            "magazineReloadTime": 6,
            "autoReload": 1,
            "autoFire": 0,
            "multiplier": 1,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "displayName": "Semi",
            "textureType": "semi",
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1
        },
        # Class: CfgWeapons\rhs_weap_2a28_base\far [Indent level: 1],
        "far": {
            "dispersion": "0.00025*15",
            "showToPlayer": 0,
            "burst": 1,
            "burstRangeMax": 1,
            "aiRateOfFire": 10,
            "aiRateOfFireDispersion": 8,
            "aiRateOfFireDistance": 1500,
            "minRange": 1500,
            "minRangeProbab": 0.75,
            "midRange": 2000,
            "midRangeProbab": 0.8,
            "maxRange": 3500,
            "maxRangeProbab": 0.05,
            "sounds": ["StandardSound"],
            # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
                "soundBegin": ["begin1",1],
                "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
            },
            "soundContinuous": 0,
            "reloadTime": 6,
            "magazineReloadTime": 6,
            "autoReload": 1,
            "autoFire": 0,
            "multiplier": 1,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "displayName": "Semi",
            "textureType": "semi",
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1
        },
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_2a28_base\StandardSound [Indent level: 1],
        "StandardSound": {
            "weaponSoundEffect": "DefaultRifle",
            "begin1": ["rhsafrf|addons|rhs_sounds|2a28|2a28_1",3.15,1,2700],
            "begin2": ["rhsafrf|addons|rhs_sounds|2a28|2a28_2",3.15,1,2700],
            "soundBegin": ["begin1",0.5,"begin2",0.5]
        },
        "cursorAim": "cannon",
        "showAimCursorInternal": 0,
        "nameSound": "cannon",
        "reloadMagazineSound": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|Cannon_120mm_Reload_01",2.51189,1,10],
        "autoReload": 1,
        "FCSMaxLeadSpeed": 25,
        "FCSZeroingDelay": 1,
        "autoFire": 0,
        "modes": ["player","topDown","close","short","medium","far"],
        # Class: CfgWeapons\cannon_120mm\TopDown [Indent level: 1],
        "TopDown": {
            "textureType": "topDown",
            "displayName": "Top-down",
            "minRange": 150,
            "minRangeProbab": 0.4,
            "midRange": 400,
            "midRangeProbab": 0.95,
            "maxRange": 8000,
            "maxRangeProbab": 0.95,
            "sounds": ["StandardSound"],
            # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
                "soundBegin": ["begin1",1],
                "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
            },
            "soundContinuous": 0,
            "reloadTime": 6,
            "magazineReloadTime": 6,
            "autoReload": 1,
            "autoFire": 0,
            "dispersion": 0.00057,
            "aiRateOfFire": 1,
            "aiRateOfFireDistance": 10,
            "multiplier": 1,
            "burst": 1,
            "burstRangeMax": -1,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "useAction": 0,
            "useActionTitle": "",
            "showToPlayer": 1,
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1,
            "aiRateOfFireDispersion": 1
        },
        "type": 65536,
        # Class: CfgWeapons\CannonCore\GunClouds [Indent level: 1],
        "GunClouds": {
        },
        "access": 3,
        "value": 2,
        "picture": "",
        "uiPicture": "",
        "ammo": "",
        "cursorSize": 1,
        "cursorAimOn": "",
        "laser": 0,
        "hiddenSelections": [],
        "hiddenSelectionsTextures": [],
        "hiddenUnderwaterSelections": [],
        "shownUnderwaterSelections": [],
        "hiddenUnderwaterSelectionsTextures": [],
        "simulation": "Weapon",
        "count": 0,
        "multiplier": 1,
        "burst": 1,
        "magazineReloadSwitchPhase": 1,
        "sound": ["",1,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": ["sound",1],
        "soundLoop": ["sound",1],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "soundBurst": 1,
        "drySound": ["",1,1],
        "zeroingSound": ["",1,1],
        "changeFiremodeSound": ["",1,1],
        "emptySound": ["",1,1],
        "soundBullet": ["emptySound",1],
        "initSpeed": 0,
        "irDistance": 0,
        "irDotIntensity": 0.001,
        "dispersion": 0.002,
        "lockAcquire": 1,
        "enableAttack": 1,
        "ffMagnitude": 0,
        "ffFrequency": 1,
        "ffCount": 1,
        "recoil": "empty",
        "recoilProne": "",
        "maxRecoilSway": 0.008,
        "swayDecaySpeed": 2,
        "model": "",
        "modelSpecial": "",
        "modelMagazine": "",
        "muzzlePos": "usti hlavne",
        "muzzleEnd": "konec hlavne",
        "irLaserPos": "laser pos",
        "irLaserEnd": "laser dir",
        "cartridgePos": "nabojnicestart",
        "cartridgeVel": "nabojniceend",
        "selectionFireAnim": "zasleh",
        "memoryPointCamera": "eye",
        "fireSpreadAngle": 3,
        "useModelOptics": 1,
        "opticsID": 0,
        "modelOptics": "",
        "opticsPPEffects": [],
        "opticsFlare": 1,
        "optics": 1,
        "forceOptics": 0,
        "useAsBinocular": 0,
        "opticsDisablePeripherialVision": 0.67,
        "opticsZoomMin": 0.25,
        "opticsZoomMax": 1.25,
        "opticsZoomInit": 0.75,
        "distanceZoomMin": 400,
        "distanceZoomMax": 400,
        "primary": 10,
        "showSwitchAction": 0,
        "showEmpty": 1,
        "showToPlayer": 1,
        "canShootInWater": 0,
        "aiRateOfFireDispersion": 0,
        "fireLightDuration": 0.05,
        "fireLightIntensity": 0.2,
        "fireLightDiffuse": [0.937,0.631,0.259],
        "fireLightAmbient": [0,0,0],
        # Class: CfgWeapons\Default\Eventhandlers [Indent level: 1],
        "Eventhandlers": {
        },
        "backgroundReload": 0,
        "reloadAction": "",
        "muzzles": ["this"],
        "useAction": 0,
        "useActionTitle": "",
        "canDrop": 1,
        "weaponLockDelay": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "weight": 0,
        "handAnim": [],
        "lockingTargetSound": ["",0.000316228,2],
        "lockedTargetSound": ["",0.000316228,6],
        "detectRange": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "fireAnims": [],
        # Class: CfgWeapons\Default\Library [Indent level: 1],
        "Library": {
            "libTextDesc": ""
        },
        "descriptionShort": "",
        # Class: CfgWeapons\Default\GunFire [Indent level: 1],
        "GunFire": {
            "access": 0,
            "cloudletDuration": 0.2,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletAlpha": 1,
            "cloudletGrowUp": 0.2,
            "cloudletFadeIn": 0.01,
            "cloudletFadeOut": 0.5,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "cloudletShape": "cloudletFire",
            "cloudletColor": [1,1,1,0],
            "cloudletDensityCoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourceSize": 0.5,
            "timeToLive": 0,
            "initT": 4500,
            "deltaT": -3000,
            # Class: CfgWeapons\Default\GunFire\Table [Indent level: 2],
            "Table": {
                # Class: CfgWeapons\Default\GunFire\Table\T0 [Indent level: 3]
                "T0": {
                    "maxT": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T1 [Indent level: 3],
                "T1": {
                    "maxT": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T2 [Indent level: 3],
                "T2": {
                    "maxT": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T3 [Indent level: 3],
                "T3": {
                    "maxT": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T4 [Indent level: 3],
                "T4": {
                    "maxT": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T5 [Indent level: 3],
                "T5": {
                    "maxT": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T6 [Indent level: 3],
                "T6": {
                    "maxT": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T7 [Indent level: 3],
                "T7": {
                    "maxT": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T8 [Indent level: 3],
                "T8": {
                    "maxT": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T9 [Indent level: 3],
                "T9": {
                    "maxT": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T10 [Indent level: 3],
                "T10": {
                    "maxT": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T11 [Indent level: 3],
                "T11": {
                    "maxT": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T12 [Indent level: 3],
                "T12": {
                    "maxT": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T13 [Indent level: 3],
                "T13": {
                    "maxT": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T14 [Indent level: 3],
                "T14": {
                    "maxT": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T15 [Indent level: 3],
                "T15": {
                    "maxT": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T16 [Indent level: 3],
                "T16": {
                    "maxT": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T17 [Indent level: 3],
                "T17": {
                    "maxT": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T18 [Indent level: 3],
                "T18": {
                    "maxT": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T19 [Indent level: 3],
                "T19": {
                    "maxT": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T20 [Indent level: 3],
                "T20": {
                    "maxT": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T21 [Indent level: 3],
                "T21": {
                    "maxT": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T22 [Indent level: 3],
                "T22": {
                    "maxT": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        "textureType": "default",
        "inertia": 0.5,
        "aimTransitionSpeed": 1
    },
    # Class: CfgWeapons\rhs_weap_2a28\HE [Indent level: 1],
    "HE": {
        "modes": ["close","short","medium","far"],
        "magazines": ["rhs_mag_og15v_16","rhs_mag_og15v_20","rhs_mag_og15v_8"],
        "aiDispersioncoefX": 7,
        "aiDispersioncoefY": 12,
        "canLock": 0,
        "ballisticsComputer": 0,
        "scope": 1,
        "cursor": "EmptyCursor",
        "displayName": "2A28",
        "reloadSound": ["A3|sounds_f|vehicles|armor|noises|reload_tank_cannon_3",3.16228,1,10],
        "minRange": 1,
        "minRangeProbab": 0.1,
        "midRange": 765,
        "midRangeProbab": 1,
        "maxRange": 1300,
        "maxRangeProbab": 0.1,
        "reloadTime": 7,
        "magazineReloadTime": 5.5,
        "aiRateOfFire": 6,
        "aiRateOfFireDistance": 1000,
        "maxLeadSpeed": 100,
        # Class: CfgWeapons\rhs_weap_2a28_base\gunParticles [Indent level: 1],
        "gunParticles": {
            # Class: CfgWeapons\rhs_weap_2a28_base\gunParticles\Effect [Indent level: 2]
            "Effect": {
                "positionname": "Usti hlavne",
                "directionname": "Konec hlavne",
                "effectname": "CannonFired"
            }
        },
        # Class: CfgWeapons\rhs_weap_2a28_base\player [Indent level: 1],
        "player": {
            "dispersion": "0.00025*15",
            "sounds": ["StandardSound"],
            # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
                "soundBegin": ["begin1",1],
                "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
            },
            "soundContinuous": 0,
            "reloadTime": 6,
            "magazineReloadTime": 6,
            "autoReload": 1,
            "autoFire": 0,
            "aiRateOfFire": 1,
            "aiRateOfFireDistance": 10,
            "minRange": 0,
            "minRangeProbab": 0.01,
            "midRange": 1,
            "midRangeProbab": 0.01,
            "maxRange": 2,
            "maxRangeProbab": 0.01,
            "multiplier": 1,
            "burst": 1,
            "burstRangeMax": -1,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "useAction": 0,
            "useActionTitle": "",
            "showToPlayer": 1,
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "displayName": "Semi",
            "textureType": "semi",
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1,
            "aiRateOfFireDispersion": 1
        },
        # Class: CfgWeapons\rhs_weap_2a28_base\close [Indent level: 1],
        "close": {
            "dispersion": "0.00025*15",
            "showToPlayer": 0,
            "burst": 1,
            "burstRangeMax": 1,
            "aiRateOfFire": 6,
            "aiRateOfFireDispersion": 0.5,
            "aiRateOfFireDistance": 500,
            "minRange": 5,
            "minRangeProbab": 0.1,
            "midRange": 500,
            "midRangeProbab": 0.8,
            "maxRange": 1000,
            "maxRangeProbab": 0.85,
            "sounds": ["StandardSound"],
            # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
                "soundBegin": ["begin1",1],
                "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
            },
            "soundContinuous": 0,
            "reloadTime": 6,
            "magazineReloadTime": 6,
            "autoReload": 1,
            "autoFire": 0,
            "multiplier": 1,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "displayName": "Semi",
            "textureType": "semi",
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1
        },
        # Class: CfgWeapons\rhs_weap_2a28_base\short [Indent level: 1],
        "short": {
            "dispersion": "0.00025*15",
            "showToPlayer": 0,
            "burst": 1,
            "burstRangeMax": 1,
            "aiRateOfFire": 6,
            "aiRateOfFireDispersion": 1,
            "aiRateOfFireDistance": 1000,
            "minRange": 500,
            "minRangeProbab": 0.3,
            "midRange": 1000,
            "midRangeProbab": 0.85,
            "maxRange": 1500,
            "maxRangeProbab": 0.85,
            "sounds": ["StandardSound"],
            # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
                "soundBegin": ["begin1",1],
                "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
            },
            "soundContinuous": 0,
            "reloadTime": 6,
            "magazineReloadTime": 6,
            "autoReload": 1,
            "autoFire": 0,
            "multiplier": 1,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "displayName": "Semi",
            "textureType": "semi",
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1
        },
        # Class: CfgWeapons\rhs_weap_2a28_base\medium [Indent level: 1],
        "medium": {
            "dispersion": "0.00025*15",
            "showToPlayer": 0,
            "burst": 1,
            "burstRangeMax": 1,
            "aiRateOfFire": 8,
            "aiRateOfFireDispersion": 4,
            "aiRateOfFireDistance": 1250,
            "minRange": 1000,
            "minRangeProbab": 0.6,
            "midRange": 1500,
            "midRangeProbab": 0.85,
            "maxRange": 2000,
            "maxRangeProbab": 0.8,
            "sounds": ["StandardSound"],
            # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
                "soundBegin": ["begin1",1],
                "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
            },
            "soundContinuous": 0,
            "reloadTime": 6,
            "magazineReloadTime": 6,
            "autoReload": 1,
            "autoFire": 0,
            "multiplier": 1,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "displayName": "Semi",
            "textureType": "semi",
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1
        },
        # Class: CfgWeapons\rhs_weap_2a28_base\far [Indent level: 1],
        "far": {
            "dispersion": "0.00025*15",
            "showToPlayer": 0,
            "burst": 1,
            "burstRangeMax": 1,
            "aiRateOfFire": 10,
            "aiRateOfFireDispersion": 8,
            "aiRateOfFireDistance": 1500,
            "minRange": 1500,
            "minRangeProbab": 0.75,
            "midRange": 2000,
            "midRangeProbab": 0.8,
            "maxRange": 3500,
            "maxRangeProbab": 0.05,
            "sounds": ["StandardSound"],
            # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
                "soundBegin": ["begin1",1],
                "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
            },
            "soundContinuous": 0,
            "reloadTime": 6,
            "magazineReloadTime": 6,
            "autoReload": 1,
            "autoFire": 0,
            "multiplier": 1,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "displayName": "Semi",
            "textureType": "semi",
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1
        },
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_2a28_base\StandardSound [Indent level: 1],
        "StandardSound": {
            "weaponSoundEffect": "DefaultRifle",
            "begin1": ["rhsafrf|addons|rhs_sounds|2a28|2a28_1",3.15,1,2700],
            "begin2": ["rhsafrf|addons|rhs_sounds|2a28|2a28_2",3.15,1,2700],
            "soundBegin": ["begin1",0.5,"begin2",0.5]
        },
        "cursorAim": "cannon",
        "showAimCursorInternal": 0,
        "nameSound": "cannon",
        "reloadMagazineSound": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|Cannon_120mm_Reload_01",2.51189,1,10],
        "autoReload": 1,
        "FCSMaxLeadSpeed": 25,
        "FCSZeroingDelay": 1,
        "autoFire": 0,
        # Class: CfgWeapons\cannon_120mm\TopDown [Indent level: 1],
        "TopDown": {
            "textureType": "topDown",
            "displayName": "Top-down",
            "minRange": 150,
            "minRangeProbab": 0.4,
            "midRange": 400,
            "midRangeProbab": 0.95,
            "maxRange": 8000,
            "maxRangeProbab": 0.95,
            "sounds": ["StandardSound"],
            # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
                "soundBegin": ["begin1",1],
                "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
            },
            "soundContinuous": 0,
            "reloadTime": 6,
            "magazineReloadTime": 6,
            "autoReload": 1,
            "autoFire": 0,
            "dispersion": 0.00057,
            "aiRateOfFire": 1,
            "aiRateOfFireDistance": 10,
            "multiplier": 1,
            "burst": 1,
            "burstRangeMax": -1,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "useAction": 0,
            "useActionTitle": "",
            "showToPlayer": 1,
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1,
            "aiRateOfFireDispersion": 1
        },
        "type": 65536,
        # Class: CfgWeapons\CannonCore\GunClouds [Indent level: 1],
        "GunClouds": {
        },
        "access": 3,
        "value": 2,
        "picture": "",
        "uiPicture": "",
        "ammo": "",
        "cursorSize": 1,
        "cursorAimOn": "",
        "laser": 0,
        "hiddenSelections": [],
        "hiddenSelectionsTextures": [],
        "hiddenUnderwaterSelections": [],
        "shownUnderwaterSelections": [],
        "hiddenUnderwaterSelectionsTextures": [],
        "simulation": "Weapon",
        "count": 0,
        "multiplier": 1,
        "burst": 1,
        "magazineReloadSwitchPhase": 1,
        "sound": ["",1,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": ["sound",1],
        "soundLoop": ["sound",1],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "soundBurst": 1,
        "drySound": ["",1,1],
        "zeroingSound": ["",1,1],
        "changeFiremodeSound": ["",1,1],
        "emptySound": ["",1,1],
        "soundBullet": ["emptySound",1],
        "initSpeed": 0,
        "irDistance": 0,
        "irDotIntensity": 0.001,
        "dispersion": 0.002,
        "lockAcquire": 1,
        "enableAttack": 1,
        "ffMagnitude": 0,
        "ffFrequency": 1,
        "ffCount": 1,
        "recoil": "empty",
        "recoilProne": "",
        "maxRecoilSway": 0.008,
        "swayDecaySpeed": 2,
        "model": "",
        "modelSpecial": "",
        "modelMagazine": "",
        "muzzlePos": "usti hlavne",
        "muzzleEnd": "konec hlavne",
        "irLaserPos": "laser pos",
        "irLaserEnd": "laser dir",
        "cartridgePos": "nabojnicestart",
        "cartridgeVel": "nabojniceend",
        "selectionFireAnim": "zasleh",
        "memoryPointCamera": "eye",
        "fireSpreadAngle": 3,
        "useModelOptics": 1,
        "opticsID": 0,
        "modelOptics": "",
        "opticsPPEffects": [],
        "opticsFlare": 1,
        "optics": 1,
        "forceOptics": 0,
        "useAsBinocular": 0,
        "opticsDisablePeripherialVision": 0.67,
        "opticsZoomMin": 0.25,
        "opticsZoomMax": 1.25,
        "opticsZoomInit": 0.75,
        "distanceZoomMin": 400,
        "distanceZoomMax": 400,
        "primary": 10,
        "showSwitchAction": 0,
        "showEmpty": 1,
        "showToPlayer": 1,
        "canShootInWater": 0,
        "aiRateOfFireDispersion": 0,
        "fireLightDuration": 0.05,
        "fireLightIntensity": 0.2,
        "fireLightDiffuse": [0.937,0.631,0.259],
        "fireLightAmbient": [0,0,0],
        # Class: CfgWeapons\Default\Eventhandlers [Indent level: 1],
        "Eventhandlers": {
        },
        "backgroundReload": 0,
        "reloadAction": "",
        "muzzles": ["this"],
        "useAction": 0,
        "useActionTitle": "",
        "canDrop": 1,
        "weaponLockDelay": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "weight": 0,
        "handAnim": [],
        "lockingTargetSound": ["",0.000316228,2],
        "lockedTargetSound": ["",0.000316228,6],
        "detectRange": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "fireAnims": [],
        # Class: CfgWeapons\Default\Library [Indent level: 1],
        "Library": {
            "libTextDesc": ""
        },
        "descriptionShort": "",
        # Class: CfgWeapons\Default\GunFire [Indent level: 1],
        "GunFire": {
            "access": 0,
            "cloudletDuration": 0.2,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletAlpha": 1,
            "cloudletGrowUp": 0.2,
            "cloudletFadeIn": 0.01,
            "cloudletFadeOut": 0.5,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "cloudletShape": "cloudletFire",
            "cloudletColor": [1,1,1,0],
            "cloudletDensityCoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourceSize": 0.5,
            "timeToLive": 0,
            "initT": 4500,
            "deltaT": -3000,
            # Class: CfgWeapons\Default\GunFire\Table [Indent level: 2],
            "Table": {
                # Class: CfgWeapons\Default\GunFire\Table\T0 [Indent level: 3]
                "T0": {
                    "maxT": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T1 [Indent level: 3],
                "T1": {
                    "maxT": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T2 [Indent level: 3],
                "T2": {
                    "maxT": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T3 [Indent level: 3],
                "T3": {
                    "maxT": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T4 [Indent level: 3],
                "T4": {
                    "maxT": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T5 [Indent level: 3],
                "T5": {
                    "maxT": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T6 [Indent level: 3],
                "T6": {
                    "maxT": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T7 [Indent level: 3],
                "T7": {
                    "maxT": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T8 [Indent level: 3],
                "T8": {
                    "maxT": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T9 [Indent level: 3],
                "T9": {
                    "maxT": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T10 [Indent level: 3],
                "T10": {
                    "maxT": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T11 [Indent level: 3],
                "T11": {
                    "maxT": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T12 [Indent level: 3],
                "T12": {
                    "maxT": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T13 [Indent level: 3],
                "T13": {
                    "maxT": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T14 [Indent level: 3],
                "T14": {
                    "maxT": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T15 [Indent level: 3],
                "T15": {
                    "maxT": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T16 [Indent level: 3],
                "T16": {
                    "maxT": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T17 [Indent level: 3],
                "T17": {
                    "maxT": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T18 [Indent level: 3],
                "T18": {
                    "maxT": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T19 [Indent level: 3],
                "T19": {
                    "maxT": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T20 [Indent level: 3],
                "T20": {
                    "maxT": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T21 [Indent level: 3],
                "T21": {
                    "maxT": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T22 [Indent level: 3],
                "T22": {
                    "maxT": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        "textureType": "default",
        "inertia": 0.5,
        "aimTransitionSpeed": 1
    },
    "aiDispersioncoefX": 7,
    "aiDispersioncoefY": 12,
    "canLock": 0,
    "ballisticsComputer": 0,
    "scope": 1,
    "cursor": "EmptyCursor",
    "displayName": "2A28",
    "reloadSound": ["A3|sounds_f|vehicles|armor|noises|reload_tank_cannon_3",3.16228,1,10],
    "magazines": ["rhs_mag_pg15v_24","rhs_mag_pg15v_20","rhs_mag_pg15v_12","rhs_mag_og15v_16","rhs_mag_og15v_20","rhs_mag_og15v_8"],
    "minRange": 1,
    "minRangeProbab": 0.1,
    "midRange": 765,
    "midRangeProbab": 1,
    "maxRange": 1300,
    "maxRangeProbab": 0.1,
    "reloadTime": 7,
    "magazineReloadTime": 5.5,
    "aiRateOfFire": 6,
    "aiRateOfFireDistance": 1000,
    "maxLeadSpeed": 100,
    # Class: CfgWeapons\rhs_weap_2a28_base\gunParticles [Indent level: 1],
    "gunParticles": {
        # Class: CfgWeapons\rhs_weap_2a28_base\gunParticles\Effect [Indent level: 2]
        "Effect": {
            "positionname": "Usti hlavne",
            "directionname": "Konec hlavne",
            "effectname": "CannonFired"
        }
    },
    # Class: CfgWeapons\rhs_weap_2a28_base\player [Indent level: 1],
    "player": {
        "dispersion": "0.00025*15",
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
            "soundBegin": ["begin1",1],
            "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
        },
        "soundContinuous": 0,
        "reloadTime": 6,
        "magazineReloadTime": 6,
        "autoReload": 1,
        "autoFire": 0,
        "aiRateOfFire": 1,
        "aiRateOfFireDistance": 10,
        "minRange": 0,
        "minRangeProbab": 0.01,
        "midRange": 1,
        "midRangeProbab": 0.01,
        "maxRange": 2,
        "maxRangeProbab": 0.01,
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "requiredOpticType": -1,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons\rhs_weap_2a28_base\close [Indent level: 1],
    "close": {
        "dispersion": "0.00025*15",
        "showToPlayer": 0,
        "burst": 1,
        "burstRangeMax": 1,
        "aiRateOfFire": 6,
        "aiRateOfFireDispersion": 0.5,
        "aiRateOfFireDistance": 500,
        "minRange": 5,
        "minRangeProbab": 0.1,
        "midRange": 500,
        "midRangeProbab": 0.8,
        "maxRange": 1000,
        "maxRangeProbab": 0.85,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
            "soundBegin": ["begin1",1],
            "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
        },
        "soundContinuous": 0,
        "reloadTime": 6,
        "magazineReloadTime": 6,
        "autoReload": 1,
        "autoFire": 0,
        "multiplier": 1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "requiredOpticType": -1
    },
    # Class: CfgWeapons\rhs_weap_2a28_base\short [Indent level: 1],
    "short": {
        "dispersion": "0.00025*15",
        "showToPlayer": 0,
        "burst": 1,
        "burstRangeMax": 1,
        "aiRateOfFire": 6,
        "aiRateOfFireDispersion": 1,
        "aiRateOfFireDistance": 1000,
        "minRange": 500,
        "minRangeProbab": 0.3,
        "midRange": 1000,
        "midRangeProbab": 0.85,
        "maxRange": 1500,
        "maxRangeProbab": 0.85,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
            "soundBegin": ["begin1",1],
            "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
        },
        "soundContinuous": 0,
        "reloadTime": 6,
        "magazineReloadTime": 6,
        "autoReload": 1,
        "autoFire": 0,
        "multiplier": 1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "requiredOpticType": -1
    },
    # Class: CfgWeapons\rhs_weap_2a28_base\medium [Indent level: 1],
    "medium": {
        "dispersion": "0.00025*15",
        "showToPlayer": 0,
        "burst": 1,
        "burstRangeMax": 1,
        "aiRateOfFire": 8,
        "aiRateOfFireDispersion": 4,
        "aiRateOfFireDistance": 1250,
        "minRange": 1000,
        "minRangeProbab": 0.6,
        "midRange": 1500,
        "midRangeProbab": 0.85,
        "maxRange": 2000,
        "maxRangeProbab": 0.8,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
            "soundBegin": ["begin1",1],
            "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
        },
        "soundContinuous": 0,
        "reloadTime": 6,
        "magazineReloadTime": 6,
        "autoReload": 1,
        "autoFire": 0,
        "multiplier": 1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "requiredOpticType": -1
    },
    # Class: CfgWeapons\rhs_weap_2a28_base\far [Indent level: 1],
    "far": {
        "dispersion": "0.00025*15",
        "showToPlayer": 0,
        "burst": 1,
        "burstRangeMax": 1,
        "aiRateOfFire": 10,
        "aiRateOfFireDispersion": 8,
        "aiRateOfFireDistance": 1500,
        "minRange": 1500,
        "minRangeProbab": 0.75,
        "midRange": 2000,
        "midRangeProbab": 0.8,
        "maxRange": 3500,
        "maxRangeProbab": 0.05,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
            "soundBegin": ["begin1",1],
            "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
        },
        "soundContinuous": 0,
        "reloadTime": 6,
        "magazineReloadTime": 6,
        "autoReload": 1,
        "autoFire": 0,
        "multiplier": 1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "requiredOpticType": -1
    },
    "sounds": ["StandardSound"],
    # Class: CfgWeapons\rhs_weap_2a28_base\StandardSound [Indent level: 1],
    "StandardSound": {
        "weaponSoundEffect": "DefaultRifle",
        "begin1": ["rhsafrf|addons|rhs_sounds|2a28|2a28_1",3.15,1,2700],
        "begin2": ["rhsafrf|addons|rhs_sounds|2a28|2a28_2",3.15,1,2700],
        "soundBegin": ["begin1",0.5,"begin2",0.5]
    },
    "cursorAim": "cannon",
    "showAimCursorInternal": 0,
    "nameSound": "cannon",
    "reloadMagazineSound": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|Cannon_120mm_Reload_01",2.51189,1,10],
    "autoReload": 1,
    "FCSMaxLeadSpeed": 25,
    "FCSZeroingDelay": 1,
    "autoFire": 0,
    "modes": ["player","topDown","close","short","medium","far"],
    # Class: CfgWeapons\cannon_120mm\TopDown [Indent level: 1],
    "TopDown": {
        "textureType": "topDown",
        "displayName": "Top-down",
        "minRange": 150,
        "minRangeProbab": 0.4,
        "midRange": 400,
        "midRangeProbab": 0.95,
        "maxRange": 8000,
        "maxRangeProbab": 0.95,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\cannon_120mm\player\StandardSound [Indent level: 2],
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|cannon_120mm|slammer_120mm_distant",3.16228,1,1500],
            "soundBegin": ["begin1",1],
            "SoundSetShot": ["Cannon120mm_Shot_SoundSet","Cannon120mm_Tail_SoundSet"]
        },
        "soundContinuous": 0,
        "reloadTime": 6,
        "magazineReloadTime": 6,
        "autoReload": 1,
        "autoFire": 0,
        "dispersion": 0.00057,
        "aiRateOfFire": 1,
        "aiRateOfFireDistance": 10,
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "requiredOpticType": -1,
        "aiRateOfFireDispersion": 1
    },
    "type": 65536,
    # Class: CfgWeapons\CannonCore\GunClouds [Indent level: 1],
    "GunClouds": {
    },
    "access": 3,
    "value": 2,
    "picture": "",
    "uiPicture": "",
    "ammo": "",
    "cursorSize": 1,
    "cursorAimOn": "",
    "laser": 0,
    "hiddenSelections": [],
    "hiddenSelectionsTextures": [],
    "hiddenUnderwaterSelections": [],
    "shownUnderwaterSelections": [],
    "hiddenUnderwaterSelectionsTextures": [],
    "simulation": "Weapon",
    "count": 0,
    "multiplier": 1,
    "burst": 1,
    "magazineReloadSwitchPhase": 1,
    "sound": ["",1,1],
    "soundBegin": ["sound",1],
    "soundBeginWater": ["sound",1],
    "soundClosure": ["sound",1],
    "soundEnd": ["sound",1],
    "soundLoop": ["sound",1],
    "soundContinuous": 0,
    "weaponSoundEffect": "",
    "soundBurst": 1,
    "drySound": ["",1,1],
    "zeroingSound": ["",1,1],
    "changeFiremodeSound": ["",1,1],
    "emptySound": ["",1,1],
    "soundBullet": ["emptySound",1],
    "initSpeed": 0,
    "irDistance": 0,
    "irDotIntensity": 0.001,
    "dispersion": 0.002,
    "lockAcquire": 1,
    "enableAttack": 1,
    "ffMagnitude": 0,
    "ffFrequency": 1,
    "ffCount": 1,
    "recoil": "empty",
    "recoilProne": "",
    "maxRecoilSway": 0.008,
    "swayDecaySpeed": 2,
    "model": "",
    "modelSpecial": "",
    "modelMagazine": "",
    "muzzlePos": "usti hlavne",
    "muzzleEnd": "konec hlavne",
    "irLaserPos": "laser pos",
    "irLaserEnd": "laser dir",
    "cartridgePos": "nabojnicestart",
    "cartridgeVel": "nabojniceend",
    "selectionFireAnim": "zasleh",
    "memoryPointCamera": "eye",
    "fireSpreadAngle": 3,
    "useModelOptics": 1,
    "opticsID": 0,
    "modelOptics": "",
    "opticsPPEffects": [],
    "opticsFlare": 1,
    "optics": 1,
    "forceOptics": 0,
    "useAsBinocular": 0,
    "opticsDisablePeripherialVision": 0.67,
    "opticsZoomMin": 0.25,
    "opticsZoomMax": 1.25,
    "opticsZoomInit": 0.75,
    "distanceZoomMin": 400,
    "distanceZoomMax": 400,
    "primary": 10,
    "showSwitchAction": 0,
    "showEmpty": 1,
    "showToPlayer": 1,
    "canShootInWater": 0,
    "aiRateOfFireDispersion": 0,
    "fireLightDuration": 0.05,
    "fireLightIntensity": 0.2,
    "fireLightDiffuse": [0.937,0.631,0.259],
    "fireLightAmbient": [0,0,0],
    # Class: CfgWeapons\Default\Eventhandlers [Indent level: 1],
    "Eventhandlers": {
    },
    "backgroundReload": 0,
    "reloadAction": "",
    "useAction": 0,
    "useActionTitle": "",
    "canDrop": 1,
    "weaponLockDelay": 0,
    "weaponLockSystem": 0,
    "cmImmunity": 1,
    "weight": 0,
    "handAnim": [],
    "lockingTargetSound": ["",0.000316228,2],
    "lockedTargetSound": ["",0.000316228,6],
    "detectRange": 0,
    "artilleryDispersion": 1,
    "artilleryCharge": 1,
    "fireAnims": [],
    # Class: CfgWeapons\Default\Library [Indent level: 1],
    "Library": {
        "libTextDesc": ""
    },
    "descriptionShort": "",
    # Class: CfgWeapons\Default\GunFire [Indent level: 1],
    "GunFire": {
        "access": 0,
        "cloudletDuration": 0.2,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 0.2,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 0.5,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletFire",
        "cloudletColor": [1,1,1,0],
        "cloudletDensityCoef": -1,
        "interval": -0.01,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 4500,
        "deltaT": -3000,
        # Class: CfgWeapons\Default\GunFire\Table [Indent level: 2],
        "Table": {
            # Class: CfgWeapons\Default\GunFire\Table\T0 [Indent level: 3]
            "T0": {
                "maxT": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T1 [Indent level: 3],
            "T1": {
                "maxT": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T2 [Indent level: 3],
            "T2": {
                "maxT": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T3 [Indent level: 3],
            "T3": {
                "maxT": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T4 [Indent level: 3],
            "T4": {
                "maxT": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T5 [Indent level: 3],
            "T5": {
                "maxT": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T6 [Indent level: 3],
            "T6": {
                "maxT": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T7 [Indent level: 3],
            "T7": {
                "maxT": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T8 [Indent level: 3],
            "T8": {
                "maxT": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T9 [Indent level: 3],
            "T9": {
                "maxT": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T10 [Indent level: 3],
            "T10": {
                "maxT": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T11 [Indent level: 3],
            "T11": {
                "maxT": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T12 [Indent level: 3],
            "T12": {
                "maxT": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T13 [Indent level: 3],
            "T13": {
                "maxT": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T14 [Indent level: 3],
            "T14": {
                "maxT": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T15 [Indent level: 3],
            "T15": {
                "maxT": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T16 [Indent level: 3],
            "T16": {
                "maxT": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T17 [Indent level: 3],
            "T17": {
                "maxT": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T18 [Indent level: 3],
            "T18": {
                "maxT": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T19 [Indent level: 3],
            "T19": {
                "maxT": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T20 [Indent level: 3],
            "T20": {
                "maxT": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T21 [Indent level: 3],
            "T21": {
                "maxT": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T22 [Indent level: 3],
            "T22": {
                "maxT": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    "textureType": "default",
    "inertia": 0.5,
    "aimTransitionSpeed": 1,
}