rhs_weap_gsh23l = {
    "initspeed": 715,
    "displayname": "GSh-23L",
    "magazines": ["rhs_mag_AM23_500","rhs_mag_upk23_ofz","rhs_mag_upk23_ofzt","rhs_mag_upk23_btz","rhs_mag_upk23_mixed","rhs_mag_upk23_ka52_ofz","rhs_mag_upk23_ka52_ofzt","rhs_mag_upk23_ka52_btz","rhs_mag_upk23_ka52_mixed"],
    "namesound": "cannon",
    "shotFromTurret": 0,
    "soundcontinuous": 1,
    "modes": ["manual","close","short","medium","far"],
    # Class: CfgWeapons\rhs_weap_gsh23l\manual [Indent level: 1],
    "manual": {
        "airateoffire": 0.5,
        "airateoffiredistance": 50,
        "burst": 4,
        "dispersion": 0.0035,
        "displayname": "GSh-23L",
        "maxrange": 3,
        "maxrangeprobab": 0.01,
        "midrange": 2,
        "midrangeprobab": 0.01,
        "minrange": 1,
        "minrangeprobab": 0.01,
        "multiplier": 1,
        "reloadtime": 0.01875,
        "autofire": 1,
        "flash": "gunfire",
        "flashSize": 0.5,
        "showtoplayer": 1,
        "sound": ["",10,1],
        "soundburst": 0,
        "soundcontinuous": 0,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_gsh30\manual\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_hmg_shot_soundset","jsrs_HMG_reverb_soundset"],
            "weaponSoundEffect": "DefaultRifle"
        },
        "soundEnd": ["sound",1],
        "textureType": "fullAuto",
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "burstRangeMax": -1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons\rhs_weap_gsh23l\close [Indent level: 1],
    "close": {
        "airateoffire": 0.001,
        "airateoffiredistance": 50,
        "burst": 1,
        "maxrange": 300,
        "maxrangeprobab": 0.04,
        "midrange": 100,
        "midrangeprobab": 0.58,
        "minrange": 0,
        "minrangeprobab": 0.5,
        "showtoplayer": 0,
        "dispersion": 0.0035,
        "displayname": "GSh-23L",
        "multiplier": 1,
        "reloadtime": 0.01875,
        "autofire": 1,
        "flash": "gunfire",
        "flashSize": 0.5,
        "sound": ["",10,1],
        "soundburst": 0,
        "soundcontinuous": 0,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_gsh30\manual\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_hmg_shot_soundset","jsrs_HMG_reverb_soundset"],
            "weaponSoundEffect": "DefaultRifle"
        },
        "soundEnd": ["sound",1],
        "textureType": "fullAuto",
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "burstRangeMax": -1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons\rhs_weap_gsh23l\short [Indent level: 1],
    "short": {
        "airateoffire": "2 + random 2",
        "airateoffiredistance": 300,
        "aiRateOfFireDispersion": 3,
        "burst": 10,
        "burstRangeMax": 15,
        "maxrange": 800,
        "midrange": 500,
        "minrange": 200,
        "maxrangeprobab": 0.04,
        "midrangeprobab": 0.58,
        "minrangeprobab": 0.5,
        "showtoplayer": 0,
        "dispersion": 0.0035,
        "displayname": "GSh-23L",
        "multiplier": 1,
        "reloadtime": 0.01875,
        "autofire": 1,
        "flash": "gunfire",
        "flashSize": 0.5,
        "sound": ["",10,1],
        "soundburst": 0,
        "soundcontinuous": 0,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_gsh30\manual\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_hmg_shot_soundset","jsrs_HMG_reverb_soundset"],
            "weaponSoundEffect": "DefaultRifle"
        },
        "soundEnd": ["sound",1],
        "textureType": "fullAuto",
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1
    },
    # Class: CfgWeapons\rhs_weap_gsh23l\medium [Indent level: 1],
    "medium": {
        "airateoffire": 3,
        "airateoffiredistance": 600,
        "aiRateOfFireDispersion": 3,
        "burst": 7,
        "burstRangeMax": 11,
        "maxrange": 1000,
        "midrange": 800,
        "minrange": 600,
        "maxrangeprobab": 0.04,
        "midrangeprobab": 0.58,
        "minrangeprobab": 0.5,
        "showtoplayer": 0,
        "dispersion": 0.0035,
        "displayname": "GSh-23L",
        "multiplier": 1,
        "reloadtime": 0.01875,
        "autofire": 1,
        "flash": "gunfire",
        "flashSize": 0.5,
        "sound": ["",10,1],
        "soundburst": 0,
        "soundcontinuous": 0,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_gsh30\manual\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_hmg_shot_soundset","jsrs_HMG_reverb_soundset"],
            "weaponSoundEffect": "DefaultRifle"
        },
        "soundEnd": ["sound",1],
        "textureType": "fullAuto",
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1
    },
    # Class: CfgWeapons\rhs_weap_gsh23l\far [Indent level: 1],
    "far": {
        "airateoffire": 4,
        "airateoffiredistance": 1000,
        "aiRateOfFireDispersion": 3,
        "burst": 4,
        "burstRangeMax": 9,
        "maxrange": 1250,
        "maxrangeprobab": 0.01,
        "midrange": 1050,
        "midrangeprobab": 0.4,
        "minrange": 850,
        "minrangeprobab": 0.05,
        "showtoplayer": 0,
        "dispersion": 0.0035,
        "displayname": "GSh-23L",
        "multiplier": 1,
        "reloadtime": 0.01875,
        "autofire": 1,
        "flash": "gunfire",
        "flashSize": 0.5,
        "sound": ["",10,1],
        "soundburst": 0,
        "soundcontinuous": 0,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_gsh30\manual\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_hmg_shot_soundset","jsrs_HMG_reverb_soundset"],
            "weaponSoundEffect": "DefaultRifle"
        },
        "soundEnd": ["sound",1],
        "textureType": "fullAuto",
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1
    },
    # Class: CfgWeapons\rhs_weap_gsh23l\gunParticles [Indent level: 1],
    "gunParticles": {
        # Class: CfgWeapons\rhs_weap_gsh23l\gunParticles\mg1 [Indent level: 2]
        "mg1": {
            "positionName": "chase01",
            "directionName": "chase01dir",
            "effectName": "MachineGun1"
        },
        # Class: CfgWeapons\rhs_weap_gsh23l\gunParticles\mg2 [Indent level: 2],
        "mg2": {
            "positionName": "chase03",
            "directionName": "chase03dir",
            "effectName": "MachineGun1"
        },
        # Class: CfgWeapons\rhs_weap_gsh23l\gunParticles\mg3 [Indent level: 2],
        "mg3": {
            "positionName": "chase03",
            "directionName": "chase03dir",
            "effectName": "MachineGun1"
        },
        # Class: CfgWeapons\rhs_weap_gsh23l\gunParticles\mg4 [Indent level: 2],
        "mg4": {
            "positionName": "chase04",
            "directionName": "chase04dir",
            "effectName": "MachineGun1"
        }
    },
    "scope": 2,
    "canlock": 2,
    "cursor": "mg",
    "cursoraim": "EmptyCursor",
    "cursorsize": 0,
    "muzzles": ["this"],
    "ballisticsComputer": 8,
    "flash": "gunfire",
    "flashSize": 0.5,
    # Class: CfgWeapons\rhs_weap_gsh30\manual_low [Indent level: 1],
    "manual_low": {
        "reloadtime": 0.2,
        "textureType": "semi",
        "burst": 0,
        "airateoffire": 0.5,
        "airateoffiredistance": 50,
        "autofire": 1,
        "dispersion": 0.006,
        "displayname": "GSh-30-2K",
        "maxrange": 3,
        "maxrangeprobab": 0.01,
        "midrange": 2,
        "midrangeprobab": 0.01,
        "minrange": 1,
        "minrangeprobab": 0.01,
        "multiplier": 1,
        "flash": "gunfire",
        "flashSize": 0.5,
        "showtoplayer": 1,
        "sound": ["",10,1],
        "soundburst": 0,
        "soundcontinuous": 0,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_gsh30\manual\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_hmg_shot_soundset","jsrs_HMG_reverb_soundset"],
            "weaponSoundEffect": "DefaultRifle"
        },
        "soundEnd": ["sound",1],
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "burstRangeMax": -1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons\gatling_30mm\HE [Indent level: 1],
    "HE": {
        "magazines": ["250Rnd_30mm_HE_shells","250Rnd_30mm_HE_shells_Tracer_Red","250Rnd_30mm_HE_shells_Tracer_Green"],
        # Class: CfgWeapons\gatling_30mm\HE\LowROF [Indent level: 2],
        "LowROF": {
            "dispersion": 0.0066,
            "burst": 5,
            "sounds": ["standardsound"],
            # Class: CfgWeapons\gatling_30mm_base\LowROF\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shot|autocannon_1|medium_distance.ogg",5,1,4000],
                "soundBegin": ["begin1",1]
            },
            "flash": "gunfire",
            "flashSize": 0.1,
            "recoil": "Empty",
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "ffCount": 6,
            "reloadTime": 0.08,
            "aiRateOfFire": 1,
            "aiRateOfFireDistance": 10,
            "minRange": 0,
            "minRangeProbab": 0.01,
            "midRange": 1,
            "midRangeProbab": 0.01,
            "maxRange": 2,
            "maxRangeProbab": 0.01,
            "soundcontinuous": 0,
            "displayName": "GSh-3-30",
            "sound": ["",10,1],
            "soundEnd": ["sound",1],
            "autoFire": 1,
            "textureType": "fullAuto",
            "recoilProne": "recoil_auto_primary_prone_3outof10",
            "aiDispersionCoefY": 3,
            "aiDispersionCoefX": 2,
            "soundBurst": 0,
            "multiplier": 1,
            "burstRangeMax": -1,
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "useAction": 0,
            "useActionTitle": "",
            "showToPlayer": 1,
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "requiredOpticType": -1,
            "aiRateOfFireDispersion": 1
        },
        "scope": 0,
        "nameSound": "cannon",
        "burst": 5,
        "reloadTime": 0.02,
        "autoFire": 1,
        "modes": ["LowROF","close","short","medium","far"],
        "shotFromTurret": 1,
        "cursor": "EmptyCursor",
        "cursorAim": "mg",
        "canLock": 0,
        "ballisticsComputer": "1 + 2 + 16",
        "FCSMaxLeadSpeed": 30.5556,
        "FCSZeroingDelay": 0.5,
        "maxZeroing": 2500,
        "aiDispersionCoefY": 0.5,
        "aiDispersionCoefX": 0.5,
        # Class: CfgWeapons\gatling_30mm_base\GunParticles [Indent level: 1],
        "GunParticles": {
            # Class: CfgWeapons\gatling_30mm_base\GunParticles\Effect [Indent level: 2]
            "Effect": {
                "effectName": "MachineGun2",
                "positionName": "Usti hlavne",
                "directionName": "Konec hlavne"
            }
        },
        # Class: CfgWeapons\gatling_30mm_base\close [Indent level: 1],
        "close": {
            "aiBurstTerminable": 1,
            "showToPlayer": 0,
            "burst": 16,
            "burstRangeMax": 37,
            "aiRateOfFire": 0.5,
            "aiRateOfFireDispersion": 1,
            "aiRateOfFireDistance": 50,
            "minRange": 0,
            "minRangeProbab": 0.1,
            "midRange": 50,
            "midRangeProbab": 0.65,
            "maxRange": 400,
            "maxRangeProbab": 0.75,
            "sounds": ["standardsound"],
            # Class: CfgWeapons\gatling_30mm_base\LowROF\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shot|autocannon_1|medium_distance.ogg",5,1,4000],
                "soundBegin": ["begin1",1]
            },
            "flash": "gunfire",
            "flashSize": 0.1,
            "recoil": "Empty",
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "ffCount": 6,
            "reloadTime": 0.08,
            "dispersion": 0.0044,
            "soundcontinuous": 0,
            "displayName": "GSh-3-30",
            "sound": ["",10,1],
            "soundEnd": ["sound",1],
            "autoFire": 1,
            "textureType": "fullAuto",
            "recoilProne": "recoil_auto_primary_prone_3outof10",
            "aiDispersionCoefY": 3,
            "aiDispersionCoefX": 2,
            "soundBurst": 0,
            "multiplier": 1,
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "requiredOpticType": -1
        },
        # Class: CfgWeapons\gatling_30mm_base
ear [Indent level: 1],
        "near": {
            "aiBurstTerminable": 1,
            "showToPlayer": 0,
            "burst": 16,
            "burstRangeMax": 37,
            "aiRateOfFire": 0.5,
            "aiRateOfFireDispersion": 1,
            "aiRateOfFireDistance": 50,
            "minRange": 0,
            "minRangeProbab": 0.1,
            "midRange": 50,
            "midRangeProbab": 0.65,
            "maxRange": 400,
            "maxRangeProbab": 0.75,
            "sounds": ["standardsound"],
            # Class: CfgWeapons\gatling_30mm_base\LowROF\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shot|autocannon_1|medium_distance.ogg",5,1,4000],
                "soundBegin": ["begin1",1]
            },
            "flash": "gunfire",
            "flashSize": 0.1,
            "recoil": "Empty",
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "ffCount": 6,
            "reloadTime": 0.08,
            "dispersion": 0.0044,
            "soundcontinuous": 0,
            "displayName": "GSh-3-30",
            "sound": ["",10,1],
            "soundEnd": ["sound",1],
            "autoFire": 1,
            "textureType": "fullAuto",
            "recoilProne": "recoil_auto_primary_prone_3outof10",
            "aiDispersionCoefY": 3,
            "aiDispersionCoefX": 2,
            "soundBurst": 0,
            "multiplier": 1,
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "requiredOpticType": -1
        },
        # Class: CfgWeapons\gatling_30mm_base\short [Indent level: 1],
        "short": {
            "aiBurstTerminable": 1,
            "showToPlayer": 0,
            "burst": 12,
            "burstRangeMax": 32,
            "aiRateOfFire": 1,
            "aiRateOfFireDispersion": 2,
            "aiRateOfFireDistance": 200,
            "minRange": 200,
            "minRangeProbab": 0.65,
            "midRange": 400,
            "midRangeProbab": 0.75,
            "maxRange": 1000,
            "maxRangeProbab": 0.7,
            "sounds": ["standardsound"],
            # Class: CfgWeapons\gatling_30mm_base\LowROF\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shot|autocannon_1|medium_distance.ogg",5,1,4000],
                "soundBegin": ["begin1",1]
            },
            "flash": "gunfire",
            "flashSize": 0.1,
            "recoil": "Empty",
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "ffCount": 6,
            "reloadTime": 0.08,
            "dispersion": 0.0044,
            "soundcontinuous": 0,
            "displayName": "GSh-3-30",
            "sound": ["",10,1],
            "soundEnd": ["sound",1],
            "autoFire": 1,
            "textureType": "fullAuto",
            "recoilProne": "recoil_auto_primary_prone_3outof10",
            "aiDispersionCoefY": 3,
            "aiDispersionCoefX": 2,
            "soundBurst": 0,
            "multiplier": 1,
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "requiredOpticType": -1
        },
        # Class: CfgWeapons\gatling_30mm_base\medium [Indent level: 1],
        "medium": {
            "aiBurstTerminable": 1,
            "showToPlayer": 0,
            "burst": 12,
            "burstRangeMax": 28,
            "aiRateOfFire": 2,
            "aiRateOfFireDispersion": 2,
            "aiRateOfFireDistance": 800,
            "minRange": 800,
            "minRangeProbab": 0.7,
            "midRange": 1400,
            "midRangeProbab": 0.4,
            "maxRange": 1800,
            "maxRangeProbab": 0.15,
            "sounds": ["standardsound"],
            # Class: CfgWeapons\gatling_30mm_base\LowROF\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shot|autocannon_1|medium_distance.ogg",5,1,4000],
                "soundBegin": ["begin1",1]
            },
            "flash": "gunfire",
            "flashSize": 0.1,
            "recoil": "Empty",
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "ffCount": 6,
            "reloadTime": 0.08,
            "dispersion": 0.0044,
            "soundcontinuous": 0,
            "displayName": "GSh-3-30",
            "sound": ["",10,1],
            "soundEnd": ["sound",1],
            "autoFire": 1,
            "textureType": "fullAuto",
            "recoilProne": "recoil_auto_primary_prone_3outof10",
            "aiDispersionCoefY": 3,
            "aiDispersionCoefX": 2,
            "soundBurst": 0,
            "multiplier": 1,
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "requiredOpticType": -1
        },
        # Class: CfgWeapons\gatling_30mm_base\far [Indent level: 1],
        "far": {
            "aiBurstTerminable": 1,
            "showToPlayer": 0,
            "burst": 9,
            "burstRangeMax": 20,
            "aiRateOfFire": 4,
            "aiRateOfFireDispersion": 4,
            "aiRateOfFireDistance": 1400,
            "minRange": 1400,
            "minRangeProbab": 0.5,
            "midRange": 1800,
            "midRangeProbab": 0.15,
            "maxRange": 2500,
            "maxRangeProbab": 0.05,
            "sounds": ["standardsound"],
            # Class: CfgWeapons\gatling_30mm_base\LowROF\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shot|autocannon_1|medium_distance.ogg",5,1,4000],
                "soundBegin": ["begin1",1]
            },
            "flash": "gunfire",
            "flashSize": 0.1,
            "recoil": "Empty",
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "ffCount": 6,
            "reloadTime": 0.08,
            "dispersion": 0.0044,
            "soundcontinuous": 0,
            "displayName": "GSh-3-30",
            "sound": ["",10,1],
            "soundEnd": ["sound",1],
            "autoFire": 1,
            "textureType": "fullAuto",
            "recoilProne": "recoil_auto_primary_prone_3outof10",
            "aiDispersionCoefY": 3,
            "aiDispersionCoefX": 2,
            "soundBurst": 0,
            "multiplier": 1,
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "requiredOpticType": -1
        },
        "displayName": "GSh-3-30",
        "type": 65536,
        # Class: CfgWeapons\CannonCore\GunClouds [Indent level: 1],
        "GunClouds": {
        },
        "access": 3,
        "value": 2,
        "picture": "",
        "uiPicture": "",
        "ammo": "",
        "cursorSize": 1,
        "showAimCursorInternal": 1,
        "cursorAimOn": "",
        "laser": 0,
        "hiddenSelections": [],
        "hiddenSelectionsTextures": [],
        "hiddenUnderwaterSelections": [],
        "shownUnderwaterSelections": [],
        "hiddenUnderwaterSelectionsTextures": [],
        "simulation": "Weapon",
        "count": 0,
        "multiplier": 1,
        "magazineReloadTime": 0,
        "magazineReloadSwitchPhase": 1,
        "sound": ["",1,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": ["sound",1],
        "soundLoop": ["sound",1],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "soundBurst": 1,
        "drySound": ["",1,1],
        "zeroingSound": ["",1,1],
        "reloadSound": ["",1,1],
        "changeFiremodeSound": ["",1,1],
        "reloadMagazineSound": ["",1,1],
        "emptySound": ["",1,1],
        "soundBullet": ["emptySound",1],
        "initSpeed": 0,
        "irDistance": 0,
        "irDotIntensity": 0.001,
        "dispersion": 0.002,
        "lockAcquire": 1,
        "enableAttack": 1,
        "ffMagnitude": 0,
        "ffFrequency": 1,
        "ffCount": 1,
        "recoil": "empty",
        "recoilProne": "",
        "maxRecoilSway": 0.008,
        "swayDecaySpeed": 2,
        "model": "",
        "modelSpecial": "",
        "modelMagazine": "",
        "muzzlePos": "usti hlavne",
        "muzzleEnd": "konec hlavne",
        "irLaserPos": "laser pos",
        "irLaserEnd": "laser dir",
        "cartridgePos": "nabojnicestart",
        "cartridgeVel": "nabojniceend",
        "selectionFireAnim": "zasleh",
        "memoryPointCamera": "eye",
        "fireSpreadAngle": 3,
        "useModelOptics": 1,
        "opticsID": 0,
        "modelOptics": "",
        "opticsPPEffects": [],
        "opticsFlare": 1,
        "optics": 1,
        "forceOptics": 0,
        "useAsBinocular": 0,
        "opticsDisablePeripherialVision": 0.67,
        "opticsZoomMin": 0.25,
        "opticsZoomMax": 1.25,
        "opticsZoomInit": 0.75,
        "distanceZoomMin": 400,
        "distanceZoomMax": 400,
        "primary": 10,
        "showSwitchAction": 0,
        "showEmpty": 1,
        "autoReload": 1,
        "showToPlayer": 1,
        "canShootInWater": 0,
        "aiRateOfFire": 5,
        "aiRateOfFireDistance": 500,
        "aiRateOfFireDispersion": 0,
        "fireLightDuration": 0.05,
        "fireLightIntensity": 0.2,
        "fireLightDiffuse": [0.937,0.631,0.259],
        "fireLightAmbient": [0,0,0],
        # Class: CfgWeapons\Default\Eventhandlers [Indent level: 1],
        "Eventhandlers": {
        },
        "backgroundReload": 0,
        "reloadAction": "",
        "muzzles": ["this"],
        "useAction": 0,
        "useActionTitle": "",
        "canDrop": 1,
        "weaponLockDelay": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "weight": 0,
        "minRange": 1,
        "minRangeProbab": 0.3,
        "midRange": 150,
        "midRangeProbab": 0.58,
        "maxRange": 500,
        "maxRangeProbab": 0.04,
        "handAnim": [],
        "lockingTargetSound": ["",0.000316228,2],
        "lockedTargetSound": ["",0.000316228,6],
        "detectRange": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "fireAnims": [],
        # Class: CfgWeapons\Default\Library [Indent level: 1],
        "Library": {
            "libTextDesc": ""
        },
        "descriptionShort": "",
        # Class: CfgWeapons\Default\GunFire [Indent level: 1],
        "GunFire": {
            "access": 0,
            "cloudletDuration": 0.2,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletAlpha": 1,
            "cloudletGrowUp": 0.2,
            "cloudletFadeIn": 0.01,
            "cloudletFadeOut": 0.5,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "cloudletShape": "cloudletFire",
            "cloudletColor": [1,1,1,0],
            "cloudletDensityCoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourceSize": 0.5,
            "timeToLive": 0,
            "initT": 4500,
            "deltaT": -3000,
            # Class: CfgWeapons\Default\GunFire\Table [Indent level: 2],
            "Table": {
                # Class: CfgWeapons\Default\GunFire\Table\T0 [Indent level: 3]
                "T0": {
                    "maxT": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T1 [Indent level: 3],
                "T1": {
                    "maxT": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T2 [Indent level: 3],
                "T2": {
                    "maxT": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T3 [Indent level: 3],
                "T3": {
                    "maxT": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T4 [Indent level: 3],
                "T4": {
                    "maxT": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T5 [Indent level: 3],
                "T5": {
                    "maxT": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T6 [Indent level: 3],
                "T6": {
                    "maxT": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T7 [Indent level: 3],
                "T7": {
                    "maxT": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T8 [Indent level: 3],
                "T8": {
                    "maxT": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T9 [Indent level: 3],
                "T9": {
                    "maxT": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T10 [Indent level: 3],
                "T10": {
                    "maxT": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T11 [Indent level: 3],
                "T11": {
                    "maxT": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T12 [Indent level: 3],
                "T12": {
                    "maxT": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T13 [Indent level: 3],
                "T13": {
                    "maxT": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T14 [Indent level: 3],
                "T14": {
                    "maxT": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T15 [Indent level: 3],
                "T15": {
                    "maxT": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T16 [Indent level: 3],
                "T16": {
                    "maxT": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T17 [Indent level: 3],
                "T17": {
                    "maxT": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T18 [Indent level: 3],
                "T18": {
                    "maxT": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T19 [Indent level: 3],
                "T19": {
                    "maxT": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T20 [Indent level: 3],
                "T20": {
                    "maxT": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T21 [Indent level: 3],
                "T21": {
                    "maxT": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T22 [Indent level: 3],
                "T22": {
                    "maxT": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        "textureType": "default",
        "inertia": 0.5,
        "aimTransitionSpeed": 1
    },
    # Class: CfgWeapons\gatling_30mm\AP [Indent level: 1],
    "AP": {
        "magazines": ["250Rnd_30mm_APDS_shells","250Rnd_30mm_APDS_shells_Tracer_Red","250Rnd_30mm_APDS_shells_Tracer_Green","250Rnd_30mm_APDS_shells_Tracer_Yellow"],
        "scope": 0,
        "nameSound": "cannon",
        "burst": 5,
        "reloadTime": 0.02,
        "autoFire": 1,
        "modes": ["LowROF","close","short","medium","far"],
        "shotFromTurret": 1,
        "cursor": "EmptyCursor",
        "cursorAim": "mg",
        "canLock": 0,
        "ballisticsComputer": "1 + 2 + 16",
        "FCSMaxLeadSpeed": 30.5556,
        "FCSZeroingDelay": 0.5,
        "maxZeroing": 2500,
        "aiDispersionCoefY": 0.5,
        "aiDispersionCoefX": 0.5,
        # Class: CfgWeapons\gatling_30mm_base\GunParticles [Indent level: 1],
        "GunParticles": {
            # Class: CfgWeapons\gatling_30mm_base\GunParticles\Effect [Indent level: 2]
            "Effect": {
                "effectName": "MachineGun2",
                "positionName": "Usti hlavne",
                "directionName": "Konec hlavne"
            }
        },
        # Class: CfgWeapons\gatling_30mm_base\LowROF [Indent level: 1],
        "LowROF": {
            "burst": 5,
            "sounds": ["standardsound"],
            # Class: CfgWeapons\gatling_30mm_base\LowROF\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shot|autocannon_1|medium_distance.ogg",5,1,4000],
                "soundBegin": ["begin1",1]
            },
            "flash": "gunfire",
            "flashSize": 0.1,
            "recoil": "Empty",
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "ffCount": 6,
            "reloadTime": 0.08,
            "dispersion": 0.0044,
            "aiRateOfFire": 1,
            "aiRateOfFireDistance": 10,
            "minRange": 0,
            "minRangeProbab": 0.01,
            "midRange": 1,
            "midRangeProbab": 0.01,
            "maxRange": 2,
            "maxRangeProbab": 0.01,
            "soundcontinuous": 0,
            "displayName": "GSh-3-30",
            "sound": ["",10,1],
            "soundEnd": ["sound",1],
            "autoFire": 1,
            "textureType": "fullAuto",
            "recoilProne": "recoil_auto_primary_prone_3outof10",
            "aiDispersionCoefY": 3,
            "aiDispersionCoefX": 2,
            "soundBurst": 0,
            "multiplier": 1,
            "burstRangeMax": -1,
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "useAction": 0,
            "useActionTitle": "",
            "showToPlayer": 1,
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "requiredOpticType": -1,
            "aiRateOfFireDispersion": 1
        },
        # Class: CfgWeapons\gatling_30mm_base\close [Indent level: 1],
        "close": {
            "aiBurstTerminable": 1,
            "showToPlayer": 0,
            "burst": 16,
            "burstRangeMax": 37,
            "aiRateOfFire": 0.5,
            "aiRateOfFireDispersion": 1,
            "aiRateOfFireDistance": 50,
            "minRange": 0,
            "minRangeProbab": 0.1,
            "midRange": 50,
            "midRangeProbab": 0.65,
            "maxRange": 400,
            "maxRangeProbab": 0.75,
            "sounds": ["standardsound"],
            # Class: CfgWeapons\gatling_30mm_base\LowROF\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shot|autocannon_1|medium_distance.ogg",5,1,4000],
                "soundBegin": ["begin1",1]
            },
            "flash": "gunfire",
            "flashSize": 0.1,
            "recoil": "Empty",
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "ffCount": 6,
            "reloadTime": 0.08,
            "dispersion": 0.0044,
            "soundcontinuous": 0,
            "displayName": "GSh-3-30",
            "sound": ["",10,1],
            "soundEnd": ["sound",1],
            "autoFire": 1,
            "textureType": "fullAuto",
            "recoilProne": "recoil_auto_primary_prone_3outof10",
            "aiDispersionCoefY": 3,
            "aiDispersionCoefX": 2,
            "soundBurst": 0,
            "multiplier": 1,
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "requiredOpticType": -1
        },
        # Class: CfgWeapons\gatling_30mm_base
ear [Indent level: 1],
        "near": {
            "aiBurstTerminable": 1,
            "showToPlayer": 0,
            "burst": 16,
            "burstRangeMax": 37,
            "aiRateOfFire": 0.5,
            "aiRateOfFireDispersion": 1,
            "aiRateOfFireDistance": 50,
            "minRange": 0,
            "minRangeProbab": 0.1,
            "midRange": 50,
            "midRangeProbab": 0.65,
            "maxRange": 400,
            "maxRangeProbab": 0.75,
            "sounds": ["standardsound"],
            # Class: CfgWeapons\gatling_30mm_base\LowROF\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shot|autocannon_1|medium_distance.ogg",5,1,4000],
                "soundBegin": ["begin1",1]
            },
            "flash": "gunfire",
            "flashSize": 0.1,
            "recoil": "Empty",
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "ffCount": 6,
            "reloadTime": 0.08,
            "dispersion": 0.0044,
            "soundcontinuous": 0,
            "displayName": "GSh-3-30",
            "sound": ["",10,1],
            "soundEnd": ["sound",1],
            "autoFire": 1,
            "textureType": "fullAuto",
            "recoilProne": "recoil_auto_primary_prone_3outof10",
            "aiDispersionCoefY": 3,
            "aiDispersionCoefX": 2,
            "soundBurst": 0,
            "multiplier": 1,
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "requiredOpticType": -1
        },
        # Class: CfgWeapons\gatling_30mm_base\short [Indent level: 1],
        "short": {
            "aiBurstTerminable": 1,
            "showToPlayer": 0,
            "burst": 12,
            "burstRangeMax": 32,
            "aiRateOfFire": 1,
            "aiRateOfFireDispersion": 2,
            "aiRateOfFireDistance": 200,
            "minRange": 200,
            "minRangeProbab": 0.65,
            "midRange": 400,
            "midRangeProbab": 0.75,
            "maxRange": 1000,
            "maxRangeProbab": 0.7,
            "sounds": ["standardsound"],
            # Class: CfgWeapons\gatling_30mm_base\LowROF\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shot|autocannon_1|medium_distance.ogg",5,1,4000],
                "soundBegin": ["begin1",1]
            },
            "flash": "gunfire",
            "flashSize": 0.1,
            "recoil": "Empty",
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "ffCount": 6,
            "reloadTime": 0.08,
            "dispersion": 0.0044,
            "soundcontinuous": 0,
            "displayName": "GSh-3-30",
            "sound": ["",10,1],
            "soundEnd": ["sound",1],
            "autoFire": 1,
            "textureType": "fullAuto",
            "recoilProne": "recoil_auto_primary_prone_3outof10",
            "aiDispersionCoefY": 3,
            "aiDispersionCoefX": 2,
            "soundBurst": 0,
            "multiplier": 1,
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "requiredOpticType": -1
        },
        # Class: CfgWeapons\gatling_30mm_base\medium [Indent level: 1],
        "medium": {
            "aiBurstTerminable": 1,
            "showToPlayer": 0,
            "burst": 12,
            "burstRangeMax": 28,
            "aiRateOfFire": 2,
            "aiRateOfFireDispersion": 2,
            "aiRateOfFireDistance": 800,
            "minRange": 800,
            "minRangeProbab": 0.7,
            "midRange": 1400,
            "midRangeProbab": 0.4,
            "maxRange": 1800,
            "maxRangeProbab": 0.15,
            "sounds": ["standardsound"],
            # Class: CfgWeapons\gatling_30mm_base\LowROF\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shot|autocannon_1|medium_distance.ogg",5,1,4000],
                "soundBegin": ["begin1",1]
            },
            "flash": "gunfire",
            "flashSize": 0.1,
            "recoil": "Empty",
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "ffCount": 6,
            "reloadTime": 0.08,
            "dispersion": 0.0044,
            "soundcontinuous": 0,
            "displayName": "GSh-3-30",
            "sound": ["",10,1],
            "soundEnd": ["sound",1],
            "autoFire": 1,
            "textureType": "fullAuto",
            "recoilProne": "recoil_auto_primary_prone_3outof10",
            "aiDispersionCoefY": 3,
            "aiDispersionCoefX": 2,
            "soundBurst": 0,
            "multiplier": 1,
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "requiredOpticType": -1
        },
        # Class: CfgWeapons\gatling_30mm_base\far [Indent level: 1],
        "far": {
            "aiBurstTerminable": 1,
            "showToPlayer": 0,
            "burst": 9,
            "burstRangeMax": 20,
            "aiRateOfFire": 4,
            "aiRateOfFireDispersion": 4,
            "aiRateOfFireDistance": 1400,
            "minRange": 1400,
            "minRangeProbab": 0.5,
            "midRange": 1800,
            "midRangeProbab": 0.15,
            "maxRange": 2500,
            "maxRangeProbab": 0.05,
            "sounds": ["standardsound"],
            # Class: CfgWeapons\gatling_30mm_base\LowROF\StandardSound [Indent level: 2],
            "StandardSound": {
                "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shot|autocannon_1|medium_distance.ogg",5,1,4000],
                "soundBegin": ["begin1",1]
            },
            "flash": "gunfire",
            "flashSize": 0.1,
            "recoil": "Empty",
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "ffCount": 6,
            "reloadTime": 0.08,
            "dispersion": 0.0044,
            "soundcontinuous": 0,
            "displayName": "GSh-3-30",
            "sound": ["",10,1],
            "soundEnd": ["sound",1],
            "autoFire": 1,
            "textureType": "fullAuto",
            "recoilProne": "recoil_auto_primary_prone_3outof10",
            "aiDispersionCoefY": 3,
            "aiDispersionCoefX": 2,
            "soundBurst": 0,
            "multiplier": 1,
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundLoop": [],
            "weaponSoundEffect": "",
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "requiredOpticType": -1
        },
        "displayName": "GSh-3-30",
        "type": 65536,
        # Class: CfgWeapons\CannonCore\GunClouds [Indent level: 1],
        "GunClouds": {
        },
        "access": 3,
        "value": 2,
        "picture": "",
        "uiPicture": "",
        "ammo": "",
        "cursorSize": 1,
        "showAimCursorInternal": 1,
        "cursorAimOn": "",
        "laser": 0,
        "hiddenSelections": [],
        "hiddenSelectionsTextures": [],
        "hiddenUnderwaterSelections": [],
        "shownUnderwaterSelections": [],
        "hiddenUnderwaterSelectionsTextures": [],
        "simulation": "Weapon",
        "count": 0,
        "multiplier": 1,
        "magazineReloadTime": 0,
        "magazineReloadSwitchPhase": 1,
        "sound": ["",1,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": ["sound",1],
        "soundLoop": ["sound",1],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "soundBurst": 1,
        "drySound": ["",1,1],
        "zeroingSound": ["",1,1],
        "reloadSound": ["",1,1],
        "changeFiremodeSound": ["",1,1],
        "reloadMagazineSound": ["",1,1],
        "emptySound": ["",1,1],
        "soundBullet": ["emptySound",1],
        "initSpeed": 0,
        "irDistance": 0,
        "irDotIntensity": 0.001,
        "dispersion": 0.002,
        "lockAcquire": 1,
        "enableAttack": 1,
        "ffMagnitude": 0,
        "ffFrequency": 1,
        "ffCount": 1,
        "recoil": "empty",
        "recoilProne": "",
        "maxRecoilSway": 0.008,
        "swayDecaySpeed": 2,
        "model": "",
        "modelSpecial": "",
        "modelMagazine": "",
        "muzzlePos": "usti hlavne",
        "muzzleEnd": "konec hlavne",
        "irLaserPos": "laser pos",
        "irLaserEnd": "laser dir",
        "cartridgePos": "nabojnicestart",
        "cartridgeVel": "nabojniceend",
        "selectionFireAnim": "zasleh",
        "memoryPointCamera": "eye",
        "fireSpreadAngle": 3,
        "useModelOptics": 1,
        "opticsID": 0,
        "modelOptics": "",
        "opticsPPEffects": [],
        "opticsFlare": 1,
        "optics": 1,
        "forceOptics": 0,
        "useAsBinocular": 0,
        "opticsDisablePeripherialVision": 0.67,
        "opticsZoomMin": 0.25,
        "opticsZoomMax": 1.25,
        "opticsZoomInit": 0.75,
        "distanceZoomMin": 400,
        "distanceZoomMax": 400,
        "primary": 10,
        "showSwitchAction": 0,
        "showEmpty": 1,
        "autoReload": 1,
        "showToPlayer": 1,
        "canShootInWater": 0,
        "aiRateOfFire": 5,
        "aiRateOfFireDistance": 500,
        "aiRateOfFireDispersion": 0,
        "fireLightDuration": 0.05,
        "fireLightIntensity": 0.2,
        "fireLightDiffuse": [0.937,0.631,0.259],
        "fireLightAmbient": [0,0,0],
        # Class: CfgWeapons\Default\Eventhandlers [Indent level: 1],
        "Eventhandlers": {
        },
        "backgroundReload": 0,
        "reloadAction": "",
        "muzzles": ["this"],
        "useAction": 0,
        "useActionTitle": "",
        "canDrop": 1,
        "weaponLockDelay": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "weight": 0,
        "minRange": 1,
        "minRangeProbab": 0.3,
        "midRange": 150,
        "midRangeProbab": 0.58,
        "maxRange": 500,
        "maxRangeProbab": 0.04,
        "handAnim": [],
        "lockingTargetSound": ["",0.000316228,2],
        "lockedTargetSound": ["",0.000316228,6],
        "detectRange": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "fireAnims": [],
        # Class: CfgWeapons\Default\Library [Indent level: 1],
        "Library": {
            "libTextDesc": ""
        },
        "descriptionShort": "",
        # Class: CfgWeapons\Default\GunFire [Indent level: 1],
        "GunFire": {
            "access": 0,
            "cloudletDuration": 0.2,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletAlpha": 1,
            "cloudletGrowUp": 0.2,
            "cloudletFadeIn": 0.01,
            "cloudletFadeOut": 0.5,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "cloudletShape": "cloudletFire",
            "cloudletColor": [1,1,1,0],
            "cloudletDensityCoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourceSize": 0.5,
            "timeToLive": 0,
            "initT": 4500,
            "deltaT": -3000,
            # Class: CfgWeapons\Default\GunFire\Table [Indent level: 2],
            "Table": {
                # Class: CfgWeapons\Default\GunFire\Table\T0 [Indent level: 3]
                "T0": {
                    "maxT": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T1 [Indent level: 3],
                "T1": {
                    "maxT": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T2 [Indent level: 3],
                "T2": {
                    "maxT": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T3 [Indent level: 3],
                "T3": {
                    "maxT": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T4 [Indent level: 3],
                "T4": {
                    "maxT": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T5 [Indent level: 3],
                "T5": {
                    "maxT": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T6 [Indent level: 3],
                "T6": {
                    "maxT": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T7 [Indent level: 3],
                "T7": {
                    "maxT": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T8 [Indent level: 3],
                "T8": {
                    "maxT": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T9 [Indent level: 3],
                "T9": {
                    "maxT": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T10 [Indent level: 3],
                "T10": {
                    "maxT": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T11 [Indent level: 3],
                "T11": {
                    "maxT": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T12 [Indent level: 3],
                "T12": {
                    "maxT": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T13 [Indent level: 3],
                "T13": {
                    "maxT": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T14 [Indent level: 3],
                "T14": {
                    "maxT": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T15 [Indent level: 3],
                "T15": {
                    "maxT": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T16 [Indent level: 3],
                "T16": {
                    "maxT": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T17 [Indent level: 3],
                "T17": {
                    "maxT": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T18 [Indent level: 3],
                "T18": {
                    "maxT": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T19 [Indent level: 3],
                "T19": {
                    "maxT": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T20 [Indent level: 3],
                "T20": {
                    "maxT": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T21 [Indent level: 3],
                "T21": {
                    "maxT": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T22 [Indent level: 3],
                "T22": {
                    "maxT": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        "textureType": "default",
        "inertia": 0.5,
        "aimTransitionSpeed": 1
    },
    "burst": 5,
    "reloadTime": 0.02,
    "autoFire": 1,
    "FCSMaxLeadSpeed": 30.5556,
    "FCSZeroingDelay": 0.5,
    "maxZeroing": 2500,
    "aiDispersionCoefY": 0.5,
    "aiDispersionCoefX": 0.5,
    # Class: CfgWeapons\gatling_30mm_base\LowROF [Indent level: 1],
    "LowROF": {
        "burst": 5,
        "sounds": ["standardsound"],
        # Class: CfgWeapons\gatling_30mm_base\LowROF\StandardSound [Indent level: 2],
        "StandardSound": {
            "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shot|autocannon_1|medium_distance.ogg",5,1,4000],
            "soundBegin": ["begin1",1]
        },
        "flash": "gunfire",
        "flashSize": 0.1,
        "recoil": "Empty",
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "ffCount": 6,
        "reloadTime": 0.08,
        "dispersion": 0.0044,
        "aiRateOfFire": 1,
        "aiRateOfFireDistance": 10,
        "minRange": 0,
        "minRangeProbab": 0.01,
        "midRange": 1,
        "midRangeProbab": 0.01,
        "maxRange": 2,
        "maxRangeProbab": 0.01,
        "soundcontinuous": 0,
        "displayName": "GSh-3-30",
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "autoFire": 1,
        "textureType": "fullAuto",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "burstRangeMax": -1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons\gatling_30mm_base
ear [Indent level: 1],
    "near": {
        "aiBurstTerminable": 1,
        "showToPlayer": 0,
        "burst": 16,
        "burstRangeMax": 37,
        "aiRateOfFire": 0.5,
        "aiRateOfFireDispersion": 1,
        "aiRateOfFireDistance": 50,
        "minRange": 0,
        "minRangeProbab": 0.1,
        "midRange": 50,
        "midRangeProbab": 0.65,
        "maxRange": 400,
        "maxRangeProbab": 0.75,
        "sounds": ["standardsound"],
        # Class: CfgWeapons\gatling_30mm_base\LowROF\StandardSound [Indent level: 2],
        "StandardSound": {
            "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shot|autocannon_1|medium_distance.ogg",5,1,4000],
            "soundBegin": ["begin1",1]
        },
        "flash": "gunfire",
        "flashSize": 0.1,
        "recoil": "Empty",
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "ffCount": 6,
        "reloadTime": 0.08,
        "dispersion": 0.0044,
        "soundcontinuous": 0,
        "displayName": "GSh-3-30",
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "autoFire": 1,
        "textureType": "fullAuto",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1
    },
    "type": 65536,
    # Class: CfgWeapons\CannonCore\GunClouds [Indent level: 1],
    "GunClouds": {
    },
    "access": 3,
    "value": 2,
    "picture": "",
    "uiPicture": "",
    "ammo": "",
    "showAimCursorInternal": 1,
    "cursorAimOn": "",
    "laser": 0,
    "hiddenSelections": [],
    "hiddenSelectionsTextures": [],
    "hiddenUnderwaterSelections": [],
    "shownUnderwaterSelections": [],
    "hiddenUnderwaterSelectionsTextures": [],
    "simulation": "Weapon",
    "count": 0,
    "multiplier": 1,
    "magazineReloadTime": 0,
    "magazineReloadSwitchPhase": 1,
    "sound": ["",1,1],
    "soundBegin": ["sound",1],
    "soundBeginWater": ["sound",1],
    "soundClosure": ["sound",1],
    "soundEnd": ["sound",1],
    "soundLoop": ["sound",1],
    "weaponSoundEffect": "",
    "soundBurst": 1,
    "drySound": ["",1,1],
    "zeroingSound": ["",1,1],
    "reloadSound": ["",1,1],
    "changeFiremodeSound": ["",1,1],
    "reloadMagazineSound": ["",1,1],
    "emptySound": ["",1,1],
    "soundBullet": ["emptySound",1],
    "irDistance": 0,
    "irDotIntensity": 0.001,
    "dispersion": 0.002,
    "lockAcquire": 1,
    "enableAttack": 1,
    "ffMagnitude": 0,
    "ffFrequency": 1,
    "ffCount": 1,
    "recoil": "empty",
    "recoilProne": "",
    "maxRecoilSway": 0.008,
    "swayDecaySpeed": 2,
    "model": "",
    "modelSpecial": "",
    "modelMagazine": "",
    "muzzlePos": "usti hlavne",
    "muzzleEnd": "konec hlavne",
    "irLaserPos": "laser pos",
    "irLaserEnd": "laser dir",
    "cartridgePos": "nabojnicestart",
    "cartridgeVel": "nabojniceend",
    "selectionFireAnim": "zasleh",
    "memoryPointCamera": "eye",
    "fireSpreadAngle": 3,
    "useModelOptics": 1,
    "opticsID": 0,
    "modelOptics": "",
    "opticsPPEffects": [],
    "opticsFlare": 1,
    "optics": 1,
    "forceOptics": 0,
    "useAsBinocular": 0,
    "opticsDisablePeripherialVision": 0.67,
    "opticsZoomMin": 0.25,
    "opticsZoomMax": 1.25,
    "opticsZoomInit": 0.75,
    "distanceZoomMin": 400,
    "distanceZoomMax": 400,
    "primary": 10,
    "showSwitchAction": 0,
    "showEmpty": 1,
    "autoReload": 1,
    "showToPlayer": 1,
    "canShootInWater": 0,
    "aiRateOfFire": 5,
    "aiRateOfFireDistance": 500,
    "aiRateOfFireDispersion": 0,
    "fireLightDuration": 0.05,
    "fireLightIntensity": 0.2,
    "fireLightDiffuse": [0.937,0.631,0.259],
    "fireLightAmbient": [0,0,0],
    # Class: CfgWeapons\Default\Eventhandlers [Indent level: 1],
    "Eventhandlers": {
    },
    "backgroundReload": 0,
    "reloadAction": "",
    "useAction": 0,
    "useActionTitle": "",
    "canDrop": 1,
    "weaponLockDelay": 0,
    "weaponLockSystem": 0,
    "cmImmunity": 1,
    "weight": 0,
    "minRange": 1,
    "minRangeProbab": 0.3,
    "midRange": 150,
    "midRangeProbab": 0.58,
    "maxRange": 500,
    "maxRangeProbab": 0.04,
    "handAnim": [],
    "lockingTargetSound": ["",0.000316228,2],
    "lockedTargetSound": ["",0.000316228,6],
    "detectRange": 0,
    "artilleryDispersion": 1,
    "artilleryCharge": 1,
    "fireAnims": [],
    # Class: CfgWeapons\Default\Library [Indent level: 1],
    "Library": {
        "libTextDesc": ""
    },
    "descriptionShort": "",
    # Class: CfgWeapons\Default\GunFire [Indent level: 1],
    "GunFire": {
        "access": 0,
        "cloudletDuration": 0.2,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 0.2,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 0.5,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletFire",
        "cloudletColor": [1,1,1,0],
        "cloudletDensityCoef": -1,
        "interval": -0.01,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 4500,
        "deltaT": -3000,
        # Class: CfgWeapons\Default\GunFire\Table [Indent level: 2],
        "Table": {
            # Class: CfgWeapons\Default\GunFire\Table\T0 [Indent level: 3]
            "T0": {
                "maxT": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T1 [Indent level: 3],
            "T1": {
                "maxT": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T2 [Indent level: 3],
            "T2": {
                "maxT": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T3 [Indent level: 3],
            "T3": {
                "maxT": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T4 [Indent level: 3],
            "T4": {
                "maxT": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T5 [Indent level: 3],
            "T5": {
                "maxT": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T6 [Indent level: 3],
            "T6": {
                "maxT": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T7 [Indent level: 3],
            "T7": {
                "maxT": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T8 [Indent level: 3],
            "T8": {
                "maxT": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T9 [Indent level: 3],
            "T9": {
                "maxT": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T10 [Indent level: 3],
            "T10": {
                "maxT": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T11 [Indent level: 3],
            "T11": {
                "maxT": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T12 [Indent level: 3],
            "T12": {
                "maxT": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T13 [Indent level: 3],
            "T13": {
                "maxT": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T14 [Indent level: 3],
            "T14": {
                "maxT": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T15 [Indent level: 3],
            "T15": {
                "maxT": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T16 [Indent level: 3],
            "T16": {
                "maxT": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T17 [Indent level: 3],
            "T17": {
                "maxT": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T18 [Indent level: 3],
            "T18": {
                "maxT": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T19 [Indent level: 3],
            "T19": {
                "maxT": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T20 [Indent level: 3],
            "T20": {
                "maxT": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T21 [Indent level: 3],
            "T21": {
                "maxT": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T22 [Indent level: 3],
            "T22": {
                "maxT": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    "textureType": "default",
    "inertia": 0.5,
    "aimTransitionSpeed": 1,
}