rhs_weap_m1garand_sa43 = {
    "author": "Red Hammer Studios",
    "picture": "rhsgref|addons|rhsgref_inventoryicons|data|weapons|rhs_weap_m1garand_sa43_ca.paa",
    "scope": 2,
    "scopeCurator": 2,
    "dlc": "RHS_GREF",
    "displayName": "M1 Garand",
    "model": "rhsgref|addons|rhsgref_weapons2|m1garand|rhs_m1garand_sa43.p3d",
    # Class: CfgWeapons\rhs_weap_m1garand_sa43\WeaponSlotsInfo [Indent level: 1],
    "WeaponSlotsInfo": {
        "mass": 94.8,
        # Class: CfgWeapons\rhs_weap_m1garand_sa43\WeaponSlotsInfo\MuzzleSlot [Indent level: 2],
        "MuzzleSlot": {
        },
        # Class: CfgWeapons\rhs_weap_m1garand_sa43\WeaponSlotsInfo\CowsSlot [Indent level: 2],
        "CowsSlot": {
        },
        # Class: CfgWeapons\rhs_weap_m1garand_sa43\WeaponSlotsInfo\PointerSlot [Indent level: 2],
        "PointerSlot": {
        },
        # Class: CfgWeapons\rhs_weap_m1garand_sa43\WeaponSlotsInfo\UnderBarrelSlot [Indent level: 2],
        "UnderBarrelSlot": {
        },
        "allowedSlots": [901]
    },
    # Class: CfgWeapons\rhs_weap_m1garand_sa43\LinkedItems [Indent level: 1],
    "LinkedItems": {
        # Class: CfgWeapons\rhs_weap_m1garand_sa43\LinkedItems\LinkedItemsOptic [Indent level: 2]
        "LinkedItemsOptic": {
        },
        # Class: CfgWeapons\rhs_weap_m1garand_sa43\LinkedItems\LinkedItemsAcc [Indent level: 2],
        "LinkedItemsAcc": {
        }
    },
    "UiPicture": "A3|weapons_f|data|UI|icon_regular_CA.paa",
    # Class: CfgWeapons\rhs_weap_m1garand_sa43\ItemInfo [Indent level: 1],
    "ItemInfo": {
        "priority": 1,
        "RMBhint": "M1 Garand",
        "onHoverText": "M1 Garand"
    },
    "baseWeapon": "rhs_weap_m1garand_sa43",
    "magazines": ["rhsgref_8Rnd_762x63_M2B_M1rifle","rhsgref_8Rnd_762x63_Tracer_M1T_M1rifle"],
    "magazineWell": [],
    "magazineReloadSwitchPhase": 0.15,
    # Class: CfgWeapons\rhs_weap_M1garand_Base_F\Library [Indent level: 1],
    "Library": {
        "libTextDesc": ""
    },
    # Class: CfgWeapons\rhs_weap_M1garand_Base_F\SAFE [Indent level: 1],
    "SAFE": {
        "showToPlayer": 0,
        "magazines": [],
        "displayName": "SAFE",
        "descriptionShort": "SAFE",
        "modes": ["Safe"],
        "discreteDistance": [0],
        "discreteDistanceInitIndex": 0,
        "drySound": ["A3|Sounds_F|arsenal|weapons|Rifles|MX|dry_Mx",0.562341,1,10],
        "changeFiremodeSound": ["A3|sounds_f|weapons|closure|firemode_changer_2",0.551189,1,5],
        # Class: CfgWeapons\RHS_SAFE_BASE\Safe [Indent level: 1],
        "Safe": {
            "sounds": [],
            "displayName": "SAFE",
            "descriptionShort": "SAFE",
            "showToPlayer": 0,
            "minRange": 0,
            "minRangeProbab": 0.001,
            "midRange": 0.001,
            "midRangeProbab": 0.001,
            "maxRange": 0.001,
            "maxRangeProbab": 0.001,
            "multiplier": 1,
            "burst": 1,
            "burstRangeMax": -1,
            "dispersion": 0.0002,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "soundContinuous": 0,
            "weaponSoundEffect": "",
            "reloadTime": 0.1,
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "autoFire": 0,
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "textureType": "semi",
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1,
            "aiRateOfFire": 2,
            "aiRateOfFireDispersion": 1,
            "aiRateOfFireDistance": 500
        },
        "scope": 0,
        "weaponInfoType": "RscWeaponZeroing",
        "recoil": "recoil_default",
        "deployedPivot": "bipod",
        # Class: CfgWeapons\Rifle_Base_F\GunParticles [Indent level: 1],
        "GunParticles": {
            # Class: CfgWeapons\Rifle_Base_F\GunParticles\FirstEffect [Indent level: 2]
            "FirstEffect": {
                "effectName": "RifleAssaultCloud",
                "positionName": "Usti hlavne",
                "directionName": "Konec hlavne"
            }
        },
        # Class: CfgWeapons\Rifle_Base_F\Eventhandlers [Indent level: 1],
        "Eventhandlers": {
            # Class: CfgWeapons\Rifle_Base_F\Eventhandlers\GSM_popMagRifle [Indent level: 2]
            "GSM_popMagRifle": {
                "fired": "_this call GSM_fnc_detectReload"
            }
        },
        # Class: CfgWeapons\Rifle_Base_F\WeaponSlotsInfo [Indent level: 1],
        "WeaponSlotsInfo": {
            "mass": 2,
            # Class: CfgWeapons\Rifle\WeaponSlotsInfo\MuzzleSlot [Indent level: 2],
            "MuzzleSlot": {
                "linkProxy": "A3|data_f|proxies|weapon_slots|MUZZLE",
                "displayName": "$str_a3_cfgweapons_abr_base_f_weaponslotsinfo_muzzleslot0",
                "compatibleItems": [],
                "iconPicture": "A3|Weapons_F|Data|UI|attachment_muzzle.paa",
                "iconPinpoint": "Center",
                "access": 1,
                "scope": 0,
                "iconPosition": [0,0],
                "iconScale": 0
            },
            # Class: CfgWeapons\Rifle\WeaponSlotsInfo\CowsSlot [Indent level: 2],
            "CowsSlot": {
                "compatibleItems": ["optic_Nightstalker","optic_tws","optic_tws_mg","optic_NVS","optic_DMS","optic_LRPS","optic_ams","optic_AMS_snd","optic_AMS_khk","optic_KHS_blk","optic_KHS_tan","optic_KHS_hex","optic_KHS_old","optic_SOS","optic_MRCO","optic_Arco","optic_aco","optic_ACO_grn","optic_aco_smg","optic_ACO_grn_smg","optic_hamr","optic_Holosight","optic_Holosight_smg","optic_Hamr_khk_F","optic_SOS_khk_F","optic_Arco_ghex_F","optic_Arco_blk_F","optic_DMS_ghex_F","optic_ERCO_blk_F","optic_ERCO_khk_F","optic_ERCO_snd_F","optic_LRPS_ghex_F","optic_LRPS_tna_F","optic_Holosight_blk_F","optic_Holosight_khk_F","optic_Holosight_smg_blk_F","optic_Holosight_smg_khk_F","optic_Arco_AK_blk_F","optic_Arco_AK_lush_F","optic_Arco_AK_arid_F","optic_DMS_weathered_F","optic_DMS_weathered_Kir_F","optic_Arco_lush_F","optic_Arco_arid_F","optic_Holosight_lush_F","optic_Holosight_arid_F","ACE_optic_Hamr_2D","ACE_optic_Hamr_PIP","ACE_optic_Arco_2D","ACE_optic_Arco_PIP","ACE_optic_MRCO_2D","ACE_optic_MRCO_PIP","ACE_optic_SOS_2D","ACE_optic_SOS_PIP","ACE_optic_LRPS_2D","ACE_optic_LRPS_PIP"],
                "linkProxy": "A3|data_f|proxies|weapon_slots|TOP",
                "displayName": "Optics Slot",
                "iconPicture": "A3|Weapons_F|Data|UI|attachment_top.paa",
                "iconPinpoint": "Bottom",
                "access": 1,
                "scope": 0,
                "iconPosition": [0,0],
                "iconScale": 0
            },
            # Class: CfgWeapons\Rifle\WeaponSlotsInfo\PointerSlot [Indent level: 2],
            "PointerSlot": {
                "compatibleItems": ["acc_flashlight","acc_pointer_IR","ACE_acc_pointer_red","ACE_acc_pointer_green_IR","ACE_acc_pointer_green"],
                "iconPicture": "A3|Weapons_F|Data|UI|attachment_side.paa",
                "iconPinpoint": "Center",
                "linkProxy": "A3|data_f|proxies|weapon_slots|SIDE",
                "displayName": "Pointer Slot",
                "access": 1,
                "scope": 0,
                "iconPosition": [0,0],
                "iconScale": 0
            },
            "allowedSlots": [901]
        },
        "htMin": 1,
        "htMax": 600,
        "afMax": 0,
        "mfMax": 0,
        "mFact": 1,
        "tBody": 100,
        "autoFire": 1,
        "reloadAction": "ReloadMagazine",
        "soundContinuous": 0,
        "optics": 0,
        "cursor": "arifle",
        "cursoraim": "CursorAim",
        "value": 4,
        "nameSound": "rifle",
        "reloadTime": 0.15,
        "modelOptics": "-",
        "sound": [],
        "opticsFlare": 0,
        "autoReload": 0,
        "aiDispersionCoefX": 6,
        "aiDispersionCoefY": 6,
        "opticsZoomMin": 0.25,
        "opticsZoomMax": 1.25,
        "opticsZoomInit": 0.75,
        "distanceZoomMin": 300,
        "distanceZoomMax": 300,
        "maxLeadSpeed": 23,
        "canLock": 0,
        "flash": "gunfire",
        "flashSize": 0.5,
        "dispersion": 0.00029,
        "recoilProne": "assaultRifleBase",
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "ffCount": 3,
        "weaponPoolAvailable": 1,
        "maxZeroing": 1000,
        "zeroingSound": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|noises|rifle_zeroing_1.ogg",5,1,5],
        "ace_overheating_mrbs": 3000,
        "ace_overheating_dispersion": 1,
        "ace_overheating_slowdownFactor": 1,
        "type": 1,
        "dexterity": 1.7,
        "aiRateOfFire": 0.5,
        "aiRateOfFireDistance": 500,
        "inertia": 0.5,
        "access": 3,
        "picture": "",
        "uiPicture": "",
        "ammo": "",
        "cursorSize": 1,
        "showAimCursorInternal": 1,
        "cursorAimOn": "",
        "laser": 0,
        "hiddenSelections": [],
        "hiddenSelectionsTextures": [],
        "hiddenUnderwaterSelections": [],
        "shownUnderwaterSelections": [],
        "hiddenUnderwaterSelectionsTextures": [],
        "simulation": "Weapon",
        "count": 0,
        "multiplier": 1,
        "burst": 1,
        "magazineReloadTime": 0,
        "magazineReloadSwitchPhase": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": ["sound",1],
        "soundLoop": ["sound",1],
        "weaponSoundEffect": "",
        "soundBurst": 1,
        "reloadSound": ["",1,1],
        "reloadMagazineSound": ["",1,1],
        "emptySound": ["",1,1],
        "soundBullet": ["emptySound",1],
        "initSpeed": 0,
        "ballisticsComputer": 0,
        "irDistance": 0,
        "irDotIntensity": 0.001,
        "lockAcquire": 1,
        "enableAttack": 1,
        "maxRecoilSway": 0.008,
        "swayDecaySpeed": 2,
        "model": "",
        "modelSpecial": "",
        "modelMagazine": "",
        "muzzlePos": "usti hlavne",
        "muzzleEnd": "konec hlavne",
        "irLaserPos": "laser pos",
        "irLaserEnd": "laser dir",
        "cartridgePos": "nabojnicestart",
        "cartridgeVel": "nabojniceend",
        "selectionFireAnim": "zasleh",
        "memoryPointCamera": "eye",
        "fireSpreadAngle": 3,
        "useModelOptics": 1,
        "opticsID": 0,
        "opticsPPEffects": [],
        "forceOptics": 0,
        "useAsBinocular": 0,
        "opticsDisablePeripherialVision": 0.67,
        "primary": 10,
        "showSwitchAction": 0,
        "showEmpty": 1,
        "canShootInWater": 0,
        "aiRateOfFireDispersion": 0,
        "fireLightDuration": 0.05,
        "fireLightIntensity": 0.2,
        "fireLightDiffuse": [0.937,0.631,0.259],
        "fireLightAmbient": [0,0,0],
        "backgroundReload": 0,
        "muzzles": ["this"],
        "useAction": 0,
        "useActionTitle": "",
        "canDrop": 1,
        "weaponLockDelay": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "weight": 0,
        "minRange": 1,
        "minRangeProbab": 0.3,
        "midRange": 150,
        "midRangeProbab": 0.58,
        "maxRange": 500,
        "maxRangeProbab": 0.04,
        "handAnim": [],
        "lockingTargetSound": ["",0.000316228,2],
        "lockedTargetSound": ["",0.000316228,6],
        "detectRange": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "fireAnims": [],
        # Class: CfgWeapons\Default\Library [Indent level: 1],
        "Library": {
            "libTextDesc": ""
        },
        # Class: CfgWeapons\Default\GunFire [Indent level: 1],
        "GunFire": {
            "access": 0,
            "cloudletDuration": 0.2,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletAlpha": 1,
            "cloudletGrowUp": 0.2,
            "cloudletFadeIn": 0.01,
            "cloudletFadeOut": 0.5,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "cloudletShape": "cloudletFire",
            "cloudletColor": [1,1,1,0],
            "cloudletDensityCoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourceSize": 0.5,
            "timeToLive": 0,
            "initT": 4500,
            "deltaT": -3000,
            # Class: CfgWeapons\Default\GunFire\Table [Indent level: 2],
            "Table": {
                # Class: CfgWeapons\Default\GunFire\Table\T0 [Indent level: 3]
                "T0": {
                    "maxT": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T1 [Indent level: 3],
                "T1": {
                    "maxT": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T2 [Indent level: 3],
                "T2": {
                    "maxT": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T3 [Indent level: 3],
                "T3": {
                    "maxT": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T4 [Indent level: 3],
                "T4": {
                    "maxT": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T5 [Indent level: 3],
                "T5": {
                    "maxT": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T6 [Indent level: 3],
                "T6": {
                    "maxT": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T7 [Indent level: 3],
                "T7": {
                    "maxT": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T8 [Indent level: 3],
                "T8": {
                    "maxT": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T9 [Indent level: 3],
                "T9": {
                    "maxT": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T10 [Indent level: 3],
                "T10": {
                    "maxT": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T11 [Indent level: 3],
                "T11": {
                    "maxT": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T12 [Indent level: 3],
                "T12": {
                    "maxT": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T13 [Indent level: 3],
                "T13": {
                    "maxT": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T14 [Indent level: 3],
                "T14": {
                    "maxT": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T15 [Indent level: 3],
                "T15": {
                    "maxT": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T16 [Indent level: 3],
                "T16": {
                    "maxT": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T17 [Indent level: 3],
                "T17": {
                    "maxT": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T18 [Indent level: 3],
                "T18": {
                    "maxT": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T19 [Indent level: 3],
                "T19": {
                    "maxT": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T20 [Indent level: 3],
                "T20": {
                    "maxT": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T21 [Indent level: 3],
                "T21": {
                    "maxT": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T22 [Indent level: 3],
                "T22": {
                    "maxT": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        # Class: CfgWeapons\Default\GunClouds [Indent level: 1],
        "GunClouds": {
            "access": 0,
            "cloudletGrowUp": 0.05,
            "cloudletFadeIn": 0,
            "cloudletFadeOut": 0.1,
            "cloudletDuration": 0.05,
            "cloudletAlpha": 0.3,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "interval": -0.02,
            "size": 0.3,
            "sourceSize": 0.02,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletShape": "cloudletClouds",
            "cloudletColor": [1,1,1,0],
            "timeToLive": 0,
            "initT": 0,
            "deltaT": 0,
            # Class: CfgWeapons\Default\GunClouds\Table [Indent level: 2],
            "Table": {
                # Class: CfgWeapons\Default\GunClouds\Table\T0 [Indent level: 3]
                "T0": {
                    "maxT": 0,
                    "color": [1,1,1,0]
                }
            }
        },
        "textureType": "default",
        "aimTransitionSpeed": 1
    },
    # Class: CfgWeapons\rhs_weap_M1garand_Base_F\ADS [Indent level: 1],
    "ADS": {
        "magazines": ["rhs_mag_m1garand_ads"],
        "showToPlayer": 0,
        "displayName": "SAFE",
        "descriptionShort": "SAFE",
        "modes": ["Safe"],
        "discreteDistance": [0],
        "discreteDistanceInitIndex": 0,
        "drySound": ["A3|Sounds_F|arsenal|weapons|Rifles|MX|dry_Mx",0.562341,1,10],
        "changeFiremodeSound": ["A3|sounds_f|weapons|closure|firemode_changer_2",0.551189,1,5],
        # Class: CfgWeapons\RHS_SAFE_BASE\Safe [Indent level: 1],
        "Safe": {
            "sounds": [],
            "displayName": "SAFE",
            "descriptionShort": "SAFE",
            "showToPlayer": 0,
            "minRange": 0,
            "minRangeProbab": 0.001,
            "midRange": 0.001,
            "midRangeProbab": 0.001,
            "maxRange": 0.001,
            "maxRangeProbab": 0.001,
            "multiplier": 1,
            "burst": 1,
            "burstRangeMax": -1,
            "dispersion": 0.0002,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "soundContinuous": 0,
            "weaponSoundEffect": "",
            "reloadTime": 0.1,
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "autoFire": 0,
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "textureType": "semi",
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1,
            "aiRateOfFire": 2,
            "aiRateOfFireDispersion": 1,
            "aiRateOfFireDistance": 500
        },
        "scope": 0,
        "weaponInfoType": "RscWeaponZeroing",
        "recoil": "recoil_default",
        "deployedPivot": "bipod",
        # Class: CfgWeapons\Rifle_Base_F\GunParticles [Indent level: 1],
        "GunParticles": {
            # Class: CfgWeapons\Rifle_Base_F\GunParticles\FirstEffect [Indent level: 2]
            "FirstEffect": {
                "effectName": "RifleAssaultCloud",
                "positionName": "Usti hlavne",
                "directionName": "Konec hlavne"
            }
        },
        # Class: CfgWeapons\Rifle_Base_F\Eventhandlers [Indent level: 1],
        "Eventhandlers": {
            # Class: CfgWeapons\Rifle_Base_F\Eventhandlers\GSM_popMagRifle [Indent level: 2]
            "GSM_popMagRifle": {
                "fired": "_this call GSM_fnc_detectReload"
            }
        },
        # Class: CfgWeapons\Rifle_Base_F\WeaponSlotsInfo [Indent level: 1],
        "WeaponSlotsInfo": {
            "mass": 2,
            # Class: CfgWeapons\Rifle\WeaponSlotsInfo\MuzzleSlot [Indent level: 2],
            "MuzzleSlot": {
                "linkProxy": "A3|data_f|proxies|weapon_slots|MUZZLE",
                "displayName": "$str_a3_cfgweapons_abr_base_f_weaponslotsinfo_muzzleslot0",
                "compatibleItems": [],
                "iconPicture": "A3|Weapons_F|Data|UI|attachment_muzzle.paa",
                "iconPinpoint": "Center",
                "access": 1,
                "scope": 0,
                "iconPosition": [0,0],
                "iconScale": 0
            },
            # Class: CfgWeapons\Rifle\WeaponSlotsInfo\CowsSlot [Indent level: 2],
            "CowsSlot": {
                "compatibleItems": ["optic_Nightstalker","optic_tws","optic_tws_mg","optic_NVS","optic_DMS","optic_LRPS","optic_ams","optic_AMS_snd","optic_AMS_khk","optic_KHS_blk","optic_KHS_tan","optic_KHS_hex","optic_KHS_old","optic_SOS","optic_MRCO","optic_Arco","optic_aco","optic_ACO_grn","optic_aco_smg","optic_ACO_grn_smg","optic_hamr","optic_Holosight","optic_Holosight_smg","optic_Hamr_khk_F","optic_SOS_khk_F","optic_Arco_ghex_F","optic_Arco_blk_F","optic_DMS_ghex_F","optic_ERCO_blk_F","optic_ERCO_khk_F","optic_ERCO_snd_F","optic_LRPS_ghex_F","optic_LRPS_tna_F","optic_Holosight_blk_F","optic_Holosight_khk_F","optic_Holosight_smg_blk_F","optic_Holosight_smg_khk_F","optic_Arco_AK_blk_F","optic_Arco_AK_lush_F","optic_Arco_AK_arid_F","optic_DMS_weathered_F","optic_DMS_weathered_Kir_F","optic_Arco_lush_F","optic_Arco_arid_F","optic_Holosight_lush_F","optic_Holosight_arid_F","ACE_optic_Hamr_2D","ACE_optic_Hamr_PIP","ACE_optic_Arco_2D","ACE_optic_Arco_PIP","ACE_optic_MRCO_2D","ACE_optic_MRCO_PIP","ACE_optic_SOS_2D","ACE_optic_SOS_PIP","ACE_optic_LRPS_2D","ACE_optic_LRPS_PIP"],
                "linkProxy": "A3|data_f|proxies|weapon_slots|TOP",
                "displayName": "Optics Slot",
                "iconPicture": "A3|Weapons_F|Data|UI|attachment_top.paa",
                "iconPinpoint": "Bottom",
                "access": 1,
                "scope": 0,
                "iconPosition": [0,0],
                "iconScale": 0
            },
            # Class: CfgWeapons\Rifle\WeaponSlotsInfo\PointerSlot [Indent level: 2],
            "PointerSlot": {
                "compatibleItems": ["acc_flashlight","acc_pointer_IR","ACE_acc_pointer_red","ACE_acc_pointer_green_IR","ACE_acc_pointer_green"],
                "iconPicture": "A3|Weapons_F|Data|UI|attachment_side.paa",
                "iconPinpoint": "Center",
                "linkProxy": "A3|data_f|proxies|weapon_slots|SIDE",
                "displayName": "Pointer Slot",
                "access": 1,
                "scope": 0,
                "iconPosition": [0,0],
                "iconScale": 0
            },
            "allowedSlots": [901]
        },
        "htMin": 1,
        "htMax": 600,
        "afMax": 0,
        "mfMax": 0,
        "mFact": 1,
        "tBody": 100,
        "autoFire": 1,
        "reloadAction": "ReloadMagazine",
        "soundContinuous": 0,
        "optics": 0,
        "cursor": "arifle",
        "cursoraim": "CursorAim",
        "value": 4,
        "nameSound": "rifle",
        "reloadTime": 0.15,
        "modelOptics": "-",
        "sound": [],
        "opticsFlare": 0,
        "autoReload": 0,
        "aiDispersionCoefX": 6,
        "aiDispersionCoefY": 6,
        "opticsZoomMin": 0.25,
        "opticsZoomMax": 1.25,
        "opticsZoomInit": 0.75,
        "distanceZoomMin": 300,
        "distanceZoomMax": 300,
        "maxLeadSpeed": 23,
        "canLock": 0,
        "flash": "gunfire",
        "flashSize": 0.5,
        "dispersion": 0.00029,
        "recoilProne": "assaultRifleBase",
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "ffCount": 3,
        "weaponPoolAvailable": 1,
        "maxZeroing": 1000,
        "zeroingSound": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|noises|rifle_zeroing_1.ogg",5,1,5],
        "ace_overheating_mrbs": 3000,
        "ace_overheating_dispersion": 1,
        "ace_overheating_slowdownFactor": 1,
        "type": 1,
        "dexterity": 1.7,
        "aiRateOfFire": 0.5,
        "aiRateOfFireDistance": 500,
        "inertia": 0.5,
        "access": 3,
        "picture": "",
        "uiPicture": "",
        "ammo": "",
        "cursorSize": 1,
        "showAimCursorInternal": 1,
        "cursorAimOn": "",
        "laser": 0,
        "hiddenSelections": [],
        "hiddenSelectionsTextures": [],
        "hiddenUnderwaterSelections": [],
        "shownUnderwaterSelections": [],
        "hiddenUnderwaterSelectionsTextures": [],
        "simulation": "Weapon",
        "count": 0,
        "multiplier": 1,
        "burst": 1,
        "magazineReloadTime": 0,
        "magazineReloadSwitchPhase": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": ["sound",1],
        "soundLoop": ["sound",1],
        "weaponSoundEffect": "",
        "soundBurst": 1,
        "reloadSound": ["",1,1],
        "reloadMagazineSound": ["",1,1],
        "emptySound": ["",1,1],
        "soundBullet": ["emptySound",1],
        "initSpeed": 0,
        "ballisticsComputer": 0,
        "irDistance": 0,
        "irDotIntensity": 0.001,
        "lockAcquire": 1,
        "enableAttack": 1,
        "maxRecoilSway": 0.008,
        "swayDecaySpeed": 2,
        "model": "",
        "modelSpecial": "",
        "modelMagazine": "",
        "muzzlePos": "usti hlavne",
        "muzzleEnd": "konec hlavne",
        "irLaserPos": "laser pos",
        "irLaserEnd": "laser dir",
        "cartridgePos": "nabojnicestart",
        "cartridgeVel": "nabojniceend",
        "selectionFireAnim": "zasleh",
        "memoryPointCamera": "eye",
        "fireSpreadAngle": 3,
        "useModelOptics": 1,
        "opticsID": 0,
        "opticsPPEffects": [],
        "forceOptics": 0,
        "useAsBinocular": 0,
        "opticsDisablePeripherialVision": 0.67,
        "primary": 10,
        "showSwitchAction": 0,
        "showEmpty": 1,
        "canShootInWater": 0,
        "aiRateOfFireDispersion": 0,
        "fireLightDuration": 0.05,
        "fireLightIntensity": 0.2,
        "fireLightDiffuse": [0.937,0.631,0.259],
        "fireLightAmbient": [0,0,0],
        "backgroundReload": 0,
        "muzzles": ["this"],
        "useAction": 0,
        "useActionTitle": "",
        "canDrop": 1,
        "weaponLockDelay": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "weight": 0,
        "minRange": 1,
        "minRangeProbab": 0.3,
        "midRange": 150,
        "midRangeProbab": 0.58,
        "maxRange": 500,
        "maxRangeProbab": 0.04,
        "handAnim": [],
        "lockingTargetSound": ["",0.000316228,2],
        "lockedTargetSound": ["",0.000316228,6],
        "detectRange": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "fireAnims": [],
        # Class: CfgWeapons\Default\Library [Indent level: 1],
        "Library": {
            "libTextDesc": ""
        },
        # Class: CfgWeapons\Default\GunFire [Indent level: 1],
        "GunFire": {
            "access": 0,
            "cloudletDuration": 0.2,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletAlpha": 1,
            "cloudletGrowUp": 0.2,
            "cloudletFadeIn": 0.01,
            "cloudletFadeOut": 0.5,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "cloudletShape": "cloudletFire",
            "cloudletColor": [1,1,1,0],
            "cloudletDensityCoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourceSize": 0.5,
            "timeToLive": 0,
            "initT": 4500,
            "deltaT": -3000,
            # Class: CfgWeapons\Default\GunFire\Table [Indent level: 2],
            "Table": {
                # Class: CfgWeapons\Default\GunFire\Table\T0 [Indent level: 3]
                "T0": {
                    "maxT": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T1 [Indent level: 3],
                "T1": {
                    "maxT": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T2 [Indent level: 3],
                "T2": {
                    "maxT": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T3 [Indent level: 3],
                "T3": {
                    "maxT": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T4 [Indent level: 3],
                "T4": {
                    "maxT": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T5 [Indent level: 3],
                "T5": {
                    "maxT": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T6 [Indent level: 3],
                "T6": {
                    "maxT": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T7 [Indent level: 3],
                "T7": {
                    "maxT": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T8 [Indent level: 3],
                "T8": {
                    "maxT": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T9 [Indent level: 3],
                "T9": {
                    "maxT": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T10 [Indent level: 3],
                "T10": {
                    "maxT": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T11 [Indent level: 3],
                "T11": {
                    "maxT": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T12 [Indent level: 3],
                "T12": {
                    "maxT": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T13 [Indent level: 3],
                "T13": {
                    "maxT": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T14 [Indent level: 3],
                "T14": {
                    "maxT": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T15 [Indent level: 3],
                "T15": {
                    "maxT": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T16 [Indent level: 3],
                "T16": {
                    "maxT": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T17 [Indent level: 3],
                "T17": {
                    "maxT": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T18 [Indent level: 3],
                "T18": {
                    "maxT": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T19 [Indent level: 3],
                "T19": {
                    "maxT": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T20 [Indent level: 3],
                "T20": {
                    "maxT": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T21 [Indent level: 3],
                "T21": {
                    "maxT": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T22 [Indent level: 3],
                "T22": {
                    "maxT": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        # Class: CfgWeapons\Default\GunClouds [Indent level: 1],
        "GunClouds": {
            "access": 0,
            "cloudletGrowUp": 0.05,
            "cloudletFadeIn": 0,
            "cloudletFadeOut": 0.1,
            "cloudletDuration": 0.05,
            "cloudletAlpha": 0.3,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "interval": -0.02,
            "size": 0.3,
            "sourceSize": 0.02,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletShape": "cloudletClouds",
            "cloudletColor": [1,1,1,0],
            "timeToLive": 0,
            "initT": 0,
            "deltaT": 0,
            # Class: CfgWeapons\Default\GunClouds\Table [Indent level: 2],
            "Table": {
                # Class: CfgWeapons\Default\GunClouds\Table\T0 [Indent level: 3]
                "T0": {
                    "maxT": 0,
                    "color": [1,1,1,0]
                }
            }
        },
        "textureType": "default",
        "aimTransitionSpeed": 1
    },
    "muzzles": ["this","SAFE","ADS"],
    "optics": 0,
    "reloadAction": "RHS_GestureReloadM1Garand",
    "maxRecoilSway": 0.0125,
    "swayDecaySpeed": 1.25,
    "recoil": "recoil_dmr_01",
    # Class: CfgWeapons\rhs_weap_M1garand_Base_F\GunParticles [Indent level: 1],
    "GunParticles": {
        # Class: CfgWeapons\rhs_weap_M1garand_Base_F\GunParticles\SecondEffect [Indent level: 2]
        "SecondEffect": {
            "positionName": "Nabojnicestart",
            "directionName": "Nabojniceend",
            "effectName": "RifleAssaultCloud"
        },
        # Class: CfgWeapons\Rifle_Base_F\GunParticles\FirstEffect [Indent level: 2],
        "FirstEffect": {
            "effectName": "RifleAssaultCloud",
            "positionName": "Usti hlavne",
            "directionName": "Konec hlavne"
        }
    },
    "weaponInfoType": "rhs_rscOptics_m1garand_handler",
    "discreteDistance": [100,200,300,400,500,600,700,800,900,1000,1100,1200],
    "discreteDistanceCameraPoint": ["eye","eye_200","eye_300","eye_400","eye_500","eye_600","eye_700","eye_800","eye_900","eye_1000","eye_1100","eye_1200"],
    "discreteDistanceInitIndex": 0,
    "cameraDir": "eye_look",
    "maxZeroing": 1200,
    "opticsZoomMin": 0.275,
    "opticsZoomMax": 1.1,
    "opticsZoomInit": 0.75,
    "distanceZoomMin": 300,
    "distanceZoomMax": 300,
    "descriptionShort": "Semi-automatic Rifle<br />Caliber: .30-06",
    "handAnim": ["OFP2_ManSkeleton","|rhsgref|addons|rhsgref_c_weapons|anims|rhs_hand_m1garand.rtm"],
    "dexterity": 1.8,
    "inertia": 0.95,
    "bullet1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|medium|metal_1.ogg",2.0099,1,10],
    "bullet2": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|medium|metal_2.ogg",2.0099,1,10],
    "bullet3": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|medium|metal_3.ogg",2.0099,1,10],
    "bullet4": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|medium|metal_4.ogg",2.0099,1,10],
    "bullet5": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|medium|dirt_1.ogg",2.0099,1,10],
    "bullet6": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|medium|dirt_2.ogg",2.0099,1,10],
    "bullet7": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|medium|dirt_3.ogg",2.0099,1,10],
    "bullet8": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|medium|dirt_4.ogg",2.0099,1,10],
    "bullet9": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|medium|grass_1.ogg",2.0099,1,10],
    "bullet10": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|medium|grass_2.ogg",2.0099,1,10],
    "bullet11": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|medium|grass_3.ogg",2.0099,1,10],
    "bullet12": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|medium|grass_4.ogg",2.0099,1,10],
    "soundBullet": ["bullet1",0.08,"bullet2",0.084,"bullet3",0.084,"bullet4",0.084,"bullet5",0.093,"bullet6",0.093,"bullet7",0.074,"bullet8",0.074,"bullet9",0.084,"bullet10",0.085,"bullet11",0.083,"bullet12",0.083],
    "modes": ["Single","far_optic1","medium_optic2","far_optic2"],
    # Class: CfgWeapons\rhs_weap_M1garand_Base_F\Single [Indent level: 1],
    "Single": {
        "dispersion": 0.00045,
        "minRange": 2,
        "minRangeProbab": 0.3,
        "midRange": 350,
        "midRangeProbab": 0.7,
        "maxRange": 500,
        "maxRangeProbab": 0.05,
        "displayName": "",
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_M1garand_Base_F\Single\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_m76_shot_soundset","jsrs_7x62mm_reverb_soundset"]
        },
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "reloadTime": 0.1,
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "requiredOpticType": -1,
        "aiRateOfFire": 2,
        "aiRateOfFireDispersion": 1,
        "aiRateOfFireDistance": 500
    },
    # Class: CfgWeapons\rhs_weap_M1garand_Base_F\far_optic1 [Indent level: 1],
    "far_optic1": {
        "showToPlayer": 0,
        "minRange": 150,
        "minRangeProbab": 0.1,
        "midRange": 500,
        "midRangeProbab": 0.7,
        "maxRange": 1000,
        "maxRangeProbab": 0.3,
        "aiRateOfFire": 5,
        "aiRateOfFireDistance": 700,
        "requiredOpticType": 1,
        "dispersion": 0.00045,
        "displayName": "",
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_M1garand_Base_F\Single\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_m76_shot_soundset","jsrs_7x62mm_reverb_soundset"]
        },
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "reloadTime": 0.1,
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons\rhs_weap_M1garand_Base_F\medium_optic2 [Indent level: 1],
    "medium_optic2": {
        "showToPlayer": 0,
        "minRange": 250,
        "minRangeProbab": 0.1,
        "midRange": 750,
        "midRangeProbab": 0.7,
        "maxRange": 1000,
        "maxRangeProbab": 0.3,
        "aiRateOfFire": 6,
        "aiRateOfFireDistance": 1000,
        "requiredOpticType": 2,
        "dispersion": 0.00045,
        "displayName": "",
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_M1garand_Base_F\Single\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_m76_shot_soundset","jsrs_7x62mm_reverb_soundset"]
        },
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "reloadTime": 0.1,
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons\rhs_weap_M1garand_Base_F\far_optic2 [Indent level: 1],
    "far_optic2": {
        "minRange": 500,
        "minRangeProbab": 0.1,
        "midRange": 1050,
        "midRangeProbab": 0.7,
        "maxRange": 2000,
        "maxRangeProbab": 0.3,
        "aiRateOfFire": 8,
        "aiRateOfFireDistance": 2000,
        "requiredOpticType": 2,
        "showToPlayer": 0,
        "dispersion": 0.00045,
        "displayName": "",
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_M1garand_Base_F\Single\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_m76_shot_soundset","jsrs_7x62mm_reverb_soundset"]
        },
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "reloadTime": 0.1,
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "aiRateOfFireDispersion": 1
    },
    "aiDispersionCoefY": 10,
    "aiDispersionCoefX": 8,
    "drySound": ["A3|sounds_f|weapons|Other|dry_1",0.01,1],
    "reloadMagazineSound": ["|rhsgref|addons|rhsgref_weapon_sounds|reloads|m1garand_reload",1,1,20],
    # Class: CfgWeapons\rhs_weap_M1garand_Base_F\Eventhandlers [Indent level: 1],
    "Eventhandlers": {
        # Class: CfgWeapons\rhs_weap_M1garand_Base_F\Eventhandlers\RHSGREF_garandPing [Indent level: 2]
        "RHSGREF_garandPing": {
            "fired": "_this call RHS_fnc_m1Handler;"
        },
        # Class: CfgWeapons\Rifle_Base_F\Eventhandlers\GSM_popMagRifle [Indent level: 2],
        "GSM_popMagRifle": {
            "fired": "_this call GSM_fnc_detectReload"
        }
    },
    "ACE_barrelTwist": 254,
    "ACE_barrelLength": 610,
    "deployedPivot": "bipod",
    "htMin": 1,
    "htMax": 600,
    "afMax": 0,
    "mfMax": 0,
    "mFact": 1,
    "tBody": 100,
    "autoFire": 1,
    "soundContinuous": 0,
    "cursor": "arifle",
    "cursoraim": "CursorAim",
    "value": 4,
    "nameSound": "rifle",
    "reloadTime": 0.15,
    "modelOptics": "-",
    "sound": [],
    "opticsFlare": 0,
    "autoReload": 0,
    "maxLeadSpeed": 23,
    "canLock": 0,
    "flash": "gunfire",
    "flashSize": 0.5,
    "dispersion": 0.00029,
    "recoilProne": "assaultRifleBase",
    "ffMagnitude": 0.5,
    "ffFrequency": 11,
    "ffCount": 3,
    "weaponPoolAvailable": 1,
    "zeroingSound": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|noises|rifle_zeroing_1.ogg",5,1,5],
    "ace_overheating_mrbs": 3000,
    "ace_overheating_dispersion": 1,
    "ace_overheating_slowdownFactor": 1,
    "type": 1,
    "aiRateOfFire": 0.5,
    "aiRateOfFireDistance": 500,
    "access": 3,
    "ammo": "",
    "cursorSize": 1,
    "showAimCursorInternal": 1,
    "cursorAimOn": "",
    "laser": 0,
    "hiddenSelections": [],
    "hiddenSelectionsTextures": [],
    "hiddenUnderwaterSelections": [],
    "shownUnderwaterSelections": [],
    "hiddenUnderwaterSelectionsTextures": [],
    "simulation": "Weapon",
    "count": 0,
    "multiplier": 1,
    "burst": 1,
    "magazineReloadTime": 0,
    "soundBegin": ["sound",1],
    "soundBeginWater": ["sound",1],
    "soundClosure": ["sound",1],
    "soundEnd": ["sound",1],
    "soundLoop": ["sound",1],
    "weaponSoundEffect": "",
    "soundBurst": 1,
    "reloadSound": ["",1,1],
    "changeFiremodeSound": ["",1,1],
    "emptySound": ["",1,1],
    "initSpeed": 0,
    "ballisticsComputer": 0,
    "irDistance": 0,
    "irDotIntensity": 0.001,
    "lockAcquire": 1,
    "enableAttack": 1,
    "modelSpecial": "",
    "modelMagazine": "",
    "muzzlePos": "usti hlavne",
    "muzzleEnd": "konec hlavne",
    "irLaserPos": "laser pos",
    "irLaserEnd": "laser dir",
    "cartridgePos": "nabojnicestart",
    "cartridgeVel": "nabojniceend",
    "selectionFireAnim": "zasleh",
    "memoryPointCamera": "eye",
    "fireSpreadAngle": 3,
    "useModelOptics": 1,
    "opticsID": 0,
    "opticsPPEffects": [],
    "forceOptics": 0,
    "useAsBinocular": 0,
    "opticsDisablePeripherialVision": 0.67,
    "primary": 10,
    "showSwitchAction": 0,
    "showEmpty": 1,
    "showToPlayer": 1,
    "canShootInWater": 0,
    "aiRateOfFireDispersion": 0,
    "fireLightDuration": 0.05,
    "fireLightIntensity": 0.2,
    "fireLightDiffuse": [0.937,0.631,0.259],
    "fireLightAmbient": [0,0,0],
    "backgroundReload": 0,
    "useAction": 0,
    "useActionTitle": "",
    "canDrop": 1,
    "weaponLockDelay": 0,
    "weaponLockSystem": 0,
    "cmImmunity": 1,
    "weight": 0,
    "minRange": 1,
    "minRangeProbab": 0.3,
    "midRange": 150,
    "midRangeProbab": 0.58,
    "maxRange": 500,
    "maxRangeProbab": 0.04,
    "lockingTargetSound": ["",0.000316228,2],
    "lockedTargetSound": ["",0.000316228,6],
    "detectRange": 0,
    "artilleryDispersion": 1,
    "artilleryCharge": 1,
    "fireAnims": [],
    # Class: CfgWeapons\Default\GunFire [Indent level: 1],
    "GunFire": {
        "access": 0,
        "cloudletDuration": 0.2,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 0.2,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 0.5,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletFire",
        "cloudletColor": [1,1,1,0],
        "cloudletDensityCoef": -1,
        "interval": -0.01,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 4500,
        "deltaT": -3000,
        # Class: CfgWeapons\Default\GunFire\Table [Indent level: 2],
        "Table": {
            # Class: CfgWeapons\Default\GunFire\Table\T0 [Indent level: 3]
            "T0": {
                "maxT": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T1 [Indent level: 3],
            "T1": {
                "maxT": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T2 [Indent level: 3],
            "T2": {
                "maxT": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T3 [Indent level: 3],
            "T3": {
                "maxT": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T4 [Indent level: 3],
            "T4": {
                "maxT": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T5 [Indent level: 3],
            "T5": {
                "maxT": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T6 [Indent level: 3],
            "T6": {
                "maxT": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T7 [Indent level: 3],
            "T7": {
                "maxT": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T8 [Indent level: 3],
            "T8": {
                "maxT": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T9 [Indent level: 3],
            "T9": {
                "maxT": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T10 [Indent level: 3],
            "T10": {
                "maxT": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T11 [Indent level: 3],
            "T11": {
                "maxT": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T12 [Indent level: 3],
            "T12": {
                "maxT": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T13 [Indent level: 3],
            "T13": {
                "maxT": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T14 [Indent level: 3],
            "T14": {
                "maxT": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T15 [Indent level: 3],
            "T15": {
                "maxT": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T16 [Indent level: 3],
            "T16": {
                "maxT": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T17 [Indent level: 3],
            "T17": {
                "maxT": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T18 [Indent level: 3],
            "T18": {
                "maxT": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T19 [Indent level: 3],
            "T19": {
                "maxT": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T20 [Indent level: 3],
            "T20": {
                "maxT": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T21 [Indent level: 3],
            "T21": {
                "maxT": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T22 [Indent level: 3],
            "T22": {
                "maxT": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgWeapons\Default\GunClouds [Indent level: 1],
    "GunClouds": {
        "access": 0,
        "cloudletGrowUp": 0.05,
        "cloudletFadeIn": 0,
        "cloudletFadeOut": 0.1,
        "cloudletDuration": 0.05,
        "cloudletAlpha": 0.3,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "interval": -0.02,
        "size": 0.3,
        "sourceSize": 0.02,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletShape": "cloudletClouds",
        "cloudletColor": [1,1,1,0],
        "timeToLive": 0,
        "initT": 0,
        "deltaT": 0,
        # Class: CfgWeapons\Default\GunClouds\Table [Indent level: 2],
        "Table": {
            # Class: CfgWeapons\Default\GunClouds\Table\T0 [Indent level: 3]
            "T0": {
                "maxT": 0,
                "color": [1,1,1,0]
            }
        }
    },
    "textureType": "default",
    "aimTransitionSpeed": 1,
}