rhs_weap_m249 = {
    "author": "Red Hammer Studios",
    "picture": "rhsusf|addons|rhsusf_inventoryicons|data|weapons|rhs_weap_m249_ca.paa",
    "scope": 2,
    "model": "rhsusf|addons|rhsusf_weapons2|M249|merged|m249_mk1.p3d",
    "hiddenSelectionsTextures": ["rhsusf|addons|rhsusf_weapons2|m249|merged|data|reciever_249_co.paa","rhsusf|addons|rhsusf_weapons2|m249|merged|data|m249_merged1_co.paa","rhsusf|addons|rhsusf_weapons2|m249|merged|data|barrelstock_old_co.paa","rhsusf|addons|rhsusf_weapons2|m249|merged|data|ammobox_merged_co.paa","rhsusf|addons|rhsusf_weapons2|m249|merged|data|mk1|stock_co.paa"],
    "displayName": "M249",
    "AB_barrelTwist": 12,
    "AB_barrelLength": 18.3,
    "initspeed": -0.953125,
    "baseWeapon": "rhs_weap_m249",
    # Class: CfgWeapons\rhs_weap_m249\WeaponSlotsInfo [Indent level: 1],
    "WeaponSlotsInfo": {
        "mass": 131.67,
        "allowedSlots": [901],
        # Class: CfgWeapons\rhs_weap_m249\WeaponSlotsInfo\CowsSlot [Indent level: 2],
        "CowsSlot": {
        },
        # Class: CfgWeapons\rhs_weap_m249\WeaponSlotsInfo\PointerSlot [Indent level: 2],
        "PointerSlot": {
            "compatibleItems": []
        },
        # Class: CfgWeapons\rhs_weap_m249\WeaponSlotsInfo\UnderBarrelSlot [Indent level: 2],
        "UnderBarrelSlot": {
            "linkProxy": "a3|data_f_mark|Proxies|Weapon_Slots|UNDERBARREL",
            "iconPicture": "A3|Weapons_F|Data|clear_empty.paa",
            "iconPinpoint": "Bottom",
            # Class: rhs_UnderSlot_m249\compatibleItems [Indent level: 0],
            "compatibleItems": {
                "rhsusf_acc_saw_bipod": 1
            },
            "scope": 0,
            "iconPosition": [0,0],
            "iconScale": 0
        }
    },
    "ACE_barrelLength": 464.8,
    "ACE_barrelTwist": 177.8,
    "inertia": 0.81,
    "hasBipod": 0,
    # Class: CfgWeapons\rhs_weap_lmg_minimi_railed\LinkedItems [Indent level: 1],
    "LinkedItems": {
        # Class: CfgWeapons\rhs_weap_lmg_minimi_railed\LinkedItems\LinkedItemsUnder [Indent level: 2]
        "LinkedItemsUnder": {
            "slot": "UnderBarrelSlot",
            "item": "rhsusf_acc_saw_bipod"
        }
    },
    "recoil": "rhs_recoil_m249",
    "deployedPivot": "deploypoint",
    "soundBipodDown": ["A3|Sounds_F_Mark|arsenal|sfx|bipods|Bipod_AAF_down",1,1,20],
    "soundBipodUp": ["A3|Sounds_F_Mark|arsenal|sfx|bipods|Bipod_AAF_up",1,1,20],
    "magazines": ["rhsusf_200Rnd_556x45_box","rhsusf_200rnd_556x45_mixed_box","rhsusf_200rnd_556x45_M855_box","rhsusf_200rnd_556x45_M855_mixed_box"],
    "magazineWell": ["STANAG_556x45","CBA_556x45_STANAG","CBA_556x45_STANAG_L","CBA_556x45_STANAG_XL","M249_556x45","CBA_556x45_MINIMI"],
    "cursor": "mg",
    "cursorAim": "EmptyCursor",
    "nameSound": "Mgun",
    "reloadaction": "rhs_GestureReloadM249STANAG",
    "descriptionShort": "Light Machine Gun<br />Caliber: 5.56x45mm NATO",
    "drysound": ["|rhsusf|addons|rhsusf_weapons2|M249|snd|empty_machineguns",1,1,10],
    "reloadmagazinesound": ["|rhsusf|addons|rhsusf_weapons2|M249|snd|saw_reload",0.5,1,20],
    "UiPicture": "A3|weapons_f|data|UI|icon_mg_CA.paa",
    "discreteDistance": [300,400,500,600,700,800,900,1000],
    "discreteDistanceCameraPoint": ["eye","eye_400","eye_500","eye_600","eye_700","eye_800","eye_900","eye_1000"],
    "discreteDistanceInitIndex": 0,
    "cameraDir": "eye_look",
    "maxZeroing": 1000,
    "handanim": ["OFP2_ManSkeleton","|rhsusf|addons|rhsusf_c_weapons|anims|rhs_hand_m249_standard.rtm"],
    "opticszoominit": 0.75,
    "opticszoommax": 1.1,
    "opticszoommin": 0.275,
    "aidispersioncoefx": 21,
    "aidispersioncoefy": 24,
    # Class: CfgWeapons\rhs_weap_lmg_minimipara\ItemInfo [Indent level: 1],
    "ItemInfo": {
        "priority": 1,
        "RMBhint": "XMC",
        "onHoverText": "TODO XMC DSS"
    },
    # Class: CfgWeapons\rhs_weap_lmg_minimipara\FullAuto [Indent level: 1],
    "FullAuto": {
        "reloadTime": 0.075,
        "dispersion": 0.00101,
        "minRange": 0,
        "minRangeProbab": 0.3,
        "midRange": 5,
        "midRangeProbab": 0.7,
        "maxRange": 10,
        "maxRangeProbab": 0.04,
        "airateoffire": 4,
        # Class: CfgWeapons\rhs_weap_lmg_minimipara\FullAuto\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_m249_shot_soundset","jsrs_5x56mm_reverb_soundset"]
        },
        # Class: CfgWeapons\rhs_weap_lmg_minimipara\FullAuto\SilencedSound [Indent level: 2],
        "SilencedSound": {
            "soundSetShot": ["jsrs_m249_shot_silenced_soundset","jsrs_6x5mm_sd_reverb_soundset"]
        },
        # Class: CfgWeapons\rhs_weap_lmg_minimipara\FullAuto\BaseSoundModeType [Indent level: 2],
        "BaseSoundModeType": {
        },
        "sounds": ["StandardSound","SilencedSound"],
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "soundContinuous": 0,
        "autoFire": 1,
        "displayName": "Full",
        "textureType": "fullAuto",
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1,
        "aiRateOfFireDispersion": 1,
        "aiRateOfFireDistance": 500
    },
    "dlc": "RHS_USAF",
    "weaponInfoType": "rhs_rscOptics_m249",
    "hiddenSelections": ["camo1","camo2","camo3","camo4","camo5"],
    # Class: CfgWeapons\rhs_weap_saw_base\GunParticles [Indent level: 1],
    "GunParticles": {
        # Class: CfgWeapons\rhs_weap_saw_base\GunParticles\AmmoBeltLinkEject [Indent level: 2]
        "AmmoBeltLinkEject": {
            "positionName": "linkeject_start",
            "directionName": "linkeject_end",
            "effectName": "MachineGunEject2"
        },
        # Class: CfgWeapons\rhs_weap_saw_base\GunParticles\MuzzleCloud [Indent level: 2],
        "MuzzleCloud": {
            "positionName": "usti hlavne",
            "directionName": "konec hlavne",
            "effectName": "RifleAssaultCloud"
        },
        # Class: CfgWeapons\rhs_weap_saw_base\GunParticles\MuzzleRefract [Indent level: 2],
        "MuzzleRefract": {
            "positionName": "usti hlavne",
            "directionName": "usti hlavne up",
            "effectName": "RHSUSF_BarrelRefract"
        },
        # Class: CfgWeapons\rhs_weap_saw_base\GunParticles\PortCloud [Indent level: 2],
        "PortCloud": {
            "positionName": "Nabojnicestart",
            "directionName": "Nabojniceend",
            "effectName": "CaselessAmmoCloud"
        }
    },
    "maxRecoilSway": 0.015,
    "swayDecaySpeed": 1.25,
    "distanceZoomMin": 300,
    "distanceZoomMax": 300,
    "dexterity": 1.8,
    "aimTransitionSpeed": 0.5,
    # Class: CfgWeapons\rhs_weap_saw_base\Library [Indent level: 1],
    "Library": {
        "libTextDesc": "The M249 provides infantry squads with the heavy volume of fire of a machine gun combined with accuracy and portability approaching that of a rifle."
    },
    "bullet1": ["A3|sounds_f|weapons|shells|5_56|metal_556_01.wss",0.1,1,15],
    "bullet2": ["A3|sounds_f|weapons|shells|5_56|metal_556_02.wss",0.1,1,15],
    "bullet3": ["A3|sounds_f|weapons|shells|5_56|metal_556_03.wss",0.177828,1,15],
    "bullet4": ["A3|sounds_f|weapons|shells|5_56|metal_556_04.wss",0.177828,1,15],
    "bullet5": ["A3|sounds_f|weapons|shells|5_56|asphlat_556_01.wss",0.1,1,15],
    "bullet6": ["A3|sounds_f|weapons|shells|5_56|asphlat_556_02.wss",0.1,1,15],
    "bullet7": ["A3|sounds_f|weapons|shells|5_56|asphlat_556_03.wss",0.1,1,15],
    "bullet8": ["A3|sounds_f|weapons|shells|5_56|asphlat_556_04.wss",0.1,1,15],
    "bullet9": ["A3|sounds_f|weapons|shells|5_56|grass_556_01.wss",0.01,1,15],
    "bullet10": ["A3|sounds_f|weapons|shells|5_56|grass_556_02.wss",0.01,1,15],
    "bullet11": ["A3|sounds_f|weapons|shells|5_56|grass_556_03.wss",0.01,1,15],
    "bullet12": ["A3|sounds_f|weapons|shells|5_56|grass_556_04.wss",0.01,1,15],
    "soundBullet": ["bullet1",0.083,"bullet2",0.083,"bullet3",0.083,"bullet4",0.083,"bullet5",0.083,"bullet6",0.083,"bullet7",0.083,"bullet8",0.083,"bullet9",0.083,"bullet10",0.083,"bullet11",0.083,"bullet12",0.083],
    "modes": ["FullAuto","close","short","medium","far_optic1","far_optic2"],
    # Class: CfgWeapons\rhs_weap_saw_base\close [Indent level: 1],
    "close": {
        "showToPlayer": 0,
        "aiBurstTerminable": 1,
        "burst": 6,
        "burstRangeMax": 12,
        "aiRateOfFire": 0.5,
        "aiRateOfFireDistance": 50,
        "minRange": 0,
        "minRangeProbab": 0.05,
        "midRange": 30,
        "midRangeProbab": 0.69,
        "maxRange": 50,
        "maxRangeProbab": 0.1,
        "reloadTime": 0.075,
        "dispersion": 0.000261799,
        # Class: CfgWeapons\rhs_weap_saw_base\FullAuto\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_m249_shot_soundset","jsrs_5x56mm_reverb_soundset"]
        },
        # Class: CfgWeapons\rhs_weap_saw_base\FullAuto\SilencedSound [Indent level: 2],
        "SilencedSound": {
            "soundSetShot": ["jsrs_m249_shot_silenced_soundset","jsrs_6x5mm_sd_reverb_soundset"]
        },
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons\rhs_weap_saw_base\FullAuto\BaseSoundModeType [Indent level: 2],
        "BaseSoundModeType": {
        },
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "soundContinuous": 0,
        "autoFire": 1,
        "displayName": "Full",
        "textureType": "fullAuto",
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons\rhs_weap_saw_base\short [Indent level: 1],
    "short": {
        "burst": 5,
        "burstRangeMax": 12,
        "aiRateOfFire": 1,
        "aiRateOfFireDispersion": 2,
        "aiRateOfFireDistance": 300,
        "minRange": 50,
        "minRangeProbab": 0.4,
        "midRange": 150,
        "midRangeProbab": 0.69,
        "maxRange": 300,
        "maxRangeProbab": 0.1,
        "showToPlayer": 0,
        "aiBurstTerminable": 1,
        "reloadTime": 0.075,
        "dispersion": 0.000261799,
        # Class: CfgWeapons\rhs_weap_saw_base\FullAuto\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_m249_shot_soundset","jsrs_5x56mm_reverb_soundset"]
        },
        # Class: CfgWeapons\rhs_weap_saw_base\FullAuto\SilencedSound [Indent level: 2],
        "SilencedSound": {
            "soundSetShot": ["jsrs_m249_shot_silenced_soundset","jsrs_6x5mm_sd_reverb_soundset"]
        },
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons\rhs_weap_saw_base\FullAuto\BaseSoundModeType [Indent level: 2],
        "BaseSoundModeType": {
        },
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "soundContinuous": 0,
        "autoFire": 1,
        "displayName": "Full",
        "textureType": "fullAuto",
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1
    },
    # Class: CfgWeapons\rhs_weap_saw_base\medium [Indent level: 1],
    "medium": {
        "burst": 5,
        "burstRangeMax": 10,
        "aiRateOfFire": 2,
        "aiRateOfFireDispersion": 2,
        "aiRateOfFireDistance": 600,
        "minRange": 200,
        "minRangeProbab": 0.1,
        "midRange": 400,
        "midRangeProbab": 0.6,
        "maxRange": 600,
        "maxRangeProbab": 0.1,
        "showToPlayer": 0,
        "aiBurstTerminable": 1,
        "reloadTime": 0.075,
        "dispersion": 0.000261799,
        # Class: CfgWeapons\rhs_weap_saw_base\FullAuto\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_m249_shot_soundset","jsrs_5x56mm_reverb_soundset"]
        },
        # Class: CfgWeapons\rhs_weap_saw_base\FullAuto\SilencedSound [Indent level: 2],
        "SilencedSound": {
            "soundSetShot": ["jsrs_m249_shot_silenced_soundset","jsrs_6x5mm_sd_reverb_soundset"]
        },
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons\rhs_weap_saw_base\FullAuto\BaseSoundModeType [Indent level: 2],
        "BaseSoundModeType": {
        },
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "soundContinuous": 0,
        "autoFire": 1,
        "displayName": "Full",
        "textureType": "fullAuto",
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1
    },
    # Class: CfgWeapons\rhs_weap_saw_base\far_optic1 [Indent level: 1],
    "far_optic1": {
        "requiredOpticType": 1,
        "burst": 3,
        "burstRangeMax": 6,
        "aiRateOfFire": 5,
        "aiRateOfFireDispersion": 4,
        "aiRateOfFireDistance": 900,
        "minRange": 350,
        "minRangeProbab": 0.039,
        "midRange": 550,
        "midRangeProbab": 0.5,
        "maxRange": 700,
        "maxRangeProbab": 0.1,
        "showToPlayer": 0,
        "aiBurstTerminable": 1,
        "reloadTime": 0.075,
        "dispersion": 0.000261799,
        # Class: CfgWeapons\rhs_weap_saw_base\FullAuto\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_m249_shot_soundset","jsrs_5x56mm_reverb_soundset"]
        },
        # Class: CfgWeapons\rhs_weap_saw_base\FullAuto\SilencedSound [Indent level: 2],
        "SilencedSound": {
            "soundSetShot": ["jsrs_m249_shot_silenced_soundset","jsrs_6x5mm_sd_reverb_soundset"]
        },
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons\rhs_weap_saw_base\FullAuto\BaseSoundModeType [Indent level: 2],
        "BaseSoundModeType": {
        },
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "soundContinuous": 0,
        "autoFire": 1,
        "displayName": "Full",
        "textureType": "fullAuto",
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0
    },
    # Class: CfgWeapons\rhs_weap_saw_base\far_optic2 [Indent level: 1],
    "far_optic2": {
        "requiredOpticType": 2,
        "autoFire": 0,
        "burst": 1,
        "burstRangeMax": 3,
        "minRange": 400,
        "minRangeProbab": 0.05,
        "midRange": 800,
        "midRangeProbab": 0.5,
        "maxRange": 1000,
        "maxRangeProbab": 0.1,
        "aiRateOfFire": 5,
        "aiRateOfFireDispersion": 4,
        "aiRateOfFireDistance": 900,
        "showToPlayer": 0,
        "aiBurstTerminable": 1,
        "reloadTime": 0.075,
        "dispersion": 0.000261799,
        # Class: CfgWeapons\rhs_weap_saw_base\FullAuto\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["jsrs_m249_shot_soundset","jsrs_5x56mm_reverb_soundset"]
        },
        # Class: CfgWeapons\rhs_weap_saw_base\FullAuto\SilencedSound [Indent level: 2],
        "SilencedSound": {
            "soundSetShot": ["jsrs_m249_shot_silenced_soundset","jsrs_6x5mm_sd_reverb_soundset"]
        },
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons\rhs_weap_saw_base\FullAuto\BaseSoundModeType [Indent level: 2],
        "BaseSoundModeType": {
        },
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "soundContinuous": 0,
        "displayName": "Full",
        "textureType": "fullAuto",
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0
    },
    "muzzles": ["this","SAFE"],
    # Class: CfgWeapons\rhs_weap_saw_base\SAFE [Indent level: 1],
    "SAFE": {
        "discreteDistanceCameraPoint": ["eye"],
        "cameraDir": "eye_look",
        "magazines": [],
        "displayName": "SAFE",
        "descriptionShort": "SAFE",
        "showToPlayer": 0,
        "modes": ["Safe"],
        "discreteDistance": [0],
        "discreteDistanceInitIndex": 0,
        "drySound": ["A3|Sounds_F|arsenal|weapons|Rifles|MX|dry_Mx",0.562341,1,10],
        "changeFiremodeSound": ["A3|sounds_f|weapons|closure|firemode_changer_2",0.551189,1,5],
        # Class: CfgWeapons\RHSUSF_SAFE_BASE\Safe [Indent level: 1],
        "Safe": {
            "sounds": [],
            "displayName": "SAFE",
            "descriptionShort": "SAFE",
            "showToPlayer": 0,
            "minRange": 0,
            "minRangeProbab": 0.001,
            "midRange": 0.001,
            "midRangeProbab": 0.001,
            "maxRange": 0.001,
            "maxRangeProbab": 0.001,
            "multiplier": 1,
            "burst": 1,
            "burstRangeMax": -1,
            "dispersion": 0.0002,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "soundContinuous": 0,
            "weaponSoundEffect": "",
            "reloadTime": 0.1,
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "autoFire": 0,
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "textureType": "semi",
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1,
            "aiRateOfFire": 2,
            "aiRateOfFireDispersion": 1,
            "aiRateOfFireDistance": 500
        },
        "scope": 0,
        "weaponInfoType": "RscWeaponZeroing",
        "recoil": "recoil_default",
        "deployedPivot": "bipod",
        # Class: CfgWeapons\Rifle_Base_F\GunParticles [Indent level: 1],
        "GunParticles": {
            # Class: CfgWeapons\Rifle_Base_F\GunParticles\FirstEffect [Indent level: 2]
            "FirstEffect": {
                "effectName": "RifleAssaultCloud",
                "positionName": "Usti hlavne",
                "directionName": "Konec hlavne"
            }
        },
        # Class: CfgWeapons\Rifle_Base_F\Eventhandlers [Indent level: 1],
        "Eventhandlers": {
            # Class: CfgWeapons\Rifle_Base_F\Eventhandlers\GSM_popMagRifle [Indent level: 2]
            "GSM_popMagRifle": {
                "fired": "_this call GSM_fnc_detectReload"
            }
        },
        # Class: CfgWeapons\Rifle_Base_F\WeaponSlotsInfo [Indent level: 1],
        "WeaponSlotsInfo": {
            "mass": 2,
            # Class: CfgWeapons\Rifle\WeaponSlotsInfo\MuzzleSlot [Indent level: 2],
            "MuzzleSlot": {
                "linkProxy": "A3|data_f|proxies|weapon_slots|MUZZLE",
                "displayName": "$str_a3_cfgweapons_abr_base_f_weaponslotsinfo_muzzleslot0",
                "compatibleItems": [],
                "iconPicture": "A3|Weapons_F|Data|UI|attachment_muzzle.paa",
                "iconPinpoint": "Center",
                "access": 1,
                "scope": 0,
                "iconPosition": [0,0],
                "iconScale": 0
            },
            # Class: CfgWeapons\Rifle\WeaponSlotsInfo\CowsSlot [Indent level: 2],
            "CowsSlot": {
                "compatibleItems": ["optic_Nightstalker","optic_tws","optic_tws_mg","optic_NVS","optic_DMS","optic_LRPS","optic_ams","optic_AMS_snd","optic_AMS_khk","optic_KHS_blk","optic_KHS_tan","optic_KHS_hex","optic_KHS_old","optic_SOS","optic_MRCO","optic_Arco","optic_aco","optic_ACO_grn","optic_aco_smg","optic_ACO_grn_smg","optic_hamr","optic_Holosight","optic_Holosight_smg","optic_Hamr_khk_F","optic_SOS_khk_F","optic_Arco_ghex_F","optic_Arco_blk_F","optic_DMS_ghex_F","optic_ERCO_blk_F","optic_ERCO_khk_F","optic_ERCO_snd_F","optic_LRPS_ghex_F","optic_LRPS_tna_F","optic_Holosight_blk_F","optic_Holosight_khk_F","optic_Holosight_smg_blk_F","optic_Holosight_smg_khk_F","optic_Arco_AK_blk_F","optic_Arco_AK_lush_F","optic_Arco_AK_arid_F","optic_DMS_weathered_F","optic_DMS_weathered_Kir_F","optic_Arco_lush_F","optic_Arco_arid_F","optic_Holosight_lush_F","optic_Holosight_arid_F","ACE_optic_Hamr_2D","ACE_optic_Hamr_PIP","ACE_optic_Arco_2D","ACE_optic_Arco_PIP","ACE_optic_MRCO_2D","ACE_optic_MRCO_PIP","ACE_optic_SOS_2D","ACE_optic_SOS_PIP","ACE_optic_LRPS_2D","ACE_optic_LRPS_PIP"],
                "linkProxy": "A3|data_f|proxies|weapon_slots|TOP",
                "displayName": "Optics Slot",
                "iconPicture": "A3|Weapons_F|Data|UI|attachment_top.paa",
                "iconPinpoint": "Bottom",
                "access": 1,
                "scope": 0,
                "iconPosition": [0,0],
                "iconScale": 0
            },
            # Class: CfgWeapons\Rifle\WeaponSlotsInfo\PointerSlot [Indent level: 2],
            "PointerSlot": {
                "compatibleItems": ["acc_flashlight","acc_pointer_IR","ACE_acc_pointer_red","ACE_acc_pointer_green_IR","ACE_acc_pointer_green"],
                "iconPicture": "A3|Weapons_F|Data|UI|attachment_side.paa",
                "iconPinpoint": "Center",
                "linkProxy": "A3|data_f|proxies|weapon_slots|SIDE",
                "displayName": "Pointer Slot",
                "access": 1,
                "scope": 0,
                "iconPosition": [0,0],
                "iconScale": 0
            },
            "allowedSlots": [901]
        },
        "htMin": 1,
        "htMax": 600,
        "afMax": 0,
        "mfMax": 0,
        "mFact": 1,
        "tBody": 100,
        "autoFire": 1,
        "reloadAction": "ReloadMagazine",
        "soundContinuous": 0,
        "optics": 0,
        "cursor": "arifle",
        "cursoraim": "CursorAim",
        "value": 4,
        "nameSound": "rifle",
        "reloadTime": 0.15,
        "modelOptics": "-",
        "sound": [],
        "opticsFlare": 0,
        "autoReload": 0,
        "aiDispersionCoefX": 6,
        "aiDispersionCoefY": 6,
        "opticsZoomMin": 0.25,
        "opticsZoomMax": 1.25,
        "opticsZoomInit": 0.75,
        "distanceZoomMin": 300,
        "distanceZoomMax": 300,
        "maxLeadSpeed": 23,
        "canLock": 0,
        "flash": "gunfire",
        "flashSize": 0.5,
        "dispersion": 0.00029,
        "recoilProne": "assaultRifleBase",
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "ffCount": 3,
        "weaponPoolAvailable": 1,
        "maxZeroing": 1000,
        "zeroingSound": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|noises|rifle_zeroing_1.ogg",5,1,5],
        "ace_overheating_mrbs": 3000,
        "ace_overheating_dispersion": 1,
        "ace_overheating_slowdownFactor": 1,
        "type": 1,
        "dexterity": 1.7,
        "aiRateOfFire": 0.5,
        "aiRateOfFireDistance": 500,
        "inertia": 0.5,
        "access": 3,
        "picture": "",
        "uiPicture": "",
        "ammo": "",
        "cursorSize": 1,
        "showAimCursorInternal": 1,
        "cursorAimOn": "",
        "laser": 0,
        "hiddenSelections": [],
        "hiddenSelectionsTextures": [],
        "hiddenUnderwaterSelections": [],
        "shownUnderwaterSelections": [],
        "hiddenUnderwaterSelectionsTextures": [],
        "simulation": "Weapon",
        "count": 0,
        "multiplier": 1,
        "burst": 1,
        "magazineReloadTime": 0,
        "magazineReloadSwitchPhase": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": ["sound",1],
        "soundLoop": ["sound",1],
        "weaponSoundEffect": "",
        "soundBurst": 1,
        "reloadSound": ["",1,1],
        "reloadMagazineSound": ["",1,1],
        "emptySound": ["",1,1],
        "soundBullet": ["emptySound",1],
        "initSpeed": 0,
        "ballisticsComputer": 0,
        "irDistance": 0,
        "irDotIntensity": 0.001,
        "lockAcquire": 1,
        "enableAttack": 1,
        "maxRecoilSway": 0.008,
        "swayDecaySpeed": 2,
        "model": "",
        "modelSpecial": "",
        "modelMagazine": "",
        "muzzlePos": "usti hlavne",
        "muzzleEnd": "konec hlavne",
        "irLaserPos": "laser pos",
        "irLaserEnd": "laser dir",
        "cartridgePos": "nabojnicestart",
        "cartridgeVel": "nabojniceend",
        "selectionFireAnim": "zasleh",
        "memoryPointCamera": "eye",
        "fireSpreadAngle": 3,
        "useModelOptics": 1,
        "opticsID": 0,
        "opticsPPEffects": [],
        "forceOptics": 0,
        "useAsBinocular": 0,
        "opticsDisablePeripherialVision": 0.67,
        "primary": 10,
        "showSwitchAction": 0,
        "showEmpty": 1,
        "canShootInWater": 0,
        "aiRateOfFireDispersion": 0,
        "fireLightDuration": 0.05,
        "fireLightIntensity": 0.2,
        "fireLightDiffuse": [0.937,0.631,0.259],
        "fireLightAmbient": [0,0,0],
        "backgroundReload": 0,
        "muzzles": ["this"],
        "useAction": 0,
        "useActionTitle": "",
        "canDrop": 1,
        "weaponLockDelay": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "weight": 0,
        "minRange": 1,
        "minRangeProbab": 0.3,
        "midRange": 150,
        "midRangeProbab": 0.58,
        "maxRange": 500,
        "maxRangeProbab": 0.04,
        "handAnim": [],
        "lockingTargetSound": ["",0.000316228,2],
        "lockedTargetSound": ["",0.000316228,6],
        "detectRange": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "fireAnims": [],
        # Class: CfgWeapons\Default\Library [Indent level: 1],
        "Library": {
            "libTextDesc": ""
        },
        # Class: CfgWeapons\Default\GunFire [Indent level: 1],
        "GunFire": {
            "access": 0,
            "cloudletDuration": 0.2,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletAlpha": 1,
            "cloudletGrowUp": 0.2,
            "cloudletFadeIn": 0.01,
            "cloudletFadeOut": 0.5,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "cloudletShape": "cloudletFire",
            "cloudletColor": [1,1,1,0],
            "cloudletDensityCoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourceSize": 0.5,
            "timeToLive": 0,
            "initT": 4500,
            "deltaT": -3000,
            # Class: CfgWeapons\Default\GunFire\Table [Indent level: 2],
            "Table": {
                # Class: CfgWeapons\Default\GunFire\Table\T0 [Indent level: 3]
                "T0": {
                    "maxT": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T1 [Indent level: 3],
                "T1": {
                    "maxT": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T2 [Indent level: 3],
                "T2": {
                    "maxT": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T3 [Indent level: 3],
                "T3": {
                    "maxT": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T4 [Indent level: 3],
                "T4": {
                    "maxT": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T5 [Indent level: 3],
                "T5": {
                    "maxT": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T6 [Indent level: 3],
                "T6": {
                    "maxT": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T7 [Indent level: 3],
                "T7": {
                    "maxT": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T8 [Indent level: 3],
                "T8": {
                    "maxT": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T9 [Indent level: 3],
                "T9": {
                    "maxT": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T10 [Indent level: 3],
                "T10": {
                    "maxT": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T11 [Indent level: 3],
                "T11": {
                    "maxT": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T12 [Indent level: 3],
                "T12": {
                    "maxT": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T13 [Indent level: 3],
                "T13": {
                    "maxT": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T14 [Indent level: 3],
                "T14": {
                    "maxT": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T15 [Indent level: 3],
                "T15": {
                    "maxT": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T16 [Indent level: 3],
                "T16": {
                    "maxT": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T17 [Indent level: 3],
                "T17": {
                    "maxT": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T18 [Indent level: 3],
                "T18": {
                    "maxT": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T19 [Indent level: 3],
                "T19": {
                    "maxT": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T20 [Indent level: 3],
                "T20": {
                    "maxT": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T21 [Indent level: 3],
                "T21": {
                    "maxT": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T22 [Indent level: 3],
                "T22": {
                    "maxT": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        # Class: CfgWeapons\Default\GunClouds [Indent level: 1],
        "GunClouds": {
            "access": 0,
            "cloudletGrowUp": 0.05,
            "cloudletFadeIn": 0,
            "cloudletFadeOut": 0.1,
            "cloudletDuration": 0.05,
            "cloudletAlpha": 0.3,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "interval": -0.02,
            "size": 0.3,
            "sourceSize": 0.02,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletShape": "cloudletClouds",
            "cloudletColor": [1,1,1,0],
            "timeToLive": 0,
            "initT": 0,
            "deltaT": 0,
            # Class: CfgWeapons\Default\GunClouds\Table [Indent level: 2],
            "Table": {
                # Class: CfgWeapons\Default\GunClouds\Table\T0 [Indent level: 3]
                "T0": {
                    "maxT": 0,
                    "color": [1,1,1,0]
                }
            }
        },
        "textureType": "default",
        "aimTransitionSpeed": 1
    },
    "magazineReloadSwitchPhase": 0.56,
    "WW2_boltSnapSound": "RHSUSF_boltSnap_m249",
    "WW2_boltSnapDelay": 0.075,
    # Class: CfgWeapons\rhs_weap_saw_base\Eventhandlers [Indent level: 1],
    "Eventhandlers": {
        # Class: CfgWeapons\rhs_weap_saw_base\Eventhandlers\RHSUSF_weapon_firedSoundHandler [Indent level: 2]
        "RHSUSF_weapon_firedSoundHandler": {
            "fired": "_this params ['_unit','_weapon']; [_unit,_weapon,['RHSUSF_rattle_m249_1','RHSUSF_rattle_m249_2','RHSUSF_rattle_m249_3','RHSUSF_rattle_m249_4','RHSUSF_rattle_m249_5','RHSUSF_rattle_m249_6'],3] call RHSUSF_fnc_beltRattle; [_unit,_weapon,'RHSUSF_boltSnap_m249'] call RHSUSF_fnc_boltSnap;"
        },
        # Class: CfgWeapons\Rifle_Base_F\Eventhandlers\GSM_popMagRifle [Indent level: 2],
        "GSM_popMagRifle": {
            "fired": "_this call GSM_fnc_detectReload"
        }
    },
    "ACE_Overheating_allowSwapBarrel": 1,
    "htMin": 1,
    "htMax": 600,
    "afMax": 0,
    "mfMax": 0,
    "mFact": 1,
    "tBody": 100,
    "autoFire": 1,
    "soundContinuous": 0,
    "optics": 0,
    "value": 4,
    "reloadTime": 0.15,
    "modelOptics": "-",
    "sound": [],
    "opticsFlare": 0,
    "autoReload": 0,
    "maxLeadSpeed": 23,
    "canLock": 0,
    "flash": "gunfire",
    "flashSize": 0.5,
    "dispersion": 0.00029,
    "recoilProne": "assaultRifleBase",
    "ffMagnitude": 0.5,
    "ffFrequency": 11,
    "ffCount": 3,
    "weaponPoolAvailable": 1,
    "zeroingSound": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|noises|rifle_zeroing_1.ogg",5,1,5],
    "ace_overheating_mrbs": 3000,
    "ace_overheating_dispersion": 1,
    "ace_overheating_slowdownFactor": 1,
    "type": 1,
    "aiRateOfFire": 0.5,
    "aiRateOfFireDistance": 500,
    "access": 3,
    "ammo": "",
    "cursorSize": 1,
    "showAimCursorInternal": 1,
    "cursorAimOn": "",
    "laser": 0,
    "hiddenUnderwaterSelections": [],
    "shownUnderwaterSelections": [],
    "hiddenUnderwaterSelectionsTextures": [],
    "simulation": "Weapon",
    "count": 0,
    "multiplier": 1,
    "burst": 1,
    "magazineReloadTime": 0,
    "soundBegin": ["sound",1],
    "soundBeginWater": ["sound",1],
    "soundClosure": ["sound",1],
    "soundEnd": ["sound",1],
    "soundLoop": ["sound",1],
    "weaponSoundEffect": "",
    "soundBurst": 1,
    "reloadSound": ["",1,1],
    "changeFiremodeSound": ["",1,1],
    "emptySound": ["",1,1],
    "ballisticsComputer": 0,
    "irDistance": 0,
    "irDotIntensity": 0.001,
    "lockAcquire": 1,
    "enableAttack": 1,
    "modelSpecial": "",
    "modelMagazine": "",
    "muzzlePos": "usti hlavne",
    "muzzleEnd": "konec hlavne",
    "irLaserPos": "laser pos",
    "irLaserEnd": "laser dir",
    "cartridgePos": "nabojnicestart",
    "cartridgeVel": "nabojniceend",
    "selectionFireAnim": "zasleh",
    "memoryPointCamera": "eye",
    "fireSpreadAngle": 3,
    "useModelOptics": 1,
    "opticsID": 0,
    "opticsPPEffects": [],
    "forceOptics": 0,
    "useAsBinocular": 0,
    "opticsDisablePeripherialVision": 0.67,
    "primary": 10,
    "showSwitchAction": 0,
    "showEmpty": 1,
    "showToPlayer": 1,
    "canShootInWater": 0,
    "aiRateOfFireDispersion": 0,
    "fireLightDuration": 0.05,
    "fireLightIntensity": 0.2,
    "fireLightDiffuse": [0.937,0.631,0.259],
    "fireLightAmbient": [0,0,0],
    "backgroundReload": 0,
    "useAction": 0,
    "useActionTitle": "",
    "canDrop": 1,
    "weaponLockDelay": 0,
    "weaponLockSystem": 0,
    "cmImmunity": 1,
    "weight": 0,
    "minRange": 1,
    "minRangeProbab": 0.3,
    "midRange": 150,
    "midRangeProbab": 0.58,
    "maxRange": 500,
    "maxRangeProbab": 0.04,
    "lockingTargetSound": ["",0.000316228,2],
    "lockedTargetSound": ["",0.000316228,6],
    "detectRange": 0,
    "artilleryDispersion": 1,
    "artilleryCharge": 1,
    "fireAnims": [],
    # Class: CfgWeapons\Default\GunFire [Indent level: 1],
    "GunFire": {
        "access": 0,
        "cloudletDuration": 0.2,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 0.2,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 0.5,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletFire",
        "cloudletColor": [1,1,1,0],
        "cloudletDensityCoef": -1,
        "interval": -0.01,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 4500,
        "deltaT": -3000,
        # Class: CfgWeapons\Default\GunFire\Table [Indent level: 2],
        "Table": {
            # Class: CfgWeapons\Default\GunFire\Table\T0 [Indent level: 3]
            "T0": {
                "maxT": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T1 [Indent level: 3],
            "T1": {
                "maxT": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T2 [Indent level: 3],
            "T2": {
                "maxT": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T3 [Indent level: 3],
            "T3": {
                "maxT": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T4 [Indent level: 3],
            "T4": {
                "maxT": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T5 [Indent level: 3],
            "T5": {
                "maxT": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T6 [Indent level: 3],
            "T6": {
                "maxT": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T7 [Indent level: 3],
            "T7": {
                "maxT": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T8 [Indent level: 3],
            "T8": {
                "maxT": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T9 [Indent level: 3],
            "T9": {
                "maxT": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T10 [Indent level: 3],
            "T10": {
                "maxT": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T11 [Indent level: 3],
            "T11": {
                "maxT": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T12 [Indent level: 3],
            "T12": {
                "maxT": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T13 [Indent level: 3],
            "T13": {
                "maxT": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T14 [Indent level: 3],
            "T14": {
                "maxT": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T15 [Indent level: 3],
            "T15": {
                "maxT": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T16 [Indent level: 3],
            "T16": {
                "maxT": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T17 [Indent level: 3],
            "T17": {
                "maxT": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T18 [Indent level: 3],
            "T18": {
                "maxT": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T19 [Indent level: 3],
            "T19": {
                "maxT": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T20 [Indent level: 3],
            "T20": {
                "maxT": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T21 [Indent level: 3],
            "T21": {
                "maxT": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T22 [Indent level: 3],
            "T22": {
                "maxT": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgWeapons\Default\GunClouds [Indent level: 1],
    "GunClouds": {
        "access": 0,
        "cloudletGrowUp": 0.05,
        "cloudletFadeIn": 0,
        "cloudletFadeOut": 0.1,
        "cloudletDuration": 0.05,
        "cloudletAlpha": 0.3,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "interval": -0.02,
        "size": 0.3,
        "sourceSize": 0.02,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletShape": "cloudletClouds",
        "cloudletColor": [1,1,1,0],
        "timeToLive": 0,
        "initT": 0,
        "deltaT": 0,
        # Class: CfgWeapons\Default\GunClouds\Table [Indent level: 2],
        "Table": {
            # Class: CfgWeapons\Default\GunClouds\Table\T0 [Indent level: 3]
            "T0": {
                "maxT": 0,
                "color": [1,1,1,0]
            }
        }
    },
    "textureType": "default",
}