rhs_weap_g36kv = {
    "picture": "rhssaf|addons|rhssaf_inventoryicons|data|weapons|rhs_weap_g36kv_ca.paa",
    "dlc": "RHS_SAF",
    "author": "Red Hammer Studios",
    "scope": 2,
    "displayName": "HK G36KV",
    "reloadAction": "RHS_GestureReloadG36V",
    "reloadmagazinesound": ["rhssaf|addons|rhssaf_sounds|G36|G36EV_reload",0.9,1,35],
    "model": "rhssaf|addons|rhssaf_m_weapon_g36|rhssaf_g36k",
    "hiddenSelections": ["Reciever","Optics","Magwell","Stock","AG36"],
    "hiddenSelectionsTextures": ["rhssaf|addons|rhssaf_t_weapon_g36|data|commonmaps|g36_commonmap_kv_co.paa","rhssaf|addons|rhssaf_t_weapon_g36|data|placeholder|g36_opticrails_co.paa","rhssaf|addons|rhssaf_t_weapon_g36|data|placeholder|g36_magwell_co.paa","rhssaf|addons|rhssaf_t_weapon_g36|data|placeholder|g36_stockfurniture_co.paa","rhssaf|addons|rhssaf_t_weapon_g36|data|placeholder|g36_ag36_co.paa"],
    "discretedistance": [300],
    "discretedistanceinitindex": 0,
    # Class: CfgWeapons\rhs_weap_g36kv\WeaponSlotsInfo [Indent level: 1],
    "WeaponSlotsInfo": {
        "mass": 74.14,
        "allowedSlots": [901],
        # Class: CfgWeapons\rhs_weap_g36kv\WeaponSlotsInfo\UnderBarrelSlot [Indent level: 2],
        "UnderBarrelSlot": {
        },
        # Class: CfgWeapons\rhs_weap_g36kv\WeaponSlotsInfo\CowsSlot [Indent level: 2],
        "CowsSlot": {
            # Class: asdg_OpticRail1913_short\compatibleItems [Indent level: 0]
            "compatibleItems": {
                "rhsusf_acc_LEUPOLDMK4": 0,
                "rhsusf_acc_LEUPOLDMK4_d": 0,
                "rhsusf_acc_LEUPOLDMK4_wd": 0,
                "rhsusf_acc_LEUPOLDMK4_2": 0,
                "rhsusf_acc_LEUPOLDMK4_2_d": 0,
                "rhsusf_acc_LEUPOLDMK4_2_MRDS": 0,
                "rhsusf_acc_premier": 0,
                "rhsusf_acc_premier_low": 0,
                "rhsusf_acc_premier_anpvs27": 0,
                "rhsusf_acc_ACOG_anpvs27": 0,
                "rhsusf_acc_SpecterDR_pvs27": 0,
                "rhs_acc_rakursPM": 1,
                "rhs_acc_dh520x56": 1,
                "rhs_acc_ekp8_18": 1,
                "rhs_acc_ekp8_18b": 1,
                "rhs_acc_ekp8_18c": 1,
                "rhs_acc_ekp8_18d": 1,
                "rhs_acc_1p87": 1,
                "rhs_acc_okp7_picatinny": 1,
                "optic_Nightstalker": 1,
                "optic_tws": 1,
                "optic_tws_mg": 1,
                "optic_NVS": 1,
                "optic_SOS": 1,
                "optic_SOS_khk_F": 1,
                "optic_MRCO": 1,
                "optic_Arco": 1,
                "optic_Arco_ghex_F": 1,
                "optic_Arco_blk_F": 1,
                "optic_aco": 1,
                "optic_ACO_grn": 1,
                "optic_aco_smg": 1,
                "optic_ACO_grn_smg": 1,
                "optic_hamr": 1,
                "optic_Hamr_khk_F": 1,
                "optic_Holosight": 1,
                "optic_Holosight_smg": 1,
                "optic_Holosight_blk_F": 1,
                "optic_Holosight_khk_F": 1,
                "optic_Holosight_smg_blk_F": 1,
                "optic_DMS": 1,
                "optic_DMS_ghex_F": 1,
                "optic_LRPS": 1,
                "optic_LRPS_ghex_F": 1,
                "optic_LRPS_tna_F": 1,
                "optic_AMS": 1,
                "optic_AMS_khk": 1,
                "optic_AMS_snd": 1,
                "optic_KHS_blk": 1,
                "optic_KHS_hex": 1,
                "optic_KHS_old": 1,
                "optic_KHS_tan": 1,
                "optic_ERCO_blk_F": 1,
                "optic_ERCO_khk_F": 1,
                "optic_ERCO_snd_F": 1,
                "rhsusf_acc_premier_mrds": 1,
                "rhsusf_acc_M8541": 1,
                "rhsusf_acc_M8541_mrds": 1,
                "rhsusf_acc_M8541_low": 1,
                "rhsusf_acc_M8541_low_d": 1,
                "rhsusf_acc_M8541_low_wd": 1,
                "rhsusf_acc_EOTECH": 1,
                "rhsusf_acc_eotech_552": 1,
                "rhsusf_acc_eotech_552_d": 1,
                "rhsusf_acc_eotech_552_wd": 1,
                "rhsusf_acc_eotech_xps3": 1,
                "rhsusf_acc_g33_xps3": 1,
                "rhsusf_acc_g33_xps3_flip": 1,
                "rhsusf_acc_g33_xps3_tan": 1,
                "rhsusf_acc_g33_xps3_tan_flip": 1,
                "rhsusf_acc_g33_t1": 1,
                "rhsusf_acc_g33_t1_flip": 1,
                "rhsusf_acc_compm4": 1,
                "rhsusf_acc_T1_high": 1,
                "rhsusf_acc_T1_low": 1,
                "rhsusf_acc_RX01": 1,
                "rhsusf_acc_RX01_NoFilter": 1,
                "rhsusf_acc_RX01_tan": 1,
                "rhsusf_acc_RX01_NoFilter_tan": 1,
                "rhsusf_acc_RM05": 1,
                "rhsusf_acc_mrds": 1,
                "rhsusf_acc_mrds_c": 1,
                "rhsusf_acc_ACOG": 1,
                "rhsusf_acc_ACOG2": 1,
                "rhsusf_acc_ACOG3": 1,
                "rhsusf_acc_ACOG_wd": 1,
                "rhsusf_acc_ACOG_d": 1,
                "rhsusf_acc_ACOG_sa": 1,
                "rhsusf_acc_ACOG_USMC": 1,
                "rhsusf_acc_ACOG2_USMC": 1,
                "rhsusf_acc_ACOG3_USMC": 1,
                "rhsusf_acc_ACOG_RMR": 1,
                "rhsusf_acc_ACOG_PIP": 1,
                "rhsusf_acc_ACOG2_pip": 1,
                "rhsusf_acc_ACOG3_pip": 1,
                "rhsusf_acc_ACOG_wd_pip": 1,
                "rhsusf_acc_ACOG_d_pip": 1,
                "rhsusf_acc_ACOG_sa_pip": 1,
                "rhsusf_acc_ACOG_USMC_pip": 1,
                "rhsusf_acc_ACOG2_USMC_pip": 1,
                "rhsusf_acc_ACOG3_USMC_pip": 1,
                "rhsusf_acc_ACOG_RMR_PIP": 1,
                "rhsusf_acc_ACOG_3d": 1,
                "rhsusf_acc_ACOG2_3d": 1,
                "rhsusf_acc_ACOG3_3d": 1,
                "rhsusf_acc_ACOG_wd_3d": 1,
                "rhsusf_acc_ACOG_d_3d": 1,
                "rhsusf_acc_ACOG_sa_3d": 1,
                "rhsusf_acc_ACOG_USMC_3d": 1,
                "rhsusf_acc_ACOG2_USMC_3d": 1,
                "rhsusf_acc_ACOG3_USMC_3d": 1,
                "rhsusf_acc_ACOG_RMR_3d": 1,
                "rhsusf_acc_ELCAN": 1,
                "rhsusf_acc_ELCAN_ard": 1,
                "rhsusf_acc_ELCAN_3d": 1,
                "rhsusf_acc_ELCAN_ard_3d": 1,
                "rhsusf_acc_ELCAN_PIP": 1,
                "rhsusf_acc_ELCAN_ard_PIP": 1,
                "rhsusf_acc_su230": 1,
                "rhsusf_acc_su230_mrds": 1,
                "rhsusf_acc_su230a": 1,
                "rhsusf_acc_su230a_mrds": 1,
                "rhsusf_acc_su230_c": 1,
                "rhsusf_acc_su230_mrds_c": 1,
                "rhsusf_acc_su230a_c": 1,
                "rhsusf_acc_su230a_mrds_c": 1,
                "rhsusf_acc_su230_3d": 1,
                "rhsusf_acc_su230_mrds_3d": 1,
                "rhsusf_acc_su230a_3d": 1,
                "rhsusf_acc_su230a_mrds_3d": 1,
                "rhsusf_acc_su230_c_3d": 1,
                "rhsusf_acc_su230_mrds_c_3d": 1,
                "rhsusf_acc_su230a_c_3d": 1,
                "rhsusf_acc_su230a_mrds_c_3d": 1,
                "rhsusf_acc_SpecterDR": 1,
                "rhsusf_acc_SpecterDR_3d": 1,
                "rhsusf_acc_SpecterDR_A": 1,
                "rhsusf_acc_SpecterDR_A_3d": 1,
                "rhsusf_acc_SpecterDR_CX": 1,
                "rhsusf_acc_SpecterDR_CX_3D": 1,
                "rhsusf_acc_SpecterDR_D": 1,
                "rhsusf_acc_SpecterDR_OD": 1,
                "rhsusf_acc_SpecterDR_D_3D": 1,
                "rhsusf_acc_SpecterDR_OD_3D": 1,
                "rhsusf_acc_anpvs27": 1,
                "rhsusf_acc_anpas13gv1": 1,
                "rhsusf_acc_M2A1": 1,
                "rhsusf_acc_ACOG_MDO": 1,
                "rhsgref_acc_RX01_camo": 1,
                "rhsgref_acc_RX01_NoFilter_camo": 1
            },
            "linkProxy": "A3|data_f|proxies|weapon_slots|TOP",
            "displayName": "Optics Slot"
        },
        # Class: CfgWeapons\rhs_weap_g36kv\WeaponSlotsInfo\PointerSlot [Indent level: 2],
        "PointerSlot": {
            "iconPosition": [0,0],
            "iconScale": 1,
            "iconPicture": "A3|Weapons_F|Data|clear_empty.paa",
            "iconPinPoint": "Left",
            # Class: rhs_western_rifle_laser_slot\compatibleItems [Indent level: 0],
            "compatibleItems": {
                "rhsusf_acc_anpeq15": 0,
                "rhsusf_acc_anpeq15_top": 0,
                "rhsusf_acc_anpeq15_light": 0,
                "rhsusf_acc_anpeq15_bk": 0,
                "rhsusf_acc_anpeq15_bk_top": 0,
                "rhsusf_acc_anpeq15_bk_light": 0,
                "rhsusf_acc_anpeq15_wmx": 0,
                "rhsusf_acc_anpeq15_wmx_light": 0,
                "rhsusf_acc_anpeq16a_top": 0,
                "rhsusf_acc_anpeq16a_light_top": 0,
                "rhsusf_acc_anpeq16a_top_h": 0,
                "rhsusf_acc_anpeq16a_light_top_h": 0,
                "rhs_acc_2dpZenit_ris": 1,
                "rhs_acc_perst1ik_ris": 1,
                "rhs_acc_perst3": 1,
                "acc_flashlight": 1,
                "acc_pointer_IR": 1,
                "rhsusf_acc_wmx": 1,
                "rhsusf_acc_wmx_bk": 1,
                "rhsusf_acc_M952V": 1,
                "rhsusf_acc_anpeq15A": 1,
                "rhsusf_acc_anpeq15_h": 1,
                "rhsusf_acc_anpeq15_light_h": 1,
                "rhsusf_acc_anpeq15_top_h": 1,
                "rhsusf_acc_anpeq15_sc": 1,
                "rhsusf_acc_anpeq15_light_sc": 1,
                "rhsusf_acc_anpeq15_top_sc": 1,
                "rhsusf_acc_anpeq15side": 1,
                "rhsusf_acc_anpeq15_bk_h": 1,
                "rhsusf_acc_anpeq15_bk_light_h": 1,
                "rhsusf_acc_anpeq15_bk_top_h": 1,
                "rhsusf_acc_anpeq15_bk_sc": 1,
                "rhsusf_acc_anpeq15_bk_light_sc": 1,
                "rhsusf_acc_anpeq15_bk_top_sc": 1,
                "rhsusf_acc_anpeq15side_bk": 1,
                "rhsusf_acc_anpeq15_wmx_h": 1,
                "rhsusf_acc_anpeq15_wmx_light_h": 1,
                "rhsusf_acc_anpeq15_wmx_sc": 1,
                "rhsusf_acc_anpeq15_wmx_light_sc": 1,
                "rhsusf_acc_anpeq16a": 1,
                "rhsusf_acc_anpeq16a_light": 1,
                "rhsusf_acc_anpeq16a_top_sc": 1,
                "rhsusf_acc_anpeq16a_light_top_sc": 1
            },
            "linkProxy": "a3|data_f|proxies|weapon_slots|side",
            "displayName": "Pointer Slot"
        },
        # Class: CfgWeapons\rhs_weap_g36kv\WeaponSlotsInfo\MuzzleSlot [Indent level: 2],
        "MuzzleSlot": {
            "iconPosition": [0,0],
            "iconScale": 1,
            "iconPicture": "A3|Weapons_F|Data|clear_empty.paa",
            "iconPinPoint": "Left",
            # Class: rhs_western_rifle_muzzle_slot\compatibleItems [Indent level: 0],
            "compatibleItems": {
                "muzzle_snds_M": 0,
                "rhsusf_acc_rotex5_grey": 1,
                "rhsusf_acc_rotex5_tan": 1,
                "rhsusf_acc_SF3P556": 1,
                "rhsusf_acc_SFMB556": 1,
                "rhsusf_acc_nt4_black": 1,
                "rhsusf_acc_nt4_tan": 1
            },
            "displayName": "$str_a3_cfgweapons_abr_base_f_weaponslotsinfo_muzzleslot0",
            "linkProxy": "A3|data_f|proxies|weapon_slots|MUZZLE"
        },
        # Class: CfgWeapons\rhs_weap_g36kv\WeaponSlotsInfo\GripodSlot [Indent level: 2],
        "GripodSlot": {
            "linkProxy": "rhsusf|addons|rhsusf_weapons|rhs_grip_proxy",
            "iconPosition": [0,0],
            # Class: rhs_rifle_gripod_slot\compatibleItems [Indent level: 0],
            "compatibleItems": {
                "rhs_acc_grip_rk2": 1,
                "rhs_acc_grip_rk6": 1,
                "rhs_acc_grip_ffg2": 1,
                "rhsusf_acc_grip1": 1,
                "rhsusf_acc_grip2": 1,
                "rhsusf_acc_grip2_tan": 1,
                "rhsusf_acc_grip2_wd": 1,
                "rhsusf_acc_grip3": 1,
                "rhsusf_acc_grip3_tan": 1,
                "rhsusf_acc_kac_grip": 1,
                "rhsusf_acc_rvg_blk": 1,
                "rhsusf_acc_rvg_de": 1,
                "rhsusf_acc_tacsac_blk": 1,
                "rhsusf_acc_tacsac_tan": 1,
                "rhsusf_acc_tacsac_blue": 1,
                "rhsusf_acc_tdstubby_blk": 1,
                "rhsusf_acc_tdstubby_tan": 1
            },
            "iconScale": 1,
            "iconPicture": "A3|Weapons_F|Data|clear_empty.paa",
            "iconPinPoint": "Left",
            "displayName": "Gripod slot",
            "access": 1,
            "scope": 0
        }
    },
    "rhs_grip1_change": "rhs_weap_g36kv_grip1",
    "rhs_grip2_change": "rhs_weap_g36kv_grip2",
    "rhs_grip3_change": "rhs_weap_g36kv_grip3",
    "baseWeapon": "rhs_weap_g36kv",
    "muzzles": ["this","SAFE"],
    "modes": ["Single","Burst2rnd","FullAuto","single_medium_optics1","single_far_optics2"],
    "weaponInfoType": "rhs_rscOptics_g36kv",
    "inertia": 0.3,
    "dexterity": 1.64958,
    "aimTransitionSpeed": 0.847084,
    "recoil": "rhs_recoil_g36",
    "maxRecoilSway": 0.008,
    "swayDecaySpeed": 1.25,
    "maxZeroing": 1600,
    "deployedpivot": "deploypivot",
    "hasBipod": 0,
    "magazineReloadSwitchPhase": 0.5,
    "magazines": ["rhssaf_30rnd_556x45_EPR_G36","rhssaf_30rnd_556x45_SOST_G36","rhssaf_100rnd_556x45_EPR_G36","rhssaf_30rnd_556x45_SPR_G36","rhssaf_30rnd_556x45_Tracers_G36","rhssaf_30rnd_556x45_MDIM_G36","rhssaf_30rnd_556x45_TDIM_G36","150Rnd_556x45_Drum_Mag_F","150Rnd_556x45_Drum_Mag_Tracer_F"],
    "magazineWell": ["CBA_556x45_G36"],
    # Class: CfgWeapons\rhs_weap_g36_base\Library [Indent level: 1],
    "Library": {
        "libTextDesc": "H&K Gewehr36"
    },
    "aidispersioncoefx": 4,
    "aidispersioncoefy": 6,
    "cameraDir": "",
    "bullet1": ["A3|sounds_f|weapons|shells|7_62|metal_762_01",0.398107,1,15],
    "bullet10": ["A3|sounds_f|weapons|shells|7_62|grass_762_02",0.281838,1,15],
    "bullet11": ["A3|sounds_f|weapons|shells|7_62|grass_762_03",0.281838,1,15],
    "bullet12": ["A3|sounds_f|weapons|shells|7_62|grass_762_04",0.281838,1,15],
    "bullet2": ["A3|sounds_f|weapons|shells|7_62|metal_762_02",0.398107,1,15],
    "bullet3": ["A3|sounds_f|weapons|shells|7_62|metal_762_03",0.398107,1,15],
    "bullet4": ["A3|sounds_f|weapons|shells|7_62|metal_762_04",0.398107,1,15],
    "bullet5": ["A3|sounds_f|weapons|shells|7_62|dirt_762_01",0.281838,1,15],
    "bullet6": ["A3|sounds_f|weapons|shells|7_62|dirt_762_02",0.281838,1,15],
    "bullet7": ["A3|sounds_f|weapons|shells|7_62|dirt_762_03",0.281838,1,15],
    "bullet8": ["A3|sounds_f|weapons|shells|7_62|dirt_762_04",0.281838,1,15],
    "bullet9": ["A3|sounds_f|weapons|shells|7_62|grass_762_01",0.281838,1,15],
    "drysound": ["rhssaf|addons|rhssaf_sounds|G36|g36_dryfire",1.01,1,10],
    "changeFiremodeSound": ["|rhssaf|addons|rhssaf_sounds|G36|g36_switch",1,1,8],
    "UiPicture": "A3|weapons_f|data|UI|icon_regular_CA.paa",
    "soundbullet": ["bullet1",0.083,"bullet2",0.083,"bullet3",0.083,"bullet4",0.083,"bullet5",0.083,"bullet6",0.083,"bullet7",0.083,"bullet8",0.083,"bullet9",0.083,"bullet10",0.083,"bullet11",0.083,"bullet12",0.083],
    # Class: CfgWeapons\rhs_weap_g36_base\SAFE [Indent level: 1],
    "SAFE": {
        "showToPlayer": 0,
        "magazines": [],
        "displayName": "SAFE",
        "descriptionShort": "SAFE",
        "modes": ["Safe"],
        "discreteDistance": [0],
        "discreteDistanceInitIndex": 0,
        "drySound": ["A3|Sounds_F|arsenal|weapons|Rifles|MX|dry_Mx",0.562341,1,10],
        "changeFiremodeSound": ["A3|sounds_f|weapons|closure|firemode_changer_2",0.551189,1,5],
        # Class: CfgWeapons\RHS_SAFE_BASE\Safe [Indent level: 1],
        "Safe": {
            "sounds": [],
            "displayName": "SAFE",
            "descriptionShort": "SAFE",
            "showToPlayer": 0,
            "minRange": 0,
            "minRangeProbab": 0.001,
            "midRange": 0.001,
            "midRangeProbab": 0.001,
            "maxRange": 0.001,
            "maxRangeProbab": 0.001,
            "multiplier": 1,
            "burst": 1,
            "burstRangeMax": -1,
            "dispersion": 0.0002,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "soundContinuous": 0,
            "weaponSoundEffect": "",
            "reloadTime": 0.1,
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "autoFire": 0,
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "textureType": "semi",
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1,
            "aiRateOfFire": 2,
            "aiRateOfFireDispersion": 1,
            "aiRateOfFireDistance": 500
        },
        "scope": 0,
        "weaponInfoType": "RscWeaponZeroing",
        "recoil": "recoil_default",
        "deployedPivot": "bipod",
        # Class: CfgWeapons\Rifle_Base_F\GunParticles [Indent level: 1],
        "GunParticles": {
            # Class: CfgWeapons\Rifle_Base_F\GunParticles\FirstEffect [Indent level: 2]
            "FirstEffect": {
                "effectName": "RifleAssaultCloud",
                "positionName": "Usti hlavne",
                "directionName": "Konec hlavne"
            }
        },
        "htMin": 1,
        "htMax": 600,
        "afMax": 0,
        "mfMax": 0,
        "mFact": 1,
        "tBody": 100,
        "autoFire": 1,
        "reloadAction": "ReloadMagazine",
        "soundContinuous": 0,
        "optics": 0,
        "cursor": "arifle",
        "cursoraim": "CursorAim",
        "value": 4,
        "nameSound": "rifle",
        "reloadTime": 0.15,
        "modelOptics": "-",
        "sound": [],
        "opticsFlare": 0,
        "autoReload": 0,
        "aiDispersionCoefX": 6,
        "aiDispersionCoefY": 6,
        "opticsZoomMin": 0.25,
        "opticsZoomMax": 1.25,
        "opticsZoomInit": 0.75,
        "distanceZoomMin": 300,
        "distanceZoomMax": 300,
        "maxLeadSpeed": 23,
        "canLock": 0,
        "flash": "gunfire",
        "flashSize": 0.5,
        "dispersion": 0.00029,
        "recoilProne": "assaultRifleBase",
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "ffCount": 3,
        "weaponPoolAvailable": 1,
        "maxZeroing": 1000,
        # Class: CfgWeapons\Rifle\WeaponSlotsInfo [Indent level: 1],
        "WeaponSlotsInfo": {
            "mass": 2,
            # Class: CfgWeapons\Rifle\WeaponSlotsInfo\MuzzleSlot [Indent level: 2],
            "MuzzleSlot": {
                "linkProxy": "A3|data_f|proxies|weapon_slots|MUZZLE",
                "displayName": "$str_a3_cfgweapons_abr_base_f_weaponslotsinfo_muzzleslot0",
                "compatibleItems": [],
                "iconPicture": "A3|Weapons_F|Data|UI|attachment_muzzle.paa",
                "iconPinpoint": "Center",
                "access": 1,
                "scope": 0,
                "iconPosition": [0,0],
                "iconScale": 0
            },
            # Class: CfgWeapons\Rifle\WeaponSlotsInfo\CowsSlot [Indent level: 2],
            "CowsSlot": {
                "compatibleItems": ["optic_Nightstalker","optic_tws","optic_tws_mg","optic_NVS","optic_DMS","optic_LRPS","optic_ams","optic_AMS_snd","optic_AMS_khk","optic_KHS_blk","optic_KHS_tan","optic_KHS_hex","optic_KHS_old","optic_SOS","optic_MRCO","optic_Arco","optic_aco","optic_ACO_grn","optic_aco_smg","optic_ACO_grn_smg","optic_hamr","optic_Holosight","optic_Holosight_smg","optic_Hamr_khk_F","optic_SOS_khk_F","optic_Arco_ghex_F","optic_Arco_blk_F","optic_DMS_ghex_F","optic_ERCO_blk_F","optic_ERCO_khk_F","optic_ERCO_snd_F","optic_LRPS_ghex_F","optic_LRPS_tna_F","optic_Holosight_blk_F","optic_Holosight_khk_F","optic_Holosight_smg_blk_F","optic_Holosight_smg_khk_F","optic_Arco_AK_blk_F","optic_Arco_AK_lush_F","optic_Arco_AK_arid_F","optic_DMS_weathered_F","optic_DMS_weathered_Kir_F","optic_Arco_lush_F","optic_Arco_arid_F","optic_Holosight_lush_F","optic_Holosight_arid_F"],
                "linkProxy": "A3|data_f|proxies|weapon_slots|TOP",
                "displayName": "Optics Slot",
                "iconPicture": "A3|Weapons_F|Data|UI|attachment_top.paa",
                "iconPinpoint": "Bottom",
                "access": 1,
                "scope": 0,
                "iconPosition": [0,0],
                "iconScale": 0
            },
            # Class: CfgWeapons\Rifle\WeaponSlotsInfo\PointerSlot [Indent level: 2],
            "PointerSlot": {
                "compatibleItems": ["acc_flashlight","acc_pointer_IR"],
                "iconPicture": "A3|Weapons_F|Data|UI|attachment_side.paa",
                "iconPinpoint": "Center",
                "linkProxy": "A3|data_f|proxies|weapon_slots|SIDE",
                "displayName": "Pointer Slot",
                "access": 1,
                "scope": 0,
                "iconPosition": [0,0],
                "iconScale": 0
            },
            "allowedSlots": [901]
        },
        "zeroingSound": ["A3|Sounds_F|arsenal|sfx|shared|zeroing_knob_tick_metal",0.316228,1,5],
        "type": 1,
        "dexterity": 1.7,
        "aiRateOfFire": 0.5,
        "aiRateOfFireDistance": 500,
        "inertia": 0.5,
        "access": 3,
        "picture": "",
        "uiPicture": "",
        "ammo": "",
        "cursorSize": 1,
        "showAimCursorInternal": 1,
        "cursorAimOn": "",
        "laser": 0,
        "hiddenSelections": [],
        "hiddenSelectionsTextures": [],
        "hiddenUnderwaterSelections": [],
        "shownUnderwaterSelections": [],
        "hiddenUnderwaterSelectionsTextures": [],
        "simulation": "Weapon",
        "count": 0,
        "multiplier": 1,
        "burst": 1,
        "magazineReloadTime": 0,
        "magazineReloadSwitchPhase": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": ["sound",1],
        "soundLoop": ["sound",1],
        "weaponSoundEffect": "",
        "soundBurst": 1,
        "reloadSound": ["",1,1],
        "reloadMagazineSound": ["",1,1],
        "emptySound": ["",1,1],
        "soundBullet": ["emptySound",1],
        "initSpeed": 0,
        "ballisticsComputer": 0,
        "irDistance": 0,
        "irDotIntensity": 0.001,
        "lockAcquire": 1,
        "enableAttack": 1,
        "maxRecoilSway": 0.008,
        "swayDecaySpeed": 2,
        "model": "",
        "modelSpecial": "",
        "modelMagazine": "",
        "muzzlePos": "usti hlavne",
        "muzzleEnd": "konec hlavne",
        "irLaserPos": "laser pos",
        "irLaserEnd": "laser dir",
        "cartridgePos": "nabojnicestart",
        "cartridgeVel": "nabojniceend",
        "selectionFireAnim": "zasleh",
        "memoryPointCamera": "eye",
        "fireSpreadAngle": 3,
        "useModelOptics": 1,
        "opticsID": 0,
        "opticsPPEffects": [],
        "forceOptics": 0,
        "useAsBinocular": 0,
        "opticsDisablePeripherialVision": 0.67,
        "primary": 10,
        "showSwitchAction": 0,
        "showEmpty": 1,
        "canShootInWater": 0,
        "aiRateOfFireDispersion": 0,
        "fireLightDuration": 0.05,
        "fireLightIntensity": 0.2,
        "fireLightDiffuse": [0.937,0.631,0.259],
        "fireLightAmbient": [0,0,0],
        # Class: CfgWeapons\Default\Eventhandlers [Indent level: 1],
        "Eventhandlers": {
        },
        "backgroundReload": 0,
        "muzzles": ["this"],
        "useAction": 0,
        "useActionTitle": "",
        "canDrop": 1,
        "weaponLockDelay": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "weight": 0,
        "minRange": 1,
        "minRangeProbab": 0.3,
        "midRange": 150,
        "midRangeProbab": 0.58,
        "maxRange": 500,
        "maxRangeProbab": 0.04,
        "handAnim": [],
        "lockingTargetSound": ["",0.000316228,2],
        "lockedTargetSound": ["",0.000316228,6],
        "detectRange": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "fireAnims": [],
        # Class: CfgWeapons\Default\Library [Indent level: 1],
        "Library": {
            "libTextDesc": ""
        },
        # Class: CfgWeapons\Default\GunFire [Indent level: 1],
        "GunFire": {
            "access": 0,
            "cloudletDuration": 0.2,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletAlpha": 1,
            "cloudletGrowUp": 0.2,
            "cloudletFadeIn": 0.01,
            "cloudletFadeOut": 0.5,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "cloudletShape": "cloudletFire",
            "cloudletColor": [1,1,1,0],
            "cloudletDensityCoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourceSize": 0.5,
            "timeToLive": 0,
            "initT": 4500,
            "deltaT": -3000,
            # Class: CfgWeapons\Default\GunFire\Table [Indent level: 2],
            "Table": {
                # Class: CfgWeapons\Default\GunFire\Table\T0 [Indent level: 3]
                "T0": {
                    "maxT": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T1 [Indent level: 3],
                "T1": {
                    "maxT": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T2 [Indent level: 3],
                "T2": {
                    "maxT": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T3 [Indent level: 3],
                "T3": {
                    "maxT": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T4 [Indent level: 3],
                "T4": {
                    "maxT": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T5 [Indent level: 3],
                "T5": {
                    "maxT": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T6 [Indent level: 3],
                "T6": {
                    "maxT": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T7 [Indent level: 3],
                "T7": {
                    "maxT": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T8 [Indent level: 3],
                "T8": {
                    "maxT": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T9 [Indent level: 3],
                "T9": {
                    "maxT": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T10 [Indent level: 3],
                "T10": {
                    "maxT": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T11 [Indent level: 3],
                "T11": {
                    "maxT": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T12 [Indent level: 3],
                "T12": {
                    "maxT": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T13 [Indent level: 3],
                "T13": {
                    "maxT": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T14 [Indent level: 3],
                "T14": {
                    "maxT": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T15 [Indent level: 3],
                "T15": {
                    "maxT": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T16 [Indent level: 3],
                "T16": {
                    "maxT": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T17 [Indent level: 3],
                "T17": {
                    "maxT": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T18 [Indent level: 3],
                "T18": {
                    "maxT": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T19 [Indent level: 3],
                "T19": {
                    "maxT": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T20 [Indent level: 3],
                "T20": {
                    "maxT": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T21 [Indent level: 3],
                "T21": {
                    "maxT": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T22 [Indent level: 3],
                "T22": {
                    "maxT": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        # Class: CfgWeapons\Default\GunClouds [Indent level: 1],
        "GunClouds": {
            "access": 0,
            "cloudletGrowUp": 0.05,
            "cloudletFadeIn": 0,
            "cloudletFadeOut": 0.1,
            "cloudletDuration": 0.05,
            "cloudletAlpha": 0.3,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "interval": -0.02,
            "size": 0.3,
            "sourceSize": 0.02,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletShape": "cloudletClouds",
            "cloudletColor": [1,1,1,0],
            "timeToLive": 0,
            "initT": 0,
            "deltaT": 0,
            # Class: CfgWeapons\Default\GunClouds\Table [Indent level: 2],
            "Table": {
                # Class: CfgWeapons\Default\GunClouds\Table\T0 [Indent level: 3]
                "T0": {
                    "maxT": 0,
                    "color": [1,1,1,0]
                }
            }
        },
        "textureType": "default",
        "aimTransitionSpeed": 1
    },
    # Class: CfgWeapons\rhs_weap_g36_base\AG36Muzzle [Indent level: 1],
    "AG36Muzzle": {
        "cameradir": "gl_look",
        "discreteDistance": [50,100,150,200,250,300,350],
        "discreteDistanceCameraPoint": ["gl_eye_50m","gl_eye_100m","gl_eye_150m","gl_eye_200m","gl_eye_250m","gl_eye_300m","gl_eye_350m"],
        "discreteDistanceInitIndex": 1,
        "displayname": "AG36",
        "magazines": ["rhs_mag_M441_HE","rhs_mag_M433_HEDP","rhs_mag_M781_Practice","rhs_mag_M397_HET","rhs_mag_M4009","rhs_mag_m576","rhs_mag_M585_white","rhs_mag_M661_green","rhs_mag_M662_red","rhs_mag_M713_red","rhs_mag_M714_white","rhs_mag_M715_green","rhs_mag_M716_yellow","1Rnd_HE_Grenade_shell","UGL_FlareWhite_F","UGL_FlareGreen_F","UGL_FlareRed_F","UGL_FlareYellow_F","UGL_FlareCIR_F","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeRed_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell","1Rnd_SmokeYellow_Grenade_shell","1Rnd_SmokePurple_Grenade_shell","1Rnd_SmokeBlue_Grenade_shell","1Rnd_SmokeOrange_Grenade_shell"],
        "magazineWell": ["UGL_40x36"],
        "useModelOptics": 0,
        "useExternalOptic": 0,
        "optics": 1,
        "cursoraim": "gl",
        "magazinereloadtime": 2,
        "reloadtime": 0.1,
        "reloadAction": "RHS_GestureReloadAG36",
        "reloadMagazineSound": ["rhssaf|addons|rhssaf_sounds|G36|ag36_reload",1,1,10],
        "magazineReloadSwitchPhase": 0.55,
        "drySound": ["rhssaf|addons|rhssaf_sounds|G36|ag36_drystrike",0.66,1,10],
        "modes": ["Single"],
        # Class: CfgWeapons\rhs_weap_ag36_base\Single [Indent level: 1],
        "Single": {
            "sounds": ["StandardSound"],
            # Class: CfgWeapons\rhs_weap_ag36_base\Single\StandardSound [Indent level: 2],
            "StandardSound": {
                "closure1": ["rhssaf|addons|rhssaf_sounds|G36|ag36_striker",1,1,10],
                "soundClosure": ["closure1",1],
                "begin1": ["rhssaf|addons|rhssaf_sounds|G36|ag36_launch",0.707946,1,200],
                "begin2": ["rhssaf|addons|rhssaf_sounds|G36|ag36_launch",0.707946,1,200],
                "soundBegin": ["begin1",0.5,"begin2",0.5]
            },
            # Class: CfgWeapons\rhs_weap_ag36_base\Single\SoundTails [Indent level: 2],
            "SoundTails": {
                # Class: CfgWeapons\rhs_weap_ag36_base\Single\SoundTails\TailInterior [Indent level: 3]
                "TailInterior": {
                    "sound": ["|rhssaf|addons|rhssaf_sounds|G36|AG36_indoor",1,1,200],
                    "frequency": 1,
                    "volume": "interior"
                }
            },
            "recoil": "M240Recoil",
            "recoilProne": "M240Recoil",
            "minRange": 30,
            "minRangeProbab": 0.1,
            "midRange": 200,
            "midRangeProbab": 0.7,
            "maxRange": 400,
            "maxRangeProbab": 0.05,
            "multiplier": 1,
            "burst": 1,
            "burstRangeMax": -1,
            "dispersion": 0.0002,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "soundContinuous": 0,
            "weaponSoundEffect": "",
            "reloadTime": 0.1,
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "autoFire": 0,
            "useAction": 0,
            "useActionTitle": "",
            "showToPlayer": 1,
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "displayName": "Semi",
            "textureType": "semi",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1,
            "aiRateOfFire": 2,
            "aiRateOfFireDispersion": 1,
            "aiRateOfFireDistance": 500
        },
        "changeFiremodeSound": ["A3|Sounds_F|arsenal|weapons|UGL|Firemode_ugl",0.316228,1,5],
        "recoil": "recoil_default",
        "modelOptics": "-",
        "memoryPointCamera": "UGL eye",
        "opticsZoomMin": 0.25,
        "opticsZoomMax": 1.25,
        "opticsZoomInit": 0.75,
        "weaponInfoType": "RscWeaponZeroing",
        "cursor": "EmptyCursor",
        "value": 3,
        "type": 0,
        "initSpeed": 75,
        "canLock": 0,
        "autoReload": 0,
        "autoAimEnabled": 0,
        "ffMagnitude": 0.1,
        "ffFrequency": 1,
        "ffCount": 1,
        "dispersion": 0.00725,
        "aiDispersionCoefY": 6,
        "maxLeadSpeed": 15,
        "muzzlePos": "usti granatometu",
        "muzzleEnd": "konec granatometu",
        "cartridgePos": "",
        "cartridgeVel": "",
        "minRange": 30,
        "minRangeProbab": 0.1,
        "midRange": 200,
        "midRangeProbab": 0.7,
        "maxRange": 400,
        "maxRangeProbab": 0.05,
        "textureType": "semi",
        "access": 3,
        "scope": 0,
        "picture": "",
        "uiPicture": "",
        "ammo": "",
        "cursorSize": 1,
        "showAimCursorInternal": 1,
        "cursorAimOn": "",
        "laser": 0,
        "hiddenSelections": [],
        "hiddenSelectionsTextures": [],
        "hiddenUnderwaterSelections": [],
        "shownUnderwaterSelections": [],
        "hiddenUnderwaterSelectionsTextures": [],
        "simulation": "Weapon",
        "nameSound": "",
        "count": 0,
        "multiplier": 1,
        "burst": 1,
        "sound": ["",1,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": ["sound",1],
        "soundLoop": ["sound",1],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "soundBurst": 1,
        "zeroingSound": ["",1,1],
        "reloadSound": ["",1,1],
        "emptySound": ["",1,1],
        "soundBullet": ["emptySound",1],
        "ballisticsComputer": 0,
        "irDistance": 0,
        "irDotIntensity": 0.001,
        "aiDispersionCoefX": 1,
        "lockAcquire": 1,
        "enableAttack": 1,
        "recoilProne": "",
        "maxRecoilSway": 0.008,
        "swayDecaySpeed": 2,
        "model": "",
        "modelSpecial": "",
        "modelMagazine": "",
        "irLaserPos": "laser pos",
        "irLaserEnd": "laser dir",
        "selectionFireAnim": "zasleh",
        "fireSpreadAngle": 3,
        "opticsID": 0,
        "opticsPPEffects": [],
        "opticsFlare": 1,
        "forceOptics": 0,
        "useAsBinocular": 0,
        "opticsDisablePeripherialVision": 0.67,
        "distanceZoomMin": 400,
        "distanceZoomMax": 400,
        "primary": 10,
        "showSwitchAction": 0,
        "showEmpty": 1,
        "autoFire": 0,
        "showToPlayer": 1,
        "canShootInWater": 0,
        "aiRateOfFire": 5,
        "aiRateOfFireDistance": 500,
        "aiRateOfFireDispersion": 0,
        "fireLightDuration": 0.05,
        "fireLightIntensity": 0.2,
        "fireLightDiffuse": [0.937,0.631,0.259],
        "fireLightAmbient": [0,0,0],
        # Class: CfgWeapons\Default\Eventhandlers [Indent level: 1],
        "Eventhandlers": {
        },
        "backgroundReload": 0,
        "muzzles": ["this"],
        "useAction": 0,
        "useActionTitle": "",
        "canDrop": 1,
        "weaponLockDelay": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "weight": 0,
        "handAnim": [],
        "lockingTargetSound": ["",0.000316228,2],
        "lockedTargetSound": ["",0.000316228,6],
        "detectRange": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "fireAnims": [],
        # Class: CfgWeapons\Default\Library [Indent level: 1],
        "Library": {
            "libTextDesc": ""
        },
        "descriptionShort": "",
        # Class: CfgWeapons\Default\GunFire [Indent level: 1],
        "GunFire": {
            "access": 0,
            "cloudletDuration": 0.2,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletAlpha": 1,
            "cloudletGrowUp": 0.2,
            "cloudletFadeIn": 0.01,
            "cloudletFadeOut": 0.5,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "cloudletShape": "cloudletFire",
            "cloudletColor": [1,1,1,0],
            "cloudletDensityCoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourceSize": 0.5,
            "timeToLive": 0,
            "initT": 4500,
            "deltaT": -3000,
            # Class: CfgWeapons\Default\GunFire\Table [Indent level: 2],
            "Table": {
                # Class: CfgWeapons\Default\GunFire\Table\T0 [Indent level: 3]
                "T0": {
                    "maxT": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T1 [Indent level: 3],
                "T1": {
                    "maxT": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T2 [Indent level: 3],
                "T2": {
                    "maxT": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T3 [Indent level: 3],
                "T3": {
                    "maxT": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T4 [Indent level: 3],
                "T4": {
                    "maxT": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T5 [Indent level: 3],
                "T5": {
                    "maxT": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T6 [Indent level: 3],
                "T6": {
                    "maxT": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T7 [Indent level: 3],
                "T7": {
                    "maxT": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T8 [Indent level: 3],
                "T8": {
                    "maxT": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T9 [Indent level: 3],
                "T9": {
                    "maxT": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T10 [Indent level: 3],
                "T10": {
                    "maxT": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T11 [Indent level: 3],
                "T11": {
                    "maxT": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T12 [Indent level: 3],
                "T12": {
                    "maxT": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T13 [Indent level: 3],
                "T13": {
                    "maxT": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T14 [Indent level: 3],
                "T14": {
                    "maxT": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T15 [Indent level: 3],
                "T15": {
                    "maxT": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T16 [Indent level: 3],
                "T16": {
                    "maxT": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T17 [Indent level: 3],
                "T17": {
                    "maxT": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T18 [Indent level: 3],
                "T18": {
                    "maxT": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T19 [Indent level: 3],
                "T19": {
                    "maxT": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T20 [Indent level: 3],
                "T20": {
                    "maxT": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T21 [Indent level: 3],
                "T21": {
                    "maxT": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T22 [Indent level: 3],
                "T22": {
                    "maxT": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        # Class: CfgWeapons\Default\GunClouds [Indent level: 1],
        "GunClouds": {
            "access": 0,
            "cloudletGrowUp": 0.05,
            "cloudletFadeIn": 0,
            "cloudletFadeOut": 0.1,
            "cloudletDuration": 0.05,
            "cloudletAlpha": 0.3,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "interval": -0.02,
            "size": 0.3,
            "sourceSize": 0.02,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletShape": "cloudletClouds",
            "cloudletColor": [1,1,1,0],
            "timeToLive": 0,
            "initT": 0,
            "deltaT": 0,
            # Class: CfgWeapons\Default\GunClouds\Table [Indent level: 2],
            "Table": {
                # Class: CfgWeapons\Default\GunClouds\Table\T0 [Indent level: 3]
                "T0": {
                    "maxT": 0,
                    "color": [1,1,1,0]
                }
            }
        },
        "inertia": 0.5,
        "aimTransitionSpeed": 1
    },
    # Class: CfgWeapons\rhs_weap_g36_base\Single [Indent level: 1],
    "Single": {
        "sounds": ["StandardSound","SilencedSound"],
        "dispersion": 0.000555596,
        "reloadtime": 0.08,
        "aiRateOfFire": 1,
        "aiRateOfFireDistance": 250,
        "aiRateOfFireDispersion": 2,
        "minRange": 30,
        "minRangeProbab": 0.7,
        "midRange": 150,
        "midRangeProbab": 0.5,
        "maxRange": 500,
        "maxRangeProbab": 0.1,
        # Class: CfgWeapons\rhs_weap_g36_base\Single\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["RHSSAF_G36_Shot_SoundSet","RHSSAF_Rifle1_Tail_SoundSet"]
        },
        # Class: CfgWeapons\rhs_weap_g36_base\Single\SilencedSound [Indent level: 2],
        "SilencedSound": {
            "soundSetShot": ["RHSSAF_sd_G36_Shot_SoundSet","RHSSAF_sd_Rifle1_Tail_SoundSet"]
        },
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "requiredOpticType": -1
    },
    # Class: CfgWeapons\rhs_weap_g36_base\Burst [Indent level: 1],
    "Burst": {
        "dispersion": 0.000555596,
        "reloadtime": 0.08,
        "aiRateOfFire": 1,
        "aiRateOfFireDistance": 100,
        "aiRateOfFireDispersion": 2,
        "minRange": 10,
        "minRangeProbab": 0.8,
        "midRange": 15,
        "midRangeProbab": 0.7,
        "maxRange": 30,
        "maxRangeProbab": 0.1,
        # Class: CfgWeapons\rhs_weap_g36_base\Burst\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["RHSSAF_G36_Shot_SoundSet","RHSSAF_Rifle1_Tail_SoundSet"]
        },
        # Class: CfgWeapons\rhs_weap_g36_base\Burst\SilencedSound [Indent level: 2],
        "SilencedSound": {
            "soundSetShot": ["RHSSAF_sd_G36_Shot_SoundSet","RHSSAF_sd_Rifle1_Tail_SoundSet"]
        },
        "sound": ["",10,1],
        "soundLoop": ["sound",1],
        "soundEnd": ["sound",1],
        "burst": 3,
        "displayName": "Burst",
        "textureType": "burst",
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 2.4,
        "aiDispersionCoefX": 1.9,
        "soundBurst": 0,
        "multiplier": 1,
        "burstRangeMax": -1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "sounds": ["StandardSound","SilencedSound"],
        "requiredOpticType": -1
    },
    # Class: CfgWeapons\rhs_weap_g36_base\FullAuto [Indent level: 1],
    "FullAuto": {
        "sounds": ["StandardSound","SilencedSound"],
        "dispersion": 0.000555596,
        "reloadtime": 0.08,
        "aiRateOfFire": 0.2,
        "aiRateOfFireDistance": 50,
        "aiRateOfFireDispersion": 1,
        "minRange": 0,
        "minRangeProbab": 0.9,
        "midRange": 5,
        "midRangeProbab": 0.8,
        "maxRange": 10,
        "maxRangeProbab": 0.1,
        # Class: CfgWeapons\rhs_weap_g36_base\FullAuto\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["RHSSAF_G36_Shot_SoundSet","RHSSAF_Rifle1_Tail_SoundSet"]
        },
        # Class: CfgWeapons\rhs_weap_g36_base\FullAuto\SilencedSound [Indent level: 2],
        "SilencedSound": {
            "soundSetShot": ["RHSSAF_sd_G36_Shot_SoundSet","RHSSAF_sd_Rifle1_Tail_SoundSet"]
        },
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "soundContinuous": 0,
        "autoFire": 1,
        "displayName": "Full",
        "textureType": "fullAuto",
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1
    },
    # Class: CfgWeapons\rhs_weap_g36_base\Burst2rnd [Indent level: 1],
    "Burst2rnd": {
        "burst": 2,
        "textureType": "dual",
        "dispersion": 0.000555596,
        "reloadtime": 0.08,
        "aiRateOfFire": 1,
        "aiRateOfFireDistance": 100,
        "aiRateOfFireDispersion": 2,
        "minRange": 10,
        "minRangeProbab": 0.8,
        "midRange": 15,
        "midRangeProbab": 0.7,
        "maxRange": 30,
        "maxRangeProbab": 0.1,
        # Class: CfgWeapons\rhs_weap_g36_base\Burst\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["RHSSAF_G36_Shot_SoundSet","RHSSAF_Rifle1_Tail_SoundSet"]
        },
        # Class: CfgWeapons\rhs_weap_g36_base\Burst\SilencedSound [Indent level: 2],
        "SilencedSound": {
            "soundSetShot": ["RHSSAF_sd_G36_Shot_SoundSet","RHSSAF_sd_Rifle1_Tail_SoundSet"]
        },
        "sound": ["",10,1],
        "soundLoop": ["sound",1],
        "soundEnd": ["sound",1],
        "displayName": "Burst",
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 2.4,
        "aiDispersionCoefX": 1.9,
        "soundBurst": 0,
        "multiplier": 1,
        "burstRangeMax": -1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "sounds": ["StandardSound","SilencedSound"],
        "requiredOpticType": -1
    },
    # Class: CfgWeapons\rhs_weap_g36_base\fullauto_medium [Indent level: 1],
    "fullauto_medium": {
        "showToPlayer": 0,
        "burst": 5,
        "aiRateOfFire": 1,
        "aiRateOfFireDistance": 100,
        "aiRateOfFireDispersion": 2,
        "minRange": 10,
        "minRangeProbab": 0.8,
        "midRange": 15,
        "midRangeProbab": 0.7,
        "maxRange": 30,
        "maxRangeProbab": 0.1,
        "sounds": ["StandardSound","SilencedSound"],
        "dispersion": 0.000555596,
        "reloadtime": 0.08,
        # Class: CfgWeapons\rhs_weap_g36_base\FullAuto\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["RHSSAF_G36_Shot_SoundSet","RHSSAF_Rifle1_Tail_SoundSet"]
        },
        # Class: CfgWeapons\rhs_weap_g36_base\FullAuto\SilencedSound [Indent level: 2],
        "SilencedSound": {
            "soundSetShot": ["RHSSAF_sd_G36_Shot_SoundSet","RHSSAF_sd_Rifle1_Tail_SoundSet"]
        },
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "soundContinuous": 0,
        "autoFire": 1,
        "displayName": "Full",
        "textureType": "fullAuto",
        "recoil": "recoil_auto_primary_3outof10",
        "recoilProne": "recoil_auto_primary_prone_3outof10",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "burstRangeMax": -1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1
    },
    # Class: CfgWeapons\rhs_weap_g36_base\single_medium_optics1 [Indent level: 1],
    "single_medium_optics1": {
        "requiredOpticType": 1,
        "showToPlayer": 0,
        "aiRateOfFire": 2,
        "aiRateOfFireDistance": 450,
        "aiRateOfFireDispersion": 3,
        "minRange": 30,
        "minRangeProbab": 0.8,
        "midRange": 300,
        "midRangeProbab": 0.6,
        "maxRange": 700,
        "maxRangeProbab": 0.2,
        "sounds": ["StandardSound","SilencedSound"],
        "dispersion": 0.000555596,
        "reloadtime": 0.08,
        # Class: CfgWeapons\rhs_weap_g36_base\Single\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["RHSSAF_G36_Shot_SoundSet","RHSSAF_Rifle1_Tail_SoundSet"]
        },
        # Class: CfgWeapons\rhs_weap_g36_base\Single\SilencedSound [Indent level: 2],
        "SilencedSound": {
            "soundSetShot": ["RHSSAF_sd_G36_Shot_SoundSet","RHSSAF_sd_Rifle1_Tail_SoundSet"]
        },
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0
    },
    # Class: CfgWeapons\rhs_weap_g36_base\single_far_optics2 [Indent level: 1],
    "single_far_optics2": {
        "requiredOpticType": 2,
        "showToPlayer": 0,
        "aiRateOfFire": 3,
        "aiRateOfFireDistance": 500,
        "aiRateOfFireDispersion": 4,
        "minRange": 30,
        "minRangeProbab": 0.8,
        "midRange": 300,
        "midRangeProbab": 0.6,
        "maxRange": 900,
        "maxRangeProbab": 0.2,
        "sounds": ["StandardSound","SilencedSound"],
        "dispersion": 0.000555596,
        "reloadtime": 0.08,
        # Class: CfgWeapons\rhs_weap_g36_base\Single\StandardSound [Indent level: 2],
        "StandardSound": {
            "soundSetShot": ["RHSSAF_G36_Shot_SoundSet","RHSSAF_Rifle1_Tail_SoundSet"]
        },
        # Class: CfgWeapons\rhs_weap_g36_base\Single\SilencedSound [Indent level: 2],
        "SilencedSound": {
            "soundSetShot": ["RHSSAF_sd_G36_Shot_SoundSet","RHSSAF_sd_Rifle1_Tail_SoundSet"]
        },
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0
    },
    # Class: CfgWeapons\Rifle_Base_F\GunParticles [Indent level: 1],
    "GunParticles": {
        # Class: CfgWeapons\Rifle_Base_F\GunParticles\FirstEffect [Indent level: 2]
        "FirstEffect": {
            "effectName": "RifleAssaultCloud",
            "positionName": "Usti hlavne",
            "directionName": "Konec hlavne"
        }
    },
    "htMin": 1,
    "htMax": 600,
    "afMax": 0,
    "mfMax": 0,
    "mFact": 1,
    "tBody": 100,
    "autoFire": 1,
    "soundContinuous": 0,
    "optics": 0,
    "cursor": "arifle",
    "cursoraim": "CursorAim",
    "value": 4,
    "nameSound": "rifle",
    "reloadTime": 0.15,
    "modelOptics": "-",
    "sound": [],
    "opticsFlare": 0,
    "autoReload": 0,
    "opticsZoomMin": 0.25,
    "opticsZoomMax": 1.25,
    "opticsZoomInit": 0.75,
    "distanceZoomMin": 300,
    "distanceZoomMax": 300,
    "maxLeadSpeed": 23,
    "canLock": 0,
    "flash": "gunfire",
    "flashSize": 0.5,
    "dispersion": 0.00029,
    "recoilProne": "assaultRifleBase",
    "ffMagnitude": 0.5,
    "ffFrequency": 11,
    "ffCount": 3,
    "weaponPoolAvailable": 1,
    "zeroingSound": ["A3|Sounds_F|arsenal|sfx|shared|zeroing_knob_tick_metal",0.316228,1,5],
    "type": 1,
    "aiRateOfFire": 0.5,
    "aiRateOfFireDistance": 500,
    "access": 3,
    "ammo": "",
    "cursorSize": 1,
    "showAimCursorInternal": 1,
    "cursorAimOn": "",
    "laser": 0,
    "hiddenUnderwaterSelections": [],
    "shownUnderwaterSelections": [],
    "hiddenUnderwaterSelectionsTextures": [],
    "simulation": "Weapon",
    "count": 0,
    "multiplier": 1,
    "magazineReloadTime": 0,
    "soundBegin": ["sound",1],
    "soundBeginWater": ["sound",1],
    "soundClosure": ["sound",1],
    "soundEnd": ["sound",1],
    "soundLoop": ["sound",1],
    "weaponSoundEffect": "",
    "soundBurst": 1,
    "reloadSound": ["",1,1],
    "emptySound": ["",1,1],
    "initSpeed": 0,
    "ballisticsComputer": 0,
    "irDistance": 0,
    "irDotIntensity": 0.001,
    "lockAcquire": 1,
    "enableAttack": 1,
    "modelSpecial": "",
    "modelMagazine": "",
    "muzzlePos": "usti hlavne",
    "muzzleEnd": "konec hlavne",
    "irLaserPos": "laser pos",
    "irLaserEnd": "laser dir",
    "cartridgePos": "nabojnicestart",
    "cartridgeVel": "nabojniceend",
    "selectionFireAnim": "zasleh",
    "memoryPointCamera": "eye",
    "fireSpreadAngle": 3,
    "useModelOptics": 1,
    "opticsID": 0,
    "opticsPPEffects": [],
    "forceOptics": 0,
    "useAsBinocular": 0,
    "opticsDisablePeripherialVision": 0.67,
    "primary": 10,
    "showSwitchAction": 0,
    "showEmpty": 1,
    "showToPlayer": 1,
    "canShootInWater": 0,
    "aiRateOfFireDispersion": 0,
    "fireLightDuration": 0.05,
    "fireLightIntensity": 0.2,
    "fireLightDiffuse": [0.937,0.631,0.259],
    "fireLightAmbient": [0,0,0],
    # Class: CfgWeapons\Default\Eventhandlers [Indent level: 1],
    "Eventhandlers": {
    },
    "backgroundReload": 0,
    "useAction": 0,
    "useActionTitle": "",
    "canDrop": 1,
    "weaponLockDelay": 0,
    "weaponLockSystem": 0,
    "cmImmunity": 1,
    "weight": 0,
    "minRange": 1,
    "minRangeProbab": 0.3,
    "midRange": 150,
    "midRangeProbab": 0.58,
    "maxRange": 500,
    "maxRangeProbab": 0.04,
    "handAnim": [],
    "lockingTargetSound": ["",0.000316228,2],
    "lockedTargetSound": ["",0.000316228,6],
    "detectRange": 0,
    "artilleryDispersion": 1,
    "artilleryCharge": 1,
    "fireAnims": [],
    "descriptionShort": "",
    # Class: CfgWeapons\Default\GunFire [Indent level: 1],
    "GunFire": {
        "access": 0,
        "cloudletDuration": 0.2,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 0.2,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 0.5,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletFire",
        "cloudletColor": [1,1,1,0],
        "cloudletDensityCoef": -1,
        "interval": -0.01,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 4500,
        "deltaT": -3000,
        # Class: CfgWeapons\Default\GunFire\Table [Indent level: 2],
        "Table": {
            # Class: CfgWeapons\Default\GunFire\Table\T0 [Indent level: 3]
            "T0": {
                "maxT": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T1 [Indent level: 3],
            "T1": {
                "maxT": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T2 [Indent level: 3],
            "T2": {
                "maxT": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T3 [Indent level: 3],
            "T3": {
                "maxT": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T4 [Indent level: 3],
            "T4": {
                "maxT": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T5 [Indent level: 3],
            "T5": {
                "maxT": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T6 [Indent level: 3],
            "T6": {
                "maxT": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T7 [Indent level: 3],
            "T7": {
                "maxT": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T8 [Indent level: 3],
            "T8": {
                "maxT": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T9 [Indent level: 3],
            "T9": {
                "maxT": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T10 [Indent level: 3],
            "T10": {
                "maxT": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T11 [Indent level: 3],
            "T11": {
                "maxT": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T12 [Indent level: 3],
            "T12": {
                "maxT": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T13 [Indent level: 3],
            "T13": {
                "maxT": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T14 [Indent level: 3],
            "T14": {
                "maxT": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T15 [Indent level: 3],
            "T15": {
                "maxT": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T16 [Indent level: 3],
            "T16": {
                "maxT": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T17 [Indent level: 3],
            "T17": {
                "maxT": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T18 [Indent level: 3],
            "T18": {
                "maxT": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T19 [Indent level: 3],
            "T19": {
                "maxT": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T20 [Indent level: 3],
            "T20": {
                "maxT": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T21 [Indent level: 3],
            "T21": {
                "maxT": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T22 [Indent level: 3],
            "T22": {
                "maxT": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgWeapons\Default\GunClouds [Indent level: 1],
    "GunClouds": {
        "access": 0,
        "cloudletGrowUp": 0.05,
        "cloudletFadeIn": 0,
        "cloudletFadeOut": 0.1,
        "cloudletDuration": 0.05,
        "cloudletAlpha": 0.3,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "interval": -0.02,
        "size": 0.3,
        "sourceSize": 0.02,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletShape": "cloudletClouds",
        "cloudletColor": [1,1,1,0],
        "timeToLive": 0,
        "initT": 0,
        "deltaT": 0,
        # Class: CfgWeapons\Default\GunClouds\Table [Indent level: 2],
        "Table": {
            # Class: CfgWeapons\Default\GunClouds\Table\T0 [Indent level: 3]
            "T0": {
                "maxT": 0,
                "color": [1,1,1,0]
            }
        }
    },
    "textureType": "default",
}