rhs_weap_M107 = {
    "author": "Red Hammer Studios",
    "picture": "rhsusf|addons|rhsusf_inventoryicons|data|weapons|rhs_weap_M107_ca.paa",
    "scope": 2,
    "displayname": "M107",
    "descriptionshort": "Anti-materiel rifle<br />Caliber: .50 BMG (12.7×99mm NATO)",
    "dlc": "RHS_USAF",
    "magazines": ["rhsusf_mag_10Rnd_STD_50BMG_M33","rhsusf_mag_10Rnd_STD_50BMG_mk211"],
    "magazinewell": ["CBA_50BMG_M107"],
    # Class: CfgWeapons|rhs_weap_M107_Base_F|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "optics": 0,
    "model": "rhsusf|addons|rhsusf_weapons|M107|M107",
    "hiddenselections": ["camo","camo2"],
    "hiddenselectionstextures": ["|rhsusf|addons|rhsusf_weapons|M107|Data|M107_Body_Co.paa","|rhsusf|addons|rhsusf_weapons|M107|Data|M107_extras_Co.paa"],
    "deployedpivot": "bipod",
    "hasbipod": 1,
    "maxrecoilsway": 0.0125,
    "swaydecayspeed": 1.25,
    # Recoil Class: recoil,
    # Class: CfgRecoils|recoil_gm6 [Indent level: 0],
    "recoil": {
        "muzzleouter": [1.4,3.5,0.7,0.8],
        "kickback": [0.1,0.12],
        "temporary": 0.025,
        "muzzleinner": [0,0,0.1,0.1],
        "permanent": 0.1
    },
    # Class: CfgWeapons|rhs_weap_M107_Base_F|GunParticles [Indent level: 1],
    "gunparticles": {
        # Class: CfgWeapons|rhs_weap_M107_Base_F|GunParticles|SecondEffect [Indent level: 2]
        "secondeffect": {
            "positionname": "Nabojnicestart",
            "directionname": "Nabojniceend",
            "effectname": "RifleAssaultCloud"
        },
        # Class: CfgWeapons|rhs_weap_M107_Base_F|GunParticles|RHSUSF_BarrelRefract [Indent level: 2],
        "rhsusf_barrelrefract": {
            "positionname": "usti hlavne",
            "directionname": "usti hlavne up",
            "effectname": "RHSUSF_BarrelRefractHeavy"
        },
        # Class: CfgWeapons|GM6_base_F|GunParticles|FirstEffect [Indent level: 2],
        "firsteffect": {
            "effectname": "SniperCloud",
            "positionname": "Usti hlavne",
            "directionname": "Konec hlavne"
        }
    },
    "weaponinfotype": "rhs_rscOptics_m107",
    "discretedistance": [100,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500],
    "discretedistancecamerapoint": ["eye","eye_400","eye_500","eye_600","eye_700","eye_800","eye_900","eye_1000","eye_1100","eye_1200","eye_1300","eye_1400","eye_1500"],
    "discretedistanceinitindex": 0,
    "cameradir": "eye_look",
    "reloadaction": "GestureReloadDMR05",
    "maxzeroing": 2000,
    # Class: CfgWeapons|rhs_weap_M107_Base_F|Single [Indent level: 1],
    "single": {
        "dispersion": 0.0004363,
        # Class: CfgWeapons|rhs_weap_M107_Base_F|Single|StandardSound [Indent level: 2],
        "standardsound": {
            "soundsetshot": ["jsrs_m107_shot_soundset","jsrs_12x7mm_reverb_soundset"]
        },
        # Class: CfgWeapons|rhs_weap_M107_Base_F|Single|SilencedSound [Indent level: 2],
        "silencedsound": {
            "soundsetshot": ["jsrs_m107_shot_silenced_soundset","jsrs_9x3mm_sd_reverb_soundset"]
        },
        # Class: CfgWeapons|rhs_weap_M107_Base_F|Single|BaseSoundModeType [Indent level: 2],
        "basesoundmodetype": {
        },
        "multiplier": 1,
        "burst": 1,
        "burstrangemax": -1,
        "sound": ["",10,1],
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundend": [],
        "soundloop": [],
        "soundcontinuous": 0,
        "weaponsoundeffect": "",
        "reloadtime": 0.1,
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "autofire": 0,
        "useaction": 0,
        "useactiontitle": "",
        "showtoplayer": 1,
        "minrange": 30,
        "minrangeprobab": 0.25,
        "midrange": 300,
        "midrangeprobab": 0.58,
        "maxrange": 600,
        "maxrangeprobab": 0.04,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "sounds": ["StandardSound","SilencedSound"],
        "displayname": "Semi",
        "texturetype": "semi",
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.03,0.0110829,0.043044,0.03,0.0159085,0.0170136,0.03,0.0138285,0.0116128,0.06,0.0066492,0.004788,0.06,-0.0007206,-0.002688,0.06,-0.001765,-0.00282,0.06,-0.0018385,-0.001764,0.06,-0.0009414,-0.0005,0.06,0,0],
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.03,0.0110829,0.0021522,0.04,0.0095451,0.0007506,0.05,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0,0.06,-0.0007206,-2.88e-005,0.06,-0.001059,-8.46e-005,0.06,-0.0011031,-8.82e-005,0.06,-0.0009414,-7.5e-005,0.06,-0.0006618,-5.28e-005,0.06,-0.0003531,-2.82e-005,0.06,-0.0001029,-8.4e-006,0.06,-4.5e-005,0,0.06,0,0],
        "aidispersioncoefy": 1.7,
        "aidispersioncoefx": 1.4,
        "soundburst": 0,
        "requiredoptictype": -1,
        "airateoffire": 2,
        "airateoffiredispersion": 1,
        "airateoffiredistance": 500
    },
    # Class: CfgWeapons|rhs_weap_M107_Base_F|WeaponSlotsInfo [Indent level: 1],
    "weaponslotsinfo": {
        "mass": 283.8,
        # Class: CfgWeapons|rhs_weap_M107_Base_F|WeaponSlotsInfo|CowsSlot [Indent level: 2],
        "cowsslot": {
            # Class: asdg_OpticRail1913_long|compatibleItems [Indent level: 0]
            "compatibleitems": {
                "rhsusf_acc_leupoldmk4": 0,
                "rhsusf_acc_leupoldmk4_d": 0,
                "rhsusf_acc_leupoldmk4_wd": 0,
                "rhsusf_acc_m8541_low": 0,
                "rhsusf_acc_m8541_low_d": 0,
                "rhsusf_acc_m8541_low_wd": 0,
                "rhsusf_acc_premier_anpvs27": 1,
                "rhsusf_acc_acog_anpvs27": 1,
                "rhsusf_acc_t1_low_fwd": 1,
                "rhsusf_acc_t1_low_fwd_ak": 1,
                "rhsusf_acc_rm05_fwd": 1,
                "rhsusf_acc_rm05_fwd_ak": 1,
                "rhsusf_acc_mrds_fwd": 1,
                "rhsusf_acc_mrds_fwd_ak": 1,
                "rhsusf_acc_mrds_fwd_c": 1,
                "rhsusf_acc_mrds_fwd_c_ak": 1,
                "rhs_acc_rakurspm": 1,
                "rhs_acc_dh520x56": 1,
                "rhs_acc_ekp8_18": 1,
                "rhs_acc_ekp8_18b": 1,
                "rhs_acc_ekp8_18c": 1,
                "rhs_acc_ekp8_18d": 1,
                "rhs_acc_1p87": 1,
                "rhs_acc_okp7_picatinny": 1,
                "optic_nightstalker": 1,
                "optic_tws": 1,
                "optic_tws_mg": 1,
                "optic_nvs": 1,
                "optic_sos": 1,
                "optic_sos_khk_f": 1,
                "optic_mrco": 1,
                "optic_arco": 1,
                "optic_arco_ghex_f": 1,
                "optic_arco_blk_f": 1,
                "optic_aco": 1,
                "optic_aco_grn": 1,
                "optic_aco_smg": 1,
                "optic_aco_grn_smg": 1,
                "optic_hamr": 1,
                "optic_hamr_khk_f": 1,
                "optic_holosight": 1,
                "optic_holosight_smg": 1,
                "optic_holosight_blk_f": 1,
                "optic_holosight_khk_f": 1,
                "optic_holosight_smg_blk_f": 1,
                "optic_dms": 1,
                "optic_dms_ghex_f": 1,
                "optic_lrps": 1,
                "optic_lrps_ghex_f": 1,
                "optic_lrps_tna_f": 1,
                "optic_ams": 1,
                "optic_ams_khk": 1,
                "optic_ams_snd": 1,
                "optic_khs_blk": 1,
                "optic_khs_hex": 1,
                "optic_khs_old": 1,
                "optic_khs_tan": 1,
                "optic_erco_blk_f": 1,
                "optic_erco_khk_f": 1,
                "optic_erco_snd_f": 1,
                "rhsusf_acc_leupoldmk4_2": 1,
                "rhsusf_acc_leupoldmk4_2_mrds": 1,
                "rhsusf_acc_leupoldmk4_2_d": 1,
                "rhsusf_acc_premier": 1,
                "rhsusf_acc_premier_mrds": 1,
                "rhsusf_acc_premier_low": 1,
                "rhsusf_acc_m8541": 1,
                "rhsusf_acc_m8541_mrds": 1,
                "rhsusf_acc_eotech": 1,
                "rhsusf_acc_eotech_552": 1,
                "rhsusf_acc_eotech_552_d": 1,
                "rhsusf_acc_eotech_552_wd": 1,
                "rhsusf_acc_eotech_xps3": 1,
                "rhsusf_acc_g33_xps3": 1,
                "rhsusf_acc_g33_xps3_flip": 1,
                "rhsusf_acc_g33_xps3_tan": 1,
                "rhsusf_acc_g33_xps3_tan_flip": 1,
                "rhsusf_acc_g33_t1": 1,
                "rhsusf_acc_g33_t1_flip": 1,
                "rhsusf_acc_compm4": 1,
                "rhsusf_acc_t1_high": 1,
                "rhsusf_acc_t1_low": 1,
                "rhsusf_acc_rx01": 1,
                "rhsusf_acc_rx01_nofilter": 1,
                "rhsusf_acc_rx01_tan": 1,
                "rhsusf_acc_rx01_nofilter_tan": 1,
                "rhsusf_acc_rm05": 1,
                "rhsusf_acc_mrds": 1,
                "rhsusf_acc_mrds_c": 1,
                "rhsusf_acc_acog": 1,
                "rhsusf_acc_acog2": 1,
                "rhsusf_acc_acog3": 1,
                "rhsusf_acc_acog_wd": 1,
                "rhsusf_acc_acog_d": 1,
                "rhsusf_acc_acog_sa": 1,
                "rhsusf_acc_acog_usmc": 1,
                "rhsusf_acc_acog2_usmc": 1,
                "rhsusf_acc_acog3_usmc": 1,
                "rhsusf_acc_acog_rmr": 1,
                "rhsusf_acc_acog_pip": 1,
                "rhsusf_acc_acog2_pip": 1,
                "rhsusf_acc_acog3_pip": 1,
                "rhsusf_acc_acog_wd_pip": 1,
                "rhsusf_acc_acog_d_pip": 1,
                "rhsusf_acc_acog_sa_pip": 1,
                "rhsusf_acc_acog_usmc_pip": 1,
                "rhsusf_acc_acog2_usmc_pip": 1,
                "rhsusf_acc_acog3_usmc_pip": 1,
                "rhsusf_acc_acog_rmr_pip": 1,
                "rhsusf_acc_acog_3d": 1,
                "rhsusf_acc_acog2_3d": 1,
                "rhsusf_acc_acog3_3d": 1,
                "rhsusf_acc_acog_wd_3d": 1,
                "rhsusf_acc_acog_d_3d": 1,
                "rhsusf_acc_acog_sa_3d": 1,
                "rhsusf_acc_acog_usmc_3d": 1,
                "rhsusf_acc_acog2_usmc_3d": 1,
                "rhsusf_acc_acog3_usmc_3d": 1,
                "rhsusf_acc_acog_rmr_3d": 1,
                "rhsusf_acc_elcan": 1,
                "rhsusf_acc_elcan_ard": 1,
                "rhsusf_acc_elcan_3d": 1,
                "rhsusf_acc_elcan_ard_3d": 1,
                "rhsusf_acc_elcan_pip": 1,
                "rhsusf_acc_elcan_ard_pip": 1,
                "rhsusf_acc_su230": 1,
                "rhsusf_acc_su230_mrds": 1,
                "rhsusf_acc_su230a": 1,
                "rhsusf_acc_su230a_mrds": 1,
                "rhsusf_acc_su230_c": 1,
                "rhsusf_acc_su230_mrds_c": 1,
                "rhsusf_acc_su230a_c": 1,
                "rhsusf_acc_su230a_mrds_c": 1,
                "rhsusf_acc_su230_3d": 1,
                "rhsusf_acc_su230_mrds_3d": 1,
                "rhsusf_acc_su230a_3d": 1,
                "rhsusf_acc_su230a_mrds_3d": 1,
                "rhsusf_acc_su230_c_3d": 1,
                "rhsusf_acc_su230_mrds_c_3d": 1,
                "rhsusf_acc_su230a_c_3d": 1,
                "rhsusf_acc_su230a_mrds_c_3d": 1,
                "rhsusf_acc_specterdr": 1,
                "rhsusf_acc_specterdr_3d": 1,
                "rhsusf_acc_specterdr_a": 1,
                "rhsusf_acc_specterdr_a_3d": 1,
                "rhsusf_acc_specterdr_cx": 1,
                "rhsusf_acc_specterdr_cx_3d": 1,
                "rhsusf_acc_specterdr_pvs27": 1,
                "rhsusf_acc_specterdr_d": 1,
                "rhsusf_acc_specterdr_od": 1,
                "rhsusf_acc_specterdr_d_3d": 1,
                "rhsusf_acc_specterdr_od_3d": 1,
                "rhsusf_acc_anpvs27": 1,
                "rhsusf_acc_anpas13gv1": 1,
                "rhsusf_acc_m2a1": 1,
                "rhsusf_acc_acog_mdo": 1,
                "rhsgref_acc_rx01_camo": 1,
                "rhsgref_acc_rx01_nofilter_camo": 1
            },
            "linkproxy": "A3|data_f|proxies|weapon_slots|TOP",
            "displayname": "Optics Slot"
        },
        # Class: CfgWeapons|rhs_weap_M107_Base_F|WeaponSlotsInfo|MuzzleSlot [Indent level: 2],
        "muzzleslot": {
        },
        # Class: CfgWeapons|rhs_weap_M107_Base_F|WeaponSlotsInfo|PointerSlot [Indent level: 2],
        "pointerslot": {
            "iconposition": [0,0],
            "iconscale": 1,
            "iconpicture": "A3|Weapons_F|Data|clear_empty.paa",
            "iconpinpoint": "Left"
        },
        "allowedslots": []
    },
    "opticszoommin": 0.275,
    "opticszoommax": 1.1,
    "opticszoominit": 0.75,
    "distancezoommin": 300,
    "distancezoommax": 300,
    "handanim": ["OFP2_ManSkeleton","|rhsusf|addons|rhsusf_c_weapons|anims|rhs_hand_M107.rtm"],
    "aimtransitionspeed": 0.5,
    "dexterity": 0.8,
    "inertia": 1.4,
    "caseless": ["",1,1,1],
    "reloadmagazinesound": ["A3|Sounds_F_Mark|arsenal|weapons|LongRangeRifles|DMR_05_Cyrus|DMR_05_reload",0.251189,1,10],
    "aidispersioncoefy": 10,
    "aidispersioncoefx": 8,
    "muzzles": ["this","SAFE"],
    # Class: CfgWeapons|rhs_weap_M107_Base_F|SAFE [Indent level: 1],
    "safe": {
        "discretedistancecamerapoint": ["eye"],
        "cameradir": "eye_look",
        "magazines": [],
        "displayname": "SAFE",
        "descriptionshort": "SAFE",
        "showtoplayer": 0,
        "modes": ["Safe"],
        "discretedistance": [0],
        "discretedistanceinitindex": 0,
        "drysound": ["A3|Sounds_F|arsenal|weapons|Rifles|MX|dry_Mx",0.562341,1,10],
        "changefiremodesound": ["A3|sounds_f|weapons|closure|firemode_changer_2",0.551189,1,5],
        # Class: CfgWeapons|RHSUSF_SAFE_BASE|Safe [Indent level: 1],
        "safe": {
            "sounds": [],
            "displayname": "SAFE",
            "descriptionshort": "SAFE",
            "showtoplayer": 0,
            "minrange": 0,
            "minrangeprobab": 0.001,
            "midrange": 0.001,
            "midrangeprobab": 0.001,
            "maxrange": 0.001,
            "maxrangeprobab": 0.001,
            "multiplier": 1,
            "burst": 1,
            "burstrangemax": -1,
            "dispersion": 0.0002,
            "sound": ["",10,1],
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundend": [],
            "soundloop": [],
            "soundcontinuous": 0,
            "weaponsoundeffect": "",
            "reloadtime": 0.1,
            "ffcount": 1,
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "flash": "gunfire",
            "flashsize": 0.1,
            "autofire": 0,
            "useaction": 0,
            "useactiontitle": "",
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "texturetype": "semi",
            # Recoil Array: recoil,
            "recoil": [0,0,0,0.03,0.0110829,0.043044,0.03,0.0159085,0.0170136,0.03,0.0138285,0.0116128,0.06,0.0066492,0.004788,0.06,-0.0007206,-0.002688,0.06,-0.001765,-0.00282,0.06,-0.0018385,-0.001764,0.06,-0.0009414,-0.0005,0.06,0,0],
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.03,0.0110829,0.0021522,0.04,0.0095451,0.0007506,0.05,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0,0.06,-0.0007206,-2.88e-005,0.06,-0.001059,-8.46e-005,0.06,-0.0011031,-8.82e-005,0.06,-0.0009414,-7.5e-005,0.06,-0.0006618,-5.28e-005,0.06,-0.0003531,-2.82e-005,0.06,-0.0001029,-8.4e-006,0.06,-4.5e-005,0,0.06,0,0],
            "aidispersioncoefy": 1.7,
            "aidispersioncoefx": 1.4,
            "soundburst": 0,
            "requiredoptictype": -1,
            "airateoffire": 2,
            "airateoffiredispersion": 1,
            "airateoffiredistance": 500
        },
        "scope": 0,
        "weaponinfotype": "RscWeaponZeroing",
        # Recoil Class: recoil,
        # Class: CfgRecoils|recoil_default [Indent level: 0],
        "recoil": {
            "muzzleouter": [0.3,1,0.3,0.2],
            "muzzleinner": [0,0,0.1,0.1],
            "kickback": [0.03,0.06],
            "permanent": 0.1,
            "temporary": 0.01
        },
        "deployedpivot": "bipod",
        # Class: CfgWeapons|Rifle_Base_F|GunParticles [Indent level: 1],
        "gunparticles": {
            # Class: CfgWeapons|Rifle_Base_F|GunParticles|FirstEffect [Indent level: 2]
            "firsteffect": {
                "effectname": "RifleAssaultCloud",
                "positionname": "Usti hlavne",
                "directionname": "Konec hlavne"
            }
        },
        "htmin": 1,
        "htmax": 600,
        "afmax": 0,
        "mfmax": 0,
        "mfact": 1,
        "tbody": 100,
        "autofire": 1,
        "reloadaction": "ReloadMagazine",
        "soundcontinuous": 0,
        "optics": 0,
        "cursor": "arifle",
        "cursoraim": "CursorAim",
        "value": 4,
        "namesound": "rifle",
        "reloadtime": 0.15,
        "modeloptics": "-",
        "sound": [],
        "opticsflare": 0,
        "autoreload": 0,
        "aidispersioncoefx": 6,
        "aidispersioncoefy": 6,
        "opticszoommin": 0.25,
        "opticszoommax": 1.25,
        "opticszoominit": 0.75,
        "distancezoommin": 300,
        "distancezoommax": 300,
        "maxleadspeed": 23,
        "canlock": 0,
        "flash": "gunfire",
        "flashsize": 0.5,
        "dispersion": 0.00029,
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.01,0.01,0.1,0,-0.02,0.1,-0.01,0.01,0.05,0,0],
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "ffcount": 3,
        "weaponpoolavailable": 1,
        "maxzeroing": 1000,
        # Class: CfgWeapons|Rifle|WeaponSlotsInfo [Indent level: 1],
        "weaponslotsinfo": {
            "mass": 2,
            # Class: CfgWeapons|Rifle|WeaponSlotsInfo|MuzzleSlot [Indent level: 2],
            "muzzleslot": {
                "linkproxy": "A3|data_f|proxies|weapon_slots|MUZZLE",
                "displayname": "$str_a3_cfgweapons_abr_base_f_weaponslotsinfo_muzzleslot0",
                "compatibleitems": [],
                "iconpicture": "A3|Weapons_F|Data|UI|attachment_muzzle.paa",
                "iconpinpoint": "Center",
                "access": 1,
                "scope": 0,
                "iconposition": [0,0],
                "iconscale": 0
            },
            # Class: CfgWeapons|Rifle|WeaponSlotsInfo|CowsSlot [Indent level: 2],
            "cowsslot": {
                "compatibleitems": ["optic_Nightstalker","optic_tws","optic_tws_mg","optic_NVS","optic_DMS","optic_LRPS","optic_ams","optic_AMS_snd","optic_AMS_khk","optic_KHS_blk","optic_KHS_tan","optic_KHS_hex","optic_KHS_old","optic_SOS","optic_MRCO","optic_Arco","optic_aco","optic_ACO_grn","optic_aco_smg","optic_ACO_grn_smg","optic_hamr","optic_Holosight","optic_Holosight_smg","optic_Hamr_khk_F","optic_SOS_khk_F","optic_Arco_ghex_F","optic_Arco_blk_F","optic_DMS_ghex_F","optic_ERCO_blk_F","optic_ERCO_khk_F","optic_ERCO_snd_F","optic_LRPS_ghex_F","optic_LRPS_tna_F","optic_Holosight_blk_F","optic_Holosight_khk_F","optic_Holosight_smg_blk_F","optic_Holosight_smg_khk_F","optic_Arco_AK_blk_F","optic_Arco_AK_lush_F","optic_Arco_AK_arid_F","optic_DMS_weathered_F","optic_DMS_weathered_Kir_F","optic_Arco_lush_F","optic_Arco_arid_F","optic_Holosight_lush_F","optic_Holosight_arid_F"],
                "linkproxy": "A3|data_f|proxies|weapon_slots|TOP",
                "displayname": "Optics Slot",
                "iconpicture": "A3|Weapons_F|Data|UI|attachment_top.paa",
                "iconpinpoint": "Bottom",
                "access": 1,
                "scope": 0,
                "iconposition": [0,0],
                "iconscale": 0
            },
            # Class: CfgWeapons|Rifle|WeaponSlotsInfo|PointerSlot [Indent level: 2],
            "pointerslot": {
                "compatibleitems": ["acc_flashlight","acc_pointer_IR"],
                "iconpicture": "A3|Weapons_F|Data|UI|attachment_side.paa",
                "iconpinpoint": "Center",
                "linkproxy": "A3|data_f|proxies|weapon_slots|SIDE",
                "displayname": "Pointer Slot",
                "access": 1,
                "scope": 0,
                "iconposition": [0,0],
                "iconscale": 0
            },
            "allowedslots": [901]
        },
        "zeroingsound": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|noises|rifle_zeroing_1.ogg",5,1,5],
        "type": 1,
        "dexterity": 1.7,
        "airateoffire": 0.5,
        "airateoffiredistance": 500,
        "inertia": 0.5,
        "access": 3,
        "picture": "",
        "uipicture": "",
        "ammo": "",
        "cursorsize": 1,
        "showaimcursorinternal": 1,
        "cursoraimon": "",
        "laser": 0,
        "hiddenselections": [],
        "hiddenselectionstextures": [],
        "hiddenunderwaterselections": [],
        "shownunderwaterselections": [],
        "hiddenunderwaterselectionstextures": [],
        "simulation": "Weapon",
        "count": 0,
        "multiplier": 1,
        "burst": 1,
        "magazinereloadtime": 0,
        "magazinereloadswitchphase": 1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundend": ["sound",1],
        "soundloop": ["sound",1],
        "weaponsoundeffect": "",
        "soundburst": 1,
        "reloadsound": ["",1,1],
        "reloadmagazinesound": ["",1,1],
        "emptysound": ["",1,1],
        "soundbullet": ["emptySound",1],
        "initspeed": 0,
        "ballisticscomputer": 0,
        "irdistance": 0,
        "irdotintensity": 0.001,
        "lockacquire": 1,
        "enableattack": 1,
        "maxrecoilsway": 0.008,
        "swaydecayspeed": 2,
        "model": "",
        "modelspecial": "",
        "modelmagazine": "",
        "muzzlepos": "usti hlavne",
        "muzzleend": "konec hlavne",
        "irlaserpos": "laser pos",
        "irlaserend": "laser dir",
        "cartridgepos": "nabojnicestart",
        "cartridgevel": "nabojniceend",
        "selectionfireanim": "zasleh",
        "memorypointcamera": "eye",
        "firespreadangle": 3,
        "usemodeloptics": 1,
        "opticsid": 0,
        "opticsppeffects": [],
        "forceoptics": 0,
        "useasbinocular": 0,
        "opticsdisableperipherialvision": 0.67,
        "primary": 10,
        "showswitchaction": 0,
        "showempty": 1,
        "canshootinwater": 0,
        "airateoffiredispersion": 0,
        "firelightduration": 0.05,
        "firelightintensity": 0.2,
        "firelightdiffuse": [0.937,0.631,0.259],
        "firelightambient": [0,0,0],
        # Class: CfgWeapons|Default|Eventhandlers [Indent level: 1],
        "eventhandlers": {
        },
        "backgroundreload": 0,
        "muzzles": ["this"],
        "useaction": 0,
        "useactiontitle": "",
        "candrop": 1,
        "weaponlockdelay": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "weight": 0,
        "minrange": 1,
        "minrangeprobab": 0.3,
        "midrange": 150,
        "midrangeprobab": 0.58,
        "maxrange": 500,
        "maxrangeprobab": 0.04,
        "handanim": [],
        "lockingtargetsound": ["",0.000316228,2],
        "lockedtargetsound": ["",0.000316228,6],
        "detectrange": 0,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "fireanims": [],
        # Class: CfgWeapons|Default|Library [Indent level: 1],
        "library": {
            "libtextdesc": ""
        },
        # Class: CfgWeapons|Default|GunFire [Indent level: 1],
        "gunfire": {
            "access": 0,
            "cloudletduration": 0.2,
            "cloudletanimperiod": 1,
            "cloudletsize": 1,
            "cloudletalpha": 1,
            "cloudletgrowup": 0.2,
            "cloudletfadein": 0.01,
            "cloudletfadeout": 0.5,
            "cloudletaccy": 0,
            "cloudletminyspeed": -100,
            "cloudletmaxyspeed": 100,
            "cloudletshape": "cloudletFire",
            "cloudletcolor": [1,1,1,0],
            "cloudletdensitycoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourcesize": 0.5,
            "timetolive": 0,
            "initt": 4500,
            "deltat": -3000,
            # Class: CfgWeapons|Default|GunFire|Table [Indent level: 2],
            "table": {
                # Class: CfgWeapons|Default|GunFire|Table|T0 [Indent level: 3]
                "t0": {
                    "maxt": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T1 [Indent level: 3],
                "t1": {
                    "maxt": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T2 [Indent level: 3],
                "t2": {
                    "maxt": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T3 [Indent level: 3],
                "t3": {
                    "maxt": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T4 [Indent level: 3],
                "t4": {
                    "maxt": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T5 [Indent level: 3],
                "t5": {
                    "maxt": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T6 [Indent level: 3],
                "t6": {
                    "maxt": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T7 [Indent level: 3],
                "t7": {
                    "maxt": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T8 [Indent level: 3],
                "t8": {
                    "maxt": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T9 [Indent level: 3],
                "t9": {
                    "maxt": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T10 [Indent level: 3],
                "t10": {
                    "maxt": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T11 [Indent level: 3],
                "t11": {
                    "maxt": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T12 [Indent level: 3],
                "t12": {
                    "maxt": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T13 [Indent level: 3],
                "t13": {
                    "maxt": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T14 [Indent level: 3],
                "t14": {
                    "maxt": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T15 [Indent level: 3],
                "t15": {
                    "maxt": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T16 [Indent level: 3],
                "t16": {
                    "maxt": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T17 [Indent level: 3],
                "t17": {
                    "maxt": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T18 [Indent level: 3],
                "t18": {
                    "maxt": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T19 [Indent level: 3],
                "t19": {
                    "maxt": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T20 [Indent level: 3],
                "t20": {
                    "maxt": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T21 [Indent level: 3],
                "t21": {
                    "maxt": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T22 [Indent level: 3],
                "t22": {
                    "maxt": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        # Class: CfgWeapons|Default|GunClouds [Indent level: 1],
        "gunclouds": {
            "access": 0,
            "cloudletgrowup": 0.05,
            "cloudletfadein": 0,
            "cloudletfadeout": 0.1,
            "cloudletduration": 0.05,
            "cloudletalpha": 0.3,
            "cloudletaccy": 0,
            "cloudletminyspeed": -100,
            "cloudletmaxyspeed": 100,
            "interval": -0.02,
            "size": 0.3,
            "sourcesize": 0.02,
            "cloudletanimperiod": 1,
            "cloudletsize": 1,
            "cloudletshape": "cloudletClouds",
            "cloudletcolor": [1,1,1,0],
            "timetolive": 0,
            "initt": 0,
            "deltat": 0,
            # Class: CfgWeapons|Default|GunClouds|Table [Indent level: 2],
            "table": {
                # Class: CfgWeapons|Default|GunClouds|Table|T0 [Indent level: 3]
                "t0": {
                    "maxt": 0,
                    "color": [1,1,1,0]
                }
            }
        },
        "texturetype": "default",
        "aimtransitionspeed": 1
    },
    "rhs_deployedhandanim": "RHS_GestureHoldM107",
    "_generalmacro": "GM6_base_F",
    "cursor": "srifle",
    "opticsppeffects": [],
    "opticsflare": 1,
    "opticsdisableperipherialvision": 1,
    "bullet1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|big|metal_1.ogg",2.0099,1,10],
    "bullet2": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|big|metal_2.ogg",2.0099,1,10],
    "bullet3": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|big|metal_3.ogg",2.0099,1,10],
    "bullet4": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|big|metal_4.ogg",2.0099,1,10],
    "bullet5": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|big|dirt_1.ogg",2.0099,1,10],
    "bullet6": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|big|dirt_2.ogg",2.0099,1,10],
    "bullet7": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|big|dirt_3.ogg",2.0099,1,10],
    "bullet8": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|big|dirt_4.ogg",2.0099,1,10],
    "bullet9": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|big|grass_1.ogg",2.0099,1,10],
    "bullet10": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|big|grass_2.ogg",2.0099,1,10],
    "bullet11": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|big|grass_3.ogg",2.0099,1,10],
    "bullet12": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|shells|big|grass_4.ogg",2.0099,1,10],
    "soundbullet": ["bullet1",0.08,"bullet2",0.084,"bullet3",0.084,"bullet4",0.084,"bullet5",0.093,"bullet6",0.093,"bullet7",0.074,"bullet8",0.074,"bullet9",0.084,"bullet10",0.085,"bullet11",0.083,"bullet12",0.083],
    "modes": ["Single","far_optic1","medium_optic2","far_optic2"],
    "drysound": ["A3|Sounds_F|arsenal|weapons|LongRangeRifles|GM6_Lynx|GM6_dry",0.562341,1,15],
    "soundbipoddeploy": ["A3|Sounds_F_Mark|arsenal|sfx|bipods|Bipod_generic_deploy",0.707946,1,20],
    "soundbipodfold": ["A3|Sounds_F_Mark|arsenal|sfx|bipods|Bipod_generic_fold",0.707946,1,20],
    "soundbipoddown": ["A3|Sounds_F_Mark|arsenal|sfx|bipods|Bipod_generic_down",0.707946,1,20],
    "soundbipodup": ["A3|Sounds_F_Mark|arsenal|sfx|bipods|Bipod_generic_up",0.707946,1,20],
    # Class: CfgWeapons|GM6_base_F|far_optic1 [Indent level: 1],
    "far_optic1": {
        "showtoplayer": 0,
        "minrange": 150,
        "minrangeprobab": 0.2,
        "midrange": 500,
        "midrangeprobab": 0.7,
        "maxrange": 1500,
        "maxrangeprobab": 0.4,
        "airateoffire": 3,
        "airateoffiredistance": 500,
        "requiredoptictype": 1,
        "dispersion": 0.00035,
        "soundcontinuous": 0,
        "reloadtime": 0.4,
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.03,0.110829,0.0516528,0.03,0.190902,0.0210168,0.03,0.059265,0.01528,0.03,0.022164,0.007296,0.03,-0.007206,-0.003072,0.03,-0.01059,-0.009024,0.03,-0.011031,-0.007056,0.03,-0.009414,-0.003,0.03,-0.006618,-0.000704,0.03,0,0],
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.03,0.110829,0.0114784,0.03,0.190902,0.0070056,0.03,0.059265,0.0079456,0.03,0.022164,0.003876,0.03,-0.007206,-0.000768,0.03,-0.01059,-0.004512,0.03,-0.011031,-0.003528,0.03,-0.009414,-0.002,0.03,-0.006618,-0.000352,0.03,0,0],
        "sounds": ["standardsound","silencedsound"],
        # Class: CfgWeapons|GM6_base_F|Single|BaseSoundModeType [Indent level: 2],
        "basesoundmodetype": {
        },
        # Class: CfgWeapons|GM6_base_F|Single|StandardSound [Indent level: 2],
        "standardsound": {
            "soundsetshot": ["jsrs_gm6_shot_soundset","jsrs_12x7mm_reverb_soundset"]
        },
        # Class: CfgWeapons|GM6_base_F|Single|SilencedSound [Indent level: 2],
        "silencedsound": {
            "closure1": ["a3|sounds_f|arsenal|weapons|longrangerifles|m320|m320_closure_01",1.77828,1,10],
            "closure2": ["a3|sounds_f|arsenal|weapons|longrangerifles|m320|m320_closure_01",1.77828,1,10],
            "soundclosure": ["closure1",0.5,"closure2",0.5]
        },
        "multiplier": 1,
        "burst": 1,
        "burstrangemax": -1,
        "sound": ["",10,1],
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundend": [],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "autofire": 0,
        "useaction": 0,
        "useactiontitle": "",
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "displayname": "Semi",
        "texturetype": "semi",
        "aidispersioncoefy": 1.7,
        "aidispersioncoefx": 1.4,
        "soundburst": 0,
        "airateoffiredispersion": 1
    },
    # Class: CfgWeapons|GM6_base_F|medium_optic2 [Indent level: 1],
    "medium_optic2": {
        "showtoplayer": 0,
        "minrange": 250,
        "minrangeprobab": 0.2,
        "midrange": 750,
        "midrangeprobab": 0.7,
        "maxrange": 1000,
        "maxrangeprobab": 0.4,
        "airateoffire": 5,
        "airateoffiredistance": 1000,
        "requiredoptictype": 2,
        "dispersion": 0.00035,
        "soundcontinuous": 0,
        "reloadtime": 0.4,
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.03,0.110829,0.0516528,0.03,0.190902,0.0210168,0.03,0.059265,0.01528,0.03,0.022164,0.007296,0.03,-0.007206,-0.003072,0.03,-0.01059,-0.009024,0.03,-0.011031,-0.007056,0.03,-0.009414,-0.003,0.03,-0.006618,-0.000704,0.03,0,0],
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.03,0.110829,0.0114784,0.03,0.190902,0.0070056,0.03,0.059265,0.0079456,0.03,0.022164,0.003876,0.03,-0.007206,-0.000768,0.03,-0.01059,-0.004512,0.03,-0.011031,-0.003528,0.03,-0.009414,-0.002,0.03,-0.006618,-0.000352,0.03,0,0],
        "sounds": ["standardsound","silencedsound"],
        # Class: CfgWeapons|GM6_base_F|Single|BaseSoundModeType [Indent level: 2],
        "basesoundmodetype": {
        },
        # Class: CfgWeapons|GM6_base_F|Single|StandardSound [Indent level: 2],
        "standardsound": {
            "soundsetshot": ["jsrs_gm6_shot_soundset","jsrs_12x7mm_reverb_soundset"]
        },
        # Class: CfgWeapons|GM6_base_F|Single|SilencedSound [Indent level: 2],
        "silencedsound": {
            "closure1": ["a3|sounds_f|arsenal|weapons|longrangerifles|m320|m320_closure_01",1.77828,1,10],
            "closure2": ["a3|sounds_f|arsenal|weapons|longrangerifles|m320|m320_closure_01",1.77828,1,10],
            "soundclosure": ["closure1",0.5,"closure2",0.5]
        },
        "multiplier": 1,
        "burst": 1,
        "burstrangemax": -1,
        "sound": ["",10,1],
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundend": [],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "autofire": 0,
        "useaction": 0,
        "useactiontitle": "",
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "displayname": "Semi",
        "texturetype": "semi",
        "aidispersioncoefy": 1.7,
        "aidispersioncoefx": 1.4,
        "soundburst": 0,
        "airateoffiredispersion": 1
    },
    # Class: CfgWeapons|GM6_base_F|far_optic2 [Indent level: 1],
    "far_optic2": {
        "minrange": 500,
        "minrangeprobab": 0.2,
        "midrange": 1200,
        "midrangeprobab": 0.7,
        "maxrange": 2100,
        "maxrangeprobab": 0.3,
        "airateoffire": 7,
        "airateoffiredistance": 1000,
        "requiredoptictype": 2,
        "showtoplayer": 0,
        "dispersion": 0.00035,
        "soundcontinuous": 0,
        "reloadtime": 0.4,
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.03,0.110829,0.0516528,0.03,0.190902,0.0210168,0.03,0.059265,0.01528,0.03,0.022164,0.007296,0.03,-0.007206,-0.003072,0.03,-0.01059,-0.009024,0.03,-0.011031,-0.007056,0.03,-0.009414,-0.003,0.03,-0.006618,-0.000704,0.03,0,0],
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.03,0.110829,0.0114784,0.03,0.190902,0.0070056,0.03,0.059265,0.0079456,0.03,0.022164,0.003876,0.03,-0.007206,-0.000768,0.03,-0.01059,-0.004512,0.03,-0.011031,-0.003528,0.03,-0.009414,-0.002,0.03,-0.006618,-0.000352,0.03,0,0],
        "sounds": ["standardsound","silencedsound"],
        # Class: CfgWeapons|GM6_base_F|Single|BaseSoundModeType [Indent level: 2],
        "basesoundmodetype": {
        },
        # Class: CfgWeapons|GM6_base_F|Single|StandardSound [Indent level: 2],
        "standardsound": {
            "soundsetshot": ["jsrs_gm6_shot_soundset","jsrs_12x7mm_reverb_soundset"]
        },
        # Class: CfgWeapons|GM6_base_F|Single|SilencedSound [Indent level: 2],
        "silencedsound": {
            "closure1": ["a3|sounds_f|arsenal|weapons|longrangerifles|m320|m320_closure_01",1.77828,1,10],
            "closure2": ["a3|sounds_f|arsenal|weapons|longrangerifles|m320|m320_closure_01",1.77828,1,10],
            "soundclosure": ["closure1",0.5,"closure2",0.5]
        },
        "multiplier": 1,
        "burst": 1,
        "burstrangemax": -1,
        "sound": ["",10,1],
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundend": [],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "autofire": 0,
        "useaction": 0,
        "useactiontitle": "",
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "displayname": "Semi",
        "texturetype": "semi",
        "aidispersioncoefy": 1.7,
        "aidispersioncoefx": 1.4,
        "soundburst": 0,
        "airateoffiredispersion": 1
    },
    # Class: CfgWeapons|Rifle_Long_Base_F|FullAuto [Indent level: 1],
    "fullauto": {
    },
    "htmin": 1,
    "htmax": 600,
    "afmax": 0,
    "mfmax": 0,
    "mfact": 1,
    "tbody": 100,
    "autofire": 1,
    "soundcontinuous": 0,
    "cursoraim": "CursorAim",
    "value": 4,
    "namesound": "rifle",
    "reloadtime": 0.15,
    "modeloptics": "-",
    "sound": [],
    "autoreload": 0,
    "maxleadspeed": 23,
    "canlock": 0,
    "flash": "gunfire",
    "flashsize": 0.5,
    "dispersion": 0.00029,
    # Recoil Array: recoilprone,
    "recoilprone": [0,0,0,0.06,0.01,0.01,0.1,0,-0.02,0.1,-0.01,0.01,0.05,0,0],
    "ffmagnitude": 0.5,
    "fffrequency": 11,
    "ffcount": 3,
    "weaponpoolavailable": 1,
    "zeroingsound": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|noises|rifle_zeroing_1.ogg",5,1,5],
    "type": 1,
    "airateoffire": 0.5,
    "airateoffiredistance": 500,
    "access": 3,
    "uipicture": "",
    "ammo": "",
    "cursorsize": 1,
    "showaimcursorinternal": 1,
    "cursoraimon": "",
    "laser": 0,
    "hiddenunderwaterselections": [],
    "shownunderwaterselections": [],
    "hiddenunderwaterselectionstextures": [],
    "simulation": "Weapon",
    "count": 0,
    "multiplier": 1,
    "burst": 1,
    "magazinereloadtime": 0,
    "magazinereloadswitchphase": 1,
    "soundbegin": ["sound",1],
    "soundbeginwater": ["sound",1],
    "soundclosure": ["sound",1],
    "soundend": ["sound",1],
    "soundloop": ["sound",1],
    "weaponsoundeffect": "",
    "soundburst": 1,
    "reloadsound": ["",1,1],
    "changefiremodesound": ["",1,1],
    "emptysound": ["",1,1],
    "initspeed": 0,
    "ballisticscomputer": 0,
    "irdistance": 0,
    "irdotintensity": 0.001,
    "lockacquire": 1,
    "enableattack": 1,
    "modelspecial": "",
    "modelmagazine": "",
    "muzzlepos": "usti hlavne",
    "muzzleend": "konec hlavne",
    "irlaserpos": "laser pos",
    "irlaserend": "laser dir",
    "cartridgepos": "nabojnicestart",
    "cartridgevel": "nabojniceend",
    "selectionfireanim": "zasleh",
    "memorypointcamera": "eye",
    "firespreadangle": 3,
    "usemodeloptics": 1,
    "opticsid": 0,
    "forceoptics": 0,
    "useasbinocular": 0,
    "primary": 10,
    "showswitchaction": 0,
    "showempty": 1,
    "showtoplayer": 1,
    "canshootinwater": 0,
    "airateoffiredispersion": 0,
    "firelightduration": 0.05,
    "firelightintensity": 0.2,
    "firelightdiffuse": [0.937,0.631,0.259],
    "firelightambient": [0,0,0],
    # Class: CfgWeapons|Default|Eventhandlers [Indent level: 1],
    "eventhandlers": {
    },
    "backgroundreload": 0,
    "useaction": 0,
    "useactiontitle": "",
    "candrop": 1,
    "weaponlockdelay": 0,
    "weaponlocksystem": 0,
    "cmimmunity": 1,
    "weight": 0,
    "minrange": 1,
    "minrangeprobab": 0.3,
    "midrange": 150,
    "midrangeprobab": 0.58,
    "maxrange": 500,
    "maxrangeprobab": 0.04,
    "lockingtargetsound": ["",0.000316228,2],
    "lockedtargetsound": ["",0.000316228,6],
    "detectrange": 0,
    "artillerydispersion": 1,
    "artillerycharge": 1,
    "fireanims": [],
    # Class: CfgWeapons|Default|GunFire [Indent level: 1],
    "gunfire": {
        "access": 0,
        "cloudletduration": 0.2,
        "cloudletanimperiod": 1,
        "cloudletsize": 1,
        "cloudletalpha": 1,
        "cloudletgrowup": 0.2,
        "cloudletfadein": 0.01,
        "cloudletfadeout": 0.5,
        "cloudletaccy": 0,
        "cloudletminyspeed": -100,
        "cloudletmaxyspeed": 100,
        "cloudletshape": "cloudletFire",
        "cloudletcolor": [1,1,1,0],
        "cloudletdensitycoef": -1,
        "interval": -0.01,
        "size": 3,
        "sourcesize": 0.5,
        "timetolive": 0,
        "initt": 4500,
        "deltat": -3000,
        # Class: CfgWeapons|Default|GunFire|Table [Indent level: 2],
        "table": {
            # Class: CfgWeapons|Default|GunFire|Table|T0 [Indent level: 3]
            "t0": {
                "maxt": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T1 [Indent level: 3],
            "t1": {
                "maxt": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T2 [Indent level: 3],
            "t2": {
                "maxt": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T3 [Indent level: 3],
            "t3": {
                "maxt": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T4 [Indent level: 3],
            "t4": {
                "maxt": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T5 [Indent level: 3],
            "t5": {
                "maxt": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T6 [Indent level: 3],
            "t6": {
                "maxt": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T7 [Indent level: 3],
            "t7": {
                "maxt": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T8 [Indent level: 3],
            "t8": {
                "maxt": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T9 [Indent level: 3],
            "t9": {
                "maxt": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T10 [Indent level: 3],
            "t10": {
                "maxt": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T11 [Indent level: 3],
            "t11": {
                "maxt": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T12 [Indent level: 3],
            "t12": {
                "maxt": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T13 [Indent level: 3],
            "t13": {
                "maxt": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T14 [Indent level: 3],
            "t14": {
                "maxt": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T15 [Indent level: 3],
            "t15": {
                "maxt": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T16 [Indent level: 3],
            "t16": {
                "maxt": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T17 [Indent level: 3],
            "t17": {
                "maxt": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T18 [Indent level: 3],
            "t18": {
                "maxt": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T19 [Indent level: 3],
            "t19": {
                "maxt": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T20 [Indent level: 3],
            "t20": {
                "maxt": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T21 [Indent level: 3],
            "t21": {
                "maxt": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T22 [Indent level: 3],
            "t22": {
                "maxt": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgWeapons|Default|GunClouds [Indent level: 1],
    "gunclouds": {
        "access": 0,
        "cloudletgrowup": 0.05,
        "cloudletfadein": 0,
        "cloudletfadeout": 0.1,
        "cloudletduration": 0.05,
        "cloudletalpha": 0.3,
        "cloudletaccy": 0,
        "cloudletminyspeed": -100,
        "cloudletmaxyspeed": 100,
        "interval": -0.02,
        "size": 0.3,
        "sourcesize": 0.02,
        "cloudletanimperiod": 1,
        "cloudletsize": 1,
        "cloudletshape": "cloudletClouds",
        "cloudletcolor": [1,1,1,0],
        "timetolive": 0,
        "initt": 0,
        "deltat": 0,
        # Class: CfgWeapons|Default|GunClouds|Table [Indent level: 2],
        "table": {
            # Class: CfgWeapons|Default|GunClouds|Table|T0 [Indent level: 3]
            "t0": {
                "maxt": 0,
                "color": [1,1,1,0]
            }
        }
    },
    "texturetype": "default",
}