rhsusf_weap_MP7A2 = {
    "author": "Red Hammer Studios",
    "dlc": "RHS_USAF",
    "picture": "rhsusf|addons|rhsusf_inventoryicons|data|weapons|rhsusf_weap_MP7A2_ca.paa",
    "displayName": "MP7A2",
    "scope": 2,
    "baseweapon": "rhsusf_weap_MP7A2",
    "initspeed": -1,
    "magazines": ["rhsusf_mag_40Rnd_46x30_FMJ","rhsusf_mag_40Rnd_46x30_JHP","rhsusf_mag_40Rnd_46x30_AP"],
    "magazineWell": ["CBA_46x30_MP7"],
    # Class: CfgWeapons\rhsusf_weap_MP7A1_base_f\Library,
    "Library": {
        "libTextDesc": "Smaller than a conventional submachine gun, the 4.6mm MP7A1 is a compact and lightweight Personal Defense Weapon that can be carried like a handgun yet is capable of rifle-like effectiveness.."
    },
    "model": "rhsusf|addons|rhsusf_weapons2|MP7|mp7a2",
    "reloadAction": "GestureReloadSMG_02",
    "maxZeroing": 200,
    "discreteDistance": [100,200],
    "maxRecoilSway": 0.0125,
    "swayDecaySpeed": 1.25,
    "inertia": 0.35,
    # Class: CfgWeapons\rhsusf_weap_MP7A1_base_f\GunParticles,
    "GunParticles": {
        # Class: CfgWeapons\rhsusf_weap_MP7A1_base_f\GunParticles\SecondEffect
        "SecondEffect": {
            "positionName": "Nabojnicestart",
            "directionName": "Nabojniceend",
            "effectName": "CaselessAmmoCloud"
        },
        # Class: CfgWeapons\Rifle_Base_F\GunParticles\FirstEffect,
        "FirstEffect": {
            "effectName": "RifleAssaultCloud",
            "positionName": "Usti hlavne",
            "directionName": "Konec hlavne"
        }
    },
    # Class: CfgWeapons\rhsusf_weap_MP7A1_base_f\WeaponSlotsInfo,
    "WeaponSlotsInfo": {
        "mass": 24.2,
        "allowedSlots": [901],
        # Class: CfgWeapons\rhsusf_weap_MP7A1_base_f\WeaponSlotsInfo\MuzzleSlot,
        "MuzzleSlot": {
            "iconPosition": [0.05,0.38],
            "iconScale": 0.2,
            "iconPicture": "A3|Weapons_F|Data|clear_empty.paa",
            "iconPinPoint": "Left",
            # Class: rhs_western_46mmsmg_muzzle_slot\compatibleItems,
            "compatibleItems": {
                "rhsusf_acc_rotex_mp7": 1,
                "rhsusf_acc_rotex_mp7_desert": 1,
                "rhsusf_acc_rotex_mp7_winter": 1,
                "rhsusf_acc_rotex_mp7_aor1": 1
            },
            "displayName": "$str_a3_cfgweapons_abr_base_f_weaponslotsinfo_muzzleslot0",
            "linkProxy": "A3|data_f|proxies|weapon_slots|MUZZLE"
        },
        # Class: CfgWeapons\rhsusf_weap_MP7A1_base_f\WeaponSlotsInfo\CowsSlot,
        "CowsSlot": {
            "iconPosition": [0.5,0.3],
            "iconScale": 0.2,
            # Class: asdg_OpticRail1913_short\compatibleItems,
            "compatibleItems": {
                "rhsusf_acc_LEUPOLDMK4": 0,
                "rhsusf_acc_LEUPOLDMK4_d": 0,
                "rhsusf_acc_LEUPOLDMK4_wd": 0,
                "rhsusf_acc_LEUPOLDMK4_2": 0,
                "rhsusf_acc_LEUPOLDMK4_2_d": 0,
                "rhsusf_acc_LEUPOLDMK4_2_MRDS": 0,
                "rhsusf_acc_premier": 0,
                "rhsusf_acc_premier_low": 0,
                "rhsusf_acc_premier_anpvs27": 0,
                "rhsusf_acc_ACOG_anpvs27": 0,
                "rhsusf_acc_SpecterDR_pvs27": 0,
                "rhs_acc_rakursPM": 1,
                "rhs_acc_dh520x56": 1,
                "rhs_acc_ekp8_18": 1,
                "rhs_acc_ekp8_18b": 1,
                "rhs_acc_ekp8_18c": 1,
                "rhs_acc_ekp8_18d": 1,
                "rhs_acc_1p87": 1,
                "rhs_acc_okp7_picatinny": 1,
                "optic_Nightstalker": 1,
                "optic_tws": 1,
                "optic_tws_mg": 1,
                "optic_NVS": 1,
                "optic_SOS": 1,
                "optic_SOS_khk_F": 1,
                "optic_MRCO": 1,
                "optic_Arco": 1,
                "optic_Arco_ghex_F": 1,
                "optic_Arco_blk_F": 1,
                "optic_aco": 1,
                "optic_ACO_grn": 1,
                "optic_aco_smg": 1,
                "optic_ACO_grn_smg": 1,
                "optic_hamr": 1,
                "optic_Hamr_khk_F": 1,
                "optic_Holosight": 1,
                "optic_Holosight_smg": 1,
                "optic_Holosight_blk_F": 1,
                "optic_Holosight_khk_F": 1,
                "optic_Holosight_smg_blk_F": 1,
                "optic_DMS": 1,
                "optic_DMS_ghex_F": 1,
                "optic_LRPS": 1,
                "optic_LRPS_ghex_F": 1,
                "optic_LRPS_tna_F": 1,
                "optic_AMS": 1,
                "optic_AMS_khk": 1,
                "optic_AMS_snd": 1,
                "optic_KHS_blk": 1,
                "optic_KHS_hex": 1,
                "optic_KHS_old": 1,
                "optic_KHS_tan": 1,
                "optic_ERCO_blk_F": 1,
                "optic_ERCO_khk_F": 1,
                "optic_ERCO_snd_F": 1,
                "rhsusf_acc_premier_mrds": 1,
                "rhsusf_acc_M8541": 1,
                "rhsusf_acc_M8541_mrds": 1,
                "rhsusf_acc_M8541_low": 1,
                "rhsusf_acc_M8541_low_d": 1,
                "rhsusf_acc_M8541_low_wd": 1,
                "rhsusf_acc_EOTECH": 1,
                "rhsusf_acc_eotech_552": 1,
                "rhsusf_acc_eotech_552_d": 1,
                "rhsusf_acc_eotech_552_wd": 1,
                "rhsusf_acc_eotech_xps3": 1,
                "rhsusf_acc_g33_xps3": 1,
                "rhsusf_acc_g33_xps3_flip": 1,
                "rhsusf_acc_g33_xps3_tan": 1,
                "rhsusf_acc_g33_xps3_tan_flip": 1,
                "rhsusf_acc_g33_t1": 1,
                "rhsusf_acc_g33_t1_flip": 1,
                "rhsusf_acc_compm4": 1,
                "rhsusf_acc_T1_high": 1,
                "rhsusf_acc_T1_low": 1,
                "rhsusf_acc_RX01": 1,
                "rhsusf_acc_RX01_NoFilter": 1,
                "rhsusf_acc_RX01_tan": 1,
                "rhsusf_acc_RX01_NoFilter_tan": 1,
                "rhsusf_acc_RM05": 1,
                "rhsusf_acc_mrds": 1,
                "rhsusf_acc_mrds_c": 1,
                "rhsusf_acc_ACOG": 1,
                "rhsusf_acc_ACOG2": 1,
                "rhsusf_acc_ACOG3": 1,
                "rhsusf_acc_ACOG_wd": 1,
                "rhsusf_acc_ACOG_d": 1,
                "rhsusf_acc_ACOG_sa": 1,
                "rhsusf_acc_ACOG_USMC": 1,
                "rhsusf_acc_ACOG2_USMC": 1,
                "rhsusf_acc_ACOG3_USMC": 1,
                "rhsusf_acc_ACOG_RMR": 1,
                "rhsusf_acc_ACOG_PIP": 1,
                "rhsusf_acc_ACOG2_pip": 1,
                "rhsusf_acc_ACOG3_pip": 1,
                "rhsusf_acc_ACOG_wd_pip": 1,
                "rhsusf_acc_ACOG_d_pip": 1,
                "rhsusf_acc_ACOG_sa_pip": 1,
                "rhsusf_acc_ACOG_USMC_pip": 1,
                "rhsusf_acc_ACOG2_USMC_pip": 1,
                "rhsusf_acc_ACOG3_USMC_pip": 1,
                "rhsusf_acc_ACOG_RMR_PIP": 1,
                "rhsusf_acc_ACOG_3d": 1,
                "rhsusf_acc_ACOG2_3d": 1,
                "rhsusf_acc_ACOG3_3d": 1,
                "rhsusf_acc_ACOG_wd_3d": 1,
                "rhsusf_acc_ACOG_d_3d": 1,
                "rhsusf_acc_ACOG_sa_3d": 1,
                "rhsusf_acc_ACOG_USMC_3d": 1,
                "rhsusf_acc_ACOG2_USMC_3d": 1,
                "rhsusf_acc_ACOG3_USMC_3d": 1,
                "rhsusf_acc_ACOG_RMR_3d": 1,
                "rhsusf_acc_ELCAN": 1,
                "rhsusf_acc_ELCAN_ard": 1,
                "rhsusf_acc_ELCAN_3d": 1,
                "rhsusf_acc_ELCAN_ard_3d": 1,
                "rhsusf_acc_ELCAN_PIP": 1,
                "rhsusf_acc_ELCAN_ard_PIP": 1,
                "rhsusf_acc_su230": 1,
                "rhsusf_acc_su230_mrds": 1,
                "rhsusf_acc_su230a": 1,
                "rhsusf_acc_su230a_mrds": 1,
                "rhsusf_acc_su230_c": 1,
                "rhsusf_acc_su230_mrds_c": 1,
                "rhsusf_acc_su230a_c": 1,
                "rhsusf_acc_su230a_mrds_c": 1,
                "rhsusf_acc_su230_3d": 1,
                "rhsusf_acc_su230_mrds_3d": 1,
                "rhsusf_acc_su230a_3d": 1,
                "rhsusf_acc_su230a_mrds_3d": 1,
                "rhsusf_acc_su230_c_3d": 1,
                "rhsusf_acc_su230_mrds_c_3d": 1,
                "rhsusf_acc_su230a_c_3d": 1,
                "rhsusf_acc_su230a_mrds_c_3d": 1,
                "rhsusf_acc_SpecterDR": 1,
                "rhsusf_acc_SpecterDR_3d": 1,
                "rhsusf_acc_SpecterDR_A": 1,
                "rhsusf_acc_SpecterDR_A_3d": 1,
                "rhsusf_acc_SpecterDR_CX": 1,
                "rhsusf_acc_SpecterDR_CX_3D": 1,
                "rhsusf_acc_SpecterDR_D": 1,
                "rhsusf_acc_SpecterDR_OD": 1,
                "rhsusf_acc_SpecterDR_D_3D": 1,
                "rhsusf_acc_SpecterDR_OD_3D": 1,
                "rhsusf_acc_anpvs27": 1,
                "rhsusf_acc_anpas13gv1": 1,
                "rhsusf_acc_M2A1": 1,
                "rhsusf_acc_ACOG_MDO": 1,
                "rhsgref_acc_RX01_camo": 1,
                "rhsgref_acc_RX01_NoFilter_camo": 1
            },
            "linkProxy": "A3|data_f|proxies|weapon_slots|TOP",
            "displayName": "Optics Slot"
        },
        # Class: CfgWeapons\rhsusf_weap_MP7A1_base_f\WeaponSlotsInfo\PointerSlot,
        "PointerSlot": {
            "iconPosition": [0.35,0.4],
            "iconScale": 0.25,
            "iconPicture": "A3|Weapons_F|Data|clear_empty.paa",
            "iconPinPoint": "Left",
            # Class: rhs_western_rifle_laser_slot\compatibleItems,
            "compatibleItems": {
                "rhsusf_acc_anpeq15": 0,
                "rhsusf_acc_anpeq15_top": 0,
                "rhsusf_acc_anpeq15_light": 0,
                "rhsusf_acc_anpeq15_bk": 0,
                "rhsusf_acc_anpeq15_bk_top": 0,
                "rhsusf_acc_anpeq15_bk_light": 0,
                "rhsusf_acc_anpeq15_wmx": 0,
                "rhsusf_acc_anpeq15_wmx_light": 0,
                "rhsusf_acc_anpeq16a_top": 0,
                "rhsusf_acc_anpeq16a_light_top": 0,
                "rhsusf_acc_anpeq16a_top_h": 0,
                "rhsusf_acc_anpeq16a_light_top_h": 0,
                "rhs_acc_2dpZenit_ris": 1,
                "rhs_acc_perst1ik_ris": 1,
                "rhs_acc_perst3": 1,
                "acc_flashlight": 1,
                "acc_pointer_IR": 1,
                "rhsusf_acc_wmx": 1,
                "rhsusf_acc_wmx_bk": 1,
                "rhsusf_acc_M952V": 1,
                "rhsusf_acc_anpeq15A": 1,
                "rhsusf_acc_anpeq15_h": 1,
                "rhsusf_acc_anpeq15_light_h": 1,
                "rhsusf_acc_anpeq15_top_h": 1,
                "rhsusf_acc_anpeq15_sc": 1,
                "rhsusf_acc_anpeq15_light_sc": 1,
                "rhsusf_acc_anpeq15_top_sc": 1,
                "rhsusf_acc_anpeq15side": 1,
                "rhsusf_acc_anpeq15_bk_h": 1,
                "rhsusf_acc_anpeq15_bk_light_h": 1,
                "rhsusf_acc_anpeq15_bk_top_h": 1,
                "rhsusf_acc_anpeq15_bk_sc": 1,
                "rhsusf_acc_anpeq15_bk_light_sc": 1,
                "rhsusf_acc_anpeq15_bk_top_sc": 1,
                "rhsusf_acc_anpeq15side_bk": 1,
                "rhsusf_acc_anpeq15_wmx_h": 1,
                "rhsusf_acc_anpeq15_wmx_light_h": 1,
                "rhsusf_acc_anpeq15_wmx_sc": 1,
                "rhsusf_acc_anpeq15_wmx_light_sc": 1,
                "rhsusf_acc_anpeq16a": 1,
                "rhsusf_acc_anpeq16a_light": 1,
                "rhsusf_acc_anpeq16a_top_sc": 1,
                "rhsusf_acc_anpeq16a_light_top_sc": 1
            },
            "linkProxy": "a3|data_f|proxies|weapon_slots|side",
            "displayName": "Pointer Slot"
        },
        # Class: CfgWeapons\rhsusf_weap_MP7A1_base_f\WeaponSlotsInfo\GripodSlot,
        "GripodSlot": {
            "linkProxy": "rhsusf|addons|rhsusf_weapons|rhs_grip_proxy",
            "iconPosition": [0,0],
            # Class: rhs_rifle_gripod_slot\compatibleItems,
            "compatibleItems": {
                "rhs_acc_grip_rk2": 1,
                "rhs_acc_grip_rk6": 1,
                "rhs_acc_grip_ffg2": 1,
                "rhsusf_acc_grip1": 1,
                "rhsusf_acc_grip2": 1,
                "rhsusf_acc_grip2_tan": 1,
                "rhsusf_acc_grip2_wd": 1,
                "rhsusf_acc_grip3": 1,
                "rhsusf_acc_grip3_tan": 1,
                "rhsusf_acc_kac_grip": 1,
                "rhsusf_acc_rvg_blk": 1,
                "rhsusf_acc_rvg_de": 1,
                "rhsusf_acc_tacsac_blk": 1,
                "rhsusf_acc_tacsac_tan": 1,
                "rhsusf_acc_tacsac_blue": 1,
                "rhsusf_acc_tdstubby_blk": 1,
                "rhsusf_acc_tdstubby_tan": 1
            },
            "iconScale": 1,
            "iconPicture": "A3|Weapons_F|Data|clear_empty.paa",
            "iconPinPoint": "Left",
            "displayName": "Gripod slot",
            "access": 1,
            "scope": 0
        }
    },
    "opticsZoomMin": 0.25,
    "opticsZoomMax": 1.25,
    "opticsZoomInit": 0.75,
    "distanceZoomMin": 100,
    "distanceZoomMax": 100,
    "descriptionShort": "Sub-machine gun <br/>Caliber: 4.6x30 mm",
    "handAnim": ["OFP2_ManSkeleton","|rhsusf|addons|rhsusf_c_weapons|anims|rhs_hand_MP7.rtm"],
    "caseless": ["",1,1,1],
    "soundBullet": ["caseless",1],
    "selectionfireanim": "zasleh",
    "hiddenSelections": ["camo","camo2","camoB"],
    "hiddenSelectionsTextures": ["rhsusf|addons|rhsusf_weapons2|mp7|mp7a2|data|mp7_co.paa","rhsusf|addons|rhsusf_weapons2|mp7|mp7a2|data|mp7_buis_co.paa","rhsusf|addons|rhsusf_weapons2|mp7|mp7a2|data|mp7_acc1_blk_co.paa"],
    "modes": ["Single","FullAuto"],
    # Class: CfgWeapons\rhsusf_weap_MP7A1_base_f\Single,
    "Single": {
        "reloadTime": 0.075,
        "dispersion": 0.00203,
        "minRange": 2,
        "minRangeProbab": 0.3,
        "midRange": 200,
        "midRangeProbab": 0.7,
        "maxRange": 350,
        "maxRangeProbab": 0.05,
        "aiRateOfFire": 2,
        "aiRateOfFireDistance": 500,
        # Class: CfgWeapons\rhsusf_weap_MP7A1_base_f\Single\StandardSound,
        "StandardSound": {
            "soundSetShot": ["RHSUSF_mp7_Shot_SoundSet","RHSUSF_rifle_small_Tail_SoundSet","RHSUSF_mp7_stereoLayer_SoundSet"]
        },
        # Class: CfgWeapons\rhsusf_weap_MP7A1_base_f\Single\SilencedSound,
        "SilencedSound": {
            "soundSetShot": ["RHSUSF_MP7_Closure_SoundSet","RHSUSF_MP7_ShotSD_SoundSet","RHSUSF_rifle1_SD_Tail_SoundSet"]
        },
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons\SMG_02_base_F\Single\BaseSoundModeType,
        "BaseSoundModeType": {
            "closure1": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|closure_Sting_01",1,1,10],
            "closure2": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|closure_Sting_02",1,1.1,10],
            "soundClosure": ["closure1",0.5,"closure2",0.5]
        },
        "recoil": "recoil_single_smg_02",
        "recoilProne": "recoil_single_prone_smg_02",
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "requiredOpticType": -1,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons\rhsusf_weap_MP7A1_base_f\FullAuto,
    "FullAuto": {
        "reloadTime": 0.075,
        "dispersion": 0.00203,
        "minRange": 0,
        "minRangeProbab": 0.1,
        "midRange": 25,
        "midRangeProbab": 0.7,
        "maxRange": 70,
        "maxRangeProbab": 0.05,
        "aiRateOfFire": 0.2,
        "aiRateOfFireDistance": 50,
        # Class: CfgWeapons\rhsusf_weap_MP7A1_base_f\FullAuto\StandardSound,
        "StandardSound": {
            "soundSetShot": ["RHSUSF_mp7_Shot_SoundSet","RHSUSF_rifle_small_Tail_SoundSet","RHSUSF_mp7_stereoLayer_SoundSet"]
        },
        # Class: CfgWeapons\rhsusf_weap_MP7A1_base_f\FullAuto\SilencedSound,
        "SilencedSound": {
            "soundSetShot": ["RHSUSF_MP7_Closure_SoundSet","RHSUSF_MP7_ShotSD_SoundSet","RHSUSF_rifle1_SD_Tail_SoundSet"]
        },
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons\SMG_02_base_F\FullAuto\BaseSoundModeType,
        "BaseSoundModeType": {
            "closure1": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|closure_Sting_01",1,1,10],
            "closure2": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|closure_Sting_02",1,1.1,10],
            "soundClosure": ["closure1",0.5,"closure2",0.5]
        },
        "recoil": "recoil_auto_smg_02",
        "recoilProne": "recoil_auto_prone_smg_02",
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "soundContinuous": 0,
        "autoFire": 1,
        "displayName": "Full",
        "textureType": "fullAuto",
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1,
        "aiRateOfFireDispersion": 1
    },
    "aiDispersionCoefY": 6,
    "aiDispersionCoefX": 4,
    "drySound": ["A3|sounds_f|weapons|Other|dry_1",0.562341,1,10],
    "reloadMagazineSound": ["rhsusf|addons|rhsusf_sounds|mp7|reload",1.3,1,13],
    "rhs_grip1_change": "rhsusf_weap_MP7A2_grip1",
    "rhs_grip2_change": "rhsusf_weap_MP7A2_grip2",
    "rhs_grip3_change": "rhsusf_weap_MP7A2_grip3",
    "_generalMacro": "SMG_02_base_F",
    "recoil": "recoil_smg_02",
    "cursor": "smg",
    "discreteDistanceInitIndex": 0,
    "bullet1": ["A3|sounds_f|weapons|shells|9mm|metal_9mm_01",0.501187,1,15],
    "bullet2": ["A3|sounds_f|weapons|shells|9mm|metal_9mm_02",0.501187,1,15],
    "bullet3": ["A3|sounds_f|weapons|shells|9mm|metal_9mm_03",0.501187,1,15],
    "bullet4": ["A3|sounds_f|weapons|shells|9mm|metal_9mm_04",0.501187,1,15],
    "bullet5": ["A3|sounds_f|weapons|shells|9mm|dirt_9mm_01",0.501187,1,15],
    "bullet6": ["A3|sounds_f|weapons|shells|9mm|dirt_9mm_02",0.501187,1,15],
    "bullet7": ["A3|sounds_f|weapons|shells|9mm|dirt_9mm_03",0.501187,1,15],
    "bullet8": ["A3|sounds_f|weapons|shells|9mm|dirt_9mm_04",0.501187,1,15],
    "bullet9": ["A3|sounds_f|weapons|shells|9mm|grass_9mm_01",0.398107,1,15],
    "bullet10": ["A3|sounds_f|weapons|shells|9mm|grass_9mm_02",0.398107,1,15],
    "bullet11": ["A3|sounds_f|weapons|shells|9mm|grass_9mm_03",0.398107,1,15],
    "bullet12": ["A3|sounds_f|weapons|shells|9mm|grass_9mm_04",0.398107,1,15],
    "changeFiremodeSound": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|firemode_Sting",0.251189,1,5],
    # Class: CfgWeapons\SMG_02_base_F\Burst,
    "Burst": {
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons\SMG_02_base_F\Burst\BaseSoundModeType,
        "BaseSoundModeType": {
            "closure1": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|closure_Sting_01",1,1,10],
            "closure2": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|closure_Sting_02",1,1.1,10],
            "soundClosure": ["closure1",0.5,"closure2",0.5]
        },
        # Class: CfgWeapons\SMG_02_base_F\Burst\StandardSound,
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|Sting_short_01",2.81838,1,1200],
            "begin2": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|Sting_short_02",2.81838,1,1200],
            "begin3": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|Sting_short_03",2.81838,1,1200],
            "soundBegin": ["begin1",0.33,"begin2",0.33,"begin3",0.34],
            # Class: CfgWeapons\SMG_02_base_F\Burst\StandardSound\SoundTails,
            "SoundTails": {
                # Class: CfgWeapons\SMG_02_base_F\Burst\StandardSound\SoundTails\TailInterior
                "TailInterior": {
                    "sound": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|Sting_tail_interior",1.58489,1,1200],
                    "frequency": 1,
                    "volume": "interior"
                },
                # Class: CfgWeapons\SMG_02_base_F\Burst\StandardSound\SoundTails\TailTrees,
                "TailTrees": {
                    "sound": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|Sting_tail_trees",1,1,1200],
                    "frequency": 1,
                    "volume": "(1-interior/1.4)*trees"
                },
                # Class: CfgWeapons\SMG_02_base_F\Burst\StandardSound\SoundTails\TailForest,
                "TailForest": {
                    "sound": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|Sting_tail_forest",1,1,1200],
                    "frequency": 1,
                    "volume": "(1-interior/1.4)*forest"
                },
                # Class: CfgWeapons\SMG_02_base_F\Burst\StandardSound\SoundTails\TailMeadows,
                "TailMeadows": {
                    "sound": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|Sting_tail_meadows",1,1,1200],
                    "frequency": 1,
                    "volume": "(1-interior/1.4)*(meadows/2 max sea/2)"
                },
                # Class: CfgWeapons\SMG_02_base_F\Burst\StandardSound\SoundTails\TailHouses,
                "TailHouses": {
                    "sound": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|Sting_tail_houses",1,1,1200],
                    "frequency": 1,
                    "volume": "(1-interior/1.4)*houses"
                }
            },
            "SoundSetShot": ["SMGSting_Shot_SoundSet","SMGSting_Tail_SoundSet","SMGSting_InteriorTail_SoundSet"],
            "closure1": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|closure_Sting_01",1,1,10],
            "closure2": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|closure_Sting_02",1,1.1,10],
            "soundClosure": ["closure1",0.5,"closure2",0.5]
        },
        # Class: CfgWeapons\SMG_02_base_F\Burst\SilencedSound,
        "SilencedSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|Silencer_Sting_short_01",0.891251,1,400],
            "begin2": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|Silencer_Sting_short_02",0.891251,1,400],
            "begin3": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|Silencer_Sting_short_03",0.891251,1,400],
            "soundBegin": ["begin1",0.33,"begin2",0.33,"begin3",0.34],
            # Class: CfgWeapons\SMG_02_base_F\Burst\SilencedSound\SoundTails,
            "SoundTails": {
                # Class: CfgWeapons\SMG_02_base_F\Burst\SilencedSound\SoundTails\TailInterior
                "TailInterior": {
                    "sound": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|Silencer_Sting_Tail_interior",1,1,400],
                    "frequency": 1,
                    "volume": "interior"
                },
                # Class: CfgWeapons\SMG_02_base_F\Burst\SilencedSound\SoundTails\TailTrees,
                "TailTrees": {
                    "sound": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|Silencer_Sting_Tail_trees",1,1,400],
                    "frequency": 1,
                    "volume": "(1-interior/1.4)*trees"
                },
                # Class: CfgWeapons\SMG_02_base_F\Burst\SilencedSound\SoundTails\TailForest,
                "TailForest": {
                    "sound": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|silencer_Sting_tail_forest",1,1,400],
                    "frequency": 1,
                    "volume": "(1-interior/1.4)*forest"
                },
                # Class: CfgWeapons\SMG_02_base_F\Burst\SilencedSound\SoundTails\TailMeadows,
                "TailMeadows": {
                    "sound": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|Silencer_Sting_Tail_meadows",1,1,400],
                    "frequency": 1,
                    "volume": "(1-interior/1.4)*(meadows/2 max sea/2)"
                },
                # Class: CfgWeapons\SMG_02_base_F\Burst\SilencedSound\SoundTails\TailHouses,
                "TailHouses": {
                    "sound": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|Silencer_Sting_Tail_houses",1,1,400],
                    "frequency": 1,
                    "volume": "(1-interior/1.4)*houses"
                }
            },
            "SoundSetShot": ["SMGSting_silencerShot_SoundSet","SMGSting_silencerTail_SoundSet","SMGSting_silencerInteriorTail_SoundSet"],
            "closure1": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|closure_Sting_01",1,1,10],
            "closure2": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|closure_Sting_02",1,1.1,10],
            "soundClosure": ["closure1",0.5,"closure2",0.5]
        },
        "soundBurst": 0,
        "burst": 3,
        "reloadTime": 0.0545,
        "dispersion": 0.00116,
        "recoil": "recoil_burst_smg_02",
        "recoilProne": "recoil_burst_prone_smg_02",
        "minRange": 2,
        "minRangeProbab": 0.3,
        "midRange": 50,
        "midRangeProbab": 0.7,
        "maxRange": 100,
        "maxRangeProbab": 0.05,
        "aiRateOfFire": 1,
        "aiRateOfFireDistance": 250,
        "sound": ["",10,1],
        "soundLoop": ["sound",1],
        "soundEnd": ["sound",1],
        "displayName": "Burst",
        "textureType": "burst",
        "aiDispersionCoefY": 2.4,
        "aiDispersionCoefX": 1.9,
        "multiplier": 1,
        "burstRangeMax": -1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons\SMG_02_base_F\UGL_F,
    "UGL_F": {
        "displayName": "EGLM",
        "magazines": ["1Rnd_HE_Grenade_shell","UGL_FlareWhite_F","UGL_FlareGreen_F","UGL_FlareRed_F","UGL_FlareYellow_F","UGL_FlareCIR_F","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeRed_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell","1Rnd_SmokeYellow_Grenade_shell","1Rnd_SmokePurple_Grenade_shell","1Rnd_SmokeBlue_Grenade_shell","1Rnd_SmokeOrange_Grenade_shell"],
        "magazineWell": ["UGL_40x36"],
        "changeFiremodeSound": ["A3|Sounds_F|arsenal|weapons|UGL|Firemode_ugl",0.316228,1,5],
        "reloadMagazineSound": ["A3|Sounds_F|arsenal|weapons|UGL|Reload_UGL",0.562341,1,10],
        "drySound": ["A3|Sounds_F|arsenal|weapons|UGL|Dry_ugl",0.562341,1,10],
        "modes": ["Single"],
        # Class: CfgWeapons\UGL_F\Single,
        "Single": {
            "sounds": ["StandardSound"],
            # Class: CfgWeapons\UGL_F\Single\BaseSoundModeType,
            "BaseSoundModeType": {
                "closure1": ["A3|Sounds_F|arsenal|weapons|UGL|Closure_UGL",1,1,10],
                "soundClosure": ["closure1",1]
            },
            # Class: CfgWeapons\UGL_F\Single\StandardSound,
            "StandardSound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons|UGL|UGL_01",0.707946,1,200],
                "begin2": ["A3|Sounds_F|arsenal|weapons|UGL|UGL_02",0.707946,1,200],
                "soundBegin": ["begin1",0.5,"begin2",0.5],
                "soundSetShot": ["UGL_shot_SoundSet","UGL_Tail_SoundSet","UGL_InteriorTail_SoundSet"],
                "closure1": ["A3|Sounds_F|arsenal|weapons|UGL|Closure_UGL",1,1,10],
                "soundClosure": ["closure1",1]
            },
            "recoil": "M240Recoil",
            "recoilProne": "M240Recoil",
            "minRange": 30,
            "minRangeProbab": 0.1,
            "midRange": 200,
            "midRangeProbab": 0.7,
            "maxRange": 400,
            "maxRangeProbab": 0.05,
            "multiplier": 1,
            "burst": 1,
            "burstRangeMax": -1,
            "dispersion": 0.0002,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "soundContinuous": 0,
            "weaponSoundEffect": "",
            "reloadTime": 0.1,
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "autoFire": 0,
            "useAction": 0,
            "useActionTitle": "",
            "showToPlayer": 1,
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "displayName": "Semi",
            "textureType": "semi",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1,
            "aiRateOfFire": 2,
            "aiRateOfFireDispersion": 1,
            "aiRateOfFireDistance": 500
        },
        "recoil": "recoil_default",
        "magazineReloadTime": 0,
        "reloadTime": 0.1,
        "optics": 1,
        "modelOptics": "-",
        "cameraDir": "UGL look",
        "memoryPointCamera": "UGL eye",
        "opticsZoomMin": 0.25,
        "opticsZoomMax": 1.25,
        "opticsZoomInit": 0.75,
        "weaponInfoType": "RscWeaponZeroing",
        "cursorAim": "gl",
        "cursor": "EmptyCursor",
        "value": 3,
        "type": 0,
        "reloadAction": "ReloadMagazine",
        "initSpeed": 75,
        "canLock": 0,
        "autoReload": 0,
        "autoAimEnabled": 0,
        "ffMagnitude": 0.1,
        "ffFrequency": 1,
        "ffCount": 1,
        "dispersion": 0.00725,
        "aiDispersionCoefY": 6,
        "maxLeadSpeed": 15,
        "muzzlePos": "usti granatometu",
        "muzzleEnd": "konec granatometu",
        "cartridgePos": "",
        "cartridgeVel": "",
        "minRange": 30,
        "minRangeProbab": 0.1,
        "midRange": 200,
        "midRangeProbab": 0.7,
        "maxRange": 400,
        "maxRangeProbab": 0.05,
        "textureType": "semi",
        "access": 3,
        "scope": 0,
        "picture": "",
        "uiPicture": "",
        "ammo": "",
        "cursorSize": 1,
        "showAimCursorInternal": 1,
        "cursorAimOn": "",
        "laser": 0,
        "hiddenSelections": [],
        "hiddenSelectionsTextures": [],
        "hiddenUnderwaterSelections": [],
        "shownUnderwaterSelections": [],
        "hiddenUnderwaterSelectionsTextures": [],
        "simulation": "Weapon",
        "nameSound": "",
        "count": 0,
        "multiplier": 1,
        "burst": 1,
        "magazineReloadSwitchPhase": 1,
        "sound": ["",1,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": ["sound",1],
        "soundLoop": ["sound",1],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "soundBurst": 1,
        "zeroingSound": ["",1,1],
        "reloadSound": ["",1,1],
        "emptySound": ["",1,1],
        "soundBullet": ["emptySound",1],
        "ballisticsComputer": 0,
        "irDistance": 0,
        "irDotIntensity": 0.001,
        "aiDispersionCoefX": 1,
        "lockAcquire": 1,
        "enableAttack": 1,
        "recoilProne": "",
        "maxRecoilSway": 0.008,
        "swayDecaySpeed": 2,
        "model": "",
        "modelSpecial": "",
        "modelMagazine": "",
        "irLaserPos": "laser pos",
        "irLaserEnd": "laser dir",
        "selectionFireAnim": "zasleh",
        "fireSpreadAngle": 3,
        "useModelOptics": 1,
        "opticsID": 0,
        "opticsPPEffects": [],
        "opticsFlare": 1,
        "forceOptics": 0,
        "useAsBinocular": 0,
        "opticsDisablePeripherialVision": 0.67,
        "distanceZoomMin": 400,
        "distanceZoomMax": 400,
        "primary": 10,
        "showSwitchAction": 0,
        "showEmpty": 1,
        "autoFire": 0,
        "showToPlayer": 1,
        "canShootInWater": 0,
        "aiRateOfFire": 5,
        "aiRateOfFireDistance": 500,
        "aiRateOfFireDispersion": 0,
        "fireLightDuration": 0.05,
        "fireLightIntensity": 0.2,
        "fireLightDiffuse": [0.937,0.631,0.259],
        "fireLightAmbient": [0,0,0],
        # Class: CfgWeapons\Default\Eventhandlers,
        "Eventhandlers": {
        },
        "backgroundReload": 0,
        "muzzles": ["this"],
        "useAction": 0,
        "useActionTitle": "",
        "canDrop": 1,
        "weaponLockDelay": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "weight": 0,
        "handAnim": [],
        "lockingTargetSound": ["",0.000316228,2],
        "lockedTargetSound": ["",0.000316228,6],
        "detectRange": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "fireAnims": [],
        # Class: CfgWeapons\Default\Library,
        "Library": {
            "libTextDesc": ""
        },
        "descriptionShort": "",
        # Class: CfgWeapons\Default\GunFire,
        "GunFire": {
            "access": 0,
            "cloudletDuration": 0.2,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletAlpha": 1,
            "cloudletGrowUp": 0.2,
            "cloudletFadeIn": 0.01,
            "cloudletFadeOut": 0.5,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "cloudletShape": "cloudletFire",
            "cloudletColor": [1,1,1,0],
            "cloudletDensityCoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourceSize": 0.5,
            "timeToLive": 0,
            "initT": 4500,
            "deltaT": -3000,
            # Class: CfgWeapons\Default\GunFire\Table,
            "Table": {
                # Class: CfgWeapons\Default\GunFire\Table\T0
                "T0": {
                    "maxT": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T1,
                "T1": {
                    "maxT": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T2,
                "T2": {
                    "maxT": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T3,
                "T3": {
                    "maxT": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T4,
                "T4": {
                    "maxT": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T5,
                "T5": {
                    "maxT": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T6,
                "T6": {
                    "maxT": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T7,
                "T7": {
                    "maxT": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T8,
                "T8": {
                    "maxT": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T9,
                "T9": {
                    "maxT": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T10,
                "T10": {
                    "maxT": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T11,
                "T11": {
                    "maxT": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T12,
                "T12": {
                    "maxT": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T13,
                "T13": {
                    "maxT": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T14,
                "T14": {
                    "maxT": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T15,
                "T15": {
                    "maxT": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T16,
                "T16": {
                    "maxT": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T17,
                "T17": {
                    "maxT": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T18,
                "T18": {
                    "maxT": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T19,
                "T19": {
                    "maxT": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T20,
                "T20": {
                    "maxT": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T21,
                "T21": {
                    "maxT": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T22,
                "T22": {
                    "maxT": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        # Class: CfgWeapons\Default\GunClouds,
        "GunClouds": {
            "access": 0,
            "cloudletGrowUp": 0.05,
            "cloudletFadeIn": 0,
            "cloudletFadeOut": 0.1,
            "cloudletDuration": 0.05,
            "cloudletAlpha": 0.3,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "interval": -0.02,
            "size": 0.3,
            "sourceSize": 0.02,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletShape": "cloudletClouds",
            "cloudletColor": [1,1,1,0],
            "timeToLive": 0,
            "initT": 0,
            "deltaT": 0,
            # Class: CfgWeapons\Default\GunClouds\Table,
            "Table": {
                # Class: CfgWeapons\Default\GunClouds\Table\T0
                "T0": {
                    "maxT": 0,
                    "color": [1,1,1,0]
                }
            }
        },
        "inertia": 0.5,
        "aimTransitionSpeed": 1
    },
    "weaponInfoType": "RscWeaponZeroing",
    "deployedPivot": "bipod",
    "htMin": 1,
    "htMax": 600,
    "afMax": 0,
    "mfMax": 0,
    "mFact": 1,
    "tBody": 100,
    "autoFire": 1,
    "soundContinuous": 0,
    "optics": 0,
    "cursoraim": "CursorAim",
    "value": 4,
    "nameSound": "rifle",
    "reloadTime": 0.15,
    "modelOptics": "-",
    "sound": [],
    "opticsFlare": 0,
    "autoReload": 0,
    "maxLeadSpeed": 23,
    "canLock": 0,
    "flash": "gunfire",
    "flashSize": 0.5,
    "dispersion": 0.00029,
    "recoilProne": "assaultRifleBase",
    "ffMagnitude": 0.5,
    "ffFrequency": 11,
    "ffCount": 3,
    "weaponPoolAvailable": 1,
    "zeroingSound": ["A3|Sounds_F|arsenal|sfx|shared|zeroing_knob_tick_metal",0.316228,1,5],
    "type": 1,
    "dexterity": 1.7,
    "aiRateOfFire": 0.5,
    "aiRateOfFireDistance": 500,
    "access": 3,
    "uiPicture": "",
    "ammo": "",
    "cursorSize": 1,
    "showAimCursorInternal": 1,
    "cursorAimOn": "",
    "laser": 0,
    "hiddenUnderwaterSelections": [],
    "shownUnderwaterSelections": [],
    "hiddenUnderwaterSelectionsTextures": [],
    "simulation": "Weapon",
    "count": 0,
    "multiplier": 1,
    "magazineReloadTime": 0,
    "magazineReloadSwitchPhase": 1,
    "soundBegin": ["sound",1],
    "soundBeginWater": ["sound",1],
    "soundClosure": ["sound",1],
    "soundEnd": ["sound",1],
    "soundLoop": ["sound",1],
    "weaponSoundEffect": "",
    "soundBurst": 1,
    "reloadSound": ["",1,1],
    "emptySound": ["",1,1],
    "ballisticsComputer": 0,
    "irDistance": 0,
    "irDotIntensity": 0.001,
    "lockAcquire": 1,
    "enableAttack": 1,
    "modelSpecial": "",
    "modelMagazine": "",
    "muzzlePos": "usti hlavne",
    "muzzleEnd": "konec hlavne",
    "irLaserPos": "laser pos",
    "irLaserEnd": "laser dir",
    "cartridgePos": "nabojnicestart",
    "cartridgeVel": "nabojniceend",
    "memoryPointCamera": "eye",
    "fireSpreadAngle": 3,
    "useModelOptics": 1,
    "opticsID": 0,
    "opticsPPEffects": [],
    "forceOptics": 0,
    "useAsBinocular": 0,
    "opticsDisablePeripherialVision": 0.67,
    "primary": 10,
    "showSwitchAction": 0,
    "showEmpty": 1,
    "showToPlayer": 1,
    "canShootInWater": 0,
    "aiRateOfFireDispersion": 0,
    "fireLightDuration": 0.05,
    "fireLightIntensity": 0.2,
    "fireLightDiffuse": [0.937,0.631,0.259],
    "fireLightAmbient": [0,0,0],
    # Class: CfgWeapons\Default\Eventhandlers,
    "Eventhandlers": {
    },
    "backgroundReload": 0,
    "muzzles": ["this"],
    "useAction": 0,
    "useActionTitle": "",
    "canDrop": 1,
    "weaponLockDelay": 0,
    "weaponLockSystem": 0,
    "cmImmunity": 1,
    "weight": 0,
    "minRange": 1,
    "minRangeProbab": 0.3,
    "midRange": 150,
    "midRangeProbab": 0.58,
    "maxRange": 500,
    "maxRangeProbab": 0.04,
    "lockingTargetSound": ["",0.000316228,2],
    "lockedTargetSound": ["",0.000316228,6],
    "detectRange": 0,
    "artilleryDispersion": 1,
    "artilleryCharge": 1,
    "fireAnims": [],
    # Class: CfgWeapons\Default\GunFire,
    "GunFire": {
        "access": 0,
        "cloudletDuration": 0.2,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 0.2,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 0.5,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletFire",
        "cloudletColor": [1,1,1,0],
        "cloudletDensityCoef": -1,
        "interval": -0.01,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 4500,
        "deltaT": -3000,
        # Class: CfgWeapons\Default\GunFire\Table,
        "Table": {
            # Class: CfgWeapons\Default\GunFire\Table\T0
            "T0": {
                "maxT": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T1,
            "T1": {
                "maxT": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T2,
            "T2": {
                "maxT": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T3,
            "T3": {
                "maxT": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T4,
            "T4": {
                "maxT": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T5,
            "T5": {
                "maxT": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T6,
            "T6": {
                "maxT": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T7,
            "T7": {
                "maxT": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T8,
            "T8": {
                "maxT": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T9,
            "T9": {
                "maxT": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T10,
            "T10": {
                "maxT": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T11,
            "T11": {
                "maxT": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T12,
            "T12": {
                "maxT": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T13,
            "T13": {
                "maxT": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T14,
            "T14": {
                "maxT": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T15,
            "T15": {
                "maxT": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T16,
            "T16": {
                "maxT": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T17,
            "T17": {
                "maxT": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T18,
            "T18": {
                "maxT": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T19,
            "T19": {
                "maxT": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T20,
            "T20": {
                "maxT": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T21,
            "T21": {
                "maxT": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T22,
            "T22": {
                "maxT": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgWeapons\Default\GunClouds,
    "GunClouds": {
        "access": 0,
        "cloudletGrowUp": 0.05,
        "cloudletFadeIn": 0,
        "cloudletFadeOut": 0.1,
        "cloudletDuration": 0.05,
        "cloudletAlpha": 0.3,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "interval": -0.02,
        "size": 0.3,
        "sourceSize": 0.02,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletShape": "cloudletClouds",
        "cloudletColor": [1,1,1,0],
        "timeToLive": 0,
        "initT": 0,
        "deltaT": 0,
        # Class: CfgWeapons\Default\GunClouds\Table,
        "Table": {
            # Class: CfgWeapons\Default\GunClouds\Table\T0
            "T0": {
                "maxT": 0,
                "color": [1,1,1,0]
            }
        }
    },
    "textureType": "default",
    "aimTransitionSpeed": 1,
}