rhs_mag_mgm140b_1 = {
    "displayname": "MGM-140B (M39A1)",
    "descriptionshort": "ATacMS Block IA, GPS/INS, ×69 M74 APAM",
    # Ammo: CfgMagazines|rhs_mag_mgm140b_1|ammo [Indent level: 1],
    "ammo": {
        "_dictAmmoName": "rhs_ammo_mgm140b_rocket",
        "triggerdistance": 250,
        "submunitionconetype": ["randomcenter",69],
        "model": "rhsusf|addons|rhsusf_heavyweapons|rockets|rhs_MGM140_rocket.p3d",
        "artillerylock": 1,
        # Ammo: CfgAmmo|R_230mm_HE|submunitionAmmo [Indent level: 1],
        "submunitionammo": {
            "_dictAmmoName": "R_230mm_fly",
            "artillerylock": 1,
            "model": "A3|Weapons_F|Ammo|Rocket_230mm_Fly_F",
            "hit": 1200,
            "indirecthit": 800,
            "indirecthitrange": 30,
            "warheadname": "HE",
            "cost": 1000,
            "audiblefire": 64,
            "dangerradiushit": 1250,
            "suppressionradiushit": 120,
            "deflecting": 0,
            "airfriction": 0,
            "muzzleeffect": "",
            "effectfly": "ArtilleryTrails",
            # Class: CfgAmmo|R_230mm_fly|CamShakeExplode [Indent level: 1],
            "camshakeexplode": {
                "power": 46,
                "duration": 3,
                "frequency": 20,
                "distance": 361.326
            },
            # Class: CfgAmmo|R_230mm_fly|CamShakeHit [Indent level: 1],
            "camshakehit": {
                "power": 230,
                "duration": 0.8,
                "frequency": 20,
                "distance": 1
            },
            # Class: CfgAmmo|R_230mm_fly|CamShakeFire [Indent level: 1],
            "camshakefire": {
                "power": 3.89432,
                "duration": 3,
                "frequency": 20,
                "distance": 121.326
            },
            # Class: CfgAmmo|R_230mm_fly|CamShakePlayerFire [Indent level: 1],
            "camshakeplayerfire": {
                "power": 5,
                "duration": 0.1,
                "frequency": 20,
                "distance": 1
            },
            "soundhit1": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_01",2.51189,1,1900],
            "soundhit2": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_02",2.51189,1,1900],
            "soundhit3": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_03",2.51189,1,1900],
            "multisoundhit": ["soundHit1",0.34,"soundHit2",0.33,"soundHit3",0.33],
            "soundsetexplosion": ["RocketsHeavy_Exp_SoundSet","RocketsHeavy_Tail_SoundSet","Explosion_Debris_SoundSet"],
            "supersoniccracknear": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_close",0.316228,1,50],
            "supersoniccrackfar": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_50meters",0.223872,1,150],
            "cratereffects": "HEShellCrater",
            "craterwatereffects": "ImpactEffectsWaterHE",
            "explosioneffects": "HEShellExplosion",
            "visiblefire": 64,
            "timetolive": 360,
            "caliber": 34,
            "deflectiondirdistribution": 0.39,
            "penetrationdirdistribution": 0.26,
            "whistleonfire": 2,
            "aiammousageflags": "64 + 128 + 256",
            # Class: CfgAmmo|ShellBase|HitEffects [Indent level: 1],
            "hiteffects": {
                "hitwater": "ImpactEffectsWaterRocket"
            },
            "soundfakefall0": ["a3|Sounds_F|weapons|falling_bomb|fall_01",3.16228,1,1000],
            "soundfakefall1": ["a3|Sounds_F|weapons|falling_bomb|fall_02",3.16228,1,1000],
            "soundfakefall2": ["a3|Sounds_F|weapons|falling_bomb|fall_03",3.16228,1,1000],
            "soundfakefall3": ["a3|Sounds_F|weapons|falling_bomb|fall_04",3.16228,1,1000],
            "soundfakefall": ["soundFakeFall0",0.25,"soundFakeFall1",0.25,"soundFakeFall2",0.25,"soundFakeFall3",0.25],
            "soundsetsoniccrack": ["bulletSonicCrack_SoundSet","bulletSonicCrackTail_SoundSet"],
            "simulation": "shotShell",
            "simulationstep": 0.05,
            "soundhit": ["",316.228,1],
            "soundfly": ["",0.0316228,4],
            "visiblefiretime": 10,
            "access": 3,
            "underwaterhitrangecoef": 1,
            "typicalspeed": 900,
            "explosionforcecoef": 1,
            "iscrateroriented": 0,
            "proxyshape": "",
            "cratershape": "",
            "weapontype": "Default",
            "animated": 0,
            "shadow": 0,
            "maxspeed": 0,
            "cartridge": "",
            "tracercolor": [0.7,0.7,0.5,0.04],
            "tracercolorr": [0.7,0.7,0.5,0.04],
            "soundengine": ["",1,1],
            "soundfall": ["",1,1],
            "hitgroundsoft": ["soundHit",1],
            "hitgroundhard": ["soundHit",1],
            "hitman": ["soundHit",1],
            "hitarmor": ["soundHit",1],
            "hitiron": ["soundHit",1],
            "hitbuilding": ["soundHit",1],
            "hitfoliage": ["soundHit",1],
            "hitwood": ["soundHit",1],
            "hitglass": ["soundHit",1],
            "hitglassarmored": ["soundHit",1],
            "hitconcrete": ["soundHit",1],
            "hitrubber": ["soundHit",1],
            "hitplastic": ["soundHit",1],
            "hitdefault": ["soundHit",1],
            "hitmetal": ["soundHit",1],
            "hitmetalplate": ["soundHit",1],
            "hittyre": ["soundHit",1],
            "hitwater": ["soundHit",1],
            "soundimpact": ["",1,1],
            "impactgroundsoft": ["soundImpact",1],
            "impactgroundhard": ["soundImpact",1],
            "impactman": ["soundImpact",1],
            "impactiron": ["soundImpact",1],
            "impactarmor": ["soundImpact",1],
            "impactbuilding": ["soundImpact",1],
            "impactfoliage": ["soundImpact",1],
            "impactwood": ["soundImpact",1],
            "impactglass": ["soundImpact",1],
            "impactglassarmored": ["soundImpact",1],
            "impactconcrete": ["soundImpact",1],
            "impactrubber": ["soundImpact",1],
            "impactplastic": ["soundImpact",1],
            "impactdefault": ["soundImpact",1],
            "impactmetal": ["soundImpact",1],
            "impactmetalplate": ["soundImpact",1],
            "impacttyre": ["soundImpact",1],
            "impactwater": ["soundImpact",1],
            "grenadefiresound": [],
            "grenadeburningsound": [],
            "deflectionslowdown": 0.8,
            "explosive": 1,
            "effectsmissile": "ExplosionEffects",
            "effectsmissileinit": "",
            "effectssmoke": "SmokeShellWhite",
            "effectsfire": "CannonFire",
            "effectflare": "FlareShell",
            "minejumpeffects": "",
            "watereffectoffset": 0.45,
            "directionalexplosion": 0,
            "explosionangle": 60,
            "explosiondir": "explosionDir",
            "explosionpos": "explosionPos",
            "explosioneffectsdir": "explosionDir",
            "minimumsafezone": 0.1,
            "soundtrigger": [],
            "soundactivation": [],
            "sounddeactivation": [],
            "explosionsoundeffect": "",
            "mintimetolive": 0,
            "irlock": 0,
            "airlock": 0,
            "laserlock": 0,
            "nvlock": 0,
            "hitonwater": 0,
            "lockseekradius": 100,
            "manualcontrol": 0,
            "maxcontrolrange": 350,
            "maneuvrability": 1,
            "tracklead": 1,
            "trackoversteer": 1,
            "missilelockcone": 0,
            "weaponlocksystem": 0,
            "cmimmunity": 1,
            "locktype": 0,
            "maverickweaponindexoffset": 0,
            "sideairfriction": 1,
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "autoseektarget": 0,
            "shootdistraction": -1,
            "explosiontime": 0,
            "fusedistance": 0,
            "inittime": 0,
            "thrusttime": 1.5,
            "thrust": 210,
            "icon": "",
            "submunitionammo": "",
            "explosiontype": "explosive",
            "minetrigger": "RangeTrigger",
            "mineboundingtime": 3,
            "mineboundingdist": 3,
            "mineinconspicuousness": 10,
            "minefloating": -1,
            "minedivespeed": 1,
            "mineplacedist": 0.5,
            "suppressionradiusbulletclose": -1,
            "dangerradiusbulletclose": -1,
            "whistledist": 0,
            # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
            "nvgmarkers": {
            },
            "mindamageforcamshakehit": 0.55,
            # Class: CfgAmmo|Default|EventHandlers [Indent level: 1],
            "eventhandlers": {
            },
        },
        "eventhandlers": "R_230mm_fly",
        "cost": 1000,
        "airfriction": 0,
        "muzzleeffect": "",
        "effectfly": "Missile0",
        "hit": 300,
        # Class: CfgAmmo|R_230mm_HE|CamShakeExplode [Indent level: 1],
        "camshakeexplode": {
            "power": 46,
            "duration": 3,
            "frequency": 20,
            "distance": 361.326
        },
        # Class: CfgAmmo|R_230mm_HE|CamShakeHit [Indent level: 1],
        "camshakehit": {
            "power": 230,
            "duration": 0.8,
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo|R_230mm_HE|CamShakeFire [Indent level: 1],
        "camshakefire": {
            "power": 3.89432,
            "duration": 3,
            "frequency": 20,
            "distance": 121.326
        },
        # Class: CfgAmmo|R_230mm_HE|CamShakePlayerFire [Indent level: 1],
        "camshakeplayerfire": {
            "power": 5,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "soundfly": ["A3|Sounds_F|weapons|Rockets|rocket_fly_1",0.562341,1.9,500],
        "soundsetexplosion": ["RocketsHeavy_Exp_SoundSet","RocketsHeavy_Tail_SoundSet","Explosion_Debris_SoundSet"],
        "simulation": "shotSubmunitions",
        "simulationstep": 0.05,
        "timetolive": 180,
        "soundhit": ["",316.228,1],
        "hitonwater": 1,
        "indirecthitrange": 8,
        "visiblefire": 16,
        "audiblefire": 16,
        "visiblefiretime": 10,
        "deflecting": 5,
        "access": 3,
        "indirecthit": 0,
        "underwaterhitrangecoef": 1,
        "typicalspeed": 900,
        "explosionforcecoef": 1,
        "iscrateroriented": 0,
        "proxyshape": "",
        "cratershape": "",
        "weapontype": "Default",
        "animated": 0,
        "shadow": 0,
        "maxspeed": 0,
        "cartridge": "",
        "tracercolor": [0.7,0.7,0.5,0.04],
        "tracercolorr": [0.7,0.7,0.5,0.04],
        "soundengine": ["",1,1],
        "supersoniccracknear": ["",1,1],
        "supersoniccrackfar": ["",1,1],
        "soundfall": ["",1,1],
        "soundfakefall": ["soundFall",1],
        "hitgroundsoft": ["soundHit",1],
        "hitgroundhard": ["soundHit",1],
        "hitman": ["soundHit",1],
        "hitarmor": ["soundHit",1],
        "hitiron": ["soundHit",1],
        "hitbuilding": ["soundHit",1],
        "hitfoliage": ["soundHit",1],
        "hitwood": ["soundHit",1],
        "hitglass": ["soundHit",1],
        "hitglassarmored": ["soundHit",1],
        "hitconcrete": ["soundHit",1],
        "hitrubber": ["soundHit",1],
        "hitplastic": ["soundHit",1],
        "hitdefault": ["soundHit",1],
        "hitmetal": ["soundHit",1],
        "hitmetalplate": ["soundHit",1],
        "hittyre": ["soundHit",1],
        "hitwater": ["soundHit",1],
        "soundimpact": ["",1,1],
        "impactgroundsoft": ["soundImpact",1],
        "impactgroundhard": ["soundImpact",1],
        "impactman": ["soundImpact",1],
        "impactiron": ["soundImpact",1],
        "impactarmor": ["soundImpact",1],
        "impactbuilding": ["soundImpact",1],
        "impactfoliage": ["soundImpact",1],
        "impactwood": ["soundImpact",1],
        "impactglass": ["soundImpact",1],
        "impactglassarmored": ["soundImpact",1],
        "impactconcrete": ["soundImpact",1],
        "impactrubber": ["soundImpact",1],
        "impactplastic": ["soundImpact",1],
        "impactdefault": ["soundImpact",1],
        "impactmetal": ["soundImpact",1],
        "impactmetalplate": ["soundImpact",1],
        "impacttyre": ["soundImpact",1],
        "impactwater": ["soundImpact",1],
        "grenadefiresound": [],
        "grenadeburningsound": [],
        "deflectionslowdown": 0.8,
        "explosive": 1,
        "explosioneffects": "ExplosionEffects",
        "cratereffects": "ImpactEffectsMedium",
        "craterwatereffects": "ImpactEffectsWater",
        "effectsmissile": "ExplosionEffects",
        "effectsmissileinit": "",
        "effectssmoke": "SmokeShellWhite",
        "effectsfire": "CannonFire",
        "effectflare": "FlareShell",
        "minejumpeffects": "",
        "watereffectoffset": 0.45,
        "directionalexplosion": 0,
        "explosionangle": 60,
        "explosiondir": "explosionDir",
        "explosionpos": "explosionPos",
        "explosioneffectsdir": "explosionDir",
        "minimumsafezone": 0.1,
        "soundtrigger": [],
        "soundactivation": [],
        "sounddeactivation": [],
        "explosionsoundeffect": "",
        "mintimetolive": 0,
        "irlock": 0,
        "airlock": 0,
        "laserlock": 0,
        "nvlock": 0,
        "lockseekradius": 100,
        "manualcontrol": 0,
        "maxcontrolrange": 350,
        "maneuvrability": 1,
        "tracklead": 1,
        "trackoversteer": 1,
        "missilelockcone": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "locktype": 0,
        "maverickweaponindexoffset": 0,
        "sideairfriction": 1,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "autoseektarget": 0,
        "shootdistraction": -1,
        "explosiontime": 0,
        "fusedistance": 0,
        "inittime": 0,
        "thrusttime": 1.5,
        "thrust": 210,
        "icon": "",
        "explosiontype": "explosive",
        "minetrigger": "RangeTrigger",
        "mineboundingtime": 3,
        "mineboundingdist": 3,
        "mineinconspicuousness": 10,
        "minefloating": -1,
        "minedivespeed": 1,
        "mineplacedist": 0.5,
        # Class: CfgAmmo|Default|HitEffects [Indent level: 1],
        "hiteffects": {
            "vehicle": "ImpactMetal",
            "object": "ImpactConcrete"
        },
        "suppressionradiusbulletclose": -1,
        "suppressionradiushit": -1,
        "dangerradiusbulletclose": -1,
        "dangerradiushit": -1,
        "caliber": 1,
        "whistledist": 0,
        "whistleonfire": 0,
        # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
        "nvgmarkers": {
        },
        "mindamageforcamshakehit": 0.55,
        # Class: CfgAmmo|Default|EventHandlers [Indent level: 1],
        "eventhandlers": {
        },
    },
    "eventhandlers": "rhs_ammo_mgm140b_rocket",
    "pylonweapon": "rhs_weap_atacms_guided",
    "displaynameshort": "Cluster",
    "count": 1,
    "model": "rhsusf|addons|rhsusf_himars|M142_ATACMS_Pod",
    "hardpoints": ["RHS_HP_ATACMS"],
    "initspeed": 850,
    "scope": 2,
    "namesound": "rockets",
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadaction": "",
    "maxleadspeed": 100,
    "weaponpoolavailable": 0,
    "value": 1,
    "picture": "",
    "modelspecial": "",
    "useaction": 0,
    "useactiontitle": "",
    "selectionfireanim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    # Class: CfgMagazines|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0,
}