rhs_mag_l159_fuelpod_grey = {
    "displayname": "Fuel Pod (Grey)",
    "displaynameshort": "Fuel Pod (Grey)",
    "model": "rhsgref|addons|rhsgref_airweapons|rhs_pylon_L159_fuelpod_grey",
    # Ammo: CfgMagazines|rhs_mag_l159_fuelpod|ammo [Indent level: 1],
    "ammo": {
        "_dictAmmoName": "rhs_ammo_l159_fuelpod_proxy",
        "model": "rhsafrf|addons|rhs_heavyweapons|atgm|rhs_atgm_base",
        "flightprofiles": ["Direct"],
        "hit": 240,
        "indirecthit": 20,
        "indirecthitrange": 4.2,
        "cost": 800,
        "maxspeed": 115,
        "canlock": 0,
        "locktype": 0,
        "irlock": 1,
        "weaponlocksystem": 1,
        "trackoversteer": 0.3,
        "tracklead": 0.85,
        "manualcontrol": 1,
        "maxcontrolrange": 3000,
        "inittime": 0,
        "missilemanualcontrolcone": 50,
        "airfriction": -2e-005,
        "sideairfriction": 0.14,
        "thrusttime": 2.5,
        "thrust": 100,
        "maneuvrability": 4,
        "typicalspeed": 115,
        "fusedistance": 100,
        "effectsmissileinit": "RocketBackEffectsNLAW",
        "effectsmissile": "RHS_missile2",
        "timetolive": 26,
        "texturetype": "semi",
        "soundfly": ["A3|Sounds_F|weapons|Rockets|rocket_fly_2",1,1,800],
        # Class: CfgAmmo|rhs_ammo_atgmBase_base|Components [Indent level: 1],
        "components": {
            # Class: CfgAmmo|rhs_ammo_atgmBase_base|Components|SensorsManagerComponent [Indent level: 2]
            "sensorsmanagercomponent": {
                # Class: CfgAmmo|rhs_ammo_atgmBase_base|Components|SensorsManagerComponent|Components [Indent level: 3]
                "components": {
                    # Class: CfgAmmo|rhs_ammo_atgmBase_base|Components|SensorsManagerComponent|Components|VisualSensorComponent [Indent level: 4]
                    "visualsensorcomponent": {
                        # Class: CfgAmmo|rhs_ammo_atgmBase_base|Components|SensorsManagerComponent|Components|VisualSensorComponent|AirTarget [Indent level: 5]
                        "airtarget": {
                            "minrange": 500,
                            "maxrange": 5000,
                            "objectdistancelimitcoef": -1,
                            "viewdistancelimitcoef": 1
                        },
                        # Class: CfgAmmo|rhs_ammo_atgmBase_base|Components|SensorsManagerComponent|Components|VisualSensorComponent|GroundTarget [Indent level: 5],
                        "groundtarget": {
                            "minrange": 500,
                            "maxrange": 5000,
                            "objectdistancelimitcoef": 1,
                            "viewdistancelimitcoef": 1
                        },
                        "maxtrackablespeed": 35,
                        "nightrangecoef": 0.8,
                        "anglerangehorizontal": 5,
                        "anglerangevertical": 5,
                        "componenttype": "VisualSensorComponent",
                        "maxfogseethrough": 0.94,
                        "color": [1,1,0.5,0.8],
                        "typerecognitiondistance": 2000,
                        "allowsmarking": 1,
                        "groundnoisedistancecoef": -1,
                        "maxgroundnoisedistance": -1,
                        "minspeedthreshold": 0,
                        "maxspeedthreshold": 0,
                        "animdirection": "",
                        "aimdown": 0,
                        "mintrackablespeed": -1e+010,
                        "mintrackableatl": -1e+010,
                        "maxtrackableatl": 1e+010
                    }
                }
            }
        },
        "explosive": 1,
        "warheadname": "HE",
        # Ammo: CfgAmmo|M_Titan_AT|submunitionAmmo [Indent level: 1],
        "submunitionammo": {
            "_dictAmmoName": "ammo_Penetrator_Titan_AT",
            "caliber": 60,
            "hit": 585,
            "model": "A3|weapons_f|empty",
            "warheadname": "HEAT",
            "indirecthit": 0,
            "indirecthitrange": 0,
            "explosive": 0,
            "typicalspeed": 1000,
            "timetolive": 0.2,
            "simulationstep": 0.05,
            "airfriction": -0.28,
            "deflecting": 0,
            "deflectiondirdistribution": 0,
            "penetrationdirdistribution": 0,
            "aiammousageflags": "128 + 512",
            "dangerradiushit": 60,
            "suppressionradiushit": 30,
            "cratereffects": "ExploAmmoCrater",
            "explosioneffects": "ExploAmmoExplosion",
            # Class: CfgAmmo|ammo_Penetrator_Base|HitEffects [Indent level: 1],
            "hiteffects": {
                "hit_foliage_green": "ImpactLeavesGreen",
                "hit_foliage_dead": "ImpactLeavesDead",
                "hit_foliage_green_big": "ImpactLeavesGreenBig",
                "hit_foliage_palm": "ImpactLeavesPalm",
                "hit_foliage_pine": "ImpactLeavesPine",
                "hitfoliage": "ImpactLeaves",
                "hitglass": "ImpactMetalSabotSmall",
                "hitglassarmored": "ImpactMetalSabotSmall",
                "hitwood": "ImpactMetalSabotSmall",
                "hithay": "ImpactMetalSabotSmall",
                "hitmetal": "ImpactMetalSabotSmall",
                "hitmetalplate": "ImpactMetalSabotSmall",
                "hitbuilding": "ImpactMetalSabotSmall",
                "hitplastic": "ImpactMetalSabotSmall",
                "hitrubber": "ImpactMetalSabotSmall",
                "hittyre": "ImpactMetalSabotSmall",
                "hitconcrete": "ImpactMetalSabotSmall",
                "hitman": "ImpactMetalSabotSmall",
                "hitgroundsoft": "ImpactMetalSabotSmall",
                "hitgroundred": "ImpactMetalSabotSmall",
                "hitgroundhard": "ImpactMetalSabotSmall",
                "hitwater": "ImpactEffectsWater",
                "default_mat": "ImpactMetalSabotSmall"
            },
            "whistleonfire": 1,
            "whistledist": 14,
            "supersoniccracknear": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_close",0.316228,1,50],
            "supersoniccrackfar": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_50meters",0.223872,1,150],
            "craterwatereffects": "ImpactEffectsWaterHE",
            "visiblefire": 64,
            "audiblefire": 250,
            "muzzleeffect": "",
            "soundfakefall0": ["a3|Sounds_F|weapons|falling_bomb|fall_01",3.16228,1,1000],
            "soundfakefall1": ["a3|Sounds_F|weapons|falling_bomb|fall_02",3.16228,1,1000],
            "soundfakefall2": ["a3|Sounds_F|weapons|falling_bomb|fall_03",3.16228,1,1000],
            "soundfakefall3": ["a3|Sounds_F|weapons|falling_bomb|fall_04",3.16228,1,1000],
            "soundfakefall": ["soundFakeFall0",0.25,"soundFakeFall1",0.25,"soundFakeFall2",0.25,"soundFakeFall3",0.25],
            "soundsetsoniccrack": ["bulletSonicCrack_SoundSet","bulletSonicCrackTail_SoundSet"],
            "simulation": "shotShell",
            "cost": 1000,
            "soundhit": ["",316.228,1],
            "soundfly": ["",0.0316228,4],
            "visiblefiretime": 10,
            "access": 3,
            "underwaterhitrangecoef": 1,
            "explosionforcecoef": 1,
            "iscrateroriented": 0,
            "proxyshape": "",
            "cratershape": "",
            "weapontype": "Default",
            "animated": 0,
            "shadow": 0,
            "maxspeed": 0,
            "cartridge": "",
            "tracercolor": [0.7,0.7,0.5,0.04],
            "tracercolorr": [0.7,0.7,0.5,0.04],
            "soundengine": ["",1,1],
            "soundfall": ["",1,1],
            "hitgroundsoft": ["soundHit",1],
            "hitgroundhard": ["soundHit",1],
            "hitman": ["soundHit",1],
            "hitarmor": ["soundHit",1],
            "hitiron": ["soundHit",1],
            "hitbuilding": ["soundHit",1],
            "hitfoliage": ["soundHit",1],
            "hitwood": ["soundHit",1],
            "hitglass": ["soundHit",1],
            "hitglassarmored": ["soundHit",1],
            "hitconcrete": ["soundHit",1],
            "hitrubber": ["soundHit",1],
            "hitplastic": ["soundHit",1],
            "hitdefault": ["soundHit",1],
            "hitmetal": ["soundHit",1],
            "hitmetalplate": ["soundHit",1],
            "hittyre": ["soundHit",1],
            "hitwater": ["soundHit",1],
            "soundimpact": ["",1,1],
            "impactgroundsoft": ["soundImpact",1],
            "impactgroundhard": ["soundImpact",1],
            "impactman": ["soundImpact",1],
            "impactiron": ["soundImpact",1],
            "impactarmor": ["soundImpact",1],
            "impactbuilding": ["soundImpact",1],
            "impactfoliage": ["soundImpact",1],
            "impactwood": ["soundImpact",1],
            "impactglass": ["soundImpact",1],
            "impactglassarmored": ["soundImpact",1],
            "impactconcrete": ["soundImpact",1],
            "impactrubber": ["soundImpact",1],
            "impactplastic": ["soundImpact",1],
            "impactdefault": ["soundImpact",1],
            "impactmetal": ["soundImpact",1],
            "impactmetalplate": ["soundImpact",1],
            "impacttyre": ["soundImpact",1],
            "impactwater": ["soundImpact",1],
            "grenadefiresound": [],
            "grenadeburningsound": [],
            "deflectionslowdown": 0.8,
            "effectsmissile": "ExplosionEffects",
            "effectsmissileinit": "",
            "effectssmoke": "SmokeShellWhite",
            "effectsfire": "CannonFire",
            "effectflare": "FlareShell",
            "effectfly": "",
            "minejumpeffects": "",
            "watereffectoffset": 0.45,
            "directionalexplosion": 0,
            "explosionangle": 60,
            "explosiondir": "explosionDir",
            "explosionpos": "explosionPos",
            "explosioneffectsdir": "explosionDir",
            "minimumsafezone": 0.1,
            "soundtrigger": [],
            "soundactivation": [],
            "sounddeactivation": [],
            "explosionsoundeffect": "",
            "mintimetolive": 0,
            "irlock": 0,
            "airlock": 0,
            "laserlock": 0,
            "nvlock": 0,
            "artillerylock": 0,
            "hitonwater": 0,
            "lockseekradius": 100,
            "manualcontrol": 0,
            "maxcontrolrange": 350,
            "maneuvrability": 1,
            "tracklead": 1,
            "trackoversteer": 1,
            "missilelockcone": 0,
            "weaponlocksystem": 0,
            "cmimmunity": 1,
            "locktype": 0,
            "maverickweaponindexoffset": 0,
            "sideairfriction": 1,
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "autoseektarget": 0,
            "shootdistraction": -1,
            "explosiontime": 0,
            "fusedistance": 0,
            "inittime": 0,
            "thrusttime": 1.5,
            "thrust": 210,
            "icon": "",
            "submunitionammo": "",
            "explosiontype": "explosive",
            "minetrigger": "RangeTrigger",
            "mineboundingtime": 3,
            "mineboundingdist": 3,
            "mineinconspicuousness": 10,
            "minefloating": -1,
            "minedivespeed": 1,
            "mineplacedist": 0.5,
            "suppressionradiusbulletclose": -1,
            "dangerradiusbulletclose": -1,
            # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
            "nvgmarkers": {
            },
            "mindamageforcamshakehit": 0.55,
            # Class: CfgAmmo|Default|EventHandlers [Indent level: 1],
            "eventhandlers": {
            },
        },
        "eventhandlers": "ammo_Penetrator_Titan_AT",
        "submunitiondirectiontype": "SubmunitionModelDirection",
        "submunitioninitspeed": 1000,
        "submunitionparentspeedcoef": 0,
        "submunitioninitialoffset": [0,0,-0.2],
        "triggeronimpact": 1,
        "deleteparentwhentriggered": 0,
        "aiammousageflags": "128 + 512",
        "explosionsoundeffect": "DefaultExplosion",
        "muzzleeffect": "",
        "simulationstep": 0.002,
        "whistledist": 4,
        "airlock": 1,
        "missilelockcone": 4.5,
        "missilekeeplockedcone": 160,
        "missilelockmaxdistance": 2000,
        "missilelockmindistance": 50,
        "missilelockmaxspeed": 35,
        "cmimmunity": 0.4,
        # Class: CfgAmmo|M_Titan_AT|Direct [Indent level: 1],
        "direct": {
        },
        # Class: CfgAmmo|M_Titan_AT|TopDown [Indent level: 1],
        "topdown": {
            "ascendheight": 150,
            "descenddistance": 180,
            "mindistance": 180,
            "ascendangle": 30
        },
        # Class: CfgAmmo|M_Titan_AT|CamShakeExplode [Indent level: 1],
        "camshakeexplode": {
            "power": 11,
            "duration": 1.4,
            "frequency": 20,
            "distance": 91.3296
        },
        # Class: CfgAmmo|M_Titan_AT|CamShakeHit [Indent level: 1],
        "camshakehit": {
            "power": 110,
            "duration": 0.6,
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo|M_Titan_AT|CamShakeFire [Indent level: 1],
        "camshakefire": {
            "power": 2.78316,
            "duration": 1.6,
            "frequency": 20,
            "distance": 61.9677
        },
        # Class: CfgAmmo|M_Titan_AT|CamShakePlayerFire [Indent level: 1],
        "camshakeplayerfire": {
            "power": 3,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "soundsetexplosion": ["RocketsHeavy_Exp_SoundSet","RocketsHeavy_Tail_SoundSet","Explosion_Debris_SoundSet"],
        "soundhit1": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_01",2.51189,1,2000],
        "soundhit2": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_02",2.51189,1,2000],
        "soundhit3": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_03",2.51189,1,2000],
        "multisoundhit": ["soundHit1",0.34,"soundHit2",0.33,"soundHit3",0.33],
        "soundengine": ["",1,1,50],
        "supersoniccracknear": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_close",0.398107,1,20],
        "supersoniccrackfar": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_50meters",0.316228,1,50],
        "cratereffects": "ATMissileCrater",
        "explosioneffects": "ATMissileExplosion",
        "deflecting": 0,
        "dangerradiushit": -1,
        "suppressionradiushit": 30,
        # Class: CfgAmmo|MissileBase|HitEffects [Indent level: 1],
        "hiteffects": {
            "hitwater": "ImpactEffectsWaterRocket"
        },
        "maverickweaponindexoffset": 0,
        "htmin": 60,
        "htmax": 1800,
        "afmax": 200,
        "mfmax": 100,
        "mfact": 0,
        "tbody": 0,
        # Class: CfgAmmo|MissileBase|EventHandlers [Indent level: 1],
        "eventhandlers": {
            # Class: CfgAmmo|MissileBase|EventHandlers|RHS_APS_FiredEH [Indent level: 2]
            "rhs_aps_firedeh": {
                "fired": "_this spawn rhs_fnc_aps_missileFired"
            }
        },
        "simulation": "shotMissile",
        "visiblefire": 32,
        "audiblefire": 32,
        "visiblefiretime": 20,
        "soundhit": ["",100,1],
        "access": 3,
        "underwaterhitrangecoef": 1,
        "explosionforcecoef": 1,
        "iscrateroriented": 0,
        "proxyshape": "",
        "cratershape": "",
        "weapontype": "Default",
        "animated": 0,
        "shadow": 0,
        "cartridge": "",
        "tracercolor": [0.7,0.7,0.5,0.04],
        "tracercolorr": [0.7,0.7,0.5,0.04],
        "soundfall": ["",1,1],
        "soundfakefall": ["soundFall",1],
        "hitgroundsoft": ["soundHit",1],
        "hitgroundhard": ["soundHit",1],
        "hitman": ["soundHit",1],
        "hitarmor": ["soundHit",1],
        "hitiron": ["soundHit",1],
        "hitbuilding": ["soundHit",1],
        "hitfoliage": ["soundHit",1],
        "hitwood": ["soundHit",1],
        "hitglass": ["soundHit",1],
        "hitglassarmored": ["soundHit",1],
        "hitconcrete": ["soundHit",1],
        "hitrubber": ["soundHit",1],
        "hitplastic": ["soundHit",1],
        "hitdefault": ["soundHit",1],
        "hitmetal": ["soundHit",1],
        "hitmetalplate": ["soundHit",1],
        "hittyre": ["soundHit",1],
        "hitwater": ["soundHit",1],
        "soundimpact": ["",1,1],
        "impactgroundsoft": ["soundImpact",1],
        "impactgroundhard": ["soundImpact",1],
        "impactman": ["soundImpact",1],
        "impactiron": ["soundImpact",1],
        "impactarmor": ["soundImpact",1],
        "impactbuilding": ["soundImpact",1],
        "impactfoliage": ["soundImpact",1],
        "impactwood": ["soundImpact",1],
        "impactglass": ["soundImpact",1],
        "impactglassarmored": ["soundImpact",1],
        "impactconcrete": ["soundImpact",1],
        "impactrubber": ["soundImpact",1],
        "impactplastic": ["soundImpact",1],
        "impactdefault": ["soundImpact",1],
        "impactmetal": ["soundImpact",1],
        "impactmetalplate": ["soundImpact",1],
        "impacttyre": ["soundImpact",1],
        "impactwater": ["soundImpact",1],
        "grenadefiresound": [],
        "grenadeburningsound": [],
        "deflectionslowdown": 0.8,
        "craterwatereffects": "ImpactEffectsWater",
        "effectssmoke": "SmokeShellWhite",
        "effectsfire": "CannonFire",
        "effectflare": "FlareShell",
        "effectfly": "",
        "minejumpeffects": "",
        "watereffectoffset": 0.45,
        "directionalexplosion": 0,
        "explosionangle": 60,
        "explosiondir": "explosionDir",
        "explosionpos": "explosionPos",
        "explosioneffectsdir": "explosionDir",
        "minimumsafezone": 0.1,
        "soundtrigger": [],
        "soundactivation": [],
        "sounddeactivation": [],
        "mintimetolive": 0,
        "laserlock": 0,
        "nvlock": 0,
        "artillerylock": 0,
        "hitonwater": 0,
        "lockseekradius": 100,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "autoseektarget": 0,
        "shootdistraction": -1,
        "explosiontime": 0,
        "icon": "",
        "explosiontype": "explosive",
        "minetrigger": "RangeTrigger",
        "mineboundingtime": 3,
        "mineboundingdist": 3,
        "mineinconspicuousness": 10,
        "minefloating": -1,
        "minedivespeed": 1,
        "mineplacedist": 0.5,
        "suppressionradiusbulletclose": -1,
        "dangerradiusbulletclose": -1,
        "caliber": 1,
        "whistleonfire": 0,
        # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
        "nvgmarkers": {
        },
        "mindamageforcamshakehit": 0.55,
    },
    "mindamageforcamshakehit": "rhs_ammo_l159_fuelpod_proxy",
    "count": 1,
    "weight": 100,
    "pylonweapon": "rhsusf_weap_DummyLauncher",
    "hardpoints": ["RHS_HP_L159_FUELPOD"],
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadaction": "",
    "maxleadspeed": 100,
    "weaponpoolavailable": 0,
    "scope": 1,
    "value": 1,
    "picture": "",
    "modelspecial": "",
    "useaction": 0,
    "useactiontitle": "",
    "initspeed": 900,
    "selectionfireanim": "zasleh",
    "namesound": "magazine",
    "mass": 8,
    "simulation": "ProxyMagazines",
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    # Class: CfgMagazines|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "descriptionshort": "",
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0,
}