rhs_mag_s13d_10 = {
    "displayname": "S-13 D FAE",
    "displaynameshort": "S-13D",
    "descriptionshort": "Thermobaric (35-40kg TNT equivalent). Introduced in 1995",
    # Ammo: CfgMagazines|rhs_mag_s13d_10|ammo [Indent level: 1],
    "ammo": {
        "_dictAmmoName": "rhs_ammo_s13d",
        "model": "rhsafrf|addons|rhs_airweapons|s13_rockets|rhs_r_s13d_fly",
        "aiammousageflags": "64+128",
        "cost": 100,
        "submunitionammo": "",
        "hit": 210,
        "indirecthit": 175,
        "indirecthitrange": 15,
        "explosive": 1,
        "allowagainstinfantry": 1,
        # Class: CfgAmmo|rhs_ammo_s13D|CamShakeExplode [Indent level: 1],
        "camshakeexplode": {
            "power": 22,
            "duration": 2,
            "frequency": 20,
            "distance": 123.905
        },
        # Class: CfgAmmo|rhs_ammo_s13D|CamShakeHit [Indent level: 1],
        "camshakehit": {
            "power": 110,
            "duration": 0.6,
            "frequency": 20,
            "distance": 1
        },
        "explosioneffects": "RHS_FAE_Explosion",
        "proxyshape": "rhsafrf|addons|rhs_airweapons|s13_rockets|rhs_r_s13_gasket",
        "dangerradiushit": 1250,
        "suppressionradiushit": 120,
        "sideairfriction": 0.001,
        "thrusttime": 0.6,
        # Class: CfgAmmo|rhs_ammo_s13b|CamShakeFire [Indent level: 1],
        "camshakefire": {
            "power": 3.32346,
            "duration": 2.2,
            "frequency": 20,
            "distance": 88.3629
        },
        # Class: CfgAmmo|rhs_ammo_s13b|CamShakePlayerFire [Indent level: 1],
        "camshakeplayerfire": {
            "power": 2,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "soundsetexplosion": ["RocketsHeavy_Exp_SoundSet","RocketsHeavy_Tail_SoundSet","Explosion_Debris_SoundSet"],
        "inittime": 0.02,
        "effectsmissile": "RHS_Rocket_Fired",
        "effectsmissileinit": "RHS_Rocket_Init",
        "soundfly": ["A3|Sounds_F|weapons|Rockets|rocket_fly_2",1,1.5,700],
        "submunitiondirectiontype": "SubmunitionModelDirection",
        "submunitioninitialoffset": [0,0,-0.1],
        "submunitionparentspeedcoef": 0,
        "submunitioninitspeed": 1053,
        "triggeronimpact": 1,
        "deleteparentwhentriggered": 0,
        "missilelockmaxdistance": 4000,
        "missilelockmindistance": 700,
        "warheadname": "HE",
        "maxspeed": 590,
        "thrust": 1060,
        "airfriction": 0.09,
        "fusedistance": 50,
        "whistledist": 30,
        "timetolive": 15,
        "muzzleeffect": "",
        "simulation": "shotMissile",
        "soundhit": ["A3|Sounds_F|weapons|Rockets|explosion_missile_02",2.51189,1,2500],
        "explosionsoundeffect": "DefaultExplosion",
        "soundengine": ["",1,1,20],
        "supersoniccracknear": ["",1,1,50],
        "supersoniccrackfar": ["",1,1,150],
        "cratereffects": "HERocketCrater",
        # Class: CfgAmmo|RocketBase|HitEffects [Indent level: 1],
        "hiteffects": {
            "hitwater": "ImpactEffectsWaterRocket"
        },
        # Class: CfgAmmo|RocketBase|EventHandlers [Indent level: 1],
        "eventhandlers": {
            # Class: CfgAmmo|RocketBase|EventHandlers|RHS_APS_FiredEH [Indent level: 2]
            "rhs_aps_firedeh": {
                "fired": "_this spawn rhs_fnc_aps_missileFired"
            }
        },
        "simulationstep": 0.05,
        "maneuvrability": 0,
        "maxcontrolrange": 0,
        "visiblefire": 32,
        "audiblefire": 32,
        "visiblefiretime": 20,
        "deflecting": 5,
        "access": 3,
        "underwaterhitrangecoef": 1,
        "typicalspeed": 900,
        "explosionforcecoef": 1,
        "iscrateroriented": 0,
        "cratershape": "",
        "weapontype": "Default",
        "animated": 0,
        "shadow": 0,
        "cartridge": "",
        "tracercolor": [0.7,0.7,0.5,0.04],
        "tracercolorr": [0.7,0.7,0.5,0.04],
        "soundfall": ["",1,1],
        "soundfakefall": ["soundFall",1],
        "hitgroundsoft": ["soundHit",1],
        "hitgroundhard": ["soundHit",1],
        "hitman": ["soundHit",1],
        "hitarmor": ["soundHit",1],
        "hitiron": ["soundHit",1],
        "hitbuilding": ["soundHit",1],
        "hitfoliage": ["soundHit",1],
        "hitwood": ["soundHit",1],
        "hitglass": ["soundHit",1],
        "hitglassarmored": ["soundHit",1],
        "hitconcrete": ["soundHit",1],
        "hitrubber": ["soundHit",1],
        "hitplastic": ["soundHit",1],
        "hitdefault": ["soundHit",1],
        "hitmetal": ["soundHit",1],
        "hitmetalplate": ["soundHit",1],
        "hittyre": ["soundHit",1],
        "hitwater": ["soundHit",1],
        "soundimpact": ["",1,1],
        "impactgroundsoft": ["soundImpact",1],
        "impactgroundhard": ["soundImpact",1],
        "impactman": ["soundImpact",1],
        "impactiron": ["soundImpact",1],
        "impactarmor": ["soundImpact",1],
        "impactbuilding": ["soundImpact",1],
        "impactfoliage": ["soundImpact",1],
        "impactwood": ["soundImpact",1],
        "impactglass": ["soundImpact",1],
        "impactglassarmored": ["soundImpact",1],
        "impactconcrete": ["soundImpact",1],
        "impactrubber": ["soundImpact",1],
        "impactplastic": ["soundImpact",1],
        "impactdefault": ["soundImpact",1],
        "impactmetal": ["soundImpact",1],
        "impactmetalplate": ["soundImpact",1],
        "impacttyre": ["soundImpact",1],
        "impactwater": ["soundImpact",1],
        "grenadefiresound": [],
        "grenadeburningsound": [],
        "deflectionslowdown": 0.8,
        "craterwatereffects": "ImpactEffectsWater",
        "effectssmoke": "SmokeShellWhite",
        "effectsfire": "CannonFire",
        "effectflare": "FlareShell",
        "effectfly": "",
        "minejumpeffects": "",
        "watereffectoffset": 0.45,
        "directionalexplosion": 0,
        "explosionangle": 60,
        "explosiondir": "explosionDir",
        "explosionpos": "explosionPos",
        "explosioneffectsdir": "explosionDir",
        "minimumsafezone": 0.1,
        "soundtrigger": [],
        "soundactivation": [],
        "sounddeactivation": [],
        "mintimetolive": 0,
        "irlock": 0,
        "airlock": 0,
        "laserlock": 0,
        "nvlock": 0,
        "artillerylock": 0,
        "hitonwater": 0,
        "lockseekradius": 100,
        "manualcontrol": 0,
        "tracklead": 1,
        "trackoversteer": 1,
        "missilelockcone": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "locktype": 0,
        "maverickweaponindexoffset": 0,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "autoseektarget": 0,
        "shootdistraction": -1,
        "explosiontime": 0,
        "icon": "",
        "explosiontype": "explosive",
        "minetrigger": "RangeTrigger",
        "mineboundingtime": 3,
        "mineboundingdist": 3,
        "mineinconspicuousness": 10,
        "minefloating": -1,
        "minedivespeed": 1,
        "mineplacedist": 0.5,
        "suppressionradiusbulletclose": -1,
        "dangerradiusbulletclose": -1,
        "caliber": 1,
        "whistleonfire": 0,
        # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
        "nvgmarkers": {
        },
        "mindamageforcamshakehit": 0.55,
    },
    "mindamageforcamshakehit": "rhs_ammo_s13d",
    "weight": 680,
    "scope": 2,
    "count": 10,
    "maxleadspeed": 200,
    "initspeed": 44,
    "namesound": "rockets",
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadaction": "",
    "weaponpoolavailable": 0,
    "value": 1,
    "model": "A3|weapons_F|ammo|mag_univ.p3d",
    "picture": "",
    "modelspecial": "",
    "useaction": 0,
    "useactiontitle": "",
    "selectionfireanim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    # Class: CfgMagazines|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0,
}