rhs_mag_fold_stock = {
    "scope": 1,
    "count": 1,
    "mass": 0,
    "picture": "A3|Weapons_F|Data|clear_empty.paa",
    "author": "Bohemia Interactive",
    "value": 1,
    "displayname": "",
    "model": "A3|weapons_F|ammo|mag_univ.p3d",
    "modelspecial": "",
    "useaction": 0,
    "useactiontitle": "",
    "reloadaction": "",
    "ammo": "",
    "type": 256,
    "initspeed": 900,
    "selectionfireanim": "zasleh",
    "namesound": "magazine",
    "maxleadspeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "displaynameshort": "",
    "weight": 0,
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    # Class: CfgMagazines|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "descriptionshort": "",
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0,
}