rhs_mag_laser_2a33_26 = {
    "count": 26,
    "displayname": "3VOF93 LG",
    "displaynameshort": "3VOF93 LG",
    # Ammo: CfgMagazines|rhs_mag_LASER_2a33|ammo [Indent level: 1],
    "ammo": {
        "_dictAmmoName": "rhs_ammo_3WOF93",
        # Ammo: CfgAmmo|Sh_155mm_AMOS_LG|submunitionAmmo [Indent level: 1],
        "submunitionammo": {
            "_dictAmmoName": "M_Mo_155mm_AT_LG",
            "hit": 1200,
            "indirecthit": 200,
            "indirecthitrange": 4,
            "weaponlocksystem": 4,
            # Class: CfgAmmo|M_Mo_120mm_AT_LG|Components [Indent level: 1],
            "components": {
                # Class: CfgAmmo|M_Mo_120mm_AT_LG|Components|SensorsManagerComponent [Indent level: 2]
                "sensorsmanagercomponent": {
                    # Class: CfgAmmo|M_Mo_120mm_AT_LG|Components|SensorsManagerComponent|Components [Indent level: 3]
                    "components": {
                        # Class: CfgAmmo|M_Mo_120mm_AT_LG|Components|SensorsManagerComponent|Components|LaserSensorComponent [Indent level: 4]
                        "lasersensorcomponent": {
                            # Class: CfgAmmo|M_Mo_120mm_AT_LG|Components|SensorsManagerComponent|Components|LaserSensorComponent|AirTarget [Indent level: 5]
                            "airtarget": {
                                "minrange": 800,
                                "maxrange": 800,
                                "objectdistancelimitcoef": -1,
                                "viewdistancelimitcoef": -1
                            },
                            # Class: CfgAmmo|M_Mo_120mm_AT_LG|Components|SensorsManagerComponent|Components|LaserSensorComponent|GroundTarget [Indent level: 5],
                            "groundtarget": {
                                "minrange": 800,
                                "maxrange": 800,
                                "objectdistancelimitcoef": -1,
                                "viewdistancelimitcoef": -1
                            },
                            "anglerangehorizontal": 40,
                            "anglerangevertical": 40,
                            "componenttype": "LaserSensorComponent",
                            "typerecognitiondistance": 0,
                            "color": [1,1,1,0],
                            "allowsmarking": 1,
                            "groundnoisedistancecoef": -1,
                            "maxgroundnoisedistance": -1,
                            "minspeedthreshold": 0,
                            "maxspeedthreshold": 0,
                            "animdirection": "",
                            "aimdown": 0,
                            "mintrackablespeed": -1e+010,
                            "maxtrackablespeed": 1e+010,
                            "mintrackableatl": -1e+010,
                            "maxtrackableatl": 1e+010
                        }
                    }
                }
            },
            "effectfly": "ArtilleryTrails",
            "cameraviewavailable": 1,
            "model": "A3|weapons_f|ammo|shell",
            "autoseektarget": 1,
            "airlock": 0,
            "maneuvrability": 6,
            "simulationstep": 0.002,
            "fusedistance": 0,
            "airfriction": 0.01,
            "sideairfriction": 0.03,
            "missilelockcone": 40,
            "missilekeeplockedcone": 40,
            "manualcontrol": 0,
            "maxspeed": 500,
            "maxcontrolrange": 4000,
            "soundhit1": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_01",2.51189,1,2000],
            "soundhit2": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_02",2.51189,1,2000],
            "soundhit3": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_03",2.51189,1,2000],
            "multisoundhit": ["soundHit1",0.34,"soundHit2",0.33,"soundHit3",0.33],
            "explosionsoundeffect": "DefaultExplosion",
            "soundfly": ["",1,1,400],
            "soundengine": ["",1,1,50],
            "supersoniccracknear": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_close",0.398107,1,20],
            "supersoniccrackfar": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_50meters",0.316228,1,50],
            "cratereffects": "ATMissileCrater",
            "explosioneffects": "ATMissileExplosion",
            "muzzleeffect": "BIS_fnc_effectFiredRocket",
            "effectsmissile": "missile4",
            "deflecting": 0,
            "cmimmunity": 0.9,
            "dangerradiushit": -1,
            "suppressionradiushit": 30,
            # Class: CfgAmmo|MissileBase|HitEffects [Indent level: 1],
            "hiteffects": {
                "hitwater": "ImpactEffectsWaterRocket"
            },
            "maverickweaponindexoffset": 0,
            "htmin": 60,
            "htmax": 1800,
            "afmax": 200,
            "mfmax": 100,
            "mfact": 0,
            "tbody": 0,
            # Class: CfgAmmo|MissileBase|EventHandlers [Indent level: 1],
            "eventhandlers": {
                # Class: CfgAmmo|MissileBase|EventHandlers|RHS_APS_FiredEH [Indent level: 2]
                "rhs_aps_firedeh": {
                    "fired": "_this spawn rhs_fnc_aps_missileFired"
                }
            },
            "simulation": "shotMissile",
            "timetolive": 20,
            "inittime": 0.15,
            "thrusttime": 2.5,
            "thrust": 350,
            "visiblefire": 32,
            "audiblefire": 32,
            "visiblefiretime": 20,
            "soundhit": ["",100,1],
            "cost": 10000,
            "access": 3,
            "underwaterhitrangecoef": 1,
            "typicalspeed": 900,
            "explosionforcecoef": 1,
            "iscrateroriented": 0,
            "proxyshape": "",
            "cratershape": "",
            "weapontype": "Default",
            "animated": 0,
            "shadow": 0,
            "cartridge": "",
            "tracercolor": [0.7,0.7,0.5,0.04],
            "tracercolorr": [0.7,0.7,0.5,0.04],
            "soundfall": ["",1,1],
            "soundfakefall": ["soundFall",1],
            "hitgroundsoft": ["soundHit",1],
            "hitgroundhard": ["soundHit",1],
            "hitman": ["soundHit",1],
            "hitarmor": ["soundHit",1],
            "hitiron": ["soundHit",1],
            "hitbuilding": ["soundHit",1],
            "hitfoliage": ["soundHit",1],
            "hitwood": ["soundHit",1],
            "hitglass": ["soundHit",1],
            "hitglassarmored": ["soundHit",1],
            "hitconcrete": ["soundHit",1],
            "hitrubber": ["soundHit",1],
            "hitplastic": ["soundHit",1],
            "hitdefault": ["soundHit",1],
            "hitmetal": ["soundHit",1],
            "hitmetalplate": ["soundHit",1],
            "hittyre": ["soundHit",1],
            "hitwater": ["soundHit",1],
            "soundimpact": ["",1,1],
            "impactgroundsoft": ["soundImpact",1],
            "impactgroundhard": ["soundImpact",1],
            "impactman": ["soundImpact",1],
            "impactiron": ["soundImpact",1],
            "impactarmor": ["soundImpact",1],
            "impactbuilding": ["soundImpact",1],
            "impactfoliage": ["soundImpact",1],
            "impactwood": ["soundImpact",1],
            "impactglass": ["soundImpact",1],
            "impactglassarmored": ["soundImpact",1],
            "impactconcrete": ["soundImpact",1],
            "impactrubber": ["soundImpact",1],
            "impactplastic": ["soundImpact",1],
            "impactdefault": ["soundImpact",1],
            "impactmetal": ["soundImpact",1],
            "impactmetalplate": ["soundImpact",1],
            "impacttyre": ["soundImpact",1],
            "impactwater": ["soundImpact",1],
            "grenadefiresound": [],
            "grenadeburningsound": [],
            "deflectionslowdown": 0.8,
            "explosive": 1,
            "craterwatereffects": "ImpactEffectsWater",
            "effectsmissileinit": "",
            "effectssmoke": "SmokeShellWhite",
            "effectsfire": "CannonFire",
            "effectflare": "FlareShell",
            "minejumpeffects": "",
            "watereffectoffset": 0.45,
            "directionalexplosion": 0,
            "explosionangle": 60,
            "explosiondir": "explosionDir",
            "explosionpos": "explosionPos",
            "explosioneffectsdir": "explosionDir",
            "minimumsafezone": 0.1,
            "soundtrigger": [],
            "soundactivation": [],
            "sounddeactivation": [],
            "mintimetolive": 0,
            "irlock": 0,
            "laserlock": 0,
            "nvlock": 0,
            "artillerylock": 0,
            "hitonwater": 0,
            "lockseekradius": 100,
            "tracklead": 1,
            "trackoversteer": 1,
            "locktype": 0,
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "shootdistraction": -1,
            "explosiontime": 0,
            "icon": "",
            "submunitionammo": "",
            "explosiontype": "explosive",
            "minetrigger": "RangeTrigger",
            "mineboundingtime": 3,
            "mineboundingdist": 3,
            "mineinconspicuousness": 10,
            "minefloating": -1,
            "minedivespeed": 1,
            "mineplacedist": 0.5,
            "suppressionradiusbulletclose": -1,
            "dangerradiusbulletclose": -1,
            "caliber": 1,
            "whistledist": 0,
            "whistleonfire": 0,
            # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
            "nvgmarkers": {
            },
            "mindamageforcamshakehit": 0.55,
        },
        "mindamageforcamshakehit": "M_Mo_155mm_AT_LG",
        "muzzleeffect": "",
        "triggerdistance": 500,
        "hit": 300,
        "cost": 500,
        "laserlock": 1,
        "irlock": 0,
        "submunitioncount": 1,
        "submunitionconeangle": 0,
        "autoseektarget": 1,
        "airfriction": 0,
        # Class: CfgAmmo|Sh_82mm_AMOS_guided|CamShakeFire [Indent level: 1],
        "camshakefire": {
            "power": 3.00922,
            "duration": 1.8,
            "frequency": 20,
            "distance": 72.4431
        },
        # Class: CfgAmmo|Sh_82mm_AMOS_guided|CamShakePlayerFire [Indent level: 1],
        "camshakeplayerfire": {
            "power": 0.01,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "model": "A3|Weapons_F|Ammo|shell.p3d",
        "simulation": "shotSubmunitions",
        "simulationstep": 0.05,
        "timetolive": 180,
        "soundhit": ["",316.228,1],
        "soundfly": ["",0.0316228,4],
        "hitonwater": 1,
        "artillerylock": 1,
        "indirecthitrange": 8,
        "visiblefire": 16,
        "audiblefire": 16,
        "visiblefiretime": 10,
        "deflecting": 5,
        "access": 3,
        "indirecthit": 0,
        "underwaterhitrangecoef": 1,
        "typicalspeed": 900,
        "explosionforcecoef": 1,
        "iscrateroriented": 0,
        "proxyshape": "",
        "cratershape": "",
        "weapontype": "Default",
        "animated": 0,
        "shadow": 0,
        "maxspeed": 0,
        "cartridge": "",
        "tracercolor": [0.7,0.7,0.5,0.04],
        "tracercolorr": [0.7,0.7,0.5,0.04],
        "soundengine": ["",1,1],
        "supersoniccracknear": ["",1,1],
        "supersoniccrackfar": ["",1,1],
        "soundfall": ["",1,1],
        "soundfakefall": ["soundFall",1],
        "hitgroundsoft": ["soundHit",1],
        "hitgroundhard": ["soundHit",1],
        "hitman": ["soundHit",1],
        "hitarmor": ["soundHit",1],
        "hitiron": ["soundHit",1],
        "hitbuilding": ["soundHit",1],
        "hitfoliage": ["soundHit",1],
        "hitwood": ["soundHit",1],
        "hitglass": ["soundHit",1],
        "hitglassarmored": ["soundHit",1],
        "hitconcrete": ["soundHit",1],
        "hitrubber": ["soundHit",1],
        "hitplastic": ["soundHit",1],
        "hitdefault": ["soundHit",1],
        "hitmetal": ["soundHit",1],
        "hitmetalplate": ["soundHit",1],
        "hittyre": ["soundHit",1],
        "hitwater": ["soundHit",1],
        "soundimpact": ["",1,1],
        "impactgroundsoft": ["soundImpact",1],
        "impactgroundhard": ["soundImpact",1],
        "impactman": ["soundImpact",1],
        "impactiron": ["soundImpact",1],
        "impactarmor": ["soundImpact",1],
        "impactbuilding": ["soundImpact",1],
        "impactfoliage": ["soundImpact",1],
        "impactwood": ["soundImpact",1],
        "impactglass": ["soundImpact",1],
        "impactglassarmored": ["soundImpact",1],
        "impactconcrete": ["soundImpact",1],
        "impactrubber": ["soundImpact",1],
        "impactplastic": ["soundImpact",1],
        "impactdefault": ["soundImpact",1],
        "impactmetal": ["soundImpact",1],
        "impactmetalplate": ["soundImpact",1],
        "impacttyre": ["soundImpact",1],
        "impactwater": ["soundImpact",1],
        "grenadefiresound": [],
        "grenadeburningsound": [],
        "deflectionslowdown": 0.8,
        "explosive": 1,
        "explosioneffects": "ExplosionEffects",
        "cratereffects": "ImpactEffectsMedium",
        "craterwatereffects": "ImpactEffectsWater",
        "effectsmissile": "ExplosionEffects",
        "effectsmissileinit": "",
        "effectssmoke": "SmokeShellWhite",
        "effectsfire": "CannonFire",
        "effectflare": "FlareShell",
        "effectfly": "",
        "minejumpeffects": "",
        "watereffectoffset": 0.45,
        "directionalexplosion": 0,
        "explosionangle": 60,
        "explosiondir": "explosionDir",
        "explosionpos": "explosionPos",
        "explosioneffectsdir": "explosionDir",
        "minimumsafezone": 0.1,
        "soundtrigger": [],
        "soundactivation": [],
        "sounddeactivation": [],
        "explosionsoundeffect": "",
        "mintimetolive": 0,
        "airlock": 0,
        "nvlock": 0,
        "lockseekradius": 100,
        "manualcontrol": 0,
        "maxcontrolrange": 350,
        "maneuvrability": 1,
        "tracklead": 1,
        "trackoversteer": 1,
        "missilelockcone": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "locktype": 0,
        "maverickweaponindexoffset": 0,
        "sideairfriction": 1,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "shootdistraction": -1,
        "explosiontime": 0,
        "fusedistance": 0,
        "inittime": 0,
        "thrusttime": 1.5,
        "thrust": 210,
        "icon": "",
        "explosiontype": "explosive",
        "minetrigger": "RangeTrigger",
        "mineboundingtime": 3,
        "mineboundingdist": 3,
        "mineinconspicuousness": 10,
        "minefloating": -1,
        "minedivespeed": 1,
        "mineplacedist": 0.5,
        # Class: CfgAmmo|Default|HitEffects [Indent level: 1],
        "hiteffects": {
            "vehicle": "ImpactMetal",
            "object": "ImpactConcrete"
        },
        "suppressionradiusbulletclose": -1,
        "suppressionradiushit": -1,
        "dangerradiusbulletclose": -1,
        "dangerradiushit": -1,
        "caliber": 1,
        "whistledist": 0,
        "whistleonfire": 0,
        # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
        "nvgmarkers": {
        },
        "mindamageforcamshakehit": 0.55,
        # Class: CfgAmmo|Default|EventHandlers [Indent level: 1],
        "eventhandlers": {
        },
    },
    "eventhandlers": "rhs_ammo_3WOF93",
    "scope": 2,
    "namesound": "heat",
    "author": "Bohemia Interactive",
    "initspeed": 810,
    "displaynamemfdformat": "HE",
    "muzzleimpulsefactor": [1.5,30],
    "type": 0,
    "reloadaction": "",
    "maxleadspeed": 100,
    "weaponpoolavailable": 0,
    "value": 1,
    "model": "A3|weapons_F|ammo|mag_univ.p3d",
    "picture": "",
    "modelspecial": "",
    "useaction": 0,
    "useactiontitle": "",
    "selectionfireanim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    # Class: CfgMagazines|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "descriptionshort": "",
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0,
}