rhs_mine_smine35_press_mag = {
    "author": "Red Hammer Studios",
    "scope": 2,
    # Ammo: CfgMagazines|rhs_mine_smine35_press_mag|ammo [Indent level: 1],
    "ammo": {
        "_dictAmmoName": "rhs_mine_smine35_press_ammo",
        "model": "rhsgref|addons|rhsgref_weapons2|mines|Smine35|SMI35_PROJ_PRESS",
        "minemodeldisabled": "rhsgref|addons|rhsgref_weapons2|mines|Smine35|SMI35_ITEM_PRESS",
        "defaultmagazine": "rhs_mine_smine35_press_mag",
        "cost": 200,
        "mineboundingdist": 1.25,
        "mineboundingtime": 0.5,
        "minedivespeed": 1,
        "mineplacedist": 0.5,
        "hit": 20,
        "indirecthit": 20,
        "indirecthitrange": 20,
        "soundhit1": ["A3|Sounds_F|arsenal|explosives|mines|Explosion_M6_slam_mine_01",3.16228,1,1300],
        "soundhit2": ["A3|Sounds_F|arsenal|explosives|mines|Explosion_M6_slam_mine_02",3.16228,1,2000],
        "multisoundhit": ["soundHit1",0.5,"soundHit2",0.5],
        "sounddeactivation": ["A3|Sounds_F_Orange|arsenal|explosives|Handling|ApersBoundingMine_Deactivate_01",1.99526,1,20],
        "explosioneffects": "BoundingMineExplosion",
        "cratereffects": "BoundingMineCrater",
        "minejumpeffects": "MineJumpEffect",
        "whistledist": 60,
        "mineinconspicuousness": 40,
        "minetrigger": "RangeTriggerBounding",
        "soundsetexplosion": ["M6slamMine_Exp_SoundSet","M6slamMine_Tail_SoundSet","Explosion_Debris_SoundSet"],
        "soundactivation": ["A3|Sounds_F_Orange|arsenal|explosives|Handling|ApersBoundingMine_Placement_01",1,1,20],
        "soundtrigger": ["A3|Sounds_F_Orange|arsenal|explosives|Handling|ApersBoundingMine_Trigger_01",3.98107,1,20],
        "icon": "iconExplosiveAP",
        "mapsize": 1,
        "explosiontype": "mine",
        "triggerwhendestroyed": 1,
        "underwaterhitrangecoef": 0.5,
        "simulation": "shotBoundingMine",
        "simulationstep": 0.1,
        "soundhit": ["",100,1],
        "soundfly": ["",0,1],
        "soundengine": ["",0,1],
        "visiblefire": 0,
        "audiblefire": 0,
        "visiblefiretime": 0,
        "timetolive": 0,
        "minecanbereactivated": 1,
        "access": 3,
        "typicalspeed": 900,
        "explosionforcecoef": 1,
        "iscrateroriented": 0,
        "proxyshape": "",
        "cratershape": "",
        "weapontype": "Default",
        "animated": 0,
        "shadow": 0,
        "maxspeed": 0,
        "cartridge": "",
        "tracercolor": [0.7,0.7,0.5,0.04],
        "tracercolorr": [0.7,0.7,0.5,0.04],
        "supersoniccracknear": ["",1,1],
        "supersoniccrackfar": ["",1,1],
        "soundfall": ["",1,1],
        "soundfakefall": ["soundFall",1],
        "hitgroundsoft": ["soundHit",1],
        "hitgroundhard": ["soundHit",1],
        "hitman": ["soundHit",1],
        "hitarmor": ["soundHit",1],
        "hitiron": ["soundHit",1],
        "hitbuilding": ["soundHit",1],
        "hitfoliage": ["soundHit",1],
        "hitwood": ["soundHit",1],
        "hitglass": ["soundHit",1],
        "hitglassarmored": ["soundHit",1],
        "hitconcrete": ["soundHit",1],
        "hitrubber": ["soundHit",1],
        "hitplastic": ["soundHit",1],
        "hitdefault": ["soundHit",1],
        "hitmetal": ["soundHit",1],
        "hitmetalplate": ["soundHit",1],
        "hittyre": ["soundHit",1],
        "hitwater": ["soundHit",1],
        "soundimpact": ["",1,1],
        "impactgroundsoft": ["soundImpact",1],
        "impactgroundhard": ["soundImpact",1],
        "impactman": ["soundImpact",1],
        "impactiron": ["soundImpact",1],
        "impactarmor": ["soundImpact",1],
        "impactbuilding": ["soundImpact",1],
        "impactfoliage": ["soundImpact",1],
        "impactwood": ["soundImpact",1],
        "impactglass": ["soundImpact",1],
        "impactglassarmored": ["soundImpact",1],
        "impactconcrete": ["soundImpact",1],
        "impactrubber": ["soundImpact",1],
        "impactplastic": ["soundImpact",1],
        "impactdefault": ["soundImpact",1],
        "impactmetal": ["soundImpact",1],
        "impactmetalplate": ["soundImpact",1],
        "impacttyre": ["soundImpact",1],
        "impactwater": ["soundImpact",1],
        "grenadefiresound": [],
        "grenadeburningsound": [],
        "deflecting": 0,
        "deflectionslowdown": 0.8,
        "explosive": 1,
        "craterwatereffects": "ImpactEffectsWater",
        "effectsmissile": "ExplosionEffects",
        "effectsmissileinit": "",
        "effectssmoke": "SmokeShellWhite",
        "effectsfire": "CannonFire",
        "effectflare": "FlareShell",
        "effectfly": "",
        "watereffectoffset": 0.45,
        "directionalexplosion": 0,
        "explosionangle": 60,
        "explosiondir": "explosionDir",
        "explosionpos": "explosionPos",
        "explosioneffectsdir": "explosionDir",
        "minimumsafezone": 0.1,
        "explosionsoundeffect": "",
        "mintimetolive": 0,
        "irlock": 0,
        "airlock": 0,
        "laserlock": 0,
        "nvlock": 0,
        "artillerylock": 0,
        "hitonwater": 0,
        "lockseekradius": 100,
        "manualcontrol": 0,
        "maxcontrolrange": 350,
        "maneuvrability": 1,
        "tracklead": 1,
        "trackoversteer": 1,
        "missilelockcone": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "locktype": 0,
        "maverickweaponindexoffset": 0,
        "sideairfriction": 1,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "autoseektarget": 0,
        "shootdistraction": -1,
        "explosiontime": 0,
        "fusedistance": 0,
        "inittime": 0,
        "thrusttime": 1.5,
        "thrust": 210,
        "airfriction": -0.0005,
        "submunitionammo": "",
        "minefloating": -1,
        # Class: CfgAmmo|Default|HitEffects [Indent level: 1],
        "hiteffects": {
            "vehicle": "ImpactMetal",
            "object": "ImpactConcrete"
        },
        "suppressionradiusbulletclose": -1,
        "suppressionradiushit": -1,
        "dangerradiusbulletclose": -1,
        "dangerradiushit": -1,
        "caliber": 1,
        "whistleonfire": 0,
        # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
        "nvgmarkers": {
        },
        "mindamageforcamshakehit": 0.55,
        # Class: CfgAmmo|Default|EventHandlers [Indent level: 1],
        "eventhandlers": {
        },
    },
    "eventhandlers": "rhs_mine_smine35_press_ammo",
    "picture": "rhsgref|addons|rhsgref_weapons2|icons|rhs_inv_smine35_ca.paa",
    "displayname": "S.Mi.35 (S.Mi.Z.35) APB Mine",
    "displaynameshort": "S.Mi.35",
    "descriptionshort": "Schrapnellmine 35 Bounding Anti-Personnel Mine with S.Mi.Z.35 pressure igniter.",
    "mass": 80,
    "model": "rhsgref|addons|rhsgref_weapons2|mines|Smine35|SMI35_ITEM_PRESS",
    # Class: CfgMagazines|APERSBoundingMine_Range_Mag|Library [Indent level: 1],
    "library": {
        "libtextdesc": "The anti-personnel bounding mine is best suitable for open areas. It is usually burried just bellow the surface of the ground. When triggered, a charge launches the body of the mine one meter into the air. The explosion covers a close area with fragments, killing the whole group."
    },
    "descriptionuse": "<t color='#9cf953'>Use: </t>Place Mine",
    "allowedslots": [901,701],
    "useaction": 1,
    "useactiontitle": "Put %1 (%2 left)",
    "type": "2*		256",
    "value": 5,
    "namesoundweapon": "mine",
    "namesound": "mine",
    "count": 1,
    "initspeed": 0,
    "maxleadspeed": 0,
    "weaponpoolavailable": 1,
    "sound": ["A3|sounds_f|dummysound",0.000316228,1,10],
    "modelspecial": "",
    "reloadaction": "",
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0,
}