rhs_vg40md_white = {
    "author": "Red Hammer Studios",
    "scope": 1,
    "displayname": "VG-40MD (White)",
    "picture": "rhsafrf|addons|rhs_weapons2|gear|rhs_vg40md_white_ca.paa",
    "model": "rhsafrf|addons|rhs_weapons2|vogs|rhs_vg40md",
    "modelspecial": "rhsafrf|addons|rhs_weapons|mag_proxies|rhs_mag_vg40md",
    "displaynameshort": "White Smoke",
    "descriptionshort": "Type: Smoke Round<br />Caliber: 40 mm<br />Rounds: 1<br />Used in: GP25",
    "namesoundweapon": "smokeshell",
    "namesound": "smokeshell",
    # Ammo: CfgMagazines|rhs_GRD40_White|ammo [Indent level: 1],
    "ammo": {
        "_dictAmmoName": "rhs_g_vg40md_white",
        "hit": 0,
        "indirecthit": 0,
        "indirecthitrange": 0.2,
        "dangerradiushit": -1,
        "suppressionradiushit": -1,
        "typicalspeed": 70,
        "cost": 100,
        "simulation": "shotSmokeX",
        "explosive": 0,
        "deflecting": 8,
        "explosiontime": 2,
        "timetolive": 30,
        "fusedistance": 0,
        "soundhit": ["",0,1],
        "smokeshellsoundhit1": ["A3|Sounds_F|weapons|smokeshell|smoke_1",1.25893,1,100],
        "smokeshellsoundhit2": ["A3|Sounds_F|weapons|smokeshell|smoke_2",1.25893,1,100],
        "smokeshellsoundhit3": ["A3|Sounds_F|weapons|smokeshell|smoke_3",1.25893,1,100],
        "smokeshellsoundloop1": ["A3|Sounds_F|weapons|smokeshell|smoke_loop1",0.125893,1,70],
        "smokeshellsoundloop2": ["A3|Sounds_F|weapons|smokeshell|smoke_loop2",0.125893,1,70],
        "grenadefiresound": ["SmokeShellSoundHit1",0.25,"SmokeShellSoundHit2",0.25,"SmokeShellSoundHit3",0.5],
        "grenadeburningsound": ["SmokeShellSoundLoop1",0.5,"SmokeShellSoundLoop2",0.5],
        "aiammousageflags": "4 + 2",
        "smokecolor": [1,1,1,1],
        "effectssmoke": "SmokeShellWhiteEffect",
        "whistledist": 0,
        "model": "rhsafrf|addons|rhs_weapons2|vogs|rhs_vg40md",
        "airfriction": -0.0012,
        "warheadname": "HEAT",
        "explosionsoundeffect": "DefaultExplosion",
        "visiblefire": 1,
        "audiblefire": 30,
        "visiblefiretime": 3,
        "caliber": 2,
        "soundhit1": ["A3|Sounds_F|arsenal|explosives|Grenades|Explosion_gng_grenades_01",3.16228,1,1500],
        "soundhit2": ["A3|Sounds_F|arsenal|explosives|Grenades|Explosion_gng_grenades_02",3.16228,1,1500],
        "soundhit3": ["A3|Sounds_F|arsenal|explosives|Grenades|Explosion_gng_grenades_03",3.16228,1,1500],
        "soundhit4": ["A3|Sounds_F|arsenal|explosives|Grenades|Explosion_gng_grenades_04",3.16228,1,1500],
        "multisoundhit": ["soundHit1",0.25,"soundHit2",0.25,"soundHit3",0.25,"soundHit4",0.25],
        # Class: CfgAmmo|G_40mm_HE|CamShakeExplode [Indent level: 1],
        "camshakeexplode": {
            "power": 8,
            "duration": 1.2,
            "frequency": 20,
            "distance": 74.5964
        },
        # Class: CfgAmmo|G_40mm_HE|CamShakeHit [Indent level: 1],
        "camshakehit": {
            "power": 20,
            "duration": 0.4,
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo|G_40mm_HE|CamShakeFire [Indent level: 1],
        "camshakefire": {
            "power": 0,
            "duration": 0.2,
            "frequency": 20,
            "distance": 0
        },
        # Class: CfgAmmo|G_40mm_HE|CamShakePlayerFire [Indent level: 1],
        "camshakeplayerfire": {
            "power": 0,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "soundsetexplosion": ["GrenadeHe_Exp_SoundSet","GrenadeHe_Tail_SoundSet","Explosion_Debris_SoundSet"],
        "soundhit5": ["A3|Sounds_F|weapons|Explosion|gr_explosion_5",3.16228,1,1400],
        "soundhit6": ["A3|Sounds_F|weapons|Explosion|gr_explosion_6",3.16228,1,1400],
        "supersoniccracknear": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_close",0.316228,1,50],
        "supersoniccrackfar": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_50meters",0.223872,1,75],
        "cratereffects": "GrenadeCrater",
        "explosioneffects": "GrenadeExplosion",
        "muzzleeffect": "",
        "explosionforcecoef": 4,
        "shadow": 1,
        "simulationstep": 0.05,
        "soundfly": ["",3.16228e-005,1],
        "soundengine": ["",0.0001,4],
        "access": 3,
        "underwaterhitrangecoef": 1,
        "iscrateroriented": 0,
        "proxyshape": "",
        "cratershape": "",
        "weapontype": "Default",
        "animated": 0,
        "maxspeed": 0,
        "cartridge": "",
        "tracercolor": [0.7,0.7,0.5,0.04],
        "tracercolorr": [0.7,0.7,0.5,0.04],
        "soundfall": ["",1,1],
        "soundfakefall": ["soundFall",1],
        "hitgroundsoft": ["soundHit",1],
        "hitgroundhard": ["soundHit",1],
        "hitman": ["soundHit",1],
        "hitarmor": ["soundHit",1],
        "hitiron": ["soundHit",1],
        "hitbuilding": ["soundHit",1],
        "hitfoliage": ["soundHit",1],
        "hitwood": ["soundHit",1],
        "hitglass": ["soundHit",1],
        "hitglassarmored": ["soundHit",1],
        "hitconcrete": ["soundHit",1],
        "hitrubber": ["soundHit",1],
        "hitplastic": ["soundHit",1],
        "hitdefault": ["soundHit",1],
        "hitmetal": ["soundHit",1],
        "hitmetalplate": ["soundHit",1],
        "hittyre": ["soundHit",1],
        "hitwater": ["soundHit",1],
        "soundimpact": ["",1,1],
        "impactgroundsoft": ["soundImpact",1],
        "impactgroundhard": ["soundImpact",1],
        "impactman": ["soundImpact",1],
        "impactiron": ["soundImpact",1],
        "impactarmor": ["soundImpact",1],
        "impactbuilding": ["soundImpact",1],
        "impactfoliage": ["soundImpact",1],
        "impactwood": ["soundImpact",1],
        "impactglass": ["soundImpact",1],
        "impactglassarmored": ["soundImpact",1],
        "impactconcrete": ["soundImpact",1],
        "impactrubber": ["soundImpact",1],
        "impactplastic": ["soundImpact",1],
        "impactdefault": ["soundImpact",1],
        "impactmetal": ["soundImpact",1],
        "impactmetalplate": ["soundImpact",1],
        "impacttyre": ["soundImpact",1],
        "impactwater": ["soundImpact",1],
        "deflectionslowdown": 0.8,
        "craterwatereffects": "ImpactEffectsWater",
        "effectsmissile": "ExplosionEffects",
        "effectsmissileinit": "",
        "effectsfire": "CannonFire",
        "effectflare": "FlareShell",
        "effectfly": "",
        "minejumpeffects": "",
        "watereffectoffset": 0.45,
        "directionalexplosion": 0,
        "explosionangle": 60,
        "explosiondir": "explosionDir",
        "explosionpos": "explosionPos",
        "explosioneffectsdir": "explosionDir",
        "minimumsafezone": 0.1,
        "soundtrigger": [],
        "soundactivation": [],
        "sounddeactivation": [],
        "mintimetolive": 0,
        "irlock": 0,
        "airlock": 0,
        "laserlock": 0,
        "nvlock": 0,
        "artillerylock": 0,
        "hitonwater": 0,
        "lockseekradius": 100,
        "manualcontrol": 0,
        "maxcontrolrange": 350,
        "maneuvrability": 1,
        "tracklead": 1,
        "trackoversteer": 1,
        "missilelockcone": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "locktype": 0,
        "maverickweaponindexoffset": 0,
        "sideairfriction": 1,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "autoseektarget": 0,
        "shootdistraction": -1,
        "inittime": 0,
        "thrusttime": 1.5,
        "thrust": 210,
        "icon": "",
        "submunitionammo": "",
        "explosiontype": "explosive",
        "minetrigger": "RangeTrigger",
        "mineboundingtime": 3,
        "mineboundingdist": 3,
        "mineinconspicuousness": 10,
        "minefloating": -1,
        "minedivespeed": 1,
        "mineplacedist": 0.5,
        # Class: CfgAmmo|Default|HitEffects [Indent level: 1],
        "hiteffects": {
            "vehicle": "ImpactMetal",
            "object": "ImpactConcrete"
        },
        "suppressionradiusbulletclose": -1,
        "dangerradiusbulletclose": -1,
        "whistleonfire": 0,
        # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
        "nvgmarkers": {
        },
        "mindamageforcamshakehit": 0.55,
        # Class: CfgAmmo|Default|EventHandlers [Indent level: 1],
        "eventhandlers": {
        },
    },
    "eventhandlers": "rhs_g_vg40md_white",
    "modelspecialisproxy": 1,
    "count": 1,
    "mass": 4.125,
    "initspeed": 76.5,
    "type": 16,
    "deleteifempty": 0,
    "value": 1,
    "useaction": 0,
    "useactiontitle": "",
    "reloadaction": "",
    "selectionfireanim": "zasleh",
    "maxleadspeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    # Class: CfgMagazines|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0,
}