rhs_mag_kh55sh_nocamo_6 = {
    "count": 6,
    "hardpoints": [],
    "displayname": "Kh-55Sh HE",
    # Ammo: CfgMagazines|rhs_mag_kh55sh_nocamo|ammo [Indent level: 1],
    "ammo": {
        "_dictAmmoName": "rhs_ammo_kh55sh_nocamo",
        "rhs_warheadtype": "EXPLOSIVE",
        "model": "rhsafrf|addons|rhs_airweapons|rhs_m_kh55sm2_fly",
        "proxyshape": "rhsafrf|addons|rhs_airweapons|rhs_m_kh55sm2",
        "submunitionammo": "",
        "cratereffects": "RHS_HeavyBombCrater",
        "explosioneffects": "RHS_HeavyBombExplosion",
        "effectsmissile": "missile5",
        "hit": 9920,
        "indirecthit": 1300,
        "indirecthitrange": 56,
        "inittime": 6,
        "maneuvrability": 10,
        "maxcontrolrange": 350000,
        "maxspeed": 255,
        "sideairfriction": 0.001,
        "simulationstep": 0.001,
        "thrust": 20,
        "thrusttime": 180,
        "timetolive": 900,
        "tracklead": 0.95,
        "trackoversteer": 50,
        "whistledist": 25,
        "weaponlocksystem": 16,
        "locktype": 0,
        "irlock": 1,
        "laserlock": 1,
        "soundfly": ["A3|Sounds_F|arsenal|weapons|Launchers|NLAW|Fly_NLAW",2.5,1.5,10800],
        "soundsetexplosion": ["BombsHeavy_Exp_SoundSet","BombsHeavy_Tail_SoundSet","Explosion_Debris_SoundSet"],
        "rhs_yield": 50000,
        "rhs_fuserange": 100,
        # Class: CfgAmmo|rhs_ammo_kh55sm|CamShakeExplode [Indent level: 1],
        "camshakeexplode": {
            "power": 140,
            "duration": 5.2,
            "frequency": 20,
            "distance": 2011.66
        },
        # Class: CfgAmmo|rhs_ammo_kh55sm|CamShakeHit [Indent level: 1],
        "camshakehit": {
            "power": 700,
            "duration": 1,
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo|rhs_ammo_kh29l|Components [Indent level: 1],
        "components": {
            # Class: CfgAmmo|rhs_ammo_kh29l|Components|SensorsManagerComponent [Indent level: 2]
            "sensorsmanagercomponent": {
                # Class: CfgAmmo|rhs_ammo_kh29l|Components|SensorsManagerComponent|Components [Indent level: 3]
                "components": {
                    # Class: CfgAmmo|rhs_ammo_kh29l|Components|SensorsManagerComponent|Components|LaserSensorComponent [Indent level: 4]
                    "lasersensorcomponent": {
                        # Class: CfgAmmo|rhs_ammo_kh29l|Components|SensorsManagerComponent|Components|LaserSensorComponent|AirTarget [Indent level: 5]
                        "airtarget": {
                            "minrange": 10000,
                            "maxrange": 10000,
                            "objectdistancelimitcoef": -1,
                            "viewdistancelimitcoef": -1
                        },
                        # Class: CfgAmmo|rhs_ammo_kh29l|Components|SensorsManagerComponent|Components|LaserSensorComponent|GroundTarget [Indent level: 5],
                        "groundtarget": {
                            "minrange": 10000,
                            "maxrange": 10000,
                            "objectdistancelimitcoef": -1,
                            "viewdistancelimitcoef": -1
                        },
                        "maxtrackablespeed": 30,
                        "anglerangehorizontal": 180,
                        "anglerangevertical": 180,
                        "componenttype": "LaserSensorComponent",
                        "typerecognitiondistance": 0,
                        "color": [1,1,1,0],
                        "allowsmarking": 1,
                        "groundnoisedistancecoef": -1,
                        "maxgroundnoisedistance": -1,
                        "minspeedthreshold": 0,
                        "maxspeedthreshold": 0,
                        "animdirection": "",
                        "aimdown": 0,
                        "mintrackablespeed": -1e+010,
                        "mintrackableatl": -1e+010,
                        "maxtrackableatl": 1e+010
                    }
                }
            }
        },
        "submunitiondirectiontype": "SubmunitionModelDirection",
        "submunitioninitialoffset": [0,0,-0.2],
        "submunitionparentspeedcoef": 0,
        "submunitioninitspeed": 1000,
        "triggeronimpact": 1,
        "deleteparentwhentriggered": 0,
        "maverickweaponindexoffset": 0,
        "lockseekradius": 120,
        "missilelockcone": 30,
        "missilekeeplockedcone": 30,
        "missilelockmaxdistance": 9000,
        "missilelockmindistance": 1500,
        "missilelockmaxspeed": 55,
        "cameraviewavailable": 0,
        "cost": 800,
        "warheadname": "HE",
        "airlock": 0,
        "cmimmunity": 0.5,
        "flightprofiles": ["TopDown"],
        # Class: CfgAmmo|Missile_AGM_02_F|TopDown [Indent level: 1],
        "topdown": {
            "ascendheight": 400,
            "descenddistance": 1000,
            "mindistance": 400,
            "ascendangle": 0.01
        },
        "aiammousageflags": "128 + 512",
        "airfriction": 0.05,
        "typicalspeed": 270,
        "fusedistance": 350,
        "effectsmissileinit": "PylonBackEffects",
        "muzzleeffect": "",
        # Class: CfgAmmo|Missile_AGM_02_F|CamShakeFire [Indent level: 1],
        "camshakefire": {
            "power": 2.9907,
            "duration": 1.8,
            "frequency": 20,
            "distance": 71.5542
        },
        # Class: CfgAmmo|Missile_AGM_02_F|CamShakePlayerFire [Indent level: 1],
        "camshakeplayerfire": {
            "power": 4,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "manualcontrol": 0,
        "soundhit1": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_01",2.51189,1,2000],
        "soundhit2": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_02",2.51189,1,2000],
        "soundhit3": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_03",2.51189,1,2000],
        "multisoundhit": ["soundHit1",0.34,"soundHit2",0.33,"soundHit3",0.33],
        "explosionsoundeffect": "DefaultExplosion",
        "soundengine": ["",1,1,50],
        "supersoniccracknear": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_close",0.398107,1,20],
        "supersoniccrackfar": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_50meters",0.316228,1,50],
        "deflecting": 0,
        "dangerradiushit": -1,
        "suppressionradiushit": 30,
        # Class: CfgAmmo|MissileBase|HitEffects [Indent level: 1],
        "hiteffects": {
            "hitwater": "ImpactEffectsWaterRocket"
        },
        "htmin": 60,
        "htmax": 1800,
        "afmax": 200,
        "mfmax": 100,
        "mfact": 0,
        "tbody": 0,
        # Class: CfgAmmo|MissileBase|EventHandlers [Indent level: 1],
        "eventhandlers": {
            # Class: CfgAmmo|MissileBase|EventHandlers|RHS_APS_FiredEH [Indent level: 2]
            "rhs_aps_firedeh": {
                "fired": "_this spawn rhs_fnc_aps_missileFired"
            }
        },
        "simulation": "shotMissile",
        "visiblefire": 32,
        "audiblefire": 32,
        "visiblefiretime": 20,
        "soundhit": ["",100,1],
        "access": 3,
        "underwaterhitrangecoef": 1,
        "explosionforcecoef": 1,
        "iscrateroriented": 0,
        "cratershape": "",
        "weapontype": "Default",
        "animated": 0,
        "shadow": 0,
        "cartridge": "",
        "tracercolor": [0.7,0.7,0.5,0.04],
        "tracercolorr": [0.7,0.7,0.5,0.04],
        "soundfall": ["",1,1],
        "soundfakefall": ["soundFall",1],
        "hitgroundsoft": ["soundHit",1],
        "hitgroundhard": ["soundHit",1],
        "hitman": ["soundHit",1],
        "hitarmor": ["soundHit",1],
        "hitiron": ["soundHit",1],
        "hitbuilding": ["soundHit",1],
        "hitfoliage": ["soundHit",1],
        "hitwood": ["soundHit",1],
        "hitglass": ["soundHit",1],
        "hitglassarmored": ["soundHit",1],
        "hitconcrete": ["soundHit",1],
        "hitrubber": ["soundHit",1],
        "hitplastic": ["soundHit",1],
        "hitdefault": ["soundHit",1],
        "hitmetal": ["soundHit",1],
        "hitmetalplate": ["soundHit",1],
        "hittyre": ["soundHit",1],
        "hitwater": ["soundHit",1],
        "soundimpact": ["",1,1],
        "impactgroundsoft": ["soundImpact",1],
        "impactgroundhard": ["soundImpact",1],
        "impactman": ["soundImpact",1],
        "impactiron": ["soundImpact",1],
        "impactarmor": ["soundImpact",1],
        "impactbuilding": ["soundImpact",1],
        "impactfoliage": ["soundImpact",1],
        "impactwood": ["soundImpact",1],
        "impactglass": ["soundImpact",1],
        "impactglassarmored": ["soundImpact",1],
        "impactconcrete": ["soundImpact",1],
        "impactrubber": ["soundImpact",1],
        "impactplastic": ["soundImpact",1],
        "impactdefault": ["soundImpact",1],
        "impactmetal": ["soundImpact",1],
        "impactmetalplate": ["soundImpact",1],
        "impacttyre": ["soundImpact",1],
        "impactwater": ["soundImpact",1],
        "grenadefiresound": [],
        "grenadeburningsound": [],
        "deflectionslowdown": 0.8,
        "explosive": 1,
        "craterwatereffects": "ImpactEffectsWater",
        "effectssmoke": "SmokeShellWhite",
        "effectsfire": "CannonFire",
        "effectflare": "FlareShell",
        "effectfly": "",
        "minejumpeffects": "",
        "watereffectoffset": 0.45,
        "directionalexplosion": 0,
        "explosionangle": 60,
        "explosiondir": "explosionDir",
        "explosionpos": "explosionPos",
        "explosioneffectsdir": "explosionDir",
        "minimumsafezone": 0.1,
        "soundtrigger": [],
        "soundactivation": [],
        "sounddeactivation": [],
        "mintimetolive": 0,
        "nvlock": 0,
        "artillerylock": 0,
        "hitonwater": 0,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "autoseektarget": 0,
        "shootdistraction": -1,
        "explosiontime": 0,
        "icon": "",
        "explosiontype": "explosive",
        "minetrigger": "RangeTrigger",
        "mineboundingtime": 3,
        "mineboundingdist": 3,
        "mineinconspicuousness": 10,
        "minefloating": -1,
        "minedivespeed": 1,
        "mineplacedist": 0.5,
        "suppressionradiusbulletclose": -1,
        "dangerradiusbulletclose": -1,
        "caliber": 1,
        "whistleonfire": 0,
        # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
        "nvgmarkers": {
        },
        "mindamageforcamshakehit": 0.55,
    },
    "mindamageforcamshakehit": "rhs_ammo_kh55sh_nocamo",
    "displaynameshort": "Kh-55Sh HE (camo)",
    "descriptionshort": "High explosive",
    "model": "rhsafrf|addons|rhs_airweapons|rhs_pylon_m_kh55sm",
    "initspeed": 0,
    "namesound": "missiles",
    "mass": 1700,
    "pylonweapon": "rhs_weap_kh55sm_Dummy_Launcher",
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadaction": "",
    "maxleadspeed": 100,
    "weaponpoolavailable": 0,
    "scope": 1,
    "value": 1,
    "picture": "",
    "modelspecial": "",
    "useaction": 0,
    "useactiontitle": "",
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    # Class: CfgMagazines|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0,
}