rhs_mag_mgm164_block2_1 = {
    "hardpoints": [],
    "displayname": "MGM-164A",
    "displaynameshort": "Cluster, Guided HEAT",
    "descriptionshort": "ATacMS Block II, GPS/INS, ×13 Guided BAT",
    # Ammo: CfgMagazines|rhs_mag_mgm164_block2_1|ammo [Indent level: 1],
    "ammo": {
        "_dictAmmoName": "rhs_ammo_mgm164_block2_rocket",
    },
    "ammo": "rhs_ammo_mgm164_block2_rocket",
    "count": 1,
    "model": "rhsusf|addons|rhsusf_himars|M142_ATACMS_Pod",
    "pylonweapon": "rhs_weap_atacms",
    "initspeed": 850,
    "scope": 2,
    "namesound": "rockets",
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadaction": "",
    "maxleadspeed": 100,
    "weaponpoolavailable": 0,
    "value": 1,
    "picture": "",
    "modelspecial": "",
    "useaction": 0,
    "useactiontitle": "",
    "selectionfireanim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    # Class: CfgMagazines|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0,
}