rhs_mag_bk_base = {
    "scope": 2,
    "reloadtime": 12,
    "magazinereloadtime": 12,
    "count": 8,
    "initspeed": 900,
    "maxleadspeed": 27,
    "rhs_magazineindex": 2,
    "muzzleimpulsefactor": 0.01,
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadaction": "",
    "weaponpoolavailable": 0,
    "value": 1,
    "displayname": "",
    "model": "A3|weapons_F|ammo|mag_univ.p3d",
    "picture": "",
    "modelspecial": "",
    "useaction": 0,
    "useactiontitle": "",
    "ammo": "",
    "selectionfireanim": "zasleh",
    "namesound": "magazine",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "displaynameshort": "",
    "weight": 0,
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    # Class: CfgMagazines|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "descriptionshort": "",
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0,
}