rhs_mag_30Rnd_556x45_Mk318_Stanag = {
    "author": "Red Hammer Studios",
    "picture": "\rhsusf\addons\rhsusf_inventoryicons\data\magazines\rhs_mag_30Rnd_556x45_Mk318_Stanag_ca.paa",
    "displayName": "30rnd STANAG Mk318 Mod 0",
    "displayNameShort": "Mk318",
    "descriptionShort": "Caliber: 5.56x45mm NATO<br/>Rounds: 30<br/>Used in: M4, M16, M27, M249",
    "ammo": "rhs_ammo_556x45_Mk318_Ball",
    "initSpeed": 950.366,
    "hiddenSelectionsTextures": ["rhsusf|addons|rhsusf_weapons|mag_proxies|data|rhs_30rn_usgi_alum_co.paa","rhsusf|addons|rhsusf_weapons|mag_proxies|data|rhs_556_m193_co.paa","rhsusf|addons|rhsusf_weapons|mag_proxies|data|rhs_30rn_magpul_earth_co.paa"],
    "mass": 9.35,
    "tracersEvery": 0,
    "lastRoundsTracer": 0,
    "model": "rhsusf\addons\rhsusf_weapons\magazines\rhs_stanag_mag",
    "modelSpecial": "rhsusf\addons\rhsusf_weapons\mag_proxies\rhs_mag_556x45_stanag_usgi_n_30rnd",
    "modelSpecialIsProxy": 1,
    "hiddenSelections": ["camo","camo01","camo02"],
    "scope": 2,
    "count": 30,
    "value": 1,
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "type": 256,
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}