rhs_200rnd_556x45_B_SAW = {
    "author": "Red Hammer Studios",
    "ammo": "rhs_ammo_556x45_M855A1_Ball",
    "displayname": "200rnd M249 Box M855A1",
    "displaynameshort": "M855A1 EPR",
    "lastroundstracer": 0,
    "tracersevery": 0,
    "picture": "\rhsusf\addons\rhsusf_inventoryicons\data\magazines\rhsusf_200Rnd_556x45_box_ca.paa",
    "scope": 1,
    "scopeArsenal": 0,
    "mass": 51.65,
    "hiddenSelections": [],
    "model": "\rhsusf\addons\rhsusf_weapons\magazines\rhs_m249_box_mag",
    "modelSpecial": "rhsusf\addons\rhsusf_weapons\mag_proxies\rhs_mag_556x45_m249_box_200rnd",
    "count": 200,
    "descriptionshort": "Caliber: 5.56x45mm M855A1 NATO<br />Rounds: 200<br />Used in: M249",
    "hiddenSelectionsTextures": ["rhsusf|addons|rhsusf_weapons|mag_proxies|data|stockpouch_m81_co.paa"],
    "reloadAction": "rhs_GestureReloadM249",
    "initSpeed": 960,
    "modelSpecialIsProxy": 1,
    "value": 1,
    "useAction": 0,
    "useActionTitle": "",
    "type": 256,
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}