rhsgref_20rnd_765x17_vz61 = {
    "dlc": "RHS_SAF",
    "author": "Red Hammer Studios",
    "mass": 5.5,
    "scope": 2,
    "scopeCurator": 2,
    "displayName": "20rnd Scorpion 7.65x17mm",
    "descriptionShort": "20rnd 7.65x17mm mag for Scorpion",
    "picture": "\rhssaf\addons\rhssaf_c_weapons\icons\m_scorpion.paa",
    "ammo": "rhs_ammo_9x17",
    "count": 20,
    "initSpeed": 320,
    "model": "\rhssaf\addons\rhssaf_m_weapon_scorpion\magazine\rhs_20rnd_scorpion_mag",
    "modelSpecial": "\rhssaf\addons\rhssaf_m_weapon_scorpion\mag_proxies\rhs_mag_765x17_scorpion_20rnd",
    "modelSpecialIsProxy": 1,
    "value": 1,
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "type": 256,
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "displayNameShort": "",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}