rhsgref_30rnd_556x45_m21 = {
    "magazineGroup": ["rhs_m21_mag_group"],
    "dlc": "RHS_SAF",
    "author": "Red Hammer Studios",
    "scope": 2,
    "scopeCurator": 2,
    "displayName": "30rnd M21 M855",
    "displaynameshort": "M855",
    "picture": "\rhssaf\addons\rhssaf_c_weapons\icons\m_m21mag_icon_ca.paa",
    "ammo": "rhs_ammo_556x45_M855_Ball",
    "count": 30,
    "initSpeed": 925,
    "mass": 10.35,
    "tracersEvery": 0,
    "lastRoundsTracer": 0,
    "descriptionshort": "Caliber: 5.56x45mm <br />Rounds: 30<br />Used in: M21 Series Rifles",
    "model": "\rhssaf\addons\rhssaf_m_weapon_m21\magazine\rhs_30rnd_m21_mag",
    "value": 1,
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "type": 256,
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}