rhsgref_50Rnd_792x57_SmE_drum = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "scopeCurator": 2,
    "displayName": "50Rnd 7.92x57 Drum S.m.E.",
    "model": "\rhsgref\addons\rhsgref_weapons2\magazines\rhs_mg42_50rnd_drum",
    "modelSpecial": "rhsgref\addons\rhsgref_weapons\mag_proxies\rhs_mag_792x57_drum_50rnd",
    "modelSpecialIsProxy": 1,
    "picture": "\rhsgref\addons\rhsgref_weapons2\icons\rhs_inv_mg42_drum_mag_ca.paa",
    "ammo": "rhs_ammo_792x57_Ball",
    "count": 50,
    "initSpeed": 770,
    "tracersEvery": 5,
    "lastRoundsTracer": 0,
    "descriptionShort": "7.92x57 ball rounds rounds in a 50Rnd drum, with a daytime tracer every 5 rounds.",
    "mass": 17.8,
    "value": 1,
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "type": 256,
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "displayNameShort": "",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}