rhsgref_5Rnd_762x54_m38 = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "displayName": "5rnd 7.62x54Rmm clip",
    "model": "\rhsgref\addons\rhsgref_weapons\m38\762x54clip",
    "picture": "\A3\Weapons_F_EPA\Data\ui\M_5rnd_127x108_ball_CA.paa",
    "ammo": "rhs_B_762x54_Ball",
    "count": 5,
    "initSpeed": 823,
    "tracersEvery": 0,
    "lastRoundsTracer": 0,
    "descriptionShort": "Caliber: 7.62x54Rmm<br />Rounds: 5<br />Used in: Mosin Nagant M38",
    "mass": 2.64,
    "value": 1,
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "type": 256,
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "displayNameShort": "",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}