rhsgref_5Rnd_792x57_kar98k = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "displayName": "5rnd 7.92x57mm clip",
    "model": "\rhsgref\addons\rhsgref_weapons\kar98k\792x57clip",
    "picture": "\A3\Weapons_F_EPA\Data\ui\M_5rnd_127x108_ball_CA.paa",
    "ammo": "rhs_ammo_792x57_Ball",
    "count": 5,
    "initSpeed": 869,
    "tracersEvery": 0,
    "lastRoundsTracer": 0,
    "descriptionShort": "Caliber: 7.92x57mm<br />Rounds: 5<br />Used in: Karabiner 98 Kurz",
    "mass": 2.97,
    "value": 1,
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "type": 256,
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "displayNameShort": "",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}