rhsgref_30rnd_1143x23_M1911B_SMG = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "scopeCurator": 2,
    "type": 16,
    "displayName": "30Rnd .45ACP M1911",
    "picture": "\rhsgref\addons\rhsgref_weapons2\icons\rhs_inv_m3a1mag_01_ca.paa",
    "ammo": "rhs_ammo_45ACP_MHP",
    "count": 30,
    "initSpeed": 280,
    "tracersEvery": 0,
    "lastRoundsTracer": 0,
    "descriptionShort": ".45ACP ball rounds in 30Rnd magazine.",
    "model": "\rhsgref\addons\rhsgref_weapons2\magazines\rhs_m3a1_mag.p3d",
    "modelSpecial": "rhsgref\addons\rhsgref_weapons\mag_proxies\rhs_mag_1143x23_m3_30rnd",
    "modelSpecialIsProxy": 1,
    "mass": 17.47,
    "value": 1,
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "displayNameShort": "",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}