rhsusf_20Rnd_762x51_m118_special_Mag = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "displayName": "20rnd M14 M118",
    "displayNameShort": "M118 Ball",
    "picture": "\A3\weapons_f\data\UI\M_20Rnd_762x51_CA.paa",
    "model": "\rhsusf\addons\rhsusf_weapons\magazines\rhs_m14_mag",
    "modelSpecial": "rhsusf\addons\rhsusf_weapons\mag_proxies\rhs_mag_762x51_M14_20rnd",
    "modelSpecialIsProxy": 1,
    "count": 20,
    "ammo": "rhs_ammo_762x51_M118_Special_Ball",
    "mass": 16.24,
    "initSpeed": 805,
    "descriptionShort": "Caliber: 7.62x51mm NATO<br />Rounds: 20<br />Used in: M14 Series Rifles",
    "value": 1,
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "type": 256,
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}