rhsusf_100Rnd_762x51_m80a1epr = {
    "author": "Red Hammer Studios",
    "picture": "\rhsusf\addons\rhsusf_inventoryicons\data\magazines\rhsusf_100Rnd_762x51_m80a1epr_ca.paa",
    "displayname": "100rnd M240 Box M80A1 EPR",
    "displayNameShort": "M80A1 EPR",
    "descriptionshort": "Caliber: 7.62x51mm NATO<br />Rounds: 100<br />Used in: M240",
    "count": 100,
    "mass": 32.34,
    "lastroundstracer": 0,
    "model": "\rhsusf\addons\rhsusf_weapons\magazines\rhs_m240_mag",
    "modelSpecial": "rhsusf\addons\rhsusf_weapons\mag_proxies\rhs_mag_762x51_m240_pouch_100rnd",
    "ammo": "rhs_ammo_762x51_M80A1EPR_Ball",
    "initSpeed": 803,
    "scope": 2,
    "type": "2*		256",
    "tracersEvery": 5,
    "modelSpecialIsProxy": 1,
    "value": 1,
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}