rhsusf_5Rnd_300winmag_xm2010 = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "displayName": "5rnd .300WM Mk248 MOD 1",
    "displaynameshort": ".300 Win Mag",
    "model": "\rhsusf\addons\rhsusf_weapons\magazines\rhs_win_mag",
    "picture": "\A3\Weapons_F_EPA\Data\ui\M_5rnd_127x108_ball_CA.paa",
    "ammo": "rhsusf_B_300winmag",
    "count": 5,
    "initSpeed": 869,
    "tracersEvery": 0,
    "lastRoundsTracer": 0,
    "descriptionShort": "Caliber: .300 Winchester Magnum<br/>Rounds: 5<br/>Used in: XM2010",
    "mass": 1.56,
    "value": 1,
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "type": 256,
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}