rhsusf_mag_7x45acp_MHP = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "type": 16,
    "displayName": "7rnd M1911 HP",
    "picture": "\rhsusf\addons\rhsusf_weapons\icons\mag_45acp_ca.paa",
    "ammo": "rhs_ammo_45ACP_MHP",
    "count": 7,
    "mass": 5.28,
    "initSpeed": 280,
    "tracersEvery": 0,
    "lastRoundsTracer": 0,
    "descriptionShort": "Caliber: .45ACP<br/>Rounds: 7<br/>Used in: M1911A1",
    "model": "\rhsusf\addons\rhsusf_weapons\magazines\rhs_7rnd_m1911_mag",
    "value": 1,
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "displayNameShort": "",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}