rhs_weap_t5000 = {
    "author": "Red Hammer Studios",
    "picture": "rhsafrf|addons|rhs_inventoryicons|data|weapons|rhs_weap_t5000_ca.paa",
    "scope": 2,
    "displayName": "T-5000",
    "descriptionShort": "T-5000",
    "model": "rhsafrf|addons|rhs_weapons3|orsis|rhs_t5000.p3d",
    "UiPicture": "A3|weapons_f|data|UI|icon_regular_CA.paa",
    "handAnim": ["OFP2_ManSkeleton","|rhsafrf|addons|rhs_c_weapons|anims|rhs_hand_orsis.rtm"],
    "weaponInfoType": "rhs_orsis_handler",
    # Class: CfgWeapons\rhs_weap_t5000\WeaponSlotsInfo,
    "WeaponSlotsInfo": {
        "mass": 132.2,
        # Class: CfgWeapons\rhs_weap_orsis_Base_F\WeaponSlotsInfo\CowsSlot,
        "CowsSlot": {
            "iconPosition": [0,0],
            "iconScale": 1,
            "iconPicture": "A3|Weapons_F|Data|clear_empty.paa",
            "iconPinPoint": "Left",
            "linkProxy": "A3|data_f|proxies|weapon_slots|TOP",
            "displayName": "Optics Slot",
            # Class: asdg_OpticRail1913\compatibleItems,
            "compatibleItems": {
                "rhs_acc_rakursPM": 1,
                "rhs_acc_dh520x56": 1,
                "rhs_acc_ekp8_18": 1,
                "rhs_acc_ekp8_18b": 1,
                "rhs_acc_ekp8_18c": 1,
                "rhs_acc_ekp8_18d": 1,
                "rhs_acc_1p87": 1,
                "rhs_acc_okp7_picatinny": 1,
                "optic_Nightstalker": 1,
                "optic_tws": 1,
                "optic_tws_mg": 1,
                "optic_NVS": 1,
                "optic_SOS": 1,
                "optic_SOS_khk_F": 1,
                "optic_MRCO": 1,
                "optic_Arco": 1,
                "optic_Arco_ghex_F": 1,
                "optic_Arco_blk_F": 1,
                "optic_aco": 1,
                "optic_ACO_grn": 1,
                "optic_aco_smg": 1,
                "optic_ACO_grn_smg": 1,
                "optic_hamr": 1,
                "optic_Hamr_khk_F": 1,
                "optic_Holosight": 1,
                "optic_Holosight_smg": 1,
                "optic_Holosight_blk_F": 1,
                "optic_Holosight_khk_F": 1,
                "optic_Holosight_smg_blk_F": 1,
                "optic_DMS": 1,
                "optic_DMS_ghex_F": 1,
                "optic_LRPS": 1,
                "optic_LRPS_ghex_F": 1,
                "optic_LRPS_tna_F": 1,
                "optic_AMS": 1,
                "optic_AMS_khk": 1,
                "optic_AMS_snd": 1,
                "optic_KHS_blk": 1,
                "optic_KHS_hex": 1,
                "optic_KHS_old": 1,
                "optic_KHS_tan": 1,
                "optic_ERCO_blk_F": 1,
                "optic_ERCO_khk_F": 1,
                "optic_ERCO_snd_F": 1,
                "rhsusf_acc_LEUPOLDMK4": 1,
                "rhsusf_acc_LEUPOLDMK4_d": 1,
                "rhsusf_acc_LEUPOLDMK4_wd": 1,
                "rhsusf_acc_LEUPOLDMK4_2": 1,
                "rhsusf_acc_LEUPOLDMK4_2_MRDS": 1,
                "rhsusf_acc_LEUPOLDMK4_2_d": 1,
                "rhsusf_acc_premier": 1,
                "rhsusf_acc_premier_mrds": 1,
                "rhsusf_acc_premier_low": 1,
                "rhsusf_acc_M8541": 1,
                "rhsusf_acc_M8541_mrds": 1,
                "rhsusf_acc_M8541_low": 1,
                "rhsusf_acc_M8541_low_d": 1,
                "rhsusf_acc_M8541_low_wd": 1,
                "rhsusf_acc_EOTECH": 1,
                "rhsusf_acc_eotech_552": 1,
                "rhsusf_acc_eotech_552_d": 1,
                "rhsusf_acc_eotech_552_wd": 1,
                "rhsusf_acc_eotech_xps3": 1,
                "rhsusf_acc_g33_xps3": 1,
                "rhsusf_acc_g33_xps3_flip": 1,
                "rhsusf_acc_g33_xps3_tan": 1,
                "rhsusf_acc_g33_xps3_tan_flip": 1,
                "rhsusf_acc_g33_t1": 1,
                "rhsusf_acc_g33_t1_flip": 1,
                "rhsusf_acc_compm4": 1,
                "rhsusf_acc_T1_high": 1,
                "rhsusf_acc_T1_low": 1,
                "rhsusf_acc_RX01": 1,
                "rhsusf_acc_RX01_NoFilter": 1,
                "rhsusf_acc_RX01_tan": 1,
                "rhsusf_acc_RX01_NoFilter_tan": 1,
                "rhsusf_acc_RM05": 1,
                "rhsusf_acc_mrds": 1,
                "rhsusf_acc_mrds_c": 1,
                "rhsusf_acc_ACOG": 1,
                "rhsusf_acc_ACOG2": 1,
                "rhsusf_acc_ACOG3": 1,
                "rhsusf_acc_ACOG_wd": 1,
                "rhsusf_acc_ACOG_d": 1,
                "rhsusf_acc_ACOG_sa": 1,
                "rhsusf_acc_ACOG_USMC": 1,
                "rhsusf_acc_ACOG2_USMC": 1,
                "rhsusf_acc_ACOG3_USMC": 1,
                "rhsusf_acc_ACOG_RMR": 1,
                "rhsusf_acc_ACOG_PIP": 1,
                "rhsusf_acc_ACOG2_pip": 1,
                "rhsusf_acc_ACOG3_pip": 1,
                "rhsusf_acc_ACOG_wd_pip": 1,
                "rhsusf_acc_ACOG_d_pip": 1,
                "rhsusf_acc_ACOG_sa_pip": 1,
                "rhsusf_acc_ACOG_USMC_pip": 1,
                "rhsusf_acc_ACOG2_USMC_pip": 1,
                "rhsusf_acc_ACOG3_USMC_pip": 1,
                "rhsusf_acc_ACOG_RMR_PIP": 1,
                "rhsusf_acc_ACOG_3d": 1,
                "rhsusf_acc_ACOG2_3d": 1,
                "rhsusf_acc_ACOG3_3d": 1,
                "rhsusf_acc_ACOG_wd_3d": 1,
                "rhsusf_acc_ACOG_d_3d": 1,
                "rhsusf_acc_ACOG_sa_3d": 1,
                "rhsusf_acc_ACOG_USMC_3d": 1,
                "rhsusf_acc_ACOG2_USMC_3d": 1,
                "rhsusf_acc_ACOG3_USMC_3d": 1,
                "rhsusf_acc_ACOG_RMR_3d": 1,
                "rhsusf_acc_ELCAN": 1,
                "rhsusf_acc_ELCAN_ard": 1,
                "rhsusf_acc_ELCAN_3d": 1,
                "rhsusf_acc_ELCAN_ard_3d": 1,
                "rhsusf_acc_ELCAN_PIP": 1,
                "rhsusf_acc_ELCAN_ard_PIP": 1,
                "rhsusf_acc_su230": 1,
                "rhsusf_acc_su230_mrds": 1,
                "rhsusf_acc_su230a": 1,
                "rhsusf_acc_su230a_mrds": 1,
                "rhsusf_acc_su230_c": 1,
                "rhsusf_acc_su230_mrds_c": 1,
                "rhsusf_acc_su230a_c": 1,
                "rhsusf_acc_su230a_mrds_c": 1,
                "rhsusf_acc_su230_3d": 1,
                "rhsusf_acc_su230_mrds_3d": 1,
                "rhsusf_acc_su230a_3d": 1,
                "rhsusf_acc_su230a_mrds_3d": 1,
                "rhsusf_acc_su230_c_3d": 1,
                "rhsusf_acc_su230_mrds_c_3d": 1,
                "rhsusf_acc_su230a_c_3d": 1,
                "rhsusf_acc_su230a_mrds_c_3d": 1,
                "rhsusf_acc_SpecterDR": 1,
                "rhsusf_acc_SpecterDR_3d": 1,
                "rhsusf_acc_SpecterDR_A": 1,
                "rhsusf_acc_SpecterDR_A_3d": 1,
                "rhsusf_acc_SpecterDR_CX": 1,
                "rhsusf_acc_SpecterDR_CX_3D": 1,
                "rhsusf_acc_SpecterDR_pvs27": 1,
                "rhsusf_acc_SpecterDR_D": 1,
                "rhsusf_acc_SpecterDR_OD": 1,
                "rhsusf_acc_SpecterDR_D_3D": 1,
                "rhsusf_acc_SpecterDR_OD_3D": 1,
                "rhsusf_acc_anpvs27": 1,
                "rhsusf_acc_anpas13gv1": 1,
                "rhsusf_acc_M2A1": 1,
                "rhsusf_acc_ACOG_MDO": 1,
                "rhsgref_acc_RX01_camo": 1,
                "rhsgref_acc_RX01_NoFilter_camo": 1
            }
        },
        # Class: CfgWeapons\rhs_weap_orsis_Base_F\WeaponSlotsInfo\PointerSlot,
        "PointerSlot": {
        },
        # Class: CfgWeapons\rhs_weap_orsis_Base_F\WeaponSlotsInfo\UnderBarrelSlot,
        "UnderBarrelSlot": {
            "iconPosition": [0,0],
            "iconScale": 1,
            "iconPicture": "A3|Weapons_F|Data|clear_empty.paa",
            "iconPinPoint": "Left",
            # Class: rhs_russian_rifle_underbarrel_slot\compatibleItems,
            "compatibleItems": {
                "rhs_acc_harris_swivel": 1,
                "bipod_01_F_snd": 1,
                "bipod_01_F_blk": 1,
                "bipod_01_F_mtp": 1,
                "bipod_02_F_blk": 1,
                "bipod_02_F_tan": 1,
                "bipod_02_F_hex": 1,
                "bipod_03_F_blk": 1,
                "bipod_03_F_oli": 1,
                "bipod_01_F_khk": 1,
                "rhsusf_acc_harris_bipod": 1
            },
            "linkProxy": "a3|data_f_mark|Proxies|Weapon_Slots|UNDERBARREL"
        },
        # Class: CfgWeapons\Rifle\WeaponSlotsInfo\MuzzleSlot,
        "MuzzleSlot": {
            "linkProxy": "A3|data_f|proxies|weapon_slots|MUZZLE",
            "displayName": "$str_a3_cfgweapons_abr_base_f_weaponslotsinfo_muzzleslot0",
            "compatibleItems": [],
            "iconPicture": "A3|Weapons_F|Data|UI|attachment_muzzle.paa",
            "iconPinpoint": "Center",
            "access": 1,
            "scope": 0,
            "iconPosition": [0,0],
            "iconScale": 0
        },
        "allowedSlots": [901]
    },
    # Class: CfgWeapons\rhs_weap_t5000\ItemInfo,
    "ItemInfo": {
        "priority": 1,
        "RMBhint": "T-5000",
        "onHoverText": "T-5000 .338 sniper rifle"
    },
    "baseWeapon": "rhs_weap_t5000",
    "dlc": "RHS_AFRF",
    "magazines": ["rhs_5Rnd_338lapua_t5000"],
    "magazineWell": ["CBA_338LM_T5000"],
    # Class: CfgWeapons\rhs_weap_orsis_Base_F\Library,
    "Library": {
        "libTextDesc": ""
    },
    "optics": 0,
    "reloadAction": "RHS_GestureReloadOrsis",
    "maxRecoilSway": 0.0125,
    "swayDecaySpeed": 1.25,
    "recoil": "rhs_recoil_orsis",
    # Class: CfgWeapons\rhs_weap_orsis_Base_F\GunParticles,
    "GunParticles": {
        # Class: CfgWeapons\rhs_weap_orsis_Base_F\GunParticles\SecondEffect
        "SecondEffect": {
            "positionName": "Nabojnicestart",
            "directionName": "Nabojniceend",
            "effectName": "RifleAssaultCloud"
        },
        # Class: CfgWeapons\rhs_weap_orsis_Base_F\GunParticles\RHS_BarrelRefract,
        "RHS_BarrelRefract": {
            "positionName": "usti hlavne",
            "directionName": "usti hlavne up",
            "effectName": "RHS_BarrelRefract"
        },
        # Class: CfgWeapons\Rifle_Base_F\GunParticles\FirstEffect,
        "FirstEffect": {
            "effectName": "RifleAssaultCloud",
            "positionName": "Usti hlavne",
            "directionName": "Konec hlavne"
        }
    },
    "discreteDistance": [100],
    "discreteDistanceInitIndex": 0,
    "maxZeroing": 1800,
    "opticsZoomMin": 0.275,
    "opticsZoomMax": 1.1,
    "opticsZoomInit": 0.75,
    "distanceZoomMin": 300,
    "distanceZoomMax": 300,
    "inertia": 0.65,
    "dexterity": 1.8,
    "aimTransitionSpeed": 0.5,
    "caseless": ["",1,1,1],
    "soundBullet": ["caseless",1],
    "modes": ["Single","far_optic1","medium_optic2","far_optic2"],
    # Class: CfgWeapons\rhs_weap_orsis_Base_F\Single,
    "Single": {
        "reloadTime": 1.6,
        "dispersion": 0.0002909,
        "minRange": 2,
        "minRangeProbab": 0.3,
        "midRange": 250,
        "midRangeProbab": 0.7,
        "maxRange": 400,
        "maxRangeProbab": 0.04,
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons\rhs_weap_orsis_Base_F\Single\StandardSound,
        "StandardSound": {
            "soundSetShot": ["RHS_orsis_Shot_SoundSet","RHS_rifle2_Tail_SoundSet"]
        },
        # Class: CfgWeapons\rhs_weap_orsis_Base_F\Single\SilencedSound,
        "SilencedSound": {
            "soundSetShot": ["RHS_sd_orsis_Shot_SoundSet","RHS_sd_mmg1_Tail_SoundSet"]
        },
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "requiredOpticType": -1,
        "aiRateOfFire": 2,
        "aiRateOfFireDispersion": 1,
        "aiRateOfFireDistance": 500
    },
    # Class: CfgWeapons\rhs_weap_orsis_Base_F\far_optic1,
    "far_optic1": {
        "showToPlayer": 0,
        "minRange": 150,
        "minRangeProbab": 0.1,
        "midRange": 500,
        "midRangeProbab": 0.7,
        "maxRange": 1000,
        "maxRangeProbab": 0.3,
        "aiRateOfFire": 5,
        "aiRateOfFireDistance": 700,
        "requiredOpticType": 1,
        "reloadTime": 1.6,
        "dispersion": 0.0002909,
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons\rhs_weap_orsis_Base_F\Single\StandardSound,
        "StandardSound": {
            "soundSetShot": ["RHS_orsis_Shot_SoundSet","RHS_rifle2_Tail_SoundSet"]
        },
        # Class: CfgWeapons\rhs_weap_orsis_Base_F\Single\SilencedSound,
        "SilencedSound": {
            "soundSetShot": ["RHS_sd_orsis_Shot_SoundSet","RHS_sd_mmg1_Tail_SoundSet"]
        },
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons\rhs_weap_orsis_Base_F\medium_optic2,
    "medium_optic2": {
        "showToPlayer": 0,
        "minRange": 250,
        "minRangeProbab": 0.1,
        "midRange": 750,
        "midRangeProbab": 0.7,
        "maxRange": 1000,
        "maxRangeProbab": 0.3,
        "aiRateOfFire": 6,
        "aiRateOfFireDistance": 1000,
        "requiredOpticType": 2,
        "reloadTime": 1.6,
        "dispersion": 0.0002909,
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons\rhs_weap_orsis_Base_F\Single\StandardSound,
        "StandardSound": {
            "soundSetShot": ["RHS_orsis_Shot_SoundSet","RHS_rifle2_Tail_SoundSet"]
        },
        # Class: CfgWeapons\rhs_weap_orsis_Base_F\Single\SilencedSound,
        "SilencedSound": {
            "soundSetShot": ["RHS_sd_orsis_Shot_SoundSet","RHS_sd_mmg1_Tail_SoundSet"]
        },
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons\rhs_weap_orsis_Base_F\far_optic2,
    "far_optic2": {
        "minRange": 500,
        "minRangeProbab": 0.1,
        "midRange": 1050,
        "midRangeProbab": 0.7,
        "maxRange": 2000,
        "maxRangeProbab": 0.3,
        "aiRateOfFire": 8,
        "aiRateOfFireDistance": 2000,
        "requiredOpticType": 2,
        "showToPlayer": 0,
        "reloadTime": 1.6,
        "dispersion": 0.0002909,
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons\rhs_weap_orsis_Base_F\Single\StandardSound,
        "StandardSound": {
            "soundSetShot": ["RHS_orsis_Shot_SoundSet","RHS_rifle2_Tail_SoundSet"]
        },
        # Class: CfgWeapons\rhs_weap_orsis_Base_F\Single\SilencedSound,
        "SilencedSound": {
            "soundSetShot": ["RHS_sd_orsis_Shot_SoundSet","RHS_sd_mmg1_Tail_SoundSet"]
        },
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "aiRateOfFireDispersion": 1
    },
    "aiDispersionCoefY": 10,
    "aiDispersionCoefX": 8,
    "drySound": ["A3|sounds_f|weapons|Other|dry_1",0.01,1],
    "reloadMagazineSound": ["rhsafrf|addons|rhs_sounds|t5000|reload",1.2,1,15],
    "hiddenSelections": ["Camo"],
    "hiddenSelectionsTextures": ["|rhsafrf|addons|rhs_weapons3|orsis|data|t5000_co.paa"],
    "muzzles": ["this","SAFE"],
    # Class: CfgWeapons\rhs_weap_orsis_Base_F\SAFE,
    "SAFE": {
        "showToPlayer": 0,
        "magazines": [],
        "displayName": "SAFE",
        "descriptionShort": "SAFE",
        "modes": ["Safe"],
        "discreteDistance": [0],
        "discreteDistanceInitIndex": 0,
        "drySound": ["A3|Sounds_F|arsenal|weapons|Rifles|MX|dry_Mx",0.562341,1,10],
        "changeFiremodeSound": ["A3|sounds_f|weapons|closure|firemode_changer_2",0.551189,1,5],
        # Class: CfgWeapons\RHS_SAFE_BASE\Safe,
        "Safe": {
            "sounds": [],
            "displayName": "SAFE",
            "descriptionShort": "SAFE",
            "showToPlayer": 0,
            "minRange": 0,
            "minRangeProbab": 0.001,
            "midRange": 0.001,
            "midRangeProbab": 0.001,
            "maxRange": 0.001,
            "maxRangeProbab": 0.001,
            "multiplier": 1,
            "burst": 1,
            "burstRangeMax": -1,
            "dispersion": 0.0002,
            "sound": ["",10,1],
            "soundBegin": ["sound",1],
            "soundBeginWater": ["sound",1],
            "soundClosure": ["sound",1],
            "soundEnd": [],
            "soundLoop": [],
            "soundContinuous": 0,
            "weaponSoundEffect": "",
            "reloadTime": 0.1,
            "ffCount": 1,
            "ffMagnitude": 0.5,
            "ffFrequency": 11,
            "flash": "gunfire",
            "flashSize": 0.1,
            "autoFire": 0,
            "useAction": 0,
            "useActionTitle": "",
            "artilleryDispersion": 1,
            "artilleryCharge": 1,
            "canShootInWater": 0,
            "textureType": "semi",
            "recoil": "recoil_single_primary_3outof10",
            "recoilProne": "recoil_single_primary_prone_3outof10",
            "aiDispersionCoefY": 1.7,
            "aiDispersionCoefX": 1.4,
            "soundBurst": 0,
            "requiredOpticType": -1,
            "aiRateOfFire": 2,
            "aiRateOfFireDispersion": 1,
            "aiRateOfFireDistance": 500
        },
        "scope": 0,
        "weaponInfoType": "RscWeaponZeroing",
        "recoil": "recoil_default",
        "deployedPivot": "bipod",
        # Class: CfgWeapons\Rifle_Base_F\GunParticles,
        "GunParticles": {
            # Class: CfgWeapons\Rifle_Base_F\GunParticles\FirstEffect
            "FirstEffect": {
                "effectName": "RifleAssaultCloud",
                "positionName": "Usti hlavne",
                "directionName": "Konec hlavne"
            }
        },
        "htMin": 1,
        "htMax": 600,
        "afMax": 0,
        "mfMax": 0,
        "mFact": 1,
        "tBody": 100,
        "autoFire": 1,
        "reloadAction": "ReloadMagazine",
        "soundContinuous": 0,
        "optics": 0,
        "cursor": "arifle",
        "cursoraim": "CursorAim",
        "value": 4,
        "nameSound": "rifle",
        "reloadTime": 0.15,
        "modelOptics": "-",
        "sound": [],
        "opticsFlare": 0,
        "autoReload": 0,
        "aiDispersionCoefX": 6,
        "aiDispersionCoefY": 6,
        "opticsZoomMin": 0.25,
        "opticsZoomMax": 1.25,
        "opticsZoomInit": 0.75,
        "distanceZoomMin": 300,
        "distanceZoomMax": 300,
        "maxLeadSpeed": 23,
        "canLock": 0,
        "flash": "gunfire",
        "flashSize": 0.5,
        "dispersion": 0.00029,
        "recoilProne": "assaultRifleBase",
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "ffCount": 3,
        "weaponPoolAvailable": 1,
        "maxZeroing": 1000,
        # Class: CfgWeapons\Rifle\WeaponSlotsInfo,
        "WeaponSlotsInfo": {
            "mass": 2,
            # Class: CfgWeapons\Rifle\WeaponSlotsInfo\MuzzleSlot,
            "MuzzleSlot": {
                "linkProxy": "A3|data_f|proxies|weapon_slots|MUZZLE",
                "displayName": "$str_a3_cfgweapons_abr_base_f_weaponslotsinfo_muzzleslot0",
                "compatibleItems": [],
                "iconPicture": "A3|Weapons_F|Data|UI|attachment_muzzle.paa",
                "iconPinpoint": "Center",
                "access": 1,
                "scope": 0,
                "iconPosition": [0,0],
                "iconScale": 0
            },
            # Class: CfgWeapons\Rifle\WeaponSlotsInfo\CowsSlot,
            "CowsSlot": {
                "compatibleItems": ["optic_Nightstalker","optic_tws","optic_tws_mg","optic_NVS","optic_DMS","optic_LRPS","optic_ams","optic_AMS_snd","optic_AMS_khk","optic_KHS_blk","optic_KHS_tan","optic_KHS_hex","optic_KHS_old","optic_SOS","optic_MRCO","optic_Arco","optic_aco","optic_ACO_grn","optic_aco_smg","optic_ACO_grn_smg","optic_hamr","optic_Holosight","optic_Holosight_smg","optic_Hamr_khk_F","optic_SOS_khk_F","optic_Arco_ghex_F","optic_Arco_blk_F","optic_DMS_ghex_F","optic_ERCO_blk_F","optic_ERCO_khk_F","optic_ERCO_snd_F","optic_LRPS_ghex_F","optic_LRPS_tna_F","optic_Holosight_blk_F","optic_Holosight_khk_F","optic_Holosight_smg_blk_F","optic_Holosight_smg_khk_F","optic_Arco_AK_blk_F","optic_Arco_AK_lush_F","optic_Arco_AK_arid_F","optic_DMS_weathered_F","optic_DMS_weathered_Kir_F","optic_Arco_lush_F","optic_Arco_arid_F","optic_Holosight_lush_F","optic_Holosight_arid_F"],
                "linkProxy": "A3|data_f|proxies|weapon_slots|TOP",
                "displayName": "Optics Slot",
                "iconPicture": "A3|Weapons_F|Data|UI|attachment_top.paa",
                "iconPinpoint": "Bottom",
                "access": 1,
                "scope": 0,
                "iconPosition": [0,0],
                "iconScale": 0
            },
            # Class: CfgWeapons\Rifle\WeaponSlotsInfo\PointerSlot,
            "PointerSlot": {
                "compatibleItems": ["acc_flashlight","acc_pointer_IR"],
                "iconPicture": "A3|Weapons_F|Data|UI|attachment_side.paa",
                "iconPinpoint": "Center",
                "linkProxy": "A3|data_f|proxies|weapon_slots|SIDE",
                "displayName": "Pointer Slot",
                "access": 1,
                "scope": 0,
                "iconPosition": [0,0],
                "iconScale": 0
            },
            "allowedSlots": [901]
        },
        "zeroingSound": ["A3|Sounds_F|arsenal|sfx|shared|zeroing_knob_tick_metal",0.316228,1,5],
        "type": 1,
        "dexterity": 1.7,
        "aiRateOfFire": 0.5,
        "aiRateOfFireDistance": 500,
        "inertia": 0.5,
        "access": 3,
        "picture": "",
        "uiPicture": "",
        "ammo": "",
        "cursorSize": 1,
        "showAimCursorInternal": 1,
        "cursorAimOn": "",
        "laser": 0,
        "hiddenSelections": [],
        "hiddenSelectionsTextures": [],
        "hiddenUnderwaterSelections": [],
        "shownUnderwaterSelections": [],
        "hiddenUnderwaterSelectionsTextures": [],
        "simulation": "Weapon",
        "count": 0,
        "multiplier": 1,
        "burst": 1,
        "magazineReloadTime": 0,
        "magazineReloadSwitchPhase": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": ["sound",1],
        "soundLoop": ["sound",1],
        "weaponSoundEffect": "",
        "soundBurst": 1,
        "reloadSound": ["",1,1],
        "reloadMagazineSound": ["",1,1],
        "emptySound": ["",1,1],
        "soundBullet": ["emptySound",1],
        "initSpeed": 0,
        "ballisticsComputer": 0,
        "irDistance": 0,
        "irDotIntensity": 0.001,
        "lockAcquire": 1,
        "enableAttack": 1,
        "maxRecoilSway": 0.008,
        "swayDecaySpeed": 2,
        "model": "",
        "modelSpecial": "",
        "modelMagazine": "",
        "muzzlePos": "usti hlavne",
        "muzzleEnd": "konec hlavne",
        "irLaserPos": "laser pos",
        "irLaserEnd": "laser dir",
        "cartridgePos": "nabojnicestart",
        "cartridgeVel": "nabojniceend",
        "selectionFireAnim": "zasleh",
        "memoryPointCamera": "eye",
        "fireSpreadAngle": 3,
        "useModelOptics": 1,
        "opticsID": 0,
        "opticsPPEffects": [],
        "forceOptics": 0,
        "useAsBinocular": 0,
        "opticsDisablePeripherialVision": 0.67,
        "primary": 10,
        "showSwitchAction": 0,
        "showEmpty": 1,
        "canShootInWater": 0,
        "aiRateOfFireDispersion": 0,
        "fireLightDuration": 0.05,
        "fireLightIntensity": 0.2,
        "fireLightDiffuse": [0.937,0.631,0.259],
        "fireLightAmbient": [0,0,0],
        # Class: CfgWeapons\Default\Eventhandlers,
        "Eventhandlers": {
        },
        "backgroundReload": 0,
        "muzzles": ["this"],
        "useAction": 0,
        "useActionTitle": "",
        "canDrop": 1,
        "weaponLockDelay": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "weight": 0,
        "minRange": 1,
        "minRangeProbab": 0.3,
        "midRange": 150,
        "midRangeProbab": 0.58,
        "maxRange": 500,
        "maxRangeProbab": 0.04,
        "handAnim": [],
        "lockingTargetSound": ["",0.000316228,2],
        "lockedTargetSound": ["",0.000316228,6],
        "detectRange": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "fireAnims": [],
        # Class: CfgWeapons\Default\Library,
        "Library": {
            "libTextDesc": ""
        },
        # Class: CfgWeapons\Default\GunFire,
        "GunFire": {
            "access": 0,
            "cloudletDuration": 0.2,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletAlpha": 1,
            "cloudletGrowUp": 0.2,
            "cloudletFadeIn": 0.01,
            "cloudletFadeOut": 0.5,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "cloudletShape": "cloudletFire",
            "cloudletColor": [1,1,1,0],
            "cloudletDensityCoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourceSize": 0.5,
            "timeToLive": 0,
            "initT": 4500,
            "deltaT": -3000,
            # Class: CfgWeapons\Default\GunFire\Table,
            "Table": {
                # Class: CfgWeapons\Default\GunFire\Table\T0
                "T0": {
                    "maxT": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T1,
                "T1": {
                    "maxT": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T2,
                "T2": {
                    "maxT": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T3,
                "T3": {
                    "maxT": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T4,
                "T4": {
                    "maxT": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T5,
                "T5": {
                    "maxT": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T6,
                "T6": {
                    "maxT": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T7,
                "T7": {
                    "maxT": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T8,
                "T8": {
                    "maxT": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T9,
                "T9": {
                    "maxT": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T10,
                "T10": {
                    "maxT": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T11,
                "T11": {
                    "maxT": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T12,
                "T12": {
                    "maxT": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T13,
                "T13": {
                    "maxT": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T14,
                "T14": {
                    "maxT": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T15,
                "T15": {
                    "maxT": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T16,
                "T16": {
                    "maxT": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T17,
                "T17": {
                    "maxT": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T18,
                "T18": {
                    "maxT": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T19,
                "T19": {
                    "maxT": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T20,
                "T20": {
                    "maxT": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T21,
                "T21": {
                    "maxT": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons\Default\GunFire\Table\T22,
                "T22": {
                    "maxT": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        # Class: CfgWeapons\Default\GunClouds,
        "GunClouds": {
            "access": 0,
            "cloudletGrowUp": 0.05,
            "cloudletFadeIn": 0,
            "cloudletFadeOut": 0.1,
            "cloudletDuration": 0.05,
            "cloudletAlpha": 0.3,
            "cloudletAccY": 0,
            "cloudletMinYSpeed": -100,
            "cloudletMaxYSpeed": 100,
            "interval": -0.02,
            "size": 0.3,
            "sourceSize": 0.02,
            "cloudletAnimPeriod": 1,
            "cloudletSize": 1,
            "cloudletShape": "cloudletClouds",
            "cloudletColor": [1,1,1,0],
            "timeToLive": 0,
            "initT": 0,
            "deltaT": 0,
            # Class: CfgWeapons\Default\GunClouds\Table,
            "Table": {
                # Class: CfgWeapons\Default\GunClouds\Table\T0
                "T0": {
                    "maxT": 0,
                    "color": [1,1,1,0]
                }
            }
        },
        "textureType": "default",
        "aimTransitionSpeed": 1
    },
    # Class: CfgWeapons\rhs_weap_orsis_Base_F\Eventhandlers,
    "Eventhandlers": {
        # Class: CfgWeapons\rhs_weap_orsis_Base_F\Eventhandlers\RHS_BoltAction
        "RHS_BoltAction": {
            "fired": "[_this select 0,_this select 1,_this select 1] call rhs_fnc_boltAction;"
        }
    },
    "rhs_boltActionSound": ["rhsafrf|addons|rhs_c_weapons|sounds|bolt.wss",1.42,1,20],
    "rhs_boltActionAnim": "RHS_GestureRechamberOrsis",
    "deployedPivot": "bipod",
    "htMin": 1,
    "htMax": 600,
    "afMax": 0,
    "mfMax": 0,
    "mFact": 1,
    "tBody": 100,
    "autoFire": 1,
    "soundContinuous": 0,
    "cursor": "arifle",
    "cursoraim": "CursorAim",
    "value": 4,
    "nameSound": "rifle",
    "reloadTime": 0.15,
    "modelOptics": "-",
    "sound": [],
    "opticsFlare": 0,
    "autoReload": 0,
    "maxLeadSpeed": 23,
    "canLock": 0,
    "flash": "gunfire",
    "flashSize": 0.5,
    "dispersion": 0.00029,
    "recoilProne": "assaultRifleBase",
    "ffMagnitude": 0.5,
    "ffFrequency": 11,
    "ffCount": 3,
    "weaponPoolAvailable": 1,
    "zeroingSound": ["A3|Sounds_F|arsenal|sfx|shared|zeroing_knob_tick_metal",0.316228,1,5],
    "type": 1,
    "aiRateOfFire": 0.5,
    "aiRateOfFireDistance": 500,
    "access": 3,
    "ammo": "",
    "cursorSize": 1,
    "showAimCursorInternal": 1,
    "cursorAimOn": "",
    "laser": 0,
    "hiddenUnderwaterSelections": [],
    "shownUnderwaterSelections": [],
    "hiddenUnderwaterSelectionsTextures": [],
    "simulation": "Weapon",
    "count": 0,
    "multiplier": 1,
    "burst": 1,
    "magazineReloadTime": 0,
    "magazineReloadSwitchPhase": 1,
    "soundBegin": ["sound",1],
    "soundBeginWater": ["sound",1],
    "soundClosure": ["sound",1],
    "soundEnd": ["sound",1],
    "soundLoop": ["sound",1],
    "weaponSoundEffect": "",
    "soundBurst": 1,
    "reloadSound": ["",1,1],
    "changeFiremodeSound": ["",1,1],
    "emptySound": ["",1,1],
    "initSpeed": 0,
    "ballisticsComputer": 0,
    "irDistance": 0,
    "irDotIntensity": 0.001,
    "lockAcquire": 1,
    "enableAttack": 1,
    "modelSpecial": "",
    "modelMagazine": "",
    "muzzlePos": "usti hlavne",
    "muzzleEnd": "konec hlavne",
    "irLaserPos": "laser pos",
    "irLaserEnd": "laser dir",
    "cartridgePos": "nabojnicestart",
    "cartridgeVel": "nabojniceend",
    "selectionFireAnim": "zasleh",
    "memoryPointCamera": "eye",
    "fireSpreadAngle": 3,
    "useModelOptics": 1,
    "opticsID": 0,
    "opticsPPEffects": [],
    "forceOptics": 0,
    "useAsBinocular": 0,
    "opticsDisablePeripherialVision": 0.67,
    "primary": 10,
    "showSwitchAction": 0,
    "showEmpty": 1,
    "showToPlayer": 1,
    "canShootInWater": 0,
    "aiRateOfFireDispersion": 0,
    "fireLightDuration": 0.05,
    "fireLightIntensity": 0.2,
    "fireLightDiffuse": [0.937,0.631,0.259],
    "fireLightAmbient": [0,0,0],
    "backgroundReload": 0,
    "useAction": 0,
    "useActionTitle": "",
    "canDrop": 1,
    "weaponLockDelay": 0,
    "weaponLockSystem": 0,
    "cmImmunity": 1,
    "weight": 0,
    "minRange": 1,
    "minRangeProbab": 0.3,
    "midRange": 150,
    "midRangeProbab": 0.58,
    "maxRange": 500,
    "maxRangeProbab": 0.04,
    "lockingTargetSound": ["",0.000316228,2],
    "lockedTargetSound": ["",0.000316228,6],
    "detectRange": 0,
    "artilleryDispersion": 1,
    "artilleryCharge": 1,
    "fireAnims": [],
    # Class: CfgWeapons\Default\GunFire,
    "GunFire": {
        "access": 0,
        "cloudletDuration": 0.2,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 0.2,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 0.5,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletFire",
        "cloudletColor": [1,1,1,0],
        "cloudletDensityCoef": -1,
        "interval": -0.01,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 4500,
        "deltaT": -3000,
        # Class: CfgWeapons\Default\GunFire\Table,
        "Table": {
            # Class: CfgWeapons\Default\GunFire\Table\T0
            "T0": {
                "maxT": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T1,
            "T1": {
                "maxT": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T2,
            "T2": {
                "maxT": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T3,
            "T3": {
                "maxT": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T4,
            "T4": {
                "maxT": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T5,
            "T5": {
                "maxT": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T6,
            "T6": {
                "maxT": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T7,
            "T7": {
                "maxT": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T8,
            "T8": {
                "maxT": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T9,
            "T9": {
                "maxT": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T10,
            "T10": {
                "maxT": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T11,
            "T11": {
                "maxT": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T12,
            "T12": {
                "maxT": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T13,
            "T13": {
                "maxT": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T14,
            "T14": {
                "maxT": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T15,
            "T15": {
                "maxT": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T16,
            "T16": {
                "maxT": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T17,
            "T17": {
                "maxT": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T18,
            "T18": {
                "maxT": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T19,
            "T19": {
                "maxT": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T20,
            "T20": {
                "maxT": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T21,
            "T21": {
                "maxT": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T22,
            "T22": {
                "maxT": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgWeapons\Default\GunClouds,
    "GunClouds": {
        "access": 0,
        "cloudletGrowUp": 0.05,
        "cloudletFadeIn": 0,
        "cloudletFadeOut": 0.1,
        "cloudletDuration": 0.05,
        "cloudletAlpha": 0.3,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "interval": -0.02,
        "size": 0.3,
        "sourceSize": 0.02,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletShape": "cloudletClouds",
        "cloudletColor": [1,1,1,0],
        "timeToLive": 0,
        "initT": 0,
        "deltaT": 0,
        # Class: CfgWeapons\Default\GunClouds\Table,
        "Table": {
            # Class: CfgWeapons\Default\GunClouds\Table\T0
            "T0": {
                "maxT": 0,
                "color": [1,1,1,0]
            }
        }
    },
    "textureType": "default",
}