d = {
    "ammo": "rhs_ammo_mgm164_block2_rocket",
    "author": "Bohemia Interactive",
    "count": 1,
    "descriptionshort": "ATacMS Block II, GPS/INS, \u00d713 Guided BAT",
    "displayname": "MGM-164A",
    "displaynameshort": "Cluster, Guided HEAT",
    "hardpoints": [],
    "initspeed": 850,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 8,
    "maxleadspeed": 100,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "rhsusf/addons/rhsusf_himars/M142_ATACMS_Pod",
    "modelspecial": "",
    "namesound": "rockets",
    "picture": "",
    "pylonweapon": "rhs_weap_atacms",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "type": 0,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 0,
    "weight": 0
}