rhs_m136_hedp_mag = {
    "author": "Red Hammer Studios",
    "displayName": "M136 HEDP",
    "descriptionshort": "Type: High Explosive, Dual Purpose",
    # Ammo: rhs_ammo_M136_hedp_rocket,
    "ammo": {
        "ammo": "rhs_ammo_M136_hedp_rocket",
        "submunitionAmmo": "rhs_ammo_M136_hedp_penetrator",
        "submunitionDirectionType": "SubmunitionModelDirection",
        "submunitionInitialOffset": [0,0,-0.2],
        "submunitionParentSpeedCoef": 0,
        "submunitionInitSpeed": 1000,
        "triggerOnImpact": 1,
        "deleteParentWhenTriggered": 0,
        "hit": 235,
        "indirectHit": 31,
        "indirectHitRange": 6.1,
        "cost": 200,
        "explosive": 0.65,
        "model": "rhsusf|addons|rhsusf_weapons2|M136|at4_rocket",
        "caliber": 0.8,
        "airFriction": 0,
        "sideAirFriction": 0.01,
        "simulationStep": 0.01,
        "maxSpeed": 219,
        "initTime": 0.1,
        "thrustTime": 0,
        "thrust": 10,
        "fuseDistance": 5,
        "visibleFire": 28,
        "audibleFire": 16,
        "whistleDist": 4,
        "timeToLive": 12,
        "CraterEffects": "ATRocketCrater",
        "explosionEffects": "ATRocketExplosion",
        "effectsMissileInit": "RocketBackEffectsRPG",
        "effectsMissile": "missile3",
        # Class: CfgAmmo\rhs_ammo_M136_rocket\CamShakeFire,
        "CamShakeFire": {
            "power": 10,
            "duration": 0.5,
            "frequency": 20,
            "distance": 30
        },
        # Class: CfgAmmo\rhs_ammo_M136_rocket\CamShakePlayerFire,
        "CamShakePlayerFire": {
            "power": 5,
            "duration": 0.1,
            "frequency": 20
        },
        "dangerRadiusHit": -1,
        "suppressionRadiusHit": 30,
        "soundHit": ["A3|Sounds_F|weapons|Rockets|explosion_missile_02",2.51189,1,2500],
        "explosionSoundEffect": "DefaultExplosion",
        "soundFly": ["",1,1,400],
        "soundEngine": ["",1,1,20],
        "supersonicCrackNear": ["",1,1,50],
        "supersonicCrackFar": ["",1,1,150],
        "muzzleEffect": "BIS_fnc_effectFiredRocket",
        # Class: CfgAmmo\RocketBase\HitEffects,
        "HitEffects": {
            "hitWater": "ImpactEffectsWaterRocket"
        },
        # Class: CfgAmmo\RocketBase\EventHandlers,
        "EventHandlers": {
            # Class: CfgAmmo\RocketBase\EventHandlers\RHS_APS_FiredEH
            "RHS_APS_FiredEH": {
                "fired": "_this spawn rhs_fnc_aps_missileFired"
            }
        },
        "simulation": "shotRocket",
        "maneuvrability": 0,
        "maxControlRange": 0,
        "visibleFireTime": 20,
        "deflecting": 5,
        "access": 3,
        "underwaterHitRangeCoef": 1,
        "typicalSpeed": 900,
        "explosionForceCoef": 1,
        "isCraterOriented": 0,
        "proxyShape": "",
        "craterShape": "",
        "weaponType": "Default",
        "animated": 0,
        "shadow": 0,
        "cartridge": "",
        "tracerColor": [0.7,0.7,0.5,0.04],
        "tracerColorR": [0.7,0.7,0.5,0.04],
        "soundFall": ["",1,1],
        "soundFakeFall": ["soundFall",1],
        "hitGroundSoft": ["soundHit",1],
        "hitGroundHard": ["soundHit",1],
        "hitMan": ["soundHit",1],
        "hitArmor": ["soundHit",1],
        "hitIron": ["soundHit",1],
        "hitBuilding": ["soundHit",1],
        "hitFoliage": ["soundHit",1],
        "hitWood": ["soundHit",1],
        "hitGlass": ["soundHit",1],
        "hitGlassArmored": ["soundHit",1],
        "hitConcrete": ["soundHit",1],
        "hitRubber": ["soundHit",1],
        "hitPlastic": ["soundHit",1],
        "hitDefault": ["soundHit",1],
        "hitMetal": ["soundHit",1],
        "hitMetalplate": ["soundHit",1],
        "hitTyre": ["soundHit",1],
        "hitWater": ["soundHit",1],
        "soundImpact": ["",1,1],
        "impactGroundSoft": ["soundImpact",1],
        "impactGroundHard": ["soundImpact",1],
        "impactMan": ["soundImpact",1],
        "impactIron": ["soundImpact",1],
        "impactArmor": ["soundImpact",1],
        "impactBuilding": ["soundImpact",1],
        "impactFoliage": ["soundImpact",1],
        "impactWood": ["soundImpact",1],
        "impactGlass": ["soundImpact",1],
        "impactGlassArmored": ["soundImpact",1],
        "impactConcrete": ["soundImpact",1],
        "impactRubber": ["soundImpact",1],
        "impactPlastic": ["soundImpact",1],
        "impactDefault": ["soundImpact",1],
        "impactMetal": ["soundImpact",1],
        "impactMetalplate": ["soundImpact",1],
        "impactTyre": ["soundImpact",1],
        "impactWater": ["soundImpact",1],
        "grenadeFireSound": [],
        "grenadeBurningSound": [],
        "deflectionSlowDown": 0.8,
        "craterWaterEffects": "ImpactEffectsWater",
        "effectsSmoke": "SmokeShellWhite",
        "effectsFire": "CannonFire",
        "effectFlare": "FlareShell",
        "effectFly": "",
        "mineJumpEffects": "",
        "waterEffectOffset": 0.45,
        "directionalExplosion": 0,
        "explosionAngle": 60,
        "explosionDir": "explosionDir",
        "explosionPos": "explosionPos",
        "explosionEffectsDir": "explosionDir",
        "minimumSafeZone": 0.1,
        "soundTrigger": [],
        "soundActivation": [],
        "soundDeactivation": [],
        "minTimeToLive": 0,
        "irLock": 0,
        "airLock": 0,
        "laserLock": 0,
        "nvLock": 0,
        "artilleryLock": 0,
        "hitOnWater": 0,
        "lockSeekRadius": 100,
        "manualControl": 0,
        "trackLead": 1,
        "trackOversteer": 1,
        "missileLockCone": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "lockType": 0,
        "maverickweaponIndexOffset": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "autoSeekTarget": 0,
        "shootDistraction": -1,
        "explosionTime": 0,
        "icon": "",
        "explosionType": "explosive",
        "mineTrigger": "RangeTrigger",
        "mineBoundingTime": 3,
        "mineBoundingDist": 3,
        "mineInconspicuousness": 10,
        "mineFloating": -1,
        "mineDiveSpeed": 1,
        "minePlaceDist": 0.5,
        "suppressionRadiusBulletClose": -1,
        "dangerRadiusBulletClose": -1,
        "whistleOnFire": 0,
        # Class: CfgAmmo\Default\NVGMarkers,
        "NVGMarkers": {
        },
        "minDamageForCamShakeHit": 0.55,
    },
    "allowedSlots": [801,701,901],
    "scope": 1,
    "picture": "rhsusf|addons|rhsusf_weapons|icons|m_m136_ca.paa",
    "model": "A3|weapons_f|empty",
    "type": "6 * 		256",
    "initSpeed": 290,
    "mass": 0,
    "value": 5,
    "count": 1,
    "nameSound": "handgrenade",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "displayNameShort": "",
    "weight": 0,
    # Class: CfgMagazines\Default\InventoryPlacements,
    "InventoryPlacements": {
    },
    # Class: CfgMagazines\Default\Library,
    "Library": {
        "libTextDesc": ""
    },
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0,
}