rhssaf_veil_green = {
    "picture": "rhssaf|addons|rhssaf_inventoryicons|data|facewear|rhssaf_veil_Green_ca.paa",
    "dlc": "RHS_SAF",
    "author": "Red Hammer Studios",
    "scope": 2,
    "scopecurator": 2,
    "displayname": "Veil Mask",
    "model": "rhssaf|addons|rhssaf_m_headgear_veil|rhssaf_veil",
    "hiddenselections": ["camo_veil"],
    "hiddenselectionstextures": ["|rhssaf|addons|rhssaf_t_headgear_veil|data|rhssaf_veil_green_co.paa"],
    "_generalmacro": "G_Balaclava_blk",
    "scopearsenal": 2,
    "identitytypes": ["NoGlasses",0,"G_RUS_SF",25],
    "mass": 6,
    "name": "None",
}