RHS_weap_gau8 = {
    "displayName": "GAU-8",
    "cursorSize": 0,
    "cursor": "mg",
    "cursorAim": "EmptyCursor",
    "initspeed": 0,
    "magazines": ["rhs_mag_1150Rnd_30x173","rhs_mag_1150Rnd_30x173_mixed","rhs_mag_1000Rnd_30x173","rhs_mag_1000Rnd_30x173_mixed"],
    "modes": ["LowROF","HighROF","close","short","medium","far"],
    # Class: CfgWeapons|RHS_weap_gau8|LowROF [Indent level: 1],
    "LowROF": {
        "displayName": "LO",
        "textureType": "burst",
        "reloadTime": 0.03,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons|Gatling_30mm_Plane_CAS_01_F|LowROF|StandardSound [Indent level: 2],
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_01_burst",5.62341,1,1500,[25704,32159]],
            "soundBegin": ["begin1",1]
        },
        "soundContinuous": 1,
        "autoFire": 1,
        "flash": "gunfire",
        "flashSize": 0.1,
        # Recoil Array: recoil,
        "recoil": [],
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "ffCount": 6,
        "burst": 20,
        "showToPlayer": 1,
        "dispersion": 0.0095,
        "aiRateOfFire": 1,
        "aiRateOfFireDistance": 10,
        "minRange": 0,
        "minRangeProbab": 0.01,
        "midRange": 1,
        "midRangeProbab": 0.01,
        "maxRange": 2,
        "maxRangeProbab": 0.01,
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        # Recoil Array: recoilProne,
        "recoilProne": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "burstRangeMax": -1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons|RHS_weap_gau8|HighROF [Indent level: 1],
    "HighROF": {
        # Class: CfgWeapons|RHS_weap_gau8|HighROF|StandardSound [Indent level: 2]
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_01_burst",5.62341,1,1500,[12852,16079.5]],
            "soundBegin": ["begin1",1]
        },
        "displayName": "HI",
        "textureType": "fullAuto",
        "reloadtime": 0.015,
        "sounds": ["StandardSound"],
        "soundContinuous": 1,
        "autoFire": 1,
        "flash": "gunfire",
        "flashSize": 0.1,
        # Recoil Array: recoil,
        "recoil": [],
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "ffCount": 6,
        "burst": 20,
        "showToPlayer": 1,
        "dispersion": 0.0095,
        "aiRateOfFire": 1,
        "aiRateOfFireDistance": 10,
        "minRange": 0,
        "minRangeProbab": 0.01,
        "midRange": 1,
        "midRangeProbab": 0.01,
        "maxRange": 2,
        "maxRangeProbab": 0.01,
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        # Recoil Array: recoilProne,
        "recoilProne": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "burstRangeMax": -1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1,
        "aiRateOfFireDispersion": 1
    },
    "scope": 1,
    "holdsterAnimValue": 1,
    "canLock": 0,
    "ballisticsComputer": 8,
    "showAimCursorInternal": 0,
    "nameSound": "cannon",
    "shotFromTurret": 0,
    "muzzlePos": "Gatling_muzzleflash",
    "muzzleEnd": "Gatling_barrels_end",
    "selectionFireAnim": "Gatling_muzzleflash",
    "autoFire": 0,
    "burst": 20,
    "aiDispersionCoefY": 0.5,
    "aiDispersionCoefX": 0.5,
    # Class: CfgWeapons|Gatling_30mm_Plane_CAS_01_F|GunParticles [Indent level: 1],
    "GunParticles": {
        # Class: CfgWeapons|Gatling_30mm_Plane_CAS_01_F|GunParticles|Effect [Indent level: 2]
        "Effect": {
            "effectName": "MachineGun3",
            "positionName": "Gatling_barrels_end",
            "directionName": "Gatling_barrels_start"
        }
    },
    # Class: CfgWeapons|Gatling_30mm_Plane_CAS_01_F|close [Indent level: 1],
    "close": {
        "showToPlayer": 0,
        "burst": 33,
        "burstRangeMax": 100,
        "aiRateOfFire": 1,
        "aiRateOfFireDispersion": 1,
        "aiRateOfFireDistance": 200,
        "minRange": 1,
        "minRangeProbab": 0.1,
        "midRange": 100,
        "midRangeProbab": 0.5,
        "maxRange": 400,
        "maxRangeProbab": 0.85,
        "displayName": "Minigun 30 mm",
        "sounds": ["StandardSound"],
        # Class: CfgWeapons|Gatling_30mm_Plane_CAS_01_F|LowROF|StandardSound [Indent level: 2],
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_01_burst",5.62341,1,1500,[25704,32159]],
            "soundBegin": ["begin1",1]
        },
        "soundContinuous": 1,
        "autoFire": 1,
        "flash": "gunfire",
        "flashSize": 0.1,
        # Recoil Array: recoil,
        "recoil": [],
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "ffCount": 6,
        "reloadTime": 0.03,
        "dispersion": 0.0095,
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "textureType": "fullAuto",
        # Recoil Array: recoilProne,
        "recoilProne": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1
    },
    # Class: CfgWeapons|Gatling_30mm_Plane_CAS_01_F|near [Indent level: 1],
    "near": {
        "showToPlayer": 0,
        "burst": 33,
        "burstRangeMax": 100,
        "aiRateOfFire": 1,
        "aiRateOfFireDispersion": 1,
        "aiRateOfFireDistance": 200,
        "minRange": 1,
        "minRangeProbab": 0.1,
        "midRange": 100,
        "midRangeProbab": 0.5,
        "maxRange": 400,
        "maxRangeProbab": 0.85,
        "displayName": "Minigun 30 mm",
        "sounds": ["StandardSound"],
        # Class: CfgWeapons|Gatling_30mm_Plane_CAS_01_F|LowROF|StandardSound [Indent level: 2],
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_01_burst",5.62341,1,1500,[25704,32159]],
            "soundBegin": ["begin1",1]
        },
        "soundContinuous": 1,
        "autoFire": 1,
        "flash": "gunfire",
        "flashSize": 0.1,
        # Recoil Array: recoil,
        "recoil": [],
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "ffCount": 6,
        "reloadTime": 0.03,
        "dispersion": 0.0095,
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "textureType": "fullAuto",
        # Recoil Array: recoilProne,
        "recoilProne": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1
    },
    # Class: CfgWeapons|Gatling_30mm_Plane_CAS_01_F|short [Indent level: 1],
    "short": {
        "showToPlayer": 0,
        "burst": 33,
        "burstRangeMax": 100,
        "aiRateOfFire": 1,
        "aiRateOfFireDispersion": 1,
        "aiRateOfFireDistance": 300,
        "minRange": 200,
        "minRangeProbab": 0.3,
        "midRange": 400,
        "midRangeProbab": 0.85,
        "maxRange": 750,
        "maxRangeProbab": 0.9,
        "displayName": "Minigun 30 mm",
        "sounds": ["StandardSound"],
        # Class: CfgWeapons|Gatling_30mm_Plane_CAS_01_F|LowROF|StandardSound [Indent level: 2],
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_01_burst",5.62341,1,1500,[25704,32159]],
            "soundBegin": ["begin1",1]
        },
        "soundContinuous": 1,
        "autoFire": 1,
        "flash": "gunfire",
        "flashSize": 0.1,
        # Recoil Array: recoil,
        "recoil": [],
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "ffCount": 6,
        "reloadTime": 0.03,
        "dispersion": 0.0095,
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "textureType": "fullAuto",
        # Recoil Array: recoilProne,
        "recoilProne": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1
    },
    # Class: CfgWeapons|Gatling_30mm_Plane_CAS_01_F|medium [Indent level: 1],
    "medium": {
        "showToPlayer": 0,
        "burst": 33,
        "burstRangeMax": 67,
        "aiRateOfFire": 2,
        "aiRateOfFireDispersion": 2,
        "aiRateOfFireDistance": 800,
        "minRange": 600,
        "minRangeProbab": 0.6,
        "midRange": 750,
        "midRangeProbab": 0.9,
        "maxRange": 1000,
        "maxRangeProbab": 0.75,
        "displayName": "Minigun 30 mm",
        "sounds": ["StandardSound"],
        # Class: CfgWeapons|Gatling_30mm_Plane_CAS_01_F|LowROF|StandardSound [Indent level: 2],
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_01_burst",5.62341,1,1500,[25704,32159]],
            "soundBegin": ["begin1",1]
        },
        "soundContinuous": 1,
        "autoFire": 1,
        "flash": "gunfire",
        "flashSize": 0.1,
        # Recoil Array: recoil,
        "recoil": [],
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "ffCount": 6,
        "reloadTime": 0.03,
        "dispersion": 0.0095,
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "textureType": "fullAuto",
        # Recoil Array: recoilProne,
        "recoilProne": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1
    },
    # Class: CfgWeapons|Gatling_30mm_Plane_CAS_01_F|far [Indent level: 1],
    "far": {
        "showToPlayer": 0,
        "burst": 33,
        "burstRangeMax": 67,
        "aiRateOfFire": 2,
        "aiRateOfFireDispersion": 3,
        "aiRateOfFireDistance": 1200,
        "minRange": 900,
        "minRangeProbab": 0.84,
        "midRange": 1250,
        "midRangeProbab": 0.7,
        "maxRange": 1600,
        "maxRangeProbab": 0.1,
        "displayName": "Minigun 30 mm",
        "sounds": ["StandardSound"],
        # Class: CfgWeapons|Gatling_30mm_Plane_CAS_01_F|LowROF|StandardSound [Indent level: 2],
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_01_burst",5.62341,1,1500,[25704,32159]],
            "soundBegin": ["begin1",1]
        },
        "soundContinuous": 1,
        "autoFire": 1,
        "flash": "gunfire",
        "flashSize": 0.1,
        # Recoil Array: recoil,
        "recoil": [],
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "ffCount": 6,
        "reloadTime": 0.03,
        "dispersion": 0.0095,
        "sound": ["",10,1],
        "soundEnd": ["sound",1],
        "textureType": "fullAuto",
        # Recoil Array: recoilProne,
        "recoilProne": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "aiDispersionCoefY": 3,
        "aiDispersionCoefX": 2,
        "soundBurst": 0,
        "multiplier": 1,
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundLoop": [],
        "weaponSoundEffect": "",
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "requiredOpticType": -1
    },
    "type": 65536,
    # Class: CfgWeapons|CannonCore|GunClouds [Indent level: 1],
    "GunClouds": {
    },
    "access": 3,
    "value": 2,
    "picture": "",
    "uiPicture": "",
    "ammo": "",
    "cursorAimOn": "",
    "laser": 0,
    "hiddenSelections": [],
    "hiddenSelectionsTextures": [],
    "hiddenUnderwaterSelections": [],
    "shownUnderwaterSelections": [],
    "hiddenUnderwaterSelectionsTextures": [],
    "simulation": "Weapon",
    "count": 0,
    "multiplier": 1,
    "magazineReloadTime": 0,
    "reloadTime": 1,
    "magazineReloadSwitchPhase": 1,
    "sound": ["",1,1],
    "soundBegin": ["sound",1],
    "soundBeginWater": ["sound",1],
    "soundClosure": ["sound",1],
    "soundEnd": ["sound",1],
    "soundLoop": ["sound",1],
    "soundContinuous": 0,
    "weaponSoundEffect": "",
    "soundBurst": 1,
    "drySound": ["",1,1],
    "zeroingSound": ["",1,1],
    "reloadSound": ["",1,1],
    "changeFiremodeSound": ["",1,1],
    "reloadMagazineSound": ["",1,1],
    "emptySound": ["",1,1],
    "soundBullet": ["emptySound",1],
    "irDistance": 0,
    "irDotIntensity": 0.001,
    "dispersion": 0.002,
    "lockAcquire": 1,
    "enableAttack": 1,
    "ffMagnitude": 0,
    "ffFrequency": 1,
    "ffCount": 1,
    # Recoil Array: recoil,
    "recoil": [],
    "maxRecoilSway": 0.008,
    "swayDecaySpeed": 2,
    "model": "",
    "modelSpecial": "",
    "modelMagazine": "",
    "irLaserPos": "laser pos",
    "irLaserEnd": "laser dir",
    "cartridgePos": "nabojnicestart",
    "cartridgeVel": "nabojniceend",
    "memoryPointCamera": "eye",
    "fireSpreadAngle": 3,
    "useModelOptics": 1,
    "opticsID": 0,
    "modelOptics": "",
    "opticsPPEffects": [],
    "opticsFlare": 1,
    "optics": 1,
    "forceOptics": 0,
    "useAsBinocular": 0,
    "opticsDisablePeripherialVision": 0.67,
    "opticsZoomMin": 0.25,
    "opticsZoomMax": 1.25,
    "opticsZoomInit": 0.75,
    "distanceZoomMin": 400,
    "distanceZoomMax": 400,
    "primary": 10,
    "showSwitchAction": 0,
    "showEmpty": 1,
    "autoReload": 1,
    "showToPlayer": 1,
    "canShootInWater": 0,
    "aiRateOfFire": 5,
    "aiRateOfFireDistance": 500,
    "aiRateOfFireDispersion": 0,
    "fireLightDuration": 0.05,
    "fireLightIntensity": 0.2,
    "fireLightDiffuse": [0.937,0.631,0.259],
    "fireLightAmbient": [0,0,0],
    # Class: CfgWeapons|Default|Eventhandlers [Indent level: 1],
    "Eventhandlers": {
    },
    "backgroundReload": 0,
    "reloadAction": "",
    "muzzles": ["this"],
    "useAction": 0,
    "useActionTitle": "",
    "canDrop": 1,
    "weaponLockDelay": 0,
    "weaponLockSystem": 0,
    "cmImmunity": 1,
    "weight": 0,
    "minRange": 1,
    "minRangeProbab": 0.3,
    "midRange": 150,
    "midRangeProbab": 0.58,
    "maxRange": 500,
    "maxRangeProbab": 0.04,
    "handAnim": [],
    "lockingTargetSound": ["",0.000316228,2],
    "lockedTargetSound": ["",0.000316228,6],
    "detectRange": 0,
    "artilleryDispersion": 1,
    "artilleryCharge": 1,
    "fireAnims": [],
    # Class: CfgWeapons|Default|Library [Indent level: 1],
    "Library": {
        "libTextDesc": ""
    },
    "descriptionShort": "",
    # Class: CfgWeapons|Default|GunFire [Indent level: 1],
    "GunFire": {
        "access": 0,
        "cloudletDuration": 0.2,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 0.2,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 0.5,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletFire",
        "cloudletColor": [1,1,1,0],
        "cloudletDensityCoef": -1,
        "interval": -0.01,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 4500,
        "deltaT": -3000,
        # Class: CfgWeapons|Default|GunFire|Table [Indent level: 2],
        "Table": {
            # Class: CfgWeapons|Default|GunFire|Table|T0 [Indent level: 3]
            "T0": {
                "maxT": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T1 [Indent level: 3],
            "T1": {
                "maxT": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T2 [Indent level: 3],
            "T2": {
                "maxT": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T3 [Indent level: 3],
            "T3": {
                "maxT": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T4 [Indent level: 3],
            "T4": {
                "maxT": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T5 [Indent level: 3],
            "T5": {
                "maxT": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T6 [Indent level: 3],
            "T6": {
                "maxT": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T7 [Indent level: 3],
            "T7": {
                "maxT": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T8 [Indent level: 3],
            "T8": {
                "maxT": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T9 [Indent level: 3],
            "T9": {
                "maxT": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T10 [Indent level: 3],
            "T10": {
                "maxT": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T11 [Indent level: 3],
            "T11": {
                "maxT": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T12 [Indent level: 3],
            "T12": {
                "maxT": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T13 [Indent level: 3],
            "T13": {
                "maxT": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T14 [Indent level: 3],
            "T14": {
                "maxT": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T15 [Indent level: 3],
            "T15": {
                "maxT": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T16 [Indent level: 3],
            "T16": {
                "maxT": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T17 [Indent level: 3],
            "T17": {
                "maxT": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T18 [Indent level: 3],
            "T18": {
                "maxT": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T19 [Indent level: 3],
            "T19": {
                "maxT": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T20 [Indent level: 3],
            "T20": {
                "maxT": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T21 [Indent level: 3],
            "T21": {
                "maxT": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T22 [Indent level: 3],
            "T22": {
                "maxT": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    "textureType": "default",
    "inertia": 0.5,
    "aimTransitionSpeed": 1,
}