rhs_weap_m590_8rd = {
    "author": "Red Hammer Studios",
    "picture": "rhsusf|addons|rhsusf_inventoryicons|data|weapons|rhs_weap_M590_8RD_ca.paa",
    "model": "rhsusf|addons|rhsusf_weapons2|M590A1|M590_8MAG",
    # Compatible Magazines: magazines parameter (+ inherited),
    "magazines": [
        "rhsusf_8rnd_00buck","rhsusf_8rnd_slug","rhsusf_8rnd_he","rhsusf_8rnd_frag",
        "rhsgref_1rnd_00buck","rhsgref_1rnd_slug","rhsusf_5rnd_00buck","rhsusf_5rnd_slug",
        "rhsusf_5rnd_he","rhsusf_5rnd_frag",],
    "magazinewell": ["CBA_12g_1rnd","CBA_12g_2rnds","CBA_12g_3rnds","CBA_12g_4rnds","CBA_12g_5rnds","CBA_12g_6rnds","CBA_12g_7rnds","CBA_12g_8rnds"],
    "displayname": "M590A1 (Long)",
    # Class: CfgWeapons|rhs_weap_M590_8RD|Single [Indent level: 1],
    "single": {
        "sounds": ["StandardSound"],
        # Class: CfgWeapons|rhs_weap_M590_8RD|Single|StandardSound [Indent level: 2],
        "standardsound": {
            "soundsetshot": ["RHSUSF_m590_Shot_SoundSet","RHSUSF_MMG1_Tail_SoundSet"]
        },
        "reloadtime": 0.6,
        "minrange": 1,
        "minrangeprobab": 0.45,
        "multiplier": 1,
        "burst": 1,
        "burstrangemax": -1,
        "dispersion": 0.0002,
        "sound": ["",10,1],
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundend": [],
        "soundloop": [],
        "soundcontinuous": 0,
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "autofire": 0,
        "useaction": 0,
        "useactiontitle": "",
        "showtoplayer": 1,
        "midrange": 300,
        "midrangeprobab": 0.58,
        "maxrange": 600,
        "maxrangeprobab": 0.04,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "displayname": "Semi",
        "texturetype": "semi",
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.03,0.0110829,0.043044,0.03,0.0159085,0.0170136,0.03,0.0138285,0.0116128,0.06,0.0066492,0.004788,0.06,-0.0007206,-0.002688,0.06,-0.001765,-0.00282,0.06,-0.0018385,-0.001764,0.06,-0.0009414,-0.0005,0.06,0,0],
        "recoil": "recoil_single_primary_3outof10",
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.03,0.0110829,0.0021522,0.04,0.0095451,0.0007506,0.05,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0,0.06,-0.0007206,-2.88e-005,0.06,-0.001059,-8.46e-005,0.06,-0.0011031,-8.82e-005,0.06,-0.0009414,-7.5e-005,0.06,-0.0006618,-5.28e-005,0.06,-0.0003531,-2.82e-005,0.06,-0.0001029,-8.4e-006,0.06,-4.5e-005,0,0.06,0,0],
        "recoilprone": "recoil_single_primary_prone_3outof10",
        "aidispersioncoefy": 1.7,
        "aidispersioncoefx": 1.4,
        "soundburst": 0,
        "requiredoptictype": -1,
        "airateoffire": 2,
        "airateoffiredispersion": 1,
        "airateoffiredistance": 500
    },
    "inertia": 0.6,
    "dexterity": 1.4,
    "dlc": "RHS_USAF",
    "scope": 2,
    "handanim": ["OFP2_ManSkeleton","|rhsusf|addons|rhsusf_c_weapons|anims|rhs_hand_m590.rtm"],
    "optics": 1,
    "modeloptics": "-",
    "descriptionshort": "Shotgun <br />Caliber: 12 gauge",
    "weaponinfotype": "rhs_m590_handler",
    "modes": ["Single"],
    "muzzles": ["this","SAFE","RHS_ReloadAction"],
    # Class: CfgWeapons|rhs_weap_M590_5RD|SAFE [Indent level: 1],
    "safe": {
        "magazines": [],
        "displayname": "SAFE",
        "descriptionshort": "SAFE",
        "showtoplayer": 0,
        "modes": ["Safe"],
        "discretedistance": [0],
        "discretedistanceinitindex": 0,
        "drysound": ["A3|Sounds_F|arsenal|weapons|Rifles|MX|dry_Mx",0.562341,1,10],
        "changefiremodesound": ["A3|sounds_f|weapons|closure|firemode_changer_2",0.551189,1,5],
        # Class: CfgWeapons|RHSUSF_SAFE_BASE|Safe [Indent level: 1],
        "safe": {
            "sounds": [],
            "displayname": "SAFE",
            "descriptionshort": "SAFE",
            "showtoplayer": 0,
            "minrange": 0,
            "minrangeprobab": 0.001,
            "midrange": 0.001,
            "midrangeprobab": 0.001,
            "maxrange": 0.001,
            "maxrangeprobab": 0.001,
            "multiplier": 1,
            "burst": 1,
            "burstrangemax": -1,
            "dispersion": 0.0002,
            "sound": ["",10,1],
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundend": [],
            "soundloop": [],
            "soundcontinuous": 0,
            "weaponsoundeffect": "",
            "reloadtime": 0.1,
            "ffcount": 1,
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "flash": "gunfire",
            "flashsize": 0.1,
            "autofire": 0,
            "useaction": 0,
            "useactiontitle": "",
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "texturetype": "semi",
            # Recoil Array: recoil,
            "recoil": [0,0,0,0.03,0.0110829,0.043044,0.03,0.0159085,0.0170136,0.03,0.0138285,0.0116128,0.06,0.0066492,0.004788,0.06,-0.0007206,-0.002688,0.06,-0.001765,-0.00282,0.06,-0.0018385,-0.001764,0.06,-0.0009414,-0.0005,0.06,0,0],
            "recoil": "recoil_single_primary_3outof10",
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.03,0.0110829,0.0021522,0.04,0.0095451,0.0007506,0.05,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0,0.06,-0.0007206,-2.88e-005,0.06,-0.001059,-8.46e-005,0.06,-0.0011031,-8.82e-005,0.06,-0.0009414,-7.5e-005,0.06,-0.0006618,-5.28e-005,0.06,-0.0003531,-2.82e-005,0.06,-0.0001029,-8.4e-006,0.06,-4.5e-005,0,0.06,0,0],
            "recoilprone": "recoil_single_primary_prone_3outof10",
            "aidispersioncoefy": 1.7,
            "aidispersioncoefx": 1.4,
            "soundburst": 0,
            "requiredoptictype": -1,
            "airateoffire": 2,
            "airateoffiredispersion": 1,
            "airateoffiredistance": 500
        },
        "scope": 0,
        "weaponinfotype": "RscWeaponZeroing",
        # Recoil Class: recoil,
        # Class: CfgRecoils|recoil_default [Indent level: 0],
        "recoil": {
            "muzzleouter": [0.3,1,0.3,0.2],
            "muzzleinner": [0,0,0.1,0.1],
            "kickback": [0.03,0.06],
            "permanent": 0.1,
            "temporary": 0.01
        },
        "recoil": "recoil_default",
        "deployedpivot": "bipod",
        # Class: CfgWeapons|Rifle_Base_F|GunParticles [Indent level: 1],
        "gunparticles": {
            # Class: CfgWeapons|Rifle_Base_F|GunParticles|FirstEffect [Indent level: 2]
            "firsteffect": {
                "effectname": "RifleAssaultCloud",
                "positionname": "Usti hlavne",
                "directionname": "Konec hlavne"
            }
        },
        "htmin": 1,
        "htmax": 600,
        "afmax": 0,
        "mfmax": 0,
        "mfact": 1,
        "tbody": 100,
        "autofire": 1,
        "reloadaction": "ReloadMagazine",
        "soundcontinuous": 0,
        "optics": 0,
        "cursor": "arifle",
        "cursoraim": "CursorAim",
        "value": 4,
        "namesound": "rifle",
        "reloadtime": 0.15,
        "modeloptics": "-",
        "sound": [],
        "opticsflare": 0,
        "autoreload": 0,
        "aidispersioncoefx": 6,
        "aidispersioncoefy": 6,
        "opticszoommin": 0.25,
        "opticszoommax": 1.25,
        "opticszoominit": 0.75,
        "distancezoommin": 300,
        "distancezoommax": 300,
        "maxleadspeed": 23,
        "canlock": 0,
        "flash": "gunfire",
        "flashsize": 0.5,
        "dispersion": 0.00029,
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.01,0.01,0.1,0,-0.02,0.1,-0.01,0.01,0.05,0,0],
        "recoilprone": "assaultRifleBase",
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "ffcount": 3,
        "weaponpoolavailable": 1,
        "maxzeroing": 1000,
        # Class: CfgWeapons|Rifle|WeaponSlotsInfo [Indent level: 1],
        "weaponslotsinfo": {
            "mass": 2,
            # Class: CfgWeapons|Rifle|WeaponSlotsInfo|MuzzleSlot [Indent level: 2],
            "muzzleslot": {
                "linkproxy": "A3|data_f|proxies|weapon_slots|MUZZLE",
                "displayname": "$str_a3_cfgweapons_abr_base_f_weaponslotsinfo_muzzleslot0",
                "compatibleitems": [],
                "iconpicture": "A3|Weapons_F|Data|UI|attachment_muzzle.paa",
                "iconpinpoint": "Center",
                "access": 1,
                "scope": 0,
                "iconposition": [0,0],
                "iconscale": 0
            },
            # Class: CfgWeapons|Rifle|WeaponSlotsInfo|CowsSlot [Indent level: 2],
            "cowsslot": {
                "compatibleitems": ["optic_Nightstalker","optic_tws","optic_tws_mg","optic_NVS","optic_DMS","optic_LRPS","optic_ams","optic_AMS_snd","optic_AMS_khk","optic_KHS_blk","optic_KHS_tan","optic_KHS_hex","optic_KHS_old","optic_SOS","optic_MRCO","optic_Arco","optic_aco","optic_ACO_grn","optic_aco_smg","optic_ACO_grn_smg","optic_hamr","optic_Holosight","optic_Holosight_smg","optic_Hamr_khk_F","optic_SOS_khk_F","optic_Arco_ghex_F","optic_Arco_blk_F","optic_DMS_ghex_F","optic_ERCO_blk_F","optic_ERCO_khk_F","optic_ERCO_snd_F","optic_LRPS_ghex_F","optic_LRPS_tna_F","optic_Holosight_blk_F","optic_Holosight_khk_F","optic_Holosight_smg_blk_F","optic_Holosight_smg_khk_F","optic_Arco_AK_blk_F","optic_Arco_AK_lush_F","optic_Arco_AK_arid_F","optic_DMS_weathered_F","optic_DMS_weathered_Kir_F","optic_Arco_lush_F","optic_Arco_arid_F","optic_Holosight_lush_F","optic_Holosight_arid_F"],
                "linkproxy": "A3|data_f|proxies|weapon_slots|TOP",
                "displayname": "Optics Slot",
                "iconpicture": "A3|Weapons_F|Data|UI|attachment_top.paa",
                "iconpinpoint": "Bottom",
                "access": 1,
                "scope": 0,
                "iconposition": [0,0],
                "iconscale": 0
            },
            # Class: CfgWeapons|Rifle|WeaponSlotsInfo|PointerSlot [Indent level: 2],
            "pointerslot": {
                "compatibleitems": ["acc_flashlight","acc_pointer_IR"],
                "iconpicture": "A3|Weapons_F|Data|UI|attachment_side.paa",
                "iconpinpoint": "Center",
                "linkproxy": "A3|data_f|proxies|weapon_slots|SIDE",
                "displayname": "Pointer Slot",
                "access": 1,
                "scope": 0,
                "iconposition": [0,0],
                "iconscale": 0
            },
            "allowedslots": [901]
        },
        "zeroingsound": ["A3|Sounds_F|arsenal|sfx|shared|zeroing_knob_tick_metal",0.316228,1,5],
        "type": 1,
        "dexterity": 1.7,
        "airateoffire": 0.5,
        "airateoffiredistance": 500,
        "inertia": 0.5,
        "access": 3,
        "picture": "",
        "uipicture": "",
        "ammo": "",
        "cursorsize": 1,
        "showaimcursorinternal": 1,
        "cursoraimon": "",
        "laser": 0,
        "hiddenselections": [],
        "hiddenselectionstextures": [],
        "hiddenunderwaterselections": [],
        "shownunderwaterselections": [],
        "hiddenunderwaterselectionstextures": [],
        "simulation": "Weapon",
        "count": 0,
        "multiplier": 1,
        "burst": 1,
        "magazinereloadtime": 0,
        "magazinereloadswitchphase": 1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundend": ["sound",1],
        "soundloop": ["sound",1],
        "weaponsoundeffect": "",
        "soundburst": 1,
        "reloadsound": ["",1,1],
        "reloadmagazinesound": ["",1,1],
        "emptysound": ["",1,1],
        "soundbullet": ["emptySound",1],
        "initspeed": 0,
        "ballisticscomputer": 0,
        "irdistance": 0,
        "irdotintensity": 0.001,
        "lockacquire": 1,
        "enableattack": 1,
        "maxrecoilsway": 0.008,
        "swaydecayspeed": 2,
        "model": "",
        "modelspecial": "",
        "modelmagazine": "",
        "muzzlepos": "usti hlavne",
        "muzzleend": "konec hlavne",
        "irlaserpos": "laser pos",
        "irlaserend": "laser dir",
        "cartridgepos": "nabojnicestart",
        "cartridgevel": "nabojniceend",
        "selectionfireanim": "zasleh",
        "memorypointcamera": "eye",
        "firespreadangle": 3,
        "usemodeloptics": 1,
        "opticsid": 0,
        "opticsppeffects": [],
        "forceoptics": 0,
        "useasbinocular": 0,
        "opticsdisableperipherialvision": 0.67,
        "primary": 10,
        "showswitchaction": 0,
        "showempty": 1,
        "canshootinwater": 0,
        "airateoffiredispersion": 0,
        "firelightduration": 0.05,
        "firelightintensity": 0.2,
        "firelightdiffuse": [0.937,0.631,0.259],
        "firelightambient": [0,0,0],
        # Class: CfgWeapons|Default|Eventhandlers [Indent level: 1],
        "eventhandlers": {
        },
        "backgroundreload": 0,
        "muzzles": ["this"],
        "useaction": 0,
        "useactiontitle": "",
        "candrop": 1,
        "weaponlockdelay": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "weight": 0,
        "minrange": 1,
        "minrangeprobab": 0.3,
        "midrange": 150,
        "midrangeprobab": 0.58,
        "maxrange": 500,
        "maxrangeprobab": 0.04,
        "handanim": [],
        "lockingtargetsound": ["",0.000316228,2],
        "lockedtargetsound": ["",0.000316228,6],
        "detectrange": 0,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "fireanims": [],
        # Class: CfgWeapons|Default|Library [Indent level: 1],
        "library": {
            "libtextdesc": ""
        },
        # Class: CfgWeapons|Default|GunFire [Indent level: 1],
        "gunfire": {
            "access": 0,
            "cloudletduration": 0.2,
            "cloudletanimperiod": 1,
            "cloudletsize": 1,
            "cloudletalpha": 1,
            "cloudletgrowup": 0.2,
            "cloudletfadein": 0.01,
            "cloudletfadeout": 0.5,
            "cloudletaccy": 0,
            "cloudletminyspeed": -100,
            "cloudletmaxyspeed": 100,
            "cloudletshape": "cloudletFire",
            "cloudletcolor": [1,1,1,0],
            "cloudletdensitycoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourcesize": 0.5,
            "timetolive": 0,
            "initt": 4500,
            "deltat": -3000,
            # Class: CfgWeapons|Default|GunFire|Table [Indent level: 2],
            "table": {
                # Class: CfgWeapons|Default|GunFire|Table|T0 [Indent level: 3]
                "t0": {
                    "maxt": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T1 [Indent level: 3],
                "t1": {
                    "maxt": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T2 [Indent level: 3],
                "t2": {
                    "maxt": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T3 [Indent level: 3],
                "t3": {
                    "maxt": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T4 [Indent level: 3],
                "t4": {
                    "maxt": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T5 [Indent level: 3],
                "t5": {
                    "maxt": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T6 [Indent level: 3],
                "t6": {
                    "maxt": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T7 [Indent level: 3],
                "t7": {
                    "maxt": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T8 [Indent level: 3],
                "t8": {
                    "maxt": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T9 [Indent level: 3],
                "t9": {
                    "maxt": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T10 [Indent level: 3],
                "t10": {
                    "maxt": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T11 [Indent level: 3],
                "t11": {
                    "maxt": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T12 [Indent level: 3],
                "t12": {
                    "maxt": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T13 [Indent level: 3],
                "t13": {
                    "maxt": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T14 [Indent level: 3],
                "t14": {
                    "maxt": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T15 [Indent level: 3],
                "t15": {
                    "maxt": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T16 [Indent level: 3],
                "t16": {
                    "maxt": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T17 [Indent level: 3],
                "t17": {
                    "maxt": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T18 [Indent level: 3],
                "t18": {
                    "maxt": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T19 [Indent level: 3],
                "t19": {
                    "maxt": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T20 [Indent level: 3],
                "t20": {
                    "maxt": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T21 [Indent level: 3],
                "t21": {
                    "maxt": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T22 [Indent level: 3],
                "t22": {
                    "maxt": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        # Class: CfgWeapons|Default|GunClouds [Indent level: 1],
        "gunclouds": {
            "access": 0,
            "cloudletgrowup": 0.05,
            "cloudletfadein": 0,
            "cloudletfadeout": 0.1,
            "cloudletduration": 0.05,
            "cloudletalpha": 0.3,
            "cloudletaccy": 0,
            "cloudletminyspeed": -100,
            "cloudletmaxyspeed": 100,
            "interval": -0.02,
            "size": 0.3,
            "sourcesize": 0.02,
            "cloudletanimperiod": 1,
            "cloudletsize": 1,
            "cloudletshape": "cloudletClouds",
            "cloudletcolor": [1,1,1,0],
            "timetolive": 0,
            "initt": 0,
            "deltat": 0,
            # Class: CfgWeapons|Default|GunClouds|Table [Indent level: 2],
            "table": {
                # Class: CfgWeapons|Default|GunClouds|Table|T0 [Indent level: 3]
                "t0": {
                    "maxt": 0,
                    "color": [1,1,1,0]
                }
            }
        },
        "texturetype": "default",
        "aimtransitionspeed": 1
    },
    # Class: CfgWeapons|rhs_weap_M590_5RD|RHS_ReloadAction [Indent level: 1],
    "rhs_reloadaction": {
        "modes": ["this"],
        # Compatible Magazines: magazines parameter (+ inherited),
        "magazines": [
            "rhsusf_5rnd_00buck","rhsusf_5rnd_slug","rhsusf_5rnd_he","rhsusf_5rnd_frag",
            "rhsgref_1rnd_00buck","rhsgref_1rnd_slug",],
        "reloadtime": 0.1,
        "displayname": "SAFE",
        "descriptionshort": "SAFE",
        "showtoplayer": 0,
        "discretedistance": [0],
        "discretedistanceinitindex": 0,
        "drysound": ["A3|Sounds_F|arsenal|weapons|Rifles|MX|dry_Mx",0.562341,1,10],
        "changefiremodesound": ["A3|sounds_f|weapons|closure|firemode_changer_2",0.551189,1,5],
        # Class: CfgWeapons|RHSUSF_SAFE_BASE|Safe [Indent level: 1],
        "safe": {
            "sounds": [],
            "displayname": "SAFE",
            "descriptionshort": "SAFE",
            "showtoplayer": 0,
            "minrange": 0,
            "minrangeprobab": 0.001,
            "midrange": 0.001,
            "midrangeprobab": 0.001,
            "maxrange": 0.001,
            "maxrangeprobab": 0.001,
            "multiplier": 1,
            "burst": 1,
            "burstrangemax": -1,
            "dispersion": 0.0002,
            "sound": ["",10,1],
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundend": [],
            "soundloop": [],
            "soundcontinuous": 0,
            "weaponsoundeffect": "",
            "reloadtime": 0.1,
            "ffcount": 1,
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "flash": "gunfire",
            "flashsize": 0.1,
            "autofire": 0,
            "useaction": 0,
            "useactiontitle": "",
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "texturetype": "semi",
            # Recoil Array: recoil,
            "recoil": [0,0,0,0.03,0.0110829,0.043044,0.03,0.0159085,0.0170136,0.03,0.0138285,0.0116128,0.06,0.0066492,0.004788,0.06,-0.0007206,-0.002688,0.06,-0.001765,-0.00282,0.06,-0.0018385,-0.001764,0.06,-0.0009414,-0.0005,0.06,0,0],
            "recoil": "recoil_single_primary_3outof10",
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.03,0.0110829,0.0021522,0.04,0.0095451,0.0007506,0.05,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0,0.06,-0.0007206,-2.88e-005,0.06,-0.001059,-8.46e-005,0.06,-0.0011031,-8.82e-005,0.06,-0.0009414,-7.5e-005,0.06,-0.0006618,-5.28e-005,0.06,-0.0003531,-2.82e-005,0.06,-0.0001029,-8.4e-006,0.06,-4.5e-005,0,0.06,0,0],
            "recoilprone": "recoil_single_primary_prone_3outof10",
            "aidispersioncoefy": 1.7,
            "aidispersioncoefx": 1.4,
            "soundburst": 0,
            "requiredoptictype": -1,
            "airateoffire": 2,
            "airateoffiredispersion": 1,
            "airateoffiredistance": 500
        },
        "scope": 0,
        "weaponinfotype": "RscWeaponZeroing",
        # Recoil Class: recoil,
        # Class: CfgRecoils|recoil_default [Indent level: 0],
        "recoil": {
            "muzzleouter": [0.3,1,0.3,0.2],
            "muzzleinner": [0,0,0.1,0.1],
            "kickback": [0.03,0.06],
            "permanent": 0.1,
            "temporary": 0.01
        },
        "recoil": "recoil_default",
        "deployedpivot": "bipod",
        # Class: CfgWeapons|Rifle_Base_F|GunParticles [Indent level: 1],
        "gunparticles": {
            # Class: CfgWeapons|Rifle_Base_F|GunParticles|FirstEffect [Indent level: 2]
            "firsteffect": {
                "effectname": "RifleAssaultCloud",
                "positionname": "Usti hlavne",
                "directionname": "Konec hlavne"
            }
        },
        "htmin": 1,
        "htmax": 600,
        "afmax": 0,
        "mfmax": 0,
        "mfact": 1,
        "tbody": 100,
        "autofire": 1,
        "reloadaction": "ReloadMagazine",
        "soundcontinuous": 0,
        "optics": 0,
        "cursor": "arifle",
        "cursoraim": "CursorAim",
        "value": 4,
        "namesound": "rifle",
        "modeloptics": "-",
        "sound": [],
        "opticsflare": 0,
        "autoreload": 0,
        "aidispersioncoefx": 6,
        "aidispersioncoefy": 6,
        "opticszoommin": 0.25,
        "opticszoommax": 1.25,
        "opticszoominit": 0.75,
        "distancezoommin": 300,
        "distancezoommax": 300,
        "maxleadspeed": 23,
        "canlock": 0,
        "flash": "gunfire",
        "flashsize": 0.5,
        "dispersion": 0.00029,
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.01,0.01,0.1,0,-0.02,0.1,-0.01,0.01,0.05,0,0],
        "recoilprone": "assaultRifleBase",
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "ffcount": 3,
        "weaponpoolavailable": 1,
        "maxzeroing": 1000,
        # Class: CfgWeapons|Rifle|WeaponSlotsInfo [Indent level: 1],
        "weaponslotsinfo": {
            "mass": 2,
            # Class: CfgWeapons|Rifle|WeaponSlotsInfo|MuzzleSlot [Indent level: 2],
            "muzzleslot": {
                "linkproxy": "A3|data_f|proxies|weapon_slots|MUZZLE",
                "displayname": "$str_a3_cfgweapons_abr_base_f_weaponslotsinfo_muzzleslot0",
                "compatibleitems": [],
                "iconpicture": "A3|Weapons_F|Data|UI|attachment_muzzle.paa",
                "iconpinpoint": "Center",
                "access": 1,
                "scope": 0,
                "iconposition": [0,0],
                "iconscale": 0
            },
            # Class: CfgWeapons|Rifle|WeaponSlotsInfo|CowsSlot [Indent level: 2],
            "cowsslot": {
                "compatibleitems": ["optic_Nightstalker","optic_tws","optic_tws_mg","optic_NVS","optic_DMS","optic_LRPS","optic_ams","optic_AMS_snd","optic_AMS_khk","optic_KHS_blk","optic_KHS_tan","optic_KHS_hex","optic_KHS_old","optic_SOS","optic_MRCO","optic_Arco","optic_aco","optic_ACO_grn","optic_aco_smg","optic_ACO_grn_smg","optic_hamr","optic_Holosight","optic_Holosight_smg","optic_Hamr_khk_F","optic_SOS_khk_F","optic_Arco_ghex_F","optic_Arco_blk_F","optic_DMS_ghex_F","optic_ERCO_blk_F","optic_ERCO_khk_F","optic_ERCO_snd_F","optic_LRPS_ghex_F","optic_LRPS_tna_F","optic_Holosight_blk_F","optic_Holosight_khk_F","optic_Holosight_smg_blk_F","optic_Holosight_smg_khk_F","optic_Arco_AK_blk_F","optic_Arco_AK_lush_F","optic_Arco_AK_arid_F","optic_DMS_weathered_F","optic_DMS_weathered_Kir_F","optic_Arco_lush_F","optic_Arco_arid_F","optic_Holosight_lush_F","optic_Holosight_arid_F"],
                "linkproxy": "A3|data_f|proxies|weapon_slots|TOP",
                "displayname": "Optics Slot",
                "iconpicture": "A3|Weapons_F|Data|UI|attachment_top.paa",
                "iconpinpoint": "Bottom",
                "access": 1,
                "scope": 0,
                "iconposition": [0,0],
                "iconscale": 0
            },
            # Class: CfgWeapons|Rifle|WeaponSlotsInfo|PointerSlot [Indent level: 2],
            "pointerslot": {
                "compatibleitems": ["acc_flashlight","acc_pointer_IR"],
                "iconpicture": "A3|Weapons_F|Data|UI|attachment_side.paa",
                "iconpinpoint": "Center",
                "linkproxy": "A3|data_f|proxies|weapon_slots|SIDE",
                "displayname": "Pointer Slot",
                "access": 1,
                "scope": 0,
                "iconposition": [0,0],
                "iconscale": 0
            },
            "allowedslots": [901]
        },
        "zeroingsound": ["A3|Sounds_F|arsenal|sfx|shared|zeroing_knob_tick_metal",0.316228,1,5],
        "type": 1,
        "dexterity": 1.7,
        "airateoffire": 0.5,
        "airateoffiredistance": 500,
        "inertia": 0.5,
        "access": 3,
        "picture": "",
        "uipicture": "",
        "ammo": "",
        "cursorsize": 1,
        "showaimcursorinternal": 1,
        "cursoraimon": "",
        "laser": 0,
        "hiddenselections": [],
        "hiddenselectionstextures": [],
        "hiddenunderwaterselections": [],
        "shownunderwaterselections": [],
        "hiddenunderwaterselectionstextures": [],
        "simulation": "Weapon",
        "count": 0,
        "multiplier": 1,
        "burst": 1,
        "magazinereloadtime": 0,
        "magazinereloadswitchphase": 1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundend": ["sound",1],
        "soundloop": ["sound",1],
        "weaponsoundeffect": "",
        "soundburst": 1,
        "reloadsound": ["",1,1],
        "reloadmagazinesound": ["",1,1],
        "emptysound": ["",1,1],
        "soundbullet": ["emptySound",1],
        "initspeed": 0,
        "ballisticscomputer": 0,
        "irdistance": 0,
        "irdotintensity": 0.001,
        "lockacquire": 1,
        "enableattack": 1,
        "maxrecoilsway": 0.008,
        "swaydecayspeed": 2,
        "model": "",
        "modelspecial": "",
        "modelmagazine": "",
        "muzzlepos": "usti hlavne",
        "muzzleend": "konec hlavne",
        "irlaserpos": "laser pos",
        "irlaserend": "laser dir",
        "cartridgepos": "nabojnicestart",
        "cartridgevel": "nabojniceend",
        "selectionfireanim": "zasleh",
        "memorypointcamera": "eye",
        "firespreadangle": 3,
        "usemodeloptics": 1,
        "opticsid": 0,
        "opticsppeffects": [],
        "forceoptics": 0,
        "useasbinocular": 0,
        "opticsdisableperipherialvision": 0.67,
        "primary": 10,
        "showswitchaction": 0,
        "showempty": 1,
        "canshootinwater": 0,
        "airateoffiredispersion": 0,
        "firelightduration": 0.05,
        "firelightintensity": 0.2,
        "firelightdiffuse": [0.937,0.631,0.259],
        "firelightambient": [0,0,0],
        # Class: CfgWeapons|Default|Eventhandlers [Indent level: 1],
        "eventhandlers": {
        },
        "backgroundreload": 0,
        "muzzles": ["this"],
        "useaction": 0,
        "useactiontitle": "",
        "candrop": 1,
        "weaponlockdelay": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "weight": 0,
        "minrange": 1,
        "minrangeprobab": 0.3,
        "midrange": 150,
        "midrangeprobab": 0.58,
        "maxrange": 500,
        "maxrangeprobab": 0.04,
        "handanim": [],
        "lockingtargetsound": ["",0.000316228,2],
        "lockedtargetsound": ["",0.000316228,6],
        "detectrange": 0,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "fireanims": [],
        # Class: CfgWeapons|Default|Library [Indent level: 1],
        "library": {
            "libtextdesc": ""
        },
        # Class: CfgWeapons|Default|GunFire [Indent level: 1],
        "gunfire": {
            "access": 0,
            "cloudletduration": 0.2,
            "cloudletanimperiod": 1,
            "cloudletsize": 1,
            "cloudletalpha": 1,
            "cloudletgrowup": 0.2,
            "cloudletfadein": 0.01,
            "cloudletfadeout": 0.5,
            "cloudletaccy": 0,
            "cloudletminyspeed": -100,
            "cloudletmaxyspeed": 100,
            "cloudletshape": "cloudletFire",
            "cloudletcolor": [1,1,1,0],
            "cloudletdensitycoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourcesize": 0.5,
            "timetolive": 0,
            "initt": 4500,
            "deltat": -3000,
            # Class: CfgWeapons|Default|GunFire|Table [Indent level: 2],
            "table": {
                # Class: CfgWeapons|Default|GunFire|Table|T0 [Indent level: 3]
                "t0": {
                    "maxt": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T1 [Indent level: 3],
                "t1": {
                    "maxt": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T2 [Indent level: 3],
                "t2": {
                    "maxt": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T3 [Indent level: 3],
                "t3": {
                    "maxt": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T4 [Indent level: 3],
                "t4": {
                    "maxt": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T5 [Indent level: 3],
                "t5": {
                    "maxt": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T6 [Indent level: 3],
                "t6": {
                    "maxt": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T7 [Indent level: 3],
                "t7": {
                    "maxt": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T8 [Indent level: 3],
                "t8": {
                    "maxt": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T9 [Indent level: 3],
                "t9": {
                    "maxt": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T10 [Indent level: 3],
                "t10": {
                    "maxt": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T11 [Indent level: 3],
                "t11": {
                    "maxt": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T12 [Indent level: 3],
                "t12": {
                    "maxt": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T13 [Indent level: 3],
                "t13": {
                    "maxt": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T14 [Indent level: 3],
                "t14": {
                    "maxt": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T15 [Indent level: 3],
                "t15": {
                    "maxt": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T16 [Indent level: 3],
                "t16": {
                    "maxt": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T17 [Indent level: 3],
                "t17": {
                    "maxt": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T18 [Indent level: 3],
                "t18": {
                    "maxt": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T19 [Indent level: 3],
                "t19": {
                    "maxt": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T20 [Indent level: 3],
                "t20": {
                    "maxt": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T21 [Indent level: 3],
                "t21": {
                    "maxt": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T22 [Indent level: 3],
                "t22": {
                    "maxt": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        # Class: CfgWeapons|Default|GunClouds [Indent level: 1],
        "gunclouds": {
            "access": 0,
            "cloudletgrowup": 0.05,
            "cloudletfadein": 0,
            "cloudletfadeout": 0.1,
            "cloudletduration": 0.05,
            "cloudletalpha": 0.3,
            "cloudletaccy": 0,
            "cloudletminyspeed": -100,
            "cloudletmaxyspeed": 100,
            "interval": -0.02,
            "size": 0.3,
            "sourcesize": 0.02,
            "cloudletanimperiod": 1,
            "cloudletsize": 1,
            "cloudletshape": "cloudletClouds",
            "cloudletcolor": [1,1,1,0],
            "timetolive": 0,
            "initt": 0,
            "deltat": 0,
            # Class: CfgWeapons|Default|GunClouds|Table [Indent level: 2],
            "table": {
                # Class: CfgWeapons|Default|GunClouds|Table|T0 [Indent level: 3]
                "t0": {
                    "maxt": 0,
                    "color": [1,1,1,0]
                }
            }
        },
        "texturetype": "default",
        "aimtransitionspeed": 1
    },
    "distancezoommin": 50,
    "distancezoommax": 50,
    "discretedistance": [50],
    "discretedistanceinitindex": 0,
    "reloadaction": "RHS_GestureReloadM590",
    # Recoil Class: recoil,
    # Class: CfgRecoils|rhs_recoil_m590 [Indent level: 0],
    "recoil": {
        "muzzleouter": [0.4,1.1,0.5,0.7],
        "kickback": [0.105,0.11],
        "permanent": 0.05,
        "temporary": 0.08,
        "muzzleinner": [0,0,0.1,0.1]
    },
    "recoil": "rhs_recoil_m590",
    "reloadsound": ["A3|sounds_f|weapons|M320|M320_reload",0.1,1,30],
    "firespreadangle": 0.95,
    # Class: CfgWeapons|rhs_weap_M590_5RD|WeaponSlotsInfo [Indent level: 1],
    "weaponslotsinfo": {
        "allowedslots": [901],
        "mass": 71.72,
        # Class: CfgWeapons|rhs_weap_M590_5RD|WeaponSlotsInfo|PointerSlot [Indent level: 2],
        "pointerslot": {
            "iconposition": [0,0],
            "iconscale": 1,
            "iconpicture": "A3|Weapons_F|Data|clear_empty.paa",
            "iconpinpoint": "Left"
        }
    },
    # Class: CfgWeapons|rhs_weap_M590_5RD|Eventhandlers [Indent level: 1],
    "eventhandlers": {
        # Class: CfgWeapons|rhs_weap_M590_5RD|Eventhandlers|RHS_BoltAction [Indent level: 2]
        "rhs_boltaction": {
            "fired": "[_this select 0,_this # 1,_this # 1,_this # 4] call rhs_fnc_boltAction;",
            "reload": "_this spawn rhs_fnc_reloadShotgun"
        }
    },
    "rhs_boltactionsound": ["rhsusf|addons|rhsusf_c_weapons|sounds|m590_pump.ogg",0.9,1,20],
    "rhs_boltactionanim": "RHS_GestureRechamberM590",
    "rhs_boltactioncasepos": [0,0.05,0.05],
    "rhs_boltactioncasedir": [0.3,0.05,0.25],
    "rhs_boltactioncasedelay": 0.1,
    "rhs_boltactioncaseselection": "rightHand",
    "deployedpivot": "bipod",
    # Class: CfgWeapons|Rifle_Base_F|GunParticles [Indent level: 1],
    "gunparticles": {
        # Class: CfgWeapons|Rifle_Base_F|GunParticles|FirstEffect [Indent level: 2]
        "firsteffect": {
            "effectname": "RifleAssaultCloud",
            "positionname": "Usti hlavne",
            "directionname": "Konec hlavne"
        }
    },
    "htmin": 1,
    "htmax": 600,
    "afmax": 0,
    "mfmax": 0,
    "mfact": 1,
    "tbody": 100,
    "autofire": 1,
    "soundcontinuous": 0,
    "cursor": "arifle",
    "cursoraim": "CursorAim",
    "value": 4,
    "namesound": "rifle",
    "reloadtime": 0.15,
    "sound": [],
    "opticsflare": 0,
    "autoreload": 0,
    "aidispersioncoefx": 6,
    "aidispersioncoefy": 6,
    "opticszoommin": 0.25,
    "opticszoommax": 1.25,
    "opticszoominit": 0.75,
    "maxleadspeed": 23,
    "canlock": 0,
    "flash": "gunfire",
    "flashsize": 0.5,
    "dispersion": 0.00029,
    # Recoil Array: recoilprone,
    "recoilprone": [0,0,0,0.06,0.01,0.01,0.1,0,-0.02,0.1,-0.01,0.01,0.05,0,0],
    "recoilprone": "assaultRifleBase",
    "ffmagnitude": 0.5,
    "fffrequency": 11,
    "ffcount": 3,
    "weaponpoolavailable": 1,
    "maxzeroing": 1000,
    "zeroingsound": ["A3|Sounds_F|arsenal|sfx|shared|zeroing_knob_tick_metal",0.316228,1,5],
    "type": 1,
    "airateoffire": 0.5,
    "airateoffiredistance": 500,
    "access": 3,
    "uipicture": "",
    "ammo": "",
    "cursorsize": 1,
    "showaimcursorinternal": 1,
    "cursoraimon": "",
    "laser": 0,
    "hiddenselections": [],
    "hiddenselectionstextures": [],
    "hiddenunderwaterselections": [],
    "shownunderwaterselections": [],
    "hiddenunderwaterselectionstextures": [],
    "simulation": "Weapon",
    "count": 0,
    "multiplier": 1,
    "burst": 1,
    "magazinereloadtime": 0,
    "magazinereloadswitchphase": 1,
    "soundbegin": ["sound",1],
    "soundbeginwater": ["sound",1],
    "soundclosure": ["sound",1],
    "soundend": ["sound",1],
    "soundloop": ["sound",1],
    "weaponsoundeffect": "",
    "soundburst": 1,
    "drysound": ["",1,1],
    "changefiremodesound": ["",1,1],
    "reloadmagazinesound": ["",1,1],
    "emptysound": ["",1,1],
    "soundbullet": ["emptySound",1],
    "initspeed": 0,
    "ballisticscomputer": 0,
    "irdistance": 0,
    "irdotintensity": 0.001,
    "lockacquire": 1,
    "enableattack": 1,
    "maxrecoilsway": 0.008,
    "swaydecayspeed": 2,
    "modelspecial": "",
    "modelmagazine": "",
    "muzzlepos": "usti hlavne",
    "muzzleend": "konec hlavne",
    "irlaserpos": "laser pos",
    "irlaserend": "laser dir",
    "cartridgepos": "nabojnicestart",
    "cartridgevel": "nabojniceend",
    "selectionfireanim": "zasleh",
    "memorypointcamera": "eye",
    "usemodeloptics": 1,
    "opticsid": 0,
    "opticsppeffects": [],
    "forceoptics": 0,
    "useasbinocular": 0,
    "opticsdisableperipherialvision": 0.67,
    "primary": 10,
    "showswitchaction": 0,
    "showempty": 1,
    "showtoplayer": 1,
    "canshootinwater": 0,
    "airateoffiredispersion": 0,
    "firelightduration": 0.05,
    "firelightintensity": 0.2,
    "firelightdiffuse": [0.937,0.631,0.259],
    "firelightambient": [0,0,0],
    "backgroundreload": 0,
    "useaction": 0,
    "useactiontitle": "",
    "candrop": 1,
    "weaponlockdelay": 0,
    "weaponlocksystem": 0,
    "cmimmunity": 1,
    "weight": 0,
    "minrange": 1,
    "minrangeprobab": 0.3,
    "midrange": 150,
    "midrangeprobab": 0.58,
    "maxrange": 500,
    "maxrangeprobab": 0.04,
    "lockingtargetsound": ["",0.000316228,2],
    "lockedtargetsound": ["",0.000316228,6],
    "detectrange": 0,
    "artillerydispersion": 1,
    "artillerycharge": 1,
    "fireanims": [],
    # Class: CfgWeapons|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    # Class: CfgWeapons|Default|GunFire [Indent level: 1],
    "gunfire": {
        "access": 0,
        "cloudletduration": 0.2,
        "cloudletanimperiod": 1,
        "cloudletsize": 1,
        "cloudletalpha": 1,
        "cloudletgrowup": 0.2,
        "cloudletfadein": 0.01,
        "cloudletfadeout": 0.5,
        "cloudletaccy": 0,
        "cloudletminyspeed": -100,
        "cloudletmaxyspeed": 100,
        "cloudletshape": "cloudletFire",
        "cloudletcolor": [1,1,1,0],
        "cloudletdensitycoef": -1,
        "interval": -0.01,
        "size": 3,
        "sourcesize": 0.5,
        "timetolive": 0,
        "initt": 4500,
        "deltat": -3000,
        # Class: CfgWeapons|Default|GunFire|Table [Indent level: 2],
        "table": {
            # Class: CfgWeapons|Default|GunFire|Table|T0 [Indent level: 3]
            "t0": {
                "maxt": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T1 [Indent level: 3],
            "t1": {
                "maxt": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T2 [Indent level: 3],
            "t2": {
                "maxt": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T3 [Indent level: 3],
            "t3": {
                "maxt": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T4 [Indent level: 3],
            "t4": {
                "maxt": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T5 [Indent level: 3],
            "t5": {
                "maxt": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T6 [Indent level: 3],
            "t6": {
                "maxt": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T7 [Indent level: 3],
            "t7": {
                "maxt": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T8 [Indent level: 3],
            "t8": {
                "maxt": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T9 [Indent level: 3],
            "t9": {
                "maxt": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T10 [Indent level: 3],
            "t10": {
                "maxt": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T11 [Indent level: 3],
            "t11": {
                "maxt": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T12 [Indent level: 3],
            "t12": {
                "maxt": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T13 [Indent level: 3],
            "t13": {
                "maxt": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T14 [Indent level: 3],
            "t14": {
                "maxt": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T15 [Indent level: 3],
            "t15": {
                "maxt": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T16 [Indent level: 3],
            "t16": {
                "maxt": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T17 [Indent level: 3],
            "t17": {
                "maxt": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T18 [Indent level: 3],
            "t18": {
                "maxt": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T19 [Indent level: 3],
            "t19": {
                "maxt": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T20 [Indent level: 3],
            "t20": {
                "maxt": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T21 [Indent level: 3],
            "t21": {
                "maxt": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T22 [Indent level: 3],
            "t22": {
                "maxt": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgWeapons|Default|GunClouds [Indent level: 1],
    "gunclouds": {
        "access": 0,
        "cloudletgrowup": 0.05,
        "cloudletfadein": 0,
        "cloudletfadeout": 0.1,
        "cloudletduration": 0.05,
        "cloudletalpha": 0.3,
        "cloudletaccy": 0,
        "cloudletminyspeed": -100,
        "cloudletmaxyspeed": 100,
        "interval": -0.02,
        "size": 0.3,
        "sourcesize": 0.02,
        "cloudletanimperiod": 1,
        "cloudletsize": 1,
        "cloudletshape": "cloudletClouds",
        "cloudletcolor": [1,1,1,0],
        "timetolive": 0,
        "initt": 0,
        "deltat": 0,
        # Class: CfgWeapons|Default|GunClouds|Table [Indent level: 2],
        "table": {
            # Class: CfgWeapons|Default|GunClouds|Table|T0 [Indent level: 3]
            "t0": {
                "maxt": 0,
                "color": [1,1,1,0]
            }
        }
    },
    "texturetype": "default",
    "aimtransitionspeed": 1,
}