rhs_weap_gi2_base = {
    "aidispersioncoefx": 2,
    "aidispersioncoefy": 4,
    # Class: CfgWeapons|rhs_weap_gi2_base|manual [Indent level: 1],
    "manual": {
        "displayname": "GI-2",
        "autofire": 1,
        "reloadtime": 0.08333,
        "dispersion": 0.00125,
        "burst": 1,
        "airateoffire": 0.5,
        "airateoffiredistance": 50,
        "minrange": 1,
        "minrangeprobab": 0.01,
        "midrange": 2,
        "midrangeprobab": 0.01,
        "maxrange": 3,
        "maxrangeprobab": 0.01,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons|rhs_weap_M197|manual|StandardSound [Indent level: 2],
        "standardsound": {
            "weaponsoundeffect": "DefaultRifle",
            "begin1": ["|rhsusf|addons|rhsusf_a2port_air|data|sounds|a10vulcanVII",3.16228,1,1100],
            "soundbegin": ["begin1",1],
            "soundsetshot": ["RHSUSF_M230_Shot_SoundSet"]
        },
        "showtoplayer": 1,
        "sound": ["",10,1],
        "soundend": ["sound",1],
        "soundcontinuous": 0,
        "texturetype": "fullAuto",
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.06,0.0443316,0.0243916,0.06,0.0477255,0.0105084,0.06,0.0335835,0.0073344,0.06,0.0140372,0.003192,0.03,-0.0007206,-0.002688,0.03,-0.001765,-0.00282,0.03,-0.0018385,-0.001764,0.06,0,0],
        "recoil": "recoil_auto_primary_3outof10",
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "recoilprone": "recoil_auto_primary_prone_3outof10",
        "aidispersioncoefy": 3,
        "aidispersioncoefx": 2,
        "soundburst": 0,
        "multiplier": 1,
        "burstrangemax": -1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "useaction": 0,
        "useactiontitle": "",
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "requiredoptictype": -1,
        "airateoffiredispersion": 1
    },
    # Class: CfgWeapons|rhs_weap_gi2_base|close [Indent level: 1],
    "close": {
        "showtoplayer": 0,
        "soundburst": 0,
        "burst": 6,
        "burstrangemax": 12,
        "airateoffire": 0.5,
        "airateoffiredistance": 50,
        "minrange": 0,
        "minrangeprobab": 0.7,
        "midrange": 200,
        "midrangeprobab": 0.95,
        "maxrange": 500,
        "maxrangeprobab": 0.6,
        "displayname": "GI-2",
        "autofire": 1,
        "reloadtime": 0.08333,
        "dispersion": 0.00125,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons|rhs_weap_M197|manual|StandardSound [Indent level: 2],
        "standardsound": {
            "weaponsoundeffect": "DefaultRifle",
            "begin1": ["|rhsusf|addons|rhsusf_a2port_air|data|sounds|a10vulcanVII",3.16228,1,1100],
            "soundbegin": ["begin1",1],
            "soundsetshot": ["RHSUSF_M230_Shot_SoundSet"]
        },
        "sound": ["",10,1],
        "soundend": ["sound",1],
        "soundcontinuous": 0,
        "texturetype": "fullAuto",
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.06,0.0443316,0.0243916,0.06,0.0477255,0.0105084,0.06,0.0335835,0.0073344,0.06,0.0140372,0.003192,0.03,-0.0007206,-0.002688,0.03,-0.001765,-0.00282,0.03,-0.0018385,-0.001764,0.06,0,0],
        "recoil": "recoil_auto_primary_3outof10",
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "recoilprone": "recoil_auto_primary_prone_3outof10",
        "aidispersioncoefy": 3,
        "aidispersioncoefx": 2,
        "multiplier": 1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "useaction": 0,
        "useactiontitle": "",
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "requiredoptictype": -1,
        "airateoffiredispersion": 1
    },
    # Class: CfgWeapons|rhs_weap_gi2_base|short [Indent level: 1],
    "short": {
        "burst": 6,
        "burstrangemax": 10,
        "airateoffire": 2,
        "airateoffiredistance": 300,
        "minrange": 300,
        "minrangeprobab": 0.7,
        "midrange": 600,
        "midrangeprobab": 0.9,
        "maxrange": 800,
        "maxrangeprobab": 0.6,
        "showtoplayer": 0,
        "soundburst": 0,
        "displayname": "GI-2",
        "autofire": 1,
        "reloadtime": 0.08333,
        "dispersion": 0.00125,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons|rhs_weap_M197|manual|StandardSound [Indent level: 2],
        "standardsound": {
            "weaponsoundeffect": "DefaultRifle",
            "begin1": ["|rhsusf|addons|rhsusf_a2port_air|data|sounds|a10vulcanVII",3.16228,1,1100],
            "soundbegin": ["begin1",1],
            "soundsetshot": ["RHSUSF_M230_Shot_SoundSet"]
        },
        "sound": ["",10,1],
        "soundend": ["sound",1],
        "soundcontinuous": 0,
        "texturetype": "fullAuto",
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.06,0.0443316,0.0243916,0.06,0.0477255,0.0105084,0.06,0.0335835,0.0073344,0.06,0.0140372,0.003192,0.03,-0.0007206,-0.002688,0.03,-0.001765,-0.00282,0.03,-0.0018385,-0.001764,0.06,0,0],
        "recoil": "recoil_auto_primary_3outof10",
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "recoilprone": "recoil_auto_primary_prone_3outof10",
        "aidispersioncoefy": 3,
        "aidispersioncoefx": 2,
        "multiplier": 1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "useaction": 0,
        "useactiontitle": "",
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "requiredoptictype": -1,
        "airateoffiredispersion": 1
    },
    # Class: CfgWeapons|rhs_weap_gi2_base|medium [Indent level: 1],
    "medium": {
        "burst": 3,
        "burstrangemax": 8,
        "airateoffire": 3,
        "airateoffiredistance": 600,
        "minrange": 700,
        "minrangeprobab": 0.7,
        "midrange": 900,
        "midrangeprobab": 0.85,
        "maxrange": 1000,
        "maxrangeprobab": 0.6,
        "showtoplayer": 0,
        "soundburst": 0,
        "displayname": "GI-2",
        "autofire": 1,
        "reloadtime": 0.08333,
        "dispersion": 0.00125,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons|rhs_weap_M197|manual|StandardSound [Indent level: 2],
        "standardsound": {
            "weaponsoundeffect": "DefaultRifle",
            "begin1": ["|rhsusf|addons|rhsusf_a2port_air|data|sounds|a10vulcanVII",3.16228,1,1100],
            "soundbegin": ["begin1",1],
            "soundsetshot": ["RHSUSF_M230_Shot_SoundSet"]
        },
        "sound": ["",10,1],
        "soundend": ["sound",1],
        "soundcontinuous": 0,
        "texturetype": "fullAuto",
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.06,0.0443316,0.0243916,0.06,0.0477255,0.0105084,0.06,0.0335835,0.0073344,0.06,0.0140372,0.003192,0.03,-0.0007206,-0.002688,0.03,-0.001765,-0.00282,0.03,-0.0018385,-0.001764,0.06,0,0],
        "recoil": "recoil_auto_primary_3outof10",
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "recoilprone": "recoil_auto_primary_prone_3outof10",
        "aidispersioncoefy": 3,
        "aidispersioncoefx": 2,
        "multiplier": 1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "useaction": 0,
        "useactiontitle": "",
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "requiredoptictype": -1,
        "airateoffiredispersion": 1
    },
    # Class: CfgWeapons|rhs_weap_gi2_base|far [Indent level: 1],
    "far": {
        "burst": 3,
        "burstrangemax": 6,
        "airateoffire": 5,
        "airateoffiredistance": 1000,
        "minrange": 1000,
        "minrangeprobab": 0.3,
        "midrange": 1200,
        "midrangeprobab": 0.85,
        "maxrange": 1400,
        "maxrangeprobab": 0.6,
        "showtoplayer": 0,
        "soundburst": 0,
        "displayname": "GI-2",
        "autofire": 1,
        "reloadtime": 0.08333,
        "dispersion": 0.00125,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons|rhs_weap_M197|manual|StandardSound [Indent level: 2],
        "standardsound": {
            "weaponsoundeffect": "DefaultRifle",
            "begin1": ["|rhsusf|addons|rhsusf_a2port_air|data|sounds|a10vulcanVII",3.16228,1,1100],
            "soundbegin": ["begin1",1],
            "soundsetshot": ["RHSUSF_M230_Shot_SoundSet"]
        },
        "sound": ["",10,1],
        "soundend": ["sound",1],
        "soundcontinuous": 0,
        "texturetype": "fullAuto",
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.06,0.0443316,0.0243916,0.06,0.0477255,0.0105084,0.06,0.0335835,0.0073344,0.06,0.0140372,0.003192,0.03,-0.0007206,-0.002688,0.03,-0.001765,-0.00282,0.03,-0.0018385,-0.001764,0.06,0,0],
        "recoil": "recoil_auto_primary_3outof10",
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "recoilprone": "recoil_auto_primary_prone_3outof10",
        "aidispersioncoefy": 3,
        "aidispersioncoefx": 2,
        "multiplier": 1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "useaction": 0,
        "useactiontitle": "",
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "requiredoptictype": -1,
        "airateoffiredispersion": 1
    },
    "scope": 1,
    "cursor": "mg",
    "cursoraim": "EmptyCursor",
    "cursorsize": 0,
    "muzzles": ["this"],
    # Class: CfgWeapons|rhs_weap_M197|GunParticles [Indent level: 1],
    "gunparticles": {
        # Class: CfgWeapons|rhs_weap_M197|GunParticles|Effect [Indent level: 2]
        "effect": {
            "effectname": "MachineGun2",
            "positionname": "machinegun",
            "directionname": "machinegun_end"
        }
    },
    "displayname": "M197",
    "ballisticscomputer": 16,
    "autofire": 1,
    "namesound": "cannon",
    # Compatible Magazines: magazines parameter (+ inherited),
    "magazines": [
        "rhs_mag_m197_750",],
    "canlock": 2,
    "modes": ["manual","close","short","medium","far"],
    # Class: CfgWeapons|gatling_30mm|HE [Indent level: 1],
    "he": {
        # Compatible Magazines: magazines parameter (+ inherited)
        "magazines": [
            "250rnd_30mm_he_shells","250rnd_30mm_he_shells_tracer_red","250rnd_30mm_he_shells_tracer_green","250rnd_30mm_apds_shells"
            "250rnd_30mm_apds_shells_tracer_red","250rnd_30mm_apds_shells_tracer_green","250rnd_30mm_apds_shells_tracer_yellow",],
        # Class: CfgWeapons|gatling_30mm|HE|LowROF [Indent level: 2],
        "lowrof": {
            "dispersion": 0.0066,
            "displayname": "300rpm",
            "burst": 5,
            "sounds": ["StandardSound"],
            # Class: CfgWeapons|gatling_30mm_base|LowROF|StandardSound [Indent level: 2],
            "standardsound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_02_burst",5.62341,1,1500,[2,45447]],
                "soundbegin": ["begin1",1]
            },
            "soundcontinuous": 1,
            "flash": "gunfire",
            "flashsize": 0.1,
            # Recoil Array: recoil,
            "recoil": [],
            "recoil": "Empty",
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "ffcount": 6,
            "reloadtime": 0.08,
            "airateoffire": 1,
            "airateoffiredistance": 10,
            "minrange": 0,
            "minrangeprobab": 0.01,
            "midrange": 1,
            "midrangeprobab": 0.01,
            "maxrange": 2,
            "maxrangeprobab": 0.01,
            "sound": ["",10,1],
            "soundend": ["sound",1],
            "autofire": 1,
            "texturetype": "fullAuto",
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
            "recoilprone": "recoil_auto_primary_prone_3outof10",
            "aidispersioncoefy": 3,
            "aidispersioncoefx": 2,
            "soundburst": 0,
            "multiplier": 1,
            "burstrangemax": -1,
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundloop": [],
            "weaponsoundeffect": "",
            "useaction": 0,
            "useactiontitle": "",
            "showtoplayer": 1,
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "requiredoptictype": -1,
            "airateoffiredispersion": 1
        },
        "scope": 0,
        "displayname": "Cannon Caseless 30 mm",
        "namesound": "cannon",
        "burst": 5,
        "reloadtime": 0.02,
        "autofire": 1,
        "modes": ["LowROF","close","short","medium","far"],
        "shotfromturret": 1,
        "cursor": "EmptyCursor",
        "cursoraim": "mg",
        "canlock": 0,
        "ballisticscomputer": "1 + 2 + 16",
        "fcsmaxleadspeed": 30.5556,
        "fcszeroingdelay": 0.5,
        "maxzeroing": 2500,
        "aidispersioncoefy": 0.5,
        "aidispersioncoefx": 0.5,
        # Class: CfgWeapons|gatling_30mm_base|GunParticles [Indent level: 1],
        "gunparticles": {
            # Class: CfgWeapons|gatling_30mm_base|GunParticles|Effect [Indent level: 2]
            "effect": {
                "effectname": "MachineGun2",
                "positionname": "Usti hlavne",
                "directionname": "Konec hlavne"
            }
        },
        # Class: CfgWeapons|gatling_30mm_base|close [Indent level: 1],
        "close": {
            "aiburstterminable": 1,
            "showtoplayer": 0,
            "burst": 16,
            "burstrangemax": 37,
            "airateoffire": 0.5,
            "airateoffiredispersion": 1,
            "airateoffiredistance": 50,
            "minrange": 0,
            "minrangeprobab": 0.1,
            "midrange": 50,
            "midrangeprobab": 0.65,
            "maxrange": 400,
            "maxrangeprobab": 0.75,
            "displayname": "300rpm",
            "sounds": ["StandardSound"],
            # Class: CfgWeapons|gatling_30mm_base|LowROF|StandardSound [Indent level: 2],
            "standardsound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_02_burst",5.62341,1,1500,[2,45447]],
                "soundbegin": ["begin1",1]
            },
            "soundcontinuous": 1,
            "flash": "gunfire",
            "flashsize": 0.1,
            # Recoil Array: recoil,
            "recoil": [],
            "recoil": "Empty",
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "ffcount": 6,
            "reloadtime": 0.08,
            "dispersion": 0.0044,
            "sound": ["",10,1],
            "soundend": ["sound",1],
            "autofire": 1,
            "texturetype": "fullAuto",
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
            "recoilprone": "recoil_auto_primary_prone_3outof10",
            "aidispersioncoefy": 3,
            "aidispersioncoefx": 2,
            "soundburst": 0,
            "multiplier": 1,
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundloop": [],
            "weaponsoundeffect": "",
            "useaction": 0,
            "useactiontitle": "",
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "requiredoptictype": -1
        },
        # Class: CfgWeapons|gatling_30mm_base|near [Indent level: 1],
        "near": {
            "aiburstterminable": 1,
            "showtoplayer": 0,
            "burst": 16,
            "burstrangemax": 37,
            "airateoffire": 0.5,
            "airateoffiredispersion": 1,
            "airateoffiredistance": 50,
            "minrange": 0,
            "minrangeprobab": 0.1,
            "midrange": 50,
            "midrangeprobab": 0.65,
            "maxrange": 400,
            "maxrangeprobab": 0.75,
            "displayname": "300rpm",
            "sounds": ["StandardSound"],
            # Class: CfgWeapons|gatling_30mm_base|LowROF|StandardSound [Indent level: 2],
            "standardsound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_02_burst",5.62341,1,1500,[2,45447]],
                "soundbegin": ["begin1",1]
            },
            "soundcontinuous": 1,
            "flash": "gunfire",
            "flashsize": 0.1,
            # Recoil Array: recoil,
            "recoil": [],
            "recoil": "Empty",
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "ffcount": 6,
            "reloadtime": 0.08,
            "dispersion": 0.0044,
            "sound": ["",10,1],
            "soundend": ["sound",1],
            "autofire": 1,
            "texturetype": "fullAuto",
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
            "recoilprone": "recoil_auto_primary_prone_3outof10",
            "aidispersioncoefy": 3,
            "aidispersioncoefx": 2,
            "soundburst": 0,
            "multiplier": 1,
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundloop": [],
            "weaponsoundeffect": "",
            "useaction": 0,
            "useactiontitle": "",
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "requiredoptictype": -1
        },
        # Class: CfgWeapons|gatling_30mm_base|short [Indent level: 1],
        "short": {
            "aiburstterminable": 1,
            "showtoplayer": 0,
            "burst": 12,
            "burstrangemax": 32,
            "airateoffire": 1,
            "airateoffiredispersion": 2,
            "airateoffiredistance": 200,
            "minrange": 200,
            "minrangeprobab": 0.65,
            "midrange": 400,
            "midrangeprobab": 0.75,
            "maxrange": 1000,
            "maxrangeprobab": 0.7,
            "displayname": "300rpm",
            "sounds": ["StandardSound"],
            # Class: CfgWeapons|gatling_30mm_base|LowROF|StandardSound [Indent level: 2],
            "standardsound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_02_burst",5.62341,1,1500,[2,45447]],
                "soundbegin": ["begin1",1]
            },
            "soundcontinuous": 1,
            "flash": "gunfire",
            "flashsize": 0.1,
            # Recoil Array: recoil,
            "recoil": [],
            "recoil": "Empty",
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "ffcount": 6,
            "reloadtime": 0.08,
            "dispersion": 0.0044,
            "sound": ["",10,1],
            "soundend": ["sound",1],
            "autofire": 1,
            "texturetype": "fullAuto",
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
            "recoilprone": "recoil_auto_primary_prone_3outof10",
            "aidispersioncoefy": 3,
            "aidispersioncoefx": 2,
            "soundburst": 0,
            "multiplier": 1,
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundloop": [],
            "weaponsoundeffect": "",
            "useaction": 0,
            "useactiontitle": "",
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "requiredoptictype": -1
        },
        # Class: CfgWeapons|gatling_30mm_base|medium [Indent level: 1],
        "medium": {
            "aiburstterminable": 1,
            "showtoplayer": 0,
            "burst": 12,
            "burstrangemax": 28,
            "airateoffire": 2,
            "airateoffiredispersion": 2,
            "airateoffiredistance": 800,
            "minrange": 800,
            "minrangeprobab": 0.7,
            "midrange": 1400,
            "midrangeprobab": 0.4,
            "maxrange": 1800,
            "maxrangeprobab": 0.15,
            "displayname": "300rpm",
            "sounds": ["StandardSound"],
            # Class: CfgWeapons|gatling_30mm_base|LowROF|StandardSound [Indent level: 2],
            "standardsound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_02_burst",5.62341,1,1500,[2,45447]],
                "soundbegin": ["begin1",1]
            },
            "soundcontinuous": 1,
            "flash": "gunfire",
            "flashsize": 0.1,
            # Recoil Array: recoil,
            "recoil": [],
            "recoil": "Empty",
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "ffcount": 6,
            "reloadtime": 0.08,
            "dispersion": 0.0044,
            "sound": ["",10,1],
            "soundend": ["sound",1],
            "autofire": 1,
            "texturetype": "fullAuto",
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
            "recoilprone": "recoil_auto_primary_prone_3outof10",
            "aidispersioncoefy": 3,
            "aidispersioncoefx": 2,
            "soundburst": 0,
            "multiplier": 1,
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundloop": [],
            "weaponsoundeffect": "",
            "useaction": 0,
            "useactiontitle": "",
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "requiredoptictype": -1
        },
        # Class: CfgWeapons|gatling_30mm_base|far [Indent level: 1],
        "far": {
            "aiburstterminable": 1,
            "showtoplayer": 0,
            "burst": 9,
            "burstrangemax": 20,
            "airateoffire": 4,
            "airateoffiredispersion": 4,
            "airateoffiredistance": 1400,
            "minrange": 1400,
            "minrangeprobab": 0.5,
            "midrange": 1800,
            "midrangeprobab": 0.15,
            "maxrange": 2500,
            "maxrangeprobab": 0.05,
            "displayname": "300rpm",
            "sounds": ["StandardSound"],
            # Class: CfgWeapons|gatling_30mm_base|LowROF|StandardSound [Indent level: 2],
            "standardsound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_02_burst",5.62341,1,1500,[2,45447]],
                "soundbegin": ["begin1",1]
            },
            "soundcontinuous": 1,
            "flash": "gunfire",
            "flashsize": 0.1,
            # Recoil Array: recoil,
            "recoil": [],
            "recoil": "Empty",
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "ffcount": 6,
            "reloadtime": 0.08,
            "dispersion": 0.0044,
            "sound": ["",10,1],
            "soundend": ["sound",1],
            "autofire": 1,
            "texturetype": "fullAuto",
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
            "recoilprone": "recoil_auto_primary_prone_3outof10",
            "aidispersioncoefy": 3,
            "aidispersioncoefx": 2,
            "soundburst": 0,
            "multiplier": 1,
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundloop": [],
            "weaponsoundeffect": "",
            "useaction": 0,
            "useactiontitle": "",
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "requiredoptictype": -1
        },
        "type": 65536,
        # Class: CfgWeapons|CannonCore|GunClouds [Indent level: 1],
        "gunclouds": {
        },
        "access": 3,
        "value": 2,
        "picture": "",
        "uipicture": "",
        "ammo": "",
        "cursorsize": 1,
        "showaimcursorinternal": 1,
        "cursoraimon": "",
        "laser": 0,
        "hiddenselections": [],
        "hiddenselectionstextures": [],
        "hiddenunderwaterselections": [],
        "shownunderwaterselections": [],
        "hiddenunderwaterselectionstextures": [],
        "simulation": "Weapon",
        "count": 0,
        "multiplier": 1,
        "magazinereloadtime": 0,
        "magazinereloadswitchphase": 1,
        "sound": ["",1,1],
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundend": ["sound",1],
        "soundloop": ["sound",1],
        "soundcontinuous": 0,
        "weaponsoundeffect": "",
        "soundburst": 1,
        "drysound": ["",1,1],
        "zeroingsound": ["",1,1],
        "reloadsound": ["",1,1],
        "changefiremodesound": ["",1,1],
        "reloadmagazinesound": ["",1,1],
        "emptysound": ["",1,1],
        "soundbullet": ["emptySound",1],
        "initspeed": 0,
        "irdistance": 0,
        "irdotintensity": 0.001,
        "dispersion": 0.002,
        "lockacquire": 1,
        "enableattack": 1,
        "ffmagnitude": 0,
        "fffrequency": 1,
        "ffcount": 1,
        # Recoil Array: recoil,
        "recoil": [],
        "recoil": "empty",
        "recoilprone": "",
        "maxrecoilsway": 0.008,
        "swaydecayspeed": 2,
        "model": "",
        "modelspecial": "",
        "modelmagazine": "",
        "muzzlepos": "usti hlavne",
        "muzzleend": "konec hlavne",
        "irlaserpos": "laser pos",
        "irlaserend": "laser dir",
        "cartridgepos": "nabojnicestart",
        "cartridgevel": "nabojniceend",
        "selectionfireanim": "zasleh",
        "memorypointcamera": "eye",
        "firespreadangle": 3,
        "usemodeloptics": 1,
        "opticsid": 0,
        "modeloptics": "",
        "opticsppeffects": [],
        "opticsflare": 1,
        "optics": 1,
        "forceoptics": 0,
        "useasbinocular": 0,
        "opticsdisableperipherialvision": 0.67,
        "opticszoommin": 0.25,
        "opticszoommax": 1.25,
        "opticszoominit": 0.75,
        "distancezoommin": 400,
        "distancezoommax": 400,
        "primary": 10,
        "showswitchaction": 0,
        "showempty": 1,
        "autoreload": 1,
        "showtoplayer": 1,
        "canshootinwater": 0,
        "airateoffire": 5,
        "airateoffiredistance": 500,
        "airateoffiredispersion": 0,
        "firelightduration": 0.05,
        "firelightintensity": 0.2,
        "firelightdiffuse": [0.937,0.631,0.259],
        "firelightambient": [0,0,0],
        # Class: CfgWeapons|Default|Eventhandlers [Indent level: 1],
        "eventhandlers": {
        },
        "backgroundreload": 0,
        "reloadaction": "",
        "muzzles": ["this"],
        "useaction": 0,
        "useactiontitle": "",
        "candrop": 1,
        "weaponlockdelay": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "weight": 0,
        "minrange": 1,
        "minrangeprobab": 0.3,
        "midrange": 150,
        "midrangeprobab": 0.58,
        "maxrange": 500,
        "maxrangeprobab": 0.04,
        "handanim": [],
        "lockingtargetsound": ["",0.000316228,2],
        "lockedtargetsound": ["",0.000316228,6],
        "detectrange": 0,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "fireanims": [],
        # Class: CfgWeapons|Default|Library [Indent level: 1],
        "library": {
            "libtextdesc": ""
        },
        "descriptionshort": "",
        # Class: CfgWeapons|Default|GunFire [Indent level: 1],
        "gunfire": {
            "access": 0,
            "cloudletduration": 0.2,
            "cloudletanimperiod": 1,
            "cloudletsize": 1,
            "cloudletalpha": 1,
            "cloudletgrowup": 0.2,
            "cloudletfadein": 0.01,
            "cloudletfadeout": 0.5,
            "cloudletaccy": 0,
            "cloudletminyspeed": -100,
            "cloudletmaxyspeed": 100,
            "cloudletshape": "cloudletFire",
            "cloudletcolor": [1,1,1,0],
            "cloudletdensitycoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourcesize": 0.5,
            "timetolive": 0,
            "initt": 4500,
            "deltat": -3000,
            # Class: CfgWeapons|Default|GunFire|Table [Indent level: 2],
            "table": {
                # Class: CfgWeapons|Default|GunFire|Table|T0 [Indent level: 3]
                "t0": {
                    "maxt": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T1 [Indent level: 3],
                "t1": {
                    "maxt": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T2 [Indent level: 3],
                "t2": {
                    "maxt": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T3 [Indent level: 3],
                "t3": {
                    "maxt": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T4 [Indent level: 3],
                "t4": {
                    "maxt": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T5 [Indent level: 3],
                "t5": {
                    "maxt": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T6 [Indent level: 3],
                "t6": {
                    "maxt": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T7 [Indent level: 3],
                "t7": {
                    "maxt": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T8 [Indent level: 3],
                "t8": {
                    "maxt": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T9 [Indent level: 3],
                "t9": {
                    "maxt": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T10 [Indent level: 3],
                "t10": {
                    "maxt": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T11 [Indent level: 3],
                "t11": {
                    "maxt": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T12 [Indent level: 3],
                "t12": {
                    "maxt": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T13 [Indent level: 3],
                "t13": {
                    "maxt": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T14 [Indent level: 3],
                "t14": {
                    "maxt": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T15 [Indent level: 3],
                "t15": {
                    "maxt": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T16 [Indent level: 3],
                "t16": {
                    "maxt": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T17 [Indent level: 3],
                "t17": {
                    "maxt": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T18 [Indent level: 3],
                "t18": {
                    "maxt": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T19 [Indent level: 3],
                "t19": {
                    "maxt": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T20 [Indent level: 3],
                "t20": {
                    "maxt": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T21 [Indent level: 3],
                "t21": {
                    "maxt": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T22 [Indent level: 3],
                "t22": {
                    "maxt": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        "texturetype": "default",
        "inertia": 0.5,
        "aimtransitionspeed": 1
    },
    # Class: CfgWeapons|gatling_30mm|AP [Indent level: 1],
    "ap": {
        # Compatible Magazines: magazines parameter (+ inherited)
        "magazines": [
            "250rnd_30mm_he_shells","250rnd_30mm_he_shells_tracer_red","250rnd_30mm_he_shells_tracer_green","250rnd_30mm_apds_shells"
            "250rnd_30mm_apds_shells_tracer_red","250rnd_30mm_apds_shells_tracer_green","250rnd_30mm_apds_shells_tracer_yellow",],
        "scope": 0,
        "displayname": "Cannon Caseless 30 mm",
        "namesound": "cannon",
        "burst": 5,
        "reloadtime": 0.02,
        "autofire": 1,
        "modes": ["LowROF","close","short","medium","far"],
        "shotfromturret": 1,
        "cursor": "EmptyCursor",
        "cursoraim": "mg",
        "canlock": 0,
        "ballisticscomputer": "1 + 2 + 16",
        "fcsmaxleadspeed": 30.5556,
        "fcszeroingdelay": 0.5,
        "maxzeroing": 2500,
        "aidispersioncoefy": 0.5,
        "aidispersioncoefx": 0.5,
        # Class: CfgWeapons|gatling_30mm_base|GunParticles [Indent level: 1],
        "gunparticles": {
            # Class: CfgWeapons|gatling_30mm_base|GunParticles|Effect [Indent level: 2]
            "effect": {
                "effectname": "MachineGun2",
                "positionname": "Usti hlavne",
                "directionname": "Konec hlavne"
            }
        },
        # Class: CfgWeapons|gatling_30mm_base|LowROF [Indent level: 1],
        "lowrof": {
            "displayname": "300rpm",
            "burst": 5,
            "sounds": ["StandardSound"],
            # Class: CfgWeapons|gatling_30mm_base|LowROF|StandardSound [Indent level: 2],
            "standardsound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_02_burst",5.62341,1,1500,[2,45447]],
                "soundbegin": ["begin1",1]
            },
            "soundcontinuous": 1,
            "flash": "gunfire",
            "flashsize": 0.1,
            # Recoil Array: recoil,
            "recoil": [],
            "recoil": "Empty",
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "ffcount": 6,
            "reloadtime": 0.08,
            "dispersion": 0.0044,
            "airateoffire": 1,
            "airateoffiredistance": 10,
            "minrange": 0,
            "minrangeprobab": 0.01,
            "midrange": 1,
            "midrangeprobab": 0.01,
            "maxrange": 2,
            "maxrangeprobab": 0.01,
            "sound": ["",10,1],
            "soundend": ["sound",1],
            "autofire": 1,
            "texturetype": "fullAuto",
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
            "recoilprone": "recoil_auto_primary_prone_3outof10",
            "aidispersioncoefy": 3,
            "aidispersioncoefx": 2,
            "soundburst": 0,
            "multiplier": 1,
            "burstrangemax": -1,
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundloop": [],
            "weaponsoundeffect": "",
            "useaction": 0,
            "useactiontitle": "",
            "showtoplayer": 1,
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "requiredoptictype": -1,
            "airateoffiredispersion": 1
        },
        # Class: CfgWeapons|gatling_30mm_base|close [Indent level: 1],
        "close": {
            "aiburstterminable": 1,
            "showtoplayer": 0,
            "burst": 16,
            "burstrangemax": 37,
            "airateoffire": 0.5,
            "airateoffiredispersion": 1,
            "airateoffiredistance": 50,
            "minrange": 0,
            "minrangeprobab": 0.1,
            "midrange": 50,
            "midrangeprobab": 0.65,
            "maxrange": 400,
            "maxrangeprobab": 0.75,
            "displayname": "300rpm",
            "sounds": ["StandardSound"],
            # Class: CfgWeapons|gatling_30mm_base|LowROF|StandardSound [Indent level: 2],
            "standardsound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_02_burst",5.62341,1,1500,[2,45447]],
                "soundbegin": ["begin1",1]
            },
            "soundcontinuous": 1,
            "flash": "gunfire",
            "flashsize": 0.1,
            # Recoil Array: recoil,
            "recoil": [],
            "recoil": "Empty",
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "ffcount": 6,
            "reloadtime": 0.08,
            "dispersion": 0.0044,
            "sound": ["",10,1],
            "soundend": ["sound",1],
            "autofire": 1,
            "texturetype": "fullAuto",
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
            "recoilprone": "recoil_auto_primary_prone_3outof10",
            "aidispersioncoefy": 3,
            "aidispersioncoefx": 2,
            "soundburst": 0,
            "multiplier": 1,
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundloop": [],
            "weaponsoundeffect": "",
            "useaction": 0,
            "useactiontitle": "",
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "requiredoptictype": -1
        },
        # Class: CfgWeapons|gatling_30mm_base|near [Indent level: 1],
        "near": {
            "aiburstterminable": 1,
            "showtoplayer": 0,
            "burst": 16,
            "burstrangemax": 37,
            "airateoffire": 0.5,
            "airateoffiredispersion": 1,
            "airateoffiredistance": 50,
            "minrange": 0,
            "minrangeprobab": 0.1,
            "midrange": 50,
            "midrangeprobab": 0.65,
            "maxrange": 400,
            "maxrangeprobab": 0.75,
            "displayname": "300rpm",
            "sounds": ["StandardSound"],
            # Class: CfgWeapons|gatling_30mm_base|LowROF|StandardSound [Indent level: 2],
            "standardsound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_02_burst",5.62341,1,1500,[2,45447]],
                "soundbegin": ["begin1",1]
            },
            "soundcontinuous": 1,
            "flash": "gunfire",
            "flashsize": 0.1,
            # Recoil Array: recoil,
            "recoil": [],
            "recoil": "Empty",
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "ffcount": 6,
            "reloadtime": 0.08,
            "dispersion": 0.0044,
            "sound": ["",10,1],
            "soundend": ["sound",1],
            "autofire": 1,
            "texturetype": "fullAuto",
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
            "recoilprone": "recoil_auto_primary_prone_3outof10",
            "aidispersioncoefy": 3,
            "aidispersioncoefx": 2,
            "soundburst": 0,
            "multiplier": 1,
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundloop": [],
            "weaponsoundeffect": "",
            "useaction": 0,
            "useactiontitle": "",
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "requiredoptictype": -1
        },
        # Class: CfgWeapons|gatling_30mm_base|short [Indent level: 1],
        "short": {
            "aiburstterminable": 1,
            "showtoplayer": 0,
            "burst": 12,
            "burstrangemax": 32,
            "airateoffire": 1,
            "airateoffiredispersion": 2,
            "airateoffiredistance": 200,
            "minrange": 200,
            "minrangeprobab": 0.65,
            "midrange": 400,
            "midrangeprobab": 0.75,
            "maxrange": 1000,
            "maxrangeprobab": 0.7,
            "displayname": "300rpm",
            "sounds": ["StandardSound"],
            # Class: CfgWeapons|gatling_30mm_base|LowROF|StandardSound [Indent level: 2],
            "standardsound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_02_burst",5.62341,1,1500,[2,45447]],
                "soundbegin": ["begin1",1]
            },
            "soundcontinuous": 1,
            "flash": "gunfire",
            "flashsize": 0.1,
            # Recoil Array: recoil,
            "recoil": [],
            "recoil": "Empty",
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "ffcount": 6,
            "reloadtime": 0.08,
            "dispersion": 0.0044,
            "sound": ["",10,1],
            "soundend": ["sound",1],
            "autofire": 1,
            "texturetype": "fullAuto",
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
            "recoilprone": "recoil_auto_primary_prone_3outof10",
            "aidispersioncoefy": 3,
            "aidispersioncoefx": 2,
            "soundburst": 0,
            "multiplier": 1,
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundloop": [],
            "weaponsoundeffect": "",
            "useaction": 0,
            "useactiontitle": "",
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "requiredoptictype": -1
        },
        # Class: CfgWeapons|gatling_30mm_base|medium [Indent level: 1],
        "medium": {
            "aiburstterminable": 1,
            "showtoplayer": 0,
            "burst": 12,
            "burstrangemax": 28,
            "airateoffire": 2,
            "airateoffiredispersion": 2,
            "airateoffiredistance": 800,
            "minrange": 800,
            "minrangeprobab": 0.7,
            "midrange": 1400,
            "midrangeprobab": 0.4,
            "maxrange": 1800,
            "maxrangeprobab": 0.15,
            "displayname": "300rpm",
            "sounds": ["StandardSound"],
            # Class: CfgWeapons|gatling_30mm_base|LowROF|StandardSound [Indent level: 2],
            "standardsound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_02_burst",5.62341,1,1500,[2,45447]],
                "soundbegin": ["begin1",1]
            },
            "soundcontinuous": 1,
            "flash": "gunfire",
            "flashsize": 0.1,
            # Recoil Array: recoil,
            "recoil": [],
            "recoil": "Empty",
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "ffcount": 6,
            "reloadtime": 0.08,
            "dispersion": 0.0044,
            "sound": ["",10,1],
            "soundend": ["sound",1],
            "autofire": 1,
            "texturetype": "fullAuto",
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
            "recoilprone": "recoil_auto_primary_prone_3outof10",
            "aidispersioncoefy": 3,
            "aidispersioncoefx": 2,
            "soundburst": 0,
            "multiplier": 1,
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundloop": [],
            "weaponsoundeffect": "",
            "useaction": 0,
            "useactiontitle": "",
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "requiredoptictype": -1
        },
        # Class: CfgWeapons|gatling_30mm_base|far [Indent level: 1],
        "far": {
            "aiburstterminable": 1,
            "showtoplayer": 0,
            "burst": 9,
            "burstrangemax": 20,
            "airateoffire": 4,
            "airateoffiredispersion": 4,
            "airateoffiredistance": 1400,
            "minrange": 1400,
            "minrangeprobab": 0.5,
            "midrange": 1800,
            "midrangeprobab": 0.15,
            "maxrange": 2500,
            "maxrangeprobab": 0.05,
            "displayname": "300rpm",
            "sounds": ["StandardSound"],
            # Class: CfgWeapons|gatling_30mm_base|LowROF|StandardSound [Indent level: 2],
            "standardsound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_02_burst",5.62341,1,1500,[2,45447]],
                "soundbegin": ["begin1",1]
            },
            "soundcontinuous": 1,
            "flash": "gunfire",
            "flashsize": 0.1,
            # Recoil Array: recoil,
            "recoil": [],
            "recoil": "Empty",
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "ffcount": 6,
            "reloadtime": 0.08,
            "dispersion": 0.0044,
            "sound": ["",10,1],
            "soundend": ["sound",1],
            "autofire": 1,
            "texturetype": "fullAuto",
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
            "recoilprone": "recoil_auto_primary_prone_3outof10",
            "aidispersioncoefy": 3,
            "aidispersioncoefx": 2,
            "soundburst": 0,
            "multiplier": 1,
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundloop": [],
            "weaponsoundeffect": "",
            "useaction": 0,
            "useactiontitle": "",
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "requiredoptictype": -1
        },
        "type": 65536,
        # Class: CfgWeapons|CannonCore|GunClouds [Indent level: 1],
        "gunclouds": {
        },
        "access": 3,
        "value": 2,
        "picture": "",
        "uipicture": "",
        "ammo": "",
        "cursorsize": 1,
        "showaimcursorinternal": 1,
        "cursoraimon": "",
        "laser": 0,
        "hiddenselections": [],
        "hiddenselectionstextures": [],
        "hiddenunderwaterselections": [],
        "shownunderwaterselections": [],
        "hiddenunderwaterselectionstextures": [],
        "simulation": "Weapon",
        "count": 0,
        "multiplier": 1,
        "magazinereloadtime": 0,
        "magazinereloadswitchphase": 1,
        "sound": ["",1,1],
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundend": ["sound",1],
        "soundloop": ["sound",1],
        "soundcontinuous": 0,
        "weaponsoundeffect": "",
        "soundburst": 1,
        "drysound": ["",1,1],
        "zeroingsound": ["",1,1],
        "reloadsound": ["",1,1],
        "changefiremodesound": ["",1,1],
        "reloadmagazinesound": ["",1,1],
        "emptysound": ["",1,1],
        "soundbullet": ["emptySound",1],
        "initspeed": 0,
        "irdistance": 0,
        "irdotintensity": 0.001,
        "dispersion": 0.002,
        "lockacquire": 1,
        "enableattack": 1,
        "ffmagnitude": 0,
        "fffrequency": 1,
        "ffcount": 1,
        # Recoil Array: recoil,
        "recoil": [],
        "recoil": "empty",
        "recoilprone": "",
        "maxrecoilsway": 0.008,
        "swaydecayspeed": 2,
        "model": "",
        "modelspecial": "",
        "modelmagazine": "",
        "muzzlepos": "usti hlavne",
        "muzzleend": "konec hlavne",
        "irlaserpos": "laser pos",
        "irlaserend": "laser dir",
        "cartridgepos": "nabojnicestart",
        "cartridgevel": "nabojniceend",
        "selectionfireanim": "zasleh",
        "memorypointcamera": "eye",
        "firespreadangle": 3,
        "usemodeloptics": 1,
        "opticsid": 0,
        "modeloptics": "",
        "opticsppeffects": [],
        "opticsflare": 1,
        "optics": 1,
        "forceoptics": 0,
        "useasbinocular": 0,
        "opticsdisableperipherialvision": 0.67,
        "opticszoommin": 0.25,
        "opticszoommax": 1.25,
        "opticszoominit": 0.75,
        "distancezoommin": 400,
        "distancezoommax": 400,
        "primary": 10,
        "showswitchaction": 0,
        "showempty": 1,
        "autoreload": 1,
        "showtoplayer": 1,
        "canshootinwater": 0,
        "airateoffire": 5,
        "airateoffiredistance": 500,
        "airateoffiredispersion": 0,
        "firelightduration": 0.05,
        "firelightintensity": 0.2,
        "firelightdiffuse": [0.937,0.631,0.259],
        "firelightambient": [0,0,0],
        # Class: CfgWeapons|Default|Eventhandlers [Indent level: 1],
        "eventhandlers": {
        },
        "backgroundreload": 0,
        "reloadaction": "",
        "muzzles": ["this"],
        "useaction": 0,
        "useactiontitle": "",
        "candrop": 1,
        "weaponlockdelay": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "weight": 0,
        "minrange": 1,
        "minrangeprobab": 0.3,
        "midrange": 150,
        "midrangeprobab": 0.58,
        "maxrange": 500,
        "maxrangeprobab": 0.04,
        "handanim": [],
        "lockingtargetsound": ["",0.000316228,2],
        "lockedtargetsound": ["",0.000316228,6],
        "detectrange": 0,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "fireanims": [],
        # Class: CfgWeapons|Default|Library [Indent level: 1],
        "library": {
            "libtextdesc": ""
        },
        "descriptionshort": "",
        # Class: CfgWeapons|Default|GunFire [Indent level: 1],
        "gunfire": {
            "access": 0,
            "cloudletduration": 0.2,
            "cloudletanimperiod": 1,
            "cloudletsize": 1,
            "cloudletalpha": 1,
            "cloudletgrowup": 0.2,
            "cloudletfadein": 0.01,
            "cloudletfadeout": 0.5,
            "cloudletaccy": 0,
            "cloudletminyspeed": -100,
            "cloudletmaxyspeed": 100,
            "cloudletshape": "cloudletFire",
            "cloudletcolor": [1,1,1,0],
            "cloudletdensitycoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourcesize": 0.5,
            "timetolive": 0,
            "initt": 4500,
            "deltat": -3000,
            # Class: CfgWeapons|Default|GunFire|Table [Indent level: 2],
            "table": {
                # Class: CfgWeapons|Default|GunFire|Table|T0 [Indent level: 3]
                "t0": {
                    "maxt": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T1 [Indent level: 3],
                "t1": {
                    "maxt": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T2 [Indent level: 3],
                "t2": {
                    "maxt": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T3 [Indent level: 3],
                "t3": {
                    "maxt": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T4 [Indent level: 3],
                "t4": {
                    "maxt": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T5 [Indent level: 3],
                "t5": {
                    "maxt": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T6 [Indent level: 3],
                "t6": {
                    "maxt": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T7 [Indent level: 3],
                "t7": {
                    "maxt": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T8 [Indent level: 3],
                "t8": {
                    "maxt": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T9 [Indent level: 3],
                "t9": {
                    "maxt": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T10 [Indent level: 3],
                "t10": {
                    "maxt": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T11 [Indent level: 3],
                "t11": {
                    "maxt": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T12 [Indent level: 3],
                "t12": {
                    "maxt": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T13 [Indent level: 3],
                "t13": {
                    "maxt": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T14 [Indent level: 3],
                "t14": {
                    "maxt": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T15 [Indent level: 3],
                "t15": {
                    "maxt": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T16 [Indent level: 3],
                "t16": {
                    "maxt": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T17 [Indent level: 3],
                "t17": {
                    "maxt": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T18 [Indent level: 3],
                "t18": {
                    "maxt": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T19 [Indent level: 3],
                "t19": {
                    "maxt": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T20 [Indent level: 3],
                "t20": {
                    "maxt": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T21 [Indent level: 3],
                "t21": {
                    "maxt": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T22 [Indent level: 3],
                "t22": {
                    "maxt": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        "texturetype": "default",
        "inertia": 0.5,
        "aimtransitionspeed": 1
    },
    "burst": 5,
    "reloadtime": 0.02,
    "shotfromturret": 1,
    "fcsmaxleadspeed": 30.5556,
    "fcszeroingdelay": 0.5,
    "maxzeroing": 2500,
    # Class: CfgWeapons|gatling_30mm_base|LowROF [Indent level: 1],
    "lowrof": {
        "displayname": "300rpm",
        "burst": 5,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons|gatling_30mm_base|LowROF|StandardSound [Indent level: 2],
        "standardsound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_02_burst",5.62341,1,1500,[2,45447]],
            "soundbegin": ["begin1",1]
        },
        "soundcontinuous": 1,
        "flash": "gunfire",
        "flashsize": 0.1,
        # Recoil Array: recoil,
        "recoil": [],
        "recoil": "Empty",
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "ffcount": 6,
        "reloadtime": 0.08,
        "dispersion": 0.0044,
        "airateoffire": 1,
        "airateoffiredistance": 10,
        "minrange": 0,
        "minrangeprobab": 0.01,
        "midrange": 1,
        "midrangeprobab": 0.01,
        "maxrange": 2,
        "maxrangeprobab": 0.01,
        "sound": ["",10,1],
        "soundend": ["sound",1],
        "autofire": 1,
        "texturetype": "fullAuto",
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "recoilprone": "recoil_auto_primary_prone_3outof10",
        "aidispersioncoefy": 3,
        "aidispersioncoefx": 2,
        "soundburst": 0,
        "multiplier": 1,
        "burstrangemax": -1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundloop": [],
        "weaponsoundeffect": "",
        "useaction": 0,
        "useactiontitle": "",
        "showtoplayer": 1,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "requiredoptictype": -1,
        "airateoffiredispersion": 1
    },
    # Class: CfgWeapons|gatling_30mm_base|near [Indent level: 1],
    "near": {
        "aiburstterminable": 1,
        "showtoplayer": 0,
        "burst": 16,
        "burstrangemax": 37,
        "airateoffire": 0.5,
        "airateoffiredispersion": 1,
        "airateoffiredistance": 50,
        "minrange": 0,
        "minrangeprobab": 0.1,
        "midrange": 50,
        "midrangeprobab": 0.65,
        "maxrange": 400,
        "maxrangeprobab": 0.75,
        "displayname": "300rpm",
        "sounds": ["StandardSound"],
        # Class: CfgWeapons|gatling_30mm_base|LowROF|StandardSound [Indent level: 2],
        "standardsound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons_vehicles|gatling_30mm|30mm_02_burst",5.62341,1,1500,[2,45447]],
            "soundbegin": ["begin1",1]
        },
        "soundcontinuous": 1,
        "flash": "gunfire",
        "flashsize": 0.1,
        # Recoil Array: recoil,
        "recoil": [],
        "recoil": "Empty",
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "ffcount": 6,
        "reloadtime": 0.08,
        "dispersion": 0.0044,
        "sound": ["",10,1],
        "soundend": ["sound",1],
        "autofire": 1,
        "texturetype": "fullAuto",
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "recoilprone": "recoil_auto_primary_prone_3outof10",
        "aidispersioncoefy": 3,
        "aidispersioncoefx": 2,
        "soundburst": 0,
        "multiplier": 1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundloop": [],
        "weaponsoundeffect": "",
        "useaction": 0,
        "useactiontitle": "",
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "requiredoptictype": -1
    },
    "type": 65536,
    # Class: CfgWeapons|CannonCore|GunClouds [Indent level: 1],
    "gunclouds": {
    },
    "access": 3,
    "value": 2,
    "picture": "",
    "uipicture": "",
    "ammo": "",
    "showaimcursorinternal": 1,
    "cursoraimon": "",
    "laser": 0,
    "hiddenselections": [],
    "hiddenselectionstextures": [],
    "hiddenunderwaterselections": [],
    "shownunderwaterselections": [],
    "hiddenunderwaterselectionstextures": [],
    "simulation": "Weapon",
    "count": 0,
    "multiplier": 1,
    "magazinereloadtime": 0,
    "magazinereloadswitchphase": 1,
    "sound": ["",1,1],
    "soundbegin": ["sound",1],
    "soundbeginwater": ["sound",1],
    "soundclosure": ["sound",1],
    "soundend": ["sound",1],
    "soundloop": ["sound",1],
    "soundcontinuous": 0,
    "weaponsoundeffect": "",
    "soundburst": 1,
    "drysound": ["",1,1],
    "zeroingsound": ["",1,1],
    "reloadsound": ["",1,1],
    "changefiremodesound": ["",1,1],
    "reloadmagazinesound": ["",1,1],
    "emptysound": ["",1,1],
    "soundbullet": ["emptySound",1],
    "initspeed": 0,
    "irdistance": 0,
    "irdotintensity": 0.001,
    "dispersion": 0.002,
    "lockacquire": 1,
    "enableattack": 1,
    "ffmagnitude": 0,
    "fffrequency": 1,
    "ffcount": 1,
    # Recoil Array: recoil,
    "recoil": [],
    "recoil": "empty",
    "recoilprone": "",
    "maxrecoilsway": 0.008,
    "swaydecayspeed": 2,
    "model": "",
    "modelspecial": "",
    "modelmagazine": "",
    "muzzlepos": "usti hlavne",
    "muzzleend": "konec hlavne",
    "irlaserpos": "laser pos",
    "irlaserend": "laser dir",
    "cartridgepos": "nabojnicestart",
    "cartridgevel": "nabojniceend",
    "selectionfireanim": "zasleh",
    "memorypointcamera": "eye",
    "firespreadangle": 3,
    "usemodeloptics": 1,
    "opticsid": 0,
    "modeloptics": "",
    "opticsppeffects": [],
    "opticsflare": 1,
    "optics": 1,
    "forceoptics": 0,
    "useasbinocular": 0,
    "opticsdisableperipherialvision": 0.67,
    "opticszoommin": 0.25,
    "opticszoommax": 1.25,
    "opticszoominit": 0.75,
    "distancezoommin": 400,
    "distancezoommax": 400,
    "primary": 10,
    "showswitchaction": 0,
    "showempty": 1,
    "autoreload": 1,
    "showtoplayer": 1,
    "canshootinwater": 0,
    "airateoffire": 5,
    "airateoffiredistance": 500,
    "airateoffiredispersion": 0,
    "firelightduration": 0.05,
    "firelightintensity": 0.2,
    "firelightdiffuse": [0.937,0.631,0.259],
    "firelightambient": [0,0,0],
    # Class: CfgWeapons|Default|Eventhandlers [Indent level: 1],
    "eventhandlers": {
    },
    "backgroundreload": 0,
    "reloadaction": "",
    "useaction": 0,
    "useactiontitle": "",
    "candrop": 1,
    "weaponlockdelay": 0,
    "weaponlocksystem": 0,
    "cmimmunity": 1,
    "weight": 0,
    "minrange": 1,
    "minrangeprobab": 0.3,
    "midrange": 150,
    "midrangeprobab": 0.58,
    "maxrange": 500,
    "maxrangeprobab": 0.04,
    "handanim": [],
    "lockingtargetsound": ["",0.000316228,2],
    "lockedtargetsound": ["",0.000316228,6],
    "detectrange": 0,
    "artillerydispersion": 1,
    "artillerycharge": 1,
    "fireanims": [],
    # Class: CfgWeapons|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "descriptionshort": "",
    # Class: CfgWeapons|Default|GunFire [Indent level: 1],
    "gunfire": {
        "access": 0,
        "cloudletduration": 0.2,
        "cloudletanimperiod": 1,
        "cloudletsize": 1,
        "cloudletalpha": 1,
        "cloudletgrowup": 0.2,
        "cloudletfadein": 0.01,
        "cloudletfadeout": 0.5,
        "cloudletaccy": 0,
        "cloudletminyspeed": -100,
        "cloudletmaxyspeed": 100,
        "cloudletshape": "cloudletFire",
        "cloudletcolor": [1,1,1,0],
        "cloudletdensitycoef": -1,
        "interval": -0.01,
        "size": 3,
        "sourcesize": 0.5,
        "timetolive": 0,
        "initt": 4500,
        "deltat": -3000,
        # Class: CfgWeapons|Default|GunFire|Table [Indent level: 2],
        "table": {
            # Class: CfgWeapons|Default|GunFire|Table|T0 [Indent level: 3]
            "t0": {
                "maxt": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T1 [Indent level: 3],
            "t1": {
                "maxt": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T2 [Indent level: 3],
            "t2": {
                "maxt": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T3 [Indent level: 3],
            "t3": {
                "maxt": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T4 [Indent level: 3],
            "t4": {
                "maxt": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T5 [Indent level: 3],
            "t5": {
                "maxt": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T6 [Indent level: 3],
            "t6": {
                "maxt": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T7 [Indent level: 3],
            "t7": {
                "maxt": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T8 [Indent level: 3],
            "t8": {
                "maxt": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T9 [Indent level: 3],
            "t9": {
                "maxt": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T10 [Indent level: 3],
            "t10": {
                "maxt": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T11 [Indent level: 3],
            "t11": {
                "maxt": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T12 [Indent level: 3],
            "t12": {
                "maxt": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T13 [Indent level: 3],
            "t13": {
                "maxt": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T14 [Indent level: 3],
            "t14": {
                "maxt": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T15 [Indent level: 3],
            "t15": {
                "maxt": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T16 [Indent level: 3],
            "t16": {
                "maxt": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T17 [Indent level: 3],
            "t17": {
                "maxt": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T18 [Indent level: 3],
            "t18": {
                "maxt": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T19 [Indent level: 3],
            "t19": {
                "maxt": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T20 [Indent level: 3],
            "t20": {
                "maxt": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T21 [Indent level: 3],
            "t21": {
                "maxt": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T22 [Indent level: 3],
            "t22": {
                "maxt": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    "texturetype": "default",
    "inertia": 0.5,
    "aimtransitionspeed": 1,
}