rhs_weap_m249_base = {
    "dlc": "RHS_USAF",
    "hasbipod": 1,
    "scope": 0,
    "uipicture": "A3|weapons_f|data|UI|icon_mg_CA.paa",
    # Compatible Magazines: magazines parameter (+ inherited),
    "magazines": [
        "rhsusf_100rnd_556x45_soft_pouch","rhsusf_200rnd_556x45_soft_pouch","rhsusf_100rnd_556x45_m200_soft_pouch","rhs_mag_30rnd_556x45_mk318_stanag",
        "rhs_mag_30rnd_556x45_mk262_stanag","rhs_mag_30rnd_556x45_m855a1_stanag","rhs_mag_30rnd_556x45_m855a1_stanag_tracer_red","rhs_mag_30rnd_556x45_m200_stanag",
        "30rnd_556x45_stanag","30rnd_556x45_stanag_tracer_red","30rnd_556x45_stanag_tracer_green","30rnd_556x45_stanag_tracer_yellow",
        "200rnd_65x39_cased_box","200rnd_65x39_cased_box_tracer","200rnd_65x39_cased_box_red","200rnd_65x39_cased_box_tracer_red",
    ],
    "reloadaction": "GestureReloadM200",
    "cursor": "mg",
    "cursoraim": "EmptyCursor",
    "namesound": "Mgun",
    "maxrecoilsway": 0.015,
    "swaydecayspeed": 1.25,
    # Recoil Class: recoil,
    # Class: CfgRecoils|recoil_mk200 [Indent level: 0],
    "recoil": {
        "muzzleouter": [0.4,0.6,0.6,0.2],
        "kickback": [0.03,0.06],
        "temporary": 0.005,
        "muzzleinner": [0,0,0.1,0.1],
        "permanent": 0.1
    },
    "recoil": "recoil_mk200",
    "opticszoommin": 0.275,
    "opticszoommax": 1,
    "opticszoominit": 0.75,
    "distancezoommin": 300,
    "distancezoommax": 300,
    "dexterity": 2.8,
    "aimtransitionspeed": 0.5,
    "discretedistance": [300,400,500,600,700,800,900,1000],
    "discretedistancecamerapoint": ["eye","eye_400","eye_500","eye_600","eye_700","eye_800","eye_900","eye_1000"],
    "discretedistanceinitindex": 2,
    "cameradir": "eye_look",
    "maxzeroing": 1000,
    "descriptionshort": "Light Machine Gun<br />Caliber: 5.56x45mm NATO",
    # Class: CfgWeapons|rhs_weap_M249_base|Library [Indent level: 1],
    "library": {
        "libtextdesc": "The M249 provides infantry squads with the heavy volume of fire of a machine gun combined with accuracy and portability approaching that of a rifle."
    },
    # Class: CfgWeapons|rhs_weap_M249_base|ItemInfo [Indent level: 1],
    "iteminfo": {
        "priority": 1,
        "rmbhint": "M249",
        "onhovertext": "TODO M249 DSS"
    },
    # Class: CfgWeapons|rhs_weap_M249_base|WeaponSlotsInfo [Indent level: 1],
    "weaponslotsinfo": {
        "mass": 151.8,
        "allowedslots": [901],
        # Class: CfgWeapons|rhs_weap_M249_base|WeaponSlotsInfo|CowsSlot [Indent level: 2],
        "cowsslot": {
            # Class: asdg_OpticRail1913_short|compatibleItems [Indent level: 0]
            "compatibleitems": {
                "rhs_acc_rakurspm": 1,
                "rhs_acc_dh520x56": 1,
                "rhs_acc_ekp8_18": 1,
                "rhs_acc_ekp8_18b": 1,
                "rhs_acc_ekp8_18c": 1,
                "rhs_acc_ekp8_18d": 1,
                "rhs_acc_1p87": 1,
                "rhs_acc_okp7_picatinny": 1,
                "optic_nightstalker": 1,
                "optic_tws": 1,
                "optic_tws_mg": 1,
                "optic_nvs": 1,
                "optic_sos": 1,
                "optic_sos_khk_f": 1,
                "optic_mrco": 1,
                "optic_arco": 1,
                "optic_arco_ghex_f": 1,
                "optic_arco_blk_f": 1,
                "optic_aco": 1,
                "optic_aco_grn": 1,
                "optic_aco_smg": 1,
                "optic_aco_grn_smg": 1,
                "optic_hamr": 1,
                "optic_hamr_khk_f": 1,
                "optic_holosight": 1,
                "optic_holosight_smg": 1,
                "optic_holosight_blk_f": 1,
                "optic_holosight_khk_f": 1,
                "optic_holosight_smg_blk_f": 1,
                "optic_dms": 1,
                "optic_dms_ghex_f": 1,
                "optic_lrps": 1,
                "optic_lrps_ghex_f": 1,
                "optic_lrps_tna_f": 1,
                "optic_ams": 1,
                "optic_ams_khk": 1,
                "optic_ams_snd": 1,
                "optic_khs_blk": 1,
                "optic_khs_hex": 1,
                "optic_khs_old": 1,
                "optic_khs_tan": 1,
                "optic_erco_blk_f": 1,
                "optic_erco_khk_f": 1,
                "optic_erco_snd_f": 1,
                "rhsusf_acc_leupoldmk4": 1,
                "rhsusf_acc_leupoldmk4_d": 1,
                "rhsusf_acc_leupoldmk4_wd": 1,
                "rhsusf_acc_leupoldmk4_2": 1,
                "rhsusf_acc_leupoldmk4_2_mrds": 1,
                "rhsusf_acc_leupoldmk4_2_d": 1,
                "rhsusf_acc_premier": 1,
                "rhsusf_acc_premier_mrds": 1,
                "rhsusf_acc_premier_low": 1,
                "rhsusf_acc_m8541": 1,
                "rhsusf_acc_m8541_d": 1,
                "rhsusf_acc_m8541_wd": 1,
                "rhsusf_acc_m8541_mrds": 1,
                "rhsusf_acc_m8541_low": 1,
                "rhsusf_acc_m8541_low_d": 1,
                "rhsusf_acc_m8541_low_wd": 1,
                "rhsusf_acc_nxs_3515x50_md": 1,
                "rhsusf_acc_nxs_3515x50f1_md": 1,
                "rhsusf_acc_nxs_3515x50f1_md_sun": 1,
                "rhsusf_acc_nxs_3515x50f1_h58": 1,
                "rhsusf_acc_nxs_3515x50f1_h58_sun": 1,
                "rhsusf_acc_nxs_5522x56_md": 1,
                "rhsusf_acc_nxs_5522x56_md_sun": 1,
                "rhsusf_acc_eotech": 1,
                "rhsusf_acc_eotech_552": 1,
                "rhsusf_acc_eotech_552_d": 1,
                "rhsusf_acc_eotech_552_wd": 1,
                "rhsusf_acc_eotech_xps3": 1,
                "rhsusf_acc_g33_xps3": 1,
                "rhsusf_acc_g33_xps3_flip": 1,
                "rhsusf_acc_g33_xps3_tan": 1,
                "rhsusf_acc_g33_xps3_tan_flip": 1,
                "rhsusf_acc_g33_t1": 1,
                "rhsusf_acc_g33_t1_flip": 1,
                "rhsusf_acc_compm4": 1,
                "rhsusf_acc_t1_high": 1,
                "rhsusf_acc_t1_low": 1,
                "rhsusf_acc_rx01": 1,
                "rhsusf_acc_rx01_nofilter": 1,
                "rhsusf_acc_rx01_tan": 1,
                "rhsusf_acc_rx01_nofilter_tan": 1,
                "rhsusf_acc_rm05": 1,
                "rhsusf_acc_mrds": 1,
                "rhsusf_acc_mrds_c": 1,
                "rhsusf_acc_acog": 1,
                "rhsusf_acc_acog2": 1,
                "rhsusf_acc_acog3": 1,
                "rhsusf_acc_acog_wd": 1,
                "rhsusf_acc_acog_d": 1,
                "rhsusf_acc_acog_sa": 1,
                "rhsusf_acc_acog_usmc": 1,
                "rhsusf_acc_acog2_usmc": 1,
                "rhsusf_acc_acog3_usmc": 1,
                "rhsusf_acc_acog_rmr": 1,
                "rhsusf_acc_acog_pip": 1,
                "rhsusf_acc_acog2_pip": 1,
                "rhsusf_acc_acog3_pip": 1,
                "rhsusf_acc_acog_wd_pip": 1,
                "rhsusf_acc_acog_d_pip": 1,
                "rhsusf_acc_acog_sa_pip": 1,
                "rhsusf_acc_acog_usmc_pip": 1,
                "rhsusf_acc_acog2_usmc_pip": 1,
                "rhsusf_acc_acog3_usmc_pip": 1,
                "rhsusf_acc_acog_rmr_pip": 1,
                "rhsusf_acc_acog_3d": 1,
                "rhsusf_acc_acog2_3d": 1,
                "rhsusf_acc_acog3_3d": 1,
                "rhsusf_acc_acog_wd_3d": 1,
                "rhsusf_acc_acog_d_3d": 1,
                "rhsusf_acc_acog_sa_3d": 1,
                "rhsusf_acc_acog_usmc_3d": 1,
                "rhsusf_acc_acog2_usmc_3d": 1,
                "rhsusf_acc_acog3_usmc_3d": 1,
                "rhsusf_acc_acog_rmr_3d": 1,
                "rhsusf_acc_elcan": 1,
                "rhsusf_acc_elcan_ard": 1,
                "rhsusf_acc_elcan_3d": 1,
                "rhsusf_acc_elcan_ard_3d": 1,
                "rhsusf_acc_elcan_pip": 1,
                "rhsusf_acc_elcan_ard_pip": 1,
                "rhsusf_acc_su230": 1,
                "rhsusf_acc_su230_mrds": 1,
                "rhsusf_acc_su230a": 1,
                "rhsusf_acc_su230a_mrds": 1,
                "rhsusf_acc_su230_c": 1,
                "rhsusf_acc_su230_mrds_c": 1,
                "rhsusf_acc_su230a_c": 1,
                "rhsusf_acc_su230a_mrds_c": 1,
                "rhsusf_acc_su230_3d": 1,
                "rhsusf_acc_su230_mrds_3d": 1,
                "rhsusf_acc_su230a_3d": 1,
                "rhsusf_acc_su230a_mrds_3d": 1,
                "rhsusf_acc_su230_c_3d": 1,
                "rhsusf_acc_su230_mrds_c_3d": 1,
                "rhsusf_acc_su230a_c_3d": 1,
                "rhsusf_acc_su230a_mrds_c_3d": 1,
                "rhsusf_acc_specterdr": 1,
                "rhsusf_acc_specterdr_3d": 1,
                "rhsusf_acc_specterdr_a": 1,
                "rhsusf_acc_specterdr_a_3d": 1,
                "rhsusf_acc_specterdr_cx": 1,
                "rhsusf_acc_specterdr_cx_3d": 1,
                "rhsusf_acc_specterdr_pvs27": 1,
                "rhsusf_acc_specterdr_d": 1,
                "rhsusf_acc_specterdr_od": 1,
                "rhsusf_acc_specterdr_d_3d": 1,
                "rhsusf_acc_specterdr_od_3d": 1,
                "rhsusf_acc_anpvs27": 1,
                "rhsusf_acc_anpas13gv1": 1,
                "rhsusf_acc_m2a1": 1,
                "rhsusf_acc_acog_mdo": 1,
                "rhsgref_acc_rx01_camo": 1,
                "rhsgref_acc_rx01_nofilter_camo": 1
            },
            "linkproxy": "A3|data_f|proxies|weapon_slots|TOP",
            "displayname": "Optics Slot"
        },
        # Class: CfgWeapons|rhs_weap_M249_base|WeaponSlotsInfo|PointerSlot [Indent level: 2],
        "pointerslot": {
            "iconposition": [0,0],
            "iconscale": 1,
            "iconpicture": "A3|Weapons_F|Data|clear_empty.paa",
            "iconpinpoint": "Left",
            # Class: rhs_western_rifle_laser_slot|compatibleItems [Indent level: 0],
            "compatibleitems": {
                "rhsusf_acc_anpeq15": 0,
                "rhsusf_acc_anpeq15_top": 0,
                "rhsusf_acc_anpeq15_light": 0,
                "rhsusf_acc_anpeq15_bk": 0,
                "rhsusf_acc_anpeq15_bk_top": 0,
                "rhsusf_acc_anpeq15_bk_light": 0,
                "rhsusf_acc_anpeq15_wmx": 0,
                "rhsusf_acc_anpeq15_wmx_light": 0,
                "rhsusf_acc_anpeq16a_top": 0,
                "rhsusf_acc_anpeq16a_light_top": 0,
                "rhsusf_acc_anpeq16a_top_h": 0,
                "rhsusf_acc_anpeq16a_light_top_h": 0,
                "rhs_acc_2dpzenit_ris": 1,
                "rhs_acc_perst1ik_ris": 1,
                "rhs_acc_perst3": 1,
                "acc_flashlight": 1,
                "acc_pointer_ir": 1,
                "rhsusf_acc_wmx": 1,
                "rhsusf_acc_wmx_bk": 1,
                "rhsusf_acc_m952v": 1,
                "rhsusf_acc_anpeq15a": 1,
                "rhsusf_acc_anpeq15_h": 1,
                "rhsusf_acc_anpeq15_light_h": 1,
                "rhsusf_acc_anpeq15_top_h": 1,
                "rhsusf_acc_anpeq15_sc": 1,
                "rhsusf_acc_anpeq15_light_sc": 1,
                "rhsusf_acc_anpeq15_top_sc": 1,
                "rhsusf_acc_anpeq15side": 1,
                "rhsusf_acc_anpeq15_bk_h": 1,
                "rhsusf_acc_anpeq15_bk_light_h": 1,
                "rhsusf_acc_anpeq15_bk_top_h": 1,
                "rhsusf_acc_anpeq15_bk_sc": 1,
                "rhsusf_acc_anpeq15_bk_light_sc": 1,
                "rhsusf_acc_anpeq15_bk_top_sc": 1,
                "rhsusf_acc_anpeq15side_bk": 1,
                "rhsusf_acc_anpeq15_wmx_h": 1,
                "rhsusf_acc_anpeq15_wmx_light_h": 1,
                "rhsusf_acc_anpeq15_wmx_sc": 1,
                "rhsusf_acc_anpeq15_wmx_light_sc": 1,
                "rhsusf_acc_anpeq16a": 1,
                "rhsusf_acc_anpeq16a_light": 1,
                "rhsusf_acc_anpeq16a_top_sc": 1,
                "rhsusf_acc_anpeq16a_light_top_sc": 1
            },
            "linkproxy": "a3|data_f|proxies|weapon_slots|side",
            "displayname": "Pointer Slot"
        }
    },
    # Class: CfgWeapons|rhs_weap_M249_base|GunParticles [Indent level: 1],
    "gunparticles": {
        # Class: CfgWeapons|rhs_weap_M249_base|GunParticles|M249_AmmoBeltLinkEject [Indent level: 2]
        "m249_ammobeltlinkeject": {
            "positionname": "ammobeltlinks_start",
            "directionname": "ammobeltlinks_end",
            "effectname": "MachineGunEject2"
        },
        # Class: CfgWeapons|rhs_weap_M249_base|GunParticles|M249_556Cartridge [Indent level: 2],
        "m249_556cartridge": {
            "positionname": "shelleject_start",
            "directionname": "shelleject_end",
            "effectname": "RHSUSF_556Cartridge"
        },
        # Class: CfgWeapons|rhs_weap_M249_base|GunParticles|M249_WhiteGas [Indent level: 2],
        "m249_whitegas": {
            "positionname": "usti hlavne",
            "directionname": "konec hlavne",
            "effectname": "RifleAssaultCloud"
        },
        # Class: CfgWeapons|rhs_weap_M249_base|GunParticles|M249_RHSUSF_BarrelRefract [Indent level: 2],
        "m249_rhsusf_barrelrefract": {
            "positionname": "usti hlavne",
            "directionname": "usti hlavne up",
            "effectname": "RHSUSF_BarrelRefractHeavy"
        }
    },
    "bullet1": ["A3|sounds_f|weapons|shells|5_56|metal_556_01.wss",0.1,1,15],
    "bullet2": ["A3|sounds_f|weapons|shells|5_56|metal_556_02.wss",0.1,1,15],
    "bullet3": ["A3|sounds_f|weapons|shells|5_56|metal_556_03.wss",0.177828,1,15],
    "bullet4": ["A3|sounds_f|weapons|shells|5_56|metal_556_04.wss",0.177828,1,15],
    "bullet5": ["A3|sounds_f|weapons|shells|5_56|asphlat_556_01.wss",0.1,1,15],
    "bullet6": ["A3|sounds_f|weapons|shells|5_56|asphlat_556_02.wss",0.1,1,15],
    "bullet7": ["A3|sounds_f|weapons|shells|5_56|asphlat_556_03.wss",0.1,1,15],
    "bullet8": ["A3|sounds_f|weapons|shells|5_56|asphlat_556_04.wss",0.1,1,15],
    "bullet9": ["A3|sounds_f|weapons|shells|5_56|grass_556_01.wss",0.01,1,15],
    "bullet10": ["A3|sounds_f|weapons|shells|5_56|grass_556_02.wss",0.01,1,15],
    "bullet11": ["A3|sounds_f|weapons|shells|5_56|grass_556_03.wss",0.01,1,15],
    "bullet12": ["A3|sounds_f|weapons|shells|5_56|grass_556_04.wss",0.01,1,15],
    "soundbullet": ["bullet1",0.083,"bullet2",0.083,"bullet3",0.083,"bullet4",0.083,"bullet5",0.083,"bullet6",0.083,"bullet7",0.083,"bullet8",0.083,"bullet9",0.083,"bullet10",0.083,"bullet11",0.083,"bullet12",0.083],
    "drysound": ["A3|sounds_f|weapons|Other|dry_1",0.01,1],
    "reloadmagazinesound": ["A3|sounds_f|weapons|reloads|new_MX",0.1,1,30],
    "modes": ["FullAuto","close","short","medium","far_optic1","far_optic2"],
    # Class: CfgWeapons|rhs_weap_M249_base|FullAuto [Indent level: 1],
    "fullauto": {
        "reloadtime": 0.075,
        "dispersion": 0.00101,
        "minrange": 0,
        "minrangeprobab": 0.3,
        "midrange": 5,
        "midrangeprobab": 0.7,
        "maxrange": 10,
        "maxrangeprobab": 0.04,
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons|rhs_weap_M249_base|FullAuto|StandardSound [Indent level: 2],
        "standardsound": {
            "soundsetshot": ["RHSUSF_m249_Shot_SoundSet","RHSUSF_rifle_small_Tail_SoundSet","RHSUSF_m249_stereoLayer_SoundSet"]
        },
        # Class: CfgWeapons|rhs_weap_M249_base|FullAuto|SilencedSound [Indent level: 2],
        "silencedsound": {
            "soundsetshot": ["RHSUSF_sd_m4_Shot_SoundSet","RHSUSF_sd_Rifle1_Tail_SoundSet","RHSUSF_sd_m4_stereoLayer_SoundSet"]
        },
        "sound": ["",10,1],
        "soundend": ["sound",1],
        "soundcontinuous": 0,
        "autofire": 1,
        "displayname": "Full",
        "texturetype": "fullAuto",
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.06,0.0443316,0.0243916,0.06,0.0477255,0.0105084,0.06,0.0335835,0.0073344,0.06,0.0140372,0.003192,0.03,-0.0007206,-0.002688,0.03,-0.001765,-0.00282,0.03,-0.0018385,-0.001764,0.06,0,0],
        "recoil": "recoil_auto_primary_3outof10",
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "recoilprone": "recoil_auto_primary_prone_3outof10",
        "aidispersioncoefy": 3,
        "aidispersioncoefx": 2,
        "soundburst": 0,
        "multiplier": 1,
        "burst": 1,
        "burstrangemax": -1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "useaction": 0,
        "useactiontitle": "",
        "showtoplayer": 1,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "requiredoptictype": -1,
        "airateoffire": 2,
        "airateoffiredispersion": 1,
        "airateoffiredistance": 500
    },
    # Class: CfgWeapons|rhs_weap_M249_base|close [Indent level: 1],
    "close": {
        "burst": 10,
        "airateoffire": 0.5,
        "airateoffiredistance": 50,
        "airateoffiredispersion": 1,
        "minrange": 0,
        "minrangeprobab": 0.05,
        "midrange": 30,
        "midrangeprobab": 0.69,
        "maxrange": 50,
        "maxrangeprobab": 0.039,
        "showtoplayer": 0,
        "reloadtime": 0.075,
        "dispersion": 0.00101,
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons|rhs_weap_M249_base|FullAuto|StandardSound [Indent level: 2],
        "standardsound": {
            "soundsetshot": ["RHSUSF_m249_Shot_SoundSet","RHSUSF_rifle_small_Tail_SoundSet","RHSUSF_m249_stereoLayer_SoundSet"]
        },
        # Class: CfgWeapons|rhs_weap_M249_base|FullAuto|SilencedSound [Indent level: 2],
        "silencedsound": {
            "soundsetshot": ["RHSUSF_sd_m4_Shot_SoundSet","RHSUSF_sd_Rifle1_Tail_SoundSet","RHSUSF_sd_m4_stereoLayer_SoundSet"]
        },
        "sound": ["",10,1],
        "soundend": ["sound",1],
        "soundcontinuous": 0,
        "autofire": 1,
        "displayname": "Full",
        "texturetype": "fullAuto",
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.06,0.0443316,0.0243916,0.06,0.0477255,0.0105084,0.06,0.0335835,0.0073344,0.06,0.0140372,0.003192,0.03,-0.0007206,-0.002688,0.03,-0.001765,-0.00282,0.03,-0.0018385,-0.001764,0.06,0,0],
        "recoil": "recoil_auto_primary_3outof10",
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "recoilprone": "recoil_auto_primary_prone_3outof10",
        "aidispersioncoefy": 3,
        "aidispersioncoefx": 2,
        "soundburst": 0,
        "multiplier": 1,
        "burstrangemax": -1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "useaction": 0,
        "useactiontitle": "",
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "requiredoptictype": -1
    },
    # Class: CfgWeapons|rhs_weap_M249_base|short [Indent level: 1],
    "short": {
        "burst": 8,
        "airateoffire": 1,
        "airateoffiredistance": 300,
        "airateoffiredispersion": 2,
        "minrange": 50,
        "minrangeprobab": 0.05,
        "midrange": 150,
        "midrangeprobab": 0.69,
        "maxrange": 300,
        "maxrangeprobab": 0.039,
        "showtoplayer": 0,
        "reloadtime": 0.075,
        "dispersion": 0.00101,
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons|rhs_weap_M249_base|FullAuto|StandardSound [Indent level: 2],
        "standardsound": {
            "soundsetshot": ["RHSUSF_m249_Shot_SoundSet","RHSUSF_rifle_small_Tail_SoundSet","RHSUSF_m249_stereoLayer_SoundSet"]
        },
        # Class: CfgWeapons|rhs_weap_M249_base|FullAuto|SilencedSound [Indent level: 2],
        "silencedsound": {
            "soundsetshot": ["RHSUSF_sd_m4_Shot_SoundSet","RHSUSF_sd_Rifle1_Tail_SoundSet","RHSUSF_sd_m4_stereoLayer_SoundSet"]
        },
        "sound": ["",10,1],
        "soundend": ["sound",1],
        "soundcontinuous": 0,
        "autofire": 1,
        "displayname": "Full",
        "texturetype": "fullAuto",
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.06,0.0443316,0.0243916,0.06,0.0477255,0.0105084,0.06,0.0335835,0.0073344,0.06,0.0140372,0.003192,0.03,-0.0007206,-0.002688,0.03,-0.001765,-0.00282,0.03,-0.0018385,-0.001764,0.06,0,0],
        "recoil": "recoil_auto_primary_3outof10",
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "recoilprone": "recoil_auto_primary_prone_3outof10",
        "aidispersioncoefy": 3,
        "aidispersioncoefx": 2,
        "soundburst": 0,
        "multiplier": 1,
        "burstrangemax": -1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "useaction": 0,
        "useactiontitle": "",
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "requiredoptictype": -1
    },
    # Class: CfgWeapons|rhs_weap_M249_base|medium [Indent level: 1],
    "medium": {
        "burst": 5,
        "airateoffire": 2,
        "airateoffiredistance": 600,
        "airateoffiredispersion": 2,
        "minrange": 200,
        "minrangeprobab": 0.05,
        "midrange": 400,
        "midrangeprobab": 0.6,
        "maxrange": 600,
        "maxrangeprobab": 0.1,
        "showtoplayer": 0,
        "reloadtime": 0.075,
        "dispersion": 0.00101,
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons|rhs_weap_M249_base|FullAuto|StandardSound [Indent level: 2],
        "standardsound": {
            "soundsetshot": ["RHSUSF_m249_Shot_SoundSet","RHSUSF_rifle_small_Tail_SoundSet","RHSUSF_m249_stereoLayer_SoundSet"]
        },
        # Class: CfgWeapons|rhs_weap_M249_base|FullAuto|SilencedSound [Indent level: 2],
        "silencedsound": {
            "soundsetshot": ["RHSUSF_sd_m4_Shot_SoundSet","RHSUSF_sd_Rifle1_Tail_SoundSet","RHSUSF_sd_m4_stereoLayer_SoundSet"]
        },
        "sound": ["",10,1],
        "soundend": ["sound",1],
        "soundcontinuous": 0,
        "autofire": 1,
        "displayname": "Full",
        "texturetype": "fullAuto",
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.06,0.0443316,0.0243916,0.06,0.0477255,0.0105084,0.06,0.0335835,0.0073344,0.06,0.0140372,0.003192,0.03,-0.0007206,-0.002688,0.03,-0.001765,-0.00282,0.03,-0.0018385,-0.001764,0.06,0,0],
        "recoil": "recoil_auto_primary_3outof10",
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "recoilprone": "recoil_auto_primary_prone_3outof10",
        "aidispersioncoefy": 3,
        "aidispersioncoefx": 2,
        "soundburst": 0,
        "multiplier": 1,
        "burstrangemax": -1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "useaction": 0,
        "useactiontitle": "",
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "requiredoptictype": -1
    },
    # Class: CfgWeapons|rhs_weap_M249_base|far_optic1 [Indent level: 1],
    "far_optic1": {
        "requiredoptictype": 1,
        "showtoplayer": 0,
        "burst": 3,
        "airateoffire": 5,
        "airateoffiredistance": 900,
        "airateoffiredispersion": 4,
        "minrange": 350,
        "minrangeprobab": 0.039,
        "midrange": 550,
        "midrangeprobab": 0.5,
        "maxrange": 700,
        "maxrangeprobab": 0.0098,
        "reloadtime": 0.075,
        "dispersion": 0.00101,
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons|rhs_weap_M249_base|FullAuto|StandardSound [Indent level: 2],
        "standardsound": {
            "soundsetshot": ["RHSUSF_m249_Shot_SoundSet","RHSUSF_rifle_small_Tail_SoundSet","RHSUSF_m249_stereoLayer_SoundSet"]
        },
        # Class: CfgWeapons|rhs_weap_M249_base|FullAuto|SilencedSound [Indent level: 2],
        "silencedsound": {
            "soundsetshot": ["RHSUSF_sd_m4_Shot_SoundSet","RHSUSF_sd_Rifle1_Tail_SoundSet","RHSUSF_sd_m4_stereoLayer_SoundSet"]
        },
        "sound": ["",10,1],
        "soundend": ["sound",1],
        "soundcontinuous": 0,
        "autofire": 1,
        "displayname": "Full",
        "texturetype": "fullAuto",
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.06,0.0443316,0.0243916,0.06,0.0477255,0.0105084,0.06,0.0335835,0.0073344,0.06,0.0140372,0.003192,0.03,-0.0007206,-0.002688,0.03,-0.001765,-0.00282,0.03,-0.0018385,-0.001764,0.06,0,0],
        "recoil": "recoil_auto_primary_3outof10",
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "recoilprone": "recoil_auto_primary_prone_3outof10",
        "aidispersioncoefy": 3,
        "aidispersioncoefx": 2,
        "soundburst": 0,
        "multiplier": 1,
        "burstrangemax": -1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "useaction": 0,
        "useactiontitle": "",
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0
    },
    # Class: CfgWeapons|rhs_weap_M249_base|far_optic2 [Indent level: 1],
    "far_optic2": {
        "requiredoptictype": 2,
        "autofire": 0,
        "burst": 1,
        "minrange": 400,
        "minrangeprobab": 0.05,
        "midrange": 800,
        "midrangeprobab": 0.5,
        "maxrange": 1000,
        "maxrangeprobab": 0.0098,
        "showtoplayer": 0,
        "airateoffire": 5,
        "airateoffiredistance": 900,
        "airateoffiredispersion": 4,
        "reloadtime": 0.075,
        "dispersion": 0.00101,
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons|rhs_weap_M249_base|FullAuto|StandardSound [Indent level: 2],
        "standardsound": {
            "soundsetshot": ["RHSUSF_m249_Shot_SoundSet","RHSUSF_rifle_small_Tail_SoundSet","RHSUSF_m249_stereoLayer_SoundSet"]
        },
        # Class: CfgWeapons|rhs_weap_M249_base|FullAuto|SilencedSound [Indent level: 2],
        "silencedsound": {
            "soundsetshot": ["RHSUSF_sd_m4_Shot_SoundSet","RHSUSF_sd_Rifle1_Tail_SoundSet","RHSUSF_sd_m4_stereoLayer_SoundSet"]
        },
        "sound": ["",10,1],
        "soundend": ["sound",1],
        "soundcontinuous": 0,
        "displayname": "Full",
        "texturetype": "fullAuto",
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.06,0.0443316,0.0243916,0.06,0.0477255,0.0105084,0.06,0.0335835,0.0073344,0.06,0.0140372,0.003192,0.03,-0.0007206,-0.002688,0.03,-0.001765,-0.00282,0.03,-0.0018385,-0.001764,0.06,0,0],
        "recoil": "recoil_auto_primary_3outof10",
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.0110829,0.0021522,0.06,0.0095451,0.0007506,0.06,0.0059265,0.0004584,0.06,0.0022164,0.000171,0.06,0,0],
        "recoilprone": "recoil_auto_primary_prone_3outof10",
        "aidispersioncoefy": 3,
        "aidispersioncoefx": 2,
        "soundburst": 0,
        "multiplier": 1,
        "burstrangemax": -1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "useaction": 0,
        "useactiontitle": "",
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0
    },
    "inertia": 0.8,
    # Class: CfgWeapons|rhs_weap_M249_base|Eventhandlers [Indent level: 1],
    "eventhandlers": {
        # Class: CfgWeapons|rhs_weap_M249_base|Eventhandlers|RHSUSF_weapon_firedSoundHandler [Indent level: 2]
        "rhsusf_weapon_firedsoundhandler": {
            "fired": "_this params ['_unit','_weapon']; [_unit,_weapon,['RHSUSF_rattle_m249_1','RHSUSF_rattle_m249_2','RHSUSF_rattle_m249_3','RHSUSF_rattle_m249_4','RHSUSF_rattle_m249_5','RHSUSF_rattle_m249_6'],3] call RHSUSF_fnc_beltRattle; [_unit,_weapon,'RHSUSF_boltSnap_m249'] call RHSUSF_fnc_boltSnap;"
        }
    },
    "ww2_boltsnapsound": "RHSUSF_boltSnap_m249",
    "ww2_boltsnapdelay": 0.08,
    "author": "Bohemia Interactive",
    "_generalmacro": "LMG_Mk200_F",
    "baseweapon": "LMG_Mk200_F",
    "handanim": ["OFP2_ManSkeleton","|A3|weapons_f|Machineguns|M200|data|Anim|M200.rtm"],
    "model": "A3|weapons_f|Machineguns|M200|M200_F.p3d",
    "displayname": "Mk200 6.5 mm",
    "picture": "A3|weapons_F|Machineguns|M200|Data|UI|gear_m200_X_CA.paa",
    "hiddenselections": ["camo","camo1","camo2"],
    "hiddenselectionstextures": ["|A3|Weapons_F|Machineguns|M200|data|1st_person_co","|A3|Weapons_F|Machineguns|M200|data|body_co","|A3|Weapons_F|Machineguns|M200|data|grip_co"],
    # Class: CfgWeapons|LMG_Mk200_F|manual [Indent level: 1],
    "manual": {
        "reloadtime": 0.075,
        "dispersion": 0.00102,
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.06,0.0443316,0.028696,0.06,0.0477255,0.0120096,0.06,0.0335835,0.0085568,0.06,0.0140372,0.003648,0.03,-0.0007206,-0.002304,0.03,-0.001765,-0.001692,0.03,-0.0018385,-0.000588,0.06,0,0],
        "recoil": "recoil_auto_mk200",
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.0443316,0.0086088,0.06,0.0477255,0.005004,0.06,0.0335835,0.0042784,0.06,0.0140372,0.002052,0.03,-0.0007206,-0.000768,0.03,-0.001765,-0.0006768,0.03,-0.0018385,-0.0004704,0.06,0,0],
        "recoilprone": "recoil_auto_prone_mk200",
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons|LMG_Mk200_F|manual|BaseSoundModeType [Indent level: 2],
        "basesoundmodetype": {
        },
        # Class: CfgWeapons|LMG_Mk200_F|manual|StandardSound [Indent level: 2],
        "standardsound": {
            "soundsetshot": ["Mk200_Shot_SoundSet","Mk200_Tail_SoundSet","Mk200_InteriorTail_SoundSet"]
        },
        # Class: CfgWeapons|LMG_Mk200_F|manual|SilencedSound [Indent level: 2],
        "silencedsound": {
            "soundsetshot": ["Mk200_silencerShot_SoundSet","Mk200_silencerTail_SoundSet","Mk200_silencerInteriorTail_SoundSet"]
        },
        "soundcontinuous": 0,
        "soundburst": 0,
        "minrange": 0,
        "minrangeprobab": 0.3,
        "midrange": 5,
        "midrangeprobab": 0.7,
        "maxrange": 10,
        "maxrangeprobab": 0.04,
        "showtoplayer": 1,
        "sound": ["",10,1],
        "soundend": ["sound",1],
        "autofire": 1,
        "displayname": "Full",
        "texturetype": "fullAuto",
        "aidispersioncoefy": 3,
        "aidispersioncoefx": 2,
        "multiplier": 1,
        "burst": 1,
        "burstrangemax": -1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "useaction": 0,
        "useactiontitle": "",
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "requiredoptictype": -1,
        "airateoffire": 2,
        "airateoffiredispersion": 1,
        "airateoffiredistance": 500
    },
    "aidispersioncoefy": 24,
    "aidispersioncoefx": 21,
    "magazinewell": ["Mk200_65x39"],
    "magazinereloadswitchphase": 0.48,
    "weaponinfotype": "RscWeaponZeroing",
    "deployedpivot": "bipod",
    "htmin": 1,
    "htmax": 600,
    "afmax": 0,
    "mfmax": 0,
    "mfact": 1,
    "tbody": 100,
    "autofire": 1,
    "soundcontinuous": 0,
    "optics": 0,
    "value": 4,
    "reloadtime": 0.15,
    "modeloptics": "-",
    "sound": [],
    "opticsflare": 0,
    "autoreload": 0,
    "maxleadspeed": 23,
    "canlock": 0,
    "flash": "gunfire",
    "flashsize": 0.5,
    "dispersion": 0.00029,
    # Recoil Array: recoilprone,
    "recoilprone": [0,0,0,0.06,0.01,0.01,0.1,0,-0.02,0.1,-0.01,0.01,0.05,0,0],
    "recoilprone": "assaultRifleBase",
    "ffmagnitude": 0.5,
    "fffrequency": 11,
    "ffcount": 3,
    "weaponpoolavailable": 1,
    "zeroingsound": ["A3|Sounds_F|arsenal|sfx|shared|zeroing_knob_tick_metal",0.316228,1,5],
    "type": 1,
    "airateoffire": 0.5,
    "airateoffiredistance": 500,
    "access": 3,
    "ammo": "",
    "cursorsize": 1,
    "showaimcursorinternal": 1,
    "cursoraimon": "",
    "laser": 0,
    "hiddenunderwaterselections": [],
    "shownunderwaterselections": [],
    "hiddenunderwaterselectionstextures": [],
    "simulation": "Weapon",
    "count": 0,
    "multiplier": 1,
    "burst": 1,
    "magazinereloadtime": 0,
    "soundbegin": ["sound",1],
    "soundbeginwater": ["sound",1],
    "soundclosure": ["sound",1],
    "soundend": ["sound",1],
    "soundloop": ["sound",1],
    "weaponsoundeffect": "",
    "soundburst": 1,
    "reloadsound": ["",1,1],
    "changefiremodesound": ["",1,1],
    "emptysound": ["",1,1],
    "initspeed": 0,
    "ballisticscomputer": 0,
    "irdistance": 0,
    "irdotintensity": 0.001,
    "lockacquire": 1,
    "enableattack": 1,
    "modelspecial": "",
    "modelmagazine": "",
    "muzzlepos": "usti hlavne",
    "muzzleend": "konec hlavne",
    "irlaserpos": "laser pos",
    "irlaserend": "laser dir",
    "cartridgepos": "nabojnicestart",
    "cartridgevel": "nabojniceend",
    "selectionfireanim": "zasleh",
    "memorypointcamera": "eye",
    "firespreadangle": 3,
    "usemodeloptics": 1,
    "opticsid": 0,
    "opticsppeffects": [],
    "forceoptics": 0,
    "useasbinocular": 0,
    "opticsdisableperipherialvision": 0.67,
    "primary": 10,
    "showswitchaction": 0,
    "showempty": 1,
    "showtoplayer": 1,
    "canshootinwater": 0,
    "airateoffiredispersion": 0,
    "firelightduration": 0.05,
    "firelightintensity": 0.2,
    "firelightdiffuse": [0.937,0.631,0.259],
    "firelightambient": [0,0,0],
    "backgroundreload": 0,
    "muzzles": ["this"],
    "useaction": 0,
    "useactiontitle": "",
    "candrop": 1,
    "weaponlockdelay": 0,
    "weaponlocksystem": 0,
    "cmimmunity": 1,
    "weight": 0,
    "minrange": 1,
    "minrangeprobab": 0.3,
    "midrange": 150,
    "midrangeprobab": 0.58,
    "maxrange": 500,
    "maxrangeprobab": 0.04,
    "lockingtargetsound": ["",0.000316228,2],
    "lockedtargetsound": ["",0.000316228,6],
    "detectrange": 0,
    "artillerydispersion": 1,
    "artillerycharge": 1,
    "fireanims": [],
    # Class: CfgWeapons|Default|GunFire [Indent level: 1],
    "gunfire": {
        "access": 0,
        "cloudletduration": 0.2,
        "cloudletanimperiod": 1,
        "cloudletsize": 1,
        "cloudletalpha": 1,
        "cloudletgrowup": 0.2,
        "cloudletfadein": 0.01,
        "cloudletfadeout": 0.5,
        "cloudletaccy": 0,
        "cloudletminyspeed": -100,
        "cloudletmaxyspeed": 100,
        "cloudletshape": "cloudletFire",
        "cloudletcolor": [1,1,1,0],
        "cloudletdensitycoef": -1,
        "interval": -0.01,
        "size": 3,
        "sourcesize": 0.5,
        "timetolive": 0,
        "initt": 4500,
        "deltat": -3000,
        # Class: CfgWeapons|Default|GunFire|Table [Indent level: 2],
        "table": {
            # Class: CfgWeapons|Default|GunFire|Table|T0 [Indent level: 3]
            "t0": {
                "maxt": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T1 [Indent level: 3],
            "t1": {
                "maxt": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T2 [Indent level: 3],
            "t2": {
                "maxt": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T3 [Indent level: 3],
            "t3": {
                "maxt": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T4 [Indent level: 3],
            "t4": {
                "maxt": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T5 [Indent level: 3],
            "t5": {
                "maxt": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T6 [Indent level: 3],
            "t6": {
                "maxt": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T7 [Indent level: 3],
            "t7": {
                "maxt": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T8 [Indent level: 3],
            "t8": {
                "maxt": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T9 [Indent level: 3],
            "t9": {
                "maxt": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T10 [Indent level: 3],
            "t10": {
                "maxt": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T11 [Indent level: 3],
            "t11": {
                "maxt": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T12 [Indent level: 3],
            "t12": {
                "maxt": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T13 [Indent level: 3],
            "t13": {
                "maxt": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T14 [Indent level: 3],
            "t14": {
                "maxt": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T15 [Indent level: 3],
            "t15": {
                "maxt": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T16 [Indent level: 3],
            "t16": {
                "maxt": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T17 [Indent level: 3],
            "t17": {
                "maxt": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T18 [Indent level: 3],
            "t18": {
                "maxt": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T19 [Indent level: 3],
            "t19": {
                "maxt": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T20 [Indent level: 3],
            "t20": {
                "maxt": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T21 [Indent level: 3],
            "t21": {
                "maxt": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T22 [Indent level: 3],
            "t22": {
                "maxt": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgWeapons|Default|GunClouds [Indent level: 1],
    "gunclouds": {
        "access": 0,
        "cloudletgrowup": 0.05,
        "cloudletfadein": 0,
        "cloudletfadeout": 0.1,
        "cloudletduration": 0.05,
        "cloudletalpha": 0.3,
        "cloudletaccy": 0,
        "cloudletminyspeed": -100,
        "cloudletmaxyspeed": 100,
        "interval": -0.02,
        "size": 0.3,
        "sourcesize": 0.02,
        "cloudletanimperiod": 1,
        "cloudletsize": 1,
        "cloudletshape": "cloudletClouds",
        "cloudletcolor": [1,1,1,0],
        "timetolive": 0,
        "initt": 0,
        "deltat": 0,
        # Class: CfgWeapons|Default|GunClouds|Table [Indent level: 2],
        "table": {
            # Class: CfgWeapons|Default|GunClouds|Table|T0 [Indent level: 3]
            "t0": {
                "maxt": 0,
                "color": [1,1,1,0]
            }
        }
    },
    "texturetype": "default",
}