rhs_mag_9k38_rocket = {
    "author": "Red Hammer Studios",
    # Ammo: rhs_ammo_9k38,
    "ammo": {
        "ammo": "rhs_ammo_9k38",
        "cmimmunity": 0.9,
        "maxspeed": 800,
        "maneuvrability": 34,
        "trackoversteer": 0.95,
        "sideairfriction": 0.072,
        "trackLead": 0.56,
        "missileLockMaxDistance": 4800,
        "missileLockMinDistance": 300,
        "missileLockMaxSpeed": 333,
        "missileLockCone": 12,
        "missileKeepLockedCone": 70,
        # Class: CfgAmmo\rhs_ammo_9k38\Components,
        "Components": {
            # Class: CfgAmmo\rhs_ammo_9k38\Components\SensorsManagerComponent
            "SensorsManagerComponent": {
                # Class: CfgAmmo\rhs_ammo_9k38\Components\SensorsManagerComponent\Components
                "Components": {
                    # Class: CfgAmmo\rhs_ammo_9k38\Components\SensorsManagerComponent\Components\IRSensorComponent
                    "IRSensorComponent": {
                        # Class: CfgAmmo\rhs_ammo_9k38\Components\SensorsManagerComponent\Components\IRSensorComponent\AirTarget
                        "AirTarget": {
                            "minRange": 500,
                            "maxRange": 4800,
                            "objectDistanceLimitCoef": -1,
                            "viewDistanceLimitCoef": 1
                        },
                        # Class: CfgAmmo\rhs_ammo_9k38\Components\SensorsManagerComponent\Components\IRSensorComponent\GroundTarget,
                        "GroundTarget": {
                            "minRange": 500,
                            "maxRange": 1000,
                            "objectDistanceLimitCoef": 1,
                            "viewDistanceLimitCoef": 1
                        },
                        "typeRecognitionDistance": -1,
                        "angleRangeHorizontal": 35,
                        "angleRangeVertical": 35,
                        "groundNoiseDistanceCoef": 0.02,
                        "maxGroundNoiseDistance": 40,
                        "minSpeedThreshold": 0,
                        "maxSpeedThreshold": -1,
                        "maxFogSeeThrough": 0.8,
                        "minTrackableSpeed": 0,
                        "maxTrackableSpeed": 333,
                        "minTrackableATL": 20,
                        "maxTrackableATL": 3900,
                        "componentType": "IRSensorComponent",
                        "color": [1,0,0,1],
                        "allowsMarking": 1,
                        "animDirection": "",
                        "aimDown": 0
                    }
                }
            }
        },
        "model": "rhsafrf|addons|rhs_heavyweapons|igla|igla_fly",
        "proxyShape": "rhsafrf|addons|rhs_heavyweapons|igla|igla_missile",
        "airlock": 2,
        "cost": 750,
        "fusedistance": 50,
        "proximityExplosionDistance": 11,
        "hit": 40,
        "indirecthit": 31,
        "indirecthitrange": 5,
        "inittime": 0.25,
        "irlock": 1,
        "simulationstep": 0.001,
        "thrust": 220,
        "thrusttime": 5.5,
        "timetolive": 15,
        "whistledist": 16,
        "effectsMissile": "RHS_9k32_Fired",
        "submunitionConeType": ["randomcenter",30],
        "submunitionConeAngle": 65,
        "submunitionAmmo": "rhs_ammo_he_fragments",
        "submunitionDirectionType": "SubmunitionTargetDirection",
        "submunitionInitialOffset": [0,0,0],
        "submunitionParentSpeedCoef": 0,
        "submunitionInitSpeed": 1500,
        "triggerOnImpact": 1,
        "deleteParentWhenTriggered": 0,
        "weaponLockSystem": "2 + 16",
        "warheadName": "HE",
        "aiAmmoUsageFlags": 256,
        "airFriction": 0.145,
        "CraterEffects": "AAMissileCrater",
        "explosionEffects": "AAMissileExplosion",
        "effectsMissileInit": "",
        "soundHit1": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_01",2.51189,1,1900],
        "soundHit2": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_02",2.51189,1,1900],
        "soundHit3": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_03",2.51189,1,1900],
        "multiSoundHit": ["soundHit1",0.34,"soundHit2",0.33,"soundHit3",0.33],
        # Class: CfgAmmo\M_Titan_AA\CamShakeExplode,
        "CamShakeExplode": {
            "power": 22,
            "duration": 2,
            "frequency": 20,
            "distance": 147.905
        },
        # Class: CfgAmmo\M_Titan_AA\CamShakeHit,
        "CamShakeHit": {
            "power": 110,
            "duration": 0.6,
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo\M_Titan_AA\CamShakeFire,
        "CamShakeFire": {
            "power": 2.78316,
            "duration": 1.6,
            "frequency": 20,
            "distance": 61.9677
        },
        # Class: CfgAmmo\M_Titan_AA\CamShakePlayerFire,
        "CamShakePlayerFire": {
            "power": 3,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "SoundSetExplosion": ["RocketsHeavy_Exp_SoundSet","RocketsHeavy_Tail_SoundSet","Explosion_Debris_SoundSet"],
        "manualControl": 0,
        "maxControlRange": 4000,
        "explosionSoundEffect": "DefaultExplosion",
        "soundFly": ["",1,1,400],
        "soundEngine": ["",1,1,50],
        "supersonicCrackNear": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_close",0.398107,1,20],
        "supersonicCrackFar": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_50meters",0.316228,1,50],
        "muzzleEffect": "BIS_fnc_effectFiredRocket",
        "deflecting": 0,
        "dangerRadiusHit": -1,
        "suppressionRadiusHit": 30,
        # Class: CfgAmmo\MissileBase\HitEffects,
        "HitEffects": {
            "hitWater": "ImpactEffectsWaterRocket"
        },
        "maverickWeaponIndexOffset": 0,
        "htMin": 60,
        "htMax": 1800,
        "afMax": 200,
        "mfMax": 100,
        "mFact": 0,
        "tBody": 0,
        # Class: CfgAmmo\MissileBase\EventHandlers,
        "EventHandlers": {
            # Class: CfgAmmo\MissileBase\EventHandlers\RHS_APS_FiredEH
            "RHS_APS_FiredEH": {
                "fired": "_this spawn rhs_fnc_aps_missileFired"
            }
        },
        "simulation": "shotMissile",
        "visibleFire": 32,
        "audibleFire": 32,
        "visibleFireTime": 20,
        "soundHit": ["",100,1],
        "access": 3,
        "underwaterHitRangeCoef": 1,
        "typicalSpeed": 900,
        "explosionForceCoef": 1,
        "isCraterOriented": 0,
        "craterShape": "",
        "weaponType": "Default",
        "animated": 0,
        "shadow": 0,
        "cartridge": "",
        "tracerColor": [0.7,0.7,0.5,0.04],
        "tracerColorR": [0.7,0.7,0.5,0.04],
        "soundFall": ["",1,1],
        "soundFakeFall": ["soundFall",1],
        "hitGroundSoft": ["soundHit",1],
        "hitGroundHard": ["soundHit",1],
        "hitMan": ["soundHit",1],
        "hitArmor": ["soundHit",1],
        "hitIron": ["soundHit",1],
        "hitBuilding": ["soundHit",1],
        "hitFoliage": ["soundHit",1],
        "hitWood": ["soundHit",1],
        "hitGlass": ["soundHit",1],
        "hitGlassArmored": ["soundHit",1],
        "hitConcrete": ["soundHit",1],
        "hitRubber": ["soundHit",1],
        "hitPlastic": ["soundHit",1],
        "hitDefault": ["soundHit",1],
        "hitMetal": ["soundHit",1],
        "hitMetalplate": ["soundHit",1],
        "hitTyre": ["soundHit",1],
        "hitWater": ["soundHit",1],
        "soundImpact": ["",1,1],
        "impactGroundSoft": ["soundImpact",1],
        "impactGroundHard": ["soundImpact",1],
        "impactMan": ["soundImpact",1],
        "impactIron": ["soundImpact",1],
        "impactArmor": ["soundImpact",1],
        "impactBuilding": ["soundImpact",1],
        "impactFoliage": ["soundImpact",1],
        "impactWood": ["soundImpact",1],
        "impactGlass": ["soundImpact",1],
        "impactGlassArmored": ["soundImpact",1],
        "impactConcrete": ["soundImpact",1],
        "impactRubber": ["soundImpact",1],
        "impactPlastic": ["soundImpact",1],
        "impactDefault": ["soundImpact",1],
        "impactMetal": ["soundImpact",1],
        "impactMetalplate": ["soundImpact",1],
        "impactTyre": ["soundImpact",1],
        "impactWater": ["soundImpact",1],
        "grenadeFireSound": [],
        "grenadeBurningSound": [],
        "deflectionSlowDown": 0.8,
        "explosive": 1,
        "craterWaterEffects": "ImpactEffectsWater",
        "effectsSmoke": "SmokeShellWhite",
        "effectsFire": "CannonFire",
        "effectFlare": "FlareShell",
        "effectFly": "",
        "mineJumpEffects": "",
        "waterEffectOffset": 0.45,
        "directionalExplosion": 0,
        "explosionAngle": 60,
        "explosionDir": "explosionDir",
        "explosionPos": "explosionPos",
        "explosionEffectsDir": "explosionDir",
        "minimumSafeZone": 0.1,
        "soundTrigger": [],
        "soundActivation": [],
        "soundDeactivation": [],
        "minTimeToLive": 0,
        "laserLock": 0,
        "nvLock": 0,
        "artilleryLock": 0,
        "hitOnWater": 0,
        "lockSeekRadius": 100,
        "lockType": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "autoSeekTarget": 0,
        "shootDistraction": -1,
        "explosionTime": 0,
        "icon": "",
        "explosionType": "explosive",
        "mineTrigger": "RangeTrigger",
        "mineBoundingTime": 3,
        "mineBoundingDist": 3,
        "mineInconspicuousness": 10,
        "mineFloating": -1,
        "mineDiveSpeed": 1,
        "minePlaceDist": 0.5,
        "suppressionRadiusBulletClose": -1,
        "dangerRadiusBulletClose": -1,
        "caliber": 1,
        "whistleOnFire": 0,
        # Class: CfgAmmo\Default\NVGMarkers,
        "NVGMarkers": {
        },
        "minDamageForCamShakeHit": 0.55,
    },
    "displayname": "9K38",
    "descriptionshort": "Range: 800-4200 m <br/>Type: ground-air <br/>Used in: 9K38",
    "picture": "rhsafrf|addons|rhs_weapons|icons|m_igla_ca.paa",
    "initspeed": 17,
    "maxleadspeed": 320,
    "modelspecial": "",
    "scope": 2,
    "nameSound": "missiles",
    "type": "6 * 		256",
    "displayNameShort": "AA",
    "model": "A3|Weapons_F_beta|Launchers|titan|titan_missile_atl",
    "mass": 100,
    "value": 5,
    "allowedSlots": [901],
    "count": 1,
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines\Default\InventoryPlacements,
    "InventoryPlacements": {
    },
    # Class: CfgMagazines\Default\Library,
    "Library": {
        "libTextDesc": ""
    },
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0,
}