rhs_rpg7_PG7VR_mag = {
    "author": "Red Hammer Studios",
    "picture": "rhsafrf|addons|rhs_inventoryicons|data|magazines|rhs_rpg7_PG7VR_mag_ca.paa",
    "displayName": "PG-7VR",
    "displayNameShort": "PG-7VR - AT",
    "descriptionShort": "Type: 105mm Tandem HEAT Rocket<br />Rounds: 1<br />Used in: RPG-7",
    "model": "rhsafrf|addons|rhs_weapons|rpg7|magazines|rhs_pg7vr_mag",
    "modelSpecial": "rhsafrf|addons|rhs_weapons|mag_proxies|rhs_mag_pg7vr",
    # Ammo: rhs_rpg7v2_pg7vr,
    "ammo": {
        "ammo": "rhs_rpg7v2_pg7vr",
        "AIAmmoUsageFlags": "128+512",
        "model": "rhsafrf|addons|rhs_weapons|rpg7|projectiles|pg7vr",
        "warheadName": "TandemHEAT",
        "submunitionAmmo": "rhs_rpg7v2_pg7vr_penetrator",
        "submunitionDirectionType": "SubmunitionModelDirection",
        "submunitionInitialOffset": [0,0,-0.2],
        "submunitionParentSpeedCoef": 0,
        "submunitionInitSpeed": 1000,
        "triggerOnImpact": 1,
        "deleteParentWhenTriggered": 0,
        "hit": 230,
        "indirectHit": 20,
        "indirectHitRange": 3.8,
        "cost": 300,
        "maxSpeed": 110,
        "initTime": 0.15,
        "airfriction": 0.9,
        "sideAirFriction": 0.1,
        "thrust": 120,
        "fuseDistance": 5,
        "timeToLive": 6,
        "airLock": 1,
        "simulationStep": 0.01,
        "thrustTime": 0.5,
        "visibleFire": 28,
        "audibleFire": 16,
        "whistleDist": 4,
        "CraterEffects": "ATRocketCrater",
        "explosionEffects": "ATRocketExplosion",
        "effectsMissileInit": "RocketBackEffectsRPG",
        "effectsMissile": "missile3",
        # Class: CfgAmmo\rhs_rpg7v2_pg7vl\CamShakeFire,
        "CamShakeFire": {
            "power": 10,
            "duration": 0.5,
            "frequency": 20,
            "distance": 30
        },
        # Class: CfgAmmo\rhs_rpg7v2_pg7vl\CamShakePlayerFire,
        "CamShakePlayerFire": {
            "power": 5,
            "duration": 0.1,
            "frequency": 20
        },
        "caliber": 0.8,
        "explosive": 0.35,
        "soundFly": ["A3|Sounds_F|arsenal|weapons_static|Missile_Launcher|rocket_fly",1.1,0.7,250],
        "irLock": 0,
        "maneuvrability": 0,
        "allowAgainstInfantry": 0,
        "soundHit1": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_01",2.51189,1,1800],
        "soundHit2": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_02",2.51189,1,1800],
        "soundHit3": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_03",2.51189,1,1800],
        "multiSoundHit": ["soundHit1",0.34,"soundHit2",0.33,"soundHit3",0.33],
        # Class: CfgAmmo\R_PG32V_F\CamShakeExplode,
        "CamShakeExplode": {
            "power": 11,
            "duration": 1.4,
            "frequency": 20,
            "distance": 99.3296
        },
        # Class: CfgAmmo\R_PG32V_F\CamShakeHit,
        "CamShakeHit": {
            "power": 110,
            "duration": 0.6,
            "frequency": 20,
            "distance": 1
        },
        "SoundSetExplosion": ["RocketsLight_Exp_SoundSet","RocketsLight_Tail_SoundSet","Explosion_Debris_SoundSet"],
        "dangerRadiusHit": -1,
        "suppressionRadiusHit": 30,
        "soundHit": ["A3|Sounds_F|weapons|Rockets|explosion_missile_02",2.51189,1,2500],
        "explosionSoundEffect": "DefaultExplosion",
        "soundEngine": ["",1,1,20],
        "supersonicCrackNear": ["",1,1,50],
        "supersonicCrackFar": ["",1,1,150],
        "muzzleEffect": "BIS_fnc_effectFiredRocket",
        # Class: CfgAmmo\RocketBase\HitEffects,
        "HitEffects": {
            "hitWater": "ImpactEffectsWaterRocket"
        },
        # Class: CfgAmmo\RocketBase\EventHandlers,
        "EventHandlers": {
            # Class: CfgAmmo\RocketBase\EventHandlers\RHS_APS_FiredEH
            "RHS_APS_FiredEH": {
                "fired": "_this spawn rhs_fnc_aps_missileFired"
            }
        },
        "simulation": "shotRocket",
        "maxControlRange": 0,
        "visibleFireTime": 20,
        "deflecting": 5,
        "access": 3,
        "underwaterHitRangeCoef": 1,
        "typicalSpeed": 900,
        "explosionForceCoef": 1,
        "isCraterOriented": 0,
        "proxyShape": "",
        "craterShape": "",
        "weaponType": "Default",
        "animated": 0,
        "shadow": 0,
        "cartridge": "",
        "tracerColor": [0.7,0.7,0.5,0.04],
        "tracerColorR": [0.7,0.7,0.5,0.04],
        "soundFall": ["",1,1],
        "soundFakeFall": ["soundFall",1],
        "hitGroundSoft": ["soundHit",1],
        "hitGroundHard": ["soundHit",1],
        "hitMan": ["soundHit",1],
        "hitArmor": ["soundHit",1],
        "hitIron": ["soundHit",1],
        "hitBuilding": ["soundHit",1],
        "hitFoliage": ["soundHit",1],
        "hitWood": ["soundHit",1],
        "hitGlass": ["soundHit",1],
        "hitGlassArmored": ["soundHit",1],
        "hitConcrete": ["soundHit",1],
        "hitRubber": ["soundHit",1],
        "hitPlastic": ["soundHit",1],
        "hitDefault": ["soundHit",1],
        "hitMetal": ["soundHit",1],
        "hitMetalplate": ["soundHit",1],
        "hitTyre": ["soundHit",1],
        "hitWater": ["soundHit",1],
        "soundImpact": ["",1,1],
        "impactGroundSoft": ["soundImpact",1],
        "impactGroundHard": ["soundImpact",1],
        "impactMan": ["soundImpact",1],
        "impactIron": ["soundImpact",1],
        "impactArmor": ["soundImpact",1],
        "impactBuilding": ["soundImpact",1],
        "impactFoliage": ["soundImpact",1],
        "impactWood": ["soundImpact",1],
        "impactGlass": ["soundImpact",1],
        "impactGlassArmored": ["soundImpact",1],
        "impactConcrete": ["soundImpact",1],
        "impactRubber": ["soundImpact",1],
        "impactPlastic": ["soundImpact",1],
        "impactDefault": ["soundImpact",1],
        "impactMetal": ["soundImpact",1],
        "impactMetalplate": ["soundImpact",1],
        "impactTyre": ["soundImpact",1],
        "impactWater": ["soundImpact",1],
        "grenadeFireSound": [],
        "grenadeBurningSound": [],
        "deflectionSlowDown": 0.8,
        "craterWaterEffects": "ImpactEffectsWater",
        "effectsSmoke": "SmokeShellWhite",
        "effectsFire": "CannonFire",
        "effectFlare": "FlareShell",
        "effectFly": "",
        "mineJumpEffects": "",
        "waterEffectOffset": 0.45,
        "directionalExplosion": 0,
        "explosionAngle": 60,
        "explosionDir": "explosionDir",
        "explosionPos": "explosionPos",
        "explosionEffectsDir": "explosionDir",
        "minimumSafeZone": 0.1,
        "soundTrigger": [],
        "soundActivation": [],
        "soundDeactivation": [],
        "minTimeToLive": 0,
        "laserLock": 0,
        "nvLock": 0,
        "artilleryLock": 0,
        "hitOnWater": 0,
        "lockSeekRadius": 100,
        "manualControl": 0,
        "trackLead": 1,
        "trackOversteer": 1,
        "missileLockCone": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "lockType": 0,
        "maverickweaponIndexOffset": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "autoSeekTarget": 0,
        "shootDistraction": -1,
        "explosionTime": 0,
        "icon": "",
        "explosionType": "explosive",
        "mineTrigger": "RangeTrigger",
        "mineBoundingTime": 3,
        "mineBoundingDist": 3,
        "mineInconspicuousness": 10,
        "mineFloating": -1,
        "mineDiveSpeed": 1,
        "minePlaceDist": 0.5,
        "suppressionRadiusBulletClose": -1,
        "dangerRadiusBulletClose": -1,
        "whistleOnFire": 0,
        # Class: CfgAmmo\Default\NVGMarkers,
        "NVGMarkers": {
        },
        "minDamageForCamShakeHit": 0.55,
    },
    "initSpeed": 66,
    "mass": 64.35,
    "scope": 2,
    "modelSpecialIsProxy": 1,
    "type": "6 * 		256",
    "value": 5,
    "allowedSlots": [901],
    "count": 1,
    "nameSound": "handgrenade",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines\Default\InventoryPlacements,
    "InventoryPlacements": {
    },
    # Class: CfgMagazines\Default\Library,
    "Library": {
        "libTextDesc": ""
    },
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0,
}