rhs_30Rnd_545x39_7N6_AK = {
    "author": "Red Hammer Studios",
    "picture": "\rhsafrf\addons\rhs_inventoryicons\data\magazines\rhs_30Rnd_545x39_AK_ca.paa",
    "scope": 2,
    "displayName": "30rnd AK-74 (Bakelite) 7N6",
    "descriptionShort": "Caliber: 5.45x39mm FMJ<br />Rounds: 30<br />Used in: AK-74M, AK-105",
    "displayNameShort": "7N6",
    "model": "\rhsafrf\addons\rhs_weapons3\magazines\rhs_ak_bklt_mag",
    "modelSpecial": "\rhsafrf\addons\rhs_weapons\mag_proxies\rhs_mag_545x39_6l20_30rnd.p3d",
    "modelSpecialIsProxy": 1,
    "ammo": "rhs_B_545x39_Ball",
    "count": 30,
    "mass": 9.09,
    "initSpeed": 915,
    "tracersEvery": 0,
    "lastRoundsTracer": 0,
    "value": 1,
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "type": 256,
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}