rhs_10Rnd_762x54mmR_7N14 = {
    "author": "Red Hammer Studios",
    "displayName": "10rnd SVD 7N14",
    "descriptionShort": "7N14 10rnd SVD Mag",
    "displayNameShort": "7N14 AP",
    "ammo": "rhs_B_762x54_7N14_Ball",
    "mass": 5.94,
    "picture": "\rhsafrf\addons\rhs_inventoryicons\data\magazines\rhs_10Rnd_762x54mmR_7N1_ca.paa",
    "model": "\rhsafrf\addons\rhs_weapons\magazines\rhs_svd_mag",
    "initSpeed": 823,
    "count": 10,
    "lastRoundsTracer": 0,
    "scope": 2,
    "modelSpecial": "\rhsafrf\addons\rhs_weapons\mag_proxies\rhs_mag_545x39_6l20_30rnd.p3d",
    "modelSpecialIsProxy": 1,
    "tracersEvery": 0,
    "value": 1,
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "type": 256,
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}