rhsgref_10Rnd_792x57_m76 = {
    "magazineGroup": ["rhs_m76_mag_group"],
    "dlc": "RHS_SAF",
    "author": "Red Hammer Studios",
    "scope": 2,
    "scopeCurator": 2,
    "displayName": "10rnd M76 7.9x57mm M75",
    "displaynameshort": "M75 Ball",
    "picture": "\rhssaf\addons\rhssaf_c_weapons\icons\m_m76mag_icon_ca.paa",
    "ammo": "rhs_ammo_792x57_Ball",
    "count": 10,
    "initSpeed": 730,
    "tracersEvery": 0,
    "lastRoundsTracer": 0,
    "descriptionshort": "Caliber: 7.92x57mm Mauser <br />Rounds: 10<br />Used in: M76 Rifle",
    "mass": 6.94,
    "model": "\rhssaf\addons\rhssaf_m_weapon_m76\magazine\rhs_10rnd_m76_mag",
    "value": 1,
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "type": 256,
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}