rhssaf_250Rnd_762x54R = {
    "displayName": "250Rnd M84 Belt 7.62x54mm M30",
    "descriptionshort": "Caliber: 7.62x54Rmm <br />Rounds: 250<br />Used in: M84 LMG",
    "ammo": "rhs_B_762x54_Ball",
    "count": 250,
    "dlc": "RHS_SAF",
    "author": "Red Hammer Studios",
    "scope": 2,
    "mass": 128.7,
    "displayNameShort": "57-N-323S",
    "model": "\rhsafrf\addons\rhs_weapons\magazines\rhs_pk_mag",
    "picture": "\rhsafrf\addons\rhs_weapons\icons\pkpbox_ca.paa",
    "initSpeed": 798,
    "tracersevery": 5,
    "modelSpecial": "\rhsafrf\addons\rhs_weapons\mag_proxies\rhs_mag_545x39_6l20_30rnd.p3d",
    "modelSpecialIsProxy": 1,
    "lastRoundsTracer": 0,
    "value": 1,
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "type": 256,
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}