rhsusf_5Rnd_762x51_m62_Mag = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "displayname": "5rnd M62 (Tracer)",
    "displayNameShort": "M62 Tracer",
    "ammo": "rhs_ammo_762x51_M62_tracer",
    "mass": 2.64,
    "initSpeed": 910,
    "tracersEvery": 1,
    "descriptionShort": "Caliber: 7.62x51mm NATO<br />Rounds: 5<br />Used in: M24 SWS",
    "picture": "\A3\weapons_f\data\UI\m_5rnd_127x108_ca.paa",
    "model": "\rhsusf\addons\rhsusf_weapons\magazines\rhs_762x51_loose",
    "modelSpecial": "rhsusf\addons\rhsusf_weapons\mag_proxies\rhs_mag_762x51_aics_5rnd",
    "modelSpecialIsProxy": 1,
    "count": 5,
    "value": 1,
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "type": 256,
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}