rhs_rpg7_TBG7V_mag = {
    "author": "Red Hammer Studios",
    "picture": "\rhsafrf\addons\rhs_inventoryicons\data\magazines\rhs_rpg7_TBG7V_mag_ca.paa",
    "displayName": "TBG-7V",
    "displayNameShort": "TBG-7V - HE",
    "descriptionShort": "Type: 105mm Thermobaric Rocket<br />Rounds: 1<br />Used in: RPG-7",
    "model": "\rhsafrf\addons\rhs_weapons\rpg7\magazines\rhs_tbg7v_mag",
    "modelSpecial": "\rhsafrf\addons\rhs_weapons\mag_proxies\rhs_mag_tbg7v",
    "ammo": "rhs_rpg7v2_tbg7v",
    "initSpeed": 66,
    "mass": 64.35,
    "scope": 2,
    "modelSpecialIsProxy": 1,
    "type": "6 * 		256",
    "value": 5,
    "allowedSlots": [901],
    "count": 1,
    "nameSound": "handgrenade",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}