rhsusf_weap_mp7a2_folded = {
    "author": "Red Hammer Studios",
    "dlc": "RHS_USAF",
    "picture": "rhsusf|addons|rhsusf_inventoryicons|data|weapons|rhsusf_weap_MP7A2_folded_ca.paa",
    "displayname": "MP7A2 (Folded)",
    "type": 2,
    "model": "rhsusf|addons|rhsusf_weapons2|MP7|mp7a2_folded",
    "reloadaction": "GestureReloadPistol",
    "handanim": ["OFP2_ManSkeleton","|rhsusf|addons|rhsusf_c_weapons|anims|rhs_hand_MP7.rtm"],
    # Recoil Class: recoil,
    # Class: CfgRecoils|rhs_recoil_mp7_folded [Indent level: 0],
    "recoil": {
        "muzzleouter": [0.13,0.45,0.28,0.21],
        "kickback": [0.03,0.045],
        "temporary": 0.01,
        "permanent": 0.05,
        "muzzleinner": [0,0,0.1,0.1]
    },
    # Class: CfgWeapons|rhsusf_weap_MP7A2_folded|WeaponSlotsInfo [Indent level: 1],
    "weaponslotsinfo": {
        "holsterscale": 0,
        "mass": 16.94,
        # Class: CfgWeapons|rhsusf_weap_MP7A2_folded|WeaponSlotsInfo|GripodSlot [Indent level: 2],
        "gripodslot": {
        },
        "allowedslots": [901],
        # Class: CfgWeapons|rhsusf_weap_MP7A1_base_f|WeaponSlotsInfo|MuzzleSlot [Indent level: 2],
        "muzzleslot": {
            "iconposition": [0.05,0.38],
            "iconscale": 0.2,
            "iconpicture": "A3|Weapons_F|Data|clear_empty.paa",
            "iconpinpoint": "Left",
            "displayname": "$str_a3_cfgweapons_abr_base_f_weaponslotsinfo_muzzleslot0",
            "linkproxy": "A3|data_f|proxies|weapon_slots|MUZZLE",
            # Class: rhs_western_46mmsmg_muzzle_slot|compatibleItems [Indent level: 0],
            "compatibleitems": {
                "rhsusf_acc_rotex_mp7": 1,
                "rhsusf_acc_rotex_mp7_desert": 1,
                "rhsusf_acc_rotex_mp7_winter": 1,
                "rhsusf_acc_rotex_mp7_aor1": 1
            }
        },
        # Class: CfgWeapons|rhsusf_weap_MP7A1_base_f|WeaponSlotsInfo|CowsSlot [Indent level: 2],
        "cowsslot": {
            "iconposition": [0.5,0.3],
            "iconscale": 0.2,
            # Class: asdg_OpticRail1913_short|compatibleItems [Indent level: 0],
            "compatibleitems": {
                "rhs_acc_rakurspm": 1,
                "rhs_acc_dh520x56": 1,
                "rhs_acc_ekp8_18": 1,
                "rhs_acc_ekp8_18b": 1,
                "rhs_acc_ekp8_18c": 1,
                "rhs_acc_ekp8_18d": 1,
                "rhs_acc_1p87": 1,
                "rhs_acc_okp7_picatinny": 1,
                "optic_nightstalker": 1,
                "optic_tws": 1,
                "optic_tws_mg": 1,
                "optic_nvs": 1,
                "optic_sos": 1,
                "optic_sos_khk_f": 1,
                "optic_mrco": 1,
                "optic_arco": 1,
                "optic_arco_ghex_f": 1,
                "optic_arco_blk_f": 1,
                "optic_aco": 1,
                "optic_aco_grn": 1,
                "optic_aco_smg": 1,
                "optic_aco_grn_smg": 1,
                "optic_hamr": 1,
                "optic_hamr_khk_f": 1,
                "optic_holosight": 1,
                "optic_holosight_smg": 1,
                "optic_holosight_blk_f": 1,
                "optic_holosight_khk_f": 1,
                "optic_holosight_smg_blk_f": 1,
                "optic_dms": 1,
                "optic_dms_ghex_f": 1,
                "optic_lrps": 1,
                "optic_lrps_ghex_f": 1,
                "optic_lrps_tna_f": 1,
                "optic_ams": 1,
                "optic_ams_khk": 1,
                "optic_ams_snd": 1,
                "optic_khs_blk": 1,
                "optic_khs_hex": 1,
                "optic_khs_old": 1,
                "optic_khs_tan": 1,
                "optic_erco_blk_f": 1,
                "optic_erco_khk_f": 1,
                "optic_erco_snd_f": 1,
                "rhsusf_acc_leupoldmk4": 1,
                "rhsusf_acc_leupoldmk4_d": 1,
                "rhsusf_acc_leupoldmk4_wd": 1,
                "rhsusf_acc_leupoldmk4_2": 1,
                "rhsusf_acc_leupoldmk4_2_mrds": 1,
                "rhsusf_acc_leupoldmk4_2_d": 1,
                "rhsusf_acc_premier": 1,
                "rhsusf_acc_premier_mrds": 1,
                "rhsusf_acc_premier_low": 1,
                "rhsusf_acc_m8541": 1,
                "rhsusf_acc_m8541_d": 1,
                "rhsusf_acc_m8541_wd": 1,
                "rhsusf_acc_m8541_mrds": 1,
                "rhsusf_acc_m8541_low": 1,
                "rhsusf_acc_m8541_low_d": 1,
                "rhsusf_acc_m8541_low_wd": 1,
                "rhsusf_acc_nxs_3515x50_md": 1,
                "rhsusf_acc_nxs_3515x50f1_md": 1,
                "rhsusf_acc_nxs_3515x50f1_md_sun": 1,
                "rhsusf_acc_nxs_3515x50f1_h58": 1,
                "rhsusf_acc_nxs_3515x50f1_h58_sun": 1,
                "rhsusf_acc_nxs_5522x56_md": 1,
                "rhsusf_acc_nxs_5522x56_md_sun": 1,
                "rhsusf_acc_eotech": 1,
                "rhsusf_acc_eotech_552": 1,
                "rhsusf_acc_eotech_552_d": 1,
                "rhsusf_acc_eotech_552_wd": 1,
                "rhsusf_acc_eotech_xps3": 1,
                "rhsusf_acc_g33_xps3": 1,
                "rhsusf_acc_g33_xps3_flip": 1,
                "rhsusf_acc_g33_xps3_tan": 1,
                "rhsusf_acc_g33_xps3_tan_flip": 1,
                "rhsusf_acc_g33_t1": 1,
                "rhsusf_acc_g33_t1_flip": 1,
                "rhsusf_acc_compm4": 1,
                "rhsusf_acc_t1_high": 1,
                "rhsusf_acc_t1_low": 1,
                "rhsusf_acc_rx01": 1,
                "rhsusf_acc_rx01_nofilter": 1,
                "rhsusf_acc_rx01_tan": 1,
                "rhsusf_acc_rx01_nofilter_tan": 1,
                "rhsusf_acc_rm05": 1,
                "rhsusf_acc_mrds": 1,
                "rhsusf_acc_mrds_c": 1,
                "rhsusf_acc_acog": 1,
                "rhsusf_acc_acog2": 1,
                "rhsusf_acc_acog3": 1,
                "rhsusf_acc_acog_wd": 1,
                "rhsusf_acc_acog_d": 1,
                "rhsusf_acc_acog_sa": 1,
                "rhsusf_acc_acog_usmc": 1,
                "rhsusf_acc_acog2_usmc": 1,
                "rhsusf_acc_acog3_usmc": 1,
                "rhsusf_acc_acog_rmr": 1,
                "rhsusf_acc_acog_pip": 1,
                "rhsusf_acc_acog2_pip": 1,
                "rhsusf_acc_acog3_pip": 1,
                "rhsusf_acc_acog_wd_pip": 1,
                "rhsusf_acc_acog_d_pip": 1,
                "rhsusf_acc_acog_sa_pip": 1,
                "rhsusf_acc_acog_usmc_pip": 1,
                "rhsusf_acc_acog2_usmc_pip": 1,
                "rhsusf_acc_acog3_usmc_pip": 1,
                "rhsusf_acc_acog_rmr_pip": 1,
                "rhsusf_acc_acog_3d": 1,
                "rhsusf_acc_acog2_3d": 1,
                "rhsusf_acc_acog3_3d": 1,
                "rhsusf_acc_acog_wd_3d": 1,
                "rhsusf_acc_acog_d_3d": 1,
                "rhsusf_acc_acog_sa_3d": 1,
                "rhsusf_acc_acog_usmc_3d": 1,
                "rhsusf_acc_acog2_usmc_3d": 1,
                "rhsusf_acc_acog3_usmc_3d": 1,
                "rhsusf_acc_acog_rmr_3d": 1,
                "rhsusf_acc_elcan": 1,
                "rhsusf_acc_elcan_ard": 1,
                "rhsusf_acc_elcan_3d": 1,
                "rhsusf_acc_elcan_ard_3d": 1,
                "rhsusf_acc_elcan_pip": 1,
                "rhsusf_acc_elcan_ard_pip": 1,
                "rhsusf_acc_su230": 1,
                "rhsusf_acc_su230_mrds": 1,
                "rhsusf_acc_su230a": 1,
                "rhsusf_acc_su230a_mrds": 1,
                "rhsusf_acc_su230_c": 1,
                "rhsusf_acc_su230_mrds_c": 1,
                "rhsusf_acc_su230a_c": 1,
                "rhsusf_acc_su230a_mrds_c": 1,
                "rhsusf_acc_su230_3d": 1,
                "rhsusf_acc_su230_mrds_3d": 1,
                "rhsusf_acc_su230a_3d": 1,
                "rhsusf_acc_su230a_mrds_3d": 1,
                "rhsusf_acc_su230_c_3d": 1,
                "rhsusf_acc_su230_mrds_c_3d": 1,
                "rhsusf_acc_su230a_c_3d": 1,
                "rhsusf_acc_su230a_mrds_c_3d": 1,
                "rhsusf_acc_specterdr": 1,
                "rhsusf_acc_specterdr_3d": 1,
                "rhsusf_acc_specterdr_a": 1,
                "rhsusf_acc_specterdr_a_3d": 1,
                "rhsusf_acc_specterdr_cx": 1,
                "rhsusf_acc_specterdr_cx_3d": 1,
                "rhsusf_acc_specterdr_pvs27": 1,
                "rhsusf_acc_specterdr_d": 1,
                "rhsusf_acc_specterdr_od": 1,
                "rhsusf_acc_specterdr_d_3d": 1,
                "rhsusf_acc_specterdr_od_3d": 1,
                "rhsusf_acc_anpvs27": 1,
                "rhsusf_acc_anpas13gv1": 1,
                "rhsusf_acc_m2a1": 1,
                "rhsusf_acc_acog_mdo": 1,
                "rhsgref_acc_rx01_camo": 1,
                "rhsgref_acc_rx01_nofilter_camo": 1
            },
            "linkproxy": "A3|data_f|proxies|weapon_slots|TOP",
            "displayname": "Optics Slot"
        },
        # Class: CfgWeapons|rhsusf_weap_MP7A1_base_f|WeaponSlotsInfo|PointerSlot [Indent level: 2],
        "pointerslot": {
            "iconposition": [0.35,0.4],
            "iconscale": 0.25,
            "iconpicture": "A3|Weapons_F|Data|clear_empty.paa",
            "iconpinpoint": "Left",
            # Class: rhs_western_rifle_laser_slot|compatibleItems [Indent level: 0],
            "compatibleitems": {
                "rhsusf_acc_anpeq15": 0,
                "rhsusf_acc_anpeq15_top": 0,
                "rhsusf_acc_anpeq15_light": 0,
                "rhsusf_acc_anpeq15_bk": 0,
                "rhsusf_acc_anpeq15_bk_top": 0,
                "rhsusf_acc_anpeq15_bk_light": 0,
                "rhsusf_acc_anpeq15_wmx": 0,
                "rhsusf_acc_anpeq15_wmx_light": 0,
                "rhsusf_acc_anpeq16a_top": 0,
                "rhsusf_acc_anpeq16a_light_top": 0,
                "rhsusf_acc_anpeq16a_top_h": 0,
                "rhsusf_acc_anpeq16a_light_top_h": 0,
                "rhs_acc_2dpzenit_ris": 1,
                "rhs_acc_perst1ik_ris": 1,
                "rhs_acc_perst3": 1,
                "acc_flashlight": 1,
                "acc_pointer_ir": 1,
                "rhsusf_acc_wmx": 1,
                "rhsusf_acc_wmx_bk": 1,
                "rhsusf_acc_m952v": 1,
                "rhsusf_acc_anpeq15a": 1,
                "rhsusf_acc_anpeq15_h": 1,
                "rhsusf_acc_anpeq15_light_h": 1,
                "rhsusf_acc_anpeq15_top_h": 1,
                "rhsusf_acc_anpeq15_sc": 1,
                "rhsusf_acc_anpeq15_light_sc": 1,
                "rhsusf_acc_anpeq15_top_sc": 1,
                "rhsusf_acc_anpeq15side": 1,
                "rhsusf_acc_anpeq15_bk_h": 1,
                "rhsusf_acc_anpeq15_bk_light_h": 1,
                "rhsusf_acc_anpeq15_bk_top_h": 1,
                "rhsusf_acc_anpeq15_bk_sc": 1,
                "rhsusf_acc_anpeq15_bk_light_sc": 1,
                "rhsusf_acc_anpeq15_bk_top_sc": 1,
                "rhsusf_acc_anpeq15side_bk": 1,
                "rhsusf_acc_anpeq15_wmx_h": 1,
                "rhsusf_acc_anpeq15_wmx_light_h": 1,
                "rhsusf_acc_anpeq15_wmx_sc": 1,
                "rhsusf_acc_anpeq15_wmx_light_sc": 1,
                "rhsusf_acc_anpeq16a": 1,
                "rhsusf_acc_anpeq16a_light": 1,
                "rhsusf_acc_anpeq16a_top_sc": 1,
                "rhsusf_acc_anpeq16a_light_top_sc": 1
            },
            "linkproxy": "a3|data_f|proxies|weapon_slots|side",
            "displayname": "Pointer Slot"
        }
    },
    "rhs_fold": "rhsusf_weap_MP7A2",
    "baseweapon": "rhsusf_weap_MP7A2_folded",
    "scope": 2,
    "rhs_fold_nogrip": 1,
    "initspeed": -1,
    "magazines": ["rhsusf_mag_40Rnd_46x30_FMJ","rhsusf_mag_40Rnd_46x30_JHP","rhsusf_mag_40Rnd_46x30_AP"],
    "magazinewell": ["CBA_46x30_MP7"],
    # Class: CfgWeapons|rhsusf_weap_MP7A1_base_f|Library [Indent level: 1],
    "library": {
        "libtextdesc": "Smaller than a conventional submachine gun, the 4.6mm MP7A1 is a compact and lightweight Personal Defense Weapon that can be carried like a handgun yet is capable of rifle-like effectiveness.."
    },
    "maxzeroing": 200,
    "discretedistance": [100,200],
    "maxrecoilsway": 0.0125,
    "swaydecayspeed": 1.25,
    "inertia": 0.35,
    "weaponinfotype": "rhs_rscOptics_mp7",
    # Class: CfgWeapons|rhsusf_weap_MP7A1_base_f|GunParticles [Indent level: 1],
    "gunparticles": {
        # Class: CfgWeapons|rhsusf_weap_MP7A1_base_f|GunParticles|SecondEffect [Indent level: 2]
        "secondeffect": {
            "positionname": "Nabojnicestart",
            "directionname": "Nabojniceend",
            "effectname": "CaselessAmmoCloud"
        },
        # Class: CfgWeapons|Rifle_Base_F|GunParticles|FirstEffect [Indent level: 2],
        "firsteffect": {
            "effectname": "RifleAssaultCloud",
            "positionname": "Usti hlavne",
            "directionname": "Konec hlavne"
        }
    },
    "opticszoommin": 0.25,
    "opticszoommax": 1.25,
    "opticszoominit": 0.75,
    "distancezoommin": 100,
    "distancezoommax": 100,
    "descriptionshort": "Sub-machine gun <br/>Caliber: 4.6x30 mm",
    "caseless": ["",1,1,1],
    "soundbullet": ["caseless",1],
    "selectionfireanim": "zasleh",
    "hiddenselections": ["camo","camo2","camoB"],
    "hiddenselectionstextures": ["rhsusf|addons|rhsusf_weapons2|mp7|mp7a2|data|mp7_co.paa","rhsusf|addons|rhsusf_weapons2|mp7|mp7a2|data|mp7_buis_co.paa","rhsusf|addons|rhsusf_weapons2|mp7|mp7a2|data|mp7_acc1_blk_co.paa"],
    "modes": ["Single","FullAuto"],
    # Class: CfgWeapons|rhsusf_weap_MP7A1_base_f|Single [Indent level: 1],
    "single": {
        "reloadtime": 0.0631579,
        "dispersion": 0.00203,
        "minrange": 2,
        "minrangeprobab": 0.3,
        "midrange": 200,
        "midrangeprobab": 0.7,
        "maxrange": 350,
        "maxrangeprobab": 0.05,
        "airateoffire": 2,
        "airateoffiredistance": 500,
        # Class: CfgWeapons|rhsusf_weap_MP7A1_base_f|Single|StandardSound [Indent level: 2],
        "standardsound": {
            "soundsetshot": ["RHSUSF_mp7_Shot_SoundSet","RHSUSF_rifle_small_Tail_SoundSet","RHSUSF_mp7_stereoLayer_SoundSet"]
        },
        # Class: CfgWeapons|rhsusf_weap_MP7A1_base_f|Single|SilencedSound [Indent level: 2],
        "silencedsound": {
            "soundsetshot": ["RHSUSF_MP7_Closure_SoundSet","RHSUSF_MP7_ShotSD_SoundSet","RHSUSF_rifle1_SD_Tail_SoundSet"]
        },
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons|SMG_02_base_F|Single|BaseSoundModeType [Indent level: 2],
        "basesoundmodetype": {
        },
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.03,0.0110829,0.021522,0.03,0.0159085,0.0085068,0.03,0.0138285,0.0058064,0.06,0.0066492,0.002394,0.06,-0.0007206,-0.001344,0.06,-0.001765,-0.00141,0.06,-0.0018385,-0.000882,0.06,-0.0009414,-0.00025,0.06,0,0],
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.03,0.0110829,0.0050218,0.03,0.0159085,0.0027522,0.03,0.0138285,0.002292,0.06,0.0066492,0.001083,0.06,-0.0007206,-0.000384,0.06,-0.001765,-0.000282,0.06,-0.0018385,-0.000147,0.06,-0.0009414,-7.5e-005,0.06,0,0],
        "multiplier": 1,
        "burst": 1,
        "burstrangemax": -1,
        "sound": ["",10,1],
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundend": [],
        "soundloop": [],
        "soundcontinuous": 0,
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "autofire": 0,
        "useaction": 0,
        "useactiontitle": "",
        "showtoplayer": 1,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "displayname": "Semi",
        "texturetype": "semi",
        "aidispersioncoefy": 1.7,
        "aidispersioncoefx": 1.4,
        "soundburst": 0,
        "requiredoptictype": -1,
        "airateoffiredispersion": 1
    },
    # Class: CfgWeapons|rhsusf_weap_MP7A1_base_f|FullAuto [Indent level: 1],
    "fullauto": {
        "reloadtime": 0.0631579,
        "dispersion": 0.00203,
        "minrange": 0,
        "minrangeprobab": 0.1,
        "midrange": 25,
        "midrangeprobab": 0.7,
        "maxrange": 70,
        "maxrangeprobab": 0.05,
        "airateoffire": 0.2,
        "airateoffiredistance": 50,
        # Class: CfgWeapons|rhsusf_weap_MP7A1_base_f|FullAuto|StandardSound [Indent level: 2],
        "standardsound": {
            "soundsetshot": ["RHSUSF_mp7_Shot_SoundSet","RHSUSF_rifle_small_Tail_SoundSet","RHSUSF_mp7_stereoLayer_SoundSet"]
        },
        # Class: CfgWeapons|rhsusf_weap_MP7A1_base_f|FullAuto|SilencedSound [Indent level: 2],
        "silencedsound": {
            "soundsetshot": ["RHSUSF_MP7_Closure_SoundSet","RHSUSF_MP7_ShotSD_SoundSet","RHSUSF_rifle1_SD_Tail_SoundSet"]
        },
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons|SMG_02_base_F|FullAuto|BaseSoundModeType [Indent level: 2],
        "basesoundmodetype": {
        },
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.06,0.0221658,0.0121958,0.06,0.031817,0.0052542,0.06,0.027657,0.0036672,0.06,0.0132984,0.001596,0.03,-0.0014412,-0.001344,0.03,-0.00353,-0.00141,0.03,-0.003677,-0.000882,0.06,-0.0018828,-0.00025,0.06,0,0],
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.06,0.0221658,0.0021522,0.06,0.031817,0.0017514,0.06,0.027657,0.0016808,0.06,0.0132984,0.000855,0.03,-0.0014412,-0.000768,0.03,-0.00353,-0.000564,0.03,-0.003677,-0.000294,0.06,-0.0018828,-0.00025,0.06,0,0],
        "sound": ["",10,1],
        "soundend": ["sound",1],
        "soundcontinuous": 0,
        "autofire": 1,
        "displayname": "Full",
        "texturetype": "fullAuto",
        "aidispersioncoefy": 3,
        "aidispersioncoefx": 2,
        "soundburst": 0,
        "multiplier": 1,
        "burst": 1,
        "burstrangemax": -1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundloop": [],
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "useaction": 0,
        "useactiontitle": "",
        "showtoplayer": 1,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "requiredoptictype": -1,
        "airateoffiredispersion": 1
    },
    "aidispersioncoefy": 6,
    "aidispersioncoefx": 4,
    "drysound": ["A3|sounds_f|weapons|Other|dry_1",0.562341,1,10],
    "reloadmagazinesound": ["rhsusf|addons|rhsusf_sounds|mp7|reload",1.3,1,13],
    "rhs_grip1_change": "rhsusf_weap_MP7A2_grip1",
    "rhs_grip2_change": "rhsusf_weap_MP7A2_grip2",
    "rhs_grip3_change": "rhsusf_weap_MP7A2_grip3",
    "_generalmacro": "SMG_02_base_F",
    "cursor": "smg",
    "discretedistanceinitindex": 0,
    "bullet1": ["A3|sounds_f|weapons|shells|9mm|metal_9mm_01",0.501187,1,15],
    "bullet2": ["A3|sounds_f|weapons|shells|9mm|metal_9mm_02",0.501187,1,15],
    "bullet3": ["A3|sounds_f|weapons|shells|9mm|metal_9mm_03",0.501187,1,15],
    "bullet4": ["A3|sounds_f|weapons|shells|9mm|metal_9mm_04",0.501187,1,15],
    "bullet5": ["A3|sounds_f|weapons|shells|9mm|dirt_9mm_01",0.501187,1,15],
    "bullet6": ["A3|sounds_f|weapons|shells|9mm|dirt_9mm_02",0.501187,1,15],
    "bullet7": ["A3|sounds_f|weapons|shells|9mm|dirt_9mm_03",0.501187,1,15],
    "bullet8": ["A3|sounds_f|weapons|shells|9mm|dirt_9mm_04",0.501187,1,15],
    "bullet9": ["A3|sounds_f|weapons|shells|9mm|grass_9mm_01",0.398107,1,15],
    "bullet10": ["A3|sounds_f|weapons|shells|9mm|grass_9mm_02",0.398107,1,15],
    "bullet11": ["A3|sounds_f|weapons|shells|9mm|grass_9mm_03",0.398107,1,15],
    "bullet12": ["A3|sounds_f|weapons|shells|9mm|grass_9mm_04",0.398107,1,15],
    "changefiremodesound": ["A3|Sounds_F|arsenal|weapons|SMG|Sting|firemode_Sting",0.251189,1,5],
    # Class: CfgWeapons|SMG_02_base_F|Burst [Indent level: 1],
    "burst": {
        "sounds": ["StandardSound","SilencedSound"],
        # Class: CfgWeapons|SMG_02_base_F|Burst|BaseSoundModeType [Indent level: 2],
        "basesoundmodetype": {
        },
        # Class: CfgWeapons|SMG_02_base_F|Burst|StandardSound [Indent level: 2],
        "standardsound": {
            "soundsetshot": ["SMGSting_Shot_SoundSet","SMGSting_Tail_SoundSet","SMGSting_InteriorTail_SoundSet"]
        },
        # Class: CfgWeapons|SMG_02_base_F|Burst|SilencedSound [Indent level: 2],
        "silencedsound": {
            "soundsetshot": ["SMGSting_silencerShot_SoundSet","SMGSting_silencerTail_SoundSet","SMGSting_silencerInteriorTail_SoundSet"]
        },
        "soundburst": 0,
        "burst": 3,
        "reloadtime": 0.0545,
        "dispersion": 0.00116,
        # Recoil Array: recoil,
        "recoil": [0,0,0,0.03,0.0110829,0.014348,0.03,0.0159085,0.0060048,0.03,0.0138285,0.004584,0.03,0.0066492,0.001824,0.03,-0.0007206,-0.00192,0.03,-0.001765,-0.002256,0.03,-0.0018385,-0.001764,0.03,-0.0009414,-0.0005,0.06,0,0],
        # Recoil Array: recoilprone,
        "recoilprone": [0,0,0,0.03,0.0110829,0.0021522,0.03,0.0159085,0.0017514,0.03,0.0138285,0.0016808,0.06,0.0066492,0.000855,0.06,-0.0007206,-0.000768,0.06,-0.001765,-0.000564,0.06,-0.0018385,-0.000294,0.06,-0.0009414,-0.00025,0.06,0,0],
        "minrange": 2,
        "minrangeprobab": 0.3,
        "midrange": 50,
        "midrangeprobab": 0.7,
        "maxrange": 100,
        "maxrangeprobab": 0.05,
        "airateoffire": 1,
        "airateoffiredistance": 250,
        "sound": ["",10,1],
        "soundloop": ["sound",1],
        "soundend": ["sound",1],
        "displayname": "Burst",
        "texturetype": "burst",
        "aidispersioncoefy": 2.4,
        "aidispersioncoefx": 1.9,
        "multiplier": 1,
        "burstrangemax": -1,
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundcontinuous": 0,
        "weaponsoundeffect": "",
        "ffcount": 1,
        "ffmagnitude": 0.5,
        "fffrequency": 11,
        "flash": "gunfire",
        "flashsize": 0.1,
        "autofire": 0,
        "useaction": 0,
        "useactiontitle": "",
        "showtoplayer": 1,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "canshootinwater": 0,
        "requiredoptictype": -1,
        "airateoffiredispersion": 1
    },
    # Class: CfgWeapons|SMG_02_base_F|UGL_F [Indent level: 1],
    "ugl_f": {
        "displayname": "EGLM",
        "magazines": ["1Rnd_HE_Grenade_shell","UGL_FlareWhite_F","UGL_FlareGreen_F","UGL_FlareRed_F","UGL_FlareYellow_F","UGL_FlareCIR_F","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeRed_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell","1Rnd_SmokeYellow_Grenade_shell","1Rnd_SmokePurple_Grenade_shell","1Rnd_SmokeBlue_Grenade_shell","1Rnd_SmokeOrange_Grenade_shell"],
        "magazinewell": ["UGL_40x36"],
        "changefiremodesound": ["A3|Sounds_F|arsenal|weapons|UGL|Firemode_ugl",0.316228,1,5],
        "reloadmagazinesound": ["A3|Sounds_F|arsenal|weapons|UGL|Reload_UGL",0.562341,1,10],
        "drysound": ["A3|Sounds_F|arsenal|weapons|UGL|Dry_ugl",0.562341,1,10],
        "modes": ["Single"],
        # Class: CfgWeapons|UGL_F|Single [Indent level: 1],
        "single": {
            "sounds": ["StandardSound"],
            # Class: CfgWeapons|UGL_F|Single|BaseSoundModeType [Indent level: 2],
            "basesoundmodetype": {
                "closure1": ["A3|Sounds_F|arsenal|weapons|UGL|Closure_UGL",1,1,10],
                "soundclosure": ["closure1",1]
            },
            # Class: CfgWeapons|UGL_F|Single|StandardSound [Indent level: 2],
            "standardsound": {
                "begin1": ["A3|Sounds_F|arsenal|weapons|UGL|UGL_01",0.707946,1,200],
                "begin2": ["A3|Sounds_F|arsenal|weapons|UGL|UGL_02",0.707946,1,200],
                "soundbegin": ["begin1",0.5,"begin2",0.5],
                "soundsetshot": ["UGL_shot_SoundSet","UGL_Tail_SoundSet","UGL_InteriorTail_SoundSet"],
                "closure1": ["A3|Sounds_F|arsenal|weapons|UGL|Closure_UGL",1,1,10],
                "soundclosure": ["closure1",1]
            },
            # Recoil Array: recoil,
            "recoil": [0,0,0,0.08,0.01,0.05,0.05,-0.003,-0.008,0.2,0,0],
            # Recoil Array: recoilprone,
            "recoilprone": [0,0,0,0.08,0.01,0.05,0.05,-0.003,-0.008,0.2,0,0],
            "minrange": 30,
            "minrangeprobab": 0.1,
            "midrange": 200,
            "midrangeprobab": 0.7,
            "maxrange": 400,
            "maxrangeprobab": 0.05,
            "multiplier": 1,
            "burst": 1,
            "burstrangemax": -1,
            "dispersion": 0.0002,
            "sound": ["",10,1],
            "soundbegin": ["sound",1],
            "soundbeginwater": ["sound",1],
            "soundclosure": ["sound",1],
            "soundend": [],
            "soundloop": [],
            "soundcontinuous": 0,
            "weaponsoundeffect": "",
            "reloadtime": 0.1,
            "ffcount": 1,
            "ffmagnitude": 0.5,
            "fffrequency": 11,
            "flash": "gunfire",
            "flashsize": 0.1,
            "autofire": 0,
            "useaction": 0,
            "useactiontitle": "",
            "showtoplayer": 1,
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "canshootinwater": 0,
            "displayname": "Semi",
            "texturetype": "semi",
            "aidispersioncoefy": 1.7,
            "aidispersioncoefx": 1.4,
            "soundburst": 0,
            "requiredoptictype": -1,
            "airateoffire": 2,
            "airateoffiredispersion": 1,
            "airateoffiredistance": 500
        },
        # Recoil Class: recoil,
        # Class: CfgRecoils|recoil_default [Indent level: 0],
        "recoil": {
            "muzzleouter": [0.3,1,0.3,0.2],
            "muzzleinner": [0,0,0.1,0.1],
            "kickback": [0.03,0.06],
            "permanent": 0.1,
            "temporary": 0.01
        },
        "magazinereloadtime": 0,
        "reloadtime": 0.1,
        "optics": 1,
        "modeloptics": "-",
        "cameradir": "UGL look",
        "memorypointcamera": "UGL eye",
        "opticszoommin": 0.25,
        "opticszoommax": 1.25,
        "opticszoominit": 0.75,
        "weaponinfotype": "RscWeaponZeroing",
        "cursoraim": "gl",
        "cursor": "EmptyCursor",
        "value": 3,
        "type": 0,
        "reloadaction": "ReloadMagazine",
        "initspeed": 75,
        "canlock": 0,
        "autoreload": 0,
        "autoaimenabled": 0,
        "ffmagnitude": 0.1,
        "fffrequency": 1,
        "ffcount": 1,
        "dispersion": 0.00725,
        "aidispersioncoefy": 6,
        "maxleadspeed": 15,
        "muzzlepos": "usti granatometu",
        "muzzleend": "konec granatometu",
        "cartridgepos": "",
        "cartridgevel": "",
        "minrange": 30,
        "minrangeprobab": 0.1,
        "midrange": 200,
        "midrangeprobab": 0.7,
        "maxrange": 400,
        "maxrangeprobab": 0.05,
        "texturetype": "semi",
        "access": 3,
        "scope": 0,
        "picture": "",
        "uipicture": "",
        "ammo": "",
        "cursorsize": 1,
        "showaimcursorinternal": 1,
        "cursoraimon": "",
        "laser": 0,
        "hiddenselections": [],
        "hiddenselectionstextures": [],
        "hiddenunderwaterselections": [],
        "shownunderwaterselections": [],
        "hiddenunderwaterselectionstextures": [],
        "simulation": "Weapon",
        "namesound": "",
        "count": 0,
        "multiplier": 1,
        "burst": 1,
        "magazinereloadswitchphase": 1,
        "sound": ["",1,1],
        "soundbegin": ["sound",1],
        "soundbeginwater": ["sound",1],
        "soundclosure": ["sound",1],
        "soundend": ["sound",1],
        "soundloop": ["sound",1],
        "soundcontinuous": 0,
        "weaponsoundeffect": "",
        "soundburst": 1,
        "zeroingsound": ["",1,1],
        "reloadsound": ["",1,1],
        "emptysound": ["",1,1],
        "soundbullet": ["emptySound",1],
        "ballisticscomputer": 0,
        "irdistance": 0,
        "irdotintensity": 0.001,
        "aidispersioncoefx": 1,
        "lockacquire": 1,
        "enableattack": 1,
        "maxrecoilsway": 0.008,
        "swaydecayspeed": 2,
        "model": "",
        "modelspecial": "",
        "modelmagazine": "",
        "irlaserpos": "laser pos",
        "irlaserend": "laser dir",
        "selectionfireanim": "zasleh",
        "firespreadangle": 3,
        "usemodeloptics": 1,
        "opticsid": 0,
        "opticsppeffects": [],
        "opticsflare": 1,
        "forceoptics": 0,
        "useasbinocular": 0,
        "opticsdisableperipherialvision": 0.67,
        "distancezoommin": 400,
        "distancezoommax": 400,
        "primary": 10,
        "showswitchaction": 0,
        "showempty": 1,
        "autofire": 0,
        "showtoplayer": 1,
        "canshootinwater": 0,
        "airateoffire": 5,
        "airateoffiredistance": 500,
        "airateoffiredispersion": 0,
        "firelightduration": 0.05,
        "firelightintensity": 0.2,
        "firelightdiffuse": [0.937,0.631,0.259],
        "firelightambient": [0,0,0],
        # Class: CfgWeapons|Default|Eventhandlers [Indent level: 1],
        "eventhandlers": {
        },
        "backgroundreload": 0,
        "muzzles": ["this"],
        "useaction": 0,
        "useactiontitle": "",
        "candrop": 1,
        "weaponlockdelay": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "weight": 0,
        "handanim": [],
        "lockingtargetsound": ["",0.000316228,2],
        "lockedtargetsound": ["",0.000316228,6],
        "detectrange": 0,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "fireanims": [],
        # Class: CfgWeapons|Default|Library [Indent level: 1],
        "library": {
            "libtextdesc": ""
        },
        "descriptionshort": "",
        # Class: CfgWeapons|Default|GunFire [Indent level: 1],
        "gunfire": {
            "access": 0,
            "cloudletduration": 0.2,
            "cloudletanimperiod": 1,
            "cloudletsize": 1,
            "cloudletalpha": 1,
            "cloudletgrowup": 0.2,
            "cloudletfadein": 0.01,
            "cloudletfadeout": 0.5,
            "cloudletaccy": 0,
            "cloudletminyspeed": -100,
            "cloudletmaxyspeed": 100,
            "cloudletshape": "cloudletFire",
            "cloudletcolor": [1,1,1,0],
            "cloudletdensitycoef": -1,
            "interval": -0.01,
            "size": 3,
            "sourcesize": 0.5,
            "timetolive": 0,
            "initt": 4500,
            "deltat": -3000,
            # Class: CfgWeapons|Default|GunFire|Table [Indent level: 2],
            "table": {
                # Class: CfgWeapons|Default|GunFire|Table|T0 [Indent level: 3]
                "t0": {
                    "maxt": 0,
                    "color": [0.82,0.95,0.93,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T1 [Indent level: 3],
                "t1": {
                    "maxt": 200,
                    "color": [0.75,0.77,0.9,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T2 [Indent level: 3],
                "t2": {
                    "maxt": 400,
                    "color": [0.56,0.62,0.67,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T3 [Indent level: 3],
                "t3": {
                    "maxt": 600,
                    "color": [0.39,0.46,0.47,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T4 [Indent level: 3],
                "t4": {
                    "maxt": 800,
                    "color": [0.24,0.31,0.31,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T5 [Indent level: 3],
                "t5": {
                    "maxt": 1000,
                    "color": [0.23,0.31,0.29,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T6 [Indent level: 3],
                "t6": {
                    "maxt": 1500,
                    "color": [0.21,0.29,0.27,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T7 [Indent level: 3],
                "t7": {
                    "maxt": 2000,
                    "color": [0.19,0.23,0.21,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T8 [Indent level: 3],
                "t8": {
                    "maxt": 2300,
                    "color": [0.22,0.19,0.1,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T9 [Indent level: 3],
                "t9": {
                    "maxt": 2500,
                    "color": [0.35,0.2,0.02,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T10 [Indent level: 3],
                "t10": {
                    "maxt": 2600,
                    "color": [0.62,0.29,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T11 [Indent level: 3],
                "t11": {
                    "maxt": 2650,
                    "color": [0.59,0.35,0.05,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T12 [Indent level: 3],
                "t12": {
                    "maxt": 2700,
                    "color": [0.75,0.37,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T13 [Indent level: 3],
                "t13": {
                    "maxt": 2750,
                    "color": [0.88,0.34,0.03,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T14 [Indent level: 3],
                "t14": {
                    "maxt": 2800,
                    "color": [0.91,0.5,0.17,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T15 [Indent level: 3],
                "t15": {
                    "maxt": 2850,
                    "color": [1,0.6,0.2,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T16 [Indent level: 3],
                "t16": {
                    "maxt": 2900,
                    "color": [1,0.71,0.3,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T17 [Indent level: 3],
                "t17": {
                    "maxt": 2950,
                    "color": [0.98,0.83,0.41,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T18 [Indent level: 3],
                "t18": {
                    "maxt": 3000,
                    "color": [0.98,0.91,0.54,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T19 [Indent level: 3],
                "t19": {
                    "maxt": 3100,
                    "color": [0.98,0.99,0.6,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T20 [Indent level: 3],
                "t20": {
                    "maxt": 3300,
                    "color": [0.96,0.99,0.72,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T21 [Indent level: 3],
                "t21": {
                    "maxt": 3600,
                    "color": [1,0.98,0.91,0]
                },
                # Class: CfgWeapons|Default|GunFire|Table|T22 [Indent level: 3],
                "t22": {
                    "maxt": 4200,
                    "color": [1,1,1,0]
                }
            }
        },
        # Class: CfgWeapons|Default|GunClouds [Indent level: 1],
        "gunclouds": {
            "access": 0,
            "cloudletgrowup": 0.05,
            "cloudletfadein": 0,
            "cloudletfadeout": 0.1,
            "cloudletduration": 0.05,
            "cloudletalpha": 0.3,
            "cloudletaccy": 0,
            "cloudletminyspeed": -100,
            "cloudletmaxyspeed": 100,
            "interval": -0.02,
            "size": 0.3,
            "sourcesize": 0.02,
            "cloudletanimperiod": 1,
            "cloudletsize": 1,
            "cloudletshape": "cloudletClouds",
            "cloudletcolor": [1,1,1,0],
            "timetolive": 0,
            "initt": 0,
            "deltat": 0,
            # Class: CfgWeapons|Default|GunClouds|Table [Indent level: 2],
            "table": {
                # Class: CfgWeapons|Default|GunClouds|Table|T0 [Indent level: 3]
                "t0": {
                    "maxt": 0,
                    "color": [1,1,1,0]
                }
            }
        },
        "inertia": 0.5,
        "aimtransitionspeed": 1
    },
    "deployedpivot": "bipod",
    "htmin": 1,
    "htmax": 600,
    "afmax": 0,
    "mfmax": 0,
    "mfact": 1,
    "tbody": 100,
    "autofire": 1,
    "soundcontinuous": 0,
    "optics": 0,
    "cursoraim": "CursorAim",
    "value": 4,
    "namesound": "rifle",
    "reloadtime": 0.15,
    "modeloptics": "-",
    "sound": [],
    "opticsflare": 0,
    "autoreload": 0,
    "maxleadspeed": 23,
    "canlock": 0,
    "flash": "gunfire",
    "flashsize": 0.5,
    "dispersion": 0.00029,
    # Recoil Array: recoilprone,
    "recoilprone": [0,0,0,0.06,0.01,0.01,0.1,0,-0.02,0.1,-0.01,0.01,0.05,0,0],
    "ffmagnitude": 0.5,
    "fffrequency": 11,
    "ffcount": 3,
    "weaponpoolavailable": 1,
    "zeroingsound": ["A3|Sounds_F|arsenal|sfx|shared|zeroing_knob_tick_metal",0.316228,1,5],
    "dexterity": 1.7,
    "airateoffire": 0.5,
    "airateoffiredistance": 500,
    "access": 3,
    "uipicture": "",
    "ammo": "",
    "cursorsize": 1,
    "showaimcursorinternal": 1,
    "cursoraimon": "",
    "laser": 0,
    "hiddenunderwaterselections": [],
    "shownunderwaterselections": [],
    "hiddenunderwaterselectionstextures": [],
    "simulation": "Weapon",
    "count": 0,
    "multiplier": 1,
    "magazinereloadtime": 0,
    "magazinereloadswitchphase": 1,
    "soundbegin": ["sound",1],
    "soundbeginwater": ["sound",1],
    "soundclosure": ["sound",1],
    "soundend": ["sound",1],
    "soundloop": ["sound",1],
    "weaponsoundeffect": "",
    "soundburst": 1,
    "reloadsound": ["",1,1],
    "emptysound": ["",1,1],
    "ballisticscomputer": 0,
    "irdistance": 0,
    "irdotintensity": 0.001,
    "lockacquire": 1,
    "enableattack": 1,
    "modelspecial": "",
    "modelmagazine": "",
    "muzzlepos": "usti hlavne",
    "muzzleend": "konec hlavne",
    "irlaserpos": "laser pos",
    "irlaserend": "laser dir",
    "cartridgepos": "nabojnicestart",
    "cartridgevel": "nabojniceend",
    "memorypointcamera": "eye",
    "firespreadangle": 3,
    "usemodeloptics": 1,
    "opticsid": 0,
    "opticsppeffects": [],
    "forceoptics": 0,
    "useasbinocular": 0,
    "opticsdisableperipherialvision": 0.67,
    "primary": 10,
    "showswitchaction": 0,
    "showempty": 1,
    "showtoplayer": 1,
    "canshootinwater": 0,
    "airateoffiredispersion": 0,
    "firelightduration": 0.05,
    "firelightintensity": 0.2,
    "firelightdiffuse": [0.937,0.631,0.259],
    "firelightambient": [0,0,0],
    # Class: CfgWeapons|Default|Eventhandlers [Indent level: 1],
    "eventhandlers": {
    },
    "backgroundreload": 0,
    "muzzles": ["this"],
    "useaction": 0,
    "useactiontitle": "",
    "candrop": 1,
    "weaponlockdelay": 0,
    "weaponlocksystem": 0,
    "cmimmunity": 1,
    "weight": 0,
    "minrange": 1,
    "minrangeprobab": 0.3,
    "midrange": 150,
    "midrangeprobab": 0.58,
    "maxrange": 500,
    "maxrangeprobab": 0.04,
    "lockingtargetsound": ["",0.000316228,2],
    "lockedtargetsound": ["",0.000316228,6],
    "detectrange": 0,
    "artillerydispersion": 1,
    "artillerycharge": 1,
    "fireanims": [],
    # Class: CfgWeapons|Default|GunFire [Indent level: 1],
    "gunfire": {
        "access": 0,
        "cloudletduration": 0.2,
        "cloudletanimperiod": 1,
        "cloudletsize": 1,
        "cloudletalpha": 1,
        "cloudletgrowup": 0.2,
        "cloudletfadein": 0.01,
        "cloudletfadeout": 0.5,
        "cloudletaccy": 0,
        "cloudletminyspeed": -100,
        "cloudletmaxyspeed": 100,
        "cloudletshape": "cloudletFire",
        "cloudletcolor": [1,1,1,0],
        "cloudletdensitycoef": -1,
        "interval": -0.01,
        "size": 3,
        "sourcesize": 0.5,
        "timetolive": 0,
        "initt": 4500,
        "deltat": -3000,
        # Class: CfgWeapons|Default|GunFire|Table [Indent level: 2],
        "table": {
            # Class: CfgWeapons|Default|GunFire|Table|T0 [Indent level: 3]
            "t0": {
                "maxt": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T1 [Indent level: 3],
            "t1": {
                "maxt": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T2 [Indent level: 3],
            "t2": {
                "maxt": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T3 [Indent level: 3],
            "t3": {
                "maxt": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T4 [Indent level: 3],
            "t4": {
                "maxt": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T5 [Indent level: 3],
            "t5": {
                "maxt": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T6 [Indent level: 3],
            "t6": {
                "maxt": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T7 [Indent level: 3],
            "t7": {
                "maxt": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T8 [Indent level: 3],
            "t8": {
                "maxt": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T9 [Indent level: 3],
            "t9": {
                "maxt": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T10 [Indent level: 3],
            "t10": {
                "maxt": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T11 [Indent level: 3],
            "t11": {
                "maxt": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T12 [Indent level: 3],
            "t12": {
                "maxt": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T13 [Indent level: 3],
            "t13": {
                "maxt": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T14 [Indent level: 3],
            "t14": {
                "maxt": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T15 [Indent level: 3],
            "t15": {
                "maxt": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T16 [Indent level: 3],
            "t16": {
                "maxt": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T17 [Indent level: 3],
            "t17": {
                "maxt": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T18 [Indent level: 3],
            "t18": {
                "maxt": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T19 [Indent level: 3],
            "t19": {
                "maxt": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T20 [Indent level: 3],
            "t20": {
                "maxt": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T21 [Indent level: 3],
            "t21": {
                "maxt": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: CfgWeapons|Default|GunFire|Table|T22 [Indent level: 3],
            "t22": {
                "maxt": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgWeapons|Default|GunClouds [Indent level: 1],
    "gunclouds": {
        "access": 0,
        "cloudletgrowup": 0.05,
        "cloudletfadein": 0,
        "cloudletfadeout": 0.1,
        "cloudletduration": 0.05,
        "cloudletalpha": 0.3,
        "cloudletaccy": 0,
        "cloudletminyspeed": -100,
        "cloudletmaxyspeed": 100,
        "interval": -0.02,
        "size": 0.3,
        "sourcesize": 0.02,
        "cloudletanimperiod": 1,
        "cloudletsize": 1,
        "cloudletshape": "cloudletClouds",
        "cloudletcolor": [1,1,1,0],
        "timetolive": 0,
        "initt": 0,
        "deltat": 0,
        # Class: CfgWeapons|Default|GunClouds|Table [Indent level: 2],
        "table": {
            # Class: CfgWeapons|Default|GunClouds|Table|T0 [Indent level: 3]
            "t0": {
                "maxt": 0,
                "color": [1,1,1,0]
            }
        }
    },
    "texturetype": "default",
    "aimtransitionspeed": 1,
}