rhs_mag_3of56_5 = {
    "count": 5,
    "displayname": "3OF56 HE",
    # Ammo: CfgMagazines|rhs_mag_3of56|ammo [Indent level: 1],
    "ammo": {
        "_dictAmmoName": "rhs_ammo_3of56",
        "hit": 160,
        "indirecthit": 50,
        "indirecthitrange": 30,
        "cost": 10,
        "artillerylock": 1,
        "timetolive": 220,
        # Class: CfgAmmo|rhs_ammo_of462|CamShakeExplode [Indent level: 1],
        "camshakeexplode": {
            "power": "(122*0.2)*10",
            "duration": "((round (122^0.5))*0.2 max 0.2)",
            "frequency": 20,
            "distance": "((30 + 122^0.5))"
        },
        # Class: CfgAmmo|rhs_ammo_of462|CamShakeHit [Indent level: 1],
        "camshakehit": {
            "power": "122 * 10",
            "duration": "((round (122^0.25))*0.2 max 0.2)",
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo|rhs_ammo_of462|CamShakeFire [Indent level: 1],
        "camshakefire": {
            "power": "(122^0.25)*10",
            "duration": "((round (122^0.5))*0.2 max 0.2)",
            "frequency": 20,
            "distance": "((122^0.5))"
        },
        "aiammousageflags": "64+32+128+256",
        "warheadname": "HE",
        "dangerradiushit": 750,
        "suppressionradiushit": 75,
        "typicalspeed": 800,
        "caliber": 10,
        "deflecting": 0,
        "explosive": 0.8,
        "model": "A3|weapons_f|ammo|shell",
        "cratereffects": "ArtyShellCrater",
        "explosioneffects": "MortarExplosion",
        "whistledist": 60,
        "thrust": 0,
        "airfriction": 0,
        "sideairfriction": 0,
        "soundhit1": ["A3|Sounds_F|arsenal|explosives|shells|Artillery_tank_shell_155mm_explosion_01",2.51189,1,1900],
        "soundhit2": ["A3|Sounds_F|arsenal|explosives|shells|Artillery_tank_shell_155mm_explosion_02",2.51189,1,1900],
        "soundhit3": ["A3|Sounds_F|arsenal|explosives|shells|Artillery_tank_shell_155mm_explosion_03",2.51189,1,1900],
        "soundhit4": ["A3|Sounds_F|arsenal|explosives|shells|Artillery_tank_shell_155mm_explosion_04",2.51189,1,1900],
        "multisoundhit": ["soundHit1",0.25,"soundHit2",0.25,"soundHit3",0.25,"soundHit4",0.25],
        # Class: CfgAmmo|Sh_155mm_AMOS|CamShakePlayerFire [Indent level: 1],
        "camshakeplayerfire": {
            "power": 0.01,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "soundsetexplosion": ["Shell155mm_Exp_SoundSet","Shell155mm_Tail_SoundSet","Explosion_Debris_SoundSet"],
        "supersoniccracknear": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_close",0.316228,1,50],
        "supersoniccrackfar": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_50meters",0.223872,1,150],
        "craterwatereffects": "ImpactEffectsWaterHE",
        "visiblefire": 64,
        "audiblefire": 250,
        "muzzleeffect": "",
        "deflectiondirdistribution": 0.39,
        "penetrationdirdistribution": 0.26,
        "whistleonfire": 2,
        # Class: CfgAmmo|ShellBase|HitEffects [Indent level: 1],
        "hiteffects": {
            "hitwater": "ImpactEffectsWaterRocket"
        },
        "soundfakefall0": ["a3|Sounds_F|weapons|falling_bomb|fall_01",3.16228,1,1000],
        "soundfakefall1": ["a3|Sounds_F|weapons|falling_bomb|fall_02",3.16228,1,1000],
        "soundfakefall2": ["a3|Sounds_F|weapons|falling_bomb|fall_03",3.16228,1,1000],
        "soundfakefall3": ["a3|Sounds_F|weapons|falling_bomb|fall_04",3.16228,1,1000],
        "soundfakefall": ["soundFakeFall0",0.25,"soundFakeFall1",0.25,"soundFakeFall2",0.25,"soundFakeFall3",0.25],
        "soundsetsoniccrack": ["bulletSonicCrack_SoundSet","bulletSonicCrackTail_SoundSet"],
        "simulation": "shotShell",
        "simulationstep": 0.05,
        "soundhit": ["",316.228,1],
        "soundfly": ["",0.0316228,4],
        "visiblefiretime": 10,
        "access": 3,
        "underwaterhitrangecoef": 1,
        "explosionforcecoef": 1,
        "iscrateroriented": 0,
        "proxyshape": "",
        "cratershape": "",
        "weapontype": "Default",
        "animated": 0,
        "shadow": 0,
        "maxspeed": 0,
        "cartridge": "",
        "tracercolor": [0.7,0.7,0.5,0.04],
        "tracercolorr": [0.7,0.7,0.5,0.04],
        "soundengine": ["",1,1],
        "soundfall": ["",1,1],
        "hitgroundsoft": ["soundHit",1],
        "hitgroundhard": ["soundHit",1],
        "hitman": ["soundHit",1],
        "hitarmor": ["soundHit",1],
        "hitiron": ["soundHit",1],
        "hitbuilding": ["soundHit",1],
        "hitfoliage": ["soundHit",1],
        "hitwood": ["soundHit",1],
        "hitglass": ["soundHit",1],
        "hitglassarmored": ["soundHit",1],
        "hitconcrete": ["soundHit",1],
        "hitrubber": ["soundHit",1],
        "hitplastic": ["soundHit",1],
        "hitdefault": ["soundHit",1],
        "hitmetal": ["soundHit",1],
        "hitmetalplate": ["soundHit",1],
        "hittyre": ["soundHit",1],
        "hitwater": ["soundHit",1],
        "soundimpact": ["",1,1],
        "impactgroundsoft": ["soundImpact",1],
        "impactgroundhard": ["soundImpact",1],
        "impactman": ["soundImpact",1],
        "impactiron": ["soundImpact",1],
        "impactarmor": ["soundImpact",1],
        "impactbuilding": ["soundImpact",1],
        "impactfoliage": ["soundImpact",1],
        "impactwood": ["soundImpact",1],
        "impactglass": ["soundImpact",1],
        "impactglassarmored": ["soundImpact",1],
        "impactconcrete": ["soundImpact",1],
        "impactrubber": ["soundImpact",1],
        "impactplastic": ["soundImpact",1],
        "impactdefault": ["soundImpact",1],
        "impactmetal": ["soundImpact",1],
        "impactmetalplate": ["soundImpact",1],
        "impacttyre": ["soundImpact",1],
        "impactwater": ["soundImpact",1],
        "grenadefiresound": [],
        "grenadeburningsound": [],
        "deflectionslowdown": 0.8,
        "effectsmissile": "ExplosionEffects",
        "effectsmissileinit": "",
        "effectssmoke": "SmokeShellWhite",
        "effectsfire": "CannonFire",
        "effectflare": "FlareShell",
        "effectfly": "",
        "minejumpeffects": "",
        "watereffectoffset": 0.45,
        "directionalexplosion": 0,
        "explosionangle": 60,
        "explosiondir": "explosionDir",
        "explosionpos": "explosionPos",
        "explosioneffectsdir": "explosionDir",
        "minimumsafezone": 0.1,
        "soundtrigger": [],
        "soundactivation": [],
        "sounddeactivation": [],
        "explosionsoundeffect": "",
        "mintimetolive": 0,
        "irlock": 0,
        "airlock": 0,
        "laserlock": 0,
        "nvlock": 0,
        "hitonwater": 0,
        "lockseekradius": 100,
        "manualcontrol": 0,
        "maxcontrolrange": 350,
        "maneuvrability": 1,
        "tracklead": 1,
        "trackoversteer": 1,
        "missilelockcone": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "locktype": 0,
        "maverickweaponindexoffset": 0,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "autoseektarget": 0,
        "shootdistraction": -1,
        "explosiontime": 0,
        "fusedistance": 0,
        "inittime": 0,
        "thrusttime": 1.5,
        "icon": "",
        "submunitionammo": "",
        "explosiontype": "explosive",
        "minetrigger": "RangeTrigger",
        "mineboundingtime": 3,
        "mineboundingdist": 3,
        "mineinconspicuousness": 10,
        "minefloating": -1,
        "minedivespeed": 1,
        "mineplacedist": 0.5,
        "suppressionradiusbulletclose": -1,
        "dangerradiusbulletclose": -1,
        # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
        "nvgmarkers": {
        },
        "mindamageforcamshakehit": 0.55,
        # Class: CfgAmmo|Default|EventHandlers [Indent level: 1],
        "eventhandlers": {
        },
    },
    "eventhandlers": "rhs_ammo_3of56",
    "scope": 2,
    "namesound": "heat",
    "initspeed": 690,
    "rhs_magazineindex": 3,
    "muzzleimpulsefactor": 0.1,
    "author": "Bohemia Interactive",
    "displaynameshort": "HE",
    "displaynamemfdformat": "HE",
    "type": 0,
    "reloadaction": "",
    "maxleadspeed": 100,
    "weaponpoolavailable": 0,
    "value": 1,
    "model": "A3|weapons_F|ammo|mag_univ.p3d",
    "picture": "",
    "modelspecial": "",
    "useaction": 0,
    "useactiontitle": "",
    "selectionfireanim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    # Class: CfgMagazines|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "descriptionshort": "",
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0,
}