rhs_mag_m257_7_green = {
    # Ammo: CfgMagazines|rhs_mag_M257_7_green|ammo [Indent level: 1],
    "ammo": {
        "_dictAmmoName": "rhs_ammo_Hydra_M257",
        "model": "rhsusf|addons|rhsusf_airweapons|proxyammo|rhsusf_r_M257_fly",
        "proxyshape": "rhsusf|addons|rhsusf_airweapons|proxyammo|rhsusf_r_M257",
        "explosive": 0,
        "hit": 10,
        "indirecthit": 8,
        "indirecthitrange": 1,
        "triggertime": 8,
        "airfriction": 0.225,
        # Ammo: CfgAmmo|rhs_ammo_Hydra_M257|submunitionAmmo [Indent level: 1],
        "submunitionammo1": {
            "_dictAmmoName": "rhs_ammo_flare_M257",
            "triggertime": 2,
            "model": "rhsusf|addons|rhsusf_airweapons|submunitions|rhsusf_r_m257_drogue",
            "brightness": 10000,
            "lightcolor": [100,100,100,100],
            "timetolive": 120,
            "intensity": 100000,
            "flaresize": 90,
            "flaremaxdistance": 3000,
            "affectedbywind": 1,
            "useflare": 1,
            "deflecting": 30,
            "smokecolor": [1,1,1,0.5],
            "size": 1,
            "triggerspeedcoef": 1,
            "audiblefire": 20,
            "muzzleeffect": "BIS_fnc_effectFiredRifle",
            "hit": 5,
            "indirecthit": 2,
            "indirecthitrange": 0.2,
            "cost": 100,
            "simulation": "shotIlluminating",
            "simulationstep": 0.05,
            "explosive": 0,
            "soundhit": ["",0,1],
            "thrust": 0,
            "airfriction": 0,
            "sideairfriction": 0,
            "artillerylock": 1,
            "soundfly": ["",3.16228e-005,1],
            "soundengine": ["",0.0001,4],
            "visiblefire": 2,
            "visiblefiretime": 0,
            "access": 3,
            "underwaterhitrangecoef": 1,
            "typicalspeed": 900,
            "explosionforcecoef": 1,
            "iscrateroriented": 0,
            "proxyshape": "",
            "cratershape": "",
            "weapontype": "Default",
            "animated": 0,
            "shadow": 0,
            "maxspeed": 0,
            "cartridge": "",
            "tracercolor": [0.7,0.7,0.5,0.04],
            "tracercolorr": [0.7,0.7,0.5,0.04],
            "supersoniccracknear": ["",1,1],
            "supersoniccrackfar": ["",1,1],
            "soundfall": ["",1,1],
            "soundfakefall": ["soundFall",1],
            "hitgroundsoft": ["soundHit",1],
            "hitgroundhard": ["soundHit",1],
            "hitman": ["soundHit",1],
            "hitarmor": ["soundHit",1],
            "hitiron": ["soundHit",1],
            "hitbuilding": ["soundHit",1],
            "hitfoliage": ["soundHit",1],
            "hitwood": ["soundHit",1],
            "hitglass": ["soundHit",1],
            "hitglassarmored": ["soundHit",1],
            "hitconcrete": ["soundHit",1],
            "hitrubber": ["soundHit",1],
            "hitplastic": ["soundHit",1],
            "hitdefault": ["soundHit",1],
            "hitmetal": ["soundHit",1],
            "hitmetalplate": ["soundHit",1],
            "hittyre": ["soundHit",1],
            "hitwater": ["soundHit",1],
            "soundimpact": ["",1,1],
            "impactgroundsoft": ["soundImpact",1],
            "impactgroundhard": ["soundImpact",1],
            "impactman": ["soundImpact",1],
            "impactiron": ["soundImpact",1],
            "impactarmor": ["soundImpact",1],
            "impactbuilding": ["soundImpact",1],
            "impactfoliage": ["soundImpact",1],
            "impactwood": ["soundImpact",1],
            "impactglass": ["soundImpact",1],
            "impactglassarmored": ["soundImpact",1],
            "impactconcrete": ["soundImpact",1],
            "impactrubber": ["soundImpact",1],
            "impactplastic": ["soundImpact",1],
            "impactdefault": ["soundImpact",1],
            "impactmetal": ["soundImpact",1],
            "impactmetalplate": ["soundImpact",1],
            "impacttyre": ["soundImpact",1],
            "impactwater": ["soundImpact",1],
            "grenadefiresound": [],
            "grenadeburningsound": [],
            "deflectionslowdown": 0.8,
            "explosioneffects": "ExplosionEffects",
            "cratereffects": "ImpactEffectsMedium",
            "craterwatereffects": "ImpactEffectsWater",
            "effectsmissile": "ExplosionEffects",
            "effectsmissileinit": "",
            "effectssmoke": "SmokeShellWhite",
            "effectsfire": "CannonFire",
            "effectflare": "FlareShell",
            "effectfly": "",
            "minejumpeffects": "",
            "watereffectoffset": 0.45,
            "directionalexplosion": 0,
            "explosionangle": 60,
            "explosiondir": "explosionDir",
            "explosionpos": "explosionPos",
            "explosioneffectsdir": "explosionDir",
            "minimumsafezone": 0.1,
            "soundtrigger": [],
            "soundactivation": [],
            "sounddeactivation": [],
            "explosionsoundeffect": "",
            "mintimetolive": 0,
            "irlock": 0,
            "airlock": 0,
            "laserlock": 0,
            "nvlock": 0,
            "hitonwater": 0,
            "lockseekradius": 100,
            "manualcontrol": 0,
            "maxcontrolrange": 350,
            "maneuvrability": 1,
            "tracklead": 1,
            "trackoversteer": 1,
            "missilelockcone": 0,
            "weaponlocksystem": 0,
            "cmimmunity": 1,
            "locktype": 0,
            "maverickweaponindexoffset": 0,
            "artillerydispersion": 1,
            "artillerycharge": 1,
            "autoseektarget": 0,
            "shootdistraction": -1,
            "explosiontime": 0,
            "fusedistance": 0,
            "inittime": 0,
            "thrusttime": 1.5,
            "icon": "",
            "submunitionammo": "",
            "explosiontype": "explosive",
            "minetrigger": "RangeTrigger",
            "mineboundingtime": 3,
            "mineboundingdist": 3,
            "mineinconspicuousness": 10,
            "minefloating": -1,
            "minedivespeed": 1,
            "mineplacedist": 0.5,
            # Class: CfgAmmo|Default|HitEffects [Indent level: 1],
            "hiteffects": {
                "vehicle": "ImpactMetal",
                "object": "ImpactConcrete"
            },
            "suppressionradiusbulletclose": -1,
            "suppressionradiushit": -1,
            "dangerradiusbulletclose": -1,
            "dangerradiushit": -1,
            "caliber": 1,
            "whistledist": 0,
            "whistleonfire": 0,
            # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
            "nvgmarkers": {
            },
            "mindamageforcamshakehit": 0.55,
            # Class: CfgAmmo|Default|EventHandlers [Indent level: 1],
            "eventhandlers": {
            },
        },
        "submunitionconetype": ["random",1],
        "submunitionconeangle": 5,
        "submunitionparentspeedcoef": 0.1,
        "maverickweapon": 1,
        "maverickweaponindexoffset": 0,
        "cost": 75,
        "maxspeed": 740,
        "thrusttime": 1.1,
        "thrust": 800,
        "sideairfriction": 0.004,
        "timetolive": 60,
        "fusedistance": 40,
        "whistledist": 24,
        "warheadname": "HE",
        "manualcontrol": 0,
        "maxcontrolrange": 0,
        "airlock": 0,
        "irlock": 0,
        "laserlock": 0,
        "nvlock": 0,
        "weaponlocksystem": 0,
        "aiammousageflags": "64 + 128",
        "missilelockmindistance": 500,
        "missilelockmaxdistance": 3000,
        "inittime": 0.002,
        "maneuvrability": 0,
        "effectsmissileinit": "PylonBackEffectsFFAR",
        "muzzleeffect": "",
        "soundfly": ["A3|Sounds_F|weapons|Rockets|rocket_fly_1",0.630957,1.2,1700],
        # Class: CfgAmmo|Rocket_04_HE_F|CamShakeExplode [Indent level: 1],
        "camshakeexplode": {
            "power": 16,
            "duration": 1.8,
            "frequency": 20,
            "distance": 191.554
        },
        # Class: CfgAmmo|Rocket_04_HE_F|CamShakeHit [Indent level: 1],
        "camshakehit": {
            "power": 80,
            "duration": 0.6,
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo|Rocket_04_HE_F|CamShakeFire [Indent level: 1],
        "camshakefire": {
            "power": 2.9907,
            "duration": 1.8,
            "frequency": 20,
            "distance": 71.5542
        },
        # Class: CfgAmmo|Rocket_04_HE_F|CamShakePlayerFire [Indent level: 1],
        "camshakeplayerfire": {
            "power": 2,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "soundsetexplosion": ["RocketsLight_Exp_SoundSet","RocketsLight_Tail_SoundSet","Explosion_Debris_SoundSet"],
        "simulationstep": 0.01,
        "soundhit1": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_01",2.51189,1,2000],
        "soundhit2": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_02",2.51189,1,2000],
        "soundhit3": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_03",2.51189,1,2000],
        "multisoundhit": ["soundHit1",0.34,"soundHit2",0.33,"soundHit3",0.33],
        "explosionsoundeffect": "DefaultExplosion",
        "soundengine": ["",1,1,50],
        "supersoniccracknear": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_close",0.398107,1,20],
        "supersoniccrackfar": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_50meters",0.316228,1,50],
        "cratereffects": "ATMissileCrater",
        "explosioneffects": "ATMissileExplosion",
        "effectsmissile": "missile4",
        "deflecting": 0,
        "cmimmunity": 0.9,
        "dangerradiushit": -1,
        "suppressionradiushit": 30,
        # Class: CfgAmmo|MissileBase|HitEffects [Indent level: 1],
        "hiteffects": {
            "hitwater": "ImpactEffectsWaterRocket"
        },
        # Class: CfgAmmo|MissileBase|Components [Indent level: 1],
        "components": {
        },
        "htmin": 60,
        "htmax": 1800,
        "afmax": 200,
        "mfmax": 100,
        "mfact": 0,
        "tbody": 0,
        # Class: CfgAmmo|MissileBase|EventHandlers [Indent level: 1],
        "eventhandlers": {
            # Class: CfgAmmo|MissileBase|EventHandlers|RHS_APS_FiredEH [Indent level: 2]
            "rhs_aps_firedeh": {
                "fired": "_this spawn rhs_fnc_aps_missileFired"
            }
        },
        "simulation": "shotMissile",
        "missilelockcone": 50,
        "visiblefire": 32,
        "audiblefire": 32,
        "visiblefiretime": 20,
        "soundhit": ["",100,1],
        "access": 3,
        "underwaterhitrangecoef": 1,
        "typicalspeed": 900,
        "explosionforcecoef": 1,
        "iscrateroriented": 0,
        "cratershape": "",
        "weapontype": "Default",
        "animated": 0,
        "shadow": 0,
        "cartridge": "",
        "tracercolor": [0.7,0.7,0.5,0.04],
        "tracercolorr": [0.7,0.7,0.5,0.04],
        "soundfall": ["",1,1],
        "soundfakefall": ["soundFall",1],
        "hitgroundsoft": ["soundHit",1],
        "hitgroundhard": ["soundHit",1],
        "hitman": ["soundHit",1],
        "hitarmor": ["soundHit",1],
        "hitiron": ["soundHit",1],
        "hitbuilding": ["soundHit",1],
        "hitfoliage": ["soundHit",1],
        "hitwood": ["soundHit",1],
        "hitglass": ["soundHit",1],
        "hitglassarmored": ["soundHit",1],
        "hitconcrete": ["soundHit",1],
        "hitrubber": ["soundHit",1],
        "hitplastic": ["soundHit",1],
        "hitdefault": ["soundHit",1],
        "hitmetal": ["soundHit",1],
        "hitmetalplate": ["soundHit",1],
        "hittyre": ["soundHit",1],
        "hitwater": ["soundHit",1],
        "soundimpact": ["",1,1],
        "impactgroundsoft": ["soundImpact",1],
        "impactgroundhard": ["soundImpact",1],
        "impactman": ["soundImpact",1],
        "impactiron": ["soundImpact",1],
        "impactarmor": ["soundImpact",1],
        "impactbuilding": ["soundImpact",1],
        "impactfoliage": ["soundImpact",1],
        "impactwood": ["soundImpact",1],
        "impactglass": ["soundImpact",1],
        "impactglassarmored": ["soundImpact",1],
        "impactconcrete": ["soundImpact",1],
        "impactrubber": ["soundImpact",1],
        "impactplastic": ["soundImpact",1],
        "impactdefault": ["soundImpact",1],
        "impactmetal": ["soundImpact",1],
        "impactmetalplate": ["soundImpact",1],
        "impacttyre": ["soundImpact",1],
        "impactwater": ["soundImpact",1],
        "grenadefiresound": [],
        "grenadeburningsound": [],
        "deflectionslowdown": 0.8,
        "craterwatereffects": "ImpactEffectsWater",
        "effectssmoke": "SmokeShellWhite",
        "effectsfire": "CannonFire",
        "effectflare": "FlareShell",
        "effectfly": "",
        "minejumpeffects": "",
        "watereffectoffset": 0.45,
        "directionalexplosion": 0,
        "explosionangle": 60,
        "explosiondir": "explosionDir",
        "explosionpos": "explosionPos",
        "explosioneffectsdir": "explosionDir",
        "minimumsafezone": 0.1,
        "soundtrigger": [],
        "soundactivation": [],
        "sounddeactivation": [],
        "mintimetolive": 0,
        "artillerylock": 0,
        "hitonwater": 0,
        "lockseekradius": 100,
        "tracklead": 1,
        "trackoversteer": 1,
        "locktype": 0,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "autoseektarget": 0,
        "shootdistraction": -1,
        "explosiontime": 0,
        "icon": "",
        "explosiontype": "explosive",
        "minetrigger": "RangeTrigger",
        "mineboundingtime": 3,
        "mineboundingdist": 3,
        "mineinconspicuousness": 10,
        "minefloating": -1,
        "minedivespeed": 1,
        "mineplacedist": 0.5,
        "suppressionradiusbulletclose": -1,
        "dangerradiusbulletclose": -1,
        "caliber": 1,
        "whistleonfire": 0,
        # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
        "nvgmarkers": {
        },
        "mindamageforcamshakehit": 0.55,
    },
    "mindamageforcamshakehit": "rhs_ammo_Hydra_M257",
    "displayname": "M257 Hydra (LAU-68)",
    "displaynameshort": "ILLUM",
    "descriptionshort": "×7 ILLUM Hydra",
    "pylonweapon": "rhs_weap_FFARLauncher_M257",
    "model": "rhsusf|addons|rhsusf_airweapons|proxypylon|rhsusf_pylon_r_FFAR_7x_green",
    "hardpoints": ["RHS_HP_FFAR_USMC"],
    "scope": 2,
    "count": 7,
    "initspeed": 44,
    "maxleadspeed": 200,
    "namesound": "rockets",
    "weight": 48,
    "displaynamemfdformat": "RKT|%2|%1",
    # Class: CfgMagazines|rhs_mag_M151_7|mfdElements [Indent level: 1],
    "mfdelements": {
        # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_a10a_ammoname [Indent level: 2]
        "rhs_a10a_ammoname": {
            # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_a10a_ammoname|Bones [Indent level: 3]
            "bones": {
            },
            # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_a10a_ammoname|Draw [Indent level: 3],
            "draw": {
                "color": [1,1,1],
                "alpha": 1,
                # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_a10a_ammoname|Draw|PylonText1 [Indent level: 4],
                "pylontext1": {
                    "type": "text",
                    "source": "static",
                    "text": "RKT",
                    "scale": 1,
                    "sourcescale": 1,
                    "align": "center",
                    "pos": [[0.005,0.02],1],
                    "right": [[0.05,0.02],1],
                    "down": [[0.005,0.105],1]
                }
            }
        },
        # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_a10a_box [Indent level: 2],
        "rhs_a10a_box": {
            # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_a10a_box|Bones [Indent level: 3]
            "bones": {
            },
            # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_a10a_box|Draw [Indent level: 3],
            "draw": {
                "color": [0.15,1,0.15],
                "alpha": 1,
                # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_a10a_box|Draw|Default [Indent level: 4],
                "default": {
                    "condition": "PylonAmmoRelative>=0.001",
                    "color": [0.15,1,0.15,1],
                    "alpha": 0.22,
                    # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_a10a_box|Draw|Default|Shape [Indent level: 5],
                    "shape": {
                        "type": "polygon",
                        "width": 4,
                        "points": [[[[-0.015,-0.04],1],[[0.015,-0.04],1],[[0.015,0.04],1],[[-0.015,0.04],1]]]
                    }
                },
                # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_a10a_box|Draw|Selected [Indent level: 4],
                "selected": {
                    "condition": "PylonSelected*(PylonAmmoRelative>=0.001)",
                    "color": [0.15,1,0.15,1],
                    "alpha": 0.22,
                    # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_a10a_box|Draw|Selected|Shape [Indent level: 5],
                    "shape": {
                        "type": "polygon",
                        "width": 4,
                        "points": [[[[-0.015,0.05],1],[[0.015,0.05],1],[[0.015,0.13],1],[[-0.015,0.13],1]]]
                    }
                },
                # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_a10a_box|Draw|Empty [Indent level: 4],
                "empty": {
                    "condition": "PylonAmmoRelative<=0",
                    "color": [0.87,0,0],
                    "alpha": 0.22,
                    # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_a10a_box|Draw|Empty|Shape [Indent level: 5],
                    "shape": {
                        "type": "polygon",
                        "width": 4,
                        "points": [[[[0.02,0.05],1],[[0.05,0.05],1],[[0.05,0.13],1],[[0.02,0.13],1]]]
                    }
                }
            }
        },
        # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_ah64_ammoname [Indent level: 2],
        "rhs_ah64_ammoname": {
            # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_ah64_ammoname|Bones [Indent level: 3]
            "bones": {
            },
            # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_ah64_ammoname|Draw [Indent level: 3],
            "draw": {
                "condition": "pylonSelected",
                # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_ah64_ammoname|Draw|PylonText1 [Indent level: 4],
                "pylontext1": {
                    "type": "text",
                    "source": "static",
                    "text": "6PD",
                    "scale": 1,
                    "sourcescale": 1,
                    "align": "center",
                    "pos": [[0.005,0.02],1],
                    "right": [[0.05,0.02],1],
                    "down": [[0.005,0.105],1]
                },
                # Class: CfgMagazines|rhs_mag_M151_7|mfdElements|rhs_ah64_ammoname|Draw|PylonAmmo [Indent level: 4],
                "pylonammo": {
                    "type": "text",
                    "source": "ammo",
                    "scale": 1,
                    "sourcescale": 1,
                    "align": "center",
                    "pos": [[0.015,0.02],1],
                    "right": [[0.06,0.02],1],
                    "down": [[0.015,0.105],1]
                }
            }
        }
    },
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadaction": "",
    "weaponpoolavailable": 0,
    "value": 1,
    "picture": "",
    "modelspecial": "",
    "useaction": 0,
    "useactiontitle": "",
    "selectionfireanim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    # Class: CfgMagazines|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0,
}