rhs_fim92_mag = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "mass": 120,
    "displayName": "FIM-92F",
    "descriptionshort": "Type: Surface-to-air<br />Caliber: 70 mm<br />Used in: FIM-92",
    "ammo": "rhs_ammo_fim92_missile",
    "type": "6 * 		256",
    "picture": "\rhsusf\addons\rhsusf_weapons\icons\m_stinger_ca.paa",
    "model": "\rhsusf\addons\rhsusf_weapons\FIM92\Stinger_proxy",
    "initSpeed": 20,
    "maxLeadSpeed": 220,
    "displayNameShort": "AA",
    "value": 5,
    "allowedSlots": [901],
    "count": 1,
    "nameSound": "handgrenade",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}