rhs_mag_M441_HE = {
    "author": "Red Hammer Studios",
    "mass": 5.06,
    "ammo": "rhsusf_40mm_HE",
    "displayName": "M441 HE Grenade Round",
    "displaynameshort": "HE Grenade",
    "descriptionshort": "Type: High Explosive Grenade<br />Caliber: 40 mm<br />Rounds: 1<br />Used in: M203, M320, M79",
    "model": "\rhsusf\addons\rhsusf_weapons2\magazines\40mm\rhs_m443",
    "modelspecial": "\rhsusf\addons\rhsusf_weapons\mag_proxies\40mm\rhs_m443",
    "modelSpecialIsProxy": 1,
    "deleteIfEmpty": 0,
    "scope": 2,
    "type": 16,
    "picture": "\A3\Weapons_f\Data\ui\gear_UGL_slug_CA.paa",
    "initSpeed": 80,
    "count": 1,
    "nameSound": "",
    "value": 1,
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}