rhs_m136_hedp_mag = {
    "author": "Red Hammer Studios",
    "displayName": "M136 HEDP",
    "descriptionshort": "Type: High Explosive, Dual Purpose",
    "ammo": "rhs_ammo_M136_hedp_rocket",
    "allowedSlots": [801,701,901],
    "scope": 1,
    "picture": "\rhsusf\addons\rhsusf_weapons\icons\m_m136_ca.paa",
    "model": "\A3\weapons_f\empty",
    "type": "6 * 		256",
    "initSpeed": 290,
    "mass": 0,
    "value": 5,
    "count": 1,
    "nameSound": "handgrenade",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "displayNameShort": "",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}