rhs_mag_maaws_HE = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "displayName": "FFV441 HE",
    "model": "rhsusf|addons|rhsusf_weapons2|m3maaws|mag_m3maaws.p3d",
    "picture": "rhsusf|addons|rhsusf_weapons2|m3maaws|UI|gear_small_CA.paa",
    "initSpeed": 255,
    "descriptionShort": "High Explosive",
    "displaynameshort": "441 HE",
    # Ammo: rhs_ammo_maaws_HE,
    "ammo": {
        "ammo": "rhs_ammo_maaws_HE",
        "EffectFly": "ArtilleryTrails",
        "soundHit1": ["A3|Sounds_F|arsenal|explosives|shells|Artillery_tank_shell_155mm_explosion_01",2.51189,1,1900],
        "soundHit2": ["A3|Sounds_F|arsenal|explosives|shells|Artillery_tank_shell_155mm_explosion_02",2.51189,1,1900],
        "soundHit3": ["A3|Sounds_F|arsenal|explosives|shells|Artillery_tank_shell_155mm_explosion_03",2.51189,1,1900],
        "soundHit4": ["A3|Sounds_F|arsenal|explosives|shells|Artillery_tank_shell_155mm_explosion_04",2.51189,1,1900],
        "multiSoundHit": ["soundHit1",0.25,"soundHit2",0.25,"soundHit3",0.25,"soundHit4",0.25],
        "soundFly": ["A3|Sounds_F|arsenal|weapons_static|Missile_Launcher|rocket_fly",1.1,1.1,900],
        "model": "rhsusf|addons|rhsusf_weapons2|m3maaws|ammo_m3maaws.p3d",
        "hit": 75,
        "indirectHit": 65,
        "indirectHitRange": 11,
        "cost": 300,
        "airFriction": 0.01,
        "sideAirFriction": 0,
        "maxSpeed": 255,
        "initTime": 0,
        "thrustTime": 0.1,
        "thrust": 0.1,
        "fuseDistance": 15,
        "CraterEffects": "ArtyShellCrater",
        "explosionEffects": "MortarExplosion",
        "effectsMissileInit": "",
        "effectsMissile": "RHSUSF_SMAW_MissileTrail",
        "simulationStep": 0.02,
        "airLock": 0,
        "irLock": 0,
        "timeToLive": 25,
        "maneuvrability": 0,
        "allowAgainstInfantry": 1,
        # Class: CfgAmmo\rhs_ammo_maaws_HE\CamShakeExplode [Indent level: 1],
        "CamShakeExplode": {
            "power": "(55*0.2)",
            "duration": "((round (55^0.5))*0.2 max 0.2)",
            "frequency": 20,
            "distance": "((5 + 55^0.5)*8)"
        },
        # Class: CfgAmmo\rhs_ammo_maaws_HE\CamShakeHit [Indent level: 1],
        "CamShakeHit": {
            "power": 110,
            "duration": "((round (110^0.25))*0.2 max 0.2)",
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo\rhs_ammo_maaws_HE\CamShakeFire [Indent level: 1],
        "CamShakeFire": {
            "power": 5,
            "duration": "((round (20^0.5))*0.2 max 0.2)",
            "frequency": 20,
            "distance": "((20^0.5)*8)"
        },
        # Class: CfgAmmo\rhs_ammo_maaws_HE\CamShakePlayerFire [Indent level: 1],
        "CamShakePlayerFire": {
            "power": 2,
            "duration": 0.2,
            "frequency": 8,
            "distance": 1
        },
        "visibleFire": 15,
        "audibleFire": 20,
        "dangerRadiusHit": -1,
        "suppressionRadiusHit": 30,
        "soundHit": ["A3|Sounds_F|weapons|Rockets|explosion_missile_02",2.51189,1,2500],
        "explosionSoundEffect": "DefaultExplosion",
        "soundEngine": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|soundfly1.ogg",1,1,750],
        "supersonicCrackNear": ["",1,1,50],
        "supersonicCrackFar": ["",1,1,150],
        "muzzleEffect": "BIS_fnc_effectFiredRocket",
        # Class: CfgAmmo\RocketBase\HitEffects [Indent level: 1],
        "HitEffects": {
            "hitWater": "ImpactEffectsWaterRocket"
        },
        "soundsetsoniccrack": ["jsrs_sc_rocket_flyby_soundset"],
        "soundsetfly": ["jsrs_sc_rocket_flyby_soundset"],
        "soundsetexplosion": ["jsrs_rocket_explosion_soundset","jsrs_shell_explosion_stereo_soundset","jsrs_shell_explosion_reverb_soundset"],
        # Class: CfgAmmo\RocketBase\EventHandlers [Indent level: 1],
        "EventHandlers": {
            # Class: CfgAmmo\RocketBase\EventHandlers\RHS_APS_FiredEH [Indent level: 2]
            "RHS_APS_FiredEH": {
                "fired": "_this spawn rhs_fnc_aps_missileFired"
            }
        },
        "simulation": "shotRocket",
        "maxControlRange": 0,
        "visibleFireTime": 20,
        "deflecting": 5,
        "access": 3,
        "underwaterHitRangeCoef": 1,
        "typicalSpeed": 900,
        "explosionForceCoef": 1,
        "isCraterOriented": 0,
        "proxyShape": "",
        "craterShape": "",
        "weaponType": "Default",
        "animated": 0,
        "shadow": 0,
        "cartridge": "",
        "tracerColor": [0.7,0.7,0.5,0.04],
        "tracerColorR": [0.7,0.7,0.5,0.04],
        "soundFall": ["",1,1],
        "soundFakeFall": ["soundFall",1],
        "hitGroundSoft": ["soundHit",1],
        "hitGroundHard": ["soundHit",1],
        "hitMan": ["soundHit",1],
        "hitArmor": ["soundHit",1],
        "hitIron": ["soundHit",1],
        "hitBuilding": ["soundHit",1],
        "hitFoliage": ["soundHit",1],
        "hitWood": ["soundHit",1],
        "hitGlass": ["soundHit",1],
        "hitGlassArmored": ["soundHit",1],
        "hitConcrete": ["soundHit",1],
        "hitRubber": ["soundHit",1],
        "hitPlastic": ["soundHit",1],
        "hitDefault": ["soundHit",1],
        "hitMetal": ["soundHit",1],
        "hitMetalplate": ["soundHit",1],
        "hitTyre": ["soundHit",1],
        "hitWater": ["soundHit",1],
        "soundImpact": ["",1,1],
        "impactGroundSoft": ["soundImpact",1],
        "impactGroundHard": ["soundImpact",1],
        "impactMan": ["soundImpact",1],
        "impactIron": ["soundImpact",1],
        "impactArmor": ["soundImpact",1],
        "impactBuilding": ["soundImpact",1],
        "impactFoliage": ["soundImpact",1],
        "impactWood": ["soundImpact",1],
        "impactGlass": ["soundImpact",1],
        "impactGlassArmored": ["soundImpact",1],
        "impactConcrete": ["soundImpact",1],
        "impactRubber": ["soundImpact",1],
        "impactPlastic": ["soundImpact",1],
        "impactDefault": ["soundImpact",1],
        "impactMetal": ["soundImpact",1],
        "impactMetalplate": ["soundImpact",1],
        "impactTyre": ["soundImpact",1],
        "impactWater": ["soundImpact",1],
        "grenadeFireSound": [],
        "grenadeBurningSound": [],
        "deflectionSlowDown": 0.8,
        "explosive": 1,
        "craterWaterEffects": "ImpactEffectsWater",
        "effectsSmoke": "SmokeShellWhite",
        "effectsFire": "CannonFire",
        "effectFlare": "FlareShell",
        "mineJumpEffects": "",
        "waterEffectOffset": 0.45,
        "directionalExplosion": 0,
        "explosionAngle": 60,
        "explosionDir": "explosionDir",
        "explosionPos": "explosionPos",
        "explosionEffectsDir": "explosionDir",
        "minimumSafeZone": 0.1,
        "soundTrigger": [],
        "soundActivation": [],
        "soundDeactivation": [],
        "minTimeToLive": 0,
        "laserLock": 0,
        "nvLock": 0,
        "artilleryLock": 0,
        "hitOnWater": 0,
        "lockSeekRadius": 100,
        "manualControl": 0,
        "trackLead": 1,
        "trackOversteer": 1,
        "missileLockCone": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "lockType": 0,
        "maverickweaponIndexOffset": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "autoSeekTarget": 0,
        "shootDistraction": -1,
        "explosionTime": 0,
        "icon": "",
        # Ammo: ,
        "submunitionAmmo": {
            "submunitionAmmo": "",
        },
        "submunitionAmmo": "",
        "explosionType": "explosive",
        "mineTrigger": "RangeTrigger",
        "mineBoundingTime": 3,
        "mineBoundingDist": 3,
        "mineInconspicuousness": 10,
        "mineFloating": -1,
        "mineDiveSpeed": 1,
        "minePlaceDist": 0.5,
        "suppressionRadiusBulletClose": -1,
        "dangerRadiusBulletClose": -1,
        "caliber": 1,
        "whistleDist": 0,
        "whistleOnFire": 0,
        # Class: CfgAmmo\Default\NVGMarkers [Indent level: 1],
        "NVGMarkers": {
        },
        "minDamageForCamShakeHit": 0.55,
    },
    "minDamageForCamShakeHit": "rhs_ammo_maaws_HE",
    "type": "2*        256",
    "mass": "68,36",
    "value": 5,
    "allowedSlots": [901],
    "count": 1,
    "nameSound": "handgrenade",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines\Default\InventoryPlacements [Indent level: 1],
    "InventoryPlacements": {
    },
    # Class: CfgMagazines\Default\Library [Indent level: 1],
    "Library": {
        "libTextDesc": ""
    },
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0,
}