rhs_fgm148_magazine_AT = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "displayName": "Javelin AT",
    "descriptionshort": "Type: High Explosive Anti Tank<br />Caliber: 127 mm<br />Used in: FGM-148",
    "picture": "rhsusf|addons|rhsusf_weapons|FGM148|data|UI|m_fgm148_ca.paa",
    "model": "rhsusf|addons|rhsusf_weapons|FGM148|fgm148_tube_ammo",
    "count": 1,
    # Ammo: rhs_ammo_M_fgm148_AT,
    "ammo": {
        "ammo": "rhs_ammo_M_fgm148_AT",
        "afMax": 200,
        "aiAmmoUsageFlags": "128 + 512",
        "audibleFire": 32,
        "caliber": 1,
        "warheadName": "TandemHEAT",
        "submunitionAmmo": "rhs_ammo_M_fgm148_AT_penetrator",
        "submunitionDirectionType": "SubmunitionModelDirection",
        "submunitionInitialOffset": [0,0,-0.2],
        "submunitionParentSpeedCoef": 0,
        "submunitionInitSpeed": 1000,
        "triggerOnImpact": 1,
        "deleteParentWhenTriggered": 0,
        "model": "rhsusf|addons|rhsusf_weapons|FGM148|fgm148_missile",
        "hit": 350,
        "indirectHit": 40,
        "indirectHitRange": 4,
        "explosive": 0.65,
        "flightProfiles": ["Direct","TopDown","Cruise"],
        # Class: CfgAmmo\rhs_ammo_M_fgm148_AT\Direct [Indent level: 1],
        "Direct": {
        },
        # Class: CfgAmmo\rhs_ammo_M_fgm148_AT\TopDown [Indent level: 1],
        "TopDown": {
            "ascendHeight": 160,
            "descendDistance": 200,
            "minDistance": 150,
            "ascendAngle": 45
        },
        # Class: CfgAmmo\rhs_ammo_M_fgm148_AT\Cruise [Indent level: 1],
        "Cruise": {
            "preferredFlightAltitude": 60,
            "lockDistanceToTarget": 1000
        },
        "irLock": 1,
        "laserLock": 1,
        "nvLock": 0,
        "airLock": 1,
        "autoSeekTarget": 0,
        "allowAgainstInfantry": 0,
        "airFriction": 0.2,
        "sideAirFriction": 0.35,
        "trackOversteer": 1.4,
        "trackLead": 1,
        "maxSpeed": 460,
        "maneuvrability": 32,
        "manualControl": 0,
        "maxControlRange": 4000,
        "fuseDistance": 30,
        "thrust": 75,
        "thrustTime": 4.2,
        "initTime": 0.5,
        "timeToLive": 60,
        "whistleDist": 4,
        "deflecting": 0,
        "simulationStep": 0.001,
        "cmImmunity": 0.9,
        "cost": 1000,
        "effectsMissile": "missile2",
        "effectsMissileInit": "RocketBackEffectsRPG",
        "effectsSmoke": "SmokeShellWhite",
        "missileLockMaxDistance": 3000,
        "missileLockMinDistance": 100,
        "missileLockMaxSpeed": 41,
        "missileLockCone": 10,
        "weaponLockSystem": "2 + 16",
        # Class: CfgAmmo\rhs_ammo_M_fgm148_AT\Components [Indent level: 1],
        "Components": {
            # Class: CfgAmmo\rhs_ammo_M_fgm148_AT\Components\SensorsManagerComponent [Indent level: 2]
            "SensorsManagerComponent": {
                # Class: CfgAmmo\rhs_ammo_M_fgm148_AT\Components\SensorsManagerComponent\Components [Indent level: 3]
                "Components": {
                    # Class: CfgAmmo\rhs_ammo_M_fgm148_AT\Components\SensorsManagerComponent\Components\IRSensorComponent [Indent level: 4]
                    "IRSensorComponent": {
                        # Class: CfgAmmo\rhs_ammo_M_fgm148_AT\Components\SensorsManagerComponent\Components\IRSensorComponent\AirTarget [Indent level: 5]
                        "AirTarget": {
                            "minRange": 500,
                            "maxRange": 3000,
                            "objectDistanceLimitCoef": 1,
                            "viewDistanceLimitCoef": -1
                        },
                        # Class: CfgAmmo\rhs_ammo_M_fgm148_AT\Components\SensorsManagerComponent\Components\IRSensorComponent\GroundTarget [Indent level: 5],
                        "GroundTarget": {
                            "minRange": 500,
                            "maxRange": 3000,
                            "objectDistanceLimitCoef": 1,
                            "viewDistanceLimitCoef": -1
                        },
                        "typeRecognitionDistance": -1,
                        "angleRangeHorizontal": 20,
                        "angleRangeVertical": 20,
                        "groundNoiseDistanceCoef": 0,
                        "maxGroundNoiseDistance": 0,
                        "minTrackableSpeed": 0,
                        "maxTrackableSpeed": 37,
                        "minTrackableATL": 0,
                        "minSpeedThreshold": 0,
                        "maxSpeedThreshold": 1,
                        "maxFogSeeThrough": 0.95,
                        "aimDown": 25,
                        "componentType": "IRSensorComponent",
                        "color": [1,0,0,1],
                        "allowsMarking": 1,
                        "animDirection": "",
                        "maxTrackableATL": 1e+010
                    }
                }
            }
        },
        "soundHit1": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_01",2.51189,1,2000],
        "soundHit2": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_02",2.51189,1,2000],
        "soundHit3": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_03",2.51189,1,2000],
        "multiSoundHit": ["soundHit1",0.34,"soundHit2",0.33,"soundHit3",0.33],
        "explosionSoundEffect": "DefaultExplosion",
        "soundFly": ["",1,1,400],
        "soundEngine": ["",1,1,50],
        "supersonicCrackNear": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_close",0.398107,1,20],
        "supersonicCrackFar": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_50meters",0.316228,1,50],
        "CraterEffects": "ATMissileCrater",
        "explosionEffects": "ATMissileExplosion",
        "muzzleEffect": "BIS_fnc_effectFiredRocket",
        "dangerRadiusHit": -1,
        "suppressionRadiusHit": 30,
        # Class: CfgAmmo\MissileBase\HitEffects [Indent level: 1],
        "HitEffects": {
            "hitWater": "ImpactEffectsWaterRocket"
        },
        "maverickWeaponIndexOffset": 0,
        "htMin": 60,
        "htMax": 1800,
        "mfMax": 100,
        "mFact": 0,
        "tBody": 0,
        # Class: CfgAmmo\MissileBase\EventHandlers [Indent level: 1],
        "EventHandlers": {
            # Class: CfgAmmo\MissileBase\EventHandlers\RHS_APS_FiredEH [Indent level: 2]
            "RHS_APS_FiredEH": {
                "fired": "_this spawn rhs_fnc_aps_missileFired"
            }
        },
        "simulation": "shotMissile",
        "visibleFire": 32,
        "visibleFireTime": 20,
        "soundHit": ["",100,1],
        "access": 3,
        "underwaterHitRangeCoef": 1,
        "typicalSpeed": 900,
        "explosionForceCoef": 1,
        "isCraterOriented": 0,
        "proxyShape": "",
        "craterShape": "",
        "weaponType": "Default",
        "animated": 0,
        "shadow": 0,
        "cartridge": "",
        "tracerColor": [0.7,0.7,0.5,0.04],
        "tracerColorR": [0.7,0.7,0.5,0.04],
        "soundFall": ["",1,1],
        "soundFakeFall": ["soundFall",1],
        "hitGroundSoft": ["soundHit",1],
        "hitGroundHard": ["soundHit",1],
        "hitMan": ["soundHit",1],
        "hitArmor": ["soundHit",1],
        "hitIron": ["soundHit",1],
        "hitBuilding": ["soundHit",1],
        "hitFoliage": ["soundHit",1],
        "hitWood": ["soundHit",1],
        "hitGlass": ["soundHit",1],
        "hitGlassArmored": ["soundHit",1],
        "hitConcrete": ["soundHit",1],
        "hitRubber": ["soundHit",1],
        "hitPlastic": ["soundHit",1],
        "hitDefault": ["soundHit",1],
        "hitMetal": ["soundHit",1],
        "hitMetalplate": ["soundHit",1],
        "hitTyre": ["soundHit",1],
        "hitWater": ["soundHit",1],
        "soundImpact": ["",1,1],
        "impactGroundSoft": ["soundImpact",1],
        "impactGroundHard": ["soundImpact",1],
        "impactMan": ["soundImpact",1],
        "impactIron": ["soundImpact",1],
        "impactArmor": ["soundImpact",1],
        "impactBuilding": ["soundImpact",1],
        "impactFoliage": ["soundImpact",1],
        "impactWood": ["soundImpact",1],
        "impactGlass": ["soundImpact",1],
        "impactGlassArmored": ["soundImpact",1],
        "impactConcrete": ["soundImpact",1],
        "impactRubber": ["soundImpact",1],
        "impactPlastic": ["soundImpact",1],
        "impactDefault": ["soundImpact",1],
        "impactMetal": ["soundImpact",1],
        "impactMetalplate": ["soundImpact",1],
        "impactTyre": ["soundImpact",1],
        "impactWater": ["soundImpact",1],
        "grenadeFireSound": [],
        "grenadeBurningSound": [],
        "deflectionSlowDown": 0.8,
        "craterWaterEffects": "ImpactEffectsWater",
        "effectsFire": "CannonFire",
        "effectFlare": "FlareShell",
        "effectFly": "",
        "mineJumpEffects": "",
        "waterEffectOffset": 0.45,
        "directionalExplosion": 0,
        "explosionAngle": 60,
        "explosionDir": "explosionDir",
        "explosionPos": "explosionPos",
        "explosionEffectsDir": "explosionDir",
        "minimumSafeZone": 0.1,
        "soundTrigger": [],
        "soundActivation": [],
        "soundDeactivation": [],
        "minTimeToLive": 0,
        "artilleryLock": 0,
        "hitOnWater": 0,
        "lockSeekRadius": 100,
        "lockType": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "shootDistraction": -1,
        "explosionTime": 0,
        "icon": "",
        "explosionType": "explosive",
        "mineTrigger": "RangeTrigger",
        "mineBoundingTime": 3,
        "mineBoundingDist": 3,
        "mineInconspicuousness": 10,
        "mineFloating": -1,
        "mineDiveSpeed": 1,
        "minePlaceDist": 0.5,
        "suppressionRadiusBulletClose": -1,
        "dangerRadiusBulletClose": -1,
        "whistleOnFire": 0,
        # Class: CfgAmmo\Default\NVGMarkers [Indent level: 1],
        "NVGMarkers": {
        },
        "minDamageForCamShakeHit": 0.55,
    },
        "minDamageForCamShakeHit": "rhs_ammo_M_fgm148_AT",
    "initSpeed": 10,
    "maxLeadSpeed": 350,
    "mass": 286.88,
    "value": 5,
    "type": "2*		256",
    "allowedSlots": [901],
    "nameSound": "handgrenade",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "displayNameShort": "",
    "weight": 0,
    # Class: CfgMagazines\Default\InventoryPlacements [Indent level: 1],
    "InventoryPlacements": {
    },
    # Class: CfgMagazines\Default\Library [Indent level: 1],
    "Library": {
        "libTextDesc": ""
    },
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0,
}