rhs_fgm148_magazine_AT = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "displayName": "Javelin AT",
    "descriptionshort": "Type: High Explosive Anti Tank<br />Caliber: 127 mm<br />Used in: FGM-148",
    "picture": "\rhsusf\addons\rhsusf_weapons\FGM148\data\UI\m_fgm148_ca.paa",
    "model": "\rhsusf\addons\rhsusf_weapons\FGM148\fgm148_tube_ammo",
    "count": 1,
    "ammo": "rhs_ammo_M_fgm148_AT",
    "initSpeed": 10,
    "maxLeadSpeed": 350,
    "mass": 286.88,
    "value": 5,
    "type": "2*		256",
    "allowedSlots": [901],
    "nameSound": "handgrenade",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "displayNameShort": "",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}