rhs_mag_smaw_HEDP = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "displayName": "Mk.3 HEDP",
    "descriptionshort": "Type: High Explosive Dual Purpose<br />Caliber: 83 mm<br />Used in: SMAW",
    "model": "rhsusf\addons\rhsusf_weapons2\smaw\ammo_smaw.p3d",
    "picture": "\rhsusf\addons\rhsusf_weapons2\smaw\UI\ammo_CA.paa",
    "initSpeed": 220,
    "displaynameshort": "Mk.3 HEDP",
    "ammo": "rhs_ammo_smaw_HEDP",
    "type": "2*256",
    "mass": 129.8,
    "value": 5,
    "allowedSlots": [901],
    "count": 1,
    "nameSound": "handgrenade",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}