rhs_mag_maaws_HEAT = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "displayName": "FFV751 HEAT",
    "model": "rhsusf\addons\rhsusf_weapons2\m3maaws\mag_m3maaws.p3d",
    "picture": "\rhsusf\addons\rhsusf_weapons2\m3maaws\UI\gear_small_CA.paa",
    "initSpeed": 290,
    "descriptionShort": "High Explosive Anti tank",
    "displaynameshort": "751 HEAT",
    "ammo": "rhs_ammo_maaws_HEAT",
    "type": "2*        256",
    "mass": 88.2,
    "value": 5,
    "allowedSlots": [901],
    "count": 1,
    "nameSound": "handgrenade",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "maxLeadSpeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}