rhs_fim92_mag = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "mass": 120,
    "displayName": "FIM-92F",
    "descriptionshort": "Type: Surface-to-air<br />Caliber: 70 mm<br />Used in: FIM-92",
    # Ammo: rhs_ammo_fim92_missile,
    "ammo": {
        "ammo": "rhs_ammo_fim92_missile",
        "model": "rhsusf|addons|rhsusf_weapons|FIM92|Stinger_Rocket",
        "hit": 60,
        "indirectHit": 55,
        "indirectHitRange": 8,
        "proximityExplosionDistance": 10,
        "maneuvrability": 34,
        "simulationStep": 0.001,
        "trackOversteer": 0.95,
        "trackLead": 0.6,
        "airLock": 2,
        "irLock": 1,
        "cost": 1000,
        "timeToLive": 15,
        "sideairfriction": 0.08,
        "maxSpeed": 750,
        "initTime": 0.25,
        "thrustTime": 4.9,
        "thrust": 325,
        "fuseDistance": 50,
        "explosive": 1,
        "audibleFire": 32,
        "whistleDist": 16,
        "cmImmunity": 0.95,
        "maxcontrolrange": 7000,
        "CraterEffects": "AAMissileCrater",
        "effectsMissile": "RHS_FIM92_Fired",
        "effectsMissileInit": "RocketBackEffectsRPG",
        "submunitionConeType": ["randomcenter",30],
        "submunitionConeAngle": 65,
        "submunitionAmmo": "rhs_ammo_he_fragments",
        "submunitionDirectionType": "SubmunitionTargetDirection",
        "submunitionInitialOffset": [0,0,0],
        "submunitionParentSpeedCoef": 0,
        "submunitionInitSpeed": 1500,
        "triggerOnImpact": 1,
        "deleteParentWhenTriggered": 0,
        "missileLockMaxDistance": 6500,
        "missileLockMinDistance": 300,
        "missileLockMaxSpeed": 333,
        "missileLockCone": 12,
        "missileKeepLockedCone": 70,
        "weaponLockSystem": "2 + 16",
        # Class: CfgAmmo\rhs_ammo_fim92_missile\Components,
        "Components": {
            # Class: CfgAmmo\rhs_ammo_fim92_missile\Components\SensorsManagerComponent
            "SensorsManagerComponent": {
                # Class: CfgAmmo\rhs_ammo_fim92_missile\Components\SensorsManagerComponent\Components
                "Components": {
                    # Class: CfgAmmo\rhs_ammo_fim92_missile\Components\SensorsManagerComponent\Components\IRSensorComponent
                    "IRSensorComponent": {
                        # Class: CfgAmmo\rhs_ammo_fim92_missile\Components\SensorsManagerComponent\Components\IRSensorComponent\AirTarget
                        "AirTarget": {
                            "minRange": 500,
                            "maxRange": 6500,
                            "objectDistanceLimitCoef": -1,
                            "viewDistanceLimitCoef": 1
                        },
                        # Class: CfgAmmo\rhs_ammo_fim92_missile\Components\SensorsManagerComponent\Components\IRSensorComponent\GroundTarget,
                        "GroundTarget": {
                            "minRange": 500,
                            "maxRange": 1000,
                            "objectDistanceLimitCoef": 1,
                            "viewDistanceLimitCoef": 1
                        },
                        "typeRecognitionDistance": -1,
                        "angleRangeHorizontal": 35,
                        "angleRangeVertical": 35,
                        "groundNoiseDistanceCoef": 0.02,
                        "maxGroundNoiseDistance": 40,
                        "minSpeedThreshold": 0,
                        "maxSpeedThreshold": -1,
                        "maxFogSeeThrough": 0.8,
                        "minTrackableSpeed": 0,
                        "maxTrackableSpeed": 330,
                        "minTrackableATL": 20,
                        "maxTrackableATL": 4000,
                        "componentType": "IRSensorComponent",
                        "color": [1,0,0,1],
                        "allowsMarking": 1,
                        "animDirection": "",
                        "aimDown": 0
                    }
                }
            }
        },
        "warheadName": "HE",
        "aiAmmoUsageFlags": 256,
        "airFriction": 0.145,
        "explosionEffects": "AAMissileExplosion",
        "soundHit1": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_01",2.51189,1,1900],
        "soundHit2": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_02",2.51189,1,1900],
        "soundHit3": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_03",2.51189,1,1900],
        "multiSoundHit": ["soundHit1",0.34,"soundHit2",0.33,"soundHit3",0.33],
        # Class: CfgAmmo\M_Titan_AA\CamShakeExplode,
        "CamShakeExplode": {
            "power": 22,
            "duration": 2,
            "frequency": 20,
            "distance": 147.905
        },
        # Class: CfgAmmo\M_Titan_AA\CamShakeHit,
        "CamShakeHit": {
            "power": 110,
            "duration": 0.6,
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo\M_Titan_AA\CamShakeFire,
        "CamShakeFire": {
            "power": 2.78316,
            "duration": 1.6,
            "frequency": 20,
            "distance": 61.9677
        },
        # Class: CfgAmmo\M_Titan_AA\CamShakePlayerFire,
        "CamShakePlayerFire": {
            "power": 3,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "SoundSetExplosion": ["RocketsHeavy_Exp_SoundSet","RocketsHeavy_Tail_SoundSet","Explosion_Debris_SoundSet"],
        "manualControl": 0,
        "explosionSoundEffect": "DefaultExplosion",
        "soundFly": ["",1,1,400],
        "soundEngine": ["",1,1,50],
        "supersonicCrackNear": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_close",0.398107,1,20],
        "supersonicCrackFar": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_50meters",0.316228,1,50],
        "muzzleEffect": "BIS_fnc_effectFiredRocket",
        "deflecting": 0,
        "dangerRadiusHit": -1,
        "suppressionRadiusHit": 30,
        # Class: CfgAmmo\MissileBase\HitEffects,
        "HitEffects": {
            "hitWater": "ImpactEffectsWaterRocket"
        },
        "maverickWeaponIndexOffset": 0,
        "htMin": 60,
        "htMax": 1800,
        "afMax": 200,
        "mfMax": 100,
        "mFact": 0,
        "tBody": 0,
        # Class: CfgAmmo\MissileBase\EventHandlers,
        "EventHandlers": {
            # Class: CfgAmmo\MissileBase\EventHandlers\RHS_APS_FiredEH
            "RHS_APS_FiredEH": {
                "fired": "_this spawn rhs_fnc_aps_missileFired"
            }
        },
        "simulation": "shotMissile",
        "visibleFire": 32,
        "visibleFireTime": 20,
        "soundHit": ["",100,1],
        "access": 3,
        "underwaterHitRangeCoef": 1,
        "typicalSpeed": 900,
        "explosionForceCoef": 1,
        "isCraterOriented": 0,
        "proxyShape": "",
        "craterShape": "",
        "weaponType": "Default",
        "animated": 0,
        "shadow": 0,
        "cartridge": "",
        "tracerColor": [0.7,0.7,0.5,0.04],
        "tracerColorR": [0.7,0.7,0.5,0.04],
        "soundFall": ["",1,1],
        "soundFakeFall": ["soundFall",1],
        "hitGroundSoft": ["soundHit",1],
        "hitGroundHard": ["soundHit",1],
        "hitMan": ["soundHit",1],
        "hitArmor": ["soundHit",1],
        "hitIron": ["soundHit",1],
        "hitBuilding": ["soundHit",1],
        "hitFoliage": ["soundHit",1],
        "hitWood": ["soundHit",1],
        "hitGlass": ["soundHit",1],
        "hitGlassArmored": ["soundHit",1],
        "hitConcrete": ["soundHit",1],
        "hitRubber": ["soundHit",1],
        "hitPlastic": ["soundHit",1],
        "hitDefault": ["soundHit",1],
        "hitMetal": ["soundHit",1],
        "hitMetalplate": ["soundHit",1],
        "hitTyre": ["soundHit",1],
        "hitWater": ["soundHit",1],
        "soundImpact": ["",1,1],
        "impactGroundSoft": ["soundImpact",1],
        "impactGroundHard": ["soundImpact",1],
        "impactMan": ["soundImpact",1],
        "impactIron": ["soundImpact",1],
        "impactArmor": ["soundImpact",1],
        "impactBuilding": ["soundImpact",1],
        "impactFoliage": ["soundImpact",1],
        "impactWood": ["soundImpact",1],
        "impactGlass": ["soundImpact",1],
        "impactGlassArmored": ["soundImpact",1],
        "impactConcrete": ["soundImpact",1],
        "impactRubber": ["soundImpact",1],
        "impactPlastic": ["soundImpact",1],
        "impactDefault": ["soundImpact",1],
        "impactMetal": ["soundImpact",1],
        "impactMetalplate": ["soundImpact",1],
        "impactTyre": ["soundImpact",1],
        "impactWater": ["soundImpact",1],
        "grenadeFireSound": [],
        "grenadeBurningSound": [],
        "deflectionSlowDown": 0.8,
        "craterWaterEffects": "ImpactEffectsWater",
        "effectsSmoke": "SmokeShellWhite",
        "effectsFire": "CannonFire",
        "effectFlare": "FlareShell",
        "effectFly": "",
        "mineJumpEffects": "",
        "waterEffectOffset": 0.45,
        "directionalExplosion": 0,
        "explosionAngle": 60,
        "explosionDir": "explosionDir",
        "explosionPos": "explosionPos",
        "explosionEffectsDir": "explosionDir",
        "minimumSafeZone": 0.1,
        "soundTrigger": [],
        "soundActivation": [],
        "soundDeactivation": [],
        "minTimeToLive": 0,
        "laserLock": 0,
        "nvLock": 0,
        "artilleryLock": 0,
        "hitOnWater": 0,
        "lockSeekRadius": 100,
        "lockType": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "autoSeekTarget": 0,
        "shootDistraction": -1,
        "explosionTime": 0,
        "icon": "",
        "explosionType": "explosive",
        "mineTrigger": "RangeTrigger",
        "mineBoundingTime": 3,
        "mineBoundingDist": 3,
        "mineInconspicuousness": 10,
        "mineFloating": -1,
        "mineDiveSpeed": 1,
        "minePlaceDist": 0.5,
        "suppressionRadiusBulletClose": -1,
        "dangerRadiusBulletClose": -1,
        "caliber": 1,
        "whistleOnFire": 0,
        # Class: CfgAmmo\Default\NVGMarkers,
        "NVGMarkers": {
        },
        "minDamageForCamShakeHit": 0.55,
    },
    "type": "6 * 		256",
    "picture": "rhsusf|addons|rhsusf_weapons|icons|m_stinger_ca.paa",
    "model": "rhsusf|addons|rhsusf_weapons|FIM92|Stinger_proxy",
    "initSpeed": 20,
    "maxLeadSpeed": 220,
    "displayNameShort": "AA",
    "value": 5,
    "allowedSlots": [901],
    "count": 1,
    "nameSound": "handgrenade",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "reloadAction": "",
    "selectionFireAnim": "zasleh",
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines\Default\InventoryPlacements,
    "InventoryPlacements": {
    },
    # Class: CfgMagazines\Default\Library,
    "Library": {
        "libTextDesc": ""
    },
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0,
}