rhs_mag_maaws_he = {
    "author": "Red Hammer Studios",
    "scope": 2,
    "displayname": "FFV441 HE",
    "model": "rhsusf|addons|rhsusf_weapons2|m3maaws|mag_m3maaws.p3d",
    "picture": "rhsusf|addons|rhsusf_weapons2|m3maaws|UI|gear_small_CA.paa",
    "initspeed": 255,
    "descriptionshort": "High Explosive",
    "displaynameshort": "441 HE",
    # Ammo: CfgMagazines|rhs_mag_maaws_HE|ammo [Indent level: 1],
    "ammo": {
        "_dictAmmoName": "rhs_ammo_maaws_HE",
        "effectfly": "ArtilleryTrails",
        "soundhit1": ["A3|Sounds_F|arsenal|explosives|shells|Artillery_tank_shell_155mm_explosion_01",2.51189,1,1900],
        "soundhit2": ["A3|Sounds_F|arsenal|explosives|shells|Artillery_tank_shell_155mm_explosion_02",2.51189,1,1900],
        "soundhit3": ["A3|Sounds_F|arsenal|explosives|shells|Artillery_tank_shell_155mm_explosion_03",2.51189,1,1900],
        "soundhit4": ["A3|Sounds_F|arsenal|explosives|shells|Artillery_tank_shell_155mm_explosion_04",2.51189,1,1900],
        "multisoundhit": ["soundHit1",0.25,"soundHit2",0.25,"soundHit3",0.25,"soundHit4",0.25],
        "soundfly": ["A3|Sounds_F|arsenal|weapons_static|Missile_Launcher|rocket_fly",1.1,1.1,900],
        "model": "rhsusf|addons|rhsusf_weapons2|m3maaws|ammo_m3maaws.p3d",
        "hit": 75,
        "indirecthit": 65,
        "indirecthitrange": 11,
        "cost": 300,
        "airfriction": 0.01,
        "sideairfriction": 0,
        "maxspeed": 255,
        "inittime": 0,
        "thrusttime": 0.1,
        "thrust": 0.1,
        "fusedistance": 15,
        "cratereffects": "ArtyShellCrater",
        "explosioneffects": "MortarExplosion",
        "effectsmissileinit": "",
        "effectsmissile": "RHSUSF_SMAW_MissileTrail",
        "simulationstep": 0.02,
        "airlock": 0,
        "irlock": 0,
        "timetolive": 25,
        "maneuvrability": 0,
        "allowagainstinfantry": 1,
        # Class: CfgAmmo|rhs_ammo_maaws_HE|CamShakeExplode [Indent level: 1],
        "camshakeexplode": {
            "power": "(55*0.2)",
            "duration": "((round (55^0.5))*0.2 max 0.2)",
            "frequency": 20,
            "distance": "((5 + 55^0.5)*8)"
        },
        # Class: CfgAmmo|rhs_ammo_maaws_HE|CamShakeHit [Indent level: 1],
        "camshakehit": {
            "power": 110,
            "duration": "((round (110^0.25))*0.2 max 0.2)",
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo|rhs_ammo_maaws_HE|CamShakeFire [Indent level: 1],
        "camshakefire": {
            "power": 5,
            "duration": "((round (20^0.5))*0.2 max 0.2)",
            "frequency": 20,
            "distance": "((20^0.5)*8)"
        },
        # Class: CfgAmmo|rhs_ammo_maaws_HE|CamShakePlayerFire [Indent level: 1],
        "camshakeplayerfire": {
            "power": 2,
            "duration": 0.2,
            "frequency": 8,
            "distance": 1
        },
        "visiblefire": 15,
        "audiblefire": 20,
        "dangerradiushit": -1,
        "suppressionradiushit": 30,
        "soundhit": ["A3|Sounds_F|weapons|Rockets|explosion_missile_02",2.51189,1,2500],
        "explosionsoundeffect": "DefaultExplosion",
        "soundengine": ["",1,1,20],
        "supersoniccracknear": ["",1,1,50],
        "supersoniccrackfar": ["",1,1,150],
        "muzzleeffect": "BIS_fnc_effectFiredRocket",
        # Class: CfgAmmo|RocketBase|HitEffects [Indent level: 1],
        "hiteffects": {
            "hitwater": "ImpactEffectsWaterRocket"
        },
        # Class: CfgAmmo|RocketBase|EventHandlers [Indent level: 1],
        "eventhandlers": {
            # Class: CfgAmmo|RocketBase|EventHandlers|RHS_APS_FiredEH [Indent level: 2]
            "rhs_aps_firedeh": {
                "fired": "_this spawn rhs_fnc_aps_missileFired"
            }
        },
        "simulation": "shotRocket",
        "maxcontrolrange": 0,
        "visiblefiretime": 20,
        "deflecting": 5,
        "access": 3,
        "underwaterhitrangecoef": 1,
        "typicalspeed": 900,
        "explosionforcecoef": 1,
        "iscrateroriented": 0,
        "proxyshape": "",
        "cratershape": "",
        "weapontype": "Default",
        "animated": 0,
        "shadow": 0,
        "cartridge": "",
        "tracercolor": [0.7,0.7,0.5,0.04],
        "tracercolorr": [0.7,0.7,0.5,0.04],
        "soundfall": ["",1,1],
        "soundfakefall": ["soundFall",1],
        "hitgroundsoft": ["soundHit",1],
        "hitgroundhard": ["soundHit",1],
        "hitman": ["soundHit",1],
        "hitarmor": ["soundHit",1],
        "hitiron": ["soundHit",1],
        "hitbuilding": ["soundHit",1],
        "hitfoliage": ["soundHit",1],
        "hitwood": ["soundHit",1],
        "hitglass": ["soundHit",1],
        "hitglassarmored": ["soundHit",1],
        "hitconcrete": ["soundHit",1],
        "hitrubber": ["soundHit",1],
        "hitplastic": ["soundHit",1],
        "hitdefault": ["soundHit",1],
        "hitmetal": ["soundHit",1],
        "hitmetalplate": ["soundHit",1],
        "hittyre": ["soundHit",1],
        "hitwater": ["soundHit",1],
        "soundimpact": ["",1,1],
        "impactgroundsoft": ["soundImpact",1],
        "impactgroundhard": ["soundImpact",1],
        "impactman": ["soundImpact",1],
        "impactiron": ["soundImpact",1],
        "impactarmor": ["soundImpact",1],
        "impactbuilding": ["soundImpact",1],
        "impactfoliage": ["soundImpact",1],
        "impactwood": ["soundImpact",1],
        "impactglass": ["soundImpact",1],
        "impactglassarmored": ["soundImpact",1],
        "impactconcrete": ["soundImpact",1],
        "impactrubber": ["soundImpact",1],
        "impactplastic": ["soundImpact",1],
        "impactdefault": ["soundImpact",1],
        "impactmetal": ["soundImpact",1],
        "impactmetalplate": ["soundImpact",1],
        "impacttyre": ["soundImpact",1],
        "impactwater": ["soundImpact",1],
        "grenadefiresound": [],
        "grenadeburningsound": [],
        "deflectionslowdown": 0.8,
        "explosive": 1,
        "craterwatereffects": "ImpactEffectsWater",
        "effectssmoke": "SmokeShellWhite",
        "effectsfire": "CannonFire",
        "effectflare": "FlareShell",
        "minejumpeffects": "",
        "watereffectoffset": 0.45,
        "directionalexplosion": 0,
        "explosionangle": 60,
        "explosiondir": "explosionDir",
        "explosionpos": "explosionPos",
        "explosioneffectsdir": "explosionDir",
        "minimumsafezone": 0.1,
        "soundtrigger": [],
        "soundactivation": [],
        "sounddeactivation": [],
        "mintimetolive": 0,
        "laserlock": 0,
        "nvlock": 0,
        "artillerylock": 0,
        "hitonwater": 0,
        "lockseekradius": 100,
        "manualcontrol": 0,
        "tracklead": 1,
        "trackoversteer": 1,
        "missilelockcone": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "locktype": 0,
        "maverickweaponindexoffset": 0,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "autoseektarget": 0,
        "shootdistraction": -1,
        "explosiontime": 0,
        "icon": "",
        "submunitionammo": "",
        "explosiontype": "explosive",
        "minetrigger": "RangeTrigger",
        "mineboundingtime": 3,
        "mineboundingdist": 3,
        "mineinconspicuousness": 10,
        "minefloating": -1,
        "minedivespeed": 1,
        "mineplacedist": 0.5,
        "suppressionradiusbulletclose": -1,
        "dangerradiusbulletclose": -1,
        "caliber": 1,
        "whistledist": 0,
        "whistleonfire": 0,
        # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
        "nvgmarkers": {
        },
        "mindamageforcamshakehit": 0.55,
    },
    "mindamageforcamshakehit": "rhs_ammo_maaws_HE",
    "type": "2*        256",
    "mass": "68,36",
    "value": 5,
    "allowedslots": [901],
    "count": 1,
    "namesound": "handgrenade",
    "modelspecial": "",
    "useaction": 0,
    "useactiontitle": "",
    "reloadaction": "",
    "selectionfireanim": "zasleh",
    "maxleadspeed": 25,
    "weaponpoolavailable": 1,
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    # Class: CfgMagazines|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0,
}