"g_bandanna_blk": {
    "author": "Bohemia Interactive",
    "_generalmacro": "G_Bandanna_blk",
    "displayname": "Bandana (Black)",
    "model": "A3\\Characters_F_Bootcamp\\Guerrilla\\g_bandana_clean.p3d",
    "picture": "A3\\Characters_F_Bootcamp\\Data\\UI\\icon_G_Bandana_clean_ca.paa",
    "hiddenselectionstextures": ["\\a3\\characters_f_bootcamp\\guerrilla\\data\\headgear_bandmask_blk_co.paa"],
    "mass": 4,
    "identitytypes": [],
    "scope": 2,
    "scopecurator": 2,
    "scopearsenal": 2,
    "hiddenselections": ["camo"],
    "name": "None",
},
"rhs_balaclava1_olive": {
    "dlc": "RHS_AFRF",
    "author": "Red Hammer Studios",
    "displayname": "Balaclava (Olive)",
    "model": "rhsafrf\\addons\\rhs_infantry2\\gear\\head\\rhs_bala1",
    "picture": "rhsafrf\\addons\\rhs_infantry\\Data\\inventory\\gear_icon_balaclava_ca.paa",
    "hiddenselections": ["Camo1"],
    "hiddenselectionstextures": ["\\rhsafrf\\addons\\rhs_infantry2\\gear\\head\\data\\rhs_bala1_olive_co.paa"],
    "_generalmacro": "G_Balaclava_blk",
    "scope": 2,
    "scopecurator": 2,
    "scopearsenal": 2,
    "identitytypes": ["NoGlasses",0,"G_RUS_SF",25],
    "mass": 6,
    "name": "None"
}