"rhsgref_ttsko_alicepack": {
    "author": "Red Hammer Studios",
    "picture": "rhsgref\\addons\\rhsgref_inventoryicons\\data\\Backpacks\\rhsgref_ttsko_alicepack_ca.paa",
    "displayname": "ALICE Pack (TTsKO)",
    "hiddenselectionstextures": ["\\rhsgref\\addons\\rhsgref_infantry\\data_cdf\\alicepack_co_gref_ttsko.paa"],
    "hiddenSelections": ["Camo"],
    "model": "rhsgref\\addons\\rhsgref_infantry\\gear_tanoa\\backpack\\alicepack",
    "scope": 2,
    "scopeCurator": 0,
    "maximumLoad": 320,
    "mass": 60,
    "mapSize": 0.5,
    "_generalMacro": "Bag_Base",
    # Class: CfgVehicles\\Bag_Base\\TransportMagazines [Indent level: 1],
    "TransportMagazines": {
    },
    # Class: CfgVehicles\\Bag_Base\\TransportWeapons [Indent level: 1],
    "TransportWeapons": {
    },
    "isbackpack": 1,
    "reversed": 1,
    "editorCategory": "EdCat_Equipment",
    "editorSubcategory": "EdSubcat_Backpacks",
    "vehicleClass": "Backpacks",
    "allowedSlots": [901],
    "icon": "iconBackpack",
    "transportMaxWeapons": 1,
    "transportMaxMagazines": 20,
    # Class: CfgVehicles\\Bag_Base\\DestructionEffects [Indent level: 1],
    "DestructionEffects": {
    },
    "side": 3,
    "waterLeakiness": 100,
    "animated": 0,
    "accuracy": 0.2,
    "typicalCargo": [],
    "destrType": "DestructBuilding",
    "transportMaxBackpacks": 1,
    "transportAmmo": 0,
    "transportRepair": 0,
    "transportFuel": 0,
    "supplyRadius": 1.4,
    "cost": 0,
    "armor": 200,
    "ladders": [],
    "nameSound": "obj_building",
    "hasDriver": 0,
    "audible": 0,
    "simulation": "house",
    "weapons": [],
    "magazines": [],
    "irTarget": 0,
    "type": 1,
    "threat": [0,0,0],
    "maxSpeed": 0,
    "coefInside": 2,
    "coefInsideHeur": 2,
    "coefSpeedInside": 2,
    "windSockExist": 0,
    "countsForScoreboard": 0,
    "access": 0,
    "autocenter": 1,
    "shadow": 1,
    "featureType": 0,
    "faction": "Default",
    "speechSingular": [],
    "speechPlural": [],
    "maxDetectRange": 20,
    "detectSkill": 20,
    "mineAlertIconRange": 200,
    "killFriendlyExpCoef": 1,
    "weaponSlots": 0,
    "camouflage": 2,
    "spotableDarkNightLightsOff": 0.001,
    "spotableNightLightsOff": 0.02,
    "spotableNightLightsOn": 4,
    "accuracyDarkNightLightsOff": 0.001,
    "accuracyNightLightsOff": 0.006,
    "accuracyNightLightsOn": 0.1,
    "attenuationEffectType": "",
    "insideSoundCoef": 0.5,
    "outsideSoundFilter": 0,
    "occludeSoundsWhenIn": 0.316228,
    "obstructSoundsWhenIn": 0.562341,
    "obstructSoundLFRatio": 0,
    "occludeSoundLFRatio": 0.25,
    "unloadInCombat": 0,
    "antiRollbarForceCoef": 0,
    "antiRollbarForceLimit": 5,
    "antiRollbarSpeedMin": 20,
    "antiRollbarSpeedMax": 60,
    "slowSpeedForwardCoef": 0.3,
    "normalSpeedForwardCoef": 0.85,
    "epeImpulseDamageCoef": 30,
    "gunnerHasFlares": 1,
    "enableManualFire": 1,
    "sensitivity": 2.5,
    "sensitivityEar": 0.0075,
    "portrait": "",
    "ghostPreview": "",
    "armorLights": 0.4,
    "armorStructural": 1,
    "crewVulnerable": 1,
    "damageResistance": 0.004,
    "crewCrashProtection": 1,
    "replaceDamaged": "",
    "replaceDamagedLimit": 0.9,
    "replaceDamagedHitpoints": [],
    "keepInEPESceneAfterDeath": 0,
    "fuelCapacity": 0,
    "fuelConsumptionRate": 0.01,
    "extCameraPosition": [0,2,-20],
    "groupCameraPosition": [0,5,-30],
    "extCameraParams": [1],
    "steerAheadSimul": 0.3,
    "steerAheadPlan": 0.4,
    "cameraSmoothSpeed": 5,
    "minFireTime": 20,
    "predictTurnSimul": 1.2,
    "predictTurnPlan": 1,
    "indirectHitEnemyCoefAI": 10,
    "indirectHitFriendlyCoefAI": -20,
    "indirectHitCivilianCoefAI": -20,
    "indirectHitUnknownCoefAI": -0.5,
    "precision": 5,
    "brakeDistance": 5,
    "formationX": 10,
    "formationZ": 20,
    "formationTime": 5,
    "alwaysTarget": 0,
    "irScanRangeMin": 0,
    "irScanRangeMax": 0,
    "irScanToEyeFactor": 1,
    "irScanGround": 1,
    "laserTarget": 0,
    "laserScanner": 0,
    "nvTarget": 0,
    "nvScanner": 0,
    "artilleryTarget": 0,
    "artilleryScanner": 0,
    "canUseScanners": 1,
    "preferRoads": 0,
    "unitInfoType": "RscUnitInfoTank",
    "unitInfoTypeLite": 0,
    "hideUnitInfo": 0,
    "nightVision": 0,
    "commanderCanSee": 31,
    "gunnerCanSee": "4+8+16",
    "driverCanSee": "2+8+16",
    "showCrewAim": 7,
    "radarType": 0,
    "limitedSpeedCoef": 0.22,
    "secondaryExplosion": -1,
    "driverForceOptics": 0,
    "hideWeaponsDriver": 1,
    "hideWeaponsCargo": 0,
    "getInRadius": 2.5,
    "selectionClan": "",
    "selectionDashboard": "",
    "selectionShowDamage": "",
    "selectionBackLights": "",
    "memoryPointSupply": "doplnovani",
    "enableGPS": 0,
    "enableWatch": 0,
    "enableRadio": 0,
    "lockDetectionSystem": 0,
    "incomingMissileDetectionSystem": 0,
    "headGforceLeaningFactor": [0.01,0.002,0.01],
    "usePreciseGetInAction": 0,
    "allowTabLock": 1,
    "showAllTargets": 0,
    "dustFrontLeftPos": "dustFrontLeft",
    "dustFrontRightPos": "dustFrontRight",
    "dustBackLeftPos": "dustBackLeft",
    "dustBackRightPos": "dustBackRight",
    "wheelCircumference": 1,
    "waterResistanceCoef": 0.5,
    "waterLinearDampingCoefX": 0,
    "waterLinearDampingCoefY": 0,
    "waterAngularDampingCoef": 0,
    "showNVGDriver": 0,
    "showNVGCommander": 0,
    "showNVGGunner": 0,
    "showNVGCargo": [0],
    "soundAttenuationCargo": [1],
    "hullDamageCauseExplosion": 0,
    # Class: CfgVehicles\\All\\EventHandlers [Indent level: 1],
    "EventHandlers": {
    },
    # Class: CfgVehicles\\All\\MarkerLights [Indent level: 1],
    "MarkerLights": {
    },
    # Class: CfgVehicles\\All\\NVGMarkers [Indent level: 1],
    "NVGMarkers": {
    },
    # Class: CfgVehicles\\All\\NVGMarker [Indent level: 1],
    "NVGMarker": {
        "diffuse": [1,1,1,1],
        "ambient": [1,1,1,1],
        "brightness": 1,
        "blinking": 0,
        "onlyInNvg": 0
    },
    # Class: CfgVehicles\\All\\Turrets [Indent level: 1],
    "Turrets": {
    },
    # Class: CfgVehicles\\All\\HeadLimits [Indent level: 1],
    "HeadLimits": {
        "initAngleX": 5,
        "minAngleX": -30,
        "maxAngleX": 40,
        "initAngleY": 0,
        "minAngleY": -90,
        "maxAngleY": 90,
        "minAngleZ": -45,
        "maxAngleZ": 45,
        "rotZRadius": 0.2
    },
    # Class: CfgVehicles\\All\\ViewPilot [Indent level: 1],
    "ViewPilot": {
        "initAngleX": 5,
        "minAngleX": -55,
        "maxAngleX": 85,
        "initAngleY": 0,
        "minAngleY": -150,
        "maxAngleY": 150,
        "minFov": 0.25,
        "maxFov": 1.25,
        "initFov": 0.75,
        "minMoveX": 0,
        "maxMoveX": 0,
        "minMoveY": 0,
        "maxMoveY": 0,
        "minMoveZ": 0,
        "maxMoveZ": 0,
        "speedZoomMaxSpeed": 1e+010,
        "speedZoomMaxFOV": 0
    },
    # Class: CfgVehicles\\All\\ViewCargo [Indent level: 1],
    "ViewCargo": {
        "initAngleX": 5,
        "minAngleX": -85,
        "maxAngleX": 85,
        "initAngleY": 0,
        "minAngleY": -150,
        "maxAngleY": 150,
        "minFov": 0.25,
        "maxFov": 1.25,
        "initFov": 0.75,
        "minMoveX": 0,
        "maxMoveX": 0,
        "minMoveY": 0,
        "maxMoveY": 0,
        "minMoveZ": 0,
        "maxMoveZ": 0,
        "speedZoomMaxSpeed": 1e+010,
        "speedZoomMaxFOV": 0
    },
    # Class: CfgVehicles\\All\\ViewOptics [Indent level: 1],
    "ViewOptics": {
        "initAngleX": 0,
        "minAngleX": -30,
        "maxAngleX": 30,
        "initAngleY": 0,
        "minAngleY": -100,
        "maxAngleY": 100,
        "initFov": 0.7,
        "minFov": 0.42,
        "maxFov": 0.85,
        "minMoveX": 0,
        "maxMoveX": 0,
        "minMoveY": 0,
        "maxMoveY": 0,
        "minMoveZ": 0,
        "maxMoveZ": 0,
        "speedZoomMaxSpeed": 1e+010,
        "speedZoomMaxFOV": 0
    },
    # Class: CfgVehicles\\All\\PilotSpec [Indent level: 1],
    "PilotSpec": {
        "showHeadPhones": 0
    },
    # Class: CfgVehicles\\All\\CargoSpec [Indent level: 1],
    "CargoSpec": {
        # Class: CfgVehicles\\All\\CargoSpec\\Cargo1 [Indent level: 2]
        "Cargo1": {
            "showHeadPhones": 0
        }
    },
    "transportSoldier": 0,
    "transportVehiclesCount": 0,
    "transportVehiclesMass": 0,
    "attendant": 0,
    "engineer": 0,
    "uavHacker": 0,
    "soundEngine": ["",1,1],
    "soundEnviron": ["",1,1],
    # Class: CfgVehicles\\All\\SoundEnvironExt [Indent level: 1],
    "SoundEnvironExt": {
    },
    # Class: CfgVehicles\\All\\SoundEquipment [Indent level: 1],
    "SoundEquipment": {
    },
    # Class: CfgVehicles\\All\\SoundGear [Indent level: 1],
    "SoundGear": {
    },
    # Class: CfgVehicles\\All\\SoundBreath [Indent level: 1],
    "SoundBreath": {
    },
    # Class: CfgVehicles\\All\\SoundBreathSwimming [Indent level: 1],
    "SoundBreathSwimming": {
    },
    # Class: CfgVehicles\\All\\SoundBreathInjured [Indent level: 1],
    "SoundBreathInjured": {
    },
    # Class: CfgVehicles\\All\\SoundHitScream [Indent level: 1],
    "SoundHitScream": {
    },
    # Class: CfgVehicles\\All\\SoundInjured [Indent level: 1],
    "SoundInjured": {
    },
    # Class: CfgVehicles\\All\\SoundBreathAutomatic [Indent level: 1],
    "SoundBreathAutomatic": {
    },
    # Class: CfgVehicles\\All\\SoundDrown [Indent level: 1],
    "SoundDrown": {
    },
    # Class: CfgVehicles\\All\\SoundChoke [Indent level: 1],
    "SoundChoke": {
    },
    # Class: CfgVehicles\\All\\SoundRecovered [Indent level: 1],
    "SoundRecovered": {
    },
    # Class: CfgVehicles\\All\\SoundBurning [Indent level: 1],
    "SoundBurning": {
    },
    # Class: CfgVehicles\\All\\PulsationSound [Indent level: 1],
    "PulsationSound": {
    },
    # Class: CfgVehicles\\All\\SoundDrowning [Indent level: 1],
    "SoundDrowning": {
    },
    "soundCrash": ["",0.316228,1],
    "soundLandCrash": ["",1,1],
    "soundWaterCrash": ["",0.177828,1],
    "soundGetIn": ["",0.000316228,1],
    "soundGetOut": ["",0.000316228,1],
    "soundServo": ["",0.00316228,0.5],
    "soundElevation": ["",0.00316228,0.5],
    "sounddamage": ["",1,1],
    "soundEngineOnInt": ["",1,1],
    "soundEngineOffInt": ["",1,1],
    "soundEngineOnExt": ["",1,1],
    "soundEngineOffExt": ["",1,1],
    "soundGearUp": ["",1,1],
    "soundGearDown": ["",1,1],
    "soundFlapsUp": ["",1,1],
    "soundFlapsDown": ["",1,1],
    "cabinOpenSound": ["",1,1],
    "cabinCloseSound": ["",1,1],
    "cabinOpenSoundInternal": ["",1,1],
    "cabinCloseSoundInternal": ["",1,1],
    "soundCrashes": ["soundCrash",1],
    "soundLandCrashes": ["soundLandCrash",1],
    "soundWaterCrashes": ["soundWaterCrash",1],
    "emptySound": ["",0,1],
    "soundWoodCrash": ["emptySound",0],
    "soundBushCrash": ["emptySound",0],
    "soundBuildingCrash": ["emptySound",0],
    "soundArmorCrash": ["emptySound",0],
    "soundLocked": ["",1,1],
    "soundIncommingMissile": ["",1,1],
    "soundDammage": ["",1,1],
    # Class: CfgVehicles\\All\\Reflectors [Indent level: 1],
    "Reflectors": {
    },
    "aggregateReflectors": [],
    "getInAction": "",
    "getOutAction": "",
    "driverAction": "",
    "driverInAction": "",
    "cargoGetInAction": [],
    "cargoGetOutAction": [],
    "cargoAction": [],
    "cargoIsCoDriver": [0],
    "driverCompartments": "Compartment1",
    "cargoCompartments": ["Compartment1"],
    "driverOpticsModel": "",
    "driverOpticsEffect": [],
    "driverOpticsColor": [1,1,1,1],
    "hideProxyInCombat": 0,
    "forceHideDriver": 0,
    "canHideDriver": -1,
    "castDriverShadow": 0,
    "castCargoShadow": 0,
    "viewDriverShadow": 1,
    "viewDriverShadowDiff": 1,
    "viewDriverShadowAmb": 1,
    "viewCargoShadow": 1,
    "viewCargoShadowDiff": 1,
    "viewCargoShadowAmb": 1,
    "ejectDeadDriver": 0,
    "ejectDeadCargo": 0,
    "crew": "Civilian",
    "hiddenSelectionsMaterials": [],
    "hiddenUnderwaterSelections": [],
    "shownUnderWaterSelections": [],
    "hiddenUnderwaterSelectionsTextures": [],
    # Class: CfgVehicles\\All\\FxExplo [Indent level: 1],
    "FxExplo": {
        "access": 1
    },
    # Class: CfgVehicles\\All\\AnimationSources [Indent level: 1],
    "AnimationSources": {
    },
    "selectionFireAnim": "",
    # Class: CfgVehicles\\All\\GunFire [Indent level: 1],
    "GunFire": {
        "access": 0,
        "cloudletDuration": 0.2,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 0.2,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 0.5,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletFire",
        "cloudletColor": [1,1,1,0],
        "interval": 0.01,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 4500,
        "deltaT": -3000,
        # Class: WeaponFireGun\\Table [Indent level: 0],
        "Table": {
            # Class: WeaponFireGun\\Table\\T0 [Indent level: 1]
            "T0": {
                "maxT": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: WeaponFireGun\\Table\\T1 [Indent level: 1],
            "T1": {
                "maxT": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: WeaponFireGun\\Table\\T2 [Indent level: 1],
            "T2": {
                "maxT": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: WeaponFireGun\\Table\\T3 [Indent level: 1],
            "T3": {
                "maxT": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: WeaponFireGun\\Table\\T4 [Indent level: 1],
            "T4": {
                "maxT": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: WeaponFireGun\\Table\\T5 [Indent level: 1],
            "T5": {
                "maxT": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: WeaponFireGun\\Table\\T6 [Indent level: 1],
            "T6": {
                "maxT": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: WeaponFireGun\\Table\\T7 [Indent level: 1],
            "T7": {
                "maxT": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: WeaponFireGun\\Table\\T8 [Indent level: 1],
            "T8": {
                "maxT": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: WeaponFireGun\\Table\\T9 [Indent level: 1],
            "T9": {
                "maxT": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: WeaponFireGun\\Table\\T10 [Indent level: 1],
            "T10": {
                "maxT": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: WeaponFireGun\\Table\\T11 [Indent level: 1],
            "T11": {
                "maxT": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: WeaponFireGun\\Table\\T12 [Indent level: 1],
            "T12": {
                "maxT": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: WeaponFireGun\\Table\\T13 [Indent level: 1],
            "T13": {
                "maxT": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: WeaponFireGun\\Table\\T14 [Indent level: 1],
            "T14": {
                "maxT": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: WeaponFireGun\\Table\\T15 [Indent level: 1],
            "T15": {
                "maxT": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: WeaponFireGun\\Table\\T16 [Indent level: 1],
            "T16": {
                "maxT": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: WeaponFireGun\\Table\\T17 [Indent level: 1],
            "T17": {
                "maxT": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: WeaponFireGun\\Table\\T18 [Indent level: 1],
            "T18": {
                "maxT": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: WeaponFireGun\\Table\\T19 [Indent level: 1],
            "T19": {
                "maxT": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: WeaponFireGun\\Table\\T20 [Indent level: 1],
            "T20": {
                "maxT": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: WeaponFireGun\\Table\\T21 [Indent level: 1],
            "T21": {
                "maxT": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: WeaponFireGun\\Table\\T22 [Indent level: 1],
            "T22": {
                "maxT": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgVehicles\\All\\GunClouds [Indent level: 1],
    "GunClouds": {
        "access": 0,
        "cloudletDuration": 0.3,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 1,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 1,
        "cloudletAccY": 0.4,
        "cloudletMinYSpeed": 0.2,
        "cloudletMaxYSpeed": 0.8,
        "cloudletShape": "cloudletClouds",
        "cloudletColor": [1,1,1,0],
        "interval": 0.05,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 0,
        "deltaT": 0,
        # Class: WeaponCloudsGun\\Table [Indent level: 0],
        "Table": {
            # Class: WeaponCloudsGun\\Table\\T0 [Indent level: 1]
            "T0": {
                "maxT": 0,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgVehicles\\All\\MGunClouds [Indent level: 1],
    "MGunClouds": {
        "access": 0,
        "cloudletGrowUp": 0.05,
        "cloudletFadeIn": 0,
        "cloudletFadeOut": 0.1,
        "cloudletDuration": 0.05,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 0.3,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletClouds",
        "cloudletColor": [1,1,1,0],
        "timeToLive": 0,
        "interval": 0.02,
        "size": 0.3,
        "sourceSize": 0.02,
        "initT": 0,
        "deltaT": 0,
        # Class: WeaponCloudsMGun\\Table [Indent level: 0],
        "Table": {
            # Class: WeaponCloudsMGun\\Table\\T0 [Indent level: 1]
            "T0": {
                "maxT": 0,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgVehicles\\All\\Damage [Indent level: 1],
    "Damage": {
        "tex": [],
        "mat": []
    },
    "selectionDamage": "zbytek",
    "HeadAimDown": 0,
    "cargoCanEject": 1,
    "driverCanEject": 1,
    "fireResistance": 10,
    "airCapacity": 10,
    "waterResistance": 10,
    "waterDamageEngine": 0.2,
    "maxFordingDepth": 1,
    "impactEffectsSea": "ImpactEffectsSea",
    "damageTexDelay": 0,
    "slingLoadCargoMemoryPoints": [],
    "slingLoadCargoMemoryPointsDir": [],
    "numberPhysicalWheels": 0,
    "damageHalf": [],
    "damageFull": [],
    # Class: CfgVehicles\\All\\camShakeGForce [Indent level: 1],
    "camShakeGForce": {
        "power": 1,
        "frequency": 20,
        "distance": 0,
        "minSpeed": 1,
        "duration": 3
    },
    "minGForce": 0.2,
    "maxGForce": 2,
    "gForceShakeAttenuation": 0.5,
    # Class: CfgVehicles\\All\\camShakeDamage [Indent level: 1],
    "camShakeDamage": {
        "power": 0.5,
        "frequency": 60,
        "distance": -1,
        "minSpeed": 1,
        "attenuation": 0.5,
        "duration": 3
    },
    "weaponsGroup1": "1 + 2",
    "weaponsGroup2": 4,
    "weaponsGroup3": "8 + 16 + 32",
    "weaponsGroup4": "64 + 128",
    "soundTurnIn": ["",0.000316228,1],
    "soundTurnOut": ["",0.000316228,1],
    "soundTurnInInternal": ["",0.000316228,1],
    "soundTurnOutInternal": ["",0.000316228,1],
    "features": "",
    # Class: CfgVehicles\\All\\SpeechVariants [Indent level: 1],
    "SpeechVariants": {
        # Class: CfgVehicles\\All\\SpeechVariants\\Default [Indent level: 2]
        "Default": {
            "speechSingular": ["veh_unknown_s"],
            "speechPlural": ["veh_unknown_p"]
        }
    },
    "textSingular": "unknown",
    "textPlural": "unknown",
    "insideDetectCoef": 0.05
},
"rhs_assault_umbts": {
    "dlc": "RHS_AFRF",
    "scope": 2,
    "author": "Red Hammer Studios",
    "model": "rhsafrf\\addons\\rhs_infantry\\gear\\backpacks\\rhs_assault_umtbs",
    "picture": "rhsafrf\\addons\\rhs_inventoryicons\\data\\backpacks\\rhs_assault_umbts_ca.paa",
    "displayName": "UMBTS Backpack",
    "hiddenSelectionsTextures": ["rhsafrf\\addons\\rhs_infantry\\data\\gearpack3_ranets_co.paa"],
    "maximumLoad": 240,
    "mass": 35,
    "mapSize": 0.45,
    "_generalMacro": "B_AssaultPack_Base",
    # Class: CfgVehicles\\Bag_Base\\TransportMagazines [Indent level: 1],
    "TransportMagazines": {
    },
    # Class: CfgVehicles\\Bag_Base\\TransportWeapons [Indent level: 1],
    "TransportWeapons": {
    },
    "isbackpack": 1,
    "reversed": 1,
    "editorCategory": "EdCat_Equipment",
    "editorSubcategory": "EdSubcat_Backpacks",
    "vehicleClass": "Backpacks",
    "allowedSlots": [901],
    "icon": "iconBackpack",
    "transportMaxWeapons": 1,
    "transportMaxMagazines": 20,
    # Class: CfgVehicles\\Bag_Base\\DestructionEffects [Indent level: 1],
    "DestructionEffects": {
    },
    "hiddenSelections": ["Camo"],
    "side": 3,
    "waterLeakiness": 100,
    "animated": 0,
    "accuracy": 0.2,
    "typicalCargo": [],
    "destrType": "DestructBuilding",
    "transportMaxBackpacks": 1,
    "transportAmmo": 0,
    "transportRepair": 0,
    "transportFuel": 0,
    "supplyRadius": 1.4,
    "cost": 0,
    "armor": 200,
    "ladders": [],
    "nameSound": "obj_building",
    "scopeCurator": 0,
    "hasDriver": 0,
    "audible": 0,
    "simulation": "house",
    "weapons": [],
    "magazines": [],
    "irTarget": 0,
    "type": 1,
    "threat": [0,0,0],
    "maxSpeed": 0,
    "coefInside": 2,
    "coefInsideHeur": 2,
    "coefSpeedInside": 2,
    "windSockExist": 0,
    "countsForScoreboard": 0,
    "access": 0,
    "autocenter": 1,
    "shadow": 1,
    "featureType": 0,
    "faction": "Default",
    "speechSingular": [],
    "speechPlural": [],
    "maxDetectRange": 20,
    "detectSkill": 20,
    "mineAlertIconRange": 200,
    "killFriendlyExpCoef": 1,
    "weaponSlots": 0,
    "camouflage": 2,
    "spotableDarkNightLightsOff": 0.001,
    "spotableNightLightsOff": 0.02,
    "spotableNightLightsOn": 4,
    "accuracyDarkNightLightsOff": 0.001,
    "accuracyNightLightsOff": 0.006,
    "accuracyNightLightsOn": 0.1,
    "attenuationEffectType": "",
    "insideSoundCoef": 0.5,
    "outsideSoundFilter": 0,
    "occludeSoundsWhenIn": 0.316228,
    "obstructSoundsWhenIn": 0.562341,
    "obstructSoundLFRatio": 0,
    "occludeSoundLFRatio": 0.25,
    "unloadInCombat": 0,
    "antiRollbarForceCoef": 0,
    "antiRollbarForceLimit": 5,
    "antiRollbarSpeedMin": 20,
    "antiRollbarSpeedMax": 60,
    "slowSpeedForwardCoef": 0.3,
    "normalSpeedForwardCoef": 0.85,
    "epeImpulseDamageCoef": 30,
    "gunnerHasFlares": 1,
    "enableManualFire": 1,
    "sensitivity": 2.5,
    "sensitivityEar": 0.0075,
    "portrait": "",
    "ghostPreview": "",
    "armorLights": 0.4,
    "armorStructural": 1,
    "crewVulnerable": 1,
    "damageResistance": 0.004,
    "crewCrashProtection": 1,
    "replaceDamaged": "",
    "replaceDamagedLimit": 0.9,
    "replaceDamagedHitpoints": [],
    "keepInEPESceneAfterDeath": 0,
    "fuelCapacity": 0,
    "fuelConsumptionRate": 0.01,
    "extCameraPosition": [0,2,-20],
    "groupCameraPosition": [0,5,-30],
    "extCameraParams": [1],
    "steerAheadSimul": 0.3,
    "steerAheadPlan": 0.4,
    "cameraSmoothSpeed": 5,
    "minFireTime": 20,
    "predictTurnSimul": 1.2,
    "predictTurnPlan": 1,
    "indirectHitEnemyCoefAI": 10,
    "indirectHitFriendlyCoefAI": -20,
    "indirectHitCivilianCoefAI": -20,
    "indirectHitUnknownCoefAI": -0.5,
    "precision": 5,
    "brakeDistance": 5,
    "formationX": 10,
    "formationZ": 20,
    "formationTime": 5,
    "alwaysTarget": 0,
    "irScanRangeMin": 0,
    "irScanRangeMax": 0,
    "irScanToEyeFactor": 1,
    "irScanGround": 1,
    "laserTarget": 0,
    "laserScanner": 0,
    "nvTarget": 0,
    "nvScanner": 0,
    "artilleryTarget": 0,
    "artilleryScanner": 0,
    "canUseScanners": 1,
    "preferRoads": 0,
    "unitInfoType": "RscUnitInfoTank",
    "unitInfoTypeLite": 0,
    "hideUnitInfo": 0,
    "nightVision": 0,
    "commanderCanSee": 31,
    "gunnerCanSee": "4+8+16",
    "driverCanSee": "2+8+16",
    "showCrewAim": 7,
    "radarType": 0,
    "limitedSpeedCoef": 0.22,
    "secondaryExplosion": -1,
    "driverForceOptics": 0,
    "hideWeaponsDriver": 1,
    "hideWeaponsCargo": 0,
    "getInRadius": 2.5,
    "selectionClan": "",
    "selectionDashboard": "",
    "selectionShowDamage": "",
    "selectionBackLights": "",
    "memoryPointSupply": "doplnovani",
    "enableGPS": 0,
    "enableWatch": 0,
    "enableRadio": 0,
    "lockDetectionSystem": 0,
    "incomingMissileDetectionSystem": 0,
    "headGforceLeaningFactor": [0.01,0.002,0.01],
    "usePreciseGetInAction": 0,
    "allowTabLock": 1,
    "showAllTargets": 0,
    "dustFrontLeftPos": "dustFrontLeft",
    "dustFrontRightPos": "dustFrontRight",
    "dustBackLeftPos": "dustBackLeft",
    "dustBackRightPos": "dustBackRight",
    "wheelCircumference": 1,
    "waterResistanceCoef": 0.5,
    "waterLinearDampingCoefX": 0,
    "waterLinearDampingCoefY": 0,
    "waterAngularDampingCoef": 0,
    "showNVGDriver": 0,
    "showNVGCommander": 0,
    "showNVGGunner": 0,
    "showNVGCargo": [0],
    "soundAttenuationCargo": [1],
    "hullDamageCauseExplosion": 0,
    # Class: CfgVehicles\\All\\EventHandlers [Indent level: 1],
    "EventHandlers": {
    },
    # Class: CfgVehicles\\All\\MarkerLights [Indent level: 1],
    "MarkerLights": {
    },
    # Class: CfgVehicles\\All\\NVGMarkers [Indent level: 1],
    "NVGMarkers": {
    },
    # Class: CfgVehicles\\All\\NVGMarker [Indent level: 1],
    "NVGMarker": {
        "diffuse": [1,1,1,1],
        "ambient": [1,1,1,1],
        "brightness": 1,
        "blinking": 0,
        "onlyInNvg": 0
    },
    # Class: CfgVehicles\\All\\Turrets [Indent level: 1],
    "Turrets": {
    },
    # Class: CfgVehicles\\All\\HeadLimits [Indent level: 1],
    "HeadLimits": {
        "initAngleX": 5,
        "minAngleX": -30,
        "maxAngleX": 40,
        "initAngleY": 0,
        "minAngleY": -90,
        "maxAngleY": 90,
        "minAngleZ": -45,
        "maxAngleZ": 45,
        "rotZRadius": 0.2
    },
    # Class: CfgVehicles\\All\\ViewPilot [Indent level: 1],
    "ViewPilot": {
        "initAngleX": 5,
        "minAngleX": -55,
        "maxAngleX": 85,
        "initAngleY": 0,
        "minAngleY": -150,
        "maxAngleY": 150,
        "minFov": 0.25,
        "maxFov": 1.25,
        "initFov": 0.75,
        "minMoveX": 0,
        "maxMoveX": 0,
        "minMoveY": 0,
        "maxMoveY": 0,
        "minMoveZ": 0,
        "maxMoveZ": 0,
        "speedZoomMaxSpeed": 1e+010,
        "speedZoomMaxFOV": 0
    },
    # Class: CfgVehicles\\All\\ViewCargo [Indent level: 1],
    "ViewCargo": {
        "initAngleX": 5,
        "minAngleX": -85,
        "maxAngleX": 85,
        "initAngleY": 0,
        "minAngleY": -150,
        "maxAngleY": 150,
        "minFov": 0.25,
        "maxFov": 1.25,
        "initFov": 0.75,
        "minMoveX": 0,
        "maxMoveX": 0,
        "minMoveY": 0,
        "maxMoveY": 0,
        "minMoveZ": 0,
        "maxMoveZ": 0,
        "speedZoomMaxSpeed": 1e+010,
        "speedZoomMaxFOV": 0
    },
    # Class: CfgVehicles\\All\\ViewOptics [Indent level: 1],
    "ViewOptics": {
        "initAngleX": 0,
        "minAngleX": -30,
        "maxAngleX": 30,
        "initAngleY": 0,
        "minAngleY": -100,
        "maxAngleY": 100,
        "initFov": 0.7,
        "minFov": 0.42,
        "maxFov": 0.85,
        "minMoveX": 0,
        "maxMoveX": 0,
        "minMoveY": 0,
        "maxMoveY": 0,
        "minMoveZ": 0,
        "maxMoveZ": 0,
        "speedZoomMaxSpeed": 1e+010,
        "speedZoomMaxFOV": 0
    },
    # Class: CfgVehicles\\All\\PilotSpec [Indent level: 1],
    "PilotSpec": {
        "showHeadPhones": 0
    },
    # Class: CfgVehicles\\All\\CargoSpec [Indent level: 1],
    "CargoSpec": {
        # Class: CfgVehicles\\All\\CargoSpec\\Cargo1 [Indent level: 2]
        "Cargo1": {
            "showHeadPhones": 0
        }
    },
    "transportSoldier": 0,
    "transportVehiclesCount": 0,
    "transportVehiclesMass": 0,
    "attendant": 0,
    "engineer": 0,
    "uavHacker": 0,
    "soundEngine": ["",1,1],
    "soundEnviron": ["",1,1],
    # Class: CfgVehicles\\All\\SoundEnvironExt [Indent level: 1],
    "SoundEnvironExt": {
    },
    # Class: CfgVehicles\\All\\SoundEquipment [Indent level: 1],
    "SoundEquipment": {
    },
    # Class: CfgVehicles\\All\\SoundGear [Indent level: 1],
    "SoundGear": {
    },
    # Class: CfgVehicles\\All\\SoundBreath [Indent level: 1],
    "SoundBreath": {
    },
    # Class: CfgVehicles\\All\\SoundBreathSwimming [Indent level: 1],
    "SoundBreathSwimming": {
    },
    # Class: CfgVehicles\\All\\SoundBreathInjured [Indent level: 1],
    "SoundBreathInjured": {
    },
    # Class: CfgVehicles\\All\\SoundHitScream [Indent level: 1],
    "SoundHitScream": {
    },
    # Class: CfgVehicles\\All\\SoundInjured [Indent level: 1],
    "SoundInjured": {
    },
    # Class: CfgVehicles\\All\\SoundBreathAutomatic [Indent level: 1],
    "SoundBreathAutomatic": {
    },
    # Class: CfgVehicles\\All\\SoundDrown [Indent level: 1],
    "SoundDrown": {
    },
    # Class: CfgVehicles\\All\\SoundChoke [Indent level: 1],
    "SoundChoke": {
    },
    # Class: CfgVehicles\\All\\SoundRecovered [Indent level: 1],
    "SoundRecovered": {
    },
    # Class: CfgVehicles\\All\\SoundBurning [Indent level: 1],
    "SoundBurning": {
    },
    # Class: CfgVehicles\\All\\PulsationSound [Indent level: 1],
    "PulsationSound": {
    },
    # Class: CfgVehicles\\All\\SoundDrowning [Indent level: 1],
    "SoundDrowning": {
    },
    "soundCrash": ["",0.316228,1],
    "soundLandCrash": ["",1,1],
    "soundWaterCrash": ["",0.177828,1],
    "soundGetIn": ["",0.000316228,1],
    "soundGetOut": ["",0.000316228,1],
    "soundServo": ["",0.00316228,0.5],
    "soundElevation": ["",0.00316228,0.5],
    "sounddamage": ["",1,1],
    "soundEngineOnInt": ["",1,1],
    "soundEngineOffInt": ["",1,1],
    "soundEngineOnExt": ["",1,1],
    "soundEngineOffExt": ["",1,1],
    "soundGearUp": ["",1,1],
    "soundGearDown": ["",1,1],
    "soundFlapsUp": ["",1,1],
    "soundFlapsDown": ["",1,1],
    "cabinOpenSound": ["",1,1],
    "cabinCloseSound": ["",1,1],
    "cabinOpenSoundInternal": ["",1,1],
    "cabinCloseSoundInternal": ["",1,1],
    "soundCrashes": ["soundCrash",1],
    "soundLandCrashes": ["soundLandCrash",1],
    "soundWaterCrashes": ["soundWaterCrash",1],
    "emptySound": ["",0,1],
    "soundWoodCrash": ["emptySound",0],
    "soundBushCrash": ["emptySound",0],
    "soundBuildingCrash": ["emptySound",0],
    "soundArmorCrash": ["emptySound",0],
    "soundLocked": ["",1,1],
    "soundIncommingMissile": ["",1,1],
    "soundDammage": ["",1,1],
    # Class: CfgVehicles\\All\\Reflectors [Indent level: 1],
    "Reflectors": {
    },
    "aggregateReflectors": [],
    "getInAction": "",
    "getOutAction": "",
    "driverAction": "",
    "driverInAction": "",
    "cargoGetInAction": [],
    "cargoGetOutAction": [],
    "cargoAction": [],
    "cargoIsCoDriver": [0],
    "driverCompartments": "Compartment1",
    "cargoCompartments": ["Compartment1"],
    "driverOpticsModel": "",
    "driverOpticsEffect": [],
    "driverOpticsColor": [1,1,1,1],
    "hideProxyInCombat": 0,
    "forceHideDriver": 0,
    "canHideDriver": -1,
    "castDriverShadow": 0,
    "castCargoShadow": 0,
    "viewDriverShadow": 1,
    "viewDriverShadowDiff": 1,
    "viewDriverShadowAmb": 1,
    "viewCargoShadow": 1,
    "viewCargoShadowDiff": 1,
    "viewCargoShadowAmb": 1,
    "ejectDeadDriver": 0,
    "ejectDeadCargo": 0,
    "crew": "Civilian",
    "hiddenSelectionsMaterials": [],
    "hiddenUnderwaterSelections": [],
    "shownUnderWaterSelections": [],
    "hiddenUnderwaterSelectionsTextures": [],
    # Class: CfgVehicles\\All\\FxExplo [Indent level: 1],
    "FxExplo": {
        "access": 1
    },
    # Class: CfgVehicles\\All\\AnimationSources [Indent level: 1],
    "AnimationSources": {
    },
    "selectionFireAnim": "",
    # Class: CfgVehicles\\All\\GunFire [Indent level: 1],
    "GunFire": {
        "access": 0,
        "cloudletDuration": 0.2,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 0.2,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 0.5,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletFire",
        "cloudletColor": [1,1,1,0],
        "interval": 0.01,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 4500,
        "deltaT": -3000,
        # Class: WeaponFireGun\\Table [Indent level: 0],
        "Table": {
            # Class: WeaponFireGun\\Table\\T0 [Indent level: 1]
            "T0": {
                "maxT": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: WeaponFireGun\\Table\\T1 [Indent level: 1],
            "T1": {
                "maxT": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: WeaponFireGun\\Table\\T2 [Indent level: 1],
            "T2": {
                "maxT": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: WeaponFireGun\\Table\\T3 [Indent level: 1],
            "T3": {
                "maxT": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: WeaponFireGun\\Table\\T4 [Indent level: 1],
            "T4": {
                "maxT": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: WeaponFireGun\\Table\\T5 [Indent level: 1],
            "T5": {
                "maxT": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: WeaponFireGun\\Table\\T6 [Indent level: 1],
            "T6": {
                "maxT": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: WeaponFireGun\\Table\\T7 [Indent level: 1],
            "T7": {
                "maxT": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: WeaponFireGun\\Table\\T8 [Indent level: 1],
            "T8": {
                "maxT": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: WeaponFireGun\\Table\\T9 [Indent level: 1],
            "T9": {
                "maxT": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: WeaponFireGun\\Table\\T10 [Indent level: 1],
            "T10": {
                "maxT": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: WeaponFireGun\\Table\\T11 [Indent level: 1],
            "T11": {
                "maxT": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: WeaponFireGun\\Table\\T12 [Indent level: 1],
            "T12": {
                "maxT": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: WeaponFireGun\\Table\\T13 [Indent level: 1],
            "T13": {
                "maxT": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: WeaponFireGun\\Table\\T14 [Indent level: 1],
            "T14": {
                "maxT": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: WeaponFireGun\\Table\\T15 [Indent level: 1],
            "T15": {
                "maxT": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: WeaponFireGun\\Table\\T16 [Indent level: 1],
            "T16": {
                "maxT": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: WeaponFireGun\\Table\\T17 [Indent level: 1],
            "T17": {
                "maxT": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: WeaponFireGun\\Table\\T18 [Indent level: 1],
            "T18": {
                "maxT": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: WeaponFireGun\\Table\\T19 [Indent level: 1],
            "T19": {
                "maxT": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: WeaponFireGun\\Table\\T20 [Indent level: 1],
            "T20": {
                "maxT": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: WeaponFireGun\\Table\\T21 [Indent level: 1],
            "T21": {
                "maxT": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: WeaponFireGun\\Table\\T22 [Indent level: 1],
            "T22": {
                "maxT": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgVehicles\\All\\GunClouds [Indent level: 1],
    "GunClouds": {
        "access": 0,
        "cloudletDuration": 0.3,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 1,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 1,
        "cloudletAccY": 0.4,
        "cloudletMinYSpeed": 0.2,
        "cloudletMaxYSpeed": 0.8,
        "cloudletShape": "cloudletClouds",
        "cloudletColor": [1,1,1,0],
        "interval": 0.05,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 0,
        "deltaT": 0,
        # Class: WeaponCloudsGun\\Table [Indent level: 0],
        "Table": {
            # Class: WeaponCloudsGun\\Table\\T0 [Indent level: 1]
            "T0": {
                "maxT": 0,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgVehicles\\All\\MGunClouds [Indent level: 1],
    "MGunClouds": {
        "access": 0,
        "cloudletGrowUp": 0.05,
        "cloudletFadeIn": 0,
        "cloudletFadeOut": 0.1,
        "cloudletDuration": 0.05,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 0.3,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletClouds",
        "cloudletColor": [1,1,1,0],
        "timeToLive": 0,
        "interval": 0.02,
        "size": 0.3,
        "sourceSize": 0.02,
        "initT": 0,
        "deltaT": 0,
        # Class: WeaponCloudsMGun\\Table [Indent level: 0],
        "Table": {
            # Class: WeaponCloudsMGun\\Table\\T0 [Indent level: 1]
            "T0": {
                "maxT": 0,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgVehicles\\All\\Damage [Indent level: 1],
    "Damage": {
        "tex": [],
        "mat": []
    },
    "selectionDamage": "zbytek",
    "HeadAimDown": 0,
    "cargoCanEject": 1,
    "driverCanEject": 1,
    "fireResistance": 10,
    "airCapacity": 10,
    "waterResistance": 10,
    "waterDamageEngine": 0.2,
    "maxFordingDepth": 1,
    "impactEffectsSea": "ImpactEffectsSea",
    "damageTexDelay": 0,
    "slingLoadCargoMemoryPoints": [],
    "slingLoadCargoMemoryPointsDir": [],
    "numberPhysicalWheels": 0,
    "damageHalf": [],
    "damageFull": [],
    # Class: CfgVehicles\\All\\camShakeGForce [Indent level: 1],
    "camShakeGForce": {
        "power": 1,
        "frequency": 20,
        "distance": 0,
        "minSpeed": 1,
        "duration": 3
    },
    "minGForce": 0.2,
    "maxGForce": 2,
    "gForceShakeAttenuation": 0.5,
    # Class: CfgVehicles\\All\\camShakeDamage [Indent level: 1],
    "camShakeDamage": {
        "power": 0.5,
        "frequency": 60,
        "distance": -1,
        "minSpeed": 1,
        "attenuation": 0.5,
        "duration": 3
    },
    "weaponsGroup1": "1 + 2",
    "weaponsGroup2": 4,
    "weaponsGroup3": "8 + 16 + 32",
    "weaponsGroup4": "64 + 128",
    "soundTurnIn": ["",0.000316228,1],
    "soundTurnOut": ["",0.000316228,1],
    "soundTurnInInternal": ["",0.000316228,1],
    "soundTurnOutInternal": ["",0.000316228,1],
    "features": "",
    # Class: CfgVehicles\\All\\SpeechVariants [Indent level: 1],
    "SpeechVariants": {
        # Class: CfgVehicles\\All\\SpeechVariants\\Default [Indent level: 2]
        "Default": {
            "speechSingular": ["veh_unknown_s"],
            "speechPlural": ["veh_unknown_p"]
        }
    },
    "textSingular": "unknown",
    "textPlural": "unknown",
    "insideDetectCoef": 0.05,
},
"rhs_sidor": {
    "dlc": "RHS_AFRF",
    "scope": 2,
    "model": "rhsafrf\\addons\\rhs_infantry\\gear\\backpacks\\rhs_sidor",
    "picture": "rhsafrf\\addons\\rhs_infantry\\Data\\inventory\\gear_icon_sidor_ca.paa",
    "author": "Red Hammer Studios",
    "displayName": "Sidor",
    "hiddenSelectionsTextures": ["rhsafrf\\addons\\rhs_infantry\\data\\gearpack3_ranets_co.paa"],
    "maximumLoad": 129,
    "mass": 20,
    "mapSize": 0.45,
    "_generalMacro": "B_AssaultPack_Base",
    # Class: CfgVehicles\\Bag_Base\\TransportMagazines [Indent level: 1],
    "TransportMagazines": {
    },
    # Class: CfgVehicles\\Bag_Base\\TransportWeapons [Indent level: 1],
    "TransportWeapons": {
    },
    "isbackpack": 1,
    "reversed": 1,
    "editorCategory": "EdCat_Equipment",
    "editorSubcategory": "EdSubcat_Backpacks",
    "vehicleClass": "Backpacks",
    "allowedSlots": [901],
    "icon": "iconBackpack",
    "transportMaxWeapons": 1,
    "transportMaxMagazines": 20,
    # Class: CfgVehicles\\Bag_Base\\DestructionEffects [Indent level: 1],
    "DestructionEffects": {
    },
    "hiddenSelections": ["Camo"],
    "side": 3,
    "waterLeakiness": 100,
    "animated": 0,
    "accuracy": 0.2,
    "typicalCargo": [],
    "destrType": "DestructBuilding",
    "transportMaxBackpacks": 1,
    "transportAmmo": 0,
    "transportRepair": 0,
    "transportFuel": 0,
    "supplyRadius": 1.4,
    "cost": 0,
    "armor": 200,
    "ladders": [],
    "nameSound": "obj_building",
    "scopeCurator": 0,
    "hasDriver": 0,
    "audible": 0,
    "simulation": "house",
    "weapons": [],
    "magazines": [],
    "irTarget": 0,
    "type": 1,
    "threat": [0,0,0],
    "maxSpeed": 0,
    "coefInside": 2,
    "coefInsideHeur": 2,
    "coefSpeedInside": 2,
    "windSockExist": 0,
    "countsForScoreboard": 0,
    "access": 0,
    "autocenter": 1,
    "shadow": 1,
    "featureType": 0,
    "faction": "Default",
    "speechSingular": [],
    "speechPlural": [],
    "maxDetectRange": 20,
    "detectSkill": 20,
    "mineAlertIconRange": 200,
    "killFriendlyExpCoef": 1,
    "weaponSlots": 0,
    "camouflage": 2,
    "spotableDarkNightLightsOff": 0.001,
    "spotableNightLightsOff": 0.02,
    "spotableNightLightsOn": 4,
    "accuracyDarkNightLightsOff": 0.001,
    "accuracyNightLightsOff": 0.006,
    "accuracyNightLightsOn": 0.1,
    "attenuationEffectType": "",
    "insideSoundCoef": 0.5,
    "outsideSoundFilter": 0,
    "occludeSoundsWhenIn": 0.316228,
    "obstructSoundsWhenIn": 0.562341,
    "obstructSoundLFRatio": 0,
    "occludeSoundLFRatio": 0.25,
    "unloadInCombat": 0,
    "antiRollbarForceCoef": 0,
    "antiRollbarForceLimit": 5,
    "antiRollbarSpeedMin": 20,
    "antiRollbarSpeedMax": 60,
    "slowSpeedForwardCoef": 0.3,
    "normalSpeedForwardCoef": 0.85,
    "epeImpulseDamageCoef": 30,
    "gunnerHasFlares": 1,
    "enableManualFire": 1,
    "sensitivity": 2.5,
    "sensitivityEar": 0.0075,
    "portrait": "",
    "ghostPreview": "",
    "armorLights": 0.4,
    "armorStructural": 1,
    "crewVulnerable": 1,
    "damageResistance": 0.004,
    "crewCrashProtection": 1,
    "replaceDamaged": "",
    "replaceDamagedLimit": 0.9,
    "replaceDamagedHitpoints": [],
    "keepInEPESceneAfterDeath": 0,
    "fuelCapacity": 0,
    "fuelConsumptionRate": 0.01,
    "extCameraPosition": [0,2,-20],
    "groupCameraPosition": [0,5,-30],
    "extCameraParams": [1],
    "steerAheadSimul": 0.3,
    "steerAheadPlan": 0.4,
    "cameraSmoothSpeed": 5,
    "minFireTime": 20,
    "predictTurnSimul": 1.2,
    "predictTurnPlan": 1,
    "indirectHitEnemyCoefAI": 10,
    "indirectHitFriendlyCoefAI": -20,
    "indirectHitCivilianCoefAI": -20,
    "indirectHitUnknownCoefAI": -0.5,
    "precision": 5,
    "brakeDistance": 5,
    "formationX": 10,
    "formationZ": 20,
    "formationTime": 5,
    "alwaysTarget": 0,
    "irScanRangeMin": 0,
    "irScanRangeMax": 0,
    "irScanToEyeFactor": 1,
    "irScanGround": 1,
    "laserTarget": 0,
    "laserScanner": 0,
    "nvTarget": 0,
    "nvScanner": 0,
    "artilleryTarget": 0,
    "artilleryScanner": 0,
    "canUseScanners": 1,
    "preferRoads": 0,
    "unitInfoType": "RscUnitInfoTank",
    "unitInfoTypeLite": 0,
    "hideUnitInfo": 0,
    "nightVision": 0,
    "commanderCanSee": 31,
    "gunnerCanSee": "4+8+16",
    "driverCanSee": "2+8+16",
    "showCrewAim": 7,
    "radarType": 0,
    "limitedSpeedCoef": 0.22,
    "secondaryExplosion": -1,
    "driverForceOptics": 0,
    "hideWeaponsDriver": 1,
    "hideWeaponsCargo": 0,
    "getInRadius": 2.5,
    "selectionClan": "",
    "selectionDashboard": "",
    "selectionShowDamage": "",
    "selectionBackLights": "",
    "memoryPointSupply": "doplnovani",
    "enableGPS": 0,
    "enableWatch": 0,
    "enableRadio": 0,
    "lockDetectionSystem": 0,
    "incomingMissileDetectionSystem": 0,
    "headGforceLeaningFactor": [0.01,0.002,0.01],
    "usePreciseGetInAction": 0,
    "allowTabLock": 1,
    "showAllTargets": 0,
    "dustFrontLeftPos": "dustFrontLeft",
    "dustFrontRightPos": "dustFrontRight",
    "dustBackLeftPos": "dustBackLeft",
    "dustBackRightPos": "dustBackRight",
    "wheelCircumference": 1,
    "waterResistanceCoef": 0.5,
    "waterLinearDampingCoefX": 0,
    "waterLinearDampingCoefY": 0,
    "waterAngularDampingCoef": 0,
    "showNVGDriver": 0,
    "showNVGCommander": 0,
    "showNVGGunner": 0,
    "showNVGCargo": [0],
    "soundAttenuationCargo": [1],
    "hullDamageCauseExplosion": 0,
    # Class: CfgVehicles\\All\\EventHandlers [Indent level: 1],
    "EventHandlers": {
    },
    # Class: CfgVehicles\\All\\MarkerLights [Indent level: 1],
    "MarkerLights": {
    },
    # Class: CfgVehicles\\All\\NVGMarkers [Indent level: 1],
    "NVGMarkers": {
    },
    # Class: CfgVehicles\\All\\NVGMarker [Indent level: 1],
    "NVGMarker": {
        "diffuse": [1,1,1,1],
        "ambient": [1,1,1,1],
        "brightness": 1,
        "blinking": 0,
        "onlyInNvg": 0
    },
    # Class: CfgVehicles\\All\\Turrets [Indent level: 1],
    "Turrets": {
    },
    # Class: CfgVehicles\\All\\HeadLimits [Indent level: 1],
    "HeadLimits": {
        "initAngleX": 5,
        "minAngleX": -30,
        "maxAngleX": 40,
        "initAngleY": 0,
        "minAngleY": -90,
        "maxAngleY": 90,
        "minAngleZ": -45,
        "maxAngleZ": 45,
        "rotZRadius": 0.2
    },
    # Class: CfgVehicles\\All\\ViewPilot [Indent level: 1],
    "ViewPilot": {
        "initAngleX": 5,
        "minAngleX": -55,
        "maxAngleX": 85,
        "initAngleY": 0,
        "minAngleY": -150,
        "maxAngleY": 150,
        "minFov": 0.25,
        "maxFov": 1.25,
        "initFov": 0.75,
        "minMoveX": 0,
        "maxMoveX": 0,
        "minMoveY": 0,
        "maxMoveY": 0,
        "minMoveZ": 0,
        "maxMoveZ": 0,
        "speedZoomMaxSpeed": 1e+010,
        "speedZoomMaxFOV": 0
    },
    # Class: CfgVehicles\\All\\ViewCargo [Indent level: 1],
    "ViewCargo": {
        "initAngleX": 5,
        "minAngleX": -85,
        "maxAngleX": 85,
        "initAngleY": 0,
        "minAngleY": -150,
        "maxAngleY": 150,
        "minFov": 0.25,
        "maxFov": 1.25,
        "initFov": 0.75,
        "minMoveX": 0,
        "maxMoveX": 0,
        "minMoveY": 0,
        "maxMoveY": 0,
        "minMoveZ": 0,
        "maxMoveZ": 0,
        "speedZoomMaxSpeed": 1e+010,
        "speedZoomMaxFOV": 0
    },
    # Class: CfgVehicles\\All\\ViewOptics [Indent level: 1],
    "ViewOptics": {
        "initAngleX": 0,
        "minAngleX": -30,
        "maxAngleX": 30,
        "initAngleY": 0,
        "minAngleY": -100,
        "maxAngleY": 100,
        "initFov": 0.7,
        "minFov": 0.42,
        "maxFov": 0.85,
        "minMoveX": 0,
        "maxMoveX": 0,
        "minMoveY": 0,
        "maxMoveY": 0,
        "minMoveZ": 0,
        "maxMoveZ": 0,
        "speedZoomMaxSpeed": 1e+010,
        "speedZoomMaxFOV": 0
    },
    # Class: CfgVehicles\\All\\PilotSpec [Indent level: 1],
    "PilotSpec": {
        "showHeadPhones": 0
    },
    # Class: CfgVehicles\\All\\CargoSpec [Indent level: 1],
    "CargoSpec": {
        # Class: CfgVehicles\\All\\CargoSpec\\Cargo1 [Indent level: 2]
        "Cargo1": {
            "showHeadPhones": 0
        }
    },
    "transportSoldier": 0,
    "transportVehiclesCount": 0,
    "transportVehiclesMass": 0,
    "attendant": 0,
    "engineer": 0,
    "uavHacker": 0,
    "soundEngine": ["",1,1],
    "soundEnviron": ["",1,1],
    # Class: CfgVehicles\\All\\SoundEnvironExt [Indent level: 1],
    "SoundEnvironExt": {
    },
    # Class: CfgVehicles\\All\\SoundEquipment [Indent level: 1],
    "SoundEquipment": {
    },
    # Class: CfgVehicles\\All\\SoundGear [Indent level: 1],
    "SoundGear": {
    },
    # Class: CfgVehicles\\All\\SoundBreath [Indent level: 1],
    "SoundBreath": {
    },
    # Class: CfgVehicles\\All\\SoundBreathSwimming [Indent level: 1],
    "SoundBreathSwimming": {
    },
    # Class: CfgVehicles\\All\\SoundBreathInjured [Indent level: 1],
    "SoundBreathInjured": {
    },
    # Class: CfgVehicles\\All\\SoundHitScream [Indent level: 1],
    "SoundHitScream": {
    },
    # Class: CfgVehicles\\All\\SoundInjured [Indent level: 1],
    "SoundInjured": {
    },
    # Class: CfgVehicles\\All\\SoundBreathAutomatic [Indent level: 1],
    "SoundBreathAutomatic": {
    },
    # Class: CfgVehicles\\All\\SoundDrown [Indent level: 1],
    "SoundDrown": {
    },
    # Class: CfgVehicles\\All\\SoundChoke [Indent level: 1],
    "SoundChoke": {
    },
    # Class: CfgVehicles\\All\\SoundRecovered [Indent level: 1],
    "SoundRecovered": {
    },
    # Class: CfgVehicles\\All\\SoundBurning [Indent level: 1],
    "SoundBurning": {
    },
    # Class: CfgVehicles\\All\\PulsationSound [Indent level: 1],
    "PulsationSound": {
    },
    # Class: CfgVehicles\\All\\SoundDrowning [Indent level: 1],
    "SoundDrowning": {
    },
    "soundCrash": ["",0.316228,1],
    "soundLandCrash": ["",1,1],
    "soundWaterCrash": ["",0.177828,1],
    "soundGetIn": ["",0.000316228,1],
    "soundGetOut": ["",0.000316228,1],
    "soundServo": ["",0.00316228,0.5],
    "soundElevation": ["",0.00316228,0.5],
    "sounddamage": ["",1,1],
    "soundEngineOnInt": ["",1,1],
    "soundEngineOffInt": ["",1,1],
    "soundEngineOnExt": ["",1,1],
    "soundEngineOffExt": ["",1,1],
    "soundGearUp": ["",1,1],
    "soundGearDown": ["",1,1],
    "soundFlapsUp": ["",1,1],
    "soundFlapsDown": ["",1,1],
    "cabinOpenSound": ["",1,1],
    "cabinCloseSound": ["",1,1],
    "cabinOpenSoundInternal": ["",1,1],
    "cabinCloseSoundInternal": ["",1,1],
    "soundCrashes": ["soundCrash",1],
    "soundLandCrashes": ["soundLandCrash",1],
    "soundWaterCrashes": ["soundWaterCrash",1],
    "emptySound": ["",0,1],
    "soundWoodCrash": ["emptySound",0],
    "soundBushCrash": ["emptySound",0],
    "soundBuildingCrash": ["emptySound",0],
    "soundArmorCrash": ["emptySound",0],
    "soundLocked": ["",1,1],
    "soundIncommingMissile": ["",1,1],
    "soundDammage": ["",1,1],
    # Class: CfgVehicles\\All\\Reflectors [Indent level: 1],
    "Reflectors": {
    },
    "aggregateReflectors": [],
    "getInAction": "",
    "getOutAction": "",
    "driverAction": "",
    "driverInAction": "",
    "cargoGetInAction": [],
    "cargoGetOutAction": [],
    "cargoAction": [],
    "cargoIsCoDriver": [0],
    "driverCompartments": "Compartment1",
    "cargoCompartments": ["Compartment1"],
    "driverOpticsModel": "",
    "driverOpticsEffect": [],
    "driverOpticsColor": [1,1,1,1],
    "hideProxyInCombat": 0,
    "forceHideDriver": 0,
    "canHideDriver": -1,
    "castDriverShadow": 0,
    "castCargoShadow": 0,
    "viewDriverShadow": 1,
    "viewDriverShadowDiff": 1,
    "viewDriverShadowAmb": 1,
    "viewCargoShadow": 1,
    "viewCargoShadowDiff": 1,
    "viewCargoShadowAmb": 1,
    "ejectDeadDriver": 0,
    "ejectDeadCargo": 0,
    "crew": "Civilian",
    "hiddenSelectionsMaterials": [],
    "hiddenUnderwaterSelections": [],
    "shownUnderWaterSelections": [],
    "hiddenUnderwaterSelectionsTextures": [],
    # Class: CfgVehicles\\All\\FxExplo [Indent level: 1],
    "FxExplo": {
        "access": 1
    },
    # Class: CfgVehicles\\All\\AnimationSources [Indent level: 1],
    "AnimationSources": {
    },
    "selectionFireAnim": "",
    # Class: CfgVehicles\\All\\GunFire [Indent level: 1],
    "GunFire": {
        "access": 0,
        "cloudletDuration": 0.2,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 0.2,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 0.5,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletFire",
        "cloudletColor": [1,1,1,0],
        "interval": 0.01,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 4500,
        "deltaT": -3000,
        # Class: WeaponFireGun\\Table [Indent level: 0],
        "Table": {
            # Class: WeaponFireGun\\Table\\T0 [Indent level: 1]
            "T0": {
                "maxT": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: WeaponFireGun\\Table\\T1 [Indent level: 1],
            "T1": {
                "maxT": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: WeaponFireGun\\Table\\T2 [Indent level: 1],
            "T2": {
                "maxT": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: WeaponFireGun\\Table\\T3 [Indent level: 1],
            "T3": {
                "maxT": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: WeaponFireGun\\Table\\T4 [Indent level: 1],
            "T4": {
                "maxT": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: WeaponFireGun\\Table\\T5 [Indent level: 1],
            "T5": {
                "maxT": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: WeaponFireGun\\Table\\T6 [Indent level: 1],
            "T6": {
                "maxT": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: WeaponFireGun\\Table\\T7 [Indent level: 1],
            "T7": {
                "maxT": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: WeaponFireGun\\Table\\T8 [Indent level: 1],
            "T8": {
                "maxT": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: WeaponFireGun\\Table\\T9 [Indent level: 1],
            "T9": {
                "maxT": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: WeaponFireGun\\Table\\T10 [Indent level: 1],
            "T10": {
                "maxT": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: WeaponFireGun\\Table\\T11 [Indent level: 1],
            "T11": {
                "maxT": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: WeaponFireGun\\Table\\T12 [Indent level: 1],
            "T12": {
                "maxT": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: WeaponFireGun\\Table\\T13 [Indent level: 1],
            "T13": {
                "maxT": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: WeaponFireGun\\Table\\T14 [Indent level: 1],
            "T14": {
                "maxT": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: WeaponFireGun\\Table\\T15 [Indent level: 1],
            "T15": {
                "maxT": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: WeaponFireGun\\Table\\T16 [Indent level: 1],
            "T16": {
                "maxT": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: WeaponFireGun\\Table\\T17 [Indent level: 1],
            "T17": {
                "maxT": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: WeaponFireGun\\Table\\T18 [Indent level: 1],
            "T18": {
                "maxT": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: WeaponFireGun\\Table\\T19 [Indent level: 1],
            "T19": {
                "maxT": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: WeaponFireGun\\Table\\T20 [Indent level: 1],
            "T20": {
                "maxT": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: WeaponFireGun\\Table\\T21 [Indent level: 1],
            "T21": {
                "maxT": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: WeaponFireGun\\Table\\T22 [Indent level: 1],
            "T22": {
                "maxT": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgVehicles\\All\\GunClouds [Indent level: 1],
    "GunClouds": {
        "access": 0,
        "cloudletDuration": 0.3,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 1,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 1,
        "cloudletAccY": 0.4,
        "cloudletMinYSpeed": 0.2,
        "cloudletMaxYSpeed": 0.8,
        "cloudletShape": "cloudletClouds",
        "cloudletColor": [1,1,1,0],
        "interval": 0.05,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 0,
        "deltaT": 0,
        # Class: WeaponCloudsGun\\Table [Indent level: 0],
        "Table": {
            # Class: WeaponCloudsGun\\Table\\T0 [Indent level: 1]
            "T0": {
                "maxT": 0,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgVehicles\\All\\MGunClouds [Indent level: 1],
    "MGunClouds": {
        "access": 0,
        "cloudletGrowUp": 0.05,
        "cloudletFadeIn": 0,
        "cloudletFadeOut": 0.1,
        "cloudletDuration": 0.05,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 0.3,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletClouds",
        "cloudletColor": [1,1,1,0],
        "timeToLive": 0,
        "interval": 0.02,
        "size": 0.3,
        "sourceSize": 0.02,
        "initT": 0,
        "deltaT": 0,
        # Class: WeaponCloudsMGun\\Table [Indent level: 0],
        "Table": {
            # Class: WeaponCloudsMGun\\Table\\T0 [Indent level: 1]
            "T0": {
                "maxT": 0,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgVehicles\\All\\Damage [Indent level: 1],
    "Damage": {
        "tex": [],
        "mat": []
    },
    "selectionDamage": "zbytek",
    "HeadAimDown": 0,
    "cargoCanEject": 1,
    "driverCanEject": 1,
    "fireResistance": 10,
    "airCapacity": 10,
    "waterResistance": 10,
    "waterDamageEngine": 0.2,
    "maxFordingDepth": 1,
    "impactEffectsSea": "ImpactEffectsSea",
    "damageTexDelay": 0,
    "slingLoadCargoMemoryPoints": [],
    "slingLoadCargoMemoryPointsDir": [],
    "numberPhysicalWheels": 0,
    "damageHalf": [],
    "damageFull": [],
    # Class: CfgVehicles\\All\\camShakeGForce [Indent level: 1],
    "camShakeGForce": {
        "power": 1,
        "frequency": 20,
        "distance": 0,
        "minSpeed": 1,
        "duration": 3
    },
    "minGForce": 0.2,
    "maxGForce": 2,
    "gForceShakeAttenuation": 0.5,
    # Class: CfgVehicles\\All\\camShakeDamage [Indent level: 1],
    "camShakeDamage": {
        "power": 0.5,
        "frequency": 60,
        "distance": -1,
        "minSpeed": 1,
        "attenuation": 0.5,
        "duration": 3
    },
    "weaponsGroup1": "1 + 2",
    "weaponsGroup2": 4,
    "weaponsGroup3": "8 + 16 + 32",
    "weaponsGroup4": "64 + 128",
    "soundTurnIn": ["",0.000316228,1],
    "soundTurnOut": ["",0.000316228,1],
    "soundTurnInInternal": ["",0.000316228,1],
    "soundTurnOutInternal": ["",0.000316228,1],
    "features": "",
    # Class: CfgVehicles\\All\\SpeechVariants [Indent level: 1],
    "SpeechVariants": {
        # Class: CfgVehicles\\All\\SpeechVariants\\Default [Indent level: 2]
        "Default": {
            "speechSingular": ["veh_unknown_s"],
            "speechPlural": ["veh_unknown_p"]
        }
    },
    "textSingular": "unknown",
    "textPlural": "unknown",
    "insideDetectCoef": 0.05,
}