rhs_mag_mk82 = {
    "bin|config.bin/CfgMagazines/rhs_mag_mk82/count": 1,
    "bin|config.bin/CfgMagazines/rhs_mag_mk82/displayName": "Mk82",
    "bin|config.bin/CfgMagazines/rhs_mag_mk82/descriptionShort": "500lb bomb",
    "bin|config.bin/CfgMagazines/rhs_mag_mk82/ammo": "rhs_ammo_mk82"    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_mk82/hit": 5000    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_mk82/indirectHit": 1150    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_mk82/cost": 50    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_mk82/sideAirFriction": 0.25    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_mk82/aiAmmoUsageFlags": "64 + 128 + 512"    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_mk82/maverickWeaponIndexOffset": 0    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/indirectHitRange": 12    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/dangerRadiusHit": 1250    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/suppressionRadiusHit": 100    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/irLock": 0    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/laserLock": 0    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/airFriction": 0.08    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/maneuvrability": 4.6    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/trackLead": 0    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/maxSpeed": 100    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/timeToLive": 120    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/initTime": 0    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/thrustTime": 0    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/thrust": 0    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/multiSoundHit": ["soundHit1",0.2,"soundHit2",0.2,"soundHit3",0.2,"soundHit4",0.2,"soundHit5",0.2]    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/explosionSoundEffect": "DefaultExplosion"    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/model": "\A3\Weapons_F\Ammo\Bomb_02_F"    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/proxyShape": "\A3\Weapons_F\Ammo\Bomb_02_F"    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/CraterEffects": "BombCrater"    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/explosionEffects": "BombExplosion"    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/whistleDist": 24    ,
    "bin|config.bin/CfgAmmo/Bo_Mk82/SoundSetExplosion": ["BombsHeavy_Exp_SoundSet","BombsHeavy_Tail_SoundSet","Explosion_Debris_SoundSet"]    ,
    "bin|config.bin/CfgAmmo/BombCore/maxControlRange": 0    ,
    "bin|config.bin/CfgAmmo/BombCore/simulation": "shotMissile"    ,
    "bin|config.bin/CfgAmmo/Default/access": 3    ,
    "bin|config.bin/CfgAmmo/Default/underwaterHitRangeCoef": 1    ,
    "bin|config.bin/CfgAmmo/Default/typicalSpeed": 900    ,
    "bin|config.bin/CfgAmmo/Default/explosionForceCoef": 1    ,
    "bin|config.bin/CfgAmmo/Default/isCraterOriented": 0    ,
    "bin|config.bin/CfgAmmo/Default/craterShape": ""    ,
    "bin|config.bin/CfgAmmo/Default/weaponType": "Default"    ,
    "bin|config.bin/CfgAmmo/Default/animated": 0    ,
    "bin|config.bin/CfgAmmo/Default/shadow": 0    ,
    "bin|config.bin/CfgAmmo/Default/cartridge": ""    ,
    "bin|config.bin/CfgAmmo/Default/simulationStep": 0.05    ,
    "bin|config.bin/CfgAmmo/Default/tracerColor": [0.7,0.7,0.5,0.04]    ,
    "bin|config.bin/CfgAmmo/Default/tracerColorR": [0.7,0.7,0.5,0.04]    ,
    "bin|config.bin/CfgAmmo/Default/supersonicCrackNear": ["",1,1]    ,
    "bin|config.bin/CfgAmmo/Default/supersonicCrackFar": ["",1,1]    ,
    "bin|config.bin/CfgAmmo/Default/hitGroundSoft": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitGroundHard": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitMan": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitArmor": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitIron": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitBuilding": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitFoliage": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitWood": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitGlass": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitGlassArmored": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitConcrete": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitRubber": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitPlastic": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitDefault": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitMetal": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitMetalplate": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitTyre": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitWater": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGroundSoft": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGroundHard": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactMan": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactIron": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactArmor": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactBuilding": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactFoliage": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactWood": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGlass": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGlassArmored": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactConcrete": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactRubber": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactPlastic": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactDefault": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactMetal": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactMetalplate": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactTyre": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactWater": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/grenadeFireSound": []    ,
    "bin|config.bin/CfgAmmo/Default/grenadeBurningSound": []    ,
    "bin|config.bin/CfgAmmo/Default/deflecting": 0    ,
    "bin|config.bin/CfgAmmo/Default/deflectionSlowDown": 0.8    ,
    "bin|config.bin/CfgAmmo/Default/explosive": 1    ,
    "bin|config.bin/CfgAmmo/Default/craterWaterEffects": "ImpactEffectsWater"    ,
    "bin|config.bin/CfgAmmo/Default/effectsMissile": "ExplosionEffects"    ,
    "bin|config.bin/CfgAmmo/Default/effectsMissileInit": ""    ,
    "bin|config.bin/CfgAmmo/Default/effectsSmoke": "SmokeShellWhite"    ,
    "bin|config.bin/CfgAmmo/Default/effectsFire": "CannonFire"    ,
    "bin|config.bin/CfgAmmo/Default/effectFlare": "FlareShell"    ,
    "bin|config.bin/CfgAmmo/Default/effectFly": ""    ,
    "bin|config.bin/CfgAmmo/Default/mineJumpEffects": ""    ,
    "bin|config.bin/CfgAmmo/Default/waterEffectOffset": 0.45    ,
    "bin|config.bin/CfgAmmo/Default/directionalExplosion": 0    ,
    "bin|config.bin/CfgAmmo/Default/explosionAngle": 60    ,
    "bin|config.bin/CfgAmmo/Default/explosionDir": "explosionDir"    ,
    "bin|config.bin/CfgAmmo/Default/explosionPos": "explosionPos"    ,
    "bin|config.bin/CfgAmmo/Default/explosionEffectsDir": "explosionDir"    ,
    "bin|config.bin/CfgAmmo/Default/minimumSafeZone": 0.1    ,
    "bin|config.bin/CfgAmmo/Default/minTimeToLive": 0    ,
    "bin|config.bin/CfgAmmo/Default/airLock": 0    ,
    "bin|config.bin/CfgAmmo/Default/nvLock": 0    ,
    "bin|config.bin/CfgAmmo/Default/artilleryLock": 0    ,
    "bin|config.bin/CfgAmmo/Default/hitOnWater": 0    ,
    "bin|config.bin/CfgAmmo/Default/lockSeekRadius": 100    ,
    "bin|config.bin/CfgAmmo/Default/manualControl": 0    ,
    "bin|config.bin/CfgAmmo/Default/trackOversteer": 1    ,
    "bin|config.bin/CfgAmmo/Default/missileLockCone": 0    ,
    "bin|config.bin/CfgAmmo/Default/weaponLockSystem": 0    ,
    "bin|config.bin/CfgAmmo/Default/cmImmunity": 1    ,
    "bin|config.bin/CfgAmmo/Default/lockType": 0    ,
    "bin|config.bin/CfgAmmo/Default/artilleryDispersion": 1    ,
    "bin|config.bin/CfgAmmo/Default/artilleryCharge": 1    ,
    "bin|config.bin/CfgAmmo/Default/autoSeekTarget": 0    ,
    "bin|config.bin/CfgAmmo/Default/visibleFire": 0    ,
    "bin|config.bin/CfgAmmo/Default/audibleFire": 0    ,
    "bin|config.bin/CfgAmmo/Default/shootDistraction": -1    ,
    "bin|config.bin/CfgAmmo/Default/visibleFireTime": 0    ,
    "bin|config.bin/CfgAmmo/Default/explosionTime": 0    ,
    "bin|config.bin/CfgAmmo/Default/fuseDistance": 0    ,
    "bin|config.bin/CfgAmmo/Default/icon": ""    ,
    "bin|config.bin/CfgAmmo/Default/submunitionAmmo": ""    ,
    "bin|config.bin/CfgAmmo/Default/explosionType": "explosive"    ,
    "bin|config.bin/CfgAmmo/Default/mineTrigger": "RangeTrigger"    ,
    "bin|config.bin/CfgAmmo/Default/mineBoundingTime": 3    ,
    "bin|config.bin/CfgAmmo/Default/mineBoundingDist": 3    ,
    "bin|config.bin/CfgAmmo/Default/mineInconspicuousness": 10    ,
    "bin|config.bin/CfgAmmo/Default/mineFloating": -1    ,
    "bin|config.bin/CfgAmmo/Default/mineDiveSpeed": 1    ,
    "bin|config.bin/CfgAmmo/Default/minePlaceDist": 0.5    ,
    "bin|config.bin/CfgAmmo/Default/suppressionRadiusBulletClose": -1    ,
    "bin|config.bin/CfgAmmo/Default/dangerRadiusBulletClose": -1    ,
    "bin|config.bin/CfgAmmo/Default/caliber": 1    ,
    "bin|config.bin/CfgAmmo/Default/whistleOnFire": 0    ,
    "bin|config.bin/CfgAmmo/Default/minDamageForCamShakeHit": 0.55,
    "bin|config.bin/CfgMagazines/rhs_mag_mk82/model": "\A3\Weapons_F\DynamicLoadout\PylonMissile_1x_Bomb_02_F.p3d",
    "bin|config.bin/CfgMagazines/rhs_mag_mk82/hardpoints": ["RHS_HP_BOMB_500","RHS_HP_LGB_500","RHS_HP_JDAM_500"],
    "bin|config.bin/CfgMagazines/rhs_mag_mk82/pylonWeapon": "rhs_weap_mk82",
    "bin|config.bin/CfgMagazines/rhs_mag_mk82/displayNameMFDFormat": "MK82\%1",
    "bin|config.bin/CfgMagazines/2Rnd_Mk82/author": "Bohemia Interactive",
    "bin|config.bin/CfgMagazines/2Rnd_Mk82/scope": 2,
    "bin|config.bin/CfgMagazines/2Rnd_Mk82/displayNameShort": "Bomb",
    "bin|config.bin/CfgMagazines/2Rnd_Mk82/initSpeed": 0,
    "bin|config.bin/CfgMagazines/2Rnd_Mk82/maxLeadSpeed": 25,
    "bin|config.bin/CfgMagazines/2Rnd_Mk82/nameSound": "missiles",
    "bin|config.bin/CfgMagazines/VehicleMagazine/type": 0,
    "bin|config.bin/CfgMagazines/VehicleMagazine/reloadAction": "",
    "bin|config.bin/CfgMagazines/VehicleMagazine/weaponPoolAvailable": 0,
    "bin|config.bin/CfgMagazines/CA_Magazine/value": 1,
    "bin|config.bin/CfgMagazines/CA_Magazine/picture": "",
    "bin|config.bin/CfgMagazines/CA_Magazine/modelSpecial": "",
    "bin|config.bin/CfgMagazines/CA_Magazine/useAction": 0,
    "bin|config.bin/CfgMagazines/CA_Magazine/useActionTitle": "",
    "bin|config.bin/CfgMagazines/CA_Magazine/selectionFireAnim": "zasleh",
    "bin|config.bin/CfgMagazines/CA_Magazine/mass": 8,
    "bin|config.bin/CfgMagazines/Default/simulation": "ProxyMagazines",
    "bin|config.bin/CfgMagazines/Default/weight": 0,
    "bin|config.bin/CfgMagazines/Default/maxThrowHoldTime": 2,
    "bin|config.bin/CfgMagazines/Default/minThrowIntensityCoef": 0.3,
    "bin|config.bin/CfgMagazines/Default/maxThrowIntensityCoef": 1.4,
    "bin|config.bin/CfgMagazines/Default/quickReload": 0
}