rhs_mag_762x51_M240_1200 = {
    "count": 1200,
    "scope": 2,
    "ammo": "rhs_ammo_762x51_M80A1EPR_Ball",
    "displayname": "7.62x51mm EPR",
    "displaynameshort": "M80A1 EPR",
    "namesound": "mgun",
    "initspeed": 838,
    "maxleadspeed": 100,
    "tracersevery": 5,
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}