rhs_mag_gbu12 = {
    "bin|config.bin/CfgMagazines/rhs_mag_gbu12/count": 1,
    "bin|config.bin/CfgMagazines/rhs_mag_gbu12/displayName": "GBU-12",
    "bin|config.bin/CfgMagazines/rhs_mag_gbu12/descriptionShort": "500lb Paveway II",
    "bin|config.bin/CfgMagazines/rhs_mag_gbu12/ammo": "rhs_ammo_gbu12"    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_gbu12/model": "\rhsusf\addons\rhsusf_airweapons\proxyammo\rhsusf_b_gbu12_fly"    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_gbu12/proxyShape": "\rhsusf\addons\rhsusf_airweapons\proxyammo\rhsusf_b_gbu12"    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_gbu12/initTime": 0.2    ,
    "bin|config.bin/CfgAmmo/Bomb_04_F/maverickWeaponIndexOffset": 8    ,
    "bin|config.bin/CfgAmmo/Bomb_04_F/SoundSetExplosion": ["BombsHeavy_Exp_SoundSet","BombsHeavy_Tail_SoundSet","Explosion_Debris_SoundSet"]    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/hit": 5000    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/indirectHit": 1100    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/indirectHitRange": 12    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/maneuvrability": 10    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/fuseDistance": 50    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/trackLead": 0.95    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/trackOversteer": 1    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/airFriction": 0.06    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/sideAirFriction": 0.12    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/aiAmmoUsageFlags": "128 + 512"    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/dangerRadiusHit": 1000    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/suppressionRadiusHit": 120    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/craterEffects": "BombCrater"    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/explosionEffects": "BombExplosion"    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/explosionSoundEffect": "DefaultExplosion"    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/explosionTime": 2    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/multiSoundHit": ["soundHit1",0.2,"soundHit2",0.2,"soundHit3",0.2,"soundHit4",0.2,"soundHit5",0.2]    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/whistleDist": 24    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/missileLockCone": 120    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/missileKeepLockedCone": 120    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/missileLockMaxDistance": 5000    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/missileLockMinDistance": 100    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/missileLockMaxSpeed": 30    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/autoSeekTarget": 1    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/lockSeekRadius": 500    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/weaponLockSystem": 4    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/cmImmunity": 0.3    ,
    "bin|config.bin/CfgAmmo/ammo_Bomb_LaserGuidedBase/flightProfiles": ["LoalAltitude"]    ,
    "bin|config.bin/CfgAmmo/LaserBombCore/cost": 20000    ,
    "bin|config.bin/CfgAmmo/LaserBombCore/irLock": 0    ,
    "bin|config.bin/CfgAmmo/LaserBombCore/laserLock": 1    ,
    "bin|config.bin/CfgAmmo/LaserBombCore/maxControlRange": 100000    ,
    "bin|config.bin/CfgAmmo/LaserBombCore/simulation": "shotMissile"    ,
    "bin|config.bin/CfgAmmo/LaserBombCore/maxSpeed": 100    ,
    "bin|config.bin/CfgAmmo/LaserBombCore/timeToLive": 120    ,
    "bin|config.bin/CfgAmmo/LaserBombCore/thrustTime": 0    ,
    "bin|config.bin/CfgAmmo/LaserBombCore/thrust": 0    ,
    "bin|config.bin/CfgAmmo/Default/access": 3    ,
    "bin|config.bin/CfgAmmo/Default/underwaterHitRangeCoef": 1    ,
    "bin|config.bin/CfgAmmo/Default/typicalSpeed": 900    ,
    "bin|config.bin/CfgAmmo/Default/explosionForceCoef": 1    ,
    "bin|config.bin/CfgAmmo/Default/isCraterOriented": 0    ,
    "bin|config.bin/CfgAmmo/Default/craterShape": ""    ,
    "bin|config.bin/CfgAmmo/Default/weaponType": "Default"    ,
    "bin|config.bin/CfgAmmo/Default/animated": 0    ,
    "bin|config.bin/CfgAmmo/Default/shadow": 0    ,
    "bin|config.bin/CfgAmmo/Default/cartridge": ""    ,
    "bin|config.bin/CfgAmmo/Default/simulationStep": 0.05    ,
    "bin|config.bin/CfgAmmo/Default/tracerColor": [0.7,0.7,0.5,0.04]    ,
    "bin|config.bin/CfgAmmo/Default/tracerColorR": [0.7,0.7,0.5,0.04]    ,
    "bin|config.bin/CfgAmmo/Default/supersonicCrackNear": ["",1,1]    ,
    "bin|config.bin/CfgAmmo/Default/supersonicCrackFar": ["",1,1]    ,
    "bin|config.bin/CfgAmmo/Default/hitGroundSoft": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitGroundHard": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitMan": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitArmor": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitIron": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitBuilding": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitFoliage": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitWood": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitGlass": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitGlassArmored": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitConcrete": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitRubber": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitPlastic": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitDefault": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitMetal": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitMetalplate": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitTyre": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitWater": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGroundSoft": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGroundHard": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactMan": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactIron": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactArmor": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactBuilding": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactFoliage": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactWood": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGlass": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGlassArmored": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactConcrete": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactRubber": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactPlastic": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactDefault": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactMetal": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactMetalplate": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactTyre": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactWater": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/grenadeFireSound": []    ,
    "bin|config.bin/CfgAmmo/Default/grenadeBurningSound": []    ,
    "bin|config.bin/CfgAmmo/Default/deflecting": 0    ,
    "bin|config.bin/CfgAmmo/Default/deflectionSlowDown": 0.8    ,
    "bin|config.bin/CfgAmmo/Default/explosive": 1    ,
    "bin|config.bin/CfgAmmo/Default/craterWaterEffects": "ImpactEffectsWater"    ,
    "bin|config.bin/CfgAmmo/Default/effectsMissile": "ExplosionEffects"    ,
    "bin|config.bin/CfgAmmo/Default/effectsMissileInit": ""    ,
    "bin|config.bin/CfgAmmo/Default/effectsSmoke": "SmokeShellWhite"    ,
    "bin|config.bin/CfgAmmo/Default/effectsFire": "CannonFire"    ,
    "bin|config.bin/CfgAmmo/Default/effectFlare": "FlareShell"    ,
    "bin|config.bin/CfgAmmo/Default/effectFly": ""    ,
    "bin|config.bin/CfgAmmo/Default/mineJumpEffects": ""    ,
    "bin|config.bin/CfgAmmo/Default/waterEffectOffset": 0.45    ,
    "bin|config.bin/CfgAmmo/Default/directionalExplosion": 0    ,
    "bin|config.bin/CfgAmmo/Default/explosionAngle": 60    ,
    "bin|config.bin/CfgAmmo/Default/explosionDir": "explosionDir"    ,
    "bin|config.bin/CfgAmmo/Default/explosionPos": "explosionPos"    ,
    "bin|config.bin/CfgAmmo/Default/explosionEffectsDir": "explosionDir"    ,
    "bin|config.bin/CfgAmmo/Default/minimumSafeZone": 0.1    ,
    "bin|config.bin/CfgAmmo/Default/minTimeToLive": 0    ,
    "bin|config.bin/CfgAmmo/Default/airLock": 0    ,
    "bin|config.bin/CfgAmmo/Default/nvLock": 0    ,
    "bin|config.bin/CfgAmmo/Default/artilleryLock": 0    ,
    "bin|config.bin/CfgAmmo/Default/hitOnWater": 0    ,
    "bin|config.bin/CfgAmmo/Default/manualControl": 0    ,
    "bin|config.bin/CfgAmmo/Default/lockType": 0    ,
    "bin|config.bin/CfgAmmo/Default/artilleryDispersion": 1    ,
    "bin|config.bin/CfgAmmo/Default/artilleryCharge": 1    ,
    "bin|config.bin/CfgAmmo/Default/visibleFire": 0    ,
    "bin|config.bin/CfgAmmo/Default/audibleFire": 0    ,
    "bin|config.bin/CfgAmmo/Default/shootDistraction": -1    ,
    "bin|config.bin/CfgAmmo/Default/visibleFireTime": 0    ,
    "bin|config.bin/CfgAmmo/Default/icon": ""    ,
    "bin|config.bin/CfgAmmo/Default/submunitionAmmo": ""    ,
    "bin|config.bin/CfgAmmo/Default/explosionType": "explosive"    ,
    "bin|config.bin/CfgAmmo/Default/mineTrigger": "RangeTrigger"    ,
    "bin|config.bin/CfgAmmo/Default/mineBoundingTime": 3    ,
    "bin|config.bin/CfgAmmo/Default/mineBoundingDist": 3    ,
    "bin|config.bin/CfgAmmo/Default/mineInconspicuousness": 10    ,
    "bin|config.bin/CfgAmmo/Default/mineFloating": -1    ,
    "bin|config.bin/CfgAmmo/Default/mineDiveSpeed": 1    ,
    "bin|config.bin/CfgAmmo/Default/minePlaceDist": 0.5    ,
    "bin|config.bin/CfgAmmo/Default/suppressionRadiusBulletClose": -1    ,
    "bin|config.bin/CfgAmmo/Default/dangerRadiusBulletClose": -1    ,
    "bin|config.bin/CfgAmmo/Default/caliber": 1    ,
    "bin|config.bin/CfgAmmo/Default/whistleOnFire": 0    ,
    "bin|config.bin/CfgAmmo/Default/minDamageForCamShakeHit": 0.55,
    "bin|config.bin/CfgMagazines/rhs_mag_gbu12/model": "\A3\Weapons_F\DynamicLoadout\PylonMissile_1x_Bomb_02_F.p3d",
    "bin|config.bin/CfgMagazines/rhs_mag_gbu12/hardpoints": ["RHS_HP_LGB_500"],
    "bin|config.bin/CfgMagazines/rhs_mag_gbu12/pylonWeapon": "rhs_weap_gbu12",
    "bin|config.bin/CfgMagazines/rhs_mag_gbu12/displayNameMFDFormat": "GBU12\%1",
    "bin|config.bin/CfgMagazines/4Rnd_Bomb_04_F/author": "Bohemia Interactive",
    "bin|config.bin/CfgMagazines/4Rnd_Bomb_04_F/scope": 2,
    "bin|config.bin/CfgMagazines/4Rnd_Bomb_04_F/displayNameShort": "Bomb",
    "bin|config.bin/CfgMagazines/4Rnd_Bomb_04_F/initSpeed": 0,
    "bin|config.bin/CfgMagazines/4Rnd_Bomb_04_F/maxLeadSpeed": 25,
    "bin|config.bin/CfgMagazines/4Rnd_Bomb_04_F/nameSound": "cannon",
    "bin|config.bin/CfgMagazines/VehicleMagazine/type": 0,
    "bin|config.bin/CfgMagazines/VehicleMagazine/reloadAction": "",
    "bin|config.bin/CfgMagazines/VehicleMagazine/weaponPoolAvailable": 0,
    "bin|config.bin/CfgMagazines/CA_Magazine/value": 1,
    "bin|config.bin/CfgMagazines/CA_Magazine/picture": "",
    "bin|config.bin/CfgMagazines/CA_Magazine/modelSpecial": "",
    "bin|config.bin/CfgMagazines/CA_Magazine/useAction": 0,
    "bin|config.bin/CfgMagazines/CA_Magazine/useActionTitle": "",
    "bin|config.bin/CfgMagazines/CA_Magazine/selectionFireAnim": "zasleh",
    "bin|config.bin/CfgMagazines/CA_Magazine/mass": 8,
    "bin|config.bin/CfgMagazines/Default/simulation": "ProxyMagazines",
    "bin|config.bin/CfgMagazines/Default/weight": 0,
    "bin|config.bin/CfgMagazines/Default/maxThrowHoldTime": 2,
    "bin|config.bin/CfgMagazines/Default/minThrowIntensityCoef": 0.3,
    "bin|config.bin/CfgMagazines/Default/maxThrowIntensityCoef": 1.4,
    "bin|config.bin/CfgMagazines/Default/quickReload": 0
}