Rhs_mag_4Rnd_stinger = {
    "scope": 2,
    "ammo": "rhs_ammo_fim92_missile",
    "displayname": "FIM-92F Stinger",
    "displaynameshort": "FIM-92F",
    "initspeed": 40,
    "maxLeadSpeed": 850,
    "nameSound": "missiles",
    "count": 4,
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}