rhs_mag_2Rnd_TOW2A = {
    "scope": 2,
    "ammo": "rhs_ammo_TOW2A_AT",
    "displayname": "BGM-71E TOW-2A",
    "displaynameshort": "BGM-71E",
    "nameSound": "missiles",
    "count": 2,
    "initSpeed": 55.71,
    "maxleadspeed": 130,
    "rhs_magazineIndex": 4,
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}