RHS_mag_AZP23_100 = {
    "count": 100,
    "scope": 2,
    "displayName": "AZP-23",
    "ammo": "RHS_ammo_23mm_AA",
    "initSpeed": 980,
    "maxLeadSpeed": 650,
    "nameSound": "cannon",
    "tracersEvery": 1,
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "displayNameShort": "",
    "weight": 0,
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}