rhs_mag_1150Rnd_30x173_mixed = {
    "count": 1150,
    # Ammo: CfgMagazines|rhs_mag_1150Rnd_30x173_mixed|ammo [Indent level: 1],
    "ammo": {
        "ammo": "rhs_ammo_30x173mm_GAU8_mixed",
        "hit": 180,
        "indirecthit": 4,
        "indirecthitrange": 8,
        "caliber": 5,
        "explosive": 0.4,
        "airlock": 1,
        "deflecting": 5,
        "airfriction": -0.00036,
        "typicalspeed": 960,
        "visiblefire": 32,
        "audiblefire": 250,
        "visiblefiretime": 3,
        "fusedistance": 10,
        "dangerradiusbulletclose": 20,
        "dangerradiushit": 60,
        "suppressionradiusbulletclose": 12,
        "suppressionradiushit": 24,
        "cost": 20,
        "allowagainstinfantry": 1,
        "aiammousageflags": "64 + 128 + 512",
        "weapontype": "cannon",
        "simulation": "shotSubmunitions",
        "triggertime": 0.01,
        "submunitionammo": ["rhs_ammo_PGU14B_API",0.8,"rhs_ammo_PGU13B_HE",0.2],
        "model": "A3|Weapons_f|empty",
        # Class: CfgAmmo|rhs_ammo_30x173mm_GAU8_mixed|CamShakeExplode [Indent level: 1],
        "camshakeexplode": {
            "power": 6,
            "duration": 1,
            "frequency": 20,
            "distance": 83.8178
        },
        # Class: CfgAmmo|rhs_ammo_30x173mm_GAU8_mixed|CamShakeHit [Indent level: 1],
        "camshakehit": {
            "power": 30,
            "duration": 0.4,
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo|rhs_ammo_30x173mm_GAU8_mixed|CamShakeFire [Indent level: 1],
        "camshakefire": {
            "power": 2.34035,
            "duration": 1,
            "frequency": 20,
            "distance": 43.8178
        },
        # Class: CfgAmmo|rhs_ammo_30x173mm_GAU8_mixed|CamShakePlayerFire [Indent level: 1],
        "camshakeplayerfire": {
            "power": 30,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "soundfakefall1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_2.ogg",2.5,1,750],
        "soundfakefall2": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_3.ogg",2.5,1,750],
        "soundfakefall3": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_4.ogg",2.5,1,750],
        "soundfakefall4": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_5.ogg",2.5,1,750],
        "soundfakefall5": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_6.ogg",2.5,1,750],
        "soundfakefall6": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_1.ogg",2.5,1,750],
        "soundfakefall": ["soundfakefall1",0.166,"soundfakefall2",0.166,"soundfakefall3",0.166,"soundfakefall4",0.166,"soundfakefall5",0.166,"soundfakefall6",0.166],
        "simulationstep": 0.05,
        "timetolive": 180,
        "soundhit": ["",316.228,1],
        "soundfly": ["",0.0316228,4],
        "hitonwater": 1,
        "artillerylock": 1,
        "access": 3,
        "underwaterhitrangecoef": 1,
        "explosionforcecoef": 1,
        "iscrateroriented": 0,
        "proxyshape": "",
        "cratershape": "",
        "animated": 0,
        "shadow": 0,
        "maxspeed": 0,
        "cartridge": "",
        "tracercolor": [0.7,0.7,0.5,0.04],
        "tracercolorr": [0.7,0.7,0.5,0.04],
        "soundengine": ["",1,1],
        "supersoniccracknear": ["",1,1],
        "supersoniccrackfar": ["",1,1],
        "soundfall": ["",1,1],
        "hitgroundsoft": ["soundHit",1],
        "hitgroundhard": ["soundHit",1],
        "hitman": ["soundHit",1],
        "hitarmor": ["soundHit",1],
        "hitiron": ["soundHit",1],
        "hitbuilding": ["soundHit",1],
        "hitfoliage": ["soundHit",1],
        "hitwood": ["soundHit",1],
        "hitglass": ["soundHit",1],
        "hitglassarmored": ["soundHit",1],
        "hitconcrete": ["soundHit",1],
        "hitrubber": ["soundHit",1],
        "hitplastic": ["soundHit",1],
        "hitdefault": ["soundHit",1],
        "hitmetal": ["soundHit",1],
        "hitmetalplate": ["soundHit",1],
        "hittyre": ["soundHit",1],
        "hitwater": ["soundHit",1],
        "soundimpact": ["",1,1],
        "impactgroundsoft": ["soundImpact",1],
        "impactgroundhard": ["soundImpact",1],
        "impactman": ["soundImpact",1],
        "impactiron": ["soundImpact",1],
        "impactarmor": ["soundImpact",1],
        "impactbuilding": ["soundImpact",1],
        "impactfoliage": ["soundImpact",1],
        "impactwood": ["soundImpact",1],
        "impactglass": ["soundImpact",1],
        "impactglassarmored": ["soundImpact",1],
        "impactconcrete": ["soundImpact",1],
        "impactrubber": ["soundImpact",1],
        "impactplastic": ["soundImpact",1],
        "impactdefault": ["soundImpact",1],
        "impactmetal": ["soundImpact",1],
        "impactmetalplate": ["soundImpact",1],
        "impacttyre": ["soundImpact",1],
        "impactwater": ["soundImpact",1],
        "grenadefiresound": [],
        "grenadeburningsound": [],
        "deflectionslowdown": 0.8,
        "explosioneffects": "ExplosionEffects",
        "cratereffects": "ImpactEffectsMedium",
        "craterwatereffects": "ImpactEffectsWater",
        "effectsmissile": "ExplosionEffects",
        "effectsmissileinit": "",
        "effectssmoke": "SmokeShellWhite",
        "effectsfire": "CannonFire",
        "effectflare": "FlareShell",
        "effectfly": "",
        "minejumpeffects": "",
        "watereffectoffset": 0.45,
        "directionalexplosion": 0,
        "explosionangle": 60,
        "explosiondir": "explosionDir",
        "explosionpos": "explosionPos",
        "explosioneffectsdir": "explosionDir",
        "minimumsafezone": 0.1,
        "soundtrigger": [],
        "soundactivation": [],
        "sounddeactivation": [],
        "explosionsoundeffect": "",
        "mintimetolive": 0,
        "irlock": 0,
        "laserlock": 0,
        "nvlock": 0,
        "lockseekradius": 100,
        "manualcontrol": 0,
        "maxcontrolrange": 350,
        "maneuvrability": 1,
        "tracklead": 1,
        "trackoversteer": 1,
        "missilelockcone": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "locktype": 0,
        "maverickweaponindexoffset": 0,
        "sideairfriction": 1,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "autoseektarget": 0,
        "shootdistraction": -1,
        "explosiontime": 0,
        "inittime": 0,
        "thrusttime": 1.5,
        "thrust": 210,
        "icon": "",
        "explosiontype": "explosive",
        "minetrigger": "RangeTrigger",
        "mineboundingtime": 3,
        "mineboundingdist": 3,
        "mineinconspicuousness": 10,
        "minefloating": -1,
        "minedivespeed": 1,
        "mineplacedist": 0.5,
        # Class: CfgAmmo|Default|HitEffects [Indent level: 1],
        "hiteffects": {
            "vehicle": "ImpactMetal",
            "object": "ImpactConcrete"
        },
        "whistledist": 0,
        "whistleonfire": 0,
        # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
        "nvgmarkers": {
        },
        "mindamageforcamshakehit": 0.55,
        # Class: CfgAmmo|Default|EventHandlers [Indent level: 1],
        "eventhandlers": {
        },
    },
    "eventhandlers": "rhs_ammo_30x173mm_GAU8_mixed",
    "tracersevery": 0,
    "author": "Bohemia Interactive",
    "scope": 2,
    "displaynameshort": "",
    "initspeed": 1120,
    "maxleadspeed": 83.3333,
    "namesound": "cannon",
    "muzzleimpulsefactor": [-0.1,1],
    "type": 0,
    "reloadaction": "",
    "weaponpoolavailable": 0,
    "value": 1,
    "displayname": "",
    "model": "A3|weapons_F|ammo|mag_univ.p3d",
    "picture": "",
    "modelspecial": "",
    "useaction": 0,
    "useactiontitle": "",
    "selectionfireanim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    # Class: CfgMagazines|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "descriptionshort": "",
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0,
}