rhs_mag_230Rnd_25mm_M242_HEI = {
    "scope": 2,
    "ammo": "RHS_ammo_M792_HEI",
    "count": 230,
    "displayname": "25x137mm M792 HEI-T",
    "displaynameshort": "M792 HEI-T",
    "initspeed": 1100,
    "lastroundstracer": 4,
    "maxleadspeed": 100,
    "namesound": "cannon",
    "tracersevery": 1,
    "author": "Bohemia Interactive",
    "displayNameMFDFormat": "ОФ",
    "weight": 126,
    "muzzleImpulseFactor": [1,4],
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}