rhs_mag_70Rnd_25mm_M242_APFSDS = {
    "ammo": "RHS_ammo_M919_APFSDS",
    "count": 70,
    "displayname": "25x137mm M919 APFSDS-T",
    "displaynameshort": "M919 APFSDS-T",
    "initspeed": 1385,
    "author": "Bohemia Interactive",
    "tracersEvery": 1,
    "muzzleImpulseFactor": [0.5,2],
    "scope": 2,
    "maxLeadSpeed": 83.3333,
    "nameSound": "cannon",
    "weight": 126,
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}