rhs_mag_M829A1 = {
    "displayName": "M829A1 APFSDS-T",
    "displayNameShort": "M829A1",
    "ammo": "rhs_ammo_M829A1",
    "count": 28,
    "initSpeed": 1575,
    "nameSound": "sabot",
    "rhs_magazineIndex": 1,
    "scope": 2,
    "muzzleImpulseFactor": ["9*0.1",9],
    "maxLeadSpeed": 20,
    "tracersEvery": 1,
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}