rhs_mag_1150Rnd_30x173_mixed = {
    "bin|config.bin/CfgMagazines/rhs_mag_1150Rnd_30x173_mixed/count": 1150,
    "bin|config.bin/CfgMagazines/rhs_mag_1150Rnd_30x173_mixed/ammo": "rhs_ammo_30x173mm_GAU8_mixed"    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/hit": 180    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/indirectHit": 4    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/indirectHitRange": 8    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/caliber": 5    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/explosive": 0.4    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/airlock": 1    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/deflecting": 5    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/airFriction": -0.00036    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/typicalSpeed": 960    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/visibleFire": 32    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/audibleFire": 250    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/visibleFireTime": 3    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/fuseDistance": 10    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/dangerRadiusBulletClose": 20    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/dangerRadiusHit": 60    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/suppressionRadiusBulletClose": 12    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/suppressionRadiusHit": 24    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/cost": 20    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/allowAgainstInfantry": 1    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/aiAmmoUsageFlags": "64 + 128 + 512"    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/weaponType": "cannon"    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/simulation": "shotSubmunitions"    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/triggerTime": 0.01    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/submunitionAmmo": ["rhs_ammo_PGU14B_API",0.8,"rhs_ammo_PGU13B_HE",0.2]    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_30x173mm_GAU8_mixed/model": "\A3\Weapons_f\empty"    ,
    "bin|config.bin/CfgAmmo/SubmunitionCore/simulationStep": 0.05    ,
    "bin|config.bin/CfgAmmo/SubmunitionCore/timeToLive": 180    ,
    "bin|config.bin/CfgAmmo/SubmunitionCore/hitOnWater": 1    ,
    "bin|config.bin/CfgAmmo/SubmunitionCore/artilleryLock": 1    ,
    "bin|config.bin/CfgAmmo/Default/access": 3    ,
    "bin|config.bin/CfgAmmo/Default/underwaterHitRangeCoef": 1    ,
    "bin|config.bin/CfgAmmo/Default/explosionForceCoef": 1    ,
    "bin|config.bin/CfgAmmo/Default/isCraterOriented": 0    ,
    "bin|config.bin/CfgAmmo/Default/proxyShape": ""    ,
    "bin|config.bin/CfgAmmo/Default/craterShape": ""    ,
    "bin|config.bin/CfgAmmo/Default/animated": 0    ,
    "bin|config.bin/CfgAmmo/Default/shadow": 0    ,
    "bin|config.bin/CfgAmmo/Default/maxSpeed": 0    ,
    "bin|config.bin/CfgAmmo/Default/cartridge": ""    ,
    "bin|config.bin/CfgAmmo/Default/tracerColor": [0.7,0.7,0.5,0.04]    ,
    "bin|config.bin/CfgAmmo/Default/tracerColorR": [0.7,0.7,0.5,0.04]    ,
    "bin|config.bin/CfgAmmo/Default/supersonicCrackNear": ["",1,1]    ,
    "bin|config.bin/CfgAmmo/Default/supersonicCrackFar": ["",1,1]    ,
    "bin|config.bin/CfgAmmo/Default/hitGroundSoft": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitGroundHard": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitMan": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitArmor": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitIron": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitBuilding": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitFoliage": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitWood": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitGlass": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitGlassArmored": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitConcrete": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitRubber": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitPlastic": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitDefault": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitMetal": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitMetalplate": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitTyre": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitWater": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGroundSoft": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGroundHard": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactMan": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactIron": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactArmor": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactBuilding": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactFoliage": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactWood": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGlass": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGlassArmored": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactConcrete": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactRubber": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactPlastic": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactDefault": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactMetal": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactMetalplate": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactTyre": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactWater": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/grenadeFireSound": []    ,
    "bin|config.bin/CfgAmmo/Default/grenadeBurningSound": []    ,
    "bin|config.bin/CfgAmmo/Default/deflectionSlowDown": 0.8    ,
    "bin|config.bin/CfgAmmo/Default/explosionEffects": "ExplosionEffects"    ,
    "bin|config.bin/CfgAmmo/Default/craterEffects": "ImpactEffectsMedium"    ,
    "bin|config.bin/CfgAmmo/Default/craterWaterEffects": "ImpactEffectsWater"    ,
    "bin|config.bin/CfgAmmo/Default/effectsMissile": "ExplosionEffects"    ,
    "bin|config.bin/CfgAmmo/Default/effectsMissileInit": ""    ,
    "bin|config.bin/CfgAmmo/Default/effectsSmoke": "SmokeShellWhite"    ,
    "bin|config.bin/CfgAmmo/Default/effectsFire": "CannonFire"    ,
    "bin|config.bin/CfgAmmo/Default/effectFlare": "FlareShell"    ,
    "bin|config.bin/CfgAmmo/Default/effectFly": ""    ,
    "bin|config.bin/CfgAmmo/Default/mineJumpEffects": ""    ,
    "bin|config.bin/CfgAmmo/Default/waterEffectOffset": 0.45    ,
    "bin|config.bin/CfgAmmo/Default/directionalExplosion": 0    ,
    "bin|config.bin/CfgAmmo/Default/explosionAngle": 60    ,
    "bin|config.bin/CfgAmmo/Default/explosionDir": "explosionDir"    ,
    "bin|config.bin/CfgAmmo/Default/explosionPos": "explosionPos"    ,
    "bin|config.bin/CfgAmmo/Default/explosionEffectsDir": "explosionDir"    ,
    "bin|config.bin/CfgAmmo/Default/minimumSafeZone": 0.1    ,
    "bin|config.bin/CfgAmmo/Default/explosionSoundEffect": ""    ,
    "bin|config.bin/CfgAmmo/Default/minTimeToLive": 0    ,
    "bin|config.bin/CfgAmmo/Default/irLock": 0    ,
    "bin|config.bin/CfgAmmo/Default/laserLock": 0    ,
    "bin|config.bin/CfgAmmo/Default/nvLock": 0    ,
    "bin|config.bin/CfgAmmo/Default/lockSeekRadius": 100    ,
    "bin|config.bin/CfgAmmo/Default/manualControl": 0    ,
    "bin|config.bin/CfgAmmo/Default/maxControlRange": 350    ,
    "bin|config.bin/CfgAmmo/Default/maneuvrability": 1    ,
    "bin|config.bin/CfgAmmo/Default/trackLead": 1    ,
    "bin|config.bin/CfgAmmo/Default/trackOversteer": 1    ,
    "bin|config.bin/CfgAmmo/Default/missileLockCone": 0    ,
    "bin|config.bin/CfgAmmo/Default/weaponLockSystem": 0    ,
    "bin|config.bin/CfgAmmo/Default/cmImmunity": 1    ,
    "bin|config.bin/CfgAmmo/Default/lockType": 0    ,
    "bin|config.bin/CfgAmmo/Default/maverickweaponIndexOffset": 0    ,
    "bin|config.bin/CfgAmmo/Default/sideAirFriction": 1    ,
    "bin|config.bin/CfgAmmo/Default/artilleryDispersion": 1    ,
    "bin|config.bin/CfgAmmo/Default/artilleryCharge": 1    ,
    "bin|config.bin/CfgAmmo/Default/autoSeekTarget": 0    ,
    "bin|config.bin/CfgAmmo/Default/shootDistraction": -1    ,
    "bin|config.bin/CfgAmmo/Default/explosionTime": 0    ,
    "bin|config.bin/CfgAmmo/Default/initTime": 0    ,
    "bin|config.bin/CfgAmmo/Default/thrustTime": 1.5    ,
    "bin|config.bin/CfgAmmo/Default/thrust": 210    ,
    "bin|config.bin/CfgAmmo/Default/icon": ""    ,
    "bin|config.bin/CfgAmmo/Default/explosionType": "explosive"    ,
    "bin|config.bin/CfgAmmo/Default/mineTrigger": "RangeTrigger"    ,
    "bin|config.bin/CfgAmmo/Default/mineBoundingTime": 3    ,
    "bin|config.bin/CfgAmmo/Default/mineBoundingDist": 3    ,
    "bin|config.bin/CfgAmmo/Default/mineInconspicuousness": 10    ,
    "bin|config.bin/CfgAmmo/Default/mineFloating": -1    ,
    "bin|config.bin/CfgAmmo/Default/mineDiveSpeed": 1    ,
    "bin|config.bin/CfgAmmo/Default/minePlaceDist": 0.5    ,
    "bin|config.bin/CfgAmmo/Default/whistleDist": 0    ,
    "bin|config.bin/CfgAmmo/Default/whistleOnFire": 0    ,
    "bin|config.bin/CfgAmmo/Default/minDamageForCamShakeHit": 0.55,
    "bin|config.bin/CfgMagazines/rhs_mag_1150Rnd_30x173_mixed/tracersEvery": 0,
    "bin|config.bin/CfgMagazines/1000Rnd_Gatling_30mm_Plane_CAS_01_F/author": "Bohemia Interactive",
    "bin|config.bin/CfgMagazines/1000Rnd_Gatling_30mm_Plane_CAS_01_F/scope": 2,
    "bin|config.bin/CfgMagazines/1000Rnd_Gatling_30mm_Plane_CAS_01_F/displayNameShort": "",
    "bin|config.bin/CfgMagazines/1000Rnd_Gatling_30mm_Plane_CAS_01_F/initSpeed": 1120,
    "bin|config.bin/CfgMagazines/1000Rnd_Gatling_30mm_Plane_CAS_01_F/maxLeadSpeed": 83.3333,
    "bin|config.bin/CfgMagazines/1000Rnd_Gatling_30mm_Plane_CAS_01_F/nameSound": "cannon",
    "bin|config.bin/CfgMagazines/1000Rnd_Gatling_30mm_Plane_CAS_01_F/muzzleImpulseFactor": [-0.1,1],
    "bin|config.bin/CfgMagazines/VehicleMagazine/type": 0,
    "bin|config.bin/CfgMagazines/VehicleMagazine/reloadAction": "",
    "bin|config.bin/CfgMagazines/VehicleMagazine/weaponPoolAvailable": 0,
    "bin|config.bin/CfgMagazines/CA_Magazine/value": 1,
    "bin|config.bin/CfgMagazines/CA_Magazine/displayName": "",
    "bin|config.bin/CfgMagazines/CA_Magazine/model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "bin|config.bin/CfgMagazines/CA_Magazine/picture": "",
    "bin|config.bin/CfgMagazines/CA_Magazine/modelSpecial": "",
    "bin|config.bin/CfgMagazines/CA_Magazine/useAction": 0,
    "bin|config.bin/CfgMagazines/CA_Magazine/useActionTitle": "",
    "bin|config.bin/CfgMagazines/CA_Magazine/selectionFireAnim": "zasleh",
    "bin|config.bin/CfgMagazines/CA_Magazine/mass": 8,
    "bin|config.bin/CfgMagazines/Default/simulation": "ProxyMagazines",
    "bin|config.bin/CfgMagazines/Default/weight": 0,
    "bin|config.bin/CfgMagazines/Default/descriptionShort": "",
    "bin|config.bin/CfgMagazines/Default/maxThrowHoldTime": 2,
    "bin|config.bin/CfgMagazines/Default/minThrowIntensityCoef": 0.3,
    "bin|config.bin/CfgMagazines/Default/maxThrowIntensityCoef": 1.4,
    "bin|config.bin/CfgMagazines/Default/quickReload": 0
}