rhs_mag_1150Rnd_30x173_mixed = {
    "count": 1150,
    # Ammo: rhs_ammo_30x173mm_GAU8_mixed,
    "ammo": {
        "ammo": "rhs_ammo_30x173mm_GAU8_mixed",
        "hit": 180,
        "indirectHit": 4,
        "indirectHitRange": 8,
        "caliber": 5,
        "explosive": 0.4,
        "airlock": 1,
        "deflecting": 5,
        "airFriction": -0.00036,
        "typicalSpeed": 960,
        "visibleFire": 32,
        "audibleFire": 250,
        "visibleFireTime": 3,
        "fuseDistance": 10,
        "dangerRadiusBulletClose": 20,
        "dangerRadiusHit": 60,
        "suppressionRadiusBulletClose": 12,
        "suppressionRadiusHit": 24,
        "cost": 20,
        "allowAgainstInfantry": 1,
        "aiAmmoUsageFlags": "64 + 128 + 512",
        "weaponType": "cannon",
        "simulation": "shotSubmunitions",
        "triggerTime": 0.01,
        "submunitionAmmo": ["rhs_ammo_PGU14B_API",0.8,"rhs_ammo_PGU13B_HE",0.2],
        "model": "A3|Weapons_f|empty",
        # Class: CfgAmmo\rhs_ammo_30x173mm_GAU8_mixed\CamShakeExplode [Indent level: 1],
        "CamShakeExplode": {
            "power": 6,
            "duration": 1,
            "frequency": 20,
            "distance": 83.8178
        },
        # Class: CfgAmmo\rhs_ammo_30x173mm_GAU8_mixed\CamShakeHit [Indent level: 1],
        "CamShakeHit": {
            "power": 30,
            "duration": 0.4,
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo\rhs_ammo_30x173mm_GAU8_mixed\CamShakeFire [Indent level: 1],
        "CamShakeFire": {
            "power": 2.34035,
            "duration": 1,
            "frequency": 20,
            "distance": 43.8178
        },
        # Class: CfgAmmo\rhs_ammo_30x173mm_GAU8_mixed\CamShakePlayerFire [Indent level: 1],
        "CamShakePlayerFire": {
            "power": 30,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "soundfakefall1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_2.ogg",2.5,1,750],
        "soundfakefall2": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_3.ogg",2.5,1,750],
        "soundfakefall3": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_4.ogg",2.5,1,750],
        "soundfakefall4": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_5.ogg",2.5,1,750],
        "soundfakefall5": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_6.ogg",2.5,1,750],
        "soundfakefall6": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_1.ogg",2.5,1,750],
        "soundfakefall": ["soundfakefall1",0.166,"soundfakefall2",0.166,"soundfakefall3",0.166,"soundfakefall4",0.166,"soundfakefall5",0.166,"soundfakefall6",0.166],
        "ACE_damageType": "explosive",
        "simulationStep": 0.05,
        "timeToLive": 180,
        "soundHit": ["",316.228,1],
        "soundFly": ["",0.0316228,4],
        "hitOnWater": 1,
        "artilleryLock": 1,
        "access": 3,
        "underwaterHitRangeCoef": 1,
        "explosionForceCoef": 1,
        "isCraterOriented": 0,
        "proxyShape": "",
        "craterShape": "",
        "animated": 0,
        "shadow": 0,
        "maxSpeed": 0,
        "cartridge": "",
        "tracerColor": [0.7,0.7,0.5,0.04],
        "tracerColorR": [0.7,0.7,0.5,0.04],
        "soundEngine": ["",1,1],
        "supersonicCrackNear": ["",1,1],
        "supersonicCrackFar": ["",1,1],
        "soundFall": ["",1,1],
        "hitGroundSoft": ["soundHit",1],
        "hitGroundHard": ["soundHit",1],
        "hitMan": ["soundHit",1],
        "hitArmor": ["soundHit",1],
        "hitIron": ["soundHit",1],
        "hitBuilding": ["soundHit",1],
        "hitFoliage": ["soundHit",1],
        "hitWood": ["soundHit",1],
        "hitGlass": ["soundHit",1],
        "hitGlassArmored": ["soundHit",1],
        "hitConcrete": ["soundHit",1],
        "hitRubber": ["soundHit",1],
        "hitPlastic": ["soundHit",1],
        "hitDefault": ["soundHit",1],
        "hitMetal": ["soundHit",1],
        "hitMetalplate": ["soundHit",1],
        "hitTyre": ["soundHit",1],
        "hitWater": ["soundHit",1],
        "soundImpact": ["",1,1],
        "impactGroundSoft": ["soundImpact",1],
        "impactGroundHard": ["soundImpact",1],
        "impactMan": ["soundImpact",1],
        "impactIron": ["soundImpact",1],
        "impactArmor": ["soundImpact",1],
        "impactBuilding": ["soundImpact",1],
        "impactFoliage": ["soundImpact",1],
        "impactWood": ["soundImpact",1],
        "impactGlass": ["soundImpact",1],
        "impactGlassArmored": ["soundImpact",1],
        "impactConcrete": ["soundImpact",1],
        "impactRubber": ["soundImpact",1],
        "impactPlastic": ["soundImpact",1],
        "impactDefault": ["soundImpact",1],
        "impactMetal": ["soundImpact",1],
        "impactMetalplate": ["soundImpact",1],
        "impactTyre": ["soundImpact",1],
        "impactWater": ["soundImpact",1],
        "grenadeFireSound": [],
        "grenadeBurningSound": [],
        "deflectionSlowDown": 0.8,
        "explosionEffects": "ExplosionEffects",
        "craterEffects": "ImpactEffectsMedium",
        "craterWaterEffects": "ImpactEffectsWater",
        "effectsMissile": "ExplosionEffects",
        "effectsMissileInit": "",
        "effectsSmoke": "SmokeShellWhite",
        "effectsFire": "CannonFire",
        "effectFlare": "FlareShell",
        "effectFly": "",
        "mineJumpEffects": "",
        "waterEffectOffset": 0.45,
        "directionalExplosion": 0,
        "explosionAngle": 60,
        "explosionDir": "explosionDir",
        "explosionPos": "explosionPos",
        "explosionEffectsDir": "explosionDir",
        "minimumSafeZone": 0.1,
        "soundTrigger": [],
        "soundActivation": [],
        "soundDeactivation": [],
        "explosionSoundEffect": "",
        "minTimeToLive": 0,
        "irLock": 0,
        "laserLock": 0,
        "nvLock": 0,
        "lockSeekRadius": 100,
        "manualControl": 0,
        "maxControlRange": 350,
        "maneuvrability": 1,
        "trackLead": 1,
        "trackOversteer": 1,
        "missileLockCone": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "lockType": 0,
        "maverickweaponIndexOffset": 0,
        "sideAirFriction": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "autoSeekTarget": 0,
        "shootDistraction": -1,
        "explosionTime": 0,
        "initTime": 0,
        "thrustTime": 1.5,
        "thrust": 210,
        "icon": "",
        "explosionType": "explosive",
        "mineTrigger": "RangeTrigger",
        "mineBoundingTime": 3,
        "mineBoundingDist": 3,
        "mineInconspicuousness": 10,
        "mineFloating": -1,
        "mineDiveSpeed": 1,
        "minePlaceDist": 0.5,
        # Class: CfgAmmo\Default\HitEffects [Indent level: 1],
        "HitEffects": {
            "vehicle": "ImpactMetal",
            "object": "ImpactConcrete"
        },
        "whistleDist": 0,
        "whistleOnFire": 0,
        # Class: CfgAmmo\Default\NVGMarkers [Indent level: 1],
        "NVGMarkers": {
        },
        "minDamageForCamShakeHit": 0.55,
        # Class: CfgAmmo\Default\EventHandlers [Indent level: 1],
        "EventHandlers": {
        },
    },
    "tracersEvery": 0,
    "author": "Bohemia Interactive",
    "scope": 2,
    "initSpeed": 1120,
    "maxLeadSpeed": 83.3333,
    "nameSound": "cannon",
    "muzzleImpulseFactor": [-0.1,1],
    "displayName": "30mm Combat Mix 5:1 DU:HEI",
    "displayNameShort": "30mm CM 5:1",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "A3|weapons_F|ammo|mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines\Default\InventoryPlacements [Indent level: 1],
    "InventoryPlacements": {
    },
    # Class: CfgMagazines\Default\Library [Indent level: 1],
    "Library": {
        "libTextDesc": ""
    },
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0,
}