rhs_mag_200rnd_127x99_SLAP_mag_Tracer_Red = {
    "scope": 2,
    "count": 200,
    "descriptionShort": "Caliber: 12.7x99 mm SLAP Tracer - Red<br/>Rounds: 200<br />Used in: Mounted M2",
    "ammo": "rhs_ammo_127x99_SLAP_Tracer_Red",
    "displayName": "12.7mm SLAP M2 HMG Tracer (Red) Belt",
    "displaynameshort": "M903 SLAP",
    "initSpeed": 1210,
    "maxLeadSpeed": 200,
    "tracersEvery": 5,
    "nameSound": "mgun",
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}