rhs_weap_fim92 = {
    "dlc": "RHS_USAF",
    "scope": 2,
    "displayName": "FIM-92F",
    "descriptionShort": "Missile launcher<br/>Caliber: 70mm<br/>Type: Surface-to-air",
    "author": "Red Hammer Studios",
    "model": "rhsusf|addons|rhsusf_weapons|FIM92|stinger_launcher",
    "picture": "rhsusf|addons|rhsusf_weapons|icons|w_fim92_ca.paa",
    "modelOptics": "-",
    "magazines": ["rhs_fim92_mag"],
    "shotPos": "usti hlavne",
    "shotEnd": "konec hlavne",
    "cmImmunity": 0.9,
    "handAnim": ["OFP2_ManSkeleton","|rhsusf|addons|rhsusf_c_weapons|anims|rhs_hand_fim92.rtm"],
    "sounds": ["StandardSound"],
    # Class: CfgWeapons\rhs_weap_fim92\StandardSound,
    "StandardSound": {
        "weaponSoundEffect": "DefaultRifle",
        "begin1": ["A3|Sounds_F|weapons|Launcher|rpg32",1.99526,1,900],
        "soundBegin": ["begin1",1]
    },
    # Class: CfgWeapons\rhs_weap_fim92\WeaponSlotsInfo,
    "WeaponSlotsInfo": {
        "allowedslots": [],
        "mass": 92.4
    },
    "drySound": ["A3|sounds_f|weapons|other|dry6",0.0316228,1,10],
    "reloadMagazineSound": ["A3|sounds_f|weapons|rockets|titan_reload_final",0.562341,1,50],
    "soundFly": ["A3|sounds_f|weapons|rockets|rocket_fly_1",0.316228,1.5,700],
    # Class: CfgWeapons\rhs_weap_fim92\OpticsModes,
    "OpticsModes": {
        # Class: CfgWeapons\rhs_weap_fim92\OpticsModes\StepScope
        "StepScope": {
            "opticsID": 1,
            "useModelOptics": 1,
            "opticsPPEffects": ["OpticsCHAbera1","OpticsBlur1"],
            "opticsFlare": 1,
            "opticsZoomMin": 0.275,
            "opticsZoomMax": 1.1,
            "opticsZoomInit": 0.75,
            "distanceZoomMin": 300,
            "distanceZoomMax": 300,
            "memoryPointCamera": "eye",
            "cameraDir": "",
            "visionMode": ["Normal"],
            "thermalMode": [],
            "opticsDisablePeripherialVision": 1
        }
    },
    "value": 20,
    "canLock": 2,
    "lockAcquire": 1,
    "weaponLockDelay": 5,
    "weaponLockSystem": 2,
    "recoil": "recoil_single_law",
    "reloadAction": "RHS_ReloadRPG",
    "cursorAim": "",
    "cursorAimOn": "",
    "minRange": 10,
    "minRangeProbab": 0.3,
    "midRange": 2500,
    "midRangeProbab": 0.8,
    "maxRange": 4800,
    "maxRangeProbab": 0.1,
    "aiRateOfFire": 5,
    "aiRateOfFireDistance": 2500,
    "weaponInfoType": "RscWeaponZeroing",
    # Class: CfgWeapons\rhs_weap_fim92\Library,
    "Library": {
        "libTextDesc": "The FIM-92 Stinger is a personal portable infrared homing surface-to-air missile (SAM), which can be adapted to fire from ground vehicles or helicopters (as an AAM), developed in the United States and entered into service in 1981."
    },
    "_generalMacro": "launch_O_Titan_F",
    "hiddenSelectionsTextures": ["A3|Weapons_F_Beta|Launchers|Titan|Data|Launcher_OPFOR_CO.paa","A3|Weapons_F_Beta|Launchers|Titan|Data|TubeL_OPFOR_CO.paa"],
    "UiPicture": "A3|Weapons_F|Data|UI|icon_aa_CA.paa",
    "nameSound": "aalauncher",
    "magazineWell": ["Titan_Long"],
    "cursor": "missile",
    "maxZeroing": 2000,
    # Class: CfgWeapons\launch_Titan_base\GunParticles,
    "GunParticles": {
        # Class: CfgWeapons\launch_Titan_base\GunParticles\effect1
        "effect1": {
            "positionName": "muzzleEnd2",
            "directionName": "muzzlePos2",
            "effectName": "RocketBackEffectsNLAWNT"
        }
    },
    "modes": ["Single","TopDown"],
    # Class: CfgWeapons\launch_Titan_base\Single,
    "Single": {
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\launch_Titan_base\Single\BaseSoundModeType,
        "BaseSoundModeType": {
        },
        # Class: CfgWeapons\launch_Titan_base\Single\StandardSound,
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Titan",3.16228,1,2000],
            "soundBegin": ["begin1",1],
            "soundSetShot": ["Launcher_Titan_Shot_SoundSet","Launcher_Titan_Tail_SoundSet"]
        },
        "recoil": "recoil_single_titan",
        "aiRateOfFire": 7,
        "aiRateOfFireDistance": 1500,
        "minRange": 70,
        "minRangeProbab": 0.6,
        "midRange": 150,
        "midRangeProbab": 0.85,
        "maxRange": 3450,
        "maxRangeProbab": 0.85,
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "dispersion": 0.0002,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "reloadTime": 0.1,
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "requiredOpticType": -1,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons\launch_Titan_base\TopDown,
    "TopDown": {
        "textureType": "topDown",
        "displayName": "Top-down Attack",
        "aiRateOfFire": 7,
        "aiRateOfFireDistance": 1500,
        "minRange": 150,
        "minRangeProbab": 0.8,
        "midRange": 500,
        "midRangeProbab": 0.95,
        "maxRange": 2000,
        "maxRangeProbab": 0.95,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\launch_Titan_base\Single\BaseSoundModeType,
        "BaseSoundModeType": {
        },
        # Class: CfgWeapons\launch_Titan_base\Single\StandardSound,
        "StandardSound": {
            "begin1": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Titan",3.16228,1,2000],
            "soundBegin": ["begin1",1],
            "soundSetShot": ["Launcher_Titan_Shot_SoundSet","Launcher_Titan_Tail_SoundSet"]
        },
        "recoil": "recoil_single_titan",
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "dispersion": 0.0002,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "reloadTime": 0.1,
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "requiredOpticType": -1,
        "aiRateOfFireDispersion": 1
    },
    "lockingTargetSound": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|locking_Titan",0.316228,1],
    "lockedTargetSound": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|locked_Titan",0.316228,2.5],
    "inertia": 1.2,
    "aimTransitionSpeed": 0.6,
    "dexterity": 0.8,
    # Class: CfgWeapons\launch_Titan_base\ItemInfo,
    "ItemInfo": {
        "priority": 3
    },
    "hiddenSelections": ["camo_launcher","camo_tube"],
    "htMin": 1,
    "htMax": 460,
    "afMax": 0,
    "mfMax": 0,
    "mFact": 1,
    "tBody": 100,
    "swayCoef": 0.5,
    "sound": ["A3|Sounds_F|weapons|Launcher|rocket_launcher_5",1,1,800],
    "weaponPoolAvailable": 1,
    "textureType": "semi",
    "autoAimEnabled": 0,
    "opticsDisablePeripherialVision": 1,
    "magazineReloadTime": 12,
    "reloadTime": 0,
    "initSpeed": 30,
    "autoReload": 0,
    "ffMagnitude": 0.1,
    "ffFrequency": 1,
    "ffCount": 1,
    "optics": 1,
    "primary": 0,
    "opticsZoomMin": 0.375,
    "opticsZoomMax": 1.1,
    "opticsZoomInit": 0.75,
    "distanceZoomMin": 100,
    "distanceZoomMax": 100,
    "type": 4,
    "count": 1,
    "access": 3,
    "ammo": "",
    "cursorSize": 1,
    "showAimCursorInternal": 1,
    "laser": 0,
    "hiddenUnderwaterSelections": [],
    "shownUnderwaterSelections": [],
    "hiddenUnderwaterSelectionsTextures": [],
    "simulation": "Weapon",
    "multiplier": 1,
    "burst": 1,
    "magazineReloadSwitchPhase": 1,
    "soundBegin": ["sound",1],
    "soundBeginWater": ["sound",1],
    "soundClosure": ["sound",1],
    "soundEnd": ["sound",1],
    "soundLoop": ["sound",1],
    "soundContinuous": 0,
    "weaponSoundEffect": "",
    "soundBurst": 1,
    "zeroingSound": ["",1,1],
    "reloadSound": ["",1,1],
    "changeFiremodeSound": ["",1,1],
    "emptySound": ["",1,1],
    "soundBullet": ["emptySound",1],
    "ballisticsComputer": 0,
    "irDistance": 0,
    "irDotIntensity": 0.001,
    "dispersion": 0.002,
    "aiDispersionCoefX": 1,
    "aiDispersionCoefY": 1,
    "enableAttack": 1,
    "recoilProne": "",
    "maxRecoilSway": 0.008,
    "swayDecaySpeed": 2,
    "modelSpecial": "",
    "modelMagazine": "",
    "muzzlePos": "usti hlavne",
    "muzzleEnd": "konec hlavne",
    "irLaserPos": "laser pos",
    "irLaserEnd": "laser dir",
    "cartridgePos": "nabojnicestart",
    "cartridgeVel": "nabojniceend",
    "selectionFireAnim": "zasleh",
    "memoryPointCamera": "eye",
    "fireSpreadAngle": 3,
    "useModelOptics": 1,
    "opticsID": 0,
    "opticsPPEffects": [],
    "opticsFlare": 1,
    "forceOptics": 0,
    "useAsBinocular": 0,
    "showSwitchAction": 0,
    "showEmpty": 1,
    "autoFire": 0,
    "showToPlayer": 1,
    "canShootInWater": 0,
    "aiRateOfFireDispersion": 0,
    "fireLightDuration": 0.05,
    "fireLightIntensity": 0.2,
    "fireLightDiffuse": [0.937,0.631,0.259],
    "fireLightAmbient": [0,0,0],
    # Class: CfgWeapons\Default\Eventhandlers,
    "Eventhandlers": {
    },
    "backgroundReload": 0,
    "muzzles": ["this"],
    "useAction": 0,
    "useActionTitle": "",
    "canDrop": 1,
    "weight": 0,
    "detectRange": 0,
    "artilleryDispersion": 1,
    "artilleryCharge": 1,
    "fireAnims": [],
    # Class: CfgWeapons\Default\GunFire,
    "GunFire": {
        "access": 0,
        "cloudletDuration": 0.2,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 0.2,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 0.5,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletFire",
        "cloudletColor": [1,1,1,0],
        "cloudletDensityCoef": -1,
        "interval": -0.01,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 4500,
        "deltaT": -3000,
        # Class: CfgWeapons\Default\GunFire\Table,
        "Table": {
            # Class: CfgWeapons\Default\GunFire\Table\T0
            "T0": {
                "maxT": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T1,
            "T1": {
                "maxT": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T2,
            "T2": {
                "maxT": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T3,
            "T3": {
                "maxT": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T4,
            "T4": {
                "maxT": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T5,
            "T5": {
                "maxT": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T6,
            "T6": {
                "maxT": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T7,
            "T7": {
                "maxT": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T8,
            "T8": {
                "maxT": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T9,
            "T9": {
                "maxT": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T10,
            "T10": {
                "maxT": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T11,
            "T11": {
                "maxT": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T12,
            "T12": {
                "maxT": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T13,
            "T13": {
                "maxT": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T14,
            "T14": {
                "maxT": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T15,
            "T15": {
                "maxT": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T16,
            "T16": {
                "maxT": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T17,
            "T17": {
                "maxT": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T18,
            "T18": {
                "maxT": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T19,
            "T19": {
                "maxT": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T20,
            "T20": {
                "maxT": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T21,
            "T21": {
                "maxT": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T22,
            "T22": {
                "maxT": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgWeapons\Default\GunClouds,
    "GunClouds": {
        "access": 0,
        "cloudletGrowUp": 0.05,
        "cloudletFadeIn": 0,
        "cloudletFadeOut": 0.1,
        "cloudletDuration": 0.05,
        "cloudletAlpha": 0.3,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "interval": -0.02,
        "size": 0.3,
        "sourceSize": 0.02,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletShape": "cloudletClouds",
        "cloudletColor": [1,1,1,0],
        "timeToLive": 0,
        "initT": 0,
        "deltaT": 0,
        # Class: CfgWeapons\Default\GunClouds\Table,
        "Table": {
            # Class: CfgWeapons\Default\GunClouds\Table\T0
            "T0": {
                "maxT": 0,
                "color": [1,1,1,0]
            }
        }
    },
}