rhs_weap_m32_Base_F = {
    "dlc": "RHS_USAF",
    "UiPicture": "A3|weapons_f|data|UI|icon_regular_CA.paa",
    "model": "rhsusf|addons|rhsusf_weapons2|M32|rhs_m32",
    "magazines": ["rhsusf_mag_6Rnd_M441_HE","rhsusf_mag_6Rnd_M433_HEDP","rhsusf_mag_6Rnd_M397_HET","rhsusf_mag_6Rnd_M576_Buckshot","rhsusf_mag_6Rnd_M781_Practice","rhsusf_mag_6Rnd_m4009","rhsusf_mag_6Rnd_M585_white","rhsusf_mag_6Rnd_m661_green","rhsusf_mag_6Rnd_m662_red","rhsusf_mag_6Rnd_M713_red","rhsusf_mag_6Rnd_M714_white","rhsusf_mag_6Rnd_M715_green","rhsusf_mag_6Rnd_M716_yellow"],
    # Class: CfgWeapons\rhs_weap_m32_Base_F\Library [Indent level: 1],
    "Library": {
        "libTextDesc": ""
    },
    "optics": 0,
    "scope": 1,
    "reloadAction": "GestureReloadKatibaUGL",
    "maxRecoilSway": 0.0125,
    "swayDecaySpeed": 1.25,
    "recoil": "recoil_gm6",
    # Class: CfgWeapons\rhs_weap_m32_Base_F\GunParticles [Indent level: 1],
    "GunParticles": {
        # Class: CfgWeapons\rhs_weap_m32_Base_F\GunParticles\SecondEffect [Indent level: 2]
        "SecondEffect": {
            "positionName": "Nabojnicestart",
            "directionName": "Nabojniceend",
            "effectName": "RifleAssaultCloud"
        },
        # Class: CfgWeapons\Rifle_Base_F\GunParticles\FirstEffect [Indent level: 2],
        "FirstEffect": {
            "effectName": "RifleAssaultCloud",
            "positionName": "Usti hlavne",
            "directionName": "Konec hlavne"
        }
    },
    "weaponInfoType": "RscWeaponZeroing",
    "cameraDir": "gl_look",
    "discreteDistance": [50,100,150,200,250,300,350,375],
    "discreteDistanceCameraPoint": ["gl_eye_50m","gl_eye_100m","gl_eye_150m","gl_eye_200m","gl_eye_250m","gl_eye_300m","gl_eye_350m","gl_eye_375m"],
    "discreteDistanceInitIndex": 1,
    "opticsZoomMin": 0.275,
    "opticsZoomMax": 1.1,
    "opticsZoomInit": 0.75,
    "distanceZoomMin": 50,
    "distanceZoomMax": 375,
    # Class: CfgWeapons\rhs_weap_m32_Base_F\WeaponSlotsInfo [Indent level: 1],
    "WeaponSlotsInfo": {
        "mass": 116.6,
        # Class: CfgWeapons\rhs_weap_m32_Base_F\WeaponSlotsInfo\CowsSlot [Indent level: 2],
        "CowsSlot": {
        },
        # Class: CfgWeapons\rhs_weap_m32_Base_F\WeaponSlotsInfo\PointerSlot [Indent level: 2],
        "PointerSlot": {
            "iconPosition": [0,0],
            "iconScale": 1,
            "iconPicture": "A3|Weapons_F|Data|clear_empty.paa",
            "iconPinPoint": "Left",
            # Class: rhs_western_rifle_laser_slot\compatibleItems [Indent level: 0],
            "compatibleItems": {
                "rhsusf_acc_anpeq15": 0,
                "rhsusf_acc_anpeq15_top": 0,
                "rhsusf_acc_anpeq15_light": 0,
                "rhsusf_acc_anpeq15_bk": 0,
                "rhsusf_acc_anpeq15_bk_top": 0,
                "rhsusf_acc_anpeq15_bk_light": 0,
                "rhsusf_acc_anpeq15_wmx": 0,
                "rhsusf_acc_anpeq15_wmx_light": 0,
                "rhsusf_acc_anpeq16a_top": 0,
                "rhsusf_acc_anpeq16a_light_top": 0,
                "rhsusf_acc_anpeq16a_top_h": 0,
                "rhsusf_acc_anpeq16a_light_top_h": 0,
                "acc_mc1laser_F": 1,
                "SureFire_ej": 1,
                "SureFire_d_ej": 1,
                "ej_PEQ15": 1,
                "ej_PEQ15Black": 1,
                "ej_PEQ15Top": 1,
                "ej_PEQ15BlackTop": 1,
                "IbexL_ej": 1,
                "Ibexf_ej": 1,
                "Streamlight_F_ej": 1,
                "Streamlight_L_ej": 1,
                "SFPEQ_laser": 1,
                "SFPEQ_light": 1,
                "Ibex_laser": 1,
                "Ibex_light": 1,
                "Ibex_laserBlack": 1,
                "Ibex_lightBlack": 1,
                "SFPEQ_light_S": 1,
                "SFPEQ_laser_S": 1,
                "SFPEQ_laser_SR": 1,
                "SFPEQ_light_SR": 1,
                "SFPEQ_light_SB": 1,
                "SFPEQ_laser_SB": 1,
                "SFPEQ_laser_SRB": 1,
                "SFPEQ_light_SRB": 1,
                "SFPEQ_laserB": 1,
                "SFPEQ_lightB": 1,
                "rhs_acc_2dpZenit_ris": 1,
                "rhs_acc_perst1ik_ris": 1,
                "rhs_acc_perst3": 1,
                "rhsusf_acc_wmx": 1,
                "rhsusf_acc_wmx_bk": 1,
                "rhsusf_acc_M952V": 1,
                "rhsusf_acc_anpeq15A": 1,
                "rhsusf_acc_anpeq15_h": 1,
                "rhsusf_acc_anpeq15_light_h": 1,
                "rhsusf_acc_anpeq15_top_h": 1,
                "rhsusf_acc_anpeq15_sc": 1,
                "rhsusf_acc_anpeq15_light_sc": 1,
                "rhsusf_acc_anpeq15_top_sc": 1,
                "rhsusf_acc_anpeq15side": 1,
                "rhsusf_acc_anpeq15_bk_h": 1,
                "rhsusf_acc_anpeq15_bk_light_h": 1,
                "rhsusf_acc_anpeq15_bk_top_h": 1,
                "rhsusf_acc_anpeq15_bk_sc": 1,
                "rhsusf_acc_anpeq15_bk_light_sc": 1,
                "rhsusf_acc_anpeq15_bk_top_sc": 1,
                "rhsusf_acc_anpeq15side_bk": 1,
                "rhsusf_acc_anpeq15_wmx_h": 1,
                "rhsusf_acc_anpeq15_wmx_light_h": 1,
                "rhsusf_acc_anpeq15_wmx_sc": 1,
                "rhsusf_acc_anpeq15_wmx_light_sc": 1,
                "rhsusf_acc_anpeq16a": 1,
                "rhsusf_acc_anpeq16a_light": 1,
                "rhsusf_acc_anpeq16a_top_sc": 1,
                "rhsusf_acc_anpeq16a_light_top_sc": 1,
                "acc_flashlight": 1,
                "acc_flashlight_broken": 1,
                "acc_pointer_IR": 1,
                "acc_pointer_IR_broken": 1,
                "acc_mc1laser": 1,
                "FHQ_acc_ANPEQ15": 1,
                "FHQ_acc_ANPEQ15_black": 1,
                "FHQ_acc_LLM01L": 1,
                "FHQ_acc_LLM01F": 1,
                "JAS_ANPEQ15_Tan": 1,
                "JAS_ANPEQ15_Blk": 1,
                "SMA_ANPEQ15_TAN": 1,
                "SMA_ANPEQ15_BLK": 1,
                "SMA_SFFL_TAN": 1,
                "SMA_SFFL_BLK": 1,
                "ACE_acc_pointer_red": 1,
                "ACE_acc_pointer_green": 1,
                "ACE_acc_pointer_green_IR": 1,
                "CUP_acc_ANPEQ_15": 1,
                "CUP_acc_ANPEQ_15_V": 1,
                "CUP_acc_ANPEQ_15_Black": 1,
                "CUP_acc_ANPEQ_15_Black_V": 1,
                "CUP_acc_ANPEQ_15_OD": 1,
                "CUP_acc_ANPEQ_15_OD_V": 1,
                "CUP_acc_ANPEQ_15_Tan_Top": 1,
                "CUP_acc_ANPEQ_15_Tan_Top_V": 1,
                "CUP_acc_ANPEQ_15_Black_Top": 1,
                "CUP_acc_ANPEQ_15_Black_Top_V": 1,
                "CUP_acc_ANPEQ_15_OD_Top": 1,
                "CUP_acc_ANPEQ_15_OD_Top_V": 1,
                "CUP_acc_ANPEQ_2": 1,
                "CUP_acc_ANPEQ_2_grey": 1,
                "CUP_acc_ANPEQ_2_camo": 1,
                "CUP_acc_ANPEQ_2_desert": 1,
                "CUP_acc_ANPEQ_2_Black_Top": 1,
                "CUP_acc_ANPEQ_2_OD_Top": 1,
                "CUP_acc_ANPEQ_2_Coyote_Top": 1,
                "CUP_acc_Flashlight": 1,
                "CUP_acc_Flashlight_wdl": 1,
                "CUP_acc_Flashlight_desert": 1,
                "CUP_acc_XM8_light_module": 1,
                "CUP_acc_LLM": 1,
                "CUP_acc_LLM_Flashlight": 1,
                "CUP_acc_LLM_black": 1,
                "CUP_acc_LLM_black_Flashlight": 1,
                "CUP_acc_LLM_od": 1,
                "CUP_acc_LLM_od_Flashlight": 1,
                "CUP_acc_ANPEQ_2_Flashlight_Black_L": 1,
                "CUP_acc_ANPEQ_2_Flashlight_Black_F": 1,
                "CUP_acc_ANPEQ_2_Flashlight_Coyote_L": 1,
                "CUP_acc_ANPEQ_2_Flashlight_Coyote_F": 1,
                "CUP_acc_ANPEQ_2_Flashlight_OD_L": 1,
                "CUP_acc_ANPEQ_2_Flashlight_OD_F": 1,
                "CUP_acc_ANPEQ_15_Flashlight_Tan_L": 1,
                "CUP_acc_ANPEQ_15_Flashlight_Tan_F": 1,
                "CUP_acc_ANPEQ_15_Flashlight_Tan_V": 1,
                "CUP_acc_ANPEQ_15_Flashlight_OD_L": 1,
                "CUP_acc_ANPEQ_15_Flashlight_OD_F": 1,
                "CUP_acc_ANPEQ_15_Flashlight_OD_V": 1,
                "CUP_acc_ANPEQ_15_Flashlight_Black_L": 1,
                "CUP_acc_ANPEQ_15_Flashlight_Black_F": 1,
                "CUP_acc_ANPEQ_15_Flashlight_Black_V": 1,
                "CUP_acc_ANPEQ_15_Top_Flashlight_Tan_L": 1,
                "CUP_acc_ANPEQ_15_Top_Flashlight_Tan_F": 1,
                "CUP_acc_ANPEQ_15_Top_Flashlight_Tan_V": 1,
                "CUP_acc_ANPEQ_15_Top_Flashlight_OD_L": 1,
                "CUP_acc_ANPEQ_15_Top_Flashlight_OD_F": 1,
                "CUP_acc_ANPEQ_15_Top_Flashlight_OD_V": 1,
                "CUP_acc_ANPEQ_15_Top_Flashlight_Black_L": 1,
                "CUP_acc_ANPEQ_15_Top_Flashlight_Black_F": 1,
                "CUP_acc_ANPEQ_15_Top_Flashlight_Black_V": 1,
                "CUP_acc_LLM01_F": 1,
                "CUP_acc_LLM01_L": 1,
                "CUP_acc_LLM01_desert_F": 1,
                "CUP_acc_LLM01_desert_L": 1,
                "CUP_acc_LLM01_hex_F": 1,
                "CUP_acc_LLM01_hex_L": 1,
                "CUP_acc_LLM01_coyote_F": 1,
                "CUP_acc_LLM01_coyote_L": 1,
                "CUP_acc_LLM01_od_F": 1,
                "CUP_acc_LLM01_od_L": 1
            },
            "linkProxy": "a3|data_f|proxies|weapon_slots|side",
            "displayName": "Pointer Slot",
            "scope": 0
        },
        # Class: CfgWeapons\Rifle\WeaponSlotsInfo\MuzzleSlot [Indent level: 2],
        "MuzzleSlot": {
            "linkProxy": "A3|data_f|proxies|weapon_slots|MUZZLE",
            "displayName": "$str_a3_cfgweapons_abr_base_f_weaponslotsinfo_muzzleslot0",
            "compatibleItems": [],
            "iconPicture": "A3|Weapons_F|Data|UI|attachment_muzzle.paa",
            "iconPinpoint": "Center",
            "access": 1,
            "scope": 0,
            "iconPosition": [0,0],
            "iconScale": 0
        },
        "allowedSlots": [901]
    },
    "handAnim": ["OFP2_ManSkeleton","|rhsusf|addons|rhsusf_c_weapons|anims|rhs_hand_M32.rtm"],
    "dexterity": 1.8,
    "aimTransitionSpeed": 0.65,
    "caseless": ["",1,1,1],
    "soundBullet": ["caseless",1],
    "modes": ["Single","far_optic1","medium_optic2","far_optic2"],
    # Class: CfgWeapons\rhs_weap_m32_Base_F\Single [Indent level: 1],
    "Single": {
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_m32_Base_F\Single\StandardSound [Indent level: 2],
        "StandardSound": {
            "weaponSoundEffect": "DefaultRifle",
            "soundClosure": [],
            "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_1.ogg",1.8,1,800],
            "begin2": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_2.ogg",1.8,1,800],
            "soundBegin": ["begin1",0.25,"begin2",0.25,"begin3",0.25,"begin4",0.25],
            "closure1": ["rhsusf|addons|rhsusf_sounds|m32|Closure_1",2.4,1,35],
            "closure2": ["rhsusf|addons|rhsusf_sounds|m32|Closure_2",2.4,1,35],
            "soundSetShot": ["jsrs_m32_shot_soundset","jsrs_12x7mm_reverb_soundset"],
            "begin3": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_3.ogg",1.8,1,800],
            "begin4": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_4.ogg",1.8,1,800]
        },
        "reloadTime": 0.075,
        "dispersion": 0.0002909,
        "minRange": 2,
        "minRangeProbab": 0.3,
        "midRange": 250,
        "midRangeProbab": 0.7,
        "maxRange": 400,
        "maxRangeProbab": 0.04,
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "showToPlayer": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "requiredOpticType": -1,
        "aiRateOfFire": 2,
        "aiRateOfFireDispersion": 1,
        "aiRateOfFireDistance": 500
    },
    # Class: CfgWeapons\rhs_weap_m32_Base_F\far_optic1 [Indent level: 1],
    "far_optic1": {
        "showToPlayer": 0,
        "minRange": 150,
        "minRangeProbab": 0.1,
        "midRange": 500,
        "midRangeProbab": 0.7,
        "maxRange": 1000,
        "maxRangeProbab": 0.3,
        "aiRateOfFire": 5,
        "aiRateOfFireDistance": 700,
        "requiredOpticType": 1,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_m32_Base_F\Single\StandardSound [Indent level: 2],
        "StandardSound": {
            "weaponSoundEffect": "DefaultRifle",
            "soundClosure": [],
            "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_1.ogg",1.8,1,800],
            "begin2": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_2.ogg",1.8,1,800],
            "soundBegin": ["begin1",0.25,"begin2",0.25,"begin3",0.25,"begin4",0.25],
            "closure1": ["rhsusf|addons|rhsusf_sounds|m32|Closure_1",2.4,1,35],
            "closure2": ["rhsusf|addons|rhsusf_sounds|m32|Closure_2",2.4,1,35],
            "soundSetShot": ["jsrs_m32_shot_soundset","jsrs_12x7mm_reverb_soundset"],
            "begin3": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_3.ogg",1.8,1,800],
            "begin4": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_4.ogg",1.8,1,800]
        },
        "reloadTime": 0.075,
        "dispersion": 0.0002909,
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons\rhs_weap_m32_Base_F\medium_optic2 [Indent level: 1],
    "medium_optic2": {
        "showToPlayer": 0,
        "minRange": 250,
        "minRangeProbab": 0.1,
        "midRange": 750,
        "midRangeProbab": 0.7,
        "maxRange": 1000,
        "maxRangeProbab": 0.3,
        "aiRateOfFire": 6,
        "aiRateOfFireDistance": 1000,
        "requiredOpticType": 2,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_m32_Base_F\Single\StandardSound [Indent level: 2],
        "StandardSound": {
            "weaponSoundEffect": "DefaultRifle",
            "soundClosure": [],
            "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_1.ogg",1.8,1,800],
            "begin2": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_2.ogg",1.8,1,800],
            "soundBegin": ["begin1",0.25,"begin2",0.25,"begin3",0.25,"begin4",0.25],
            "closure1": ["rhsusf|addons|rhsusf_sounds|m32|Closure_1",2.4,1,35],
            "closure2": ["rhsusf|addons|rhsusf_sounds|m32|Closure_2",2.4,1,35],
            "soundSetShot": ["jsrs_m32_shot_soundset","jsrs_12x7mm_reverb_soundset"],
            "begin3": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_3.ogg",1.8,1,800],
            "begin4": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_4.ogg",1.8,1,800]
        },
        "reloadTime": 0.075,
        "dispersion": 0.0002909,
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "aiRateOfFireDispersion": 1
    },
    # Class: CfgWeapons\rhs_weap_m32_Base_F\far_optic2 [Indent level: 1],
    "far_optic2": {
        "minRange": 500,
        "minRangeProbab": 0.1,
        "midRange": 1050,
        "midRangeProbab": 0.7,
        "maxRange": 2000,
        "maxRangeProbab": 0.3,
        "aiRateOfFire": 8,
        "aiRateOfFireDistance": 2000,
        "requiredOpticType": 2,
        "showToPlayer": 0,
        "sounds": ["StandardSound"],
        # Class: CfgWeapons\rhs_weap_m32_Base_F\Single\StandardSound [Indent level: 2],
        "StandardSound": {
            "weaponSoundEffect": "DefaultRifle",
            "soundClosure": [],
            "begin1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_1.ogg",1.8,1,800],
            "begin2": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_2.ogg",1.8,1,800],
            "soundBegin": ["begin1",0.25,"begin2",0.25,"begin3",0.25,"begin4",0.25],
            "closure1": ["rhsusf|addons|rhsusf_sounds|m32|Closure_1",2.4,1,35],
            "closure2": ["rhsusf|addons|rhsusf_sounds|m32|Closure_2",2.4,1,35],
            "soundSetShot": ["jsrs_m32_shot_soundset","jsrs_12x7mm_reverb_soundset"],
            "begin3": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_3.ogg",1.8,1,800],
            "begin4": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|Shot|UGL|Close_4.ogg",1.8,1,800]
        },
        "reloadTime": 0.075,
        "dispersion": 0.0002909,
        "multiplier": 1,
        "burst": 1,
        "burstRangeMax": -1,
        "sound": ["",10,1],
        "soundBegin": ["sound",1],
        "soundBeginWater": ["sound",1],
        "soundClosure": ["sound",1],
        "soundEnd": [],
        "soundLoop": [],
        "soundContinuous": 0,
        "weaponSoundEffect": "",
        "ffCount": 1,
        "ffMagnitude": 0.5,
        "ffFrequency": 11,
        "flash": "gunfire",
        "flashSize": 0.1,
        "autoFire": 0,
        "useAction": 0,
        "useActionTitle": "",
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "canShootInWater": 0,
        "displayName": "Semi",
        "textureType": "semi",
        "recoil": "recoil_single_primary_3outof10",
        "recoilProne": "recoil_single_primary_prone_3outof10",
        "aiDispersionCoefY": 1.7,
        "aiDispersionCoefX": 1.4,
        "soundBurst": 0,
        "aiRateOfFireDispersion": 1
    },
    "aiDispersionCoefY": 10,
    "aiDispersionCoefX": 8,
    "drySound": ["A3|sounds_f|weapons|Other|dry_1",0.01,1],
    "deployedPivot": "bipod",
    # Class: CfgWeapons\Rifle_Base_F\Eventhandlers [Indent level: 1],
    "Eventhandlers": {
        # Class: CfgWeapons\Rifle_Base_F\Eventhandlers\GSM_popMagRifle [Indent level: 2]
        "GSM_popMagRifle": {
            "fired": "_this call GSM_fnc_detectReload"
        }
    },
    "htMin": 1,
    "htMax": 600,
    "afMax": 0,
    "mfMax": 0,
    "mFact": 1,
    "tBody": 100,
    "autoFire": 1,
    "soundContinuous": 0,
    "cursor": "arifle",
    "cursoraim": "CursorAim",
    "value": 4,
    "displayName": "Rifle",
    "nameSound": "rifle",
    "reloadTime": 0.15,
    "modelOptics": "-",
    "sound": [],
    "opticsFlare": 0,
    "autoReload": 0,
    "maxLeadSpeed": 23,
    "canLock": 0,
    "flash": "gunfire",
    "flashSize": 0.5,
    "dispersion": 0.00029,
    "recoilProne": "assaultRifleBase",
    "ffMagnitude": 0.5,
    "ffFrequency": 11,
    "ffCount": 3,
    "weaponPoolAvailable": 1,
    "maxZeroing": 1000,
    "zeroingSound": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|weapons|noises|rifle_zeroing_1.ogg",5,1,5],
    "ace_overheating_mrbs": 3000,
    "ace_overheating_dispersion": 1,
    "ace_overheating_slowdownFactor": 1,
    "type": 1,
    "aiRateOfFire": 0.5,
    "aiRateOfFireDistance": 500,
    "inertia": 0.5,
    "access": 3,
    "picture": "",
    "ammo": "",
    "cursorSize": 1,
    "showAimCursorInternal": 1,
    "cursorAimOn": "",
    "laser": 0,
    "hiddenSelections": [],
    "hiddenSelectionsTextures": [],
    "hiddenUnderwaterSelections": [],
    "shownUnderwaterSelections": [],
    "hiddenUnderwaterSelectionsTextures": [],
    "simulation": "Weapon",
    "count": 0,
    "multiplier": 1,
    "burst": 1,
    "magazineReloadTime": 0,
    "magazineReloadSwitchPhase": 1,
    "soundBegin": ["sound",1],
    "soundBeginWater": ["sound",1],
    "soundClosure": ["sound",1],
    "soundEnd": ["sound",1],
    "soundLoop": ["sound",1],
    "weaponSoundEffect": "",
    "soundBurst": 1,
    "reloadSound": ["",1,1],
    "changeFiremodeSound": ["",1,1],
    "reloadMagazineSound": ["",1,1],
    "emptySound": ["",1,1],
    "initSpeed": 0,
    "ballisticsComputer": 0,
    "irDistance": 0,
    "irDotIntensity": 0.001,
    "lockAcquire": 1,
    "enableAttack": 1,
    "modelSpecial": "",
    "modelMagazine": "",
    "muzzlePos": "usti hlavne",
    "muzzleEnd": "konec hlavne",
    "irLaserPos": "laser pos",
    "irLaserEnd": "laser dir",
    "cartridgePos": "nabojnicestart",
    "cartridgeVel": "nabojniceend",
    "selectionFireAnim": "zasleh",
    "memoryPointCamera": "eye",
    "fireSpreadAngle": 3,
    "useModelOptics": 1,
    "opticsID": 0,
    "opticsPPEffects": [],
    "forceOptics": 0,
    "useAsBinocular": 0,
    "opticsDisablePeripherialVision": 0.67,
    "primary": 10,
    "showSwitchAction": 0,
    "showEmpty": 1,
    "showToPlayer": 1,
    "canShootInWater": 0,
    "aiRateOfFireDispersion": 0,
    "fireLightDuration": 0.05,
    "fireLightIntensity": 0.2,
    "fireLightDiffuse": [0.937,0.631,0.259],
    "fireLightAmbient": [0,0,0],
    "backgroundReload": 0,
    "muzzles": ["this"],
    "useAction": 0,
    "useActionTitle": "",
    "canDrop": 1,
    "weaponLockDelay": 0,
    "weaponLockSystem": 0,
    "cmImmunity": 1,
    "weight": 0,
    "minRange": 1,
    "minRangeProbab": 0.3,
    "midRange": 150,
    "midRangeProbab": 0.58,
    "maxRange": 500,
    "maxRangeProbab": 0.04,
    "lockingTargetSound": ["",0.000316228,2],
    "lockedTargetSound": ["",0.000316228,6],
    "detectRange": 0,
    "artilleryDispersion": 1,
    "artilleryCharge": 1,
    "fireAnims": [],
    "descriptionShort": "",
    # Class: CfgWeapons\Default\GunFire [Indent level: 1],
    "GunFire": {
        "access": 0,
        "cloudletDuration": 0.2,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletAlpha": 1,
        "cloudletGrowUp": 0.2,
        "cloudletFadeIn": 0.01,
        "cloudletFadeOut": 0.5,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "cloudletShape": "cloudletFire",
        "cloudletColor": [1,1,1,0],
        "cloudletDensityCoef": -1,
        "interval": -0.01,
        "size": 3,
        "sourceSize": 0.5,
        "timeToLive": 0,
        "initT": 4500,
        "deltaT": -3000,
        # Class: CfgWeapons\Default\GunFire\Table [Indent level: 2],
        "Table": {
            # Class: CfgWeapons\Default\GunFire\Table\T0 [Indent level: 3]
            "T0": {
                "maxT": 0,
                "color": [0.82,0.95,0.93,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T1 [Indent level: 3],
            "T1": {
                "maxT": 200,
                "color": [0.75,0.77,0.9,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T2 [Indent level: 3],
            "T2": {
                "maxT": 400,
                "color": [0.56,0.62,0.67,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T3 [Indent level: 3],
            "T3": {
                "maxT": 600,
                "color": [0.39,0.46,0.47,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T4 [Indent level: 3],
            "T4": {
                "maxT": 800,
                "color": [0.24,0.31,0.31,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T5 [Indent level: 3],
            "T5": {
                "maxT": 1000,
                "color": [0.23,0.31,0.29,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T6 [Indent level: 3],
            "T6": {
                "maxT": 1500,
                "color": [0.21,0.29,0.27,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T7 [Indent level: 3],
            "T7": {
                "maxT": 2000,
                "color": [0.19,0.23,0.21,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T8 [Indent level: 3],
            "T8": {
                "maxT": 2300,
                "color": [0.22,0.19,0.1,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T9 [Indent level: 3],
            "T9": {
                "maxT": 2500,
                "color": [0.35,0.2,0.02,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T10 [Indent level: 3],
            "T10": {
                "maxT": 2600,
                "color": [0.62,0.29,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T11 [Indent level: 3],
            "T11": {
                "maxT": 2650,
                "color": [0.59,0.35,0.05,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T12 [Indent level: 3],
            "T12": {
                "maxT": 2700,
                "color": [0.75,0.37,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T13 [Indent level: 3],
            "T13": {
                "maxT": 2750,
                "color": [0.88,0.34,0.03,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T14 [Indent level: 3],
            "T14": {
                "maxT": 2800,
                "color": [0.91,0.5,0.17,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T15 [Indent level: 3],
            "T15": {
                "maxT": 2850,
                "color": [1,0.6,0.2,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T16 [Indent level: 3],
            "T16": {
                "maxT": 2900,
                "color": [1,0.71,0.3,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T17 [Indent level: 3],
            "T17": {
                "maxT": 2950,
                "color": [0.98,0.83,0.41,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T18 [Indent level: 3],
            "T18": {
                "maxT": 3000,
                "color": [0.98,0.91,0.54,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T19 [Indent level: 3],
            "T19": {
                "maxT": 3100,
                "color": [0.98,0.99,0.6,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T20 [Indent level: 3],
            "T20": {
                "maxT": 3300,
                "color": [0.96,0.99,0.72,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T21 [Indent level: 3],
            "T21": {
                "maxT": 3600,
                "color": [1,0.98,0.91,0]
            },
            # Class: CfgWeapons\Default\GunFire\Table\T22 [Indent level: 3],
            "T22": {
                "maxT": 4200,
                "color": [1,1,1,0]
            }
        }
    },
    # Class: CfgWeapons\Default\GunClouds [Indent level: 1],
    "GunClouds": {
        "access": 0,
        "cloudletGrowUp": 0.05,
        "cloudletFadeIn": 0,
        "cloudletFadeOut": 0.1,
        "cloudletDuration": 0.05,
        "cloudletAlpha": 0.3,
        "cloudletAccY": 0,
        "cloudletMinYSpeed": -100,
        "cloudletMaxYSpeed": 100,
        "interval": -0.02,
        "size": 0.3,
        "sourceSize": 0.02,
        "cloudletAnimPeriod": 1,
        "cloudletSize": 1,
        "cloudletShape": "cloudletClouds",
        "cloudletColor": [1,1,1,0],
        "timeToLive": 0,
        "initT": 0,
        "deltaT": 0,
        # Class: CfgWeapons\Default\GunClouds\Table [Indent level: 2],
        "Table": {
            # Class: CfgWeapons\Default\GunClouds\Table\T0 [Indent level: 3]
            "T0": {
                "maxT": 0,
                "color": [1,1,1,0]
            }
        }
    },
    "textureType": "default",
}