rhs_scarf = {
    "dlc": "RHS_AFRF",
    "author": "Red Hammer Studios",
    "displayname": "Scarf",
    "model": "rhsafrf|addons|rhs_infantry|gear|head|rhs_scarf",
    "picture": "rhsafrf|addons|rhs_infantry|Data|inventory|gear_icon_scarf_ca.paa",
    "identitytypes": ["NoGlasses",0,"rhs_scarf",30],
    "_generalmacro": "G_Balaclava_blk",
    "scope": 2,
    "scopecurator": 2,
    "scopearsenal": 2,
    "hiddenselections": ["camo"],
    "hiddenselectionstextures": ["|a3|characters_f_bootcamp|guerrilla|data|headgear_balaclava_blk_co.paa"],
    "mass": 6,
    "name": "None",
}