d = {
    "_generalmacro": "G_Spectacles",
    "author": "Bohemia Interactive",
    "displayname": "Spectacle Glasses",
    "hiddenselections": [
        "camo"
    ],
    "hiddenselectionstextures": [
        "/a3/characters_f/heads/glasses/data/spectacles_brown_ca.paa"
    ],
    "identitytypes": [
        "G_CIVIL_aidworker",
        100,
        "G_CIVIL_constructionworker",
        120,
        "G_CIVIL_man",
        80,
        "NoGlasses",
        0,
        "G_NATO_default",
        0,
        "G_NATO_casual",
        0,
        "G_NATO_pilot",
        0,
        "G_NATO_recon",
        5,
        "G_NATO_SF",
        0,
        "G_NATO_sniper",
        0,
        "G_NATO_diver",
        0,
        "G_IRAN_default",
        0,
        "G_IRAN_diver",
        0,
        "G_GUERIL_default",
        10,
        "G_HAF_default",
        10,
        "G_CIVIL_female",
        10,
        "G_CIVIL_male",
        20
    ],
    "mass": 2,
    "model": "A3/characters_f_beta/heads/glasses/g_spectacles",
    "name": "None",
    "picture": "A3/Characters_F/data/ui/icon_g_spectacles_CA.paa",
    "scope": 2
}