d = {
    "_generalmacro": "G_Tactical_Clear",
    "author": "Bohemia Interactive",
    "displayname": "Tactical Glasses",
    "identitytypes": [
        "NoGlasses",
        0,
        "G_NATO_default",
        250,
        "G_NATO_casual",
        0,
        "G_NATO_pilot",
        0,
        "G_NATO_recon",
        50,
        "G_NATO_SF",
        250,
        "G_NATO_sniper",
        0,
        "G_NATO_diver",
        0,
        "G_IRAN_default",
        0,
        "G_IRAN_diver",
        0,
        "G_GUERIL_default",
        0,
        "G_HAF_default",
        50,
        "G_CIVIL_female",
        0,
        "G_CIVIL_male",
        0,
        "G_Rangemaster",
        1
    ],
    "mass": 1,
    "model": "A3/characters_f/heads/glasses/g_tactical_clear",
    "name": "None",
    "picture": "A3/Characters_F/data/ui/icon_g_tactical_CA.paa",
    "scope": 2
}