d = {
    "displayname": "None",
    "identitytypes": [
        "G_RUS_SF",
        50,
        "G_CIVIL_aidworker",
        200,
        "G_CIVIL_man",
        150,
        "G_CIVIL_paramedic",
        520,
        "G_CIVIL_constructionworker",
        220,
        "NoGlasses",
        1000,
        "G_NATO_default",
        300,
        "G_NATO_casual",
        550,
        "G_NATO_pilot",
        1000,
        "G_NATO_recon",
        595,
        "G_NATO_SF",
        300,
        "G_NATO_sniper",
        1000,
        "G_NATO_diver",
        0,
        "G_IRAN_default",
        1000,
        "G_IRAN_diver",
        0,
        "G_GUERIL_default",
        595,
        "G_HAF_default",
        595,
        "G_CIVIL_female",
        655,
        "G_CIVIL_male",
        670,
        "g_Rangemaster",
        0,
        "G_IRAN_officer",
        500
    ],
    "mass": 1,
    "model": "",
    "name": "None",
    "picture": "A3/Characters_F/data/ui/icon_g_aviators_CA.paa",
    "scope": 2
}