d = {
    "ammo": "B_65x39_Case_Yellow",
    "author": "Bohemia Interactive",
    "count": 1000,
    "descriptionshort": "Caliber: 6.5x39 mm Tracer - Yellow<br />Rounds: 1000<br />Used in: Vehicles",
    "displayname": "6.5 mm 1000Rnd LMG Tracer (Yellow) Belt",
    "displaynamemfdformat": "LMG",
    "displaynameshort": "Tracer",
    "initspeed": 825,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 8,
    "maxleadspeed": 36.1111,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "",
    "namesound": "mgun",
    "picture": "",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "tracersevery": 1,
    "type": 0,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 0,
    "weight": 0
}