d = {
    "ammo": "B_50BW_Ball_F",
    "author": "Bohemia Interactive",
    "count": 10,
    "descriptionshort": "Caliber: .50 BW - Caseless<br />Rounds: 10<br />Used in: Type 115",
    "displayname": ".50 BW 10Rnd Caseless Mag",
    "displaynameshort": "",
    "initspeed": 580,
    "inventoryplacements": {},
    "lastroundstracer": 0,
    "library": {
        "libtextdesc": ""
    },
    "mass": 12,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "",
    "namesound": "magazine",
    "picture": "A3/Weapons_F_Exp/Data/UI/icon_10Rnd_50BW_Mag_F_ca.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "tracersevery": 0,
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}