d = {
    "ammo": "B_762x51_Ball",
    "author": "Bohemia Interactive",
    "count": 10,
    "descriptionshort": "Caliber: 7.62x51 mm NATO<br />Rounds: 10<br />Used in: Mk18 ABR, Mk-I EMR, Mk14, SPAR-17",
    "displayname": "7.62 mm 10rnd Mk14 Mag",
    "displaynameshort": "",
    "dlc": "Enoch",
    "initspeed": 850,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 6,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "a3/Weapons_F_Enoch/MagazineProxies/mag_762x51_mk14_10rnd",
    "modelspecialisproxy": 1,
    "namesound": "magazine",
    "picture": "a3/Weapons_F_Enoch/MagazineProxies/data/UI/icon_10Rnd_Mk14_762x51_Mag_ca.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}