d = {
    "ammo": "B_762x51_Ball",
    "author": "Bohemia Interactive",
    "count": 10,
    "descriptionshort": "Caliber: 7.62x54 mm<br />Rounds: 10<br />Used in: Rahim",
    "displayname": "7.62 mm 10Rnd Mag",
    "displaynameshort": "",
    "initspeed": 830,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 8,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "a3/Weapons_F_Mark/MagazineProxies/mag_762x51_mk14_20rnd",
    "modelspecialisproxy": 1,
    "namesound": "magazine",
    "picture": "A3/Weapons_F_EPA/Data/ui/M_10Rnd_762x51_CA.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}