d = {
    "ammo": "B_338_Ball",
    "author": "Bohemia Interactive",
    "count": 10,
    "descriptionshort": "Caliber: .338 Lapua Magnum<br />Rounds: 10<br />Used in: MAR-10",
    "displayname": ".338 LM 10Rnd Mag",
    "displaynameshort": "",
    "initspeed": 915,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 14,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "",
    "namesound": "magazine",
    "picture": "A3/Weapons_F_Mark/Data/UI/M_338_CA.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}