d = {
    "ammo": "B_93x64_Ball",
    "author": "Bohemia Interactive",
    "count": 150,
    "descriptionshort": "Caliber: 9.3x64mm<br />Rounds: 150<br />Used in: Navid",
    "displayname": "9.3mm 150Rnd Belt",
    "displaynameshort": "",
    "initspeed": 785,
    "inventoryplacements": {},
    "lastroundstracer": 6,
    "library": {
        "libtextdesc": ""
    },
    "mass": 70,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "",
    "namesound": "magazine",
    "picture": "A3/Weapons_F_Mark/Data/UI/M_93x64_CA.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "tracersevery": 3,
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}