d = {
    "ammo": "B_762x51_Tracer_Green",
    "author": "Bohemia Interactive",
    "count": 150,
    "descriptionshort": "Caliber: 7.62x54 mm<br/>Rounds: 150<br />Used in: Zafir",
    "displayname": "7.62 mm 150Rnd Box",
    "displaynameshort": "",
    "initspeed": 860,
    "inventoryplacements": {},
    "lastroundstracer": 4,
    "library": {
        "libtextdesc": ""
    },
    "mass": 50,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "",
    "namesound": "mgun",
    "picture": "A3/Weapons_F_Beta/Data/UI/m_150Rnd_762x51_CA.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "tracersevery": 5,
    "type": "2*\t\t256",
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}