d = {
    "ammo": "B_556x45_Ball_Tracer_Red",
    "author": "Bohemia Interactive",
    "count": 150,
    "descriptionshort": "Caliber: 5.56x45 mm<br />Rounds: 150<br />Used in: SPAR-16/S",
    "displayname": "5.56 mm 150Rnd Mag",
    "displaynameshort": "",
    "initspeed": 930,
    "inventoryplacements": {},
    "lastroundstracer": 4,
    "library": {
        "libtextdesc": ""
    },
    "mass": 30,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "a3/Weapons_F_Exp/MagazineProxies/mag_556x45_stanag_150rnd.p3d",
    "modelspecialisproxy": 1,
    "namesound": "magazine",
    "picture": "A3/Weapons_F_Exp/Data/UI/icon_150Rnd_556x45_Drum_Mag_F_ca.paa",
    "quickreload": 0,
    "reloadaction": "GestureReloadSPAR_02",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "tracersevery": 0,
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}