d = {
    "ammo": "B_9x21_Ball_Tracer_Yellow",
    "author": "Bohemia Interactive",
    "count": 16,
    "descriptionshort": "Caliber: 9x21 mm<br />Rounds: 16<br />Used in: PDW2000, P07, ROOK-40",
    "displayname": "9 mm 16Rnd Reload Tracer (Yellow) Mag",
    "displaynameshort": "",
    "initspeed": 410,
    "inventoryplacements": {},
    "lastroundstracer": 4,
    "library": {
        "libtextdesc": ""
    },
    "mass": 6,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "",
    "namesound": "magazine",
    "picture": "A3/weapons_f/data/ui/M_16Rnd_9x21_CA.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "tracersevery": 0,
    "type": 16,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}