d = {
    "ammo": "B_556x45_Ball_Tracer_Yellow",
    "author": "Bohemia Interactive",
    "count": 200,
    "descriptionshort": "Caliber: 5.56x45 mm<br />Rounds: 200<br />Used in: LIM-85",
    "displayname": "5.56 mm 200Rnd Reload Tracer (Yellow) Box",
    "displaynameshort": "",
    "initspeed": 915,
    "inventoryplacements": {},
    "lastroundstracer": 4,
    "library": {
        "libtextdesc": ""
    },
    "mass": 40,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "",
    "namesound": "magazine",
    "picture": "A3/Weapons_F_Exp/Data/UI/icon_200Rnd_556x45_Box_F_ca.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "tracersevery": 4,
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}