d = {
    "ammo": "B_762x51_Ball",
    "author": "Bohemia Interactive",
    "count": 200,
    "descriptionshort": "Caliber: 7.62x51 mm<br />Rounds: 2000<br />Used in: AH-9",
    "displayname": "7.62 mm Minigun Belt",
    "displaynamemfdformat": "COAX",
    "displaynameshort": "",
    "initspeed": 860,
    "inventoryplacements": {},
    "lastroundstracer": 4,
    "library": {
        "libtextdesc": ""
    },
    "mass": 8,
    "maxleadspeed": 36.1111,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "",
    "namesound": "mgun",
    "picture": "",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "tracersevery": 5,
    "type": 0,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 0,
    "weight": 0
}