d = {
    "ammo": "CMflareAmmo",
    "author": "Bohemia Interactive",
    "count": 240,
    "descriptionshort": "",
    "displayname": "",
    "displaynameshort": "",
    "initspeed": 30,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 8,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "",
    "namesound": "magazine",
    "picture": "",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 1,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}