d = {
    "ammo": "B_45ACP_Ball_Green",
    "author": "Bohemia Interactive",
    "count": 30,
    "descriptionshort": "Caliber: .45 ACP Tracers - Green<br />Rounds: 30<br />Used in: Vermin SMG",
    "displayname": ".45 ACP 30Rnd Vermin Tracers (Green) Mag",
    "displaynameshort": "Tracer",
    "initspeed": 280,
    "inventoryplacements": {},
    "lastroundstracer": 30,
    "library": {
        "libtextdesc": ""
    },
    "mass": 10,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "",
    "namesound": "magazine",
    "picture": "A3/Weapons_F/Data/UI/M_30Rnd_45ACP_CA.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "tracersevery": 1,
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}