d = {
    "ammo": "B_762x39_Ball_Green_F",
    "author": "Bohemia Interactive",
    "count": 30,
    "descriptionshort": "Caliber: 7.62x39 mm<br />Rounds: 30<br />Used in: AK-12, AK-12 GL, AKM",
    "displayname": "7.62 mm 30Rnd AKM Tracer (Green) Mag",
    "displaynameshort": "Tracer",
    "initspeed": 715,
    "inventoryplacements": {},
    "lastroundstracer": 30,
    "library": {
        "libtextdesc": ""
    },
    "mass": 10,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "a3/Weapons_F_Exp/MagazineProxies/mag_762x39_akm_30rnd.p3d",
    "modelspecialisproxy": 1,
    "namesound": "magazine",
    "picture": "A3/Weapons_F_Exp/Data/UI/icon_30Rnd_762x39_Mag_Tracer_Green_F_ca.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "tracersevery": 1,
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}