d = {
    "ammo": "G_40mm_SmokeGreen",
    "author": "Bohemia Interactive",
    "count": 3,
    "deleteifempty": 0,
    "descriptionshort": "Type: Smoke Rounds - Green<br />Rounds: 3<br />Used in: 3GL",
    "displayname": "3Rnd 3GL Smoke Rounds (Green)",
    "displaynameshort": "Green Smoke",
    "initspeed": 80,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 12,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "a3/Weapons_F/MagazineProxies/mag_40x36_HE_1rnd.p3d",
    "modelspecialisproxy": 1,
    "namesound": "",
    "picture": "A3/Weapons_f/Data/UI/gear_UGL_Smokeshell_green_CA.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "type": 16,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}