d = {
    "ammo": "BombCluster_01_Ammo_F",
    "author": "Bohemia Interactive",
    "count": 4,
    "descriptionshort": "750lb, laser-guided cluster bomb",
    "displayname": "CBU-85",
    "displaynameshort": "Cluster Bomb",
    "initspeed": 0,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 8,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "",
    "namesound": "cannon",
    "picture": "",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "type": 0,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 0,
    "weight": 0
}