d = {
    "ammo": "M_Titan_AA_long",
    "author": "Bohemia Interactive",
    "count": 4,
    "descriptionshort": "Medium-range, radar-guided, air-to-air missile with high-explosive warhead",
    "displayname": "Titan Missile",
    "displaynamemfdformat": "\u0417-\u0412 \u0420\u0410\u041a\u0415\u0422\u0410",
    "displaynameshort": "AA",
    "initspeed": 25,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 8,
    "maxleadspeed": 694.444,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "",
    "namesound": "missiles",
    "picture": "",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "type": 0,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 0,
    "weight": 0
}