d = {
    "ammo": "B_762x39_Ball_F",
    "author": "Bohemia Interactive",
    "count": 75,
    "descriptionshort": "Caliber: 7.62x39 mm<br />Rounds: 75<br />Used in: RPK-12, AK-12, AK-12 GL, AKM",
    "displayname": "7.62 mm 75Rnd AKM Mag",
    "displaynameshort": "",
    "dlc": "Enoch",
    "initspeed": 715,
    "inventoryplacements": {},
    "lastroundstracer": 4,
    "library": {
        "libtextdesc": ""
    },
    "mass": 26,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "a3/Weapons_F_Enoch/MagazineProxies/mag_762x39_akm_75rnd",
    "modelspecialisproxy": 1,
    "namesound": "magazine",
    "picture": "a3/Weapons_F_Enoch/MagazineProxies/data/UI/icon_75Rnd_762x39_Mag_F_CA.paa",
    "quickreload": 0,
    "reloadaction": "GestureReloadAK12_Drum",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "tracersevery": 0,
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}