d = {
    "ammo": "Chemlight_green",
    "author": "Bohemia Interactive",
    "count": 1,
    "descriptionshort": "Type: Light - Green<br />Rounds: 1<br />Used in: Hand",
    "displayname": "Chemlight (Green)",
    "displaynameshort": "Green Light",
    "initspeed": 14,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 2,
    "maxleadspeed": 6.94444,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/Weapons_f/chemlight/chemlight_green",
    "modelspecial": "",
    "namesound": "Chemlight",
    "namesoundweapon": "Chemlight",
    "picture": "A3/Weapons_F/Data/UI/M_chemlight_green_CA.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 2,
    "weaponpoolavailable": 1,
    "weight": 0
}