d = {
    "ammo": "F_20mm_White",
    "author": "Bohemia Interactive",
    "count": 1,
    "descriptionshort": "Type: Flare Rounds - White<br />Rounds: 1<br />Used in: Flare Gun",
    "displayname": "Flare (White)",
    "displaynameshort": "White Flare",
    "initspeed": 80,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 4,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_f/ammo/flare_white",
    "modelspecial": "",
    "namesound": "",
    "picture": "A3/Weapons_F/Data/UI/gear_flare_white_ca.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "type": 16,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}