d = {
    "ammo": "GrenadeHand_stone",
    "author": "Bohemia Interactive",
    "count": 1,
    "descriptionshort": "Just an ordinary run-of-the-mill stone",
    "displayname": "Stone",
    "displaynameshort": "Stone",
    "initspeed": 18,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 10,
    "maxleadspeed": 6.94444,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/Weapons_f/ammo/Handgrenade",
    "modelspecial": "",
    "namesound": "handgrenade",
    "picture": "A3/Weapons_F/Data/UI/gear_M67_CA.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 1,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 0.1,
    "weaponpoolavailable": 1,
    "weight": 0
}