d = {
    "ammo": "GrenadeHand",
    "author": "Bohemia Interactive",
    "count": 1,
    "descriptionshort": "Type: Defensive Grenade<br />Rounds: 1<br />Used in: Hand",
    "displayname": "RGO Grenade",
    "displaynameshort": "RGO Grenade",
    "initspeed": 18,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 10,
    "maxleadspeed": 6.94444,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/Weapons_f/ammo/Handgrenade",
    "modelspecial": "",
    "namesound": "handgrenade",
    "picture": "A3/Weapons_F/Data/UI/gear_M67_CA.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}