d = {
    "ammo": "ammo_Missile_Cruise_01_Cluster",
    "author": "Bohemia Interactive",
    "count": 18,
    "descriptionshort": "Long-range, data link guided, surface-to-surface missile with cluster munitions",
    "displayname": "Cruise Missile Cluster",
    "displaynameshort": "VCM Cluster",
    "initspeed": 12,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 8,
    "maxleadspeed": 1.38889,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/weapons_F/ammo/mag_univ.p3d",
    "modelspecial": "",
    "namesound": "missiles",
    "picture": "",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "type": 0,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 0,
    "weight": 0
}