d = {
    "ammo": "",
    "author": "Bohemia Interactive",
    "count": 30,
    "descriptionshort": "",
    "displayname": "Money",
    "displaynameshort": "",
    "initspeed": 900,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 5,
    "maxleadspeed": 25,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/Structures_F/Items/Valuables/Money_F",
    "modelspecial": "",
    "namesound": "magazine",
    "picture": "a3/Missions_F_Oldman/Props/data/Money_ca.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 1,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 1,
    "weight": 0
}