d = {
    "ammo": "ammo_Missile_BIM9X",
    "author": "Bohemia Interactive",
    "count": 1,
    "descriptionshort": "Short-range, infrared-guided, air-to-air missile with high-explosive warhead",
    "displayname": "BIM 9X AA x1",
    "displaynameshort": "AA SR",
    "ejectspeed": [
        1,
        0,
        0
    ],
    "hardpoints": [
        "B_BIM9X",
        "I_BIM9X"
    ],
    "initspeed": 0,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 8,
    "maxleadspeed": 700,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "mfdelements": {
        "plane_fighter_01": {
            "bones": {
                "center": {
                    "pos": [
                        0,
                        0
                    ],
                    "type": "fixed"
                }
            },
            "draw": {
                "default": {
                    "alpha": 0.22,
                    "color": [
                        0,
                        0.12,
                        0
                    ],
                    "condition": "PylonAmmoRelative>0",
                    "pylontext1": {
                        "align": "center",
                        "down": [
                            "Center",
                            1,
                            [
                                -0.005,
                                0.065
                            ],
                            1
                        ],
                        "pos": [
                            "Center",
                            1,
                            [
                                -0.005,
                                0.02
                            ],
                            1
                        ],
                        "right": [
                            "Center",
                            1,
                            [
                                0.045,
                                0.02
                            ],
                            1
                        ],
                        "scale": 1,
                        "source": "static",
                        "sourcescale": 1,
                        "text": "IR",
                        "type": "text"
                    },
                    "shape": {
                        "points": [
                            [
                                "Center",
                                [
                                    0,
                                    -0.0147436
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0075,
                                    -0.0127679
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.01299,
                                    -0.00737179
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.015,
                                    0
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.01299,
                                    0.00737179
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0075,
                                    0.0127679
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0,
                                    0.0147436
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0075,
                                    0.0127679
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.01299,
                                    0.00737179
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.015,
                                    0
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.01299,
                                    -0.00737179
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0075,
                                    -0.0127679
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0,
                                    -0.0147436
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    0.0106066,
                                    -0.0104253
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0212132,
                                    -0.0208506
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    0.0106066,
                                    0.0104253
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0212132,
                                    0.0208506
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    -0.0106066,
                                    0.0104253
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0212132,
                                    0.0208506
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    -0.0106066,
                                    -0.0104253
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0212132,
                                    -0.0208506
                                ],
                                1
                            ],
                            []
                        ],
                        "type": "line",
                        "width": 4
                    }
                },
                "empty": {
                    "alpha": 1,
                    "background": {
                        "points": [
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.0106066,
                                        -0.0104253
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.015,
                                        6.44463e-10
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.0106066,
                                        0.0104253
                                    ],
                                    1
                                ]
                            ],
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.0106066,
                                        0.0104253
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -1.31134e-09,
                                        0.0147436
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.0106066,
                                        0.0104253
                                    ],
                                    1
                                ]
                            ],
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.0106066,
                                        0.0104253
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.015,
                                        -1.75816e-10
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.0106066,
                                        -0.0104253
                                    ],
                                    1
                                ]
                            ],
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.0106066,
                                        -0.0104253
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        2.62268e-09,
                                        -0.0147436
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.0106066,
                                        -0.0104253
                                    ],
                                    1
                                ]
                            ]
                        ],
                        "type": "polygon"
                    },
                    "color": [
                        1,
                        0,
                        0,
                        1
                    ],
                    "condition": "PylonAmmoRelative <= 0",
                    "pylontext1": {
                        "align": "center",
                        "down": [
                            "Center",
                            1,
                            [
                                -0.005,
                                0.065
                            ],
                            1
                        ],
                        "pos": [
                            "Center",
                            1,
                            [
                                -0.005,
                                0.02
                            ],
                            1
                        ],
                        "right": [
                            "Center",
                            1,
                            [
                                0.045,
                                0.02
                            ],
                            1
                        ],
                        "scale": 1,
                        "source": "static",
                        "sourcescale": 1,
                        "text": "IR",
                        "type": "text"
                    },
                    "shape": {
                        "points": [
                            [
                                "Center",
                                [
                                    0,
                                    -0.0147436
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0075,
                                    -0.0127679
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.01299,
                                    -0.00737179
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.015,
                                    0
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.01299,
                                    0.00737179
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0075,
                                    0.0127679
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0,
                                    0.0147436
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0075,
                                    0.0127679
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.01299,
                                    0.00737179
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.015,
                                    0
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.01299,
                                    -0.00737179
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0075,
                                    -0.0127679
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0,
                                    -0.0147436
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    0.0106066,
                                    -0.0104253
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0212132,
                                    -0.0208506
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    0.0106066,
                                    0.0104253
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0212132,
                                    0.0208506
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    -0.0106066,
                                    0.0104253
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0212132,
                                    0.0208506
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    -0.0106066,
                                    -0.0104253
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0212132,
                                    -0.0208506
                                ],
                                1
                            ],
                            []
                        ],
                        "type": "line",
                        "width": 4
                    }
                },
                "selected": {
                    "alpha": 1,
                    "background": {
                        "points": [
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.0106066,
                                        -0.0104253
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.015,
                                        6.44463e-10
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.0106066,
                                        0.0104253
                                    ],
                                    1
                                ]
                            ],
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.0106066,
                                        0.0104253
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -1.31134e-09,
                                        0.0147436
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.0106066,
                                        0.0104253
                                    ],
                                    1
                                ]
                            ],
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.0106066,
                                        0.0104253
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.015,
                                        -1.75816e-10
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.0106066,
                                        -0.0104253
                                    ],
                                    1
                                ]
                            ],
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.0106066,
                                        -0.0104253
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        2.62268e-09,
                                        -0.0147436
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.0106066,
                                        -0.0104253
                                    ],
                                    1
                                ]
                            ]
                        ],
                        "type": "polygon"
                    },
                    "color": [
                        0,
                        0.12,
                        0
                    ],
                    "condition": "(PylonSelected +  PylonAmmoRelative)/2",
                    "pylontext1": {
                        "align": "center",
                        "down": [
                            "Center",
                            1,
                            [
                                -0.005,
                                0.065
                            ],
                            1
                        ],
                        "pos": [
                            "Center",
                            1,
                            [
                                -0.005,
                                0.02
                            ],
                            1
                        ],
                        "right": [
                            "Center",
                            1,
                            [
                                0.045,
                                0.02
                            ],
                            1
                        ],
                        "scale": 1,
                        "source": "static",
                        "sourcescale": 1,
                        "text": "IR",
                        "type": "text"
                    },
                    "shape": {
                        "points": [
                            [
                                "Center",
                                [
                                    0,
                                    -0.0147436
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0075,
                                    -0.0127679
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.01299,
                                    -0.00737179
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.015,
                                    0
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.01299,
                                    0.00737179
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0075,
                                    0.0127679
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0,
                                    0.0147436
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0075,
                                    0.0127679
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.01299,
                                    0.00737179
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.015,
                                    0
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.01299,
                                    -0.00737179
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0075,
                                    -0.0127679
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0,
                                    -0.0147436
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    0.0106066,
                                    -0.0104253
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0212132,
                                    -0.0208506
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    0.0106066,
                                    0.0104253
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0212132,
                                    0.0208506
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    -0.0106066,
                                    0.0104253
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0212132,
                                    0.0208506
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    -0.0106066,
                                    -0.0104253
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0212132,
                                    -0.0208506
                                ],
                                1
                            ],
                            []
                        ],
                        "type": "line",
                        "width": 4
                    }
                }
            }
        },
        "plane_fighter_04": {
            "bones": {
                "center": {
                    "pos": [
                        0,
                        0
                    ],
                    "type": "fixed"
                }
            },
            "draw": {
                "default": {
                    "alpha": 0.22,
                    "color": [
                        0,
                        0.12,
                        0
                    ],
                    "condition": "PylonAmmoRelative>0",
                    "pylontext1": {
                        "align": "center",
                        "down": [
                            "Center",
                            1,
                            [
                                -0.005,
                                0.065
                            ],
                            1
                        ],
                        "pos": [
                            "Center",
                            1,
                            [
                                -0.005,
                                0.02
                            ],
                            1
                        ],
                        "right": [
                            "Center",
                            1,
                            [
                                0.045,
                                0.02
                            ],
                            1
                        ],
                        "scale": 1,
                        "source": "static",
                        "sourcescale": 1,
                        "text": "IR",
                        "type": "text"
                    },
                    "shape": {
                        "points": [
                            [
                                "Center",
                                [
                                    0,
                                    -0.00982906
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.005,
                                    -0.00851197
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.00866,
                                    -0.00491453
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.01,
                                    0
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.00866,
                                    0.00491453
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.005,
                                    0.00851197
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0,
                                    0.00982906
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.005,
                                    0.00851197
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.00866,
                                    0.00491453
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.01,
                                    0
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.00866,
                                    -0.00491453
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.005,
                                    -0.00851197
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0,
                                    -0.00982906
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    0.00707107,
                                    -0.00695019
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0141421,
                                    -0.0139004
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    0.00707107,
                                    0.00695019
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0141421,
                                    0.0139004
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    -0.00707107,
                                    0.00695019
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0141421,
                                    0.0139004
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    -0.00707107,
                                    -0.00695019
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0141421,
                                    -0.0139004
                                ],
                                1
                            ],
                            []
                        ],
                        "type": "line",
                        "width": 4
                    }
                },
                "empty": {
                    "alpha": 1,
                    "background": {
                        "points": [
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.00707107,
                                        -0.00695019
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.01,
                                        4.29642e-10
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.00707107,
                                        0.00695019
                                    ],
                                    1
                                ]
                            ],
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.00707107,
                                        0.00695019
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -8.74228e-10,
                                        0.00982906
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.00707107,
                                        0.00695019
                                    ],
                                    1
                                ]
                            ],
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.00707107,
                                        0.00695019
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.01,
                                        -1.1721e-10
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.00707107,
                                        -0.00695019
                                    ],
                                    1
                                ]
                            ],
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.00707107,
                                        -0.00695019
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        1.74846e-09,
                                        -0.00982906
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.00707107,
                                        -0.00695019
                                    ],
                                    1
                                ]
                            ]
                        ],
                        "type": "polygon"
                    },
                    "color": [
                        1,
                        0,
                        0,
                        1
                    ],
                    "condition": "PylonAmmoRelative <= 0",
                    "pylontext1": {
                        "align": "center",
                        "down": [
                            "Center",
                            1,
                            [
                                -0.005,
                                0.065
                            ],
                            1
                        ],
                        "pos": [
                            "Center",
                            1,
                            [
                                -0.005,
                                0.02
                            ],
                            1
                        ],
                        "right": [
                            "Center",
                            1,
                            [
                                0.045,
                                0.02
                            ],
                            1
                        ],
                        "scale": 1,
                        "source": "static",
                        "sourcescale": 1,
                        "text": "IR",
                        "type": "text"
                    },
                    "shape": {
                        "points": [
                            [
                                "Center",
                                [
                                    0,
                                    -0.00982906
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.005,
                                    -0.00851197
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.00866,
                                    -0.00491453
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.01,
                                    0
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.00866,
                                    0.00491453
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.005,
                                    0.00851197
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0,
                                    0.00982906
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.005,
                                    0.00851197
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.00866,
                                    0.00491453
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.01,
                                    0
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.00866,
                                    -0.00491453
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.005,
                                    -0.00851197
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0,
                                    -0.00982906
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    0.00707107,
                                    -0.00695019
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0141421,
                                    -0.0139004
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    0.00707107,
                                    0.00695019
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0141421,
                                    0.0139004
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    -0.00707107,
                                    0.00695019
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0141421,
                                    0.0139004
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    -0.00707107,
                                    -0.00695019
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0141421,
                                    -0.0139004
                                ],
                                1
                            ],
                            []
                        ],
                        "type": "line",
                        "width": 4
                    }
                },
                "selected": {
                    "alpha": 1,
                    "background": {
                        "points": [
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.00707107,
                                        -0.00695019
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.01,
                                        4.29642e-10
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.00707107,
                                        0.00695019
                                    ],
                                    1
                                ]
                            ],
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.00707107,
                                        0.00695019
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -8.74228e-10,
                                        0.00982906
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.00707107,
                                        0.00695019
                                    ],
                                    1
                                ]
                            ],
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.00707107,
                                        0.00695019
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.01,
                                        -1.1721e-10
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.00707107,
                                        -0.00695019
                                    ],
                                    1
                                ]
                            ],
                            [
                                [
                                    "Center",
                                    1,
                                    [
                                        0,
                                        0
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        -0.00707107,
                                        -0.00695019
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        1.74846e-09,
                                        -0.00982906
                                    ],
                                    1
                                ],
                                [
                                    "Center",
                                    [
                                        0.00707107,
                                        -0.00695019
                                    ],
                                    1
                                ]
                            ]
                        ],
                        "type": "polygon"
                    },
                    "color": [
                        0,
                        0.12,
                        0
                    ],
                    "condition": "(PylonSelected +  PylonAmmoRelative)/2",
                    "pylontext1": {
                        "align": "center",
                        "down": [
                            "Center",
                            1,
                            [
                                -0.005,
                                0.065
                            ],
                            1
                        ],
                        "pos": [
                            "Center",
                            1,
                            [
                                -0.005,
                                0.02
                            ],
                            1
                        ],
                        "right": [
                            "Center",
                            1,
                            [
                                0.045,
                                0.02
                            ],
                            1
                        ],
                        "scale": 1,
                        "source": "static",
                        "sourcescale": 1,
                        "text": "IR",
                        "type": "text"
                    },
                    "shape": {
                        "points": [
                            [
                                "Center",
                                [
                                    0,
                                    -0.00982906
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.005,
                                    -0.00851197
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.00866,
                                    -0.00491453
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.01,
                                    0
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.00866,
                                    0.00491453
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.005,
                                    0.00851197
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0,
                                    0.00982906
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.005,
                                    0.00851197
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.00866,
                                    0.00491453
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.01,
                                    0
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.00866,
                                    -0.00491453
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.005,
                                    -0.00851197
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0,
                                    -0.00982906
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    0.00707107,
                                    -0.00695019
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0141421,
                                    -0.0139004
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    0.00707107,
                                    0.00695019
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    0.0141421,
                                    0.0139004
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    -0.00707107,
                                    0.00695019
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0141421,
                                    0.0139004
                                ],
                                1
                            ],
                            [],
                            [
                                "Center",
                                [
                                    -0.00707107,
                                    -0.00695019
                                ],
                                1
                            ],
                            [
                                "Center",
                                [
                                    -0.0141421,
                                    -0.0139004
                                ],
                                1
                            ],
                            []
                        ],
                        "type": "line",
                        "width": 4
                    }
                }
            }
        }
    },
    "minthrowintensitycoef": 0.3,
    "model": "A3/Weapons_F_Jets/Ammo/PylonPod_Missile_AA_08_x1_F",
    "modelspecial": "",
    "namesound": "missiles",
    "picture": "",
    "pylonweapon": "weapon_BIM9xLauncher",
    "quickreload": 0,
    "reloadaction": "",
    "reloadsound": [
        "A3/sounds_f/dummysound",
        0.000316228,
        1,
        20
    ],
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "sound": [
        "A3/sounds_f/dummysound",
        1,
        1,
        1300
    ],
    "type": 0,
    "useaction": 0,
    "useactiontitle": "",
    "value": 1,
    "weaponpoolavailable": 0,
    "weight": 0
}