d = {
    "ammo": "SmokeShellPurple",
    "author": "Bohemia Interactive",
    "count": 1,
    "descriptionshort": "Type: Smoke Grenade - Purple<br />Rounds: 1<br />Used in: Hand",
    "displayname": "Smoke Grenade (Purple)",
    "displaynameshort": "Purple Smoke",
    "initspeed": 22,
    "inventoryplacements": {},
    "library": {
        "libtextdesc": ""
    },
    "mass": 4,
    "maxleadspeed": 6.94444,
    "maxthrowholdtime": 2,
    "maxthrowintensitycoef": 1.4,
    "minthrowintensitycoef": 0.3,
    "model": "A3/Weapons_f/ammo/smokegrenade_purple",
    "modelspecial": "",
    "namesound": "smokeshell",
    "namesoundweapon": "smokeshell",
    "picture": "A3/Weapons_f/data/ui/gear_smokegrenade_purple_ca.paa",
    "quickreload": 0,
    "reloadaction": "",
    "scope": 2,
    "selectionfireanim": "zasleh",
    "simulation": "ProxyMagazines",
    "type": 256,
    "useaction": 0,
    "useactiontitle": "",
    "value": 2,
    "weaponpoolavailable": 1,
    "weight": 0
}