rhs_mag_vog30_30 = {
    "displayname": "VOG30",
    "displaynameshort": "VOG30",
    "count": 30,
    # Ammo: CfgMagazines|RHS_mag_VOG30_30|ammo [Indent level: 1],
    "ammo": {
        "_dictAmmoName": "rhs_ammo_VOG30",
        "hit": 40,
        "indirecthit": 7,
        "indirecthitrange": 4.174,
        "dangerradiushit": 50,
        "suppressionradiushit": 20,
        # Class: CfgAmmo|rhs_ammo_VOG30|CamShakeExplode [Indent level: 1],
        "camshakeexplode": {
            "power": "(30*0.2)",
            "duration": "((round (30^0.5))*0.2 max 0.2)",
            "frequency": 20,
            "distance": "((3 + 30^0.5)*8)"
        },
        # Class: CfgAmmo|rhs_ammo_VOG30|CamShakeHit [Indent level: 1],
        "camshakehit": {
            "power": 20,
            "duration": "((round (30^0.25))*0.2 max 0.2)",
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo|rhs_ammo_VOG30|CamShakeFire [Indent level: 1],
        "camshakefire": {
            "power": "(0^0.25)",
            "duration": "((round (0^0.5))*0.2 max 0.2)",
            "frequency": 20,
            "distance": "((0^0.5)*8)"
        },
        # Class: CfgAmmo|rhs_ammo_VOG30|CamShakePlayerFire [Indent level: 1],
        "camshakeplayerfire": {
            "power": 0,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "explosionsoundeffect": "DefaultExplosion",
        "simulation": "shotShell",
        "model": "A3|weapons_f|ammo|UGL_slug",
        "warheadname": "HE",
        "visiblefire": 1,
        "audiblefire": 30,
        "visiblefiretime": 3,
        "explosive": 1,
        "cost": 10,
        "deflecting": 5,
        "airfriction": -0.001,
        "fusedistance": 15,
        "whistledist": 16,
        "typicalspeed": 185,
        "caliber": 2,
        "soundhit1": ["A3|Sounds_F|arsenal|explosives|Grenades|Explosion_gng_grenades_01",3.16228,1,1500],
        "soundhit2": ["A3|Sounds_F|arsenal|explosives|Grenades|Explosion_gng_grenades_02",3.16228,1,1500],
        "soundhit3": ["A3|Sounds_F|arsenal|explosives|Grenades|Explosion_gng_grenades_03",3.16228,1,1500],
        "soundhit4": ["A3|Sounds_F|arsenal|explosives|Grenades|Explosion_gng_grenades_04",3.16228,1,1500],
        "multisoundhit": ["soundHit1",0.25,"soundHit2",0.25,"soundHit3",0.25,"soundHit4",0.25],
        "soundsetexplosion": ["jsrs_grenade_explosion_soundset","jsrs_40mm_explosion_stereo_soundset","jsrs_grenade_explosion_reverb_soundset"],
        "soundhit5": ["A3|Sounds_F|weapons|Explosion|gr_explosion_5",3.16228,1,1400],
        "soundhit6": ["A3|Sounds_F|weapons|Explosion|gr_explosion_6",3.16228,1,1400],
        "supersoniccracknear": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_close",0.316228,1,50],
        "supersoniccrackfar": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_50meters",0.223872,1,75],
        "cratereffects": "GrenadeCrater",
        "explosioneffects": "GrenadeExplosion",
        "muzzleeffect": "",
        "explosionforcecoef": 4,
        "shadow": 1,
        "simulationstep": 0.05,
        "soundhit": ["",10,1],
        "soundfly": ["",3.16228e-005,1],
        "soundengine": ["",0.0001,4],
        "timetolive": 20,
        "access": 3,
        "underwaterhitrangecoef": 1,
        "iscrateroriented": 0,
        "proxyshape": "",
        "cratershape": "",
        "weapontype": "Default",
        "animated": 0,
        "maxspeed": 0,
        "cartridge": "",
        "tracercolor": [0.7,0.7,0.5,0.04],
        "tracercolorr": [0.7,0.7,0.5,0.04],
        "soundfall": ["",1,1],
        "soundfakefall": ["soundFall",1],
        "hitgroundsoft": ["soundHit",1],
        "hitgroundhard": ["soundHit",1],
        "hitman": ["soundHit",1],
        "hitarmor": ["soundHit",1],
        "hitiron": ["soundHit",1],
        "hitbuilding": ["soundHit",1],
        "hitfoliage": ["soundHit",1],
        "hitwood": ["soundHit",1],
        "hitglass": ["soundHit",1],
        "hitglassarmored": ["soundHit",1],
        "hitconcrete": ["soundHit",1],
        "hitrubber": ["soundHit",1],
        "hitplastic": ["soundHit",1],
        "hitdefault": ["soundHit",1],
        "hitmetal": ["soundHit",1],
        "hitmetalplate": ["soundHit",1],
        "hittyre": ["soundHit",1],
        "hitwater": ["soundHit",1],
        "soundimpact": ["",1,1],
        "impactgroundsoft": ["soundImpact",1],
        "impactgroundhard": ["soundImpact",1],
        "impactman": ["soundImpact",1],
        "impactiron": ["soundImpact",1],
        "impactarmor": ["soundImpact",1],
        "impactbuilding": ["soundImpact",1],
        "impactfoliage": ["soundImpact",1],
        "impactwood": ["soundImpact",1],
        "impactglass": ["soundImpact",1],
        "impactglassarmored": ["soundImpact",1],
        "impactconcrete": ["soundImpact",1],
        "impactrubber": ["soundImpact",1],
        "impactplastic": ["soundImpact",1],
        "impactdefault": ["soundImpact",1],
        "impactmetal": ["soundImpact",1],
        "impactmetalplate": ["soundImpact",1],
        "impacttyre": ["soundImpact",1],
        "impactwater": ["soundImpact",1],
        "grenadefiresound": [],
        "grenadeburningsound": [],
        "deflectionslowdown": 0.8,
        "craterwatereffects": "ImpactEffectsWater",
        "effectsmissile": "ExplosionEffects",
        "effectsmissileinit": "",
        "effectssmoke": "SmokeShellWhite",
        "effectsfire": "CannonFire",
        "effectflare": "FlareShell",
        "effectfly": "",
        "minejumpeffects": "",
        "watereffectoffset": 0.45,
        "directionalexplosion": 0,
        "explosionangle": 60,
        "explosiondir": "explosionDir",
        "explosionpos": "explosionPos",
        "explosioneffectsdir": "explosionDir",
        "minimumsafezone": 0.1,
        "soundtrigger": [],
        "soundactivation": [],
        "sounddeactivation": [],
        "mintimetolive": 0,
        "irlock": 0,
        "airlock": 0,
        "laserlock": 0,
        "nvlock": 0,
        "artillerylock": 0,
        "hitonwater": 0,
        "lockseekradius": 100,
        "manualcontrol": 0,
        "maxcontrolrange": 350,
        "maneuvrability": 1,
        "tracklead": 1,
        "trackoversteer": 1,
        "missilelockcone": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "locktype": 0,
        "maverickweaponindexoffset": 0,
        "sideairfriction": 1,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "autoseektarget": 0,
        "shootdistraction": -1,
        "explosiontime": 0,
        "inittime": 0,
        "thrusttime": 1.5,
        "thrust": 210,
        "icon": "",
        "submunitionammo": "",
        "explosiontype": "explosive",
        "minetrigger": "RangeTrigger",
        "mineboundingtime": 3,
        "mineboundingdist": 3,
        "mineinconspicuousness": 10,
        "minefloating": -1,
        "minedivespeed": 1,
        "mineplacedist": 0.5,
        # Class: CfgAmmo|Default|HitEffects [Indent level: 1],
        "hiteffects": {
            "vehicle": "ImpactMetal",
            "object": "ImpactConcrete"
        },
        "suppressionradiusbulletclose": -1,
        "dangerradiusbulletclose": -1,
        "whistleonfire": 0,
        # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
        "nvgmarkers": {
        },
        "mindamageforcamshakehit": 0.55,
        # Class: CfgAmmo|Default|EventHandlers [Indent level: 1],
        "eventhandlers": {
        },
    },
    "eventhandlers": "rhs_ammo_VOG30",
    "initspeed": 185,
    "namesound": "handgrenade",
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadaction": "",
    "maxleadspeed": 100,
    "weaponpoolavailable": 0,
    "scope": 1,
    "value": 1,
    "model": "A3|weapons_F|ammo|mag_univ.p3d",
    "picture": "",
    "modelspecial": "",
    "useaction": 0,
    "useactiontitle": "",
    "selectionfireanim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    # Class: CfgMagazines|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "descriptionshort": "",
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0
}