rhs_mag_3bm46_10 = {
    "displayName": "APFSDS-T 3BM48",
    "displayNameShort": "3BM48",
    # Ammo: rhs_ammo_3bm46,
    "ammo": {
        "ammo": "rhs_ammo_3bm46",
        "caliber": 0.1,
        "submunitionAmmo": "rhs_ammo_3bm46_penetrator",
        "submunitionDirectionType": "SubmunitionModelDirection",
        "submunitionInitialOffset": [0,0,-0.1],
        "submunitionParentSpeedCoef": 1,
        "submunitionInitSpeed": 0,
        "triggerOnImpact": 1,
        "deleteParentWhenTriggered": 0,
        "indirectHit": 40,
        "indirectHitRange": 0.5,
        "typicalSpeed": 1700,
        "simulationStep": 0.01,
        "effectFly": "RHS_125mm_Sabot_Eject",
        "cost": 500,
        "hit": 250,
        "explosive": 0,
        "deflecting": 10,
        "timeToLive": 15,
        "whistleOnFire": 1,
        "whistleDist": 14,
        "muzzleEffect": "",
        "model": "A3|Weapons_f|Data|bullettracer|shell_tracer_red",
        "warheadName": "AP",
        "dangerRadiusHit": 100,
        "suppressionRadiusHit": 18,
        "airFriction": -3.96e-005,
        "CraterEffects": "ExploAmmoCrater",
        "explosionEffects": "ExploAmmoExplosion",
        "tracerScale": 3,
        "tracerStartTime": 0.1,
        "tracerEndTime": 3,
        "soundHit1": ["A3|Sounds_F|arsenal|explosives|shells|Tank_shell_explosion_01",1.77828,1,1800],
        "soundHit2": ["A3|Sounds_F|arsenal|explosives|shells|Tank_shell_explosion_02",1.77828,1,1800],
        "soundHit3": ["A3|Sounds_F|arsenal|explosives|shells|Tank_shell_explosion_03",1.77828,1,1800],
        "soundHit4": ["A3|Sounds_F|arsenal|explosives|shells|Tank_shell_explosion_04",1.77828,1,1800],
        "multiSoundHit": ["soundHit1",0.25,"soundHit2",0.25,"soundHit3",0.25,"soundHit4",0.25],
        # Class: CfgAmmo\Sh_120mm_APFSDS\HitEffects [Indent level: 1],
        "HitEffects": {
            "hitMetal": "ImpactMetalSabotBig",
            "hitMetalPlate": "ImpactMetalSabotBig",
            "hitBuilding": "ImpactConcreteSabot",
            "hitConcrete": "ImpactConcreteSabot",
            "hitGroundSoft": "ImpactEffectsGroundSabot",
            "hitGroundHard": "ImpactEffectsGroundSabot",
            "hitWater": "ImpactEffectsWater",
            "default_mat": "ImpactEffectsGroundSabot"
        },
        "aiAmmoUsageFlags": "128 + 512",
        # Class: CfgAmmo\Sh_120mm_APFSDS\CamShakeExplode [Indent level: 1],
        "CamShakeExplode": {
            "power": 13.4164,
            "duration": 2.6,
            "frequency": 20,
            "distance": 40.2492
        },
        # Class: CfgAmmo\Sh_120mm_APFSDS\CamShakeHit [Indent level: 1],
        "CamShakeHit": {
            "power": 180,
            "duration": 0.8,
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo\Sh_120mm_APFSDS\CamShakeFire [Indent level: 1],
        "CamShakeFire": {
            "power": 3.30975,
            "duration": 2.2,
            "frequency": 20,
            "distance": 87.6356
        },
        # Class: CfgAmmo\Sh_120mm_APFSDS\CamShakePlayerFire [Indent level: 1],
        "CamShakePlayerFire": {
            "power": 0.02,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "SoundSetExplosion": ["Shell105mm130mm_Exp_SoundSet","Shell105mm130mm_Tail_SoundSet","Explosion_Debris_SoundSet"],
        "supersonicCrackNear": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_close",0.316228,1,50],
        "supersonicCrackFar": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_50meters",0.223872,1,150],
        "CraterWaterEffects": "ImpactEffectsWaterHE",
        "visibleFire": 64,
        "audibleFire": 250,
        "deflectionDirDistribution": 0.39,
        "penetrationDirDistribution": 0.26,
        "soundFakeFall0": ["a3|Sounds_F|weapons|falling_bomb|fall_01",3.16228,1,1000],
        "soundFakeFall1": ["a3|Sounds_F|weapons|falling_bomb|fall_02",3.16228,1,1000],
        "soundFakeFall2": ["a3|Sounds_F|weapons|falling_bomb|fall_03",3.16228,1,1000],
        "soundFakeFall3": ["a3|Sounds_F|weapons|falling_bomb|fall_04",3.16228,1,1000],
        "soundFakeFall": ["soundFakeFall0",0.25,"soundFakeFall1",0.25,"soundFakeFall2",0.25,"soundFakeFall3",0.25],
        "soundSetSonicCrack": ["bulletSonicCrack_SoundSet","bulletSonicCrackTail_SoundSet"],
        "simulation": "shotShell",
        "soundHit": ["",316.228,1],
        "soundFly": ["",0.0316228,4],
        "visibleFireTime": 10,
        "access": 3,
        "underwaterHitRangeCoef": 1,
        "explosionForceCoef": 1,
        "isCraterOriented": 0,
        "proxyShape": "",
        "craterShape": "",
        "weaponType": "Default",
        "animated": 0,
        "shadow": 0,
        "maxSpeed": 0,
        "cartridge": "",
        "tracerColor": [0.7,0.7,0.5,0.04],
        "tracerColorR": [0.7,0.7,0.5,0.04],
        "soundEngine": ["",1,1],
        "soundFall": ["",1,1],
        "hitGroundSoft": ["soundHit",1],
        "hitGroundHard": ["soundHit",1],
        "hitMan": ["soundHit",1],
        "hitArmor": ["soundHit",1],
        "hitIron": ["soundHit",1],
        "hitBuilding": ["soundHit",1],
        "hitFoliage": ["soundHit",1],
        "hitWood": ["soundHit",1],
        "hitGlass": ["soundHit",1],
        "hitGlassArmored": ["soundHit",1],
        "hitConcrete": ["soundHit",1],
        "hitRubber": ["soundHit",1],
        "hitPlastic": ["soundHit",1],
        "hitDefault": ["soundHit",1],
        "hitMetal": ["soundHit",1],
        "hitMetalplate": ["soundHit",1],
        "hitTyre": ["soundHit",1],
        "hitWater": ["soundHit",1],
        "soundImpact": ["",1,1],
        "impactGroundSoft": ["soundImpact",1],
        "impactGroundHard": ["soundImpact",1],
        "impactMan": ["soundImpact",1],
        "impactIron": ["soundImpact",1],
        "impactArmor": ["soundImpact",1],
        "impactBuilding": ["soundImpact",1],
        "impactFoliage": ["soundImpact",1],
        "impactWood": ["soundImpact",1],
        "impactGlass": ["soundImpact",1],
        "impactGlassArmored": ["soundImpact",1],
        "impactConcrete": ["soundImpact",1],
        "impactRubber": ["soundImpact",1],
        "impactPlastic": ["soundImpact",1],
        "impactDefault": ["soundImpact",1],
        "impactMetal": ["soundImpact",1],
        "impactMetalplate": ["soundImpact",1],
        "impactTyre": ["soundImpact",1],
        "impactWater": ["soundImpact",1],
        "grenadeFireSound": [],
        "grenadeBurningSound": [],
        "deflectionSlowDown": 0.8,
        "effectsMissile": "ExplosionEffects",
        "effectsMissileInit": "",
        "effectsSmoke": "SmokeShellWhite",
        "effectsFire": "CannonFire",
        "effectFlare": "FlareShell",
        "mineJumpEffects": "",
        "waterEffectOffset": 0.45,
        "directionalExplosion": 0,
        "explosionAngle": 60,
        "explosionDir": "explosionDir",
        "explosionPos": "explosionPos",
        "explosionEffectsDir": "explosionDir",
        "minimumSafeZone": 0.1,
        "soundTrigger": [],
        "soundActivation": [],
        "soundDeactivation": [],
        "explosionSoundEffect": "",
        "minTimeToLive": 0,
        "irLock": 0,
        "airLock": 0,
        "laserLock": 0,
        "nvLock": 0,
        "artilleryLock": 0,
        "hitOnWater": 0,
        "lockSeekRadius": 100,
        "manualControl": 0,
        "maxControlRange": 350,
        "maneuvrability": 1,
        "trackLead": 1,
        "trackOversteer": 1,
        "missileLockCone": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "lockType": 0,
        "maverickweaponIndexOffset": 0,
        "sideAirFriction": 1,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "autoSeekTarget": 0,
        "shootDistraction": -1,
        "explosionTime": 0,
        "fuseDistance": 0,
        "initTime": 0,
        "thrustTime": 1.5,
        "thrust": 210,
        "icon": "",
        "explosionType": "explosive",
        "mineTrigger": "RangeTrigger",
        "mineBoundingTime": 3,
        "mineBoundingDist": 3,
        "mineInconspicuousness": 10,
        "mineFloating": -1,
        "mineDiveSpeed": 1,
        "minePlaceDist": 0.5,
        "suppressionRadiusBulletClose": -1,
        "dangerRadiusBulletClose": -1,
        # Class: CfgAmmo\Default\NVGMarkers [Indent level: 1],
        "NVGMarkers": {
        },
        "minDamageForCamShakeHit": 0.55,
        # Class: CfgAmmo\Default\EventHandlers [Indent level: 1],
        "EventHandlers": {
        },
    },
    "initSpeed": 1700,
    "reloadTime": 6.5,
    "magazineReloadTime": 6.5,
    "lastRoundsTracer": 5,
    "tracersEvery": 1,
    "count": 10,
    "scope": 2,
    "rhs_magazineIndex": 1,
    "maxLeadSpeed": 80,
    "muzzleImpulseFactor": ["14*0.2",14],
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "A3|weapons_F|ammo|mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines\Default\InventoryPlacements [Indent level: 1],
    "InventoryPlacements": {
    },
    # Class: CfgMagazines\Default\Library [Indent level: 1],
    "Library": {
        "libTextDesc": ""
    },
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0,
}