RHS_mag_VOG30_30 = {
    "bin|config.bin/CfgMagazines/RHS_mag_VOG30_30/displayName": "VOG30",
    "bin|config.bin/CfgMagazines/RHS_mag_VOG30_30/displayNameShort": "VOG30",
    "bin|config.bin/CfgMagazines/RHS_mag_VOG30_30/count": 30,
    "bin|config.bin/CfgMagazines/RHS_mag_VOG30_30/ammo": "rhs_ammo_VOG30"    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_VOG30/hit": 40    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_VOG30/indirectHit": 7    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_VOG30/indirectHitRange": 4.174    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_VOG30/dangerRadiusHit": 50    ,
    "bin|config.bin/CfgAmmo/rhs_ammo_VOG30/suppressionRadiusHit": 20    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/explosionSoundEffect": "DefaultExplosion"    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/simulation": "shotShell"    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/model": "\A3\weapons_f\ammo\UGL_slug"    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/warheadName": "HE"    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/visibleFire": 1    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/audibleFire": 30    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/visibleFireTime": 3    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/explosive": 1    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/cost": 10    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/deflecting": 5    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/airFriction": -0.001    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/fuseDistance": 15    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/whistleDist": 16    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/typicalSpeed": 185    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/caliber": 2    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/multiSoundHit": ["soundHit1",0.25,"soundHit2",0.25,"soundHit3",0.25,"soundHit4",0.25]    ,
    "bin|config.bin/CfgAmmo/G_40mm_HE/SoundSetExplosion": ["GrenadeHe_Exp_SoundSet","GrenadeHe_Tail_SoundSet","Explosion_Debris_SoundSet"]    ,
    "bin|config.bin/CfgAmmo/GrenadeBase/supersonicCrackNear": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_close",0.316228,1,50]    ,
    "bin|config.bin/CfgAmmo/GrenadeBase/supersonicCrackFar": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_50meters",0.223872,1,75]    ,
    "bin|config.bin/CfgAmmo/GrenadeBase/CraterEffects": "GrenadeCrater"    ,
    "bin|config.bin/CfgAmmo/GrenadeBase/explosionEffects": "GrenadeExplosion"    ,
    "bin|config.bin/CfgAmmo/GrenadeBase/muzzleEffect": ""    ,
    "bin|config.bin/CfgAmmo/GrenadeBase/explosionForceCoef": 4    ,
    "bin|config.bin/CfgAmmo/GrenadeBase/shadow": 1    ,
    "bin|config.bin/CfgAmmo/GrenadeCore/simulationStep": 0.05    ,
    "bin|config.bin/CfgAmmo/GrenadeCore/timeToLive": 20    ,
    "bin|config.bin/CfgAmmo/Default/access": 3    ,
    "bin|config.bin/CfgAmmo/Default/underwaterHitRangeCoef": 1    ,
    "bin|config.bin/CfgAmmo/Default/isCraterOriented": 0    ,
    "bin|config.bin/CfgAmmo/Default/proxyShape": ""    ,
    "bin|config.bin/CfgAmmo/Default/craterShape": ""    ,
    "bin|config.bin/CfgAmmo/Default/weaponType": "Default"    ,
    "bin|config.bin/CfgAmmo/Default/animated": 0    ,
    "bin|config.bin/CfgAmmo/Default/maxSpeed": 0    ,
    "bin|config.bin/CfgAmmo/Default/cartridge": ""    ,
    "bin|config.bin/CfgAmmo/Default/tracerColor": [0.7,0.7,0.5,0.04]    ,
    "bin|config.bin/CfgAmmo/Default/tracerColorR": [0.7,0.7,0.5,0.04]    ,
    "bin|config.bin/CfgAmmo/Default/hitGroundSoft": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitGroundHard": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitMan": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitArmor": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitIron": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitBuilding": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitFoliage": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitWood": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitGlass": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitGlassArmored": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitConcrete": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitRubber": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitPlastic": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitDefault": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitMetal": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitMetalplate": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitTyre": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/hitWater": ["soundHit",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGroundSoft": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGroundHard": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactMan": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactIron": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactArmor": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactBuilding": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactFoliage": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactWood": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGlass": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactGlassArmored": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactConcrete": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactRubber": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactPlastic": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactDefault": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactMetal": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactMetalplate": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactTyre": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/impactWater": ["soundImpact",1]    ,
    "bin|config.bin/CfgAmmo/Default/grenadeFireSound": []    ,
    "bin|config.bin/CfgAmmo/Default/grenadeBurningSound": []    ,
    "bin|config.bin/CfgAmmo/Default/deflectionSlowDown": 0.8    ,
    "bin|config.bin/CfgAmmo/Default/craterWaterEffects": "ImpactEffectsWater"    ,
    "bin|config.bin/CfgAmmo/Default/effectsMissile": "ExplosionEffects"    ,
    "bin|config.bin/CfgAmmo/Default/effectsMissileInit": ""    ,
    "bin|config.bin/CfgAmmo/Default/effectsSmoke": "SmokeShellWhite"    ,
    "bin|config.bin/CfgAmmo/Default/effectsFire": "CannonFire"    ,
    "bin|config.bin/CfgAmmo/Default/effectFlare": "FlareShell"    ,
    "bin|config.bin/CfgAmmo/Default/effectFly": ""    ,
    "bin|config.bin/CfgAmmo/Default/mineJumpEffects": ""    ,
    "bin|config.bin/CfgAmmo/Default/waterEffectOffset": 0.45    ,
    "bin|config.bin/CfgAmmo/Default/directionalExplosion": 0    ,
    "bin|config.bin/CfgAmmo/Default/explosionAngle": 60    ,
    "bin|config.bin/CfgAmmo/Default/explosionDir": "explosionDir"    ,
    "bin|config.bin/CfgAmmo/Default/explosionPos": "explosionPos"    ,
    "bin|config.bin/CfgAmmo/Default/explosionEffectsDir": "explosionDir"    ,
    "bin|config.bin/CfgAmmo/Default/minimumSafeZone": 0.1    ,
    "bin|config.bin/CfgAmmo/Default/minTimeToLive": 0    ,
    "bin|config.bin/CfgAmmo/Default/irLock": 0    ,
    "bin|config.bin/CfgAmmo/Default/airLock": 0    ,
    "bin|config.bin/CfgAmmo/Default/laserLock": 0    ,
    "bin|config.bin/CfgAmmo/Default/nvLock": 0    ,
    "bin|config.bin/CfgAmmo/Default/artilleryLock": 0    ,
    "bin|config.bin/CfgAmmo/Default/hitOnWater": 0    ,
    "bin|config.bin/CfgAmmo/Default/lockSeekRadius": 100    ,
    "bin|config.bin/CfgAmmo/Default/manualControl": 0    ,
    "bin|config.bin/CfgAmmo/Default/maxControlRange": 350    ,
    "bin|config.bin/CfgAmmo/Default/maneuvrability": 1    ,
    "bin|config.bin/CfgAmmo/Default/trackLead": 1    ,
    "bin|config.bin/CfgAmmo/Default/trackOversteer": 1    ,
    "bin|config.bin/CfgAmmo/Default/missileLockCone": 0    ,
    "bin|config.bin/CfgAmmo/Default/weaponLockSystem": 0    ,
    "bin|config.bin/CfgAmmo/Default/cmImmunity": 1    ,
    "bin|config.bin/CfgAmmo/Default/lockType": 0    ,
    "bin|config.bin/CfgAmmo/Default/maverickweaponIndexOffset": 0    ,
    "bin|config.bin/CfgAmmo/Default/sideAirFriction": 1    ,
    "bin|config.bin/CfgAmmo/Default/artilleryDispersion": 1    ,
    "bin|config.bin/CfgAmmo/Default/artilleryCharge": 1    ,
    "bin|config.bin/CfgAmmo/Default/autoSeekTarget": 0    ,
    "bin|config.bin/CfgAmmo/Default/shootDistraction": -1    ,
    "bin|config.bin/CfgAmmo/Default/explosionTime": 0    ,
    "bin|config.bin/CfgAmmo/Default/initTime": 0    ,
    "bin|config.bin/CfgAmmo/Default/thrustTime": 1.5    ,
    "bin|config.bin/CfgAmmo/Default/thrust": 210    ,
    "bin|config.bin/CfgAmmo/Default/icon": ""    ,
    "bin|config.bin/CfgAmmo/Default/submunitionAmmo": ""    ,
    "bin|config.bin/CfgAmmo/Default/explosionType": "explosive"    ,
    "bin|config.bin/CfgAmmo/Default/mineTrigger": "RangeTrigger"    ,
    "bin|config.bin/CfgAmmo/Default/mineBoundingTime": 3    ,
    "bin|config.bin/CfgAmmo/Default/mineBoundingDist": 3    ,
    "bin|config.bin/CfgAmmo/Default/mineInconspicuousness": 10    ,
    "bin|config.bin/CfgAmmo/Default/mineFloating": -1    ,
    "bin|config.bin/CfgAmmo/Default/mineDiveSpeed": 1    ,
    "bin|config.bin/CfgAmmo/Default/minePlaceDist": 0.5    ,
    "bin|config.bin/CfgAmmo/Default/suppressionRadiusBulletClose": -1    ,
    "bin|config.bin/CfgAmmo/Default/dangerRadiusBulletClose": -1    ,
    "bin|config.bin/CfgAmmo/Default/whistleOnFire": 0    ,
    "bin|config.bin/CfgAmmo/Default/minDamageForCamShakeHit": 0.55,
    "bin|config.bin/CfgMagazines/RHS_mag_VOG30_30/initSpeed": 185,
    "bin|config.bin/CfgMagazines/RHS_mag_VOG30_30/nameSound": "handgrenade",
    "bin|config.bin/CfgMagazines/VehicleMagazine/author": "Bohemia Interactive",
    "bin|config.bin/CfgMagazines/VehicleMagazine/type": 0,
    "bin|config.bin/CfgMagazines/VehicleMagazine/reloadAction": "",
    "bin|config.bin/CfgMagazines/VehicleMagazine/maxLeadSpeed": 100,
    "bin|config.bin/CfgMagazines/VehicleMagazine/weaponPoolAvailable": 0,
    "bin|config.bin/CfgMagazines/CA_Magazine/scope": 1,
    "bin|config.bin/CfgMagazines/CA_Magazine/value": 1,
    "bin|config.bin/CfgMagazines/CA_Magazine/model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "bin|config.bin/CfgMagazines/CA_Magazine/picture": "",
    "bin|config.bin/CfgMagazines/CA_Magazine/modelSpecial": "",
    "bin|config.bin/CfgMagazines/CA_Magazine/useAction": 0,
    "bin|config.bin/CfgMagazines/CA_Magazine/useActionTitle": "",
    "bin|config.bin/CfgMagazines/CA_Magazine/selectionFireAnim": "zasleh",
    "bin|config.bin/CfgMagazines/CA_Magazine/mass": 8,
    "bin|config.bin/CfgMagazines/Default/simulation": "ProxyMagazines",
    "bin|config.bin/CfgMagazines/Default/weight": 0,
    "bin|config.bin/CfgMagazines/Default/descriptionShort": "",
    "bin|config.bin/CfgMagazines/Default/maxThrowHoldTime": 2,
    "bin|config.bin/CfgMagazines/Default/minThrowIntensityCoef": 0.3,
    "bin|config.bin/CfgMagazines/Default/maxThrowIntensityCoef": 1.4,
    "bin|config.bin/CfgMagazines/Default/quickReload": 0
}