rhs_mag_9m117m_8 = {
    "count": 8,
    "displayName": "ATGM 9M117M",
    "displayNameShort": "9M117M",
    # Ammo: rhs_ammo_9m117m,
    "ammo": {
        "ammo": "rhs_ammo_9m117m",
        "warheadName": "TandemHEAT",
        "submunitionAmmo": "rhs_ammo_9m117m_penetrator",
        "submunitionDirectionType": "SubmunitionModelDirection",
        "submunitionInitialOffset": [0,0,-0.2],
        "submunitionParentSpeedCoef": 0,
        "submunitionInitSpeed": 1000,
        "triggerOnImpact": 1,
        "deleteParentWhenTriggered": 0,
        "model": "rhsafrf|addons|rhs_heavyweapons|atgm|rhs_atgm_base",
        "indirectHitRange": 4.2,
        "cost": 100,
        "canlock": 1,
        "irlock": 1,
        "airLock": 1,
        "laserlock": 0,
        "manualControl": 0,
        "missileManualControlCone": 20,
        "maxcontrolrange": 5000,
        "weaponLockSystem": "1+4",
        "maxSpeed": 300,
        "typicalSpeed": 120,
        "inittime": 0,
        "thrust": 112,
        "thrusttime": 6,
        "timetolive": 30,
        "sideairfriction": 0.1,
        "trackOversteer": 0.3,
        "trackLead": 1,
        "maneuvrability": 17,
        "rhs_saclos": 1,
        "rhs_ballisticMode": 1,
        "rhs_guideMode": "BEAMRIDER",
        # Class: CfgAmmo\rhs_ammo_9m117\EventHandlers [Indent level: 1],
        "EventHandlers": {
            # Class: CfgAmmo\rhs_ammo_9m117\EventHandlers\RHS_Guidance [Indent level: 2]
            "RHS_Guidance": {
                "fired": "_this call RHS_fnc_saclosGuide"
            },
            # Class: CfgAmmo\MissileBase\EventHandlers\RHS_APS_FiredEH [Indent level: 2],
            "RHS_APS_FiredEH": {
                "fired": "_this spawn rhs_fnc_aps_missileFired"
            }
        },
        "scope": 2,
        "hit": 240,
        "indirectHit": 20,
        "simulationStep": 0.005,
        "deflecting": 0,
        "fuseDistance": 50,
        "whistleDist": 2,
        "flightProfiles": ["Direct"],
        "CraterEffects": "ATRocketCrater",
        "explosionEffects": "ATRocketExplosion",
        "effectsMissileInit": "RocketBackEffectsNLAW",
        "effectsMissile": "missile2",
        "textureType": "semi",
        "lockType": 0,
        "soundFly": ["A3|Sounds_F|weapons|Rockets|rocket_fly_2",1,1,800],
        # Class: CfgAmmo\rhs_ammo_atgmCore_base\Components [Indent level: 1],
        "Components": {
            # Class: CfgAmmo\rhs_ammo_atgmCore_base\Components\SensorsManagerComponent [Indent level: 2]
            "SensorsManagerComponent": {
                # Class: CfgAmmo\rhs_ammo_atgmCore_base\Components\SensorsManagerComponent\Components [Indent level: 3]
                "Components": {
                    # Class: CfgAmmo\rhs_ammo_atgmCore_base\Components\SensorsManagerComponent\Components\VisualSensorComponent [Indent level: 4]
                    "VisualSensorComponent": {
                        # Class: CfgAmmo\rhs_ammo_atgmCore_base\Components\SensorsManagerComponent\Components\VisualSensorComponent\AirTarget [Indent level: 5]
                        "AirTarget": {
                            "minRange": 500,
                            "maxRange": 5000,
                            "objectDistanceLimitCoef": -1,
                            "viewDistanceLimitCoef": 1
                        },
                        # Class: CfgAmmo\rhs_ammo_atgmCore_base\Components\SensorsManagerComponent\Components\VisualSensorComponent\GroundTarget [Indent level: 5],
                        "GroundTarget": {
                            "minRange": 500,
                            "maxRange": 5000,
                            "objectDistanceLimitCoef": 1,
                            "viewDistanceLimitCoef": 1
                        },
                        "maxTrackableSpeed": 35,
                        "nightRangeCoef": 0.8,
                        "angleRangeHorizontal": 5,
                        "angleRangeVertical": 5,
                        "componentType": "VisualSensorComponent",
                        "maxFogSeeThrough": 0.94,
                        "color": [1,1,0.5,0.8],
                        "typeRecognitionDistance": 2000,
                        "allowsMarking": 1,
                        "groundNoiseDistanceCoef": -1,
                        "maxGroundNoiseDistance": -1,
                        "minSpeedThreshold": 0,
                        "maxSpeedThreshold": 0,
                        "animDirection": "",
                        "aimDown": 0,
                        "minTrackableSpeed": -1e+010,
                        "minTrackableATL": -1e+010,
                        "maxTrackableATL": 1e+010
                    }
                }
            }
        },
        "explosive": 1,
        "aiAmmoUsageFlags": "128 + 512",
        "explosionSoundEffect": "DefaultExplosion",
        "muzzleEffect": "",
        "airFriction": 0.085,
        "missileLockCone": 4.5,
        "missileKeepLockedCone": 160,
        "missileLockMaxDistance": 2000,
        "missileLockMinDistance": 50,
        "missileLockMaxSpeed": 35,
        "cmImmunity": 0.4,
        # Class: CfgAmmo\M_Titan_AT\Direct [Indent level: 1],
        "Direct": {
        },
        # Class: CfgAmmo\M_Titan_AT\TopDown [Indent level: 1],
        "TopDown": {
            "ascendHeight": 150,
            "descendDistance": 180,
            "minDistance": 180,
            "ascendAngle": 30
        },
        # Class: CfgAmmo\M_Titan_AT\CamShakeExplode [Indent level: 1],
        "CamShakeExplode": {
            "power": 11,
            "duration": 1.4,
            "frequency": 20,
            "distance": 91.3296
        },
        # Class: CfgAmmo\M_Titan_AT\CamShakeHit [Indent level: 1],
        "CamShakeHit": {
            "power": 110,
            "duration": 0.6,
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo\M_Titan_AT\CamShakeFire [Indent level: 1],
        "CamShakeFire": {
            "power": 2.78316,
            "duration": 1.6,
            "frequency": 20,
            "distance": 61.9677
        },
        # Class: CfgAmmo\M_Titan_AT\CamShakePlayerFire [Indent level: 1],
        "CamShakePlayerFire": {
            "power": 3,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "SoundSetExplosion": ["jsrs_rocket_explosion_soundset","jsrs_rocket_explosion_stereo_soundset","jsrs_shell_explosion_reverb_soundset"],
        "soundsetsoniccrack": ["jsrs_sc_rocket_flyby_soundset"],
        "ace_frag_skip": 1,
        "soundHit1": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_01",2.51189,1,2000],
        "soundHit2": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_02",2.51189,1,2000],
        "soundHit3": ["A3|Sounds_F|arsenal|weapons|Launchers|Titan|Explosion_titan_missile_03",2.51189,1,2000],
        "multiSoundHit": ["soundHit1",0.34,"soundHit2",0.33,"soundHit3",0.33],
        "soundEngine": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|soundfly1.ogg",1,1,750],
        "supersonicCrackNear": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_close",0.398107,1,20],
        "supersonicCrackFar": ["A3|Sounds_F|weapons|Explosion|supersonic_crack_50meters",0.316228,1,50],
        "dangerRadiusHit": -1,
        "suppressionRadiusHit": 30,
        # Class: CfgAmmo\MissileBase\HitEffects [Indent level: 1],
        "HitEffects": {
            "hitWater": "ImpactEffectsWaterRocket"
        },
        "maverickWeaponIndexOffset": 0,
        "htMin": 60,
        "htMax": 1800,
        "afMax": 200,
        "mfMax": 100,
        "mFact": 0,
        "tBody": 0,
        "soundsetfly": ["jsrs_sc_rocket_flyby_soundset"],
        "ace_rearm_caliber": 250,
        "ACE_damageType": "explosive",
        "simulation": "shotMissile",
        "visibleFire": 32,
        "audibleFire": 32,
        "visibleFireTime": 20,
        "soundHit": ["",100,1],
        "access": 3,
        "underwaterHitRangeCoef": 1,
        "explosionForceCoef": 1,
        "isCraterOriented": 0,
        "proxyShape": "",
        "craterShape": "",
        "weaponType": "Default",
        "animated": 0,
        "shadow": 0,
        "cartridge": "",
        "tracerColor": [0.7,0.7,0.5,0.04],
        "tracerColorR": [0.7,0.7,0.5,0.04],
        "soundFall": ["",1,1],
        "soundFakeFall": ["soundFall",1],
        "hitGroundSoft": ["soundHit",1],
        "hitGroundHard": ["soundHit",1],
        "hitMan": ["soundHit",1],
        "hitArmor": ["soundHit",1],
        "hitIron": ["soundHit",1],
        "hitBuilding": ["soundHit",1],
        "hitFoliage": ["soundHit",1],
        "hitWood": ["soundHit",1],
        "hitGlass": ["soundHit",1],
        "hitGlassArmored": ["soundHit",1],
        "hitConcrete": ["soundHit",1],
        "hitRubber": ["soundHit",1],
        "hitPlastic": ["soundHit",1],
        "hitDefault": ["soundHit",1],
        "hitMetal": ["soundHit",1],
        "hitMetalplate": ["soundHit",1],
        "hitTyre": ["soundHit",1],
        "hitWater": ["soundHit",1],
        "soundImpact": ["",1,1],
        "impactGroundSoft": ["soundImpact",1],
        "impactGroundHard": ["soundImpact",1],
        "impactMan": ["soundImpact",1],
        "impactIron": ["soundImpact",1],
        "impactArmor": ["soundImpact",1],
        "impactBuilding": ["soundImpact",1],
        "impactFoliage": ["soundImpact",1],
        "impactWood": ["soundImpact",1],
        "impactGlass": ["soundImpact",1],
        "impactGlassArmored": ["soundImpact",1],
        "impactConcrete": ["soundImpact",1],
        "impactRubber": ["soundImpact",1],
        "impactPlastic": ["soundImpact",1],
        "impactDefault": ["soundImpact",1],
        "impactMetal": ["soundImpact",1],
        "impactMetalplate": ["soundImpact",1],
        "impactTyre": ["soundImpact",1],
        "impactWater": ["soundImpact",1],
        "grenadeFireSound": [],
        "grenadeBurningSound": [],
        "deflectionSlowDown": 0.8,
        "craterWaterEffects": "ImpactEffectsWater",
        "effectsSmoke": "SmokeShellWhite",
        "effectsFire": "CannonFire",
        "effectFlare": "FlareShell",
        "effectFly": "",
        "mineJumpEffects": "",
        "waterEffectOffset": 0.45,
        "directionalExplosion": 0,
        "explosionAngle": 60,
        "explosionDir": "explosionDir",
        "explosionPos": "explosionPos",
        "explosionEffectsDir": "explosionDir",
        "minimumSafeZone": 0.1,
        "soundTrigger": [],
        "soundActivation": [],
        "soundDeactivation": [],
        "minTimeToLive": 0,
        "nvLock": 0,
        "artilleryLock": 0,
        "hitOnWater": 0,
        "lockSeekRadius": 100,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "autoSeekTarget": 0,
        "shootDistraction": -1,
        "explosionTime": 0,
        "icon": "",
        "explosionType": "explosive",
        "mineTrigger": "RangeTrigger",
        "mineBoundingTime": 3,
        "mineBoundingDist": 3,
        "mineInconspicuousness": 10,
        "mineFloating": -1,
        "mineDiveSpeed": 1,
        "minePlaceDist": 0.5,
        "suppressionRadiusBulletClose": -1,
        "dangerRadiusBulletClose": -1,
        "caliber": 1,
        "whistleOnFire": 0,
        # Class: CfgAmmo\Default\NVGMarkers [Indent level: 1],
        "NVGMarkers": {
        },
        "minDamageForCamShakeHit": 0.55,
    },
    "scope": 2,
    "reloadTime": 12,
    "magazineReloadTime": 12,
    "initSpeed": 80,
    "maxleadspeed": 70,
    "nameSound": "missiles",
    "rhs_magazineIndex": 2,
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "A3|weapons_F|ammo|mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    # Class: CfgMagazines\Default\InventoryPlacements [Indent level: 1],
    "InventoryPlacements": {
    },
    # Class: CfgMagazines\Default\Library [Indent level: 1],
    "Library": {
        "libTextDesc": ""
    },
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0,
}