rhs_mag_3of26_5 = {
    "count": 5,
    "displayName": "HE-FRAG-FS 3OF26",
    "displayNameShort": "3OF26",
    "ammo": "rhs_ammo_3of26",
    "initSpeed": 850,
    "tracersEvery": 0,
    "reloadTime": 6.5,
    "magazineReloadTime": 6.5,
    "muzzleImpulseFactor": ["14*0.5",14],
    "scope": 2,
    "rhs_magazineIndex": 3,
    "maxLeadSpeed": 40,
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}