rhs_mag_127x108mm_50 = {
    "scope": 2,
    "displayName": "12.7x108mm",
    "displayNameShort": "12.7x108mm",
    "count": 50,
    "ammo": "rhs_ammo_127x108mm",
    "initSpeed": 817,
    "tracersEvery": 4,
    "nameSound": "mgun",
    "weight": "0.13*50",
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "maxLeadSpeed": 100,
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}