rhs_mag_s8_12 = {
    "scope": 2,
    "displayName": "S-8 KOM HEAT",
    "displayNameShort": "S-8 KOM",
    "descriptionShort": "HEAT (Penetration: 350mm RHA)",
    # Ammo: rhs_ammo_s8,
    "ammo": {
        "ammo": "rhs_ammo_s8",
        "AIAmmoUsageFlags": "64+128+512",
        "cost": 100,
        "initTime": 0.02,
        "sideAirFriction": 0.003,
        "proxyShape": "A3|Weapons_F_EPC|Ammo|Rocket_03_HE_F.p3d",
        "model": "A3|Weapons_F_EPC|Ammo|Rocket_03_HE_fly_F.p3d",
        "effectsMissile": "RHS_Rocket_Fired",
        "effectsMissileInit": "RHS_Rocket_Init",
        "soundFly": ["A3|Sounds_F|weapons|Rockets|rocket_fly_2",1,1.5,700],
        "submunitionAmmo": "rhs_ammo_s8_penetrator",
        "submunitionDirectionType": "SubmunitionModelDirection",
        "submunitionInitialOffset": [0,0,-0.2],
        "submunitionParentSpeedCoef": 0,
        "submunitionInitSpeed": 1000,
        "triggerOnImpact": 1,
        "deleteParentWhenTriggered": 0,
        "missileLockMaxDistance": 4000,
        "missileLockMinDistance": 700,
        "hit": 400,
        "indirectHit": 60,
        "indirectHitRange": 15,
        "warheadName": "HE",
        "maxSpeed": 590,
        "thrustTime": 0.69,
        "thrust": 1060,
        "airFriction": 0.09,
        "fuseDistance": 50,
        "whistleDist": 30,
        "timeToLive": 15,
        "muzzleEffect": "",
        "simulation": "shotMissile",
        # Class: CfgAmmo\R_80mm_HE\CamShakeExplode [Indent level: 1],
        "CamShakeExplode": {
            "power": 16,
            "duration": 1.8,
            "frequency": 20,
            "distance": 191.554
        },
        # Class: CfgAmmo\R_80mm_HE\CamShakeHit [Indent level: 1],
        "CamShakeHit": {
            "power": 80,
            "duration": 0.6,
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo\R_80mm_HE\CamShakeFire [Indent level: 1],
        "CamShakeFire": {
            "power": 2.9907,
            "duration": 1.8,
            "frequency": 20,
            "distance": 71.5542
        },
        # Class: CfgAmmo\R_80mm_HE\CamShakePlayerFire [Indent level: 1],
        "CamShakePlayerFire": {
            "power": 2,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "CraterEffects": "80mm_Smoke",
        "explosionEffects": "80mm_Explode",
        "SoundSetExplosion": ["jsrs_rocket_explosion_soundset","jsrs_rocket_explosion_stereo_soundset","jsrs_shell_explosion_reverb_soundset"],
        "soundsetsoniccrack": ["jsrs_sc_rocket_flyby_soundset"],
        "ace_frag_skip": 1,
        "ace_rearm_caliber": 80,
        "ace_rearm_dummy": "ace_rearm_R_80mm_HE",
        "dangerRadiusHit": -1,
        "suppressionRadiusHit": 30,
        "soundHit": ["A3|Sounds_F|weapons|Rockets|explosion_missile_02",2.51189,1,2500],
        "explosionSoundEffect": "DefaultExplosion",
        "soundEngine": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|soundfly1.ogg",1,1,750],
        "supersonicCrackNear": ["",1,1,50],
        "supersonicCrackFar": ["",1,1,150],
        # Class: CfgAmmo\RocketBase\HitEffects [Indent level: 1],
        "HitEffects": {
            "hitWater": "ImpactEffectsWaterRocket"
        },
        "soundsetfly": ["jsrs_sc_rocket_flyby_soundset"],
        # Class: CfgAmmo\RocketBase\EventHandlers [Indent level: 1],
        "EventHandlers": {
            # Class: CfgAmmo\RocketBase\EventHandlers\RHS_APS_FiredEH [Indent level: 2]
            "RHS_APS_FiredEH": {
                "fired": "_this spawn rhs_fnc_aps_missileFired"
            }
        },
        "ACE_damageType": "explosive",
        "simulationStep": 0.05,
        "maneuvrability": 0,
        "maxControlRange": 0,
        "visibleFire": 32,
        "audibleFire": 32,
        "visibleFireTime": 20,
        "deflecting": 5,
        "access": 3,
        "underwaterHitRangeCoef": 1,
        "typicalSpeed": 900,
        "explosionForceCoef": 1,
        "isCraterOriented": 0,
        "craterShape": "",
        "weaponType": "Default",
        "animated": 0,
        "shadow": 0,
        "cartridge": "",
        "tracerColor": [0.7,0.7,0.5,0.04],
        "tracerColorR": [0.7,0.7,0.5,0.04],
        "soundFall": ["",1,1],
        "soundFakeFall": ["soundFall",1],
        "hitGroundSoft": ["soundHit",1],
        "hitGroundHard": ["soundHit",1],
        "hitMan": ["soundHit",1],
        "hitArmor": ["soundHit",1],
        "hitIron": ["soundHit",1],
        "hitBuilding": ["soundHit",1],
        "hitFoliage": ["soundHit",1],
        "hitWood": ["soundHit",1],
        "hitGlass": ["soundHit",1],
        "hitGlassArmored": ["soundHit",1],
        "hitConcrete": ["soundHit",1],
        "hitRubber": ["soundHit",1],
        "hitPlastic": ["soundHit",1],
        "hitDefault": ["soundHit",1],
        "hitMetal": ["soundHit",1],
        "hitMetalplate": ["soundHit",1],
        "hitTyre": ["soundHit",1],
        "hitWater": ["soundHit",1],
        "soundImpact": ["",1,1],
        "impactGroundSoft": ["soundImpact",1],
        "impactGroundHard": ["soundImpact",1],
        "impactMan": ["soundImpact",1],
        "impactIron": ["soundImpact",1],
        "impactArmor": ["soundImpact",1],
        "impactBuilding": ["soundImpact",1],
        "impactFoliage": ["soundImpact",1],
        "impactWood": ["soundImpact",1],
        "impactGlass": ["soundImpact",1],
        "impactGlassArmored": ["soundImpact",1],
        "impactConcrete": ["soundImpact",1],
        "impactRubber": ["soundImpact",1],
        "impactPlastic": ["soundImpact",1],
        "impactDefault": ["soundImpact",1],
        "impactMetal": ["soundImpact",1],
        "impactMetalplate": ["soundImpact",1],
        "impactTyre": ["soundImpact",1],
        "impactWater": ["soundImpact",1],
        "grenadeFireSound": [],
        "grenadeBurningSound": [],
        "deflectionSlowDown": 0.8,
        "explosive": 1,
        "craterWaterEffects": "ImpactEffectsWater",
        "effectsSmoke": "SmokeShellWhite",
        "effectsFire": "CannonFire",
        "effectFlare": "FlareShell",
        "effectFly": "",
        "mineJumpEffects": "",
        "waterEffectOffset": 0.45,
        "directionalExplosion": 0,
        "explosionAngle": 60,
        "explosionDir": "explosionDir",
        "explosionPos": "explosionPos",
        "explosionEffectsDir": "explosionDir",
        "minimumSafeZone": 0.1,
        "soundTrigger": [],
        "soundActivation": [],
        "soundDeactivation": [],
        "minTimeToLive": 0,
        "irLock": 0,
        "airLock": 0,
        "laserLock": 0,
        "nvLock": 0,
        "artilleryLock": 0,
        "hitOnWater": 0,
        "lockSeekRadius": 100,
        "manualControl": 0,
        "trackLead": 1,
        "trackOversteer": 1,
        "missileLockCone": 0,
        "weaponLockSystem": 0,
        "cmImmunity": 1,
        "lockType": 0,
        "maverickweaponIndexOffset": 0,
        "artilleryDispersion": 1,
        "artilleryCharge": 1,
        "autoSeekTarget": 0,
        "shootDistraction": -1,
        "explosionTime": 0,
        "icon": "",
        "explosionType": "explosive",
        "mineTrigger": "RangeTrigger",
        "mineBoundingTime": 3,
        "mineBoundingDist": 3,
        "mineInconspicuousness": 10,
        "mineFloating": -1,
        "mineDiveSpeed": 1,
        "minePlaceDist": 0.5,
        "suppressionRadiusBulletClose": -1,
        "dangerRadiusBulletClose": -1,
        "caliber": 1,
        "whistleOnFire": 0,
        # Class: CfgAmmo\Default\NVGMarkers [Indent level: 1],
        "NVGMarkers": {
        },
        "minDamageForCamShakeHit": 0.55,
    },
    "count": 12,
    "initSpeed": 44,
    "nameSound": "rockets",
    "maxleadspeed": 30,
    "weight": 155.6,
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "A3|weapons_F|ammo|mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    # Class: CfgMagazines\Default\InventoryPlacements [Indent level: 1],
    "InventoryPlacements": {
    },
    # Class: CfgMagazines\Default\Library [Indent level: 1],
    "Library": {
        "libTextDesc": ""
    },
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0,
}