rhs_mag_3bm22_14 = {
    "count": 14,
    "displayName": "APFSDS-T 3BM22",
    "displayNameShort": "3BM22",
    "ammo": "rhs_ammo_3bm22",
    "initSpeed": 1760,
    "reloadTime": 6.5,
    "magazineReloadTime": 6.5,
    "lastRoundsTracer": 5,
    "tracersEvery": 1,
    "scope": 2,
    "rhs_magazineIndex": 1,
    "maxLeadSpeed": 80,
    "muzzleImpulseFactor": ["14*0.2",14],
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}