rhs_mag_9m119_4 = {
    "count": 4,
    "scope": 2,
    "canLock": 0,
    "displayName": "ATGM 9M119",
    "displayNameShort": "9M119",
    "ammo": "rhs_ammo_9m119",
    "reloadTime": 30,
    "magazineReloadTime": 30,
    "initSpeed": 125,
    "maxleadspeed": 50,
    "nameSound": "missiles",
    "rhs_magazineIndex": 4,
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}