rhs_mag_PG9V = {
    "displayName": "HEAT PG9V",
    "displayNameShort": "PG9V",
    "ammo": "rhs_ammo_pg9v",
    "count": 1,
    "initSpeed": 435,
    "scope": 2,
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "maxLeadSpeed": 100,
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}