rhs_mag_3bk31_8 = {
    "displayName": "HEAT-FS 3BK31",
    "displayNameShort": "3BK31",
    "ammo": "rhs_ammo_3bk31",
    "initSpeed": 905,
    "reloadTime": 6.5,
    "magazineReloadTime": 6.5,
    "count": 8,
    "tracersEvery": 1,
    "muzzleImpulseFactor": ["14*0.2",14],
    "scope": 2,
    "maxLeadSpeed": 27,
    "rhs_magazineIndex": 2,
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}