rhs_mag_og15v_20 = {
    "count": 20,
    "scope": 2,
    "displayName": "HE-FRAG OG15V",
    "displayNameShort": "OG15V",
    "ammo": "rhs_ammo_og15v",
    "initSpeed": 290,
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "maxLeadSpeed": 100,
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "nameSound": "magazine",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}