rhs_mag_s8_12 = {
    "scope": 2,
    "displayName": "S-8 KOM HEAT",
    "displayNameShort": "S-8 KOM",
    "descriptionShort": "HEAT (Penetration: 350mm RHA)",
    "ammo": "rhs_ammo_s8",
    "count": 12,
    "initSpeed": 44,
    "nameSound": "rockets",
    "maxleadspeed": 30,
    "weight": 155.6,
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}