rhs_mag_127x108mm_1SLT_1470 = {
    # Ammo: CfgMagazines|rhs_mag_127x108mm_1slt_1470|ammo [Indent level: 1],
    "ammo": {
        "ammo": "rhs_ammo_127x108mm_1SLT",
        "submunitionconetype": ["randomcenter",2],
        "submunitionconeangle": 0.207,
        "weapontype": "mGun",
        "explosive": 0,
        "allowagainstinfantry": 1,
        "airlock": 1,
        "airfriction": -0.0009,
        "audiblefire": 22,
        "visiblefire": 22,
        "visiblefiretime": 3,
        "submunitionammo": ["rhs_ammo_127x108mm_notracer",0.85,"rhs_ammo_127x108mm",0.15],
        "cost": 10,
        "triggertime": 0.01,
        "triggerspeedcoef": [0.8,1],
        "model": "A3|Weapons_f|empty",
        "cartridge": "FxCartridge_127",
        "explosioneffects": "",
        "cratereffects": "",
        "hit": 25,
        "timetolive": 15,
        # Class: CfgAmmo|rhs_ammo_127x108mm_x5|CamShakeExplode [Indent level: 1],
        "camshakeexplode": {
            "power": 2.4,
            "duration": 0.6,
            "frequency": 20,
            "distance": 51.7128
        },
        # Class: CfgAmmo|rhs_ammo_127x108mm_x5|CamShakeHit [Indent level: 1],
        "camshakehit": {
            "power": 12,
            "duration": 0.4,
            "frequency": 20,
            "distance": 1
        },
        # Class: CfgAmmo|rhs_ammo_127x108mm_x5|CamShakeFire [Indent level: 1],
        "camshakefire": {
            "power": 1,
            "duration": 0.2,
            "frequency": 20,
            "distance": 8
        },
        # Class: CfgAmmo|rhs_ammo_127x108mm_x5|CamShakePlayerFire [Indent level: 1],
        "camshakeplayerfire": {
            "power": 1,
            "duration": 0.1,
            "frequency": 20,
            "distance": 1
        },
        "soundfakefall1": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_2.ogg",2.5,1,750],
        "soundfakefall2": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_3.ogg",2.5,1,750],
        "soundfakefall3": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_4.ogg",2.5,1,750],
        "soundfakefall4": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_5.ogg",2.5,1,750],
        "soundfakefall5": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_6.ogg",2.5,1,750],
        "soundfakefall6": ["|jsrs_soundmod_complete|JSRS_Soundmod_Soundfiles|warfare|arty_flyby_1.ogg",2.5,1,750],
        "soundfakefall": ["soundfakefall1",0.166,"soundfakefall2",0.166,"soundfakefall3",0.166,"soundfakefall4",0.166,"soundfakefall5",0.166,"soundfakefall6",0.166],
        "simulation": "shotSubmunitions",
        "simulationstep": 0.05,
        "soundhit": ["",316.228,1],
        "soundfly": ["",0.0316228,4],
        "hitonwater": 1,
        "artillerylock": 1,
        "indirecthitrange": 8,
        "deflecting": 5,
        "access": 3,
        "indirecthit": 0,
        "underwaterhitrangecoef": 1,
        "typicalspeed": 900,
        "explosionforcecoef": 1,
        "iscrateroriented": 0,
        "proxyshape": "",
        "cratershape": "",
        "animated": 0,
        "shadow": 0,
        "maxspeed": 0,
        "tracercolor": [0.7,0.7,0.5,0.04],
        "tracercolorr": [0.7,0.7,0.5,0.04],
        "soundengine": ["",1,1],
        "supersoniccracknear": ["",1,1],
        "supersoniccrackfar": ["",1,1],
        "soundfall": ["",1,1],
        "hitgroundsoft": ["soundHit",1],
        "hitgroundhard": ["soundHit",1],
        "hitman": ["soundHit",1],
        "hitarmor": ["soundHit",1],
        "hitiron": ["soundHit",1],
        "hitbuilding": ["soundHit",1],
        "hitfoliage": ["soundHit",1],
        "hitwood": ["soundHit",1],
        "hitglass": ["soundHit",1],
        "hitglassarmored": ["soundHit",1],
        "hitconcrete": ["soundHit",1],
        "hitrubber": ["soundHit",1],
        "hitplastic": ["soundHit",1],
        "hitdefault": ["soundHit",1],
        "hitmetal": ["soundHit",1],
        "hitmetalplate": ["soundHit",1],
        "hittyre": ["soundHit",1],
        "hitwater": ["soundHit",1],
        "soundimpact": ["",1,1],
        "impactgroundsoft": ["soundImpact",1],
        "impactgroundhard": ["soundImpact",1],
        "impactman": ["soundImpact",1],
        "impactiron": ["soundImpact",1],
        "impactarmor": ["soundImpact",1],
        "impactbuilding": ["soundImpact",1],
        "impactfoliage": ["soundImpact",1],
        "impactwood": ["soundImpact",1],
        "impactglass": ["soundImpact",1],
        "impactglassarmored": ["soundImpact",1],
        "impactconcrete": ["soundImpact",1],
        "impactrubber": ["soundImpact",1],
        "impactplastic": ["soundImpact",1],
        "impactdefault": ["soundImpact",1],
        "impactmetal": ["soundImpact",1],
        "impactmetalplate": ["soundImpact",1],
        "impacttyre": ["soundImpact",1],
        "impactwater": ["soundImpact",1],
        "grenadefiresound": [],
        "grenadeburningsound": [],
        "deflectionslowdown": 0.8,
        "craterwatereffects": "ImpactEffectsWater",
        "effectsmissile": "ExplosionEffects",
        "effectsmissileinit": "",
        "effectssmoke": "SmokeShellWhite",
        "effectsfire": "CannonFire",
        "effectflare": "FlareShell",
        "effectfly": "",
        "minejumpeffects": "",
        "watereffectoffset": 0.45,
        "directionalexplosion": 0,
        "explosionangle": 60,
        "explosiondir": "explosionDir",
        "explosionpos": "explosionPos",
        "explosioneffectsdir": "explosionDir",
        "minimumsafezone": 0.1,
        "soundtrigger": [],
        "soundactivation": [],
        "sounddeactivation": [],
        "explosionsoundeffect": "",
        "mintimetolive": 0,
        "irlock": 0,
        "laserlock": 0,
        "nvlock": 0,
        "lockseekradius": 100,
        "manualcontrol": 0,
        "maxcontrolrange": 350,
        "maneuvrability": 1,
        "tracklead": 1,
        "trackoversteer": 1,
        "missilelockcone": 0,
        "weaponlocksystem": 0,
        "cmimmunity": 1,
        "locktype": 0,
        "maverickweaponindexoffset": 0,
        "sideairfriction": 1,
        "artillerydispersion": 1,
        "artillerycharge": 1,
        "autoseektarget": 0,
        "shootdistraction": -1,
        "explosiontime": 0,
        "fusedistance": 0,
        "inittime": 0,
        "thrusttime": 1.5,
        "thrust": 210,
        "icon": "",
        "explosiontype": "explosive",
        "minetrigger": "RangeTrigger",
        "mineboundingtime": 3,
        "mineboundingdist": 3,
        "mineinconspicuousness": 10,
        "minefloating": -1,
        "minedivespeed": 1,
        "mineplacedist": 0.5,
        # Class: CfgAmmo|Default|HitEffects [Indent level: 1],
        "hiteffects": {
            "vehicle": "ImpactMetal",
            "object": "ImpactConcrete"
        },
        "suppressionradiusbulletclose": -1,
        "suppressionradiushit": -1,
        "dangerradiusbulletclose": -1,
        "dangerradiushit": -1,
        "caliber": 1,
        "whistledist": 0,
        "whistleonfire": 0,
        # Class: CfgAmmo|Default|NVGMarkers [Indent level: 1],
        "nvgmarkers": {
        },
        "mindamageforcamshakehit": 0.55,
        # Class: CfgAmmo|Default|EventHandlers [Indent level: 1],
        "eventhandlers": {
        },
    },
    "eventhandlers": "rhs_ammo_127x108mm_1SLT",
    "displayname": "1SLT 12.7x108mm",
    "displaynameshort": "1SLT 12.7x108mm",
    "tracersevery": 1,
    "weight": 208.74,
    "initspeed": 735,
    "count": 1470,
    "maxleadspeed": 300,
    "scope": 2,
    "namesound": "mgun",
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadaction": "",
    "weaponpoolavailable": 0,
    "value": 1,
    "model": "A3|weapons_F|ammo|mag_univ.p3d",
    "picture": "",
    "modelspecial": "",
    "useaction": 0,
    "useactiontitle": "",
    "selectionfireanim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    # Class: CfgMagazines|Default|InventoryPlacements [Indent level: 1],
    "inventoryplacements": {
    },
    # Class: CfgMagazines|Default|Library [Indent level: 1],
    "library": {
        "libtextdesc": ""
    },
    "descriptionshort": "",
    "maxthrowholdtime": 2,
    "minthrowintensitycoef": 0.3,
    "maxthrowintensitycoef": 1.4,
    "quickreload": 0,
}