rhs_mag_3ubr6_195 = {
    "count": 195,
    "weight": 78,
    "displayName": "APBC-T 3UBR6",
    "displayNameShort": "3UBR6",
    "ammo": "rhs_ammo_3ubr6",
    "nameSound": "sabot",
    "tracersEvery": 3,
    "rhs_magazineIndex": 6,
    "maxLeadSpeed": 25,
    "initSpeed": 1120,
    "author": "Bohemia Interactive",
    "scope": 2,
    "muzzleImpulseFactor": [0.05,0.05],
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}