rhs_mag_9m113M = {
    "displayName": "ATGM 9M113M",
    "displayNameShort": "9M113M",
    "ammo": "rhs_ammo_9m113M",
    "scope": 2,
    "count": 1,
    "initSpeed": 80,
    "maxleadspeed": 80,
    "nameSound": "missiles",
    "rhs_magazineIndex": 4,
    "author": "Bohemia Interactive",
    "type": 0,
    "reloadAction": "",
    "weaponPoolAvailable": 0,
    "value": 1,
    "model": "\A3\weapons_F\ammo\mag_univ.p3d",
    "picture": "",
    "modelSpecial": "",
    "useAction": 0,
    "useActionTitle": "",
    "selectionFireAnim": "zasleh",
    "mass": 8,
    "simulation": "ProxyMagazines",
    "weight": 0,
    "descriptionShort": "",
    "maxThrowHoldTime": 2,
    "minThrowIntensityCoef": 0.3,
    "maxThrowIntensityCoef": 1.4,
    "quickReload": 0
}